lovesegfault/nix-config

flake.lock

| SHA256                                                                                            | Commit Message                        |
| ------------------------------------------------------------------------------------------------- | ------------------------------------- |
| [`f1630254`](https://github.com/yaxitech/ragenix/commit/f1630254a8814397c461467d551f58a039101122) | `Disable jsonschema default features` |

chore(flake/ragenix): `71147db3` -> `f0d6249c`

---

flake.lock

| SHA256                                                                                            | Commit Message                 |
| ------------------------------------------------------------------------------------------------- | ------------------------------ |
| [`022f9486`](https://github.com/yaxitech/ragenix/commit/022f948660a2b8cd9ab537b237827ae08e439375) | `Add ragenix(1) manpage (#83)` |

chore(flake/ragenix): `23fb4b6e` -> `022f9486`

---

flake.lock

| SHA256                                                                                                      | Commit Message                              |
| [`64ab7d6e`](https://github.com/nix-community/home-manager/commit/64ab7d6e8d157848ec285cd267db29e2f14c1076) | `Prepare inclusion in nixos-search (#2971)` |

chore(flake/home-manager): `20703892` -> `64ab7d6e`

---

flake.lock

| SHA256                                                                                                      | Commit Message                                            |
| [`95505955`](https://github.com/nix-community/home-manager/commit/9550595502bf437be7eb32f312a924ec891872d1) | `docs,tests: fetch nmd and nmt using fetchTarball`        |
| [`0434f8e4`](https://github.com/nix-community/home-manager/commit/0434f8e4cab4f200c9b4d3741a9e5d89705e6754) | `integration-common: set hmModule's description directly` |
| [`0ca0b910`](https://github.com/nix-community/home-manager/commit/0ca0b91088a462d4cac888baad3c3732d6dedb51) | …

chore(flake/home-manager): `1dbac84b` -> `95505955`

---

flake.lock
nix/checks.nix

| SHA256                                                                                                       | Commit Message                                                       |
| ------------------------------------------------------------------------------------------------------------ | -------------------------------------------------------------------- |
| [`e48619d6`](https://github.com/cachix/pre-commit-hooks.nix/commit/e48619d65be73a2fc1c80ea5c3036b3c5c31caa2) | `fix(nix/tools): get chktex, latexindent from texlive.scheme-medium` |
| [`b29df527`](https://github.com/cachix/pre-commit-hooks.nix/commit/b29df5277e316f2c8845532c49c6a9d03d449485) | `style(nix/tools): also sort inherits and callPackage lines`         |
| [`b35118da`](https://github.com/cachix/pre-commit-hooks.nix/co …

chore(flake/pre-commit-hooks): `60cad1a3` -> `2a4f1cfa`

---

flake.lock

| [`118a9f79`](https://github.com/nix-community/home-manager/commit/118a9f79fd45748ec4a7c9dd17e04aec08e0d070) | `` Translate using Weblate (Japanese) ``         |
| [`dd6c5acd`](https://github.com/nix-community/home-manager/commit/dd6c5acd86e8a05b7dde00c8149c522fa6312c2e) | `` Translate using Weblate (Ukrainian) ``        |
| [`7783e1b9`](https://github.com/nix-community/home-manager/commit/7783e1b949f84d8d7a1c2e146f2bfa504b7f41db) | `` Add translation using Weblate …

chore(flake/home-manager): `bf5712c5` -> `46f637bd`

---

flake.lock
users/bemeurer/graphical/darwin.nix
users/bemeurer/graphical/linux.nix

- chore(flake/stylix): ba5565d6 -> dcf3bcf0
- fix(users/bemeurer/graphical/linux): disable stylix KDE integration
- fix(users/bemeurer/graphical/darwin): disable stylix KDE integration

fix: stylix

---

flake.lock

| Commit                                                                                                    | Message                                                                          |
| --------------------------------------------------------------------------------------------------------- | -------------------------------------------------------------------------------- |
| [`0109e357`](https://github.com/nix-community/lanzaboote/commit/0109e357aa8005fd1600c05d2711f393fa6da35e) | `` Revert "Merge pull request #147 from nix-community/nixpkgs-infrastructure" `` |

chore(flake/lanzaboote): `f1384860` -> `6d6cdf59`

---

flake.lock

| [`b76899f4`](https://github.com/ryantm/agenix/commit/b76899f4c177fcf901e90704aa472f15d7c83cae) | `` Update nix installer ``                                                |
| [`7f30f9b4`](https://github.com/ryantm/agenix/commit/7f30f9b4b31219407fb0d7a536da3fdcbf151727) | `` Revert "dev: try switching to determinate systems installer action" `` |

chore(flake/agenix): `da5d6f05` -> `572baca9`

---

flake.lock

| Commit                                                                                                       | Message                                          |
| ------------------------------------------------------------------------------------------------------------ | ------------------------------------------------ |
| [`9a3ff337`](https://github.com/cachix/pre-commit-hooks.nix/commit/9a3ff3372d84f1d6cc5b071e9ada558dec2e4bf9) | `` Add beautysh ``                               |
| [`da3d9e32`](https://github.com/cachix/pre-commit-hooks.nix/commit/da3d9e32bbd717ccbf15996d4b085d66c905f09b) | `` Add options for eclint hook ``                |
| [`541e43e3`](https://github.com/cachix/pre-commit-hooks.nix/commit/541e43e30b449719db458269b3fa4c4a9e490877) | `` fix(pre-commit-run): Remove …

chore(flake/pre-commit-hooks): `66c352d3` -> `8edf336c`

---

.github/workflows/ci.yaml
flake.lock
flake.nix

- fix(flake): temporarily switch to stylix fork to avoid IFD
- ci: disallow IFD

fix: remove all IFD

---

.github/workflows/ci.yaml
nix/darwin.nix
nix/home-manager.nix
nix/nixos.nix

- fix(nix/nixos): remove recurseIntoAttrs
- fix(nix/darwin): remove recurseIntoAttrs
- fix(nix/home-manager): remove recurseIntoAttrs
- ci: run full nix flake check

ci: full nix flake check

---

flake.lock

| [`752d2d43`](https://github.com/nix-community/lanzaboote/commit/752d2d4347129418d926cba654cd8273d8375ec7) | `` fix(deps): update all dependencies `` |

chore(flake/lanzaboote): `81975f3b` -> `f8d26384`

---

flake.lock

| [`17a452c5`](https://github.com/danth/stylix/commit/17a452c5d58bb90057d49c7e3e613b5e6dc1c0f4) | `` Remove repetition of Waybar CSS (#192) `` |

chore(flake/stylix): `8b3f6172` -> `17a452c5`

---

flake.lock

| [`7b7fcbce`](https://github.com/nix-community/lanzaboote/commit/7b7fcbce58e335240d51b9030b8f54aa1cb99851) | `` fix(deps): update all dependencies `` |

chore(flake/lanzaboote): `5655251a` -> `9186a778`

---

flake.lock

| Commit                                                                                           | Message                           |
| ------------------------------------------------------------------------------------------------ | --------------------------------- |
| [`4a4542ba`](https://github.com/LnL7/nix-darwin/commit/4a4542ba8963f8be02c3b7aeab9197d04b070fd0) | `` Adding test ``                 |
| [`6c407989`](https://github.com/LnL7/nix-darwin/commit/6c407989348618d0349400e25fd9b1c47058fda2) | `` Adding reduce motion option `` |

chore(flake/darwin): `1a41453c` -> `0dd382b7`

---

flake.lock

| [`7b5a9140`](https://github.com/nix-community/lanzaboote/commit/7b5a91408f14d49a69bd549172f9326a133e6306) | `` Revert "chore(deps): lock file maintenance" `` |
| [`57e329ff`](https://github.com/nix-community/lanzaboote/commit/57e329ffde6278ab9adc7e2c6f94cd7b2da68807) | `` chore(deps): lock file maintenance ``          |
| [`82898a7c`](https://github.com/nix-community/lanzaboote/commit/82898a7c31303d966c5553abce7934a782c6c2f3) | `` fix(deps): update all dependencies `` …

chore(flake/lanzaboote): `7b91a7a3` -> `df553744`

---

flake.lock

| Commit                                                                                                   | Message                                       |
| -------------------------------------------------------------------------------------------------------- | --------------------------------------------- |
| [`238b0dc9`](https://github.com/hercules-ci/flake-parts/commit/238b0dc94b068a32530e8675425d22753d4af343) | `` apps: Add polyfill ``                      |
| [`562a6b5e`](https://github.com/hercules-ci/flake-parts/commit/562a6b5e54193e32c9819903c166cf211072e46c) | `` dev: Test apps ``                          |
| [`acd542d1`](https://github.com/hercules-ci/flake-parts/commit/acd542d16b086b2aeb823c090bf6121e7a1af12b) | `` apps: use lib.getExe to find executable `` |

chore(flake/flake-parts): `07f63952` -> `bffc4be1`

---

flake.lock

| [`bbab50dd`](https://github.com/nix-community/lanzaboote/commit/bbab50ddcddd5c990f614c694ac1a42b3192b89e) | `` chore(deps): lock file maintenance `` |
| [`9e20be5e`](https://github.com/nix-community/lanzaboote/commit/9e20be5eed5053f7278834ea945369d846ec63fc) | `` fix(deps): update all dependencies `` |

chore(flake/lanzaboote): `c42edac7` -> `f2bc0af5`

---

flake.lock

| [`53fc3ad7`](https://github.com/nix-community/lanzaboote/commit/53fc3ad7fb1248aa9b985c7d17a5b8ae1f44ed49) | `` fix(deps): update all dependencies `` |

chore(flake/lanzaboote): `f2bc0af5` -> `d9ec678b`

---

flake.lock

| [`78374106`](https://github.com/nix-community/lanzaboote/commit/78374106eae28013c28950fcd680f1059e6b99ff) | `` fix(deps): update all dependencies `` |

chore(flake/lanzaboote): `470ba03c` -> `73fec693`

---

flake.lock

| [`1d4df708`](https://github.com/nix-community/lanzaboote/commit/1d4df708bd6f4435d5b490af9ca7114b37c6f1d0) | `` fix(deps): update all dependencies `` |

chore(flake/lanzaboote): `eeb45682` -> `7fbb67b4`

---

flake.lock

| [`f8eaaa02`](https://github.com/nix-community/lanzaboote/commit/f8eaaa02a6cf9e9cff1e6145ae6ae499f0740811) | `` chore(deps): lock file maintenance `` |

chore(flake/lanzaboote): `7fbb67b4` -> `3881267e`

---

flake.lock

| Commit                                                                                           | Message                |
| ------------------------------------------------------------------------------------------------ | ---------------------- |
| [`c18685e7`](https://github.com/LnL7/nix-darwin/commit/c18685e7737ce942d94f15db4f2c80f53f1c11cd) | `` update README.md `` |

chore(flake/darwin): `c7ae5dc9` -> `d9ea313b`

---

flake.lock

| [`5a3b42c6`](https://github.com/nix-community/lanzaboote/commit/5a3b42c61af0f12beace14bedd2a5081565ed04c) | `` fix(deps): update all dependencies `` |

chore(flake/lanzaboote): `d67e1cc1` -> `df7ac26b`

---

flake.lock

| Commit                                                                                                | Message                        |
| ----------------------------------------------------------------------------------------------------- | ------------------------------ |
| [`1d744bb4`](https://github.com/cachix/git-hooks.nix/commit/1d744bb4e578c681b0c468924dc9a67ec52990e1) | `` Remove trailing new line `` |
| [`fa4b9ef8`](https://github.com/cachix/git-hooks.nix/commit/fa4b9ef890fee95125163c1f7a1df39217b1c6c6) | `` Add Poetry hooks ``         |

chore(flake/pre-commit-hooks): `c11e43ae` -> `9fc61b5e`

---

flake.lock

| Commit                                                                                         | Message                      |
| ---------------------------------------------------------------------------------------------- | ---------------------------- |
| [`4e8e6b07`](https://github.com/github/gemoji/commit/4e8e6b07eb38288988e09869f308814708d6c8fd) | `` Create dependabot.yaml `` |

chore(flake/gemoji): `5476a66d` -> `0eca75db`

---

flake.lock

| [`afb1af06`](https://github.com/nix-community/lanzaboote/commit/afb1af06377ce43d4e05f67c6151ab0ff512f942) | `` fix(deps): update all dependencies `` |

chore(flake/lanzaboote): `850f2732` -> `2eb19b87`

---

flake.lock

| [`66b68332`](https://github.com/cachix/git-hooks.nix/commit/66b68332893bedc1a1c05629cc4836cee21101e9) | `` chore(deps): update cachix/cachix-action action to v15 `` |
| [`250a88b6`](https://github.com/cachix/git-hooks.nix/commit/250a88b62c3b629be27b07ccc28eaf81021a9e6c) | `` chore(deps): update actions/checkout action to v4 ``      |
| [`df3ac191`](https://github.com/cachix/git-hooks.nix/commit/df3ac1917f9fdf993a5b925cbde0428838831452) | `` dev: fix typo …

chore(flake/git-hooks): `97c0dc86` -> `e4ea49a8`

---

flake.lock

| Commit                                                                                                | Message                 |
| ----------------------------------------------------------------------------------------------------- | ----------------------- |
| [`2c2eb0d4`](https://github.com/cachix/git-hooks.nix/commit/2c2eb0d42ef93f85d151a7ecff840cd78a7d9893) | `` Update Ruff check `` |

chore(flake/git-hooks): `622291c0` -> `f451c193`

---

flake.lock

| [`1520d675`](https://github.com/lovesegfault/vim-config/commit/1520d675df7ee9ca6afd39ce3ac849677ae886f0) | `` chore(flake/nixvim): ebd2182b -> 00f32f04 ``    |
| [`d1d50d25`](https://github.com/lovesegfault/vim-config/commit/d1d50d25f05a4c0e6c425115a714046fb3a04c84) | `` chore(flake/git-hooks): c7012d0c -> bfef0ada `` |

chore(flake/lovesegfault-vim-config): `8b884663` -> `1520d675`

---

flake.lock

| [`a69de7d0`](https://github.com/lovesegfault/vim-config/commit/a69de7d0226e994d5c7fb1dc4c9afbf48ddbf97f) | `` chore(flake/nixvim): 312db6b6 -> 851edc8d ``    |
| [`afc9844b`](https://github.com/lovesegfault/vim-config/commit/afc9844b5b5642079e4136e1c236c2451401dfb4) | `` chore(flake/git-hooks): bfef0ada -> 1064a45e `` |

chore(flake/lovesegfault-vim-config): `07c51172` -> `a69de7d0`

---

flake.lock

| [`35af94ee`](https://github.com/lovesegfault/vim-config/commit/35af94eec822392707ec050a6cf7843c4b139c09) | `` chore(flake/nixvim): 1854d591 -> 4c8d3559 ``    |
| [`f2f5f248`](https://github.com/lovesegfault/vim-config/commit/f2f5f248443fb9af99f76c31495123e9f93fdbe4) | `` chore(flake/git-hooks): 6cedaa7c -> c8a54057 `` |

chore(flake/lovesegfault-vim-config): `293ab384` -> `35af94ee`

---

flake.lock

| [`d443fe59`](https://github.com/lovesegfault/vim-config/commit/d443fe59bfae7fcd8e367097d16237a383986bc6) | `` chore(flake/nixvim): 48141474 -> 70e9532e ``      |
| [`9d6119a5`](https://github.com/lovesegfault/vim-config/commit/9d6119a5ece59a07d909e02e3525e6a7b02a3ee0) | `` chore(flake/treefmt-nix): 070f8347 -> 3ffd842a `` |
| [`e78f6075`](https://github.com/lovesegfault/vim-config/commit/e78f6075ed5d43f0f364d1e0030325b985e838d0) | `` chore(flake/git-hooks): …

chore(flake/lovesegfault-vim-config): `74020a84` -> `d443fe59`

---

flake.lock

| [`b819b6c7`](https://github.com/lovesegfault/vim-config/commit/b819b6c74fdd248ee43fce3f1d0ac046a20348d1) | `` chore(flake/treefmt-nix): 41266e63 -> ee41a466 `` |
| [`9852619a`](https://github.com/lovesegfault/vim-config/commit/9852619a5b1a58920eef244a3a23e8d4a725228c) | `` chore(flake/nixvim): 9307b201 -> 400d1d92 ``      |
| [`ffb9d499`](https://github.com/lovesegfault/vim-config/commit/ffb9d499749a6a54c9df9162650999cd45618432) | `` chore(flake/git-hooks): …

chore(flake/lovesegfault-vim-config): `93a5b01a` -> `b819b6c7`

---

flake.lock

| [`e3fd2b06`](https://github.com/lovesegfault/vim-config/commit/e3fd2b066b175919d3cb39f9bfb252f697d99b5b) | `` chore(flake/nixvim): 5f4a4b47 -> 0ca98d02 ``    |
| [`f7a18537`](https://github.com/lovesegfault/vim-config/commit/f7a1853749093aa1b5e9907887e32fa6618f3795) | `` chore(flake/git-hooks): 2f5ae3fc -> 5f58871c `` |

chore(flake/lovesegfault-vim-config): `7de959be` -> `e3fd2b06`

---

flake.lock

| [`0a699ae9`](https://github.com/lovesegfault/vim-config/commit/0a699ae93b310bf44946f9892e37adb1938f56f4) | `` chore(flake/git-hooks): 4ebefcac -> 06bb5971 `` |
| [`29c3b279`](https://github.com/lovesegfault/vim-config/commit/29c3b279e25fb26b8c2e6b1c69825283b9e679b1) | `` chore(flake/nixvim): af650ba9 -> 5cd8c9cf ``    |

chore(flake/lovesegfault-vim-config): `f00157ca` -> `0a699ae9`

---

flake.lock

| [`edc4ba82`](https://github.com/lovesegfault/vim-config/commit/edc4ba82e30d31c642284b4a466f3ed94c03ab27) | `` chore(flake/git-hooks): 06bb5971 -> eb74e0be `` |
| [`83303d40`](https://github.com/lovesegfault/vim-config/commit/83303d402d932b43816d718081b0890d517cb140) | `` chore(flake/nixvim): 5cd8c9cf -> 2e1b3b7d ``    |

chore(flake/lovesegfault-vim-config): `0a699ae9` -> `edc4ba82`

---

flake.lock

| [`681c87d2`](https://github.com/lovesegfault/vim-config/commit/681c87d238219039333721ef963126fcc84a4104) | `` chore(flake/git-hooks): ff68f917 -> 3c3e88f0 ``   |
| [`bc729752`](https://github.com/lovesegfault/vim-config/commit/bc729752d7c939e71bad565a6187042e633f5067) | `` chore(flake/nixvim): 429f2e8d -> 717e7060 ``      |
| [`60d94d28`](https://github.com/lovesegfault/vim-config/commit/60d94d28ba5d370d955f1ad1ff895999ed58beee) | `` chore(flake/treefmt-nix): …

chore(flake/lovesegfault-vim-config): `b1eff05d` -> `681c87d2`

---

flake.lock

| [`fdfbb222`](https://github.com/lovesegfault/vim-config/commit/fdfbb2229658320e3c9673ca8cf5a40145a25645) | `` chore(flake/nixvim): 029eafd7 -> 4726334e ``             |
| [`a6628990`](https://github.com/lovesegfault/vim-config/commit/a662899035991965244de387dc0bfe164736e53f) | `` chore(flake/nix-github-actions): 622f829f -> e04df33f `` |

chore(flake/lovesegfault-vim-config): `43d1e9c2` -> `fdfbb222`

---

flake.lock

| [`0318fde2`](https://github.com/nix-community/lanzaboote/commit/0318fde24299eee3ad1a764590621284bfc030e8) | `` fix(deps): update all dependencies `` |
| [`2572569c`](https://github.com/nix-community/lanzaboote/commit/2572569cf9742f7bd66702cb1ecff0162a7de708) | `` chore(deps): lock file maintenance `` |

chore(flake/lanzaboote): `2fa1368f` -> `e3978795`

---

flake.lock

| [`de430e77`](https://github.com/nix-community/lanzaboote/commit/de430e77cbd68e109aca302a5c0b3870e20c21b6) | `` chore(deps): lock file maintenance `` |

chore(flake/lanzaboote): `0ad4ce46` -> `cef39a78`

---

flake.lock

| [`d3e53c97`](https://github.com/lovesegfault/vim-config/commit/d3e53c97a98034731ed04f5f6329da59c98dee87) | `` chore(flake/nixvim): e680b367 -> 78bfbf7b ``      |
| [`ae60c6db`](https://github.com/lovesegfault/vim-config/commit/ae60c6db136afe6984dad78cd25b766ba8b349e6) | `` chore(flake/treefmt-nix): 6209c381 -> 49717b5a `` |
| [`18e63945`](https://github.com/lovesegfault/vim-config/commit/18e639452a7c7fb3a5093190eadc4e7296aff8d9) | `` chore(flake/flake-parts): …

chore(flake/lovesegfault-vim-config): `fd814511` -> `d3e53c97`

---

flake.lock

| [`f22e494d`](https://github.com/lovesegfault/vim-config/commit/f22e494d8c9bb260ef3cb1fb03835d2f2287f6bc) | `` chore(flake/nixvim): 08be2027 -> 4b5364a6 ``      |
| [`db6ce48d`](https://github.com/lovesegfault/vim-config/commit/db6ce48d69479406ea77c791104ac1a35846c134) | `` chore(flake/git-hooks): 6f4e2a21 -> d8c02f0f ``   |
| [`cb39edb5`](https://github.com/lovesegfault/vim-config/commit/cb39edb5836cd249754d6caec61ec8cf21e14dc0) | `` chore(flake/treefmt-nix): …

chore(flake/lovesegfault-vim-config): `1e2579b8` -> `f22e494d`

---

flake.lock

| [`6b1c7653`](https://github.com/lovesegfault/vim-config/commit/6b1c7653725c6297441c19a23d54e8ac13ff70b3) | `` chore(flake/nixvim): c1810144 -> c351af10 ``    |
| [`a7450f19`](https://github.com/lovesegfault/vim-config/commit/a7450f19a427dd0b7b764afa0be38db046bda590) | `` chore(flake/git-hooks): d8c02f0f -> c2b3567b `` |

chore(flake/lovesegfault-vim-config): `07f6d67f` -> `6b1c7653`

---

flake.lock

| [`e267046a`](https://github.com/lovesegfault/vim-config/commit/e267046aebe98d4c34567306cbbbb8087a316d11) | `` chore(flake/nixpkgs): 5d67ea6b -> 3566ab72 ``   |
| [`8a07a23f`](https://github.com/lovesegfault/vim-config/commit/8a07a23ff142e7c5c2534a7c2e68a726a00c547b) | `` chore(flake/git-hooks): c2b3567b -> aa9f40c9 `` |
| [`c537d242`](https://github.com/lovesegfault/vim-config/commit/c537d242663376e0f936d9f7fa6fa884b361d9f6) | `` chore(flake/nixvim): c351af10 -> …

chore(flake/lovesegfault-vim-config): `6b1c7653` -> `e267046a`

---

flake.lock

| [`51f63792`](https://github.com/nix-community/lanzaboote/commit/51f6379241b58a88773b6a0236030203b6102c63) | `` fix(deps): update all dependencies `` |
| [`daebba6e`](https://github.com/nix-community/lanzaboote/commit/daebba6eb5137beae490289d0436fcb9281915fc) | `` chore(deps): lock file maintenance `` |

chore(flake/lanzaboote): `2f48272f` -> `26a59c1b`

---

flake.lock

| [`c7d2d3aa`](https://github.com/lovesegfault/vim-config/commit/c7d2d3aa8d0b4d36e385e815493d7f93d91e77d4) | `` chore(flake/nixvim): cbf960e5 -> 8fb2fe22 ``    |
| [`178b6f69`](https://github.com/lovesegfault/vim-config/commit/178b6f69c32c71dd4434c80d3eb35f8bbe1f08f3) | `` chore(flake/git-hooks): 94ee657f -> 15a87ced `` |

chore(flake/lovesegfault-vim-config): `ee5bbd95` -> `c7d2d3aa`

---

flake.lock

| [`a9fe6398`](https://github.com/lovesegfault/vim-config/commit/a9fe63981950e41bfbaa10cd7920c4b987a452a8) | `` chore(flake/nixvim): 115994f1 -> 342161bf ``    |
| [`a18d9b60`](https://github.com/lovesegfault/vim-config/commit/a18d9b607baa089185ed674d027e4e89e2f3f644) | `` chore(flake/git-hooks): 15a87ced -> 9364dc02 `` |

chore(flake/lovesegfault-vim-config): `1b761e38` -> `a9fe6398`

---

flake.lock

| Commit                                                                                        | Message                      |
| --------------------------------------------------------------------------------------------- | ---------------------------- |
| [`d8289c3f`](https://github.com/danth/stylix/commit/d8289c3f0e5995863921ea207392c122f5d59f6d) | `` ci: disable IFD (#855) `` |

chore(flake/stylix): `4af2686c` -> `d8289c3f`

---

flake.lock

| Commit                                                                                        | Message                                   |
| --------------------------------------------------------------------------------------------- | ----------------------------------------- |
| [`aeb550ad`](https://github.com/danth/stylix/commit/aeb550add3bfa1ce3ce249c3b3dad71ebb018318) | `` doc: remove site-url setting (#878) `` |

chore(flake/stylix): `eb7b19c2` -> `aeb550ad`

---

flake.lock

| [`6b783278`](https://github.com/lovesegfault/vim-config/commit/6b78327885c226de68bd0b8890abf5535172f87a) | `` chore(flake/nixpkgs): 32fb99ba -> 0196c017 `` |
| [`b1f83c11`](https://github.com/lovesegfault/vim-config/commit/b1f83c11edfe66ccb0e0b29cba5872050b149073) | `` chore(flake/nixvim): 0ab99471 -> 53f9d242 ``  |

chore(flake/lovesegfault-vim-config): `f1c95c76` -> `6b783278`

---

flake.lock

| [`effd09a7`](https://github.com/lovesegfault/vim-config/commit/effd09a707fded4eb90a53ffca12654ac0d629eb) | `` chore(flake/nixvim): 6f8d8f7a -> 03065fd4 ``    |
| [`0c3bf90a`](https://github.com/lovesegfault/vim-config/commit/0c3bf90aee56aaad3220325ef634e1a6624b909c) | `` chore(flake/git-hooks): 25d4946d -> 42b1ba08 `` |

chore(flake/lovesegfault-vim-config): `665bf10a` -> `effd09a7`

---

flake.lock

| Commit                                                                                                  | Message                                   |
| ------------------------------------------------------------------------------------------------------- | ----------------------------------------- |
| [`47c8c772`](https://github.com/tinted-theming/schemes/commit/47c8c7726e98069cade5827e5fb2bfee02ce6991) | `` Add slugs to Rose Pine themes (#43) `` |

chore(flake/tinted-schemes): `a1bc2bd8` -> `47c8c772`

---

flake.lock

| Commit                                                                                                  | Message                          |
| ------------------------------------------------------------------------------------------------------- | -------------------------------- |
| [`4ff7fe1c`](https://github.com/tinted-theming/schemes/commit/4ff7fe1cf77217393ed0981a1de314f418c28b49) | `` Rename .yml to .yaml (#45) `` |

chore(flake/tinted-schemes): `d4a7c5b6` -> `4ff7fe1c`

---

flake.lock

| [`886ddaa7`](https://github.com/lovesegfault/vim-config/commit/886ddaa7da253e8abee661bf29ff423d6d5a53a0) | `` chore(flake/git-hooks): b5a62751 -> 59f17850 `` |
| [`809c3830`](https://github.com/lovesegfault/vim-config/commit/809c38309c27c46b42daeb570ece66011186d2a8) | `` chore(flake/nixvim): 3a3abf11 -> 33097dcf ``    |

chore(flake/lovesegfault-vim-config): `db8307ee` -> `886ddaa7`

---

flake.lock

| [`60b47d7e`](https://github.com/lovesegfault/vim-config/commit/60b47d7eeb7109ca2fd2ee33fe42866490cb72d0) | `` chore(flake/git-hooks): ea26a82d -> dcf50727 `` |
| [`e1987eb6`](https://github.com/lovesegfault/vim-config/commit/e1987eb6dca55e3fa404a970d37d941a3fd8c7c7) | `` chore(flake/nixvim): c9802712 -> 3d84c137 ``    |

chore(flake/lovesegfault-vim-config): `cbbe5aa8` -> `60b47d7e`

---

flake.lock
hosts/spinoza/default.nix
users/bemeurer/graphical/firefox.nix

| Commit                                                                                        | Message                                                                              |
| --------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------ |
| [`d9df91c5`](https://github.com/danth/stylix/commit/d9df91c55643a8b5229a3ae3a496a30f14965457) | `` vscode: theme default profile by default (#1015) ``                               |
| [`a55488c2`](https://github.com/danth/stylix/commit/a55488c247928380ee6a18c0a3a56a2d52fe06bc) | `` doc: reduce overuse of alerts (#1041) ``                                          |
| …

chore(flake/stylix): `08e0c91d` -> `d9df91c5`

---

flake.lock

| Commit                                                                                                  | Message                                           |
| ------------------------------------------------------------------------------------------------------- | ------------------------------------------------- |
| [`c37771c4`](https://github.com/tinted-theming/schemes/commit/c37771c4ae8ff1667e27ddcf24991ebeb94a4e77) | `` update windows author to current name (#47) `` |

chore(flake/tinted-schemes): `4ff7fe1c` -> `c37771c4`

---

flake.lock

| Commit                                                                                        | Message                                                      |
| --------------------------------------------------------------------------------------------- | ------------------------------------------------------------ |
| [`9a3fb931`](https://github.com/danth/stylix/commit/9a3fb931fdfc5d6be48dc3c90fe775aada78efba) | `` stylix: update all flake inputs ``                        |
| [`bb8af4c6`](https://github.com/danth/stylix/commit/bb8af4c6580168cd59660a34c463d26f92078288) | `` ci: skip adding Cachix for flake updates (#1108) ``       |
| [`2cdfff25`](https://github.com/danth/stylix/commit/2cdfff2575fdec2741b8a3dda44fcb984372187b) | `` ci: run flake update on stable release (#1105) `` …

chore(flake/stylix): `581fa67c` -> `9a3fb931`

---

flake.lock

| [`d2c6d1e5`](https://github.com/lovesegfault/vim-config/commit/d2c6d1e5725da30a9176330eef1a7717aaa9223b) | `` chore(flake/git-hooks): fa466640 -> 80479b6e ``   |
| [`f0a2e53e`](https://github.com/lovesegfault/vim-config/commit/f0a2e53e6ecc85592c407a568aa9ad1e4f223628) | `` chore(flake/treefmt-nix): e758f274 -> 42dd9289 `` |
| [`63821fa0`](https://github.com/lovesegfault/vim-config/commit/63821fa0ab11c3d5433af3b46f169d6e8f260bce) | `` chore(flake/nixvim): 95ca65c8 …

chore(flake/lovesegfault-vim-config): `019385d2` -> `d2c6d1e5`

---

flake.lock

| Commit                                                                                                  | Message                               |
| ------------------------------------------------------------------------------------------------------- | ------------------------------------- |
| [`b15ea410`](https://github.com/tinted-theming/schemes/commit/b15ea410ff2091a064a92d0f6b8bae80a2f27798) | `` Add base24 mountain theme (#62) `` |

chore(flake/tinted-schemes): `de3eeb6a` -> `b15ea410`

---

flake.lock

| [`aceb7d8d`](https://github.com/lovesegfault/vim-config/commit/aceb7d8dcfb401a80f043d98a6349a16018c8ebd) | `` chore(flake/git-hooks): 623c5628 -> fae816c5 `` |
| [`b97d6220`](https://github.com/lovesegfault/vim-config/commit/b97d62207a80e0d3a47d3547f82a8ec3ac3fd8e8) | `` chore(flake/nixvim): d2c3b26b -> 1f3e5741 ``    |

chore(flake/lovesegfault-vim-config): `74d21213` -> `aceb7d8d`

---

flake.lock

| [`b1a84f89`](https://github.com/nix-community/stylix/commit/b1a84f898284de362536a91efaa4c0cd6b338973) | `` fnott: rename progress-bar-color setting to progress-color (#1872) `` |
| [`0e7b897c`](https://github.com/nix-community/stylix/commit/0e7b897c73c5dfe4651696953f1131d179625c7a) | `` flake: update all inputs (#1881) ``                                   |

chore(flake/stylix): `5c34e203` -> `b1a84f89`

---

flake.lock

| Commit                                                                                                  | Message                                          |
| ------------------------------------------------------------------------------------------------------- | ------------------------------------------------ |
| [`317a5e10`](https://github.com/tinted-theming/schemes/commit/317a5e10c35825a6c905d912e480dfe8e71c7559) | `` Add base24 version of tomorrow-night (#71) `` |

chore(flake/tinted-schemes): `d4cf913a` -> `317a5e10`

---

flake.lock

| [`472fc5e6`](https://github.com/lovesegfault/vim-config/commit/472fc5e68941d83c14a96c7ae8370997c4bf1712) | `` chore(flake/git-hooks): 54df955a -> cfc9f7bb `` |
| [`64b9bcf2`](https://github.com/lovesegfault/vim-config/commit/64b9bcf23cc170c1b07ae857c9beda4a5a65baec) | `` chore(flake/nixvim): eb54f65d -> 42d87fd4 ``    |

chore(flake/lovesegfault-vim-config): `3f8246db` -> `472fc5e6`
