flake.lock
| [`571d0ed8`](https://github.com/nix-community/home-manager/commit/571d0ed82538ea11f9ed4451fae892d9de8c3cc7) | `` flake.lock: Update ``                            |
| [`8506c692`](https://github.com/nix-community/home-manager/commit/8506c6922293877476a64ddb93b7484b3da7788c) | `` home-manager: quote username in init template `` |
=> chore(flake/home-manager): `cc05d263` -> `571d0ed8`

flake.lock
| [`73ab8e0d`](https://github.com/LnL7/nix-darwin/commit/73ab8e0d702c9cdda3a92ba3ff95024ff2e70448) | `` Add/fix some launchd.plist options ``        |
| [`90b36a5e`](https://github.com/LnL7/nix-darwin/commit/90b36a5efe003a388451af2e0f41774bcdc0d658) | `` synergy: add options for TLS ``              |
| [`0cf7d413`](https://github.com/LnL7/nix-darwin/commit/0cf7d413898a975097a196e5ddb3f6a0f214234b) | `` fix(modules/fonts): ignore repeated fonts `` |
=> chore(flake/darwin): `02591252` -> `a1ee4d33`

flake.lock
| [`a1c5d01a`](https://github.com/danth/stylix/commit/a1c5d01a40ca65335925974741020fe8b217b7bd) | `` Add example configuration :memo: `` |
=> chore(flake/stylix): `936d97a0` -> `a1c5d01a`

flake.lock
| Commit                                                                                         | Message                                                                 |
| ---------------------------------------------------------------------------------------------- | ----------------------------------------------------------------------- |
| [`7f6a225a`](https://github.com/NixOS/nixpkgs/commit/7f6a225a6a0cebf108b7dca5a32650087849411b) | `` live555: 2023.01.19 -> 2023.03.30 ``                                 |
| [`29ae6a1f`](https://github.com/NixOS/nixpkgs/commit/29ae6a1f3d7a8886b3772df4dc42a13817875c7d) | `` deltachat-desktop: 1.36.2 -> 1.36.3 ``                               |
| [`213f6aa8`](https://github.com/NixOS/nixpkgs/commit/213f6aa82cd943cfd898d7db2669e9a0a0a6c7ab) | `` …
=> chore(flake/nixpkgs): `555daa9d` -> `645bc49f`

flake.lock
| Commit                                                                                              | Message                                                |
| --------------------------------------------------------------------------------------------------- | ------------------------------------------------------ |
| [`55aac55c`](https://github.com/serokell/deploy-rs/commit/55aac55cfafec93938e19a6b475142d81110b3d4) | `` [#197] Fix hostname overriding for remote builds `` |
=> chore(flake/deploy-rs): `8c9ea960` -> `c2ea4e64`

flake.lock
| [`342fd40c`](https://github.com/nix-community/home-manager/commit/342fd40ccb642736e7d4268f61befe14d71ce7a8) | `` home-manager: fix config file variable check (#3901) `` |
=> chore(flake/home-manager): `5160039e` -> `342fd40c`

flake.lock
| [`47d6c3f6`](https://github.com/nix-community/home-manager/commit/47d6c3f65234230d37f1cf7d3d6b5575ec80fe0c) | `` home-manager: fix variable name `` |
=> chore(flake/home-manager): `342fd40c` -> `47d6c3f6`

flake.lock
| Commit                                                                                         | Message                                                                  |
| ---------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------ |
| [`40550f06`](https://github.com/ryantm/agenix/commit/40550f0619ede64d49f0b531d356e271c875c6db) | `` fix truncated output when decrypting a large file to stdout via -d `` |
=> chore(flake/agenix): `e6496197` -> `0e3a237c`

flake.lock
| [`ecefdd8b`](https://github.com/danth/stylix/commit/ecefdd8b7d01885ceb40051be6948546b9d2f7ed) | `` Fix GNOME extensions app not launching :bug: `` |
=> chore(flake/stylix): `a1c5d01a` -> `ecefdd8b`

flake.lock
| Commit                                                                                         | Message                  |
| ---------------------------------------------------------------------------------------------- | ------------------------ |
| [`8722cf94`](https://github.com/ryantm/agenix/commit/8722cf94f15be0d907e52c595b548bc1052b803e) | `` doc: missing space `` |
=> chore(flake/agenix): `0e3a237c` -> `2994d002`

flake.lock
| [`38954690`](https://github.com/nix-community/home-manager/commit/3895469036e4f42ab4bb0482e18c3677e3fb12b1) | `` fnott: add D-Bus service file ``          |
| [`64d1f75a`](https://github.com/nix-community/home-manager/commit/64d1f75a1eda1e329f9f795578de10fad0fb82df) | `` herbstluftwm: fix default tag renaming `` |
| [`218503b6`](https://github.com/nix-community/home-manager/commit/218503b691d25d7df00644e775f4aab1e464d516) | `` zellij: use xdg.configHome on darwin ``   |
=> chore(flake/home-manager): `47d6c3f6` -> `38954690`

flake.lock
| [`6169690a`](https://github.com/nix-community/home-manager/commit/6169690ae38175295605d521bd778d999fbd85cd) | `` zsh: add `package` option to `oh-my-zsh` `` |
| [`5cd5a1b5`](https://github.com/nix-community/home-manager/commit/5cd5a1b58582b2d3b7c380a42890b5a464747005) | `` aerc: add oauth params ``                   |
=> chore(flake/home-manager): `38954690` -> `6169690a`

flake.lock
| [`32d3e39c`](https://github.com/nix-community/home-manager/commit/32d3e39c491e2f91152c84f8ad8b003420eab0a1) | `` neovim: enable tests on Darwin `` |
=> chore(flake/home-manager): `6169690a` -> `32d3e39c`

flake.lock
| [`170e9b10`](https://github.com/nix-community/impermanence/commit/170e9b105dc6e859c0039d3fa7bd6970954f87d8) | `` README: Add matrix room link ``                                       |
| [`b4160ba7`](https://github.com/nix-community/impermanence/commit/b4160ba71debd3f796a4b0ba0e0c680a96013d0d) | `` nixos: Rewrite directory creation for saner default permissions ``    |
| …
=> chore(flake/impermanence): `6138eb8e` -> `c3f7012d`

flake.lock
| [`6c43a349`](https://github.com/NixOS/nixpkgs/commit/6c43a3495a11e261e5f41e5d7eda2d71dae1b2fe) | `` linux_6_1: fixup evaluation without aliases ``                                 |
| [`ada2485f`](https://github.com/NixOS/nixpkgs/commit/ada2485ff397bc4adcae778bdfa0b242e8dcc4d4) | `` atari++: refactor ``                                                           |
| [`9fec09d9`](https://github.com/NixOS/nixpkgs/commit/9fec09d93cb2c …
=> chore(flake/nixpkgs): `645bc49f` -> `6c43a349`

flake.lock
| [`2d575226`](https://github.com/nix-community/impermanence/commit/2d575226bf87cb77d3c6cada0847ee7ee8d8571b) | `` nixos: Fix collision detection logic `` |
=> chore(flake/impermanence): `c3f7012d` -> `df1692e2`

flake.lock
| [`48ad7ade`](https://github.com/nix-community/home-manager/commit/48ad7ade11795dd10a095c68f6a4a4dcb339307b) | `` Translate using Weblate (Catalan) `` |
=> chore(flake/home-manager): `32d3e39c` -> `48ad7ade`

flake.lock
| [`e21ec3db`](https://github.com/nix-community/home-manager/commit/e21ec3db17c4b474f6bd9d8b967a3415fbc6b51d) | `` git: add delta.package option `` |
| [`5904f12d`](https://github.com/nix-community/home-manager/commit/5904f12d7d343929c8a09a9bbcbf3eb88c2e0a26) | `` flake.lock: Update ``            |
=> chore(flake/home-manager): `48ad7ade` -> `e21ec3db`

flake.lock
| [`a5a294a6`](https://github.com/nix-community/home-manager/commit/a5a294a622a7d3a837aaa145334e4d813c1bc5b1) | `` sway: import NIXOS_OZONE_WL into systemd `` |
=> chore(flake/home-manager): `e21ec3db` -> `a5a294a6`

flake.lock
| Commit                                                                                                       | Message                       |
| ------------------------------------------------------------------------------------------------------------ | ----------------------------- |
| [`5514a012`](https://github.com/cachix/pre-commit-hooks.nix/commit/5514a012fae43028263006fa66e73a7f16969e87) | `` Add hook for `dune fmt` `` |
| [`63131a6d`](https://github.com/cachix/pre-commit-hooks.nix/commit/63131a6dc6c129b49200908ab35099c2a4cc1d15) | `` Update hook description `` |
| [`871a56c3`](https://github.com/cachix/pre-commit-hooks.nix/commit/871a56c37ae559023b5c4de70197d5ec3d1081b6) | `` Update README file ``      |
| [`b17f6ad4`](https://github.com/cachix/pre-commit-hooks.nix/commit/b17f6a …
=> chore(flake/pre-commit-hooks): `b7ca8f6f` -> `56cd2d47`

flake.lock
| Commit                                                                                        | Message                             |
| --------------------------------------------------------------------------------------------- | ----------------------------------- |
| [`95fd9afe`](https://github.com/danth/stylix/commit/95fd9afebd690453ca9196cd7cf59db001e7da19) | `` Fix module name in docs (#91) `` |
=> chore(flake/stylix): `ecefdd8b` -> `95fd9afe`

flake.lock
| [`6f9781b1`](https://github.com/nix-community/home-manager/commit/6f9781b1b0cf3fedbe9d2d0a785aeec4d6085c10) | `` flake: Move tests back to devShells.*.tests (#3905) `` |
=> chore(flake/home-manager): `a5a294a6` -> `6f9781b1`

flake.lock
| [`75e62acf`](https://github.com/NixOS/nixpkgs/commit/75e62acf2e6f7e998ea913ac646d4596e9ca95d5) | `` jfrog-cli: 2.36.0 -> 2.36.1 ``                                         |
| [`5d91a896`](https://github.com/NixOS/nixpkgs/commit/5d91a896449650d13fbba8c8abc65d1615c2b654) | `` kalendar: Remove unused fetchFromGitLab ``                             |
| [`a5cbcee7`](https://github.com/NixOS/nixpkgs/commit/a5cbcee70b0a1e3711f41ffcb6b6ab64a22e080a) | …
=> chore(flake/nixpkgs): `6c43a349` -> `e78d25df`

flake.lock
| Commit                                                                                                      | Message                                                                                            |
| ----------------------------------------------------------------------------------------------------------- | -------------------------------------------------------------------------------------------------- |
| [`0263da49`](https://github.com/nix-community/home-manager/commit/0263da497eae3246ea15ed6f0f7875bc15592cef) | `` notmuch & neomutt: Control virtualboxes being set in NeoMutt for Notmuch integration (#3143) `` |
=> chore(flake/home-manager): `6f9781b1` -> `0263da49`

flake.lock
| [`61421936`](https://github.com/nix-community/home-manager/commit/6142193635ecdafb9a231bd7d1880b9b7b210d19) | `` atuin: Use flags option with nushell integration (#3917) `` |
=> chore(flake/home-manager): `0263da49` -> `61421936`

flake.lock
| Commit                                                                                                    | Message                |
| --------------------------------------------------------------------------------------------------------- | ---------------------- |
| [`47c65b4a`](https://github.com/Mic92/nix-index-database/commit/47c65b4a4f8c42a2461ef9a0ed9413bbeb8a097a) | `` Update README.md `` |
=> chore(flake/nix-index-database): `68ec961c` -> `e3e320b1`

flake.lock
| [`74a7d447`](https://github.com/NixOS/nixpkgs/commit/74a7d447b2164cfd273014cc374a8877fdc29045) | `` iptsd: 1.1.1 -> 1.2.0 ``                                                          |
| [`7509871f`](https://github.com/NixOS/nixpkgs/commit/7509871fea118c38e7342551254015f42868b544) | `` looseversion: init at 1.0.3 ``                                                    |
| …
=> chore(flake/nixpkgs): `e78d25df` -> `884ac294`

flake.lock
| [`f1f0ef95`](https://github.com/NixOS/nixpkgs/commit/f1f0ef95cc4b5eb6a30bda28bce1838819bb2a81) | `` tauri-mobile: init at unstable-2023-04-25 (#228178) ``                    |
| [`a7b0ff0a`](https://github.com/NixOS/nixpkgs/commit/a7b0ff0a0de9d5576fe15fa9083c933cfd430902) | `` bugdom,nanosaur,nanosaur2,otto-matic: add desktop files (#215525) ``      |
| [`c634094e`](https://github.com/NixOS/nixpkgs/commit/c634094e7b103b68935b8aae2e040819e …
=> chore(flake/nixpkgs): `884ac294` -> `c8018361`

flake.lock
| [`d82c9af8`](https://github.com/nix-community/home-manager/commit/d82c9af8175878a461a0fdf914e67cc446664570) | `` nixos: use `lib` argument instead of `pkgs.lib` (#3454) `` |
=> chore(flake/home-manager): `61421936` -> `d82c9af8`

flake.lock
| Commit                                                                                        | Message                                          |
| --------------------------------------------------------------------------------------------- | ------------------------------------------------ |
| [`bd1b9701`](https://github.com/danth/stylix/commit/bd1b9701155e5d46c057971f8f15db0aa604bc72) | `` vscode: Set editor and terminal font (#93) `` |
| [`906574cb`](https://github.com/danth/stylix/commit/906574cb375085193f22f0834f33c33c6307a836) | `` Fix markup on truth value (#94) ``            |
=> chore(flake/stylix): `95fd9afe` -> `bd1b9701`

flake.lock
| Commit                                                                                                       | Message                                                 |
| ------------------------------------------------------------------------------------------------------------ | ------------------------------------------------------- |
| [`e936545d`](https://github.com/cachix/pre-commit-hooks.nix/commit/e936545d520301a2f9e7deabb905d2a33a4a72bf) | `` Fix typo giving `dune-fmt`'s setting a wrong type `` |
=> chore(flake/pre-commit-hooks): `56cd2d47` -> `fb58866e`

flake.lock
| [`43ba4489`](https://github.com/nix-community/home-manager/commit/43ba4489bd3f9f69519f5f7ebdb76d0455eccbbe) | `` flake: unwrap devShells.*.tests `` |
=> chore(flake/home-manager): `d82c9af8` -> `43ba4489`

flake.lock
| [`c4f3a370`](https://github.com/nix-community/home-manager/commit/c4f3a3707104999d5b6fe4c4e5c3833980a92513) | `` jujutsu: add module `` |
=> chore(flake/home-manager): `f2d62911` -> `c4f3a370`

flake.lock
| [`27d89b49`](https://github.com/nix-community/home-manager/commit/27d89b49e3cd3c83b9609a6ff9173a9b8d2d9ad4) | `` zplug: Update the path of init.zsh (#3922) `` |
=> chore(flake/home-manager): `c4f3a370` -> `27d89b49`

flake.lock
| [`f873350a`](https://github.com/NixOS/nixpkgs/commit/f873350afdb4627f520161cf850007e102287c6c) | `` wio: remove ``                                                               |
| [`cfe96dbf`](https://github.com/NixOS/nixpkgs/commit/cfe96dbfce8bd62dcd4a8ad62cb79dec140b1a62) | `` python310Packages.blobfile: 2.0.1 -> 2.0.2 ``                                |
| [`1d1d5d27`](https://github.com/NixOS/nixpkgs/commit/1d1d5d272490cdb80e25e …
=> chore(flake/nixpkgs): `d6b863fd` -> `937a9d1e`

flake.lock
| Commit                                                                                        | Message                                                      |
| --------------------------------------------------------------------------------------------- | ------------------------------------------------------------ |
| [`76a8050a`](https://github.com/danth/stylix/commit/76a8050ab2bf1f34e219e78f6b3d55a37870581f) | `` Add option to disable animation in Plymouth :sparkles: `` |
=> chore(flake/stylix): `bd1b9701` -> `76a8050a`

flake.lock
| [`3144311f`](https://github.com/nix-community/home-manager/commit/3144311f31194b537808ae6848f86f3dbf977d59) | `` zsh: allow multiple bindings to history-substring-search (#3929) `` |
=> chore(flake/home-manager): `27d89b49` -> `3144311f`

flake.lock
| [`0cfe2552`](https://github.com/NixOS/nixos-hardware/commit/0cfe255229e2f617377feaceb3e890d9cf884125) | `` starfive visionfive2: update kernel ``                |
| [`b0fd9625`](https://github.com/NixOS/nixos-hardware/commit/b0fd96252521a42c2c691c7eb0fffb958b6f49b4) | `` starfive visionfive2: update u-boot ``                |
| [`2ce2f3f9`](https://github.com/NixOS/nixos-hardware/commit/2ce2f3f9789a24f4ddd7f925b7b5f67ec8920e33) | `` starfive visionfive2: fix …
=> chore(flake/nixos-hardware): `3006d286` -> `e4a21ddc`

flake.lock
| [`67a6315b`](https://github.com/NixOS/nixpkgs/commit/67a6315ba873f60d93d26631256df497c39cf8a9) | `` vkd3d-proton: init at unstable-2023-04-21 ``                               |
| [`7d7d95d8`](https://github.com/NixOS/nixpkgs/commit/7d7d95d871f35d3d8e54ce705d9ae665227daa9e) | `` vkd3d: init at 1.7 ``                                                      |
| [`99fa5c68`](https://github.com/NixOS/nixpkgs/commit/99fa5c68cab8434d6eabe500d588f …
=> chore(flake/nixpkgs): `937a9d1e` -> `08e4dc3a`

flake.lock
| [`fcc22971`](https://github.com/NixOS/nixpkgs/commit/fcc22971b9cc32a9e5a5d30d1aede17e4d7b69bc) | `` lieer: remove myself from maintainers ``                                  |
| [`8a42226c`](https://github.com/NixOS/nixpkgs/commit/8a42226c4473a57eb08ffbe9fab86efa784b2080) | `` github-runner: 2.303.0 -> 2.304.0 (#229141) ``                            |
| [`3056e9c3`](https://github.com/NixOS/nixpkgs/commit/3056e9c39564559985ed9ed514f4789fb …
=> chore(flake/nixpkgs): `08e4dc3a` -> `da45bf6e`

flake.lock
| [`0e4c33d7`](https://github.com/nix-community/home-manager/commit/0e4c33d76006c9080d2f228ba1c2308e3e4d7be6) | `` i3status-rust: satisfy new 0.31 TOML output requirements (#3938) `` |
=> chore(flake/home-manager): `3144311f` -> `0e4c33d7`

flake.lock
| [`23ac1ecb`](https://github.com/NixOS/nixos-hardware/commit/23ac1ecb8fdccbf880c0d051b5df69745543db3e) | `` Update README.md ``                      |
| [`8792ddc5`](https://github.com/NixOS/nixos-hardware/commit/8792ddc50c954685c5588e53dccf49847e5a1e54) | `` Add Dell XPS 9520 to flake and README `` |
| [`03548bee`](https://github.com/NixOS/nixos-hardware/commit/03548beefd2a015e8db3e5f6171bbdd5435f2fc1) | `` add dell precision 3541 to flake.nix ``  |
| …
=> chore(flake/nixos-hardware): `e4a21ddc` -> `7dc46304`

flake.lock
| Commit                                                                                         | Message                                                                               |
| ---------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------- |
| [`b4135f4f`](https://github.com/NixOS/nixpkgs/commit/b4135f4f3934198366851f8f694bd1b1972ae89a) | `` networkmanager-fortisslvpn: patch to build with ppp-2.5.0 ``                       |
| [`c9c5068a`](https://github.com/NixOS/nixpkgs/commit/c9c5068a274c045efdbd2a67de7270ab583967f4) | `` grandorgue: 3.10.1-1 -> 3.11.0 ``                                                  |
| …
=> chore(flake/nixpkgs): `da45bf6e` -> `1a411f23`

flake.lock
| [`f7ab221e`](https://github.com/danth/stylix/commit/f7ab221e56678b04adc8f889945988afa6be8a2e) | `` Add example by SomeGuyNamedMy (#96) ``           |
| [`d3153db5`](https://github.com/danth/stylix/commit/d3153db5e367478368be275b1aa57d6c1a4bf7aa) | `` Improve README and link to Matrix room :memo: `` |
=> chore(flake/stylix): `095ab80a` -> `f7ab221e`

flake.lock
| [`a9367cea`](https://github.com/danth/stylix/commit/a9367cea1bdc0ad35b3b0b2afc4aa9cf94cdecdb) | `` Fix screenshots not loading on GitHub Pages :memo: `` |
=> chore(flake/stylix): `f7ab221e` -> `a9367cea`

flake.lock
| [`514c0a71`](https://github.com/nix-community/home-manager/commit/514c0a71f47cb80282742d7e4b6913c2c0582c2d) | `` helix: provide more detailed settings description (#3932) `` |
| [`788777b5`](https://github.com/nix-community/home-manager/commit/788777b536df6e4c48fa158a9245c6f8a82beb43) | `` nushell: add envVars attribute (#3930) ``                    |
=> chore(flake/home-manager): `0e4c33d7` -> `514c0a71`

flake.lock
| [`ae6d5466`](https://github.com/nix-community/home-manager/commit/ae6d5466bf3ee61f5565f1631a787a7eda68c99d) | `` firefox: support bookmark tags (#3942) `` |
=> chore(flake/home-manager): `6abb775e` -> `ae6d5466`

flake.lock
| [`f3824311`](https://github.com/nix-community/home-manager/commit/f3824311a16cbe70dbaeedc17a97dfcd11901c3f) | `` readline: Add support for keynames (#3947) `` |
=> chore(flake/home-manager): `ae6d5466` -> `f3824311`

flake.lock
| Commit                                                                                              | Message                                                                  |
| --------------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------ |
| [`784e9ee2`](https://github.com/serokell/deploy-rs/commit/784e9ee24d977c99dcb5ba5aef81dae48cb899fb) | `` [Chore] Handle 'temp_path' as an actual 'Path' instead of 'String' `` |
=> chore(flake/deploy-rs): `c2ea4e64` -> `6b0b6a1c`

flake.lock
| [`fd155c2a`](https://github.com/NixOS/nixpkgs/commit/fd155c2a9494bd706bea5dc3916869bb3ffa739a) | `` llvmPackages_16.llvm: avoid calling roundevenf on darwin ``              |
| [`3c7fba2b`](https://github.com/NixOS/nixpkgs/commit/3c7fba2b0f70f0d6860f0be3780fa0176f6339a8) | `` llvmPackages_16.llvm: fix postPatch on darwin ``                         |
| [`cae55ac3`](https://github.com/NixOS/nixpkgs/commit/cae55ac31d4d904d5281c8c382e4eb68f36bb …
=> chore(flake/nixpkgs): `1a411f23` -> `0d8145a5`

flake.lock
| [`db08b1f1`](https://github.com/NixOS/nixos-hardware/commit/db08b1f13fe125d3dfeac89745ea3f362442eede) | `` tests: fix conflicts with profiles using grub ``        |
| [`d626c3f8`](https://github.com/NixOS/nixos-hardware/commit/d626c3f873e20e56f59bea88430f83328a355933) | `` add missing nxp boards ``                               |
| [`31f8d1c3`](https://github.com/NixOS/nixos-hardware/commit/31f8d1c36431153b98606e0b0c4427140ab8dc69) | `` Added Lenovo Thinkpad …
=> chore(flake/nixos-hardware): `7dc46304` -> `51559e69`

flake.lock
| [`38271ead`](https://github.com/nix-community/home-manager/commit/38271ead8e7b291beb9d3b8312e66c3268796c0a) | `` xfconf: support uint (#3946) `` |
=> chore(flake/home-manager): `f3824311` -> `38271ead`

flake.lock
| Commit                                                                                         | Message                                                                                      |
| ---------------------------------------------------------------------------------------------- | -------------------------------------------------------------------------------------------- |
| [`e5fa77e7`](https://github.com/NixOS/nixpkgs/commit/e5fa77e771e3f80914de72d05ee9c3263b8b5ab4) | `` xplorer: init at unstable-2023-03-19 ``                                                   |
| [`62c557d5`](https://github.com/NixOS/nixpkgs/commit/62c557d55438f460251b065c8ab21bffd3022d8d) | `` python3Packages.langchain: init at 0.0.158 ``                                             |
| …
=> chore(flake/nixpkgs): `0d8145a5` -> `3e313808`

flake.lock
| Commit                                                                                                    | Message                                                        |
| --------------------------------------------------------------------------------------------------------- | -------------------------------------------------------------- |
| [`a5372db9`](https://github.com/nix-community/lanzaboote/commit/a5372db91fb13d98b2d32bc15d2ad303f58885a6) | `` hotfix(stub): rust_version -> rust-version in Cargo.toml `` |
| [`9dd9116b`](https://github.com/nix-community/lanzaboote/commit/9dd9116b1ec88f834483de6b95f499dee25f0fea) | `` stub: export boot loader interface efivars ``               |
=> chore(flake/lanzaboote): `adc01887` -> `ae49611b`

flake.lock
| [`669669fc`](https://github.com/nix-community/home-manager/commit/669669fcb403e3137dfe599bbcc26e60502c3543) | `` Translate using Weblate (Polish) `` |
=> chore(flake/home-manager): `38271ead` -> `669669fc`

flake.lock
| Commit                                                                                                    | Message                    |
| --------------------------------------------------------------------------------------------------------- | -------------------------- |
| [`28dc2d3c`](https://github.com/Mic92/nix-index-database/commit/28dc2d3c5115373770836ec004d4649e1fcaedb0) | `` also integrate comma `` |
=> chore(flake/nix-index-database): `e3e320b1` -> `7b9e09d4`

flake.lock
| Commit                                                                                         | Message                                                                                                  |
| ---------------------------------------------------------------------------------------------- | -------------------------------------------------------------------------------------------------------- |
| [`81f51312`](https://github.com/NixOS/nixpkgs/commit/81f5131292ebf17115c2367fe02e15ff3b59738a) | `` yatas: 1.3.3 -> 1.5.1 ``                                                                              |
| [`56749016`](https://github.com/NixOS/nixpkgs/commit/567490160158d4ffe870a62ae8ed58c271279a67) | `` Revert "nixos/qemu-vm: fix diskless VMs" `` …
=> chore(flake/nixpkgs): `3e313808` -> `897876e4`

flake.lock
| [`a834ddf8`](https://github.com/nix-community/home-manager/commit/a834ddf88cb2eb4f77b7c0a2d6e2e8e0fb37c4e3) | `` flake: set source path in home-manager tool `` |
=> chore(flake/home-manager): `669669fc` -> `a834ddf8`

flake.lock
| [`0b4ec666`](https://github.com/nix-community/home-manager/commit/0b4ec66640ad5a1aa912a2ae7643f9756e71b4a7) | `` dconf: Warn about strict typing of options ``                    |
| [`ea29b1a8`](https://github.com/nix-community/home-manager/commit/ea29b1a8d1e2717581f4db852ad6647fc03bd00d) | `` docs: Add GVariant cross-references ``                           |
| [`13d666dd`](https://github.com/nix-community/home-manager/commit/13d6 …
=> chore(flake/home-manager): `a834ddf8` -> `990b82ec`

flake.lock
| [`6fc82e56`](https://github.com/nix-community/home-manager/commit/6fc82e56971523acfe1a61dbcb20f4bb969b3990) | `` i3status-rust: revert #3938 (#3957) `` |
=> chore(flake/home-manager): `990b82ec` -> `6fc82e56`

flake.lock
| [`de8ba413`](https://github.com/nix-community/home-manager/commit/de8ba413c578b68ef602c4f4c5909d9636a5bf92) | `` home-environment: honor use-xdg-base-directories `` |
| [`01730248`](https://github.com/nix-community/home-manager/commit/017302483c2c4372e7a680f390d7bb861335d849) | `` xfconf: fix type order (#3961) ``                   |
=> chore(flake/home-manager): `6fc82e56` -> `de8ba413`

flake.lock
| [`78ceec68`](https://github.com/nix-community/home-manager/commit/78ceec68f29ed56d6118617e9f0f588bf164067f) | `` xsession: cleanup systemd variables (#3636) ``        |
| [`e34fbe18`](https://github.com/nix-community/home-manager/commit/e34fbe18011483d1aac6f44cd2f03c0c89196812) | `` pass-secret-service: Add dbus file, assert (#3953) `` |
| [`d12ca778`](https://github.com/nix-community/home-manager/commit/d12ca77844a08b8b44edae0d66be0922544c2172) | `` …
=> chore(flake/home-manager): `de8ba413` -> `78ceec68`

flake.lock
| [`7378e062`](https://github.com/nix-community/lanzaboote/commit/7378e06257cec1a57900c781384c9e65e933fbed) | `` fix(deps): update all dependencies `` |
=> chore(flake/lanzaboote): `ae49611b` -> `39e61a0e`

flake.lock
| Commit                                                                                                    | Message                                         |
| --------------------------------------------------------------------------------------------------------- | ----------------------------------------------- |
| [`0b380642`](https://github.com/Mic92/nix-index-database/commit/0b3806422d55fc9fdd20b1c19e6065c717dbdec9) | `` fix the comma package in nixos-module.nix `` |
=> chore(flake/nix-index-database): `7b9e09d4` -> `54049e3d`

flake.lock
| [`983f8a1b`](https://github.com/nix-community/home-manager/commit/983f8a1bb965b261492123cd8e2d07da46d4d50a) | `` git-cliff: add module `` |
=> chore(flake/home-manager): `3f3fa731` -> `983f8a1b`

flake.lock
| Commit                                                                                           | Message                              |
| ------------------------------------------------------------------------------------------------ | ------------------------------------ |
| [`da2c0a74`](https://github.com/LnL7/nix-darwin/commit/da2c0a74ca7aa2472cf2bc819ce8af53530b3bd8) | `` buildkite-agent: update module `` |
=> chore(flake/darwin): `379d42fa` -> `9520a6e4`

flake.lock
| Commit                                                                                           | Message                                                                        |
| ------------------------------------------------------------------------------------------------ | ------------------------------------------------------------------------------ |
| [`fa97d795`](https://github.com/LnL7/nix-darwin/commit/fa97d795677432ceea46df9a6f609efbe3dbe90c) | `` nix: Fix registry extra attrs not being applied ``                          |
| [`2303eed5`](https://github.com/LnL7/nix-darwin/commit/2303eed571946c367d134dd39d017e3bb3517241) | `` feat(screensaver): add support of askForPassword and askForPasswordDelay `` |
| [`ca62d93c`](https://github.com/LnL7/nix-darwin/commit/ca62d93c6c6bf89 …
=> chore(flake/darwin): `9520a6e4` -> `252541bd`

flake.lock
| [`010c2698`](https://github.com/nix-community/home-manager/commit/010c26987729d6a2e0e19da6df7c3f0465ae03b3) | `` zsh: add `package` option (#3945) `` |
=> chore(flake/home-manager): `983f8a1b` -> `010c2698`

flake.lock
| [`fa720861`](https://github.com/nix-community/home-manager/commit/fa720861b5b68536434360aa0ccf0a5fb9060a73) | `` translate-shell: add module (#3659) ``              |
| [`b365342a`](https://github.com/nix-community/home-manager/commit/b365342adb36fd659a1472dced6f55b706c15162) | `` ledger: add structural `settings` option (#3661) `` |
=> chore(flake/home-manager): `010c2698` -> `fa720861`

flake.lock
| [`6be87366`](https://github.com/nix-community/home-manager/commit/6be873663e5b16ded72f9b17b984f64be02437f0) | `` ssh: add setEnv option (#3935) `` |
=> chore(flake/home-manager): `2f6a917a` -> `6be87366`

flake.lock
| [`cc9f65d1`](https://github.com/nix-community/home-manager/commit/cc9f65d104e5227d103a529a9fc3687ef4ccb117) | `` zellij: adds options to integrate with zsh, bash and fish shells (#3926) `` |
=> chore(flake/home-manager): `d97e8f88` -> `cc9f65d1`

flake.lock
| [`c84a8f24`](https://github.com/NixOS/nixos-hardware/commit/c84a8f242331c513a310aff7ebf83cabd11de3bc) | `` nxp-imx8: drop kernel overlay `` |
=> chore(flake/nixos-hardware): `51559e69` -> `fb131794`

flake.lock
| Commit                                                                                         | Message                                        |
| ---------------------------------------------------------------------------------------------- | ---------------------------------------------- |
| [`6b4ff3d1`](https://github.com/ryantm/agenix/commit/6b4ff3d19165b2bbf8f3447ceaa431fb22311037) | `` Check darwin home-manager test in CI ``     |
| [`50743bd1`](https://github.com/ryantm/agenix/commit/50743bd1178c1afc426ee914686d1437eec8c9d2) | `` Add darwin tests for home-manager module `` |
| [`19bf5a20`](https://github.com/ryantm/agenix/commit/19bf5a20d835145e5f3fc8d61672eefee4c33450) | `` Clean-up Darwin integration test ``         |
| …
=> chore(flake/agenix): `2994d002` -> `92197270`

flake.lock
| [`a835096f`](https://github.com/nix-community/home-manager/commit/a835096fd2bcc369f57b76b9b17cc00348f595f5) | `` kitty: add shellIntegration (#3759) `` |
=> chore(flake/home-manager): `cc9f65d1` -> `a835096f`

flake.lock
| [`eec22729`](https://github.com/nix-community/home-manager/commit/eec22729990ddf53d1e45e74624ddf667cdbe11b) | `` tests: various minor cleanups ``                          |
| [`19c509a6`](https://github.com/nix-community/home-manager/commit/19c509a6fa945212e478e5522149117162217bc5) | `` emacs: minor fixes ``                                     |
| [`1eac5feb`](https://github.com/nix-community/home-manager/commit/1eac5febc412b3aa6acc29c705e99d42 …
=> chore(flake/home-manager): `a835096f` -> `eec22729`

flake.lock
| [`e39036d5`](https://github.com/NixOS/nixos-hardware/commit/e39036d599ad51d6a3f77f7e96bfa630f4991410) | `` feat: Add focus m2 gen1 `` |
=> chore(flake/nixos-hardware): `fb131794` -> `81cd8867`

flake.lock
| [`93849977`](https://github.com/nix-community/home-manager/commit/938499771727f2a53a19eb178f16fc42ff53a9f8) | `` Translate using Weblate (Japanese) `` |
| [`130abb8d`](https://github.com/nix-community/home-manager/commit/130abb8dbdf441be2dbd3c2d42398faeff5d89b1) | `` Translate using Weblate (German) ``   |
=> chore(flake/home-manager): `eec22729` -> `93849977`

flake.lock
| [`e0026e16`](https://github.com/nix-community/home-manager/commit/e0026e16a5beff80f641e4edca318e654baa5a9b) | `` fuzzel: add module `` |
=> chore(flake/home-manager): `93849977` -> `e0026e16`

flake.lock
| [`6702b22b`](https://github.com/nix-community/home-manager/commit/6702b22b9805bc1879715d4111e3764cd4237aed) | `` ssh: install an ssh client `` |
=> chore(flake/home-manager): `e0026e16` -> `6702b22b`

flake.lock
| [`db3d440e`](https://github.com/nix-community/home-manager/commit/db3d440e2664e8aaf67742b6fd545cf148fe5016) | `` kitty: improve error message when theme not found (#3989) `` |
=> chore(flake/home-manager): `6702b22b` -> `db3d440e`

flake.lock
| Commit                                                                                                      | Message               |
| ----------------------------------------------------------------------------------------------------------- | --------------------- |
| [`e4272987`](https://github.com/nix-community/home-manager/commit/e4272987f785a8848205263abb4911b922c21e1b) | `` Drop CODEOWNERS `` |
=> chore(flake/home-manager): `db3d440e` -> `e4272987`

flake.lock
| [`5a39142b`](https://github.com/nix-community/impermanence/commit/5a39142bbbb87e928a195b996dc134e7bfe2471a) | `` feat(nixos): allow persistant locations to be disabled `` |
=> chore(flake/impermanence): `df1692e2` -> `ec1a8e70`

flake.lock
| [`3d22883c`](https://github.com/LnL7/nix-darwin/commit/3d22883cdb4226306be7583f5513b3ca23a72e24) | `` add tests ``                                         |
| [`f781cb0a`](https://github.com/LnL7/nix-darwin/commit/f781cb0ac5ea2daa5183b8df8f4de4ef0747f440) | `` give credits ``                                      |
| [`4094dbcc`](https://github.com/LnL7/nix-darwin/commit/4094dbccde0d00fd062d365b8c79526711a6bc95) | `` newline eof for authorized-keys conf ``              |
| …
=> chore(flake/darwin): `252541bd` -> `0dbf1c2f`

flake.lock
| Commit                                                                                         | Message                                                      |
| ---------------------------------------------------------------------------------------------- | ------------------------------------------------------------ |
| [`72205a86`](https://github.com/ryantm/agenix/commit/72205a86cafc06df6a11e1ae9dcef71374cd2cf5) | `` Add test for custom secret paths for HM ``                |
| [`758cdc98`](https://github.com/ryantm/agenix/commit/758cdc98f49ba72f4e941933575db8a70f24cfe3) | `` Disable shellcheck warning about impossible comparison `` |
=> chore(flake/agenix): `92197270` -> `db5637d1`

flake.lock
| [`c0deab0e`](https://github.com/nix-community/home-manager/commit/c0deab0effd576e70343cb5df0c64428e0e0d010) | `` ci: autolabel PRs for aerc changes and some zsh files (#3992) `` |
=> chore(flake/home-manager): `e4272987` -> `c0deab0e`

flake.lock
| [`b3b91ca4`](https://github.com/NixOS/nixos-hardware/commit/b3b91ca4871dcbbcb9dbe016c6203736480edd6e) | `` samsung/np900x3c: drop deprecated synaptics `` |
=> chore(flake/nixos-hardware): `81cd8867` -> `b3a8d308`

flake.lock
| Commit                                                                                                | Message                                                                               |
| ----------------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------- |
| [`bbacfd60`](https://github.com/NixOS/nixos-hardware/commit/bbacfd60126930faee6801c44bcda186151a22d6) | `` PR review comment ``                                                               |
| [`2c2d2240`](https://github.com/NixOS/nixos-hardware/commit/2c2d22409f4082ab8891fe118f7ec041e83175d4) | `` Add HP Elitebook 845g9 ``                                                          |
| …
=> chore(flake/nixos-hardware): `b3a8d308` -> `71ce8537`

flake.lock
| Commit                                                                                                       | Message               |
| ------------------------------------------------------------------------------------------------------------ | --------------------- |
| [`00d88811`](https://github.com/cachix/pre-commit-hooks.nix/commit/00d88811c82fe44533363d1ac3d94c8ee2b2a479) | `` Fixup hook docs `` |
=> chore(flake/pre-commit-hooks): `48c59cec` -> `96eabec5`

flake.lock
| [`70c1240b`](https://github.com/NixOS/nixpkgs/commit/70c1240b6fb88a51f06942b00dc5092bc13fd35c) | `` python3Packages.cocotb: fix failing build (#231184) ``                         |
| [`25f3323d`](https://github.com/NixOS/nixpkgs/commit/25f3323d60271ac9b668757322c47f96aa7ca726) | `` nixos/etcd: Fix mapping of clientCertAuth option ``                            |
| [`cedcd620`](https://github.com/NixOS/nixpkgs/commit/cedcd620c50b0 …
=> chore(flake/nixpkgs): `0470f36b` -> `17a68959`

flake.lock
| [`e2bde0d4`](https://github.com/NixOS/nixpkgs/commit/e2bde0d450ba2bbd80785f69706ba9844ff4faec) | `` terraform-providers.sumologic: 2.22.0 -> 2.22.1 ``                      |
| [`e82d36f9`](https://github.com/NixOS/nixpkgs/commit/e82d36f97f71784333278b7473d553ec548bb9af) | `` terraform-providers.scaleway: 2.18.0 -> 2.19.0 ``                       |
| [`17c278a8`](https://github.com/NixOS/nixpkgs/commit/17c278a8758e67559dd9b40900970bf37350dcc6) …
=> chore(flake/nixpkgs): `17a68959` -> `963006aa`

flake.lock
| [`b7d814c5`](https://github.com/nix-community/home-manager/commit/b7d814c5744dca7e70b3dc2638f06568dce96ca6) | `` tests: bump nmt to latest `` |
=> chore(flake/home-manager): `c0deab0e` -> `b7d814c5`

flake.lock
| [`6f4fc9d7`](https://github.com/nix-community/impermanence/commit/6f4fc9d70c3ec1bcf5fc5e2563e77621ad13eb1e) | `` Skip generating bind mounts if no bind mounts are configured. `` |
=> chore(flake/impermanence): `ec1a8e70` -> `89253fb1`

flake.lock
| [`59659243`](https://github.com/nix-community/home-manager/commit/59659243cd4ababda605e79b4a9c2e6d83e24c86) | `` PR_TEMPLATE: Note nix3 test method in checklist (#3972) `` |
| [`e14e7970`](https://github.com/nix-community/home-manager/commit/e14e797041e393abd1ffab597d299a72d3b582e5) | `` neomutt: add missing stub in test (#3996) ``               |
=> chore(flake/home-manager): `b7d814c5` -> `59659243`

flake.lock
| Commit                                                                                                    | Message                  |
| --------------------------------------------------------------------------------------------------------- | ------------------------ |
| [`3f80a741`](https://github.com/nix-community/lanzaboote/commit/3f80a7416ffb7f5733682e062ca390c88fe463e1) | `` flake.lock: Update `` |
=> chore(flake/lanzaboote): `39e61a0e` -> `d93eebb9`

flake.lock
| [`6236fd19`](https://github.com/LnL7/nix-darwin/commit/6236fd19231394d74520274c457fd72cab569ab3) | `` buildkite-agent: allow 'types.path' in runtimePackages `` |
| [`f1a562ee`](https://github.com/LnL7/nix-darwin/commit/f1a562eef19a042a1b2693e412a1f95aad11eab6) | `` refactor: rename clock option menuExtraClock ``           |
| [`f6b7489d`](https://github.com/LnL7/nix-darwin/commit/f6b7489ddb316eb2b331e2f3a5ef43e11d8eff34) | `` feat: defaults write …
=> chore(flake/darwin): `0dbf1c2f` -> `dfbdabbb`

flake.lock
| [`099081ff`](https://github.com/NixOS/nixpkgs/commit/099081ff402d0b649becb48d986331132dfbe95a) | `` skaffold: 2.4.0 -> 2.4.1 ``                                                  |
| [`1af30523`](https://github.com/NixOS/nixpkgs/commit/1af3052329c3de4a95b2efd98f71839e6bbb5191) | `` pulumictl: 0.0.42 -> 0.0.43 ``                                               |
| [`5cc6776f`](https://github.com/NixOS/nixpkgs/commit/5cc6776fe11dcce86105e …
=> chore(flake/nixpkgs): `e6e38991` -> `48a0fb7a`

flake.lock
| Commit                                                                                                    | Message                         |
| --------------------------------------------------------------------------------------------------------- | ------------------------------- |
| [`c17650da`](https://github.com/nix-community/lanzaboote/commit/c17650dafc065c607d199a3125d33402603c5076) | `` flake: add rustfmt checks `` |
| [`65dbe449`](https://github.com/nix-community/lanzaboote/commit/65dbe449996c6937cfa9d55e5d97c525d98a5412) | `` stub: format with rustfmt `` |
| [`e37bf51e`](https://github.com/nix-community/lanzaboote/commit/e37bf51ed3c600e9fa851c491f0a3de0ff4eae1f) | `` stub: format with rustfmt `` |
=> chore(flake/lanzaboote): `d93eebb9` -> `354ec6f4`

flake.lock
| Commit                                                                                        | Message                     |
| --------------------------------------------------------------------------------------------- | --------------------------- |
| [`1c953ad0`](https://github.com/danth/stylix/commit/1c953ad0dc9d7f0a8e0dd52b286d2d25dd43f0b5) | `` Opacity support (#77) `` |
=> chore(flake/stylix): `a9367cea` -> `1c953ad0`

flake.lock
| Commit                                                                                                      | Message                      |
| ----------------------------------------------------------------------------------------------------------- | ---------------------------- |
| [`c10403a5`](https://github.com/nix-community/home-manager/commit/c10403a5739d6275334710903fe709bc8d587980) | `` Update ssh.nix (#4000) `` |
=> chore(flake/home-manager): `59659243` -> `c10403a5`

flake.lock
| Commit                                                                                                    | Message                         |
| --------------------------------------------------------------------------------------------------------- | ------------------------------- |
| [`ad28b4cd`](https://github.com/nix-community/lanzaboote/commit/ad28b4cd017b5eb2bc4cd3c4240dc5cc1bf3908f) | `` stub: bump crate to 0.3.0 `` |
| [`39cda9e4`](https://github.com/nix-community/lanzaboote/commit/39cda9e457841a7ab70fc1d98536dc9e40a2eaaf) | `` tool: bump crate to 0.3.0 `` |
| [`cc428efc`](https://github.com/nix-community/lanzaboote/commit/cc428efc862d9169f5c826f342ed9938c89ba70c) | `` flake: add cargo-release ``  |
=> chore(flake/lanzaboote): `3a5e15f4` -> `7ed294c8`

flake.lock
| [`b9a52ad2`](https://github.com/nix-community/home-manager/commit/b9a52ad20e58ebd003444915e35e3dd2c18fc715) | `` script-directory: add module (#3995) `` |
=> chore(flake/home-manager): `c10403a5` -> `b9a52ad2`

flake.lock
| [`ad86cb32`](https://github.com/NixOS/nixpkgs/commit/ad86cb327212828c44236aff5fe0d3ba452a8f56) | `` pasystray: 0.7.1 -> 0.8.2 ``                                           |
| [`3041059a`](https://github.com/NixOS/nixpkgs/commit/3041059a288d155dd72fdca4812ec383e08e4489) | `` polypane: 13.0.3 -> 13.1.2 ``                                          |
| [`44d0de34`](https://github.com/NixOS/nixpkgs/commit/44d0de3499c11f5c9817a00fec76386ae16ff606) | …
=> chore(flake/nixpkgs): `48a0fb7a` -> `5b1bc788`

flake.lock
| [`cd9e19da`](https://github.com/danth/stylix/commit/cd9e19daa104c7f49fdc571b9cf8c9d76dd1b3ba) | `` Add options availability checks (#100) `` |
=> chore(flake/stylix): `1c953ad0` -> `cd9e19da`

flake.lock
| [`ef85c3fe`](https://github.com/NixOS/nixpkgs/commit/ef85c3fe518186ae1effb0441a92c33468c475e2) | `` nixos: use passAsFile to avoid "Argument list too long" error ``                  |
| [`7a7b0862`](https://github.com/NixOS/nixpkgs/commit/7a7b0862dbe772582eb3e41c85430faf206fb606) | `` erlang_26: init ``                                                                |
| …
=> chore(flake/nixpkgs): `5b1bc788` -> `5ae23a80`

flake.lock
| [`68c1807f`](https://github.com/NixOS/nixpkgs/commit/68c1807f3c523788b5ce58879ec67ed9c43022d6) | `` eudev: 3.2.11 -> 3.2.12 ``                                                |
| [`aff52a74`](https://github.com/NixOS/nixpkgs/commit/aff52a7444ae59535c44ed4dd33a038fbea9af80) | `` komikku: 1.19.0 -> 1.20.0 ``                                              |
| [`7a288f77`](https://github.com/NixOS/nixpkgs/commit/7a288f777a58a0a962bdf5e03b7308f7f …
=> chore(flake/nixpkgs): `5ae23a80` -> `3005f20c`

flake.lock
| Commit                                                                                                      | Message                                                                                        |
| ----------------------------------------------------------------------------------------------------------- | ---------------------------------------------------------------------------------------------- |
| [`27ef11f0`](https://github.com/nix-community/home-manager/commit/27ef11f0218d9018ebb2948d40133df2b1de622d) | `` helix: update languages.toml generation (support every option in languages.toml) (#4003) `` |
=> chore(flake/home-manager): `b9a52ad2` -> `27ef11f0`

flake.lock
| Commit                                                                                                    | Message                                                       |
| --------------------------------------------------------------------------------------------------------- | ------------------------------------------------------------- |
| [`77f12794`](https://github.com/nix-community/lanzaboote/commit/77f1279406db09e572954e970163312a7fb1cfe0) | `` tool(bootspec): remove boilerplate with newest bootspec `` |
=> chore(flake/lanzaboote): `7ed294c8` -> `3fb74cfb`

flake.lock
| Commit                                                                                                    | Message                              |
| --------------------------------------------------------------------------------------------------------- | ------------------------------------ |
| [`c96299ea`](https://github.com/nix-community/lanzaboote/commit/c96299ea46feadc77d7ded2cd582d174e86e2a67) | `` deps: update to uefi-rs 0.21.0 `` |
=> chore(flake/lanzaboote): `3fb74cfb` -> `f9681e3e`

flake.lock
| [`13a74643`](https://github.com/nix-community/home-manager/commit/13a74643d72b1891b03f2566983819d451bd4b56) | `` home-manager: fix error message in flake check `` |
=> chore(flake/home-manager): `27ef11f0` -> `13a74643`

flake.lock
| [`ba006d7c`](https://github.com/nix-community/home-manager/commit/ba006d7cca2cb871c6a31bdbc130c05cde5ca8e8) | `` script-directory: fix news entry (#4010) `` |
=> chore(flake/home-manager): `13a74643` -> `ba006d7c`

flake.lock
| Commit                                                                                         | Message                                                               |
| ---------------------------------------------------------------------------------------------- | --------------------------------------------------------------------- |
| [`9e291a27`](https://github.com/NixOS/nixpkgs/commit/9e291a2755fbfb7af294508424b381ebc8839d80) | `` terragrunt: 0.45.11 -> 0.45.13 ``                                  |
| [`ec9e4dd1`](https://github.com/NixOS/nixpkgs/commit/ec9e4dd188bd81da41c5800bb63445be525e1d69) | `` jfrog-cli: add changelog to meta ``                                |
| [`10ecb4b8`](https://github.com/NixOS/nixpkgs/commit/10ecb4b84e19960701ee48bae0f521f9fcf92268) | `` nebula: 1.7.0 …
=> chore(flake/nixpkgs): `3005f20c` -> `50a18318`

flake.lock
| [`5ecd73cd`](https://github.com/nix-community/lanzaboote/commit/5ecd73cdac8b4069640ef8ee6b84f8b66747fedd) | `` fix(deps): update all dependencies `` |
=> chore(flake/lanzaboote): `f9681e3e` -> `36adaf5a`

flake.lock
| [`ebdd18cd`](https://github.com/LnL7/nix-darwin/commit/ebdd18cdc169f680a1385c0d26dfe92dc5062ade) | `` ci: refactor to several jobs to enable optional checks `` |
| [`d2222000`](https://github.com/LnL7/nix-darwin/commit/d222200091f2d739bf811b98056fbd0062ea0789) | `` ci: use latest stable channel 22.05 -> 22.11 ``           |
| [`a379f9af`](https://github.com/LnL7/nix-darwin/commit/a379f9afe7f80b137d66fbbeeb81da9b29b519da) | `` docs: update flake snippet to 22.11 `` …
=> chore(flake/darwin): `dfbdabbb` -> `b8c286c8`

flake.lock
| [`d9995d94`](https://github.com/nix-community/home-manager/commit/d9995d94f194955d1f1af0e1ad5866a904196c20) | `` lib/file-type: fix xrefs (#4007) `` |
=> chore(flake/home-manager): `ba006d7c` -> `d9995d94`

flake.lock
| [`49a5cd8b`](https://github.com/NixOS/nixpkgs/commit/49a5cd8be665a5152b941890db54c8a92a69ce5a) | `` darwin.sigtool: add meta ``                                                     |
| [`d79d7bdb`](https://github.com/NixOS/nixpkgs/commit/d79d7bdbf43df9aa19f3c3234c0729c54cee6105) | `` lens: Change lens' listed license from MIT to their own proprietary license. `` |
| [`a4b25ea8`](https://github.com/NixOS/nixpkgs/commit/a4b25ea80 …
=> chore(flake/nixpkgs): `50a18318` -> `7084250d`

flake.lock
| [`58eb968c`](https://github.com/nix-community/home-manager/commit/58eb968c21d309a6c2b020ea8d64e25c38ceebba) | `` flake.lock: Update `` |
=> chore(flake/home-manager): `d9995d94` -> `58eb968c`

flake.lock
| [`30ddfcd2`](https://github.com/nix-community/lanzaboote/commit/30ddfcd2ceda86a952cbfae3cf99e7ce0796db4d) | `` tool: improve command error messages `` |
=> chore(flake/lanzaboote): `36adaf5a` -> `1f542a1e`

flake.lock
| [`e2864d99`](https://github.com/NixOS/nixos-hardware/commit/e2864d99fddc26c2ab11f6937f493c6390b0ad12) | `` starfive visionfive2: replace 8GB memory patch with overlay `` |
| [`ee1055d8`](https://github.com/NixOS/nixos-hardware/commit/ee1055d80ce5fcfe556e4c7185d9afcf922a7caf) | `` [FocusGen1M2] Disable TPM interrupt due to upstream bug ``     |
=> chore(flake/nixos-hardware): `71ce8537` -> `4cc688ee`

flake.lock
| Commit                                                                                                    | Message                                       |
| --------------------------------------------------------------------------------------------------------- | --------------------------------------------- |
| [`740f7f93`](https://github.com/nix-community/lanzaboote/commit/740f7f93142df2cb97d7e448b677f672bc346a6b) | `` flake: checkInputs -> nativeCheckInputs `` |
| [`8e4de789`](https://github.com/nix-community/lanzaboote/commit/8e4de7892abf47a0292012ca8b900c5bb9734b1a) | `` flake: add proper description ``           |
=> chore(flake/lanzaboote): `1f542a1e` -> `dc52f035`

flake.lock
| Commit                                                                                         | Message                                                                 |
| ---------------------------------------------------------------------------------------------- | ----------------------------------------------------------------------- |
| [`e89ce050`](https://github.com/NixOS/nixpkgs/commit/e89ce0502750f0e85d2756059caca1ce50d60e2c) | `` xfsprogs: 6.2.0 -> 6.3.0 (#233430) ``                                |
| [`93581dbb`](https://github.com/NixOS/nixpkgs/commit/93581dbb574af0b5142638a559aa66db1ddc4042) | `` python3.pkgs.mmcv: 1.7.1 -> 2.0.0 ``                                 |
| [`a1815ec7`](https://github.com/NixOS/nixpkgs/commit/a1815ec7dab8d4d331dd058f3f0e57d13e93384a) | `` …
=> chore(flake/nixpkgs): `7084250d` -> `d30264c2`

flake.lock
| [`8d3ecfc3`](https://github.com/NixOS/nixpkgs/commit/8d3ecfc309178032e739961cfd6fd0451540b353) | `` gotrue-supabase: fix version ``                                                 |
| [`663049c3`](https://github.com/NixOS/nixpkgs/commit/663049c30229b24cbba610ef51c74cb46d17658a) | `` srsran: fix version ``                                                          |
| [`695797d5`](https://github.com/NixOS/nixpkgs/commit/695797d5b …
=> chore(flake/nixpkgs): `d30264c2` -> `f91ee306`

flake.lock
| [`d1f04b0f`](https://github.com/nix-community/home-manager/commit/d1f04b0f365a34896a37d9015637796537ec88a3) | `` yt-dlp: generate config if settings or extraConfig are defined (#4018) `` |
=> chore(flake/home-manager): `58eb968c` -> `d1f04b0f`

flake.lock
| [`bec196cd`](https://github.com/nix-community/home-manager/commit/bec196cd9b5f34213c7dc90ef2a524336df70e30) | `` helix: improve warning message for languages option (#4023) `` |
=> chore(flake/home-manager): `d1f04b0f` -> `bec196cd`

flake.lock
| [`b673e1b7`](https://github.com/nix-community/lanzaboote/commit/b673e1b71fbdb8c025b3ba52ed4250630d6eb650) | `` docs: add precision about dbx and OptionROMs `` |
=> chore(flake/lanzaboote): `dc52f035` -> `f641dcfc`

flake.lock
| [`6a192256`](https://github.com/nix-community/home-manager/commit/6a1922568337e7cf21175213d3aafd1ac79c9a2e) | `` home-manager: verify username and home directory `` |
=> chore(flake/home-manager): `bec196cd` -> `6a192256`

flake.lock
| [`2d963854`](https://github.com/nix-community/home-manager/commit/2d963854ae2499193c0c72fd67435fee34d3e4fd) | `` ssh: don't install a client by default (#4016) `` |
=> chore(flake/home-manager): `6a192256` -> `2d963854`

flake.lock
| Commit                                                                                                    | Message                              |
| --------------------------------------------------------------------------------------------------------- | ------------------------------------ |
| [`72b66bfc`](https://github.com/nix-community/lanzaboote/commit/72b66bfc69942e5b031527eb20a43b1cd403c64b) | `` docs: fixup stray ``` ``          |
| [`de80330e`](https://github.com/nix-community/lanzaboote/commit/de80330ec4408e38732a321b0ded8695af5838b8) | `` docs: update upstreaming state `` |
=> chore(flake/lanzaboote): `f641dcfc` -> `e9003f12`

flake.lock
| Commit                                                                                         | Message                                                                  |
| ---------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------ |
| [`decb072d`](https://github.com/NixOS/nixpkgs/commit/decb072d37813bb3e37246530a0aa7656829c70f) | `` killport: 0.8.0 -> 0.9.0 ``                                           |
| [`bee7cb59`](https://github.com/NixOS/nixpkgs/commit/bee7cb59046bbb5ff9d4ad21ffbd97c56fd56862) | `` powerstat: 0.03.01 -> 0.03.03 ``                                      |
| [`8d908a2e`](https://github.com/NixOS/nixpkgs/commit/8d908a2ed404652abaaa48ac2a438955a1f57af9) | `` …
=> chore(flake/nixpkgs): `f91ee306` -> `e1080230`

flake.lock
| Commit                                                                                                    | Message                                          |
| --------------------------------------------------------------------------------------------------------- | ------------------------------------------------ |
| [`f1d199d0`](https://github.com/nix-community/lanzaboote/commit/f1d199d0b4ec62180044bdaa781818be585b2b10) | `` fix(deps): update rust crate log to 0.4.18 `` |
=> chore(flake/lanzaboote): `e9003f12` -> `2e62c11b`

flake.lock
| Commit                                                                                         | Message                                                                               |
| ---------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------- |
| [`919e2249`](https://github.com/NixOS/nixpkgs/commit/919e224951a6d6749961594926a8dd4a75077335) | `` CODEOWNERS: add raitobezarius as a ZFS code owner ``                               |
| [`d7d44eb8`](https://github.com/NixOS/nixpkgs/commit/d7d44eb80840bbb8e338baf39c0708d3fe3be699) | `` rtl-sdr: fix version in librtlsdr.pc ``                                            |
| …
=> chore(flake/nixpkgs): `e1080230` -> `4e37b4e5`

flake.lock
| Commit                                                                                                       | Message                                             |
| ------------------------------------------------------------------------------------------------------------ | --------------------------------------------------- |
| [`da695773`](https://github.com/cachix/pre-commit-hooks.nix/commit/da695773e5d7a7da7c4c6c3ec3f14d00a7a36803) | `` nil: Fix hook only failing if last file fails `` |
=> chore(flake/pre-commit-hooks): `8e2c1a5a` -> `ca2fdbf3`

flake.lock
| [`43ed7048`](https://github.com/nix-community/home-manager/commit/43ed7048f670661d1ae2ea0d2f7655e87e7b0461) | `` Drop remaining CODEOWNERS reference from PR template (#4033) `` |
=> chore(flake/home-manager): `2d963854` -> `43ed7048`

flake.lock
| [`9f82227b`](https://github.com/nix-community/home-manager/commit/9f82227b64245c273d98dd02dedd44fc7576041e) | `` lib/file-type: convert `executable` to bool (#4036) `` |
=> chore(flake/home-manager): `43ed7048` -> `9f82227b`

flake.lock
| Commit                                                                                         | Message                                                                                                      |
| ---------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------------------------------ |
| [`93707532`](https://github.com/NixOS/nixpkgs/commit/93707532366ba2bc6b4b8ae920ba31246b20a613) | `` xcp: 0.9.4 -> 0.10.0 ``                                                                                   |
| [`4358d2ac`](https://github.com/NixOS/nixpkgs/commit/4358d2ac4feaff46846bb3b908c72497e8146d50) | `` kyverno: 1.9.4 -> 1.9.5 `` …
=> chore(flake/nixpkgs): `4e37b4e5` -> `5e871d8a`

flake.lock
| [`54a9d645`](https://github.com/nix-community/home-manager/commit/54a9d6456eaa6195998a0f37bdbafee9953ca0fb) | `` waybar: merge multiple style definitions (#4038) `` |
=> chore(flake/home-manager): `9f82227b` -> `54a9d645`

flake.lock
| Commit                                                                                               | Message                                                  |
| ---------------------------------------------------------------------------------------------------- | -------------------------------------------------------- |
| [`a1720a10`](https://github.com/numtide/flake-utils/commit/a1720a10a6cfe8234c0e93907ffe81be440f4cef) | `` Bump cachix/install-nix-action from 20 to 21 (#96) `` |
=> chore(flake/flake-utils): `cfacdce0` -> `a1720a10`

flake.lock
| [`add08fca`](https://github.com/LnL7/nix-darwin/commit/add08fcab07cea0db9b5403861d5ae81ee09f1ee) | `` flakes: Do not verify channels when using flakes. `` |
=> chore(flake/darwin): `b8c286c8` -> `4338bc86`

flake.lock
| [`f1490b8c`](https://github.com/nix-community/home-manager/commit/f1490b8caf2ef6f59205c78cf1a8b68e776214a3) | `` Switch current unstable version to 23.11 `` |
| [`33ccc5c2`](https://github.com/nix-community/home-manager/commit/33ccc5c28572d200f1e8d93fccba17e084e5f587) | `` Switch stable branch to release-23.05 ``    |
| [`b2a6cf7b`](https://github.com/nix-community/home-manager/commit/b2a6cf7b59343f4c1c29f5777b16ccd8f6e6495b) | `` docs: update copyright years `` …
=> chore(flake/home-manager): `54a9d645` -> `f1490b8c`

flake.lock
| [`53ccbe01`](https://github.com/nix-community/home-manager/commit/53ccbe017079d5fba2b605cb9f9584629bebd03a) | `` fish: use babelfish for `hm-session-vars.sh` (#4012) `` |
=> chore(flake/home-manager): `f1490b8c` -> `53ccbe01`

flake.lock
| [`96078e4a`](https://github.com/nix-community/home-manager/commit/96078e4a939b5e5fec1cfd83a11b3df7146a58ff) | `` Fix release notes (#4044) `` |
=> chore(flake/home-manager): `53ccbe01` -> `96078e4a`

flake.lock
| [`3876cc61`](https://github.com/nix-community/home-manager/commit/3876cc613ac3983078964ffb5a0c01d00028139e) | `` Translate using Weblate (Ukrainian) `` |
| [`04f6c292`](https://github.com/nix-community/home-manager/commit/04f6c2925b2e625504cd5a6ee758d320596f6394) | `` Translate using Weblate (Persian) ``   |
| [`efed2ccd`](https://github.com/nix-community/home-manager/commit/efed2ccd9f7fbdae1f355b245bed7864dee96317) | `` Translate using Weblate (Spanish) ``   |
| …
=> chore(flake/home-manager): `96078e4a` -> `3876cc61`

flake.lock
| [`28ecd175`](https://github.com/NixOS/nixpkgs/commit/28ecd1752334b467929ef3f565389fdf94c03f1e) | `` nixos/doc: Mention container registry deprecation in gitlab ``                |
| [`e9594e60`](https://github.com/NixOS/nixpkgs/commit/e9594e60319bae339c8cc7211e9f773d394839ae) | `` nixos/gitlab: Warn users who are still using an external registry ``          |
| [`014816cb`](https://github.com/NixOS/nixpkgs/commit/014816cbe46973336 …
=> chore(flake/nixpkgs): `5e871d8a` -> `4f53efe3`

flake.lock
| Commit                                                                                                    | Message                     |
| --------------------------------------------------------------------------------------------------------- | --------------------------- |
| [`7ecafb29`](https://github.com/nix-community/lanzaboote/commit/7ecafb29470c58d7aad00ae771234cdfa2c02da5) | `` stub: add fat variant `` |
=> chore(flake/lanzaboote): `2e62c11b` -> `da243579`

flake.lock
| [`04147e05`](https://github.com/NixOS/nixpkgs/commit/04147e058dcdec8e04c1bcbfbeed7dd7366a20a9) | `` fetchurl: remove mirror kent.dl.sourceforge.net ``                       |
| [`7cb219d3`](https://github.com/NixOS/nixpkgs/commit/7cb219d309992c8ec62b1eb80be701ed486fd4f5) | `` yamlfix: 1.9.0 -> 1.10.0 ``                                              |
| [`99d37f54`](https://github.com/NixOS/nixpkgs/commit/99d37f54f002290eb32c5a06451d05572af8e …
=> chore(flake/nixpkgs): `4f53efe3` -> `e6351928`

flake.lock
| [`e171cb06`](https://github.com/Mic92/nix-index-database/commit/e171cb06e7f77cc506e0712dd0a67530de1c80e3) | `` disable i686-linux again ``                     |
| [`eafda9c7`](https://github.com/Mic92/nix-index-database/commit/eafda9c78822602053b815d666424e115f70416e) | `` Bump cachix/install-nix-action from 20 to 21 `` |
=> chore(flake/nix-index-database): `219067a5` -> `669ca1f2`

flake.lock
| [`bffc49ff`](https://github.com/nix-community/home-manager/commit/bffc49ffb255f213d2f902043da37b3016450f4a) | `` ripgrep: remove configDir `` |
=> chore(flake/home-manager): `29519461` -> `bffc49ff`

flake.lock
| [`57ed23cd`](https://github.com/nix-community/home-manager/commit/57ed23cd29e7b72518e19d2917e2b2880a94162c) | `` flake.lock: Update ``              |
| [`221056c5`](https://github.com/nix-community/home-manager/commit/221056c59ffab1e513fcf8ccb1079a8d44848fa9) | `` tests: fix `getOutput` on stubs `` |
=> chore(flake/home-manager): `bffc49ff` -> `57ed23cd`

flake.lock
| [`dd498255`](https://github.com/NixOS/nixpkgs/commit/dd4982554e18b936790da07c4ea2db7c7600f283) | `` hyperfine: 1.16.1 -> 0.17.0 (#235842) ``                                 |
| [`6ddd842a`](https://github.com/NixOS/nixpkgs/commit/6ddd842a4a90a700a6f997befd5f1d241f57873d) | `` python310Packages.bitarray: 2.7.3 -> 2.7.4 ``                            |
| [`12d0400e`](https://github.com/NixOS/nixpkgs/commit/12d0400e9b73c19145df3635a94e45ecc228d …
=> chore(flake/nixpkgs): `e6351928` -> `dd498255`

flake.lock
| [`607d8fad`](https://github.com/nix-community/home-manager/commit/607d8fad96436b134424b9935166a7cd0884003e) | `` i3-sway: quote output names (#4059) `` |
=> chore(flake/home-manager): `57ed23cd` -> `607d8fad`

flake.lock
| Commit                                                                                              | Message                                                                                 |
| --------------------------------------------------------------------------------------------------- | --------------------------------------------------------------------------------------- |
| [`8ef5b948`](https://github.com/serokell/deploy-rs/commit/8ef5b948e308d809cb7882036007e0ef9743acc8) | `` fixup! [#210] Add activation script for darwin system and provide a usage example `` |
| [`f4062956`](https://github.com/serokell/deploy-rs/commit/f4062956807a0a9703de166ac4a160a7aca1133c) | `` [#210] Add activation script for darwin system and provide a usage example ``        |
=> chore(flake/deploy-rs): `c8018991` -> `65211db6`

flake.lock
| [`3cae2f1c`](https://github.com/nix-community/lanzaboote/commit/3cae2f1c63afed69c3735d19e3056a4841ef8755) | `` fix(deps): update all dependencies `` |
=> chore(flake/lanzaboote): `e422970c` -> `45d04a45`

flake.lock
| Commit                                                                                                       | Message                                      |
| ------------------------------------------------------------------------------------------------------------ | -------------------------------------------- |
| [`24b41ae3`](https://github.com/cachix/pre-commit-hooks.nix/commit/24b41ae3048c0ad3c124ec6fe1771aa28eddf40f) | `` add lua-language-server typecheck/lint `` |
=> chore(flake/pre-commit-hooks): `ca2fdbf3` -> `238a10d4`

flake.lock
| [`2e5b4636`](https://github.com/NixOS/nixpkgs/commit/2e5b4636ffebf5fa32bb9680e16a6b75afb93ee9) | `` berglas: 1.0.2 -> 1.0.3 ``                                                |
| [`03c65919`](https://github.com/NixOS/nixpkgs/commit/03c659190515317c5164ae6239a9556b6c1ac12a) | `` zincsearch: 0.3.5 -> 0.4.5, rename from zinc (#218017) ``                 |
| [`b1efae4a`](https://github.com/NixOS/nixpkgs/commit/b1efae4a9edc0402c1611e86696bc92b3 …
=> chore(flake/nixpkgs): `dd498255` -> `7409480d`

flake.lock
| [`28614ed7`](https://github.com/nix-community/home-manager/commit/28614ed7a1e3ace824c122237bdc0e5e0b62c5c3) | `` lib: add functions to create DAGs from lists `` |
| [`79e03fbe`](https://github.com/nix-community/home-manager/commit/79e03fbe24dde6fe10662723870400d87a9cb40d) | `` lib: remove listOrDagOf type ``                 |
=> chore(flake/home-manager): `24d590cc` -> `28614ed7`

flake.lock
| Commit                                                                                        | Message                                                             |
| --------------------------------------------------------------------------------------------- | ------------------------------------------------------------------- |
| [`7bcf3ce6`](https://github.com/danth/stylix/commit/7bcf3ce6c9e9225e87d4e3b0c2e7d27a39954c02) | `` Fix palette generation when system does not use stylix (#106) `` |
=> chore(flake/stylix): `5989b015` -> `7bcf3ce6`

flake.lock
| Commit                                                                                                       | Message                                               |
| ------------------------------------------------------------------------------------------------------------ | ----------------------------------------------------- |
| [`a9f20d6d`](https://github.com/cachix/pre-commit-hooks.nix/commit/a9f20d6d1da97624e83a0053b69547b180e0c816) | `` fix(lua-ls): copied path to .luarc.json ``         |
| [`0af49116`](https://github.com/cachix/pre-commit-hooks.nix/commit/0af49116a254469c13b2f6946a519e39e268e245) | `` fix(lua-ls): correct typo ``                       |
| [`ac27fe1d`](https://github.com/cachix/pre-commit-hooks.nix/commit/ac27fe1daa19db5b78fda1d947de0b6859f21ddd) | `` Add …
=> chore(flake/pre-commit-hooks): `a117a1cd` -> `6881eb2a`

flake.lock
| [`39c7d0a9`](https://github.com/nix-community/home-manager/commit/39c7d0a97a77d3f31953941767a0822c94dc01f5) | `` imv: add module (#4032) `` |
| [`3512a6da`](https://github.com/nix-community/home-manager/commit/3512a6dafb7836cfceef00dcb29ce6f01c2ce280) | `` rtx: add module (#4051) `` |
=> chore(flake/home-manager): `28614ed7` -> `39c7d0a9`

flake.lock
| [`cc6745b3`](https://github.com/nix-community/home-manager/commit/cc6745b35fefe48624ebf573382e1e0e4a6fe85e) | `` aerc: add package option (#4065) `` |
=> chore(flake/home-manager): `39c7d0a9` -> `cc6745b3`

flake.lock
| [`257b5c19`](https://github.com/LnL7/nix-darwin/commit/257b5c199490aa073ab60c1d22d213025661dd44) | `` ssh: fix public keys in home directory not working ``  |
| [`9c7a07b8`](https://github.com/LnL7/nix-darwin/commit/9c7a07b8b2d476b6b9f574c8f35000c7c7fbbaf4) | `` system/checks: allow disabling the buildUsers check `` |
=> chore(flake/darwin): `4338bc86` -> `40e4b85b`

flake.lock
| Commit                                                                                                       | Message             |
| ------------------------------------------------------------------------------------------------------------ | ------------------- |
| [`d64b4d64`](https://github.com/cachix/pre-commit-hooks.nix/commit/d64b4d64e56fd1fcabb71b97ab54c6dcc36da3a5) | `` Add pyupgrade `` |
=> chore(flake/pre-commit-hooks): `6881eb2a` -> `182af512`

flake.lock
| [`cacf82c2`](https://github.com/NixOS/nixos-hardware/commit/cacf82c2b13d9bebe9b37df508385207a35001fb) | `` starfive visionfive2: u-boot: update to SDK version v3.0.4 `` |
| [`468a7a10`](https://github.com/NixOS/nixos-hardware/commit/468a7a108108908c7a35d6549f1e1f0236a9448a) | `` lenovo-thinkpad-x1-6th-gen: swap throttled with thermald ``   |
| [`61509d05`](https://github.com/NixOS/nixos-hardware/commit/61509d052c2c4444d66c5671ab5c3597e051eb1d) | …
=> chore(flake/nixos-hardware): `4cc688ee` -> `e4b34b90`

flake.lock
| [`8549e37e`](https://github.com/NixOS/nixpkgs/commit/8549e37ebcff8916da2977416941dc521f24da16) | `` bilibili: 1.10.1-1 -> 1.10.1-4 ``                                                        |
| [`e58b4a10`](https://github.com/NixOS/nixpkgs/commit/e58b4a101ba50a0a7e10015ec9996c39038e94c9) | `` bun: 0.6.6 -> 0.6.7 ``                                                                   |
| …
=> chore(flake/nixpkgs): `7409480d` -> `4729ffac`

flake.lock
| [`381e92a3`](https://github.com/NixOS/nixpkgs/commit/381e92a35e2d196fdd6077680dca0cd0197e75cb) | `` jasmin-compiler: 2022.09.2 → 2022.09.3 ``                                           |
| [`ffd47a04`](https://github.com/NixOS/nixpkgs/commit/ffd47a047d63053cbf327b9fbc9867fbbb21a113) | `` coqPackages.relation-algebra: init at 1.7.9 for Coq 8.17 ``                         |
| …
=> chore(flake/nixpkgs): `4729ffac` -> `381e92a3`

flake.lock
| [`f889ec0e`](https://github.com/nix-community/home-manager/commit/f889ec0ec366e3ad8fb94e3afa7a31f3ee1da3b9) | `` tests: `--show-trace` in CI (#4070) `` |
=> chore(flake/home-manager): `cc6745b3` -> `f889ec0e`

flake.lock
| [`69bdd6de`](https://github.com/nix-community/home-manager/commit/69bdd6de50df2082901d94dbf70ecb762d8b636c) | `` tests/stubs: inherit default versions from pkgs (#4069) `` |
=> chore(flake/home-manager): `f889ec0e` -> `69bdd6de`

flake.lock
| [`2bbfc3a7`](https://github.com/nix-community/home-manager/commit/2bbfc3a78afb4ea60345a5660d8d4173da66c884) | `` Translate using Weblate (Russian) ``              |
| [`7d07f8b6`](https://github.com/nix-community/home-manager/commit/7d07f8b6f9db338dffa9b11e047bf82efa4ad696) | `` Translate using Weblate (Chinese (Simplified)) `` |
=> chore(flake/home-manager): `69bdd6de` -> `2bbfc3a7`

flake.lock
| [`9b8ba302`](https://github.com/nix-community/home-manager/commit/9b8ba302ff38fe25b4a30c7dcafeb26d0ef37f9d) | `` Clean up deprecated lib functions (#4068) `` |
=> chore(flake/home-manager): `2bbfc3a7` -> `9b8ba302`

flake.lock
| Commit                                                                                         | Message                                                                                          |
| ---------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------------------ |
| [`7cd807e5`](https://github.com/NixOS/nixpkgs/commit/7cd807e5883736e1eeddb091b5774ee95af29869) | `` ocamlPackages.pgocaml: fix for OCaml 5.0 ``                                                   |
| [`7b77c9ed`](https://github.com/NixOS/nixpkgs/commit/7b77c9ed6375fa070e5db921442098ed45d8ae3d) | `` ocamlPackages.wasm: disable for OCaml ≥ 5.0 ``                                                |
| …
=> chore(flake/nixpkgs): `381e92a3` -> `a64b73e0`

flake.lock
| Commit                                                                                           | Message                                                |
| ------------------------------------------------------------------------------------------------ | ------------------------------------------------------ |
| [`1ba9ae3d`](https://github.com/LnL7/nix-darwin/commit/1ba9ae3d217c2285909232d635caeaf0e16ecd54) | `` darwin-installer: fix `/run` not getting created `` |
=> chore(flake/darwin): `40e4b85b` -> `7c16d313`

flake.lock
| Commit                                                                                                      | Message                                                                            |
| ----------------------------------------------------------------------------------------------------------- | ---------------------------------------------------------------------------------- |
| [`1e5d741e`](https://github.com/nix-community/home-manager/commit/1e5d741ea3f3290d7ac06a02ded24bfdc7aadb37) | `` Espanso: Fix broken module to be compatible with Espanso version 2.x (#4066) `` |
=> chore(flake/home-manager): `9b8ba302` -> `1e5d741e`

flake.lock
| [`000df987`](https://github.com/nix-community/home-manager/commit/000df987957b459b4e3de9e8977f95028e627424) | `` flake.lock: Update ``                           |
| [`e7fdcb40`](https://github.com/nix-community/home-manager/commit/e7fdcb40b2ddb79ed0b166e9694b361581c3dddb) | `` joshuto: add the joshuto file manager ``        |
| [`301b3648`](https://github.com/nix-community/home-manager/commit/301b3648927c050b224daa90cb4a99e4329456f2) | `` maintainers: add …
=> chore(flake/home-manager): `1e5d741e` -> `000df987`

flake.lock
| [`0945875a`](https://github.com/nix-community/home-manager/commit/0945875a2a20de314093b0f9d4d5448e9b4fdccb) | `` boxxy: add module (#4075) ``                                     |
| [`2a69182c`](https://github.com/nix-community/home-manager/commit/2a69182c569b190ae0d95244707db4d1209de6cf) | `` Revert "maintainers: add rasmus-kirk as a maintainer" (#4076) `` |
=> chore(flake/home-manager): `000df987` -> `0945875a`

flake.lock
| [`16f6a3bb`](https://github.com/NixOS/nixpkgs/commit/16f6a3bb7052dd8066ec33324a233be5be82ee84) | `` ical2orgpy: fix eval ``                                                         |
| [`652c7169`](https://github.com/NixOS/nixpkgs/commit/652c71692236f4d24a692b43d343fc9ba5ae306a) | `` frida-tools: fix eval ``                                                        |
| [`49de589a`](https://github.com/NixOS/nixpkgs/commit/49de589ae …
=> chore(flake/nixpkgs): `a64b73e0` -> `ae766d59`

flake.lock
| [`0144ac41`](https://github.com/nix-community/home-manager/commit/0144ac418ef633bfc9dbd89b8c199ad3a617c59f) | `` sway: add support for XDG autostart using systemd (#3747) `` |
=> chore(flake/home-manager): `0945875a` -> `0144ac41`

flake.lock
| [`cc942923`](https://github.com/NixOS/nixos-hardware/commit/cc942923915d500c83822b72edef50b6c649ab35) | `` starfive visionfive2: Add firmware update script. `` |
| [`54cc1a6c`](https://github.com/NixOS/nixos-hardware/commit/54cc1a6c79dd2cdb7698816cb2d40e257f2939d3) | `` hp.14-df0023: init ``                                |
=> chore(flake/nixos-hardware): `e4b34b90` -> `70d5f55f`

flake.lock
| Commit                                                                                                    | Message                                                                         |
| --------------------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------- |
| [`63bbfe35`](https://github.com/nix-community/lanzaboote/commit/63bbfe35d88c86a32f56b35677c84c1efec76687) | `` feat(stub): throw compile error in case of enabling fat and thin features `` |
=> chore(flake/lanzaboote): `45d04a45` -> `9f97a908`

flake.lock
| [`9967f8a7`](https://github.com/NixOS/nixpkgs/commit/9967f8a79680b98788d5e1eb765c9f3e12850c8b) | `` emacsPackages.beancount: init at 20230205.436 ``                              |
| [`dabcf529`](https://github.com/NixOS/nixpkgs/commit/dabcf529135db0708319c39eba05af2a8d639b73) | `` katriawm: 22.12 -> 23.04 ``                                                   |
| [`ca2cb9f6`](https://github.com/NixOS/nixpkgs/commit/ca2cb9f644458b1a7 …
=> chore(flake/nixpkgs): `ae766d59` -> `21951114`

flake.lock
| [`a2ca907b`](https://github.com/NixOS/nixos-hardware/commit/a2ca907b42e713fa3c5416fac4f2dd161cfa48d5) | `` lenovo-thinkpad-x1-nano-gen1: init `` |
=> chore(flake/nixos-hardware): `70d5f55f` -> `2a807ad6`

flake.lock
| [`e85f0c7c`](https://github.com/NixOS/nixpkgs/commit/e85f0c7cf6f7319a91674f11fccbbc9a8d5ca30f) | `` python310Packages.dnachisel: add format ``                               |
| [`f09bde4c`](https://github.com/NixOS/nixpkgs/commit/f09bde4cd04ea035b199537b28ccc72985693cde) | `` python310Packages.dnachisel: add changelog to meta ``                    |
| [`9401a0c7`](https://github.com/NixOS/nixpkgs/commit/9401a0c780b49faf6c28adf55764f230301d0 …
=> chore(flake/nixpkgs): `21951114` -> `75a5ebf4`

flake.lock
| [`9e37a1b6`](https://github.com/nix-community/home-manager/commit/9e37a1b6f9507ed27080518ff4007988a50c957e) | `` programs.joshuto: add the joshuto file manager (#4004) `` |
| [`b0cdae4e`](https://github.com/nix-community/home-manager/commit/b0cdae4e9baa188d69ba84aa1b7406b7bebe37f6) | `` browserpass: test on Darwin again (#4081) ``              |
=> chore(flake/home-manager): `0144ac41` -> `9e37a1b6`

flake.lock
| Commit                                                                                                    | Message                        |
| --------------------------------------------------------------------------------------------------------- | ------------------------------ |
| [`6bf1f559`](https://github.com/Mic92/nix-index-database/commit/6bf1f5593f768be3a6f3c86b256fa5e723b8155a) | `` enable swap to avoid oom `` |
=> chore(flake/nix-index-database): `669ca1f2` -> `6bf1f559`

flake.lock
| Commit                                                                                                    | Message                                                |
| --------------------------------------------------------------------------------------------------------- | ------------------------------------------------------ |
| [`7e83b70f`](https://github.com/Mic92/nix-index-database/commit/7e83b70f31f4483c07e6939166cb667ecb8d05d5) | `` update packages.nix to release 2023-06-12-124826 `` |
| [`cd017305`](https://github.com/Mic92/nix-index-database/commit/cd017305c32fbaa80524414d2df42eb327dabe05) | `` drop i686-linux from ci ``                          |
=> chore(flake/nix-index-database): `6bf1f559` -> `7e83b70f`

flake.lock
| Commit                                                                                                    | Message                                                                                  |
| --------------------------------------------------------------------------------------------------------- | ---------------------------------------------------------------------------------------- |
| [`b77ef07c`](https://github.com/nix-community/lanzaboote/commit/b77ef07cec5f94d7eeb39efcacb739f0017c6e37) | `` project: perform clippy/rustfmt checking via a higher order derivation transformer `` |
| [`5b228934`](https://github.com/nix-community/lanzaboote/commit/5b228934732ec0d6482a9ed6359bf48bb2d4fbb7) | `` project: move to nixpkgs Rust infrastructure `` …
=> chore(flake/lanzaboote): `9f97a908` -> `59e3ebb1`

flake.lock
| [`b01eb1eb`](https://github.com/nix-community/home-manager/commit/b01eb1eb3b579c74e6a4189ef33cc3fa24c40613) | `` Add infrastructure for contacts and calendars (#4078) `` |
=> chore(flake/home-manager): `9e37a1b6` -> `b01eb1eb`

flake.lock
| [`8da11353`](https://github.com/nix-community/home-manager/commit/8da1135365829e77fb5b17cfa4587860f306147f) | `` aerc: improve module (#3150) ``                |
| [`cbbceb48`](https://github.com/nix-community/home-manager/commit/cbbceb4894acb9750388e0cf535aa7a5663b207c) | `` offlineimap: Add package option (#4021) ``     |
| [`d437f0d4`](https://github.com/nix-community/home-manager/commit/d437f0d4e0f72fe76688142e954a4a9b61ac9833) | `` specialisation: fix path `` …
=> chore(flake/home-manager): `b01eb1eb` -> `8da11353`

flake.lock
| [`d9a97e8b`](https://github.com/nix-community/home-manager/commit/d9a97e8b33227a6086538ac2d3d1960b03ed940c) | `` calendars: add missing modules (#4087) `` |
=> chore(flake/home-manager): `8da11353` -> `d9a97e8b`

flake.lock
| Commit                                                                                                       | Message                                                           |
| ------------------------------------------------------------------------------------------------------------ | ----------------------------------------------------------------- |
| [`1d657159`](https://github.com/cachix/pre-commit-hooks.nix/commit/1d6571590bacc8f62da19d68444a312fed7f2ee9) | `` `dune-opam-sync` should also trigger on opam template files `` |
=> chore(flake/pre-commit-hooks): `182af512` -> `5b6b54d3`

flake.lock
| [`0d1e053c`](https://github.com/nix-community/home-manager/commit/0d1e053ce997f1dc181a0790c3b1ba2c76550ace) | `` vdirsyncer: Add missing include of services module (#4089) `` |
=> chore(flake/home-manager): `d9a97e8b` -> `0d1e053c`

flake.lock
| [`e4aa9fd8`](https://github.com/nix-community/home-manager/commit/e4aa9fd83b5c2d43b3c9c9de979a8675fcb8e563) | `` Translate using Weblate (Japanese) ``             |
| [`25230267`](https://github.com/nix-community/home-manager/commit/252302673da838acb7ea545c5b945037fce9ae22) | `` Translate using Weblate (Chinese (Simplified)) `` |
=> chore(flake/home-manager): `0d1e053c` -> `e4aa9fd8`

flake.lock
| Commit                                                                                        | Message                        |
| --------------------------------------------------------------------------------------------- | ------------------------------ |
| [`0015e563`](https://github.com/danth/stylix/commit/0015e56326ede9857a074ad2f442e7f86fc7b233) | `` Create style guide (#90) `` |
=> chore(flake/stylix): `7bcf3ce6` -> `0015e563`

flake.lock
| [`77777777`](https://github.com/nix-community/lanzaboote/commit/77777777007deffdd7237f7ce0690325c6bcc0eb) | `` Fix eval when aliases are disabled `` |
=> chore(flake/lanzaboote): `59e3ebb1` -> `823ad6b7`

flake.lock
| [`62f111ef`](https://github.com/nix-community/home-manager/commit/62f111ef1e50e518dbb3f0782a31dcd244a0a2d7) | `` ci: bump cachix/install-nix-action from 20 to 21 `` |
=> chore(flake/home-manager): `e4aa9fd8` -> `62f111ef`

flake.lock
| Commit                                                                                                    | Message                                                      |
| --------------------------------------------------------------------------------------------------------- | ------------------------------------------------------------ |
| [`fa3b6fa5`](https://github.com/Mic92/nix-index-database/commit/fa3b6fa51075a76fe3f1e949850ac55782834e3f) | `` add mergify ``                                            |
| [`5ca82658`](https://github.com/Mic92/nix-index-database/commit/5ca826583aae491e8c315adc348523825342e3c9) | `` flake.lock: Update ``                                     |
| [`7a4eef28`](https://github.com/Mic92/nix-index-database/commit/7a4eef2856307efecdde4db9b02ecbab9f812827) …
=> chore(flake/nix-index-database): `14eede94` -> `e11c6107`

flake.lock
| Commit                                                                                              | Message                                                   |
| --------------------------------------------------------------------------------------------------- | --------------------------------------------------------- |
| [`f28f8c60`](https://github.com/serokell/deploy-rs/commit/f28f8c6063dfdee3720a8841cc857df2c911dec8) | `` actually merge confirm_timeout into merged_settings `` |
=> chore(flake/deploy-rs): `65211db6` -> `724463b5`

flake.lock
| [`75b24cc5`](https://github.com/nix-community/home-manager/commit/75b24cc557d4947ab46691142863e5a5db5c3f78) | `` thunderbird: support aliases `` |
=> chore(flake/home-manager): `5db22bce` -> `75b24cc5`

flake.lock
| Commit                                                                                         | Message                                                                                            |
| ---------------------------------------------------------------------------------------------- | -------------------------------------------------------------------------------------------------- |
| [`fbb732ae`](https://github.com/NixOS/nixpkgs/commit/fbb732aebc1f375f2b5fb8e5d938c995864e8d2e) | `` wamr: use finalAttrs pattern ``                                                                 |
| [`3b0f5393`](https://github.com/NixOS/nixpkgs/commit/3b0f5393d9eb3a90ce4e4b0ed8d671a5ac977a46) | `` neovimUtils.grammarToPlugin: install tree-sitter grammars for neovim without nvim-treesitter `` | …
=> chore(flake/nixpkgs): `75a5ebf4` -> `0eeebd64`

flake.lock
| [`32376992`](https://github.com/nix-community/home-manager/commit/32376992f7ef4d7ae76dda690de5b23725fd8300) | `` qt: add "kde" to qt.platformTheme (#4085) `` |
=> chore(flake/home-manager): `75b24cc5` -> `32376992`

flake.lock
| [`194086df`](https://github.com/nix-community/home-manager/commit/194086df82d235919c1f8da68c4af2490d4675f9) | `` git-credential-oauth: add module `` |
=> chore(flake/home-manager): `32376992` -> `194086df`

flake.lock
| [`e0034971`](https://github.com/nix-community/home-manager/commit/e0034971f9def16bbc32124147787bc0f09f0e59) | `` comodoro: add module `` |
=> chore(flake/home-manager): `194086df` -> `e0034971`

flake.lock
| [`2ed58e3f`](https://github.com/NixOS/nixos-hardware/commit/2ed58e3fa29abb411dd921f15f820c4be1456bc4) | `` Removed extra overlay for kernel ``        |
| [`ba8b9209`](https://github.com/NixOS/nixos-hardware/commit/ba8b9209ce99b572b971678cb7f0341c2f20f518) | `` Add Microchip Icicle-kit board support. `` |
=> chore(flake/nixos-hardware): `2a807ad6` -> `429f232f`

flake.lock
| [`d214b93e`](https://github.com/nix-community/home-manager/commit/d214b93ee3c82b2746b85e8cb96bc150c6a74e50) | `` Add missing qt modules (#4094) `` |
=> chore(flake/home-manager): `e0034971` -> `d214b93e`

flake.lock
| [`4e09c832`](https://github.com/nix-community/home-manager/commit/4e09c83255c5b23d58714d56672d3946faf1bcef) | `` qt: bunch of fixes and updates (#4095) `` |
=> chore(flake/home-manager): `d214b93e` -> `4e09c832`

flake.lock
| [`ea2f1761`](https://github.com/nix-community/home-manager/commit/ea2f17615e31783ace1271a3325e9cac27c3b4d8) | `` khal: improve module (#4088) `` |
=> chore(flake/home-manager): `4e09c832` -> `ea2f1761`

flake.lock
| [`1c1a4c22`](https://github.com/NixOS/nixpkgs/commit/1c1a4c22de045a3ec53e16e2686007c55b421833) | `` Revert "quartoMinimal: 1.2.475 -> 1.3.361" ``                              |
| [`6a964f99`](https://github.com/NixOS/nixpkgs/commit/6a964f9965667667e4bfd243656b3165972fafb7) | `` docker-buildx: 0.10.5 -> 0.11.0 ``                                         |
| [`cc7f31d8`](https://github.com/NixOS/nixpkgs/commit/cc7f31d895199f5cb344d092c3d8c …
=> chore(flake/nixpkgs): `0eeebd64` -> `0d2cf7fe`

flake.lock
| [`9ba7b399`](https://github.com/nix-community/home-manager/commit/9ba7b3990eb1f4782ea3f5fe7ac4f3c88dd7a32c) | `` qt: fix breeze-qt5 path (#4098) `` |
=> chore(flake/home-manager): `ea2f1761` -> `9ba7b399`

flake.lock
| [`89afe706`](https://github.com/NixOS/nixpkgs/commit/89afe706797a64bebddc558e7b50d2862c15a40e) | `` libraspberrypi: build all binaries on 32-bit ARM ``                                 |
| [`5d486408`](https://github.com/NixOS/nixpkgs/commit/5d486408b510035c76b31d8d880c830d773b40a4) | `` opensmalltalk-vm: init at 202206021410 (#215158) ``                                 |
| …
=> chore(flake/nixpkgs): `0d2cf7fe` -> `7c67f006`

flake.lock
| Commit                                                                                            | Message                                                 |
| ------------------------------------------------------------------------------------------------- | ------------------------------------------------------- |
| [`13d91ca0`](https://github.com/lovesegfault/nix/commit/13d91ca08e005c387cf5d62a52de0283a1bda816) | `` feat: add always-allow-substitutes ``                |
| [`567a5f01`](https://github.com/lovesegfault/nix/commit/567a5f01465d83359cb57c0f265b90e849452415) | `` Remove old default from docs for `hashed-mirrors` `` |
| [`5b1b2569`](https://github.com/lovesegfault/nix/commit/5b1b25695c37087d214ea1cc32b91d7b5825754d) | `` Fix SourcePath::resolveSymlinks() ``                 |
=> chore(flake/nix): `6904fe14` -> `13d91ca0`

flake.lock
| [`7c06e70c`](https://github.com/NixOS/nixpkgs/commit/7c06e70c29690f41b9adbf3be04c069fd2526f95) | `` code-server: 4.13.0 -> 4.14.0 ``                                            |
| [`992ccdd8`](https://github.com/NixOS/nixpkgs/commit/992ccdd822ecff0712ed0004f89df9e96f6a4963) | `` github-runner: 2.304.0 -> 2.305.0 (#238138) ``                              |
| [`adf6bc1f`](https://github.com/NixOS/nixpkgs/commit/adf6bc1fc310f6db7d4bbb783 …
=> chore(flake/nixpkgs): `7c67f006` -> `04af42f3`

flake.lock
| [`edf9cf65`](https://github.com/nix-community/home-manager/commit/edf9cf65238609db16680be74fe28d4d4858476e) | `` home-manager: prioritize `-I` parameters ``            |
| [`f7c4dae2`](https://github.com/nix-community/home-manager/commit/f7c4dae2c818dc281ab73567f2fb6820c3597fb9) | `` Translate using Weblate (French) ``                    |
| [`162c17b0`](https://github.com/nix-community/home-manager/commit/162c17b0c9b9e3d80c7e731c03ad24157364432d) | …
=> chore(flake/home-manager): `9ba7b399` -> `edf9cf65`

flake.lock
| [`28c82303`](https://github.com/nix-community/home-manager/commit/28c823032cabfaa340a09e1d84cf45d11375c644) | `` Bump install-nix-action to v22 (#4111) `` |
=> chore(flake/home-manager): `edf9cf65` -> `28c82303`

flake.lock
| [`383d7306`](https://github.com/danth/stylix/commit/383d7306df0450603816852baf9b992a431bb82e) | `` Implemented Zellij Support (#108) `` |
=> chore(flake/stylix): `0015e563` -> `383d7306`

flake.lock
| Commit                                                                                                            | Message                                        |
| ----------------------------------------------------------------------------------------------------------------- | ---------------------------------------------- |
| [`849bc2be`](https://github.com/nix-community/nix-index-database/commit/849bc2be2a760d4d5f81a57167dcf8f2e7ddc1aa) | `` enable kvm system-feature for evaluation `` |
=> chore(flake/nix-index-database): `e11c6107` -> `d626d2e1`

flake.lock
| Commit                                                                                                            | Message                                                           |
| ----------------------------------------------------------------------------------------------------------------- | ----------------------------------------------------------------- |
| [`b94eda87`](https://github.com/nix-community/nix-index-database/commit/b94eda8739f8ac2d0dda6ad8e7f4e3d60bbf712a) | `` Update nix-install-action to get the latest version of nix. `` |
| [`2731e1d4`](https://github.com/nix-community/nix-index-database/commit/2731e1d49c88de4665c4862583767c0267f02069) | `` Exclude aarch64 VM test on Garnix. ``                          |
| …
=> chore(flake/nix-index-database): `d626d2e1` -> `a91d228c`

flake.lock
| Commit                                                                                                    | Message                                      |
| --------------------------------------------------------------------------------------------------------- | -------------------------------------------- |
| [`19a73124`](https://github.com/nix-community/lanzaboote/commit/19a731246292c333f6e19d5c56b3a5f3471a6422) | `` remove QUICK_START.md bootspec section `` |
=> chore(flake/lanzaboote): `823ad6b7` -> `9044916b`

flake.lock
| [`0480dabc`](https://github.com/nix-community/home-manager/commit/0480dabc99e1b669ebe909949180fa2786e733cd) | `` vdirsyncer: Fix service by moving the options before the command (#4109) `` |
=> chore(flake/home-manager): `28c82303` -> `0480dabc`

flake.lock
| [`75b3af82`](https://github.com/nix-community/nix-index-database/commit/75b3af8233366046bac5c15dbb7af6553b9fa49c) | `` Add --all-systems to nix flake show. ``             |
| [`5c566904`](https://github.com/nix-community/nix-index-database/commit/5c566904add58b532da327ffe0070889eef87618) | `` update packages.nix to release 2023-06-18-141259 `` |
=> chore(flake/nix-index-database): `a91d228c` -> `c8210cb3`

flake.lock
| [`1711db73`](https://github.com/LnL7/nix-darwin/commit/1711db734e29a2df3b1b72ec1e15bd50b0629fd1) | `` add ipfs service ``                            |
| [`8d13a55f`](https://github.com/LnL7/nix-darwin/commit/8d13a55f1c3020825400ef066ab13ef62ca441bf) | `` workflows: fix Nix install on `macos-12` ``    |
| [`f532e43f`](https://github.com/LnL7/nix-darwin/commit/f532e43f7efa58a0202956fac19f402893ae0ecd) | `` templates.flake: add contents of simple.nix `` |
| …
=> chore(flake/darwin): `7c16d313` -> `8a5af0da`

flake.lock
| Commit                                                                                                    | Message                                |
| --------------------------------------------------------------------------------------------------------- | -------------------------------------- |
| [`d791fc5c`](https://github.com/nix-community/lanzaboote/commit/d791fc5c357ef5c07a4080bcb320a66a032906f4) | `` remove QUICK_START.md sharp-edge `` |
=> chore(flake/lanzaboote): `9044916b` -> `c758cdad`

flake.lock
| [`a10aa82e`](https://github.com/nix-community/home-manager/commit/a10aa82e8aaee11d8e8b8c5e7e19f758a7553bf0) | `` docs: Document osConfig module argument (#4103) `` |
=> chore(flake/home-manager): `0480dabc` -> `a10aa82e`

flake.lock
| [`abfb11bd`](https://github.com/numtide/flake-utils/commit/abfb11bd1aec8ced1c9bb9adfe68018230f4fb3c) | `` Bump cachix/install-nix-action from 21 to 22 (#100) `` |
=> chore(flake/flake-utils): `a1720a10` -> `abfb11bd`

flake.lock
| [`6bdd72b9`](https://github.com/nix-community/home-manager/commit/6bdd72b914fc3472be807bc9b427650b49808a94) | `` clipman: wrong module name in description (#4117) `` |
=> chore(flake/home-manager): `a10aa82e` -> `6bdd72b9`

flake.lock
| [`f06a43dc`](https://github.com/nix-community/home-manager/commit/f06a43dca05fb7f1aa44742bf861d9c827b45122) | `` starship: add enable_transience for fish (#3975) `` |
=> chore(flake/home-manager): `6bdd72b9` -> `f06a43dc`

flake.lock
| Commit                                                                                                       | Message                                                         |
| ------------------------------------------------------------------------------------------------------------ | --------------------------------------------------------------- |
| [`a63f7150`](https://github.com/cachix/pre-commit-hooks.nix/commit/a63f71505767530fef5fa5fce49edf8957f7a825) | `` maint: Don't use literalDocBook ``                           |
| [`39f2e2ca`](https://github.com/cachix/pre-commit-hooks.nix/commit/39f2e2cacc567fc5b793e2155f2772a0722e96aa) | `` chore(deps): bump cachix/install-nix-action from 21 to 22 `` |
| [`bbe94664`](https://github.com/cachix/pre-commit-hooks.nix/commit/bbe946646559387 …
=> chore(flake/pre-commit-hooks): `5b6b54d3` -> `7807e185`

flake.lock
| [`cd87d923`](https://github.com/LnL7/nix-darwin/commit/cd87d92320bb32f250aefb2bc039c43bb3ffb7e2) | `` GHActions: Bump install-nix-action to v22 ``           |
| [`1fc5d125`](https://github.com/LnL7/nix-darwin/commit/1fc5d125fb14835ee12122395adb85b26c8f732e) | `` docs: clarify how to use inputs with flakes ``         |
| [`51b8bdfc`](https://github.com/LnL7/nix-darwin/commit/51b8bdfc0e43e24ebe097f167778d4e7fe88dd77) | `` nix: Add build machines protocol option. `` …
=> chore(flake/darwin): `8a5af0da` -> `ed275afb`

flake.lock
| [`e8b5f8f9`](https://github.com/nix-community/home-manager/commit/e8b5f8f9b3368dcc4814129d6f66c1af7cf3b6e5) | `` Update documentation to mention renamed option name. (#4126) `` |
=> chore(flake/home-manager): `f06a43dc` -> `e8b5f8f9`

flake.lock
| [`e6d134ce`](https://github.com/nix-community/home-manager/commit/e6d134ce12ed78c1ac31745853aa1e74310f1a7d) | `` home-environment: re-enable Nixpkgs release check ``   |
| [`ec58f8be`](https://github.com/nix-community/home-manager/commit/ec58f8bed77b2982560c66239ce170f3764f6a36) | `` borgmatic: add missing support for output and hooks `` |
=> chore(flake/home-manager): `e8b5f8f9` -> `e6d134ce`

flake.lock
| [`9a76fb9a`](https://github.com/nix-community/home-manager/commit/9a76fb9a852fdf9edd3b0aabc119efa1d618f969) | `` home-environment: allow skipping sanity checks `` |
| [`1b615306`](https://github.com/nix-community/home-manager/commit/1b615306089aafcf6b375adb1cb568511c00b143) | `` Translate using Weblate (German) ``               |
| [`da27ee44`](https://github.com/nix-community/home-manager/commit/da27ee446b7160081be1ef089c7843641a01d52e) | `` flake.lock: …
=> chore(flake/home-manager): `e6d134ce` -> `9a76fb9a`

flake.lock
| [`9ce6977f`](https://github.com/nix-community/home-manager/commit/9ce6977fe76fb408042a432e314764f8d1d86263) | `` himalaya: adjust module for 0.8.X (#4093) `` |
=> chore(flake/home-manager): `9a76fb9a` -> `9ce6977f`

flake.lock
| [`50cb4d8a`](https://github.com/nix-community/home-manager/commit/50cb4d8a1ef1240a54074addf081bd96dbbcab12) | `` programs.helix: add defaultEditor (#4127) `` |
=> chore(flake/home-manager): `9ce6977f` -> `50cb4d8a`

flake.lock
| [`1fefd7bb`](https://github.com/nix-community/home-manager/commit/1fefd7bb8da0eec6755747f410fa491411a94296) | `` gtk: Add gtk4.extraCss option (#4133) `` |
=> chore(flake/home-manager): `50cb4d8a` -> `1fefd7bb`

flake.lock
| [`737cfdec`](https://github.com/LnL7/nix-darwin/commit/737cfdec9ce54eed56b4f9c281bbd892ebf5dc6b) | `` eval-config.nix: readd `lib.mdDoc` temporarily `` |
=> chore(flake/darwin): `ed275afb` -> `bc346a67`

flake.lock
| Commit                                                                                                      | Message                                                                            |
| ----------------------------------------------------------------------------------------------------------- | ---------------------------------------------------------------------------------- |
| [`a4817894`](https://github.com/nix-community/home-manager/commit/a4817894576f9cd01d784e60a0bfb143c81fc2be) | `` treewide: remove marsam as maintainer (#4136) ``                                |
| [`29358e8b`](https://github.com/nix-community/home-manager/commit/29358e8be7e93c75cc0248a077db528e8617a507) | `` starship: Remove INSIDE_EMACS checks when enabling shell integration (#4135) `` |
=> chore(flake/home-manager): `1fefd7bb` -> `a4817894`

flake.lock
| [`6c78ba79`](https://github.com/nix-community/home-manager/commit/6c78ba7932567331fb8ebabf34a143b998bb5f23) | `` docs/contributing: link to NMT's bash-lib (#4125) `` |
=> chore(flake/home-manager): `a4817894` -> `6c78ba79`

flake.lock
| [`b9046172`](https://github.com/nix-community/home-manager/commit/b9046172a580a648045e7c2f7077cc143936ad8f) | `` Add translation using Weblate (Indonesian) `` |
| [`91df8b34`](https://github.com/nix-community/home-manager/commit/91df8b34719aeb158e89fcef28e8e5f4ccaada36) | `` Translate using Weblate (Indonesian) ``       |
=> chore(flake/home-manager): `6c78ba79` -> `b9046172`

flake.lock
| [`70ac1887`](https://github.com/nix-community/home-manager/commit/70ac18872a5f1a57a4546ff58888bf67a8bbb5b3) | `` antidote: add module `` |
=> chore(flake/home-manager): `b9046172` -> `70ac1887`

flake.lock
| [`d2b6f2d1`](https://github.com/nix-community/home-manager/commit/d2b6f2d154bf6b27a93ed895392f80c503df7cfa) | `` zellij: fix module description for shell integrations `` |
| [`491f74db`](https://github.com/nix-community/home-manager/commit/491f74db894b5c5843a9e4b123aa773e1b21583f) | `` antidote: fix package source path ``                     |
=> chore(flake/home-manager): `70ac1887` -> `d2b6f2d1`

flake.lock
| [`fbb3ab94`](https://github.com/LnL7/nix-darwin/commit/fbb3ab94e67bab73e721d5bbbcc6b05b0cf60f2f) | `` activity monitor: change settings to null `` |
=> chore(flake/darwin): `bc346a67` -> `6460468e`

flake.lock
| [`29872a1c`](https://github.com/nix-community/home-manager/commit/29872a1c8f5ed2fde270afb0583d1fabce5e0459) | `` docs: update nmd `` |
=> chore(flake/home-manager): `d2b6f2d1` -> `29872a1c`

flake.lock
| [`68aebb45`](https://github.com/nix-community/home-manager/commit/68aebb45de644b81a71f0c7b8b22ad51c9a0df7a) | `` fish: follow links to find man pages ``                |
| [`b59f682e`](https://github.com/nix-community/home-manager/commit/b59f682e860185e0670148d44be290c469bcc300) | `` fish: consider man pages from extraOutputsToInstall `` |
| [`28b6c367`](https://github.com/nix-community/home-manager/commit/28b6c3670cbfab9ff78e6de8cd38f93ec42d253b) | …
=> chore(flake/home-manager): `29872a1c` -> `68aebb45`

flake.lock
| Commit                                                                                                      | Message              |
| ----------------------------------------------------------------------------------------------------------- | -------------------- |
| [`172d46d4`](https://github.com/nix-community/home-manager/commit/172d46d4b2677b32277d903bdf4cff77c2cc6477) | `` docs: bump nmd `` |
=> chore(flake/home-manager): `68aebb45` -> `172d46d4`

flake.lock
| [`3ae20aa5`](https://github.com/NixOS/nixpkgs/commit/3ae20aa58a6c0d1ca95c9b11f59a2d12eebc511f) | `` ocamlPackages.domain-local-await: 0.2.0 → 0.2.1 ``                     |
| [`826f484b`](https://github.com/NixOS/nixpkgs/commit/826f484b8de1f2d8dff4b7156a09d675e9e4b8d1) | `` ocamlPackages.thread-table: init at 0.1.0 ``                           |
| [`0e07d132`](https://github.com/NixOS/nixpkgs/commit/0e07d132c5a562f43e823b6b4a0004ed2d91f40e) | …
=> chore(flake/nixpkgs): `04af42f3` -> `3ae20aa5`

flake.lock
| [`9d6702cf`](https://github.com/LnL7/nix-darwin/commit/9d6702cf2b81f5d0ef9d628d99e8deb45f84b454) | `` eval-config: remove compatibility shims ``           |
| [`42d1643e`](https://github.com/LnL7/nix-darwin/commit/42d1643e7a79aa9a0c6bf50e5944fec4e5c492f2) | `` {ci,readme}: update stable nixpkgs to 23.05 ``       |
| [`69648c6c`](https://github.com/LnL7/nix-darwin/commit/69648c6cbbecf34c327d73e36b5aed32edfb9ed9) | `` doc/manual: use `nixos-render-docs` ``               |
| …
=> chore(flake/darwin): `6460468e` -> `ace0ef2a`

flake.lock
| [`0ee5ab61`](https://github.com/nix-community/home-manager/commit/0ee5ab611dc1fbb5180bd7d88d2aeb7841a4d179) | `` ci: build manual and push to home-manager.dev `` |
=> chore(flake/home-manager): `172d46d4` -> `0ee5ab61`

flake.lock
| [`a62f16b9`](https://github.com/LnL7/nix-darwin/commit/a62f16b94dff6ad5835ec6beb992e09e76bc2fe6) | `` readme: update links for redirect ``              |
| [`df03a145`](https://github.com/LnL7/nix-darwin/commit/df03a145b36f4787ef033589159129a1c936a643) | `` ci: update manual updater to 23.05 ``             |
| [`f253b41d`](https://github.com/LnL7/nix-darwin/commit/f253b41de83c9f34fba9eda66cc42b90e10937c7) | `` buildkite-agent: fix launcd daemon environment `` |
=> chore(flake/darwin): `ace0ef2a` -> `53c6748f`

flake.lock
| Commit                                                                                           | Message                              |
| ------------------------------------------------------------------------------------------------ | ------------------------------------ |
| [`25ae710b`](https://github.com/LnL7/nix-darwin/commit/25ae710ba3cd448c5d5678788d37f3d149378bc0) | `` also update README in gh-pages `` |
| [`cb37c35e`](https://github.com/LnL7/nix-darwin/commit/cb37c35e33239b844203987fff18f91370939921) | `` fix darwin-option descriptions `` |
=> chore(flake/darwin): `53c6748f` -> `25ae710b`

flake.lock
| Commit                                                                                               | Message              |
| ---------------------------------------------------------------------------------------------------- | -------------------- |
| [`dbabf0ca`](https://github.com/numtide/flake-utils/commit/dbabf0ca0c0c4bce6ea5eaf65af5cb694d2082c7) | `` Add meld (#99) `` |
=> chore(flake/flake-utils): `abfb11bd` -> `dbabf0ca`

flake.lock
| Commit                                                                                         | Message                                                        |
| ---------------------------------------------------------------------------------------------- | -------------------------------------------------------------- |
| [`e43d080e`](https://github.com/NixOS/nixpkgs/commit/e43d080ed7a97347e4a58ef9d8402f9cfcfb79bd) | `` python310Packages.mkdocs-swagger-ui-tag: 0.6.1 -> 0.6.2 ``  |
| [`636db898`](https://github.com/NixOS/nixpkgs/commit/636db898ebbb8856320fe6d2472d79e18f88d5c7) | `` lib.licenses: add Sustainable Use License (#239455) ``      |
| [`3a3654c8`](https://github.com/NixOS/nixpkgs/commit/3a3654c83678de3fbe59bca88483a5bb2b435f0b) | `` jellyfin-media-player: add aarch64-linux …
=> chore(flake/nixpkgs): `3ae20aa5` -> `1c9db971`

flake.lock
| Commit                                                                                                       | Message                |
| ------------------------------------------------------------------------------------------------------------ | ---------------------- |
| [`a35f6ac9`](https://github.com/cachix/pre-commit-hooks.nix/commit/a35f6ac90aebf85bfc22e943601d708667e01ac0) | `` Add crystal hook `` |
=> chore(flake/pre-commit-hooks): `7807e185` -> `1fa438ee`

flake.lock
| [`4c08f65a`](https://github.com/nix-community/home-manager/commit/4c08f65ab5105a55eed3fc9003f3e6874b69fe13) | `` broot: fix test (#4170) `` |
| [`3bc1bc40`](https://github.com/nix-community/home-manager/commit/3bc1bc40121eb0975dc3d96741300bb4fd16be29) | `` antidote: fix .dot path `` |
=> chore(flake/home-manager): `0ee5ab61` -> `4c08f65a`

flake.lock
| [`7dfce721`](https://github.com/danth/stylix/commit/7dfce721b923549a773bf32c16515ebf1a509dae) | `` Fix Zellij selection highlight (#112) ``                          |
| [`91979967`](https://github.com/danth/stylix/commit/9197996704df974a073d83e3c793b8e11282fa11) | `` Fix Actions workflow on MacOS :construction_worker: :arrow_up: `` |
=> chore(flake/stylix): `383d7306` -> `7dfce721`

flake.lock
| [`9dd107a1`](https://github.com/nix-community/home-manager/commit/9dd107a1d5395fae9b969597e02f3ef3a43ddd47) | `` flake: add formatter (#3620) `` |
=> chore(flake/home-manager): `4c08f65a` -> `9dd107a1`

flake.lock
| [`47c2adc6`](https://github.com/nix-community/home-manager/commit/47c2adc6b31e9cff335010f570814e44418e2b3e) | `` docs: update link to allowed users setting (#4176) ``           |
| [`f5f64ac0`](https://github.com/nix-community/home-manager/commit/f5f64ac022ed379442286a4e81a2a7cdc552cb28) | `` zsh: allow setting custom syntax highlighting styles (#4122) `` |
=> chore(flake/home-manager): `9dd107a1` -> `47c2adc6`

flake.lock
| [`a7002d6b`](https://github.com/nix-community/home-manager/commit/a7002d6bfca54742d5fc9b485a1879953b4585b9) | `` kakoune: add defaultEditor option `` |
=> chore(flake/home-manager): `47c2adc6` -> `a7002d6b`

flake.lock
| Commit                                                                                                       | Message                                          |
| ------------------------------------------------------------------------------------------------------------ | ------------------------------------------------ |
| [`31522e85`](https://github.com/cachix/pre-commit-hooks.nix/commit/31522e851a65b5bafe9292395d61e12a37c0597c) | `` Get rid of the runtime dependency in OCaml `` |
| [`ed3d3d1f`](https://github.com/cachix/pre-commit-hooks.nix/commit/ed3d3d1fc1febb4e9e9cf041cc7af01d8f2afbf0) | `` Add a hook for `headache` ``                  |
=> chore(flake/pre-commit-hooks): `5843cf06` -> `522fd47a`

flake.lock
| Commit                                                                                           | Message                                                       |
| ------------------------------------------------------------------------------------------------ | ------------------------------------------------------------- |
| [`89ec258c`](https://github.com/LnL7/nix-darwin/commit/89ec258c7cac6d83f673ae5e4ce170bfc2c1f615) | `` documentation: Link to nixpkgs master if rev is unknown `` |
| [`d207fa60`](https://github.com/LnL7/nix-darwin/commit/d207fa609121341fe214b70b24fd4b12ae1e8737) | `` default.nix: Use nixpkgs.rev if it is set ``               |
| [`9af7fe60`](https://github.com/LnL7/nix-darwin/commit/9af7fe60b6a4ab990a95478a89f1bdd1c7517510) | `` feat(darwin-rebuild): support …
=> chore(flake/darwin): `25ae710b` -> `43587cdb`

flake.lock
| [`17ce23ea`](https://github.com/nix-community/home-manager/commit/17ce23ea56aeecbd01dfeb08f6a7902c80f27311) | `` lsd: use -A instead of -a in aliases (#4173) `` |
=> chore(flake/home-manager): `a7002d6b` -> `17ce23ea`

flake.lock
| [`0f710127`](https://github.com/nix-community/home-manager/commit/0f71012724b151aa02c8f05f2dc0e121e7a4371e) | `` README: Remove the pills (#4181) `` |
=> chore(flake/home-manager): `17ce23ea` -> `0f710127`

flake.lock
| [`44d1a854`](https://github.com/nix-community/home-manager/commit/44d1a8542ac92f0ce75d970090216245043a2709) | `` sxhkd: allow usage of derivations as keybind commands (#4169) `` |
=> chore(flake/home-manager): `0f710127` -> `44d1a854`

flake.lock
| [`7a0e9a67`](https://github.com/nix-community/home-manager/commit/7a0e9a67824aa05f972459aefc2caafe6fdc0f88) | `` chromium: fix `commandLineArgs` to use the user specified package (#4175) `` |
=> chore(flake/home-manager): `44d1a854` -> `7a0e9a67`

flake.lock
| [`89d10f8a`](https://github.com/nix-community/home-manager/commit/89d10f8adce369a80e046c2fd56d1e7b7507bb5b) | `` news: fix typo in programs.zsh.antidote entry `` |
| [`2d9210f2`](https://github.com/nix-community/home-manager/commit/2d9210f25ed18d5d4e11e6b886de4027c0c51a94) | `` ssh-agent: init module (#4178) ``                |
=> chore(flake/home-manager): `7a0e9a67` -> `89d10f8a`

flake.lock
| Commit                                                                                         | Message                                                                  |
| ---------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------ |
| [`7f9d0dca`](https://github.com/NixOS/nixpkgs/commit/7f9d0dcaccf83c7592bf42fe5b304f669eae3a36) | `` labeler: label nodejs pull-requests ``                                |
| [`78e7de27`](https://github.com/NixOS/nixpkgs/commit/78e7de270c22bde17f24b70952604e4b6a5b53c7) | `` charasay: 2.1.0 -> 3.0.0 ``                                           |
| [`fd42e163`](https://github.com/NixOS/nixpkgs/commit/fd42e1630e8ee0985cea8f67a51e6a09a940d729) | `` …
=> chore(flake/nixpkgs): `6b3d1b1c` -> `4ffc4dc9`

flake.lock
| Commit                                                                                         | Message                                                                                                  |
| ---------------------------------------------------------------------------------------------- | -------------------------------------------------------------------------------------------------------- |
| [`e470bc2b`](https://github.com/NixOS/nixpkgs/commit/e470bc2b48321381838625d9782efa651fd5c0ad) | `` turbovnc: 3.0.1 -> 3.0.3 ``                                                                           |
| [`e824b1bd`](https://github.com/NixOS/nixpkgs/commit/e824b1bd18d8c548e313555104ab9273d2a86432) | `` gimoji: 0.5.0 -> 0.5.1 `` …
=> chore(flake/nixpkgs): `4ffc4dc9` -> `645ff62e`

flake.lock
| [`c85d9137`](https://github.com/nix-community/home-manager/commit/c85d9137db45a1c9c161f4718b13cc3bd4cbd173) | `` ci: autolabel calendars PRs (#4165) `` |
| [`53c75ac2`](https://github.com/nix-community/home-manager/commit/53c75ac2e6de7eb6f4837a0f1abf55abe013afad) | `` flake.lock: Update (#4161) ``          |
=> chore(flake/home-manager): `89d10f8a` -> `c85d9137`

flake.lock
| Commit                                                                                           | Message                                 |
| ------------------------------------------------------------------------------------------------ | --------------------------------------- |
| [`d2b70c61`](https://github.com/LnL7/nix-darwin/commit/d2b70c61bf5555df5f81bfa9b05c341cf68463b9) | `` tailscale: improve MagicDNS setup `` |
=> chore(flake/darwin): `43587cdb` -> `b06bab83`

flake.lock
| [`35cab8eb`](https://github.com/danth/stylix/commit/35cab8eb76c1d3672b2b290a64f357847c30d090) | `` Set fonts in gnome module (#116) `` |
=> chore(flake/stylix): `7dfce721` -> `35cab8eb`

flake.lock
| Commit                                                                                                       | Message                        |
| ------------------------------------------------------------------------------------------------------------ | ------------------------------ |
| [`27375222`](https://github.com/cachix/pre-commit-hooks.nix/commit/27375222d4e4e4a5b0516249aa44374b5baeeb48) | `` hooks.nix: string -> str `` |
=> chore(flake/pre-commit-hooks): `522fd47a` -> `42587d34`

flake.lock
| [`8c66b46a`](https://github.com/nix-community/home-manager/commit/8c66b46a86afa21763766ef97d7c8be5f3954e2b) | `` home-manager: Use `path:` URI type for flake default (#3646) `` |
=> chore(flake/home-manager): `c85d9137` -> `8c66b46a`

flake.lock
| [`c24deeca`](https://github.com/nix-community/home-manager/commit/c24deeca64538dcbc589ed8da9146e4ca9eb85b7) | `` xfconf: remove properties with null values (#4192) `` |
=> chore(flake/home-manager): `8c66b46a` -> `c24deeca`

flake.lock
| [`3be2abb2`](https://github.com/nix-community/home-manager/commit/3be2abb2e6df41d9ddd5816032adf91691328225) | `` i18n: Use glibcLocales from NixOS if possible (#2333) (#4177) `` |
=> chore(flake/home-manager): `c24deeca` -> `3be2abb2`

flake.lock
| [`b40eaf23`](https://github.com/NixOS/nixpkgs/commit/b40eaf233717e7f8d4368f974759c2a8f151052f) | `` buildkite-agent: 3.48.0 -> 3.49.0 (#241141) ``                              |
| [`ac4790a8`](https://github.com/NixOS/nixpkgs/commit/ac4790a84edc4ef5cf8ba3e97f1155190ee3eace) | `` nixos/jenkins-job-builder: Fix link to documentation, use mkEnableOption `` |
| [`ec0bc24a`](https://github.com/NixOS/nixpkgs/commit/ec0bc24ae9b4bc40476d7f2be …
=> chore(flake/nixpkgs): `645ff62e` -> `0fbe93c5`

flake.lock
| [`b406b8d1`](https://github.com/nix-community/home-manager/commit/b406b8d1bc90f6cd3e120d189b3e929f17ca4aea) | `` PULL_REQUEST_TEMPLATE.md: add maintainer cc section (#4193) `` |
| [`4a26e210`](https://github.com/nix-community/home-manager/commit/4a26e21030a6ea9adbcc967812286bbe71fe45c5) | `` programs.khal ``                                               |
| [`d895a774`](https://github.com/nix-community/home-manager/commit/d895a774489c …
=> chore(flake/home-manager): `3be2abb2` -> `b406b8d1`

flake.lock
| [`2f78e6fc`](https://github.com/nix-community/home-manager/commit/2f78e6fcba61ce81536d19e6c662e55ab272d539) | `` antidote: static file move to /tmp ``   |
| [`b66af0ac`](https://github.com/nix-community/home-manager/commit/b66af0ac666d01f95c8f83e60b02a851700c048c) | `` Translate using Weblate (Indonesian) `` |
=> chore(flake/home-manager): `b406b8d1` -> `2f78e6fc`

flake.lock
| [`9ef5b7d7`](https://github.com/NixOS/nixpkgs/commit/9ef5b7d793a0ac1f1742696b5ec668169ff9c80d) | `` nixos/x11: change the description of the display manager service ``               |
| [`bd3da6b6`](https://github.com/NixOS/nixpkgs/commit/bd3da6b6f2afda870927f55290169f91198675be) | `` csvquote: fix typo ``                                                             |
| …
=> chore(flake/nixpkgs): `0fbe93c5` -> `78419eda`

flake.lock
| [`b23c7501`](https://github.com/nix-community/home-manager/commit/b23c7501f7e0a001486c9a5555a6c53ac7b08e85) | `` i3: remove deprecated example in i3.config.startup (#4201) `` |
=> chore(flake/home-manager): `2f78e6fc` -> `b23c7501`

flake.lock
| Commit                                                                                                       | Message                                       |
| ------------------------------------------------------------------------------------------------------------ | --------------------------------------------- |
| [`57b845f5`](https://github.com/cachix/pre-commit-hooks.nix/commit/57b845f5f8f31ac0c48f449d17c9caa1c2f07291) | `` Do not print "hooks up to date" message `` |
=> chore(flake/pre-commit-hooks): `f6a6863a` -> `8d316204`

flake.lock
| Commit                                                                                                       | Message                                              |
| ------------------------------------------------------------------------------------------------------------ | ---------------------------------------------------- |
| [`658bf06b`](https://github.com/cachix/pre-commit-hooks.nix/commit/658bf06b1691f76803527ce0eda660620a03a161) | `` Only run `typos` against text files by default `` |
=> chore(flake/pre-commit-hooks): `8d316204` -> `c8d18ba3`

flake.lock
| [`23de9f3b`](https://github.com/NixOS/nixpkgs/commit/23de9f3b56e72632c628d92b71c47032e14a3d4d) | `` electron_25-bin: 25.1.1 -> 25.2.0 ``                                              |
| [`d05f851f`](https://github.com/NixOS/nixpkgs/commit/d05f851f77e889e934920c9986540332643da85b) | `` electron_24-bin: 24.4.1 -> 24.5.1 ``                                              |
| …
=> chore(flake/nixpkgs): `78419eda` -> `f292b496`

flake.lock
| Commit                                                                                                            | Message                                |
| ----------------------------------------------------------------------------------------------------------------- | -------------------------------------- |
| [`4d5a3eec`](https://github.com/nix-community/nix-index-database/commit/4d5a3eec1dc9dbc5c2718ea955a0928f1a3567fd) | `` flake.lock: Update ``               |
| [`bb486d01`](https://github.com/nix-community/nix-index-database/commit/bb486d01163c91c0c0b8f18557dadc518c5a9934) | `` Fix flake lock step in workflow. `` |
=> chore(flake/nix-index-database): `c8210cb3` -> `4d5a3eec`

flake.lock
| Commit                                                                                                            | Message                                                                    |
| ----------------------------------------------------------------------------------------------------------------- | -------------------------------------------------------------------------- |
| [`44337c30`](https://github.com/nix-community/nix-index-database/commit/44337c30729a3616c7a71d485af70d231b29675a) | `` update packages.nix to release 2023-07-06-220047 ``                     |
| [`b55bac3e`](https://github.com/nix-community/nix-index-database/commit/b55bac3e4eda652cf6f850a6bb25ed9377552b8b) | `` Use correct syntax to get the ref. ``                                   |
| …
=> chore(flake/nix-index-database): `4d5a3eec` -> `44337c30`

flake.lock
| [`719de878`](https://github.com/nix-community/home-manager/commit/719de878f75b293eb3a8ab30943ae6ecf458c0a4) | `` imapnotify: Add launchd agent (#3291) `` |
=> chore(flake/home-manager): `b23c7501` -> `719de878`

flake.lock
| Commit                                                                                        | Message                            |
| --------------------------------------------------------------------------------------------- | ---------------------------------- |
| [`fea4469c`](https://github.com/danth/stylix/commit/fea4469ce1897012e9dbf8d1fb3e7967fb99dcae) | `` Added WezTerm Support (#119) `` |
=> chore(flake/stylix): `35cab8eb` -> `fea4469c`

flake.lock
| [`34db2f05`](https://github.com/nix-community/home-manager/commit/34db2f05219bcb0e41cc85490e4c338e2405546c) | `` unison: Allow using same option multiple times (#4208) `` |
=> chore(flake/home-manager): `719de878` -> `34db2f05`

flake.lock
| Commit                                                                                                | Message                                                                         |
| ----------------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------- |
| [`30f71ba6`](https://github.com/NixOS/nixos-hardware/commit/30f71ba6e0ce7c26d103bd383ca30c4c9d179a5a) | `` star64: init ``                                                              |
| [`ff35653b`](https://github.com/NixOS/nixos-hardware/commit/ff35653b1493d6ae27acb04bf6851e095b23ffea) | `` starfive visionfive2: update kernel to 6.4.0 ``                              |
| …
=> chore(flake/nixos-hardware): `429f232f` -> `47dca15d`

flake.lock
| [`04eceedb`](https://github.com/NixOS/nixpkgs/commit/04eceedb4fe3641224e776efd7fc6d4a57aa5731) | `` fdm: Install helper script, manual, and examples (#241310) ``             |
| [`a123917a`](https://github.com/NixOS/nixpkgs/commit/a123917a0726974ea1bab1ffebb49201c6c1256f) | `` ocamlPackages.seqes: disable for OCaml < 4.14 & enable tests ``           |
| [`1502e8a5`](https://github.com/NixOS/nixpkgs/commit/1502e8a52cce39f9a31bfddefaf0b7aa3 …
=> chore(flake/nixpkgs): `f292b496` -> `3c748757`

flake.lock
| [`050d01a6`](https://github.com/nix-community/home-manager/commit/050d01a62cfe19642fb193084acf34a428a67223) | `` darcs: add module ``                               |
| [`af715ed8`](https://github.com/nix-community/home-manager/commit/af715ed857f9d94086e4ef833949944bf0322521) | `` tests: some minor cleanups ``                      |
| [`f288310b`](https://github.com/nix-community/home-manager/commit/f288310b7adf9775e405f251eb4920969fd8afa5) | `` …
=> chore(flake/home-manager): `34db2f05` -> `050d01a6`

flake.lock
| Commit                                                                                                      | Message                 |
| ----------------------------------------------------------------------------------------------------------- | ----------------------- |
| [`069d450b`](https://github.com/nix-community/home-manager/commit/069d450b6d2da9369ee5a8ddb2dbf909d3535471) | `` pyenv: add module `` |
=> chore(flake/home-manager): `050d01a6` -> `069d450b`

flake.lock
| [`98282a48`](https://github.com/nix-community/home-manager/commit/98282a481df50d357e9cbfa7e6a6d481df37e8c2) | `` swayosd: add module `` |
=> chore(flake/home-manager): `069d450b` -> `98282a48`

flake.lock
| [`24805d3c`](https://github.com/nix-community/home-manager/commit/24805d3ca73f7d4c34239efaa1c73d2d4558a8ea) | `` himalaya: fix notmuch backend `` |
=> chore(flake/home-manager): `98282a48` -> `24805d3c`

flake.lock
| [`ba5565d6`](https://github.com/danth/stylix/commit/ba5565d6989954ad3846245a5b4b122e4dba76d0) | `` Refactor palette generator :recycle: `` |
=> chore(flake/stylix): `c354350b` -> `ba5565d6`

flake.lock
| Commit                                                                                           | Message                       |
| ------------------------------------------------------------------------------------------------ | ----------------------------- |
| [`d2b01ab4`](https://github.com/LnL7/nix-darwin/commit/d2b01ab455cb3fcae531fecc5fd23947dd102065) | `` nix/linux-builder: init `` |
=> chore(flake/darwin): `b06bab83` -> `4272af40`

flake.lock
| [`e15010ee`](https://github.com/nix-community/home-manager/commit/e15010ee6e9bd356a6746ff9b9f9a9097ee8ddcf) | `` nushell: add login.nu configuration option `` |
=> chore(flake/home-manager): `24805d3c` -> `e15010ee`

flake.lock
| [`75711474`](https://github.com/nix-community/nix-index-database/commit/757114749d4613cf71f3748e780a1be8a67a5d3c) | `` update packages.nix to release 2023-07-09-034646 `` |
| [`0f0adadf`](https://github.com/nix-community/nix-index-database/commit/0f0adadf026172cef1d7eef9011baaaf7d8b4cad) | `` flake.lock: Update ``                               |
=> chore(flake/nix-index-database): `44337c30` -> `75711474`

flake.lock
| Commit                                                                                           | Message                                    |
| ------------------------------------------------------------------------------------------------ | ------------------------------------------ |
| [`d9e825f1`](https://github.com/LnL7/nix-darwin/commit/d9e825f121784a7628ae177a04cb80709043e0fe) | `` linux-builder: fix evaluation errors `` |
=> chore(flake/darwin): `4272af40` -> `4e3fc186`

flake.lock
| [`86157256`](https://github.com/nix-community/home-manager/commit/86157256d2e0d257c53eefeb008230f043e12210) | `` flake.lock: Update `` |
=> chore(flake/home-manager): `e15010ee` -> `86157256`

flake.lock
| [`b70db52f`](https://github.com/nix-community/home-manager/commit/b70db52ff06f30e3de7f21b6ea47e75baa0c46f6) | `` imapnotify: move test ``                            |
| [`fad47555`](https://github.com/nix-community/home-manager/commit/fad475553ae2de3ba1dbcab980698ac070d04e72) | `` imapnotify: use direct nix store path for config `` |
=> chore(flake/home-manager): `86157256` -> `b70db52f`

flake.lock
| [`f9724c45`](https://github.com/LnL7/nix-darwin/commit/f9724c4543035d6190c00168ebfa93f0b2e927d0) | `` eval-config: rationalize handling of Nixpkgs ``       |
| [`51ba5e61`](https://github.com/LnL7/nix-darwin/commit/51ba5e614acf1c94d519e6047814219082827faa) | `` version: rewrite Git revision logic ``                |
| [`72b7e866`](https://github.com/LnL7/nix-darwin/commit/72b7e8668c24950b8300ffe3d135dad1ae72a4f5) | `` version: default Git revision options to `null` ``    | …
=> chore(flake/darwin): `4e3fc186` -> `66a3047f`

flake.lock
| [`7f46848e`](https://github.com/NixOS/nixos-hardware/commit/7f46848ea6f8755264be8cd37376bb068c185142) | `` lenovo legion 7 slim 15ach6: remove brightness service `` |
| [`4259025d`](https://github.com/NixOS/nixos-hardware/commit/4259025da1308836a5c978ee8015f47b7185334b) | `` apple/t2: update to kernel 6.4.2 ``                       |
=> chore(flake/nixos-hardware): `47dca15d` -> `f0984a5a`

flake.lock
| Commit                                                                                           | Message                                             |
| ------------------------------------------------------------------------------------------------ | --------------------------------------------------- |
| [`8364529f`](https://github.com/LnL7/nix-darwin/commit/8364529fc49f35294c2fcc23f7caa0becd6e5cdf) | `` fix zsh eating output without new line ending `` |
=> chore(flake/darwin): `66a3047f` -> `90ae979e`

flake.lock
| Commit                                                                                           | Message                                                    |
| ------------------------------------------------------------------------------------------------ | ---------------------------------------------------------- |
| [`591446ca`](https://github.com/LnL7/nix-darwin/commit/591446ca945402044ad109990491ed87c42ba37a) | `` nix: Remove readOnlyStore option as it has no effect `` |
| [`4a7da05c`](https://github.com/LnL7/nix-darwin/commit/4a7da05c1ef53064d548742eddb1964cf4b3dda7) | `` Fix spelling ``                                         |
=> chore(flake/darwin): `90ae979e` -> `97d4a910`

flake.lock
| [`b70656af`](https://github.com/LnL7/nix-darwin/commit/b70656affa5e63efcf0a0a728c6f9a26911c7ef4) | `` Add system.systemBuilderCommands and systemBuilderArgs `` |
=> chore(flake/darwin): `97d4a910` -> `83620edf`

flake.lock
| [`a6d1d954`](https://github.com/nix-community/home-manager/commit/a6d1d954b81caf4c9291b8ac35452fef842f289b) | `` ssh-agent: add assertion and fix news entry (#4210) `` |
=> chore(flake/home-manager): `b70db52f` -> `a6d1d954`

flake.lock
| [`39eac9bf`](https://github.com/NixOS/nixos-hardware/commit/39eac9bf9a5553ba0815f5824309fa00f9573820) | `` added 16IRX8H Lenovo Legion 7i Pro (2023) (#660) `` |
| [`bb7ba40a`](https://github.com/NixOS/nixos-hardware/commit/bb7ba40a67bfc8f4bbc23aad6e12d8df0e1df53f) | `` Update microchip/common/bsp/uboot.nix
``           |
| [`e5ea5821`](https://github.com/NixOS/nixos-hardware/commit/e5ea58213358b9037a00d0b1c2bcc5e4b0d46151) | `` Microchip uboot build failure with …
=> chore(flake/nixos-hardware): `f0984a5a` -> `44bc0250`

flake.lock
| [`5d8f9910`](https://github.com/NixOS/nixpkgs/commit/5d8f9910f51b9f1e054c4bcfb2be274103cabdbc) | `` python310Packages.django-mysql: 4.10.0 -> 4.11.0 ``                                 |
| [`193583c2`](https://github.com/NixOS/nixpkgs/commit/193583c2415a0f129655d51e818a32e5ab92e0a5) | `` sbt: 1.9.1 -> 1.9.2 (#242598) ``                                                    |
| …
=> chore(flake/nixpkgs): `408c0e8c` -> `4a729ce4`

flake.lock
| Commit                                                                                               | Message                        |
| ---------------------------------------------------------------------------------------------------- | ------------------------------ |
| [`919d646d`](https://github.com/numtide/flake-utils/commit/919d646de7be200f3bf08cb76ae1f09402b6f9b4) | `` Fix typo in ReadMe (#95) `` |
=> chore(flake/flake-utils): `dbabf0ca` -> `919d646d`

flake.lock
| Commit                                                                                           | Message                                                |
| ------------------------------------------------------------------------------------------------ | ------------------------------------------------------ |
| [`63af129c`](https://github.com/LnL7/nix-darwin/commit/63af129cb56548edf8e620437443f8e8b57864f9) | `` etc: use `.before-nix-darwin` instead of `.orig` `` |
| [`ac9a366a`](https://github.com/LnL7/nix-darwin/commit/ac9a366aed7e0d4cbad304aa97d1a3da70f27fa5) | `` uninstaller: remove `/Applications/Nix Apps` ``     |
| [`cad8954f`](https://github.com/LnL7/nix-darwin/commit/cad8954f75809eda533cfb01dc92de8d32f5332d) | `` etc: fail if we can't add a file ``                 |
| …
=> chore(flake/darwin): `83620edf` -> `eb22022b`

flake.lock
| [`e42fb597`](https://github.com/nix-community/home-manager/commit/e42fb59768f0305085abde0dd27ab5e0cc15420c) | `` flake.lock: Update `` |
=> chore(flake/home-manager): `a6d1d954` -> `e42fb597`

flake.lock
| [`8eb09d4d`](https://github.com/LnL7/nix-darwin/commit/8eb09d4d0b3d820934d9871c884e0423bc95ba89) | `` uninstaller: fix removing `/Applications/Nix Apps` `` |
=> chore(flake/darwin): `eb22022b` -> `43ce0868`

flake.lock
| [`a3bd43a6`](https://github.com/NixOS/nixpkgs/commit/a3bd43a6dd8f7f64f6f36438d5b04ed9de33bd27) | `` evcc: 0.118.7 -> 0.118.8 (#242852) ``                                  |
| [`a4f7840e`](https://github.com/NixOS/nixpkgs/commit/a4f7840e1813bc389995083fac2b3bcd0ca6823d) | `` redmine: fix Gemfile ``                                                |
| [`4d8e3794`](https://github.com/NixOS/nixpkgs/commit/4d8e3794dfa2c3e6d8fd5d3718d877ba7c3cc3c2) | …
=> chore(flake/nixpkgs): `4a729ce4` -> `f2406198`

flake.lock
| [`c80294ef`](https://github.com/LnL7/nix-darwin/commit/c80294ef26ff5c896534101f8aa8d9f30bd1f3d5) | `` Update modules/services/cachix-agent.nix ``               |
| [`adc6a88f`](https://github.com/LnL7/nix-darwin/commit/adc6a88ff17e55ec6a6522c9a37a2ead26a3ed7a) | `` cachix-agent: clarify what should be in the token file `` |
=> chore(flake/darwin): `43ce0868` -> `795492c9`

flake.lock
| [`4511c29a`](https://github.com/LnL7/nix-darwin/commit/4511c29a72a285b12acdf440d306f83227b927df) | `` flake: use `nix-darwin` instead of `darwin` `` |
=> chore(flake/darwin): `795492c9` -> `2ad716c2`

flake.lock
| [`a86a6f8b`](https://github.com/LnL7/nix-darwin/commit/a86a6f8b71a816b505d0e8e4310e644a3f75fdfd) | `` workflows: use `nix-darwin` instead of `darwin` `` |
=> chore(flake/darwin): `2ad716c2` -> `d468d4e8`

flake.lock
| [`fbc47b7b`](https://github.com/LnL7/nix-darwin/commit/fbc47b7bbccb7a1325cad65a30509233193484a7) | `` use `types.lines` for yabai.extraConfig option `` |
=> chore(flake/darwin): `d468d4e8` -> `c806a736`

flake.lock
| [`d4ea64f2`](https://github.com/NixOS/nixos-hardware/commit/d4ea64f2063820120c05f6ba93ee02e6d4671d6b) | `` Revert "framework: switch to power-profiles-daemon" `` |
| [`bc2ab72b`](https://github.com/NixOS/nixos-hardware/commit/bc2ab72beca298aa6074eaee0a612d3dd08d5073) | `` framework: switch to power-profiles-daemon ``          |
=> chore(flake/nixos-hardware): `44bc0250` -> `d4ea64f2`

flake.lock
| Commit                                                                                                       | Message                      |
| ------------------------------------------------------------------------------------------------------------ | ---------------------------- |
| [`d96b54dd`](https://github.com/cachix/pre-commit-hooks.nix/commit/d96b54dd024d4c769923b446ae7484d9560e09f2) | `` Add yamllint to README `` |
=> chore(flake/pre-commit-hooks): `c8d18ba3` -> `5e28316d`

flake.lock
| Commit                                                                                         | Message                                                |
| ---------------------------------------------------------------------------------------------- | ------------------------------------------------------ |
| [`6e8a48c2`](https://github.com/ryantm/agenix/commit/6e8a48c2dca4fd8bd6a002dda1da1645753ef006) | `` doc: fix nixos option format in descriptions ``     |
| [`0d949607`](https://github.com/ryantm/agenix/commit/0d94960783efdcaaee800b22f03c861b8c575d3f) | `` doc: fix defaultText by adding literalExpression `` |
=> chore(flake/agenix): `db5637d1` -> `0d8c5325`

flake.lock
| [`bec87d53`](https://github.com/nix-community/home-manager/commit/bec87d536c9f441ffeb603fc821fa7e613585d00) | `` aerc: add assertion to limit per-account extraConfig to UI config (#4196) `` |
=> chore(flake/home-manager): `e42fb597` -> `bec87d53`

flake.lock
| Commit                                                                                                      | Message                                                                              |
| ----------------------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------ |
| [`c1cdce3d`](https://github.com/nix-community/home-manager/commit/c1cdce3d89741d402d8fd2c93e3d2643ff85b053) | `` i3-sway: allow arbitrary floating modifier (#4229) ``                             |
| [`f63b39a6`](https://github.com/nix-community/home-manager/commit/f63b39a67dcfeae4ed326acba181c898753ae7ad) | `` i3-sway: multiple outputs (#4223) ``                                              |
| …
=> chore(flake/home-manager): `bec87d53` -> `c1cdce3d`

flake.lock
| [`34603224`](https://github.com/nix-community/home-manager/commit/346032240c15d8b6034847dc7a5f53312a5a57fc) | `` Translate using Weblate (French) `` |
=> chore(flake/home-manager): `55985674` -> `34603224`

flake.lock
| [`f5b03feb`](https://github.com/nix-community/home-manager/commit/f5b03feb33629cb2b6dd513935637e8cc718a5ba) | `` imapnotify: Use JSON type for extraConfig (#4238) `` |
=> chore(flake/home-manager): `34603224` -> `f5b03feb`

flake.lock
| [`22fa44b7`](https://github.com/nix-community/nix-index-database/commit/22fa44b7f14684d184733fb26a628f3878ff7aaf) | `` update packages.nix to release 2023-07-16-035005 `` |
| [`2be67445`](https://github.com/nix-community/nix-index-database/commit/2be674457c62798a6b25ce26214835a04287c64c) | `` flake.lock: Update ``                               |
=> chore(flake/nix-index-database): `75711474` -> `22fa44b7`

flake.lock
| [`232fe3d4`](https://github.com/nix-community/home-manager/commit/232fe3d450dac73e55cf6fd2d73600c6cb82cd8b) | `` flake.lock: Update ``                              |
| [`1e7ba710`](https://github.com/nix-community/home-manager/commit/1e7ba7102e62cec727e1579a157e510bf123b350) | `` home-manager: remove Home Manager default paths `` |
=> chore(flake/home-manager): `f5b03feb` -> `232fe3d4`

flake.lock
| [`2f84579a`](https://github.com/nix-community/home-manager/commit/2f84579a70b8c74e5ebb37299a0c3ba279f09382) | `` Update translation files `` |
=> chore(flake/home-manager): `232fe3d4` -> `2f84579a`

flake.lock
| [`4eb1c549`](https://github.com/LnL7/nix-darwin/commit/4eb1c549a9d43c4a85373dbf63986869aab9589b) | `` etc: check for existing files during checks stage `` |
| [`c91c3519`](https://github.com/LnL7/nix-darwin/commit/c91c3519435a267dc7bcfa78bbd6ba158435f7f4) | `` etc: rename activation script variables ``           |
=> chore(flake/darwin): `c806a736` -> `61662a63`

flake.lock
| Commit                                                                                                       | Message                                |
| ------------------------------------------------------------------------------------------------------------ | -------------------------------------- |
| [`09214adc`](https://github.com/cachix/pre-commit-hooks.nix/commit/09214adc27bdd286ee371387c423a18e02be7250) | `` fix(lua-ls): update + shell hook `` |
=> chore(flake/pre-commit-hooks): `5e28316d` -> `87589fa4`

flake.lock
| [`0841242b`](https://github.com/nix-community/home-manager/commit/0841242b94638fcd010f7f64e56b7b1cad50c697) | `` ripgrep: don't set env. variable if no config (#4254) `` |
| [`8c350c20`](https://github.com/nix-community/home-manager/commit/8c350c2069ac3eed6344fa62e3249afa0ce2728c) | `` docs: update for Markdown migration ``                   |
| [`9f9e277b`](https://github.com/nix-community/home-manager/commit/9f9e277b60a6e6915ad3a129e06861044b50 …
=> chore(flake/home-manager): `2f84579a` -> `0841242b`

flake.lock
| [`44ba0184`](https://github.com/nix-community/home-manager/commit/44ba0184376c1bf017b8f2646a6040fb66d9c3e8) | `` jujutsu: update for Jujutsu 0.8.0 (#4250) `` |
=> chore(flake/home-manager): `0841242b` -> `44ba0184`

flake.lock
| [`3f751bfd`](https://github.com/NixOS/nixpkgs/commit/3f751bfdf6d1086317d175b628a17690605cccd1) | `` nixos/bpftune: drop flaky tests ``                                               |
| [`d31e7c52`](https://github.com/NixOS/nixpkgs/commit/d31e7c52820c76402cacbfebb6634f51f0012a6c) | `` rclone: 1.63.0 -> 1.63.1 (#244073) ``                                            |
| …
=> chore(flake/nixpkgs): `6cee3b58` -> `684c17c4`

flake.lock
| Commit                                                                                                    | Message                                                                               |
| --------------------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------- |
| [`434ee97a`](https://github.com/nix-community/lanzaboote/commit/434ee97ab3131923d036a05e37c764f497e81c82) | `` flake: offer nix-community cache as a suggested substituter ``                     |
| [`d4131e0c`](https://github.com/nix-community/lanzaboote/commit/d4131e0c6586a4ee8197dc1986e5e0784e14d833) | `` docs: suggest to track released versions rather than master for the flake setup `` |
=> chore(flake/lanzaboote): `c758cdad` -> `bfc88266`

flake.lock
| [`0cb3ac57`](https://github.com/nix-community/home-manager/commit/0cb3ac57fca6b52c42e4c0f560185540ae1dfb6c) | `` Translate using Weblate (Indonesian) ``              |
| [`2e2b24e5`](https://github.com/nix-community/home-manager/commit/2e2b24e5bcafad740a35ca07b2107624efa1c9e1) | `` Translate using Weblate (Ukrainian) ``               |
| [`975f5aa6`](https://github.com/nix-community/home-manager/commit/975f5aa643a08edf1c16a4510d1c3e008386976f) | `` …
=> chore(flake/home-manager): `44ba0184` -> `0cb3ac57`

flake.lock
| [`9cceec40`](https://github.com/nix-community/lanzaboote/commit/9cceec40088dc5cf3e62d5123c90aae0c53f2de4) | `` fix(deps): update all dependencies `` |
=> chore(flake/lanzaboote): `bfc88266` -> `78f00a28`

flake.lock
| Commit                                                                                           | Message                                                                                                                     |
| ------------------------------------------------------------------------------------------------ | --------------------------------------------------------------------------------------------------------------------------- |
| [`bc776e49`](https://github.com/LnL7/nix-darwin/commit/bc776e4940106a2578998dd3117a76d62ec0a8cc) | `` Match nixos handling of fonts.fonts by looking for .ttf, .ttc, and .otf files in any directory in the passed packages `` |
=> chore(flake/darwin): `61662a63` -> `531c3de7`

flake.lock
| Commit                                                                                                    | Message                                                                     |
| --------------------------------------------------------------------------------------------------------- | --------------------------------------------------------------------------- |
| [`0dbcd0ec`](https://github.com/nix-community/lanzaboote/commit/0dbcd0ec1a5b6979cb28662048cec611fc8fdef1) | `` Revert "docs: suggest to track released versions rather than master " `` |
=> chore(flake/lanzaboote): `78f00a28` -> `85420159`

flake.lock
| Commit                                                                                                    | Message                                                                          |
| --------------------------------------------------------------------------------------------------------- | -------------------------------------------------------------------------------- |
| [`aa2cb467`](https://github.com/nix-community/lanzaboote/commit/aa2cb467da1bf9507cc8c0106572e00963c901bc) | `` docs: suggest to use 0.3.0 tagged release of lanzaboote rather than master `` |
=> chore(flake/lanzaboote): `85420159` -> `bf82f823`

flake.lock
| [`1443abd2`](https://github.com/nix-community/home-manager/commit/1443abd2696ec6bd6fb9701e6c26b277a27b4a3e) | `` script-directory: fix documentation link (#4258) `` |
=> chore(flake/home-manager): `0cb3ac57` -> `1443abd2`

flake.lock
| [`5a3eb102`](https://github.com/NixOS/nixpkgs/commit/5a3eb10245e6fbbbfc21b20a3a71f7f6279ace31) | `` kubevpn: init at 1.1.34 ``                                                 |
| [`d345ddaf`](https://github.com/NixOS/nixpkgs/commit/d345ddaf65bbada63057752ebf6f2efa58817db3) | `` nomad_1_5: 1.5.6 -> 1.5.7 ``                                               |
| [`2e60058b`](https://github.com/NixOS/nixpkgs/commit/2e60058b9539a05001f6b76f178c9 …
=> chore(flake/nixpkgs): `684c17c4` -> `5df4d78d`

flake.lock
| [`ee567324`](https://github.com/nix-community/home-manager/commit/ee5673246de0254186e469935909e821b8f4ec15) | `` hyprland: add module `` |
=> chore(flake/home-manager): `1443abd2` -> `ee567324`

flake.lock
| Commit                                                                                                    | Message                  |
| --------------------------------------------------------------------------------------------------------- | ------------------------ |
| [`ec210ff4`](https://github.com/nix-community/lanzaboote/commit/ec210ff40d5337b0c8682cf3c866a2145133a4f8) | `` stub: fix typo ``     |
| [`2a109c01`](https://github.com/nix-community/lanzaboote/commit/2a109c0121122bfd7080c11cf37eedf06d877e78) | `` flake.lock: Update `` |
=> chore(flake/lanzaboote): `bf82f823` -> `e7246c6b`

flake.lock
| Commit                                                                                        | Message                                           |
| --------------------------------------------------------------------------------------------- | ------------------------------------------------- |
| [`34a6d389`](https://github.com/danth/stylix/commit/34a6d389f34b2548b3ae9fad77508620a0358817) | `` Disable Linux-only modules on Darwin (#130) `` |
=> chore(flake/stylix): `dcf3bcf0` -> `34a6d389`

flake.lock
| [`76dd6c66`](https://github.com/nix-community/home-manager/commit/76dd6c66190db0d46ac6b3ca816cc17b581df42c) | `` hyprland: prioritize variables and beziers (#4263) `` |
=> chore(flake/home-manager): `ee567324` -> `76dd6c66`

flake.lock
| [`3e8f4539`](https://github.com/NixOS/nixpkgs/commit/3e8f45393d5f34ff47ef1f55faa3cd76a195efe8) | `` Fix package ref ``                                                        |
| [`e43e2448`](https://github.com/NixOS/nixpkgs/commit/e43e2448161c0a2c4928abec4e16eae1516571bc) | `` ocamlPackages.ocamlformat-rpc-lib: 0.21.0 -> 0.26.0 ``                    |
| [`9140559d`](https://github.com/NixOS/nixpkgs/commit/9140559dd121ca98ce83cd8ba707ac8ba …
=> chore(flake/nixpkgs): `5df4d78d` -> `9ca78564`

flake.lock
| [`12303c65`](https://github.com/NixOS/nixpkgs/commit/12303c652b881435065a98729eb7278313041e49) | `` xfce.mousepad: allow to disable polkit ``                                       |
| [`03042003`](https://github.com/NixOS/nixpkgs/commit/030420030dcd00238420e628d39ab96fcbc12213) | `` netsurf.browser: add the infamous -fcommon compiler flag ``                     |
| [`fc415c59`](https://github.com/NixOS/nixpkgs/commit/fc415c59b …
=> chore(flake/nixpkgs): `9ca78564` -> `12303c65`

flake.lock
| [`8de10d21`](https://github.com/nix-community/nix-index-database/commit/8de10d210a672af5d62af39cd2a60a80d09f34fa) | `` flake.lock: Update `` |
=> chore(flake/nix-index-database): `22fa44b7` -> `8de10d21`

flake.lock
| [`c1e6fc40`](https://github.com/nix-community/nix-index-database/commit/c1e6fc40dd5c0d16940bc012421268b94e404b0b) | `` update packages.nix to release 2023-07-23-033400 `` |
=> chore(flake/nix-index-database): `8de10d21` -> `c1e6fc40`

flake.lock
| [`5fd8914d`](https://github.com/LnL7/nix-darwin/commit/5fd8914dac6ba43ea650fadec35344f20ce50544) | `` treewide: fix `mkEnableOption` docs `` |
=> chore(flake/darwin): `531c3de7` -> `ced9f58f`

flake.lock
| [`fb03fa55`](https://github.com/nix-community/home-manager/commit/fb03fa5516d4e86059d24ab35a611ffa3a359547) | `` flake.lock: Update `` |
=> chore(flake/home-manager): `76dd6c66` -> `fb03fa55`

flake.lock
| Commit                                                                                           | Message                            |
| ------------------------------------------------------------------------------------------------ | ---------------------------------- |
| [`0dafe217`](https://github.com/LnL7/nix-darwin/commit/0dafe2170deb6a691255cecc212af4b1cdf8297b) | `` Add `darwin-version` command `` |
=> chore(flake/darwin): `ced9f58f` -> `0f9058e7`

flake.lock
| [`a30f5b5b`](https://github.com/nix-community/home-manager/commit/a30f5b5b35e2d974fb5e1a3721eaec723ef48c89) | `` gh-dash: add module `` |
=> chore(flake/home-manager): `ab70a023` -> `a30f5b5b`

flake.lock
| [`ba9650b1`](https://github.com/NixOS/nixos-hardware/commit/ba9650b14e83b365fb9e731f7d7c803f22d2aecf) | `` deciso/dec: init, tested with DEC2750 `` |
| [`20f2efe6`](https://github.com/NixOS/nixos-hardware/commit/20f2efe651b7bf812cc26ae8bb4c3daf5927cd96) | `` ga402: remove useless kernel flags ``    |
| [`70325e39`](https://github.com/NixOS/nixos-hardware/commit/70325e398b4cf1410ed024d9dea486f61446878b) | `` Added Asus Zephyrus GA502 ``             |
=> chore(flake/nixos-hardware): `d4ea64f2` -> `ba9650b1`

flake.lock
| Commit                                                                                         | Message                                         |
| ---------------------------------------------------------------------------------------------- | ----------------------------------------------- |
| [`91220a70`](https://github.com/ryantm/agenix/commit/91220a701d0bf8055547620baa765b36d885db7a) | `` Rephrase cli app summary ``                  |
| [`2bee5c98`](https://github.com/ryantm/agenix/commit/2bee5c988c41387ef61879927206e1bc98aae978) | `` Extend tutorial section ``                   |
| [`1d7fd156`](https://github.com/ryantm/agenix/commit/1d7fd1569043356d9c64d81e8b40177e164f2017) | `` Extend flake install section ``              |
| …
=> chore(flake/agenix): `0d8c5325` -> `d8c973fd`

flake.lock
| Commit                                                                                           | Message                                             |
| ------------------------------------------------------------------------------------------------ | --------------------------------------------------- |
| [`a5b09580`](https://github.com/LnL7/nix-darwin/commit/a5b09580e2d0bbc52b338afe4f1f1d46178e6bbf) | `` Revert "eval-config: set `class`" ``             |
| [`c4a1a1c4`](https://github.com/LnL7/nix-darwin/commit/c4a1a1c458b70156f85b2529dc5113c21f832916) | `` eternal-terminal: change launchd agent config `` |
| [`6adc4c68`](https://github.com/LnL7/nix-darwin/commit/6adc4c680b6b6970004629e5496b191f9a315faa) | `` eternal-terminal: add module ``                  |
| …
=> chore(flake/darwin): `0f9058e7` -> `6ed4eb54`

flake.lock
| [`9f8bc612`](https://github.com/LnL7/nix-darwin/commit/9f8bc612c8563c851e09f7ddf88c5f8ce6e0d52b) | `` eternal-terminal: enable keep alive `` |
=> chore(flake/darwin): `6ed4eb54` -> `efd35d99`

flake.lock
| [`ba2c0737`](https://github.com/nix-community/home-manager/commit/ba2c0737cc848db03470828fdb5e86df75ed42a8) | `` firefox: make package nullable (#4113) `` |
=> chore(flake/home-manager): `0306d5ed` -> `ba2c0737`

flake.lock
| Commit                                                                                           | Message                                          |
| ------------------------------------------------------------------------------------------------ | ------------------------------------------------ |
| [`7ff10017`](https://github.com/LnL7/nix-darwin/commit/7ff10017ed1636d23a1ad838611fe7339c9a499f) | `` chore: apply CR suggestions ``                |
| [`56f56c80`](https://github.com/LnL7/nix-darwin/commit/56f56c80ef15178c0f6c4dc5b72338c95f0f0076) | `` sketchybar: init ``                           |
| [`640331df`](https://github.com/LnL7/nix-darwin/commit/640331dfba943068a20f7519fff619e7e9f375ba) | `` docs: add magnification values range ``       |
| …
=> chore(flake/darwin): `efd35d99` -> `1c1dd8b0`

flake.lock
| [`6a00d1b5`](https://github.com/LnL7/nix-darwin/commit/6a00d1b59b2618c98977fb4200e71de28174d737) | `` Update modules/programs/bash/default.nix ``        |
| [`e21b70da`](https://github.com/LnL7/nix-darwin/commit/e21b70da3f9cd630629b83faa7762be5c6da23f2) | `` Don't run static bashrc only for pure nix-shell `` |
=> chore(flake/darwin): `1c1dd8b0` -> `94212ebe`

flake.lock
| [`7da39a7a`](https://github.com/NixOS/nixpkgs/commit/7da39a7a9e8849db860cd1adfad2bcb5539d4f76) | `` treewide .goModules: revert renaming the derivation ``                          |
| [`29e6553d`](https://github.com/NixOS/nixpkgs/commit/29e6553d1fa2b6849482486638ac85de9301b203) | `` ocamlPackages.dolog: 3.0 → 6.0.0 ``                                             |
| [`7fc27444`](https://github.com/NixOS/nixpkgs/commit/7fc27444d …
=> chore(flake/nixpkgs): `12303c65` -> `b12803b6`

flake.lock
| Commit                                                                                            | Message                                                                         |
| ------------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------- |
| [`a95057b7`](https://github.com/lovesegfault/nix/commit/a95057b7fcc33c52827503f4dbb1c759e42075e1) | `` feat: add always-allow-substitutes ``                                        |
| [`8398872a`](https://github.com/lovesegfault/nix/commit/8398872ae0e750f45979854e586d94638360ead4) | `` doc: clarify release notes about nested attribute merges ``                  |
| [`07d1e304`](https://github.com/lovesegfault/nix/commit/07d1e3 …
=> chore(flake/nix): `13d91ca0` -> `a95057b7`

flake.lock
| [`588303a2`](https://github.com/LnL7/nix-darwin/commit/588303a21f468c52ed24759d74c888690a855ec1) | `` fix: correct description of services.ofborg.logFile `` |
=> chore(flake/darwin): `94212ebe` -> `16c07487`

flake.lock
| Commit                                                                                                       | Message                         |
| ------------------------------------------------------------------------------------------------------------ | ------------------------------- |
| [`901814db`](https://github.com/cachix/pre-commit-hooks.nix/commit/901814db4e3a6988aa082f59cfab3375f926a90e) | `` Fix typo in code comment ``  |
| [`de701a97`](https://github.com/cachix/pre-commit-hooks.nix/commit/de701a97a0271ebda5d1cae76db08937e56206ca) | `` Add rome ``                  |
| [`bef27b95`](https://github.com/cachix/pre-commit-hooks.nix/commit/bef27b950c966263fea3a9822f9ed24e739c7b1f) | `` Add mkdocs-linkcheck hook `` |
=> chore(flake/pre-commit-hooks): `eb433bff` -> `2ddd4dbc`

flake.lock
| Commit                                                                                                       | Message                                                                 |
| ------------------------------------------------------------------------------------------------------------ | ----------------------------------------------------------------------- |
| [`73954b2d`](https://github.com/cachix/pre-commit-hooks.nix/commit/73954b2d7c28ead19fa25d60599254dda25ba9a8) | `` Make the generated configuration depend on the pre-commit package `` |
=> chore(flake/pre-commit-hooks): `2ddd4dbc` -> `fa01fdab`

flake.lock
| Commit                                                                                                       | Message                              |
| ------------------------------------------------------------------------------------------------------------ | ------------------------------------ |
| [`47b6bb15`](https://github.com/cachix/pre-commit-hooks.nix/commit/47b6bb155e162d57e4c93834a21bf530e86d4cec) | `` Add `deno lint` and `deno fmt` `` |
=> chore(flake/pre-commit-hooks): `fa01fdab` -> `9289996d`

flake.lock
| [`5c829554`](https://github.com/danth/stylix/commit/5c829554280f3139ddbfce8561d7430efbf2abfb) | `` fix i3 config for latest version of hm (#133) `` |
=> chore(flake/stylix): `34a6d389` -> `5c829554`

flake.lock, graphical/fonts.nix
| [`5a5ddf79`](https://github.com/NixOS/nixpkgs/commit/5a5ddf79cc75e2f10a8d5b5dbaa31587ad8b6883) | `` linux-firmware: fix build, add explicit revision ``                               |
| [`b4da2293`](https://github.com/NixOS/nixpkgs/commit/b4da229372cbed279f72ba7c23a43dc201e2bcf1) | `` python310Packages.python-benedict: 0.31.0 -> 0.32.0 ``                            |
| …
=> chore(flake/nixpkgs): `b12803b6` -> `ef99fa5c`

flake.lock
| [`8d243f7d`](https://github.com/nix-community/home-manager/commit/8d243f7da13d6ee32f722a3f1afeced150b6d4da) | `` gpg: fix typo (#4277) `` |
=> chore(flake/home-manager): `ba2c0737` -> `8d243f7d`

flake.lock
| [`539e08e1`](https://github.com/NixOS/nixpkgs/commit/539e08e12a1a96a0513d71694a2acc8574f9984e) | `` tts: 0.15.6 -> 0.16.0 ``                                                                       |
| [`9770f6a2`](https://github.com/NixOS/nixpkgs/commit/9770f6a23aadfe10b7072c014a7e3da43a106075) | `` python310Packages.trainer: 0.0.27 -> 0.0.29 ``                                                 |
| …
=> chore(flake/nixpkgs): `ef99fa5c` -> `c9cf0708`

flake.lock
| [`2719a57e`](https://github.com/danth/stylix/commit/2719a57e2bcadf441175bef1e7c3f593a978e56f) | `` Use renamed NixOS option for fonts (#134) `` |
=> chore(flake/stylix): `5c829554` -> `2719a57e`

flake.lock
| [`6c05a4c7`](https://github.com/NixOS/nixpkgs/commit/6c05a4c70ca92a313486e4a54d47489b6c05c7e5) | `` wttrbar: init at 0.3.2 ``                                              |
| [`7bc72fa4`](https://github.com/NixOS/nixpkgs/commit/7bc72fa4711a80ed5ef9f5de42dae2bce1dd2382) | `` maintainers: add khaneliman ``                                         |
| [`bfbd4a3f`](https://github.com/NixOS/nixpkgs/commit/bfbd4a3fa66d5859cf1da95c3f8032c802ee6b4c) | …
=> chore(flake/nixpkgs): `c9cf0708` -> `2a9d660f`

flake.lock
| [`c29f2e6f`](https://github.com/danth/stylix/commit/c29f2e6f9d0326a690d0c2376712e9134ad8f5c8) | `` Add trick with dynamic wallpaper generation (#135) `` |
=> chore(flake/stylix): `2719a57e` -> `c29f2e6f`

flake.lock
| Commit                                                                                                       | Message                      |
| ------------------------------------------------------------------------------------------------------------ | ---------------------------- |
| [`1e2443dd`](https://github.com/cachix/pre-commit-hooks.nix/commit/1e2443dd3f669eb65433b2fc26a3065e05a7dc9c) | `` dependabot -> renovate `` |
=> chore(flake/pre-commit-hooks): `9289996d` -> `1e2443dd`

flake.lock
| [`5c232267`](https://github.com/nix-community/home-manager/commit/5c23226768abd3402636f4d3c65aea8450997102) | `` hyprland: use `toKeyValue`'s `indent` argument (#4274) `` |
=> chore(flake/home-manager): `8d243f7d` -> `5c232267`

flake.lock
| [`f58889c0`](https://github.com/nix-community/home-manager/commit/f58889c07efa8e1328fdf93dc1796ec2a5c47f38) | `` gnome-terminal: add assertion on profile names `` |
=> chore(flake/home-manager): `5c232267` -> `f58889c0`

flake.lock
| [`1378acfa`](https://github.com/nix-community/nix-index-database/commit/1378acfa470b5c625f3b6167974636987e510e4c) | `` flake.lock: Update `` |
=> chore(flake/nix-index-database): `c1e6fc40` -> `1378acfa`

flake.lock
| [`d74b8171`](https://github.com/nix-community/nix-index-database/commit/d74b8171153ae35d7d323a9b1ad6c4cf7a995591) | `` update packages.nix to release 2023-07-30-032440 `` |
=> chore(flake/nix-index-database): `1378acfa` -> `d74b8171`

flake.lock
| [`96e5a0a0`](https://github.com/NixOS/nixos-hardware/commit/96e5a0a0e8568c998135ea05575a9ed2c87f5492) | `` t14s: reformat ``                                  |
| [`67b0b87f`](https://github.com/NixOS/nixos-hardware/commit/67b0b87fd8e77a0b0bb6b37b09e5b70fa7cea713) | `` p14s, t14s: remove linux-firmware version check `` |
=> chore(flake/nixos-hardware): `ba9650b1` -> `96e5a0a0`

flake.lock
| Commit                                                                                                       | Message                                  |
| ------------------------------------------------------------------------------------------------------------ | ---------------------------------------- |
| [`2759193c`](https://github.com/cachix/pre-commit-hooks.nix/commit/2759193c230c5c0c0767cda10e6d99937021ec8a) | `` Check that pkgs isn't used by docs `` |
| [`d3657e70`](https://github.com/cachix/pre-commit-hooks.nix/commit/d3657e7015550c8fd9231dde51ad5b042e783caa) | `` Fix doc ``                            |
=> chore(flake/pre-commit-hooks): `1e2443dd` -> `fcbf4705`

flake.lock
| [`729ab77f`](https://github.com/nix-community/home-manager/commit/729ab77f9e998e0989fa30140ecc91e738bc0cb1) | `` home-manager: skip manual in uninstall configuration `` |
=> chore(flake/home-manager): `f58889c0` -> `729ab77f`

flake.lock
| [`e985164a`](https://github.com/nix-community/impermanence/commit/e985164ad5b17f4be8a2d3177b96b75a622a943a) | `` nixos: Introduce `persistentStoragePath` option `` |
=> chore(flake/impermanence): `89253fb1` -> `e3a7acd1`

flake.lock
| [`3db43afc`](https://github.com/nix-community/home-manager/commit/3db43afcb4a755221530ff821ec4ac30eca77033) | `` home-manager: rework news command `` |
=> chore(flake/home-manager): `729ab77f` -> `3db43afc`

flake.lock
| [`4fd794d3`](https://github.com/nix-community/home-manager/commit/4fd794d3df88735dcf9662155d77b08a2e2dde29) | `` gh: option to enable helper for additional hosts (#4288) `` |
=> chore(flake/home-manager): `3db43afc` -> `4fd794d3`

flake.lock
| [`5ba1b5be`](https://github.com/NixOS/nixpkgs/commit/5ba1b5be5a22b2f955ee294d347ba8b76e172bc2) | `` nushellPlugins.query: 0.83.0 -> 0.83.1 ``                                           |
| [`f7a4a376`](https://github.com/NixOS/nixpkgs/commit/f7a4a3764f3675af8d7aec314a550546cd603f0c) | `` nushellPlugins.gstat: 0.83.0 -> 0.83.1 ``                                           |
| …
=> chore(flake/nixpkgs): `e6ab4698` -> `fb942492`

flake.lock
| [`310c0063`](https://github.com/nix-community/home-manager/commit/310c0063b2558e94ad8bc3c1f2ddead82e0872cd) | `` Update translation files ``                       |
| [`04da1b90`](https://github.com/nix-community/home-manager/commit/04da1b908be79dd88c4e2ef43363a4d5a1536df2) | `` Translate using Weblate (Chinese (Simplified)) `` |
=> chore(flake/home-manager): `4fd794d3` -> `310c0063`

flake.lock
| [`89df56fe`](https://github.com/nix-community/home-manager/commit/89df56fefe728bed13b4b5b99af196017e330dd5) | `` fish: fix session vars build in cross-compiled system (#4293) `` |
=> chore(flake/home-manager): `310c0063` -> `89df56fe`

flake.lock
| [`4542db60`](https://github.com/nix-community/home-manager/commit/4542db605602898fe0c431e19f01e1af2865dae8) | `` man: fix caches generation in cross-compiled system (#4294) `` |
=> chore(flake/home-manager): `89df56fe` -> `4542db60`

flake.lock
| [`5f7b55cc`](https://github.com/danth/stylix/commit/5f7b55cc690b5ca02d1dc19175cab2ccdd408811) | `` Change waybar font size to pt instead of px (#138) `` |
=> chore(flake/stylix): `c29f2e6f` -> `5f7b55cc`

flake.lock
| [`9910c698`](https://github.com/NixOS/nixos-hardware/commit/9910c6985687cf1c365bc10c95c5bacdaed81e3f) | `` GPD-P3: Remove S2 sleep kernel param, use S3 instead `` |
=> chore(flake/nixos-hardware): `96e5a0a0` -> `9910c698`

flake.lock
| [`24f9162b`](https://github.com/NixOS/nixos-hardware/commit/24f9162b26f0debd163f6d94752aa2acb9db395a) | `` framework: Clarify 13th Gen Intel Core support ``     |
| [`35382904`](https://github.com/NixOS/nixos-hardware/commit/353829048c3a7c3a99346fe6686672330b1109b1) | `` microsoft-surface: update default kernel to 6.1.18 `` |
| [`af694376`](https://github.com/NixOS/nixos-hardware/commit/af694376e2f20e6ab40bf814cad24590bed0aa9d) | `` p14s: Add common/{cpu,gpu}/amd …
=> chore(flake/nixos-hardware): `9910c698` -> `24f9162b`

flake.lock
| [`a146ab6a`](https://github.com/nix-community/home-manager/commit/a146ab6a61c20b97b8343c7c77870a4a3f645b1c) | `` himalaya: update a link to ticket `` |
=> chore(flake/home-manager): `8c731978` -> `a146ab6a`

flake.lock
| [`484a1c94`](https://github.com/nix-community/home-manager/commit/484a1c94424d296b15af3e6858f08b576b842ec2) | `` network-manager-applet: remove `--sm-disable` flag `` |
=> chore(flake/home-manager): `a146ab6a` -> `484a1c94`

flake.lock
| [`b2ac1d2c`](https://github.com/nix-community/home-manager/commit/b2ac1d2c32ac11b8d231d23622cdc4b2f28d07d2) | `` flake.lock: Update `` |
=> chore(flake/home-manager): `484a1c94` -> `b2ac1d2c`

flake.lock
| Commit                                                                                           | Message                                 |
| ------------------------------------------------------------------------------------------------ | --------------------------------------- |
| [`97e97862`](https://github.com/LnL7/nix-darwin/commit/97e978626e8beaa89aa2472ea7f3704c176316cd) | `` linux-builder: add maxJobs option `` |
=> chore(flake/darwin): `16c07487` -> `d3529322`

flake.lock
| [`5eaeb7eb`](https://github.com/NixOS/nixpkgs/commit/5eaeb7eb5a6469b5c814698949fad93f255a71e5) | `` python3Packages.dask-awkward: 2023.6.3 -> 2023.8.0 (#246671) ``            |
| [`41501361`](https://github.com/NixOS/nixpkgs/commit/415013610e49b64668ad8e0dc36eb73391abc4cb) | `` vscode-extensions.eamodio.gitlens: 13.4.0 -> 14.1.1 ``                     |
| [`6e5a922b`](https://github.com/NixOS/nixpkgs/commit/6e5a922b38e1b635a26b2ed3d93ba …
=> chore(flake/nixpkgs): `9e1960bc` -> `66aedfd0`

flake.lock
| [`86dd48d7`](https://github.com/nix-community/home-manager/commit/86dd48d70a2e2c17e84e747ba4faa92453e68d4a) | `` Translate using Weblate (Korean) ``   |
| [`9b0bc4ce`](https://github.com/nix-community/home-manager/commit/9b0bc4ce7917f7b6f597fbe00b655fd992f63147) | `` Translate using Weblate (Romanian) `` |
| [`e79f416b`](https://github.com/nix-community/home-manager/commit/e79f416b61da725fe167e74a33f344b2edee61f7) | `` Translate using Weblate (German) ``   |
=> chore(flake/home-manager): `b2ac1d2c` -> `86dd48d7`

flake.lock
| Commit                                                                                                       | Message                           |
| ------------------------------------------------------------------------------------------------------------ | --------------------------------- |
| [`b97cc1fb`](https://github.com/cachix/pre-commit-hooks.nix/commit/b97cc1fbb51e72a0fc0489586264de333da3e020) | `` Fix typo ``                    |
| [`b9ce83aa`](https://github.com/cachix/pre-commit-hooks.nix/commit/b9ce83aa6b383407f9cb58f6eb5d1854f8ef4cd9) | `` Add options to 'typos' hook `` |
=> chore(flake/pre-commit-hooks): `fcbf4705` -> `52bf4046`

flake.lock
| Commit                                                                                                       | Message                                                      |
| ------------------------------------------------------------------------------------------------------------ | ------------------------------------------------------------ |
| [`046d10f9`](https://github.com/cachix/pre-commit-hooks.nix/commit/046d10f9d395cd8ee81e20b55e764b7a63bed500) | `` Fix settings for typos and add some additional options `` |
| [`8346dc30`](https://github.com/cachix/pre-commit-hooks.nix/commit/8346dc308cf7192e1c1b645f1aac39ea69cba43e) | `` Fix wording of options and use `lib.mdDoc` ``             |
=> chore(flake/pre-commit-hooks): `52bf4046` -> `ebb43bda`

flake.lock
| [`a4f45087`](https://github.com/nix-community/home-manager/commit/a4f450879119a2a000264bd5ac90b186e1147617) | `` jujutsu: fix zsh completion (#4305) `` |
=> chore(flake/home-manager): `86dd48d7` -> `a4f45087`

flake.lock
| [`15043a65`](https://github.com/nix-community/home-manager/commit/15043a65915bcc16ad207d65b202659e4988066b) | `` zsh: Add `zsh.history.ignoreAllDups` config option (#4248) `` |
=> chore(flake/home-manager): `a4f45087` -> `15043a65`

flake.lock
| [`87e3122b`](https://github.com/NixOS/nixos-hardware/commit/87e3122b67587492a617764f88c71991893fcf8a) | `` starfive visionfive2: Increase mtd0 to fit spl ``   |
| [`e8159d4e`](https://github.com/NixOS/nixos-hardware/commit/e8159d4e3d271f60f89e349d820726856ce09f11) | `` starfive visionfive2: update kernel to 6.5.0-rc1 `` |
| [`258b9faf`](https://github.com/NixOS/nixos-hardware/commit/258b9faff07cb7676002c63793e6f7da2c522a96) | `` apple/t2: update to kernel 6.4.8 `` …
=> chore(flake/nixos-hardware): `24f9162b` -> `87e3122b`

flake.lock
| [`0a014a72`](https://github.com/nix-community/home-manager/commit/0a014a729cdd54d9919ff36b714d047909d7a4c8) | `` aerc: do not use smtp-starttls (#4272) `` |
=> chore(flake/home-manager): `15043a65` -> `0a014a72`

flake.lock
| [`25bbc404`](https://github.com/NixOS/nixpkgs/commit/25bbc404a1c3ef99435ced65f949d4731621ad26) | `` flood: fix mainProgram merge issue ``                                     |
| [`ffbd4117`](https://github.com/NixOS/nixpkgs/commit/ffbd41175460f5d870fac5cfef58d73f770684c9) | `` home-assistant: 2023.8.0 -> 2023.8.1 ``                                   |
| [`6f82a3d2`](https://github.com/NixOS/nixpkgs/commit/6f82a3d2d6ee0e942c3a636fb23630420 …
=> chore(flake/nixpkgs): `66aedfd0` -> `18036c0b`

flake.lock
| Commit                                                                                           | Message                                             |
| ------------------------------------------------------------------------------------------------ | --------------------------------------------------- |
| [`dd738669`](https://github.com/LnL7/nix-darwin/commit/dd73866955aa5305536d88dfae93051378206f9a) | `` Fix example configuration for flake migration `` |
=> chore(flake/darwin): `d3529322` -> `e3c554fe`

flake.lock
| Commit                                                                                                       | Message                        |
| ------------------------------------------------------------------------------------------------------------ | ------------------------------ |
| [`2b9608f3`](https://github.com/cachix/pre-commit-hooks.nix/commit/2b9608f3c679ca55b2d0083aa8d6672783e2c068) | `` Expose always_run option `` |
=> chore(flake/pre-commit-hooks): `ebb43bda` -> `3139c4d1`

flake.lock
| [`9d539267`](https://github.com/LnL7/nix-darwin/commit/9d53926782b6c857ebdf9682137068f9cbcdb5d5) | `` tests: fix uses of `!` ``                          |
| [`e2187d63`](https://github.com/LnL7/nix-darwin/commit/e2187d633ca8e156e8810af29da39692a30c37d1) | `` fish: simplify `babelfishTranslate` ``             |
| [`e65825ca`](https://github.com/LnL7/nix-darwin/commit/e65825ca9ef935a3219c5a3e81a42b747e04e58b) | `` fish: add default for `babelfishPackage` ``        |
| …
=> chore(flake/darwin): `e3c554fe` -> `829041cf`

flake.lock
| [`c55a6b6f`](https://github.com/nix-community/nix-index-database/commit/c55a6b6fdcf88c09c4beaedfcd2bf70a8480e8c8) | `` flake.lock: Update `` |
=> chore(flake/nix-index-database): `d74b8171` -> `c55a6b6f`

flake.lock
| [`6c626d54`](https://github.com/nix-community/nix-index-database/commit/6c626d54d0414d34c771c0f6f9d771bc8aaaa3c4) | `` update packages.nix to release 2023-08-06-033242 `` |
=> chore(flake/nix-index-database): `c55a6b6f` -> `6c626d54`

flake.lock
| [`5426a950`](https://github.com/NixOS/nixos-hardware/commit/5426a95071d0b9782b3209b3995cde1f5689616e) | `` inspiron 14 5420: more tlp info in README `` |
| [`a5a696f2`](https://github.com/NixOS/nixos-hardware/commit/a5a696f281b5ecc8a56396491df00f6f0b9786db) | `` inspiron 14 5420: add to flake.nix ``        |
| [`a75e04b2`](https://github.com/NixOS/nixos-hardware/commit/a75e04b2599136dc41606f7aab7ab41c2de718f9) | `` inspiron 14 5420: remove TLP ``              |
| …
=> chore(flake/nixos-hardware): `87e3122b` -> `5426a950`

flake.lock
| [`903e06d7`](https://github.com/nix-community/home-manager/commit/903e06d734bcae48efb79b9afd51b406d2744179) | `` taffybar: Avoid restarting too quickly (#4316) `` |
=> chore(flake/home-manager): `0a014a72` -> `903e06d7`

flake.lock
| Commit                                                                                         | Message                                                            |
| ---------------------------------------------------------------------------------------------- | ------------------------------------------------------------------ |
| [`148e69a4`](https://github.com/NixOS/nixpkgs/commit/148e69a477594c6b40061124dd39b5ab704d0b97) | `` viking: enable on darwin (#247225) ``                           |
| [`54e6327e`](https://github.com/NixOS/nixpkgs/commit/54e6327e288a41c1ead755480d288e9712eb66b2) | `` lens: 6.3.0 -> 6.5.2 (#242911) ``                               |
| [`7cbd6c6b`](https://github.com/NixOS/nixpkgs/commit/7cbd6c6bccf3cf8dbeea61c8a949d690666e4ffa) | `` remnote: 1.8.52 -> 1.12.3 …
=> chore(flake/nixpkgs): `18036c0b` -> `5faab298`

flake.lock
| Commit                                                                                                       | Message                                        |
| ------------------------------------------------------------------------------------------------------------ | ---------------------------------------------- |
| [`2175ea0a`](https://github.com/cachix/pre-commit-hooks.nix/commit/2175ea0a00a8f2033bff9487d3f54a9186b84a33) | `` Fix settings for hook `mkdocs-linkcheck` `` |
=> chore(flake/pre-commit-hooks): `3139c4d1` -> `e5588ddf`

flake.lock
| Commit                                                                                           | Message                                          |
| ------------------------------------------------------------------------------------------------ | ------------------------------------------------ |
| [`0fb94bf8`](https://github.com/NixOS/templates/commit/0fb94bf87144b18e42765693c3e15ac5f17eeab0) | `` full: Mark nixosModule as deprecated (#70) `` |
=> chore(flake/templates): `0edaa063` -> `0fb94bf8`

flake.lock
| Commit                                                                                         | Message                                                                                         |
| ---------------------------------------------------------------------------------------------- | ----------------------------------------------------------------------------------------------- |
| [`5a8e9243`](https://github.com/NixOS/nixpkgs/commit/5a8e9243812ba528000995b294292d3b5e120947) | `` solana-cli: 1.14.17 -> 1.14.23 ``                                                            |
| [`0d9fe73c`](https://github.com/NixOS/nixpkgs/commit/0d9fe73c144f4a89c8a942b12292f8a030fbd7b9) | `` buildah-unwrapped: 1.31.0 -> 1.31.1 ``                                                       |
| …
=> chore(flake/nixpkgs): `5faab298` -> `5a8e9243`

flake.lock
| [`7b8d43fb`](https://github.com/nix-community/home-manager/commit/7b8d43fbaf8450c30caaed5eab876897d0af891b) | `` modules: types.string throws error now (#4324) `` |
=> chore(flake/home-manager): `903e06d7` -> `7b8d43fb`

flake.lock
| [`8ff521ac`](https://github.com/NixOS/nixos-hardware/commit/8ff521acd2c8132c62141c2990deb7406e32b335) | `` XPS 9560: Remove `lib.mkDefault` on mergable options `` |
| [`1b3c1283`](https://github.com/NixOS/nixos-hardware/commit/1b3c128388ff214c6b91b4564903a9bce4cbbfa3) | `` common/nvidia disable: Remove `lib.mkDefault` ``        |
=> chore(flake/nixos-hardware): `5426a950` -> `8ff521ac`

flake.lock
| [`a8f8f483`](https://github.com/nix-community/home-manager/commit/a8f8f48320c64bd4e3a266a850bbfde2c6fe3a04) | `` mu: add package option (#4325) `` |
=> chore(flake/home-manager): `7b8d43fb` -> `a8f8f483`

flake.lock
| [`b671517f`](https://github.com/LnL7/nix-darwin/commit/b671517f28ff963a4953b507ce167d6420ee3613) | `` finder: `types.string` -> `types.str` `` |
=> chore(flake/darwin): `829041cf` -> `426d3871`

flake.lock
| [`6e1eff9a`](https://github.com/nix-community/home-manager/commit/6e1eff9aac0e8d84bda7f2d60ba6108eea9b7e79) | `` kanshi: support adaptive sync (#4328) `` |
=> chore(flake/home-manager): `a8f8f483` -> `6e1eff9a`

flake.lock
| [`f61352cf`](https://github.com/NixOS/nixos-hardware/commit/f61352cf8066ddd3dfe9058e62184bae7382672d) | `` framework: add 13th gen to flake.nix ``            |
| [`161c91c0`](https://github.com/NixOS/nixos-hardware/commit/161c91c01ab55a199b78c5014eedd0cedcd7a482) | `` framework: fix references to 13th gen in README `` |
=> chore(flake/nixos-hardware): `8ff521ac` -> `f61352cf`

flake.lock
| Commit                                                                                                       | Message              |
| ------------------------------------------------------------------------------------------------------------ | -------------------- |
| [`dbdef427`](https://github.com/cachix/pre-commit-hooks.nix/commit/dbdef42778c71a15ff62f4169fc496f46144360b) | `` add clang-tidy `` |
=> chore(flake/pre-commit-hooks): `e5588ddf` -> `c5ac3aa3`

flake.lock
| Commit                                                                                                    | Message                                         |
| --------------------------------------------------------------------------------------------------------- | ----------------------------------------------- |
| [`4a1b07d0`](https://github.com/nix-community/lanzaboote/commit/4a1b07d0a984f0dcc54d0d70f057613b07b8260f) | `` Fix lzbt build with recent nixos-unstable `` |
=> chore(flake/lanzaboote): `e7246c6b` -> `f1384860`

flake.lock
| [`c445b079`](https://github.com/NixOS/nixpkgs/commit/c445b079d40d7d6c19182a5a31847aef7157dc56) | `` flameshot: provide meta.mainProgram ``                                   |
| [`960b8c5c`](https://github.com/NixOS/nixpkgs/commit/960b8c5ce77fc6d9edc9fe0a1553aefbfc7ff432) | `` betterlockscreen: provide meta.mainProgram ``                            |
| [`1d56cde4`](https://github.com/NixOS/nixpkgs/commit/1d56cde48b77bd4536e5de0042e80729fcd89 …
=> chore(flake/nixpkgs): `5a8e9243` -> `ce5e4a6e`

flake.lock
| [`255f9210`](https://github.com/nix-community/home-manager/commit/255f921049df8d45fb5afa2529b79106edbd8301) | `` programs.khal: uncomment locale config (#4319) `` |
=> chore(flake/home-manager): `6e1eff9a` -> `255f9210`

flake.lock
| [`406d34d9`](https://github.com/nix-community/home-manager/commit/406d34d919e9e8b831b531782cf5ef6995188566) | `` lf: simplify option validation (#4334) `` |
=> chore(flake/home-manager): `255f9210` -> `406d34d9`

flake.lock
| [`430a56dd`](https://github.com/NixOS/nixos-hardware/commit/430a56dd16fe583a812b2df44dca002acab2f4f6) | `` raspberry-pi/4: fix modesetting on 6.1 kernels `` |
| [`33052d5c`](https://github.com/NixOS/nixos-hardware/commit/33052d5cad540300eade03d72e74dc8389e34afb) | `` apple/t2: update to kernel 6.4.9 ``               |
| [`ca062b3e`](https://github.com/NixOS/nixos-hardware/commit/ca062b3e6c324b1a00098d67360a6e13b0fed805) | `` star64: remove unused flake input from README …
=> chore(flake/nixos-hardware): `f61352cf` -> `430a56dd`

flake.lock
| [`9a203c6b`](https://github.com/nix-community/nix-index-database/commit/9a203c6bf691f7c4b66618bb5d085395c5cfe1d1) | `` flake.lock: Update `` |
=> chore(flake/nix-index-database): `6c626d54` -> `9a203c6b`

flake.lock
| [`f4d70d09`](https://github.com/nix-community/nix-index-database/commit/f4d70d098f066a30c7087144063dca179495f7d6) | `` update packages.nix to release 2023-08-13-032820 `` |
=> chore(flake/nix-index-database): `9a203c6b` -> `f4d70d09`

flake.lock
| [`c3ab5ea0`](https://github.com/nix-community/home-manager/commit/c3ab5ea047e6dc73df530948f7367455749d8906) | `` home-manager: handle profile list in Nix >2.17 `` |
=> chore(flake/home-manager): `406d34d9` -> `c3ab5ea0`

flake.lock
| [`beb35709`](https://github.com/danth/stylix/commit/beb35709c9a769a5f279d3177af778a15dcbda46) | `` Move extra CSS to the end of the file (#147) `` |
=> chore(flake/stylix): `5f7b55cc` -> `beb35709`

flake.lock
| Commit                                                                                           | Message                                                                       |
| ------------------------------------------------------------------------------------------------ | ----------------------------------------------------------------------------- |
| [`d21a7e30`](https://github.com/LnL7/nix-darwin/commit/d21a7e30e60521de9d69b56686588697fbf8f19a) | `` Update pkgs/darwin-installer/default.nix ``                                |
| [`5c22b241`](https://github.com/LnL7/nix-darwin/commit/5c22b241f7bd998941248210bbf1340b5f38baff) | `` chore(installer): capitalize the default option when reading user input `` |
=> chore(flake/darwin): `426d3871` -> `3fcd8378`

flake.lock
| Commit                                                                                         | Message                                                                                                             |
| ---------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------------------------------------- |
| [`100a1550`](https://github.com/NixOS/nixpkgs/commit/100a1550b0e7a64b960c625b656f9229bdef5f87) | `` terraform-providers.acme: 2.15.1 -> 2.16.1 ``                                                                    |
| [`1cce3064`](https://github.com/NixOS/nixpkgs/commit/1cce30649512915739f9d634ff043dfdbd0e2e57) | `` alsa-project: expose the scope as a top-level …
=> chore(flake/nixpkgs): `ce5e4a6e` -> `100a1550`

flake.lock
| [`da6874e8`](https://github.com/nix-community/home-manager/commit/da6874e8bb82204323b94154585a1471c739f73e) | `` Translate using Weblate (Romanian) ``            |
| [`d08812fe`](https://github.com/nix-community/home-manager/commit/d08812fe1a850b5948b2101cb4adcb6f8c4faa94) | `` Translate using Weblate (Portuguese (Brazil)) `` |
| [`88067b9b`](https://github.com/nix-community/home-manager/commit/88067b9b148ed86f81d80d13e49f0f848dbd96e0) | `` hyprland: remove …
=> chore(flake/home-manager): `c3ab5ea0` -> `da6874e8`

flake.lock
| Commit                                                                                         | Message                                                                                  |
| ---------------------------------------------------------------------------------------------- | ---------------------------------------------------------------------------------------- |
| [`6e287913`](https://github.com/NixOS/nixpkgs/commit/6e287913f7b1ef537c97aa301b67c34ea46b640f) | `` buck2: include prelude source in .prelude passthru ``                                 |
| [`e85b6933`](https://github.com/NixOS/nixpkgs/commit/e85b6933d543dc98a5f80525150ed048209f5e73) | `` buck2: minor tweaks ``                                                                |
| …
=> chore(flake/nixpkgs): `100a1550` -> `6e287913`

flake.lock
| [`18791781`](https://github.com/nix-community/home-manager/commit/18791781ea86cbec6bce8bcb847444b9c73b8b3b) | `` browserpass: support librewolf `` |
=> chore(flake/home-manager): `da6874e8` -> `18791781`

flake.lock
| [`75cfe974`](https://github.com/nix-community/home-manager/commit/75cfe974e2ca05a61b66768674032b4c079e55d4) | `` Translate using Weblate (German) `` |
| [`b84767a1`](https://github.com/nix-community/home-manager/commit/b84767a145e04d07ef699d266161cda605f48b11) | `` xplr: add module ``                 |
=> chore(flake/home-manager): `18791781` -> `75cfe974`

flake.lock
| Commit                                                                                         | Message                                                                                         |
| ---------------------------------------------------------------------------------------------- | ----------------------------------------------------------------------------------------------- |
| [`2501addf`](https://github.com/NixOS/nixpkgs/commit/2501addf2d61a3052128659883fee33435edd669) | `` nix-doc: 0.5.9 -> 0.5.10 ``                                                                  |
| [`624607b3`](https://github.com/NixOS/nixpkgs/commit/624607b3a5cfa1d1e68b7b768ad925da142630b5) | `` postgresql11JitPackages.plr: 8.4.5 -> 8.4.6 ``                                               |
| …
=> chore(flake/nixpkgs): `6e287913` -> `8353344d`

flake.lock
| [`9db5b89f`](https://github.com/nix-community/home-manager/commit/9db5b89f40736943d017a761da044479044be182) | `` pqiv: add module `` |
=> chore(flake/home-manager): `75cfe974` -> `9db5b89f`

flake.lock
| Commit                                                                                                       | Message                                             |
| ------------------------------------------------------------------------------------------------------------ | --------------------------------------------------- |
| [`61bda565`](https://github.com/cachix/pre-commit-hooks.nix/commit/61bda56530889b4acf6c935d832f219b6c0ebd83) | `` Let shellcheck handle good vs bad shell types `` |
=> chore(flake/pre-commit-hooks): `c5ac3aa3` -> `3e3d45c1`

flake.lock
| [`aa59f917`](https://github.com/nix-community/home-manager/commit/aa59f917462f2d25ffd1f3128a063d4d3d1642d4) | `` fcitx5: add `fcitx5-config-qt` to test stub `` |
| [`1ccd0c93`](https://github.com/nix-community/home-manager/commit/1ccd0c935ca8ade5e0826da8ac4f1bff3f473da6) | `` pqiv: only run tests on Linux platforms ``     |
=> chore(flake/home-manager): `9db5b89f` -> `aa59f917`

flake.lock
| [`2471d965`](https://github.com/nix-community/home-manager/commit/2471d965a3522025157a790fc49c3567fd56e26e) | `` flake.lock: Update `` |
=> chore(flake/home-manager): `aa59f917` -> `2471d965`

flake.lock
| [`ffccbdf7`](https://github.com/LnL7/nix-darwin/commit/ffccbdf7d80a8d610b4b7c2bd11f1fbc7f370275) | `` add progress to homebrew package installations `` |
=> chore(flake/darwin): `3fcd8378` -> `511177ff`

flake.lock
| [`6a94c1a5`](https://github.com/nix-community/home-manager/commit/6a94c1a59737783c282c4031555a289c28b961e4) | `` fix(qt): allow theming for apps started by systemd (#4349) `` |
=> chore(flake/home-manager): `2471d965` -> `6a94c1a5`

flake.lock
| Commit                                                                                                       | Message                                              |
| ------------------------------------------------------------------------------------------------------------ | ---------------------------------------------------- |
| [`cf2901f0`](https://github.com/cachix/pre-commit-hooks.nix/commit/cf2901f0b46b1f0461eba466bf2bc45d4df105c9) | `` Allow empty settings for mkdocs-linkcheck hook `` |
| [`c249b6eb`](https://github.com/cachix/pre-commit-hooks.nix/commit/c249b6eb997c274b7c7f5fa326c63ef53d3a62e6) | `` Add profile setting to isort hook ``              |
=> chore(flake/pre-commit-hooks): `3e3d45c1` -> `7e3517c0`

flake.lock
| [`8fc24972`](https://github.com/NixOS/nixpkgs/commit/8fc24972c51a2ab5fb55fcdebc6c5fa8d06c8888) | `` ocamlPackages.domain-local-await: 0.2.1 → 1.0.0 ``                           |
| [`b1981b02`](https://github.com/NixOS/nixpkgs/commit/b1981b02e183fb376a45932c9a901ea22d4bf77a) | `` arm-trusted-firmware.armTrustedFirmwareTools: remove CC_FOR_BUILD ``         |
| [`994fcd68`](https://github.com/NixOS/nixpkgs/commit/994fcd68b932702219ca0 …
=> chore(flake/nixpkgs): `caac0eb6` -> `42c25608`

flake.lock
| [`7f183653`](https://github.com/NixOS/nixos-hardware/commit/7f1836531b126cfcf584e7d7d71bf8758bb58969) | `` starfive visionfive2: use stable opensbi release ``   |
| [`d5bd79a4`](https://github.com/NixOS/nixos-hardware/commit/d5bd79a48b48a8a4d3daea9bfc71aff6d79ffc80) | `` starfive visionfive2: drop outdated kernel patches `` |
=> chore(flake/nixos-hardware): `430a56dd` -> `7f183653`

flake.lock
| [`5ad01f1b`](https://github.com/NixOS/nixpkgs/commit/5ad01f1b6f1c3a9b0ebe0d81b51761cc80291f82) | `` lib/modules: Report a better error when option tree has bare type ``                           |
| [`e95c64de`](https://github.com/NixOS/nixpkgs/commit/e95c64de4ebbb48700fac130617fa342c73fd9f5) | `` mutt: 2.2.10 -> 2.2.11 ``                                                                      |
| …
=> chore(flake/nixpkgs): `42c25608` -> `8ecc900b`

flake.lock
| [`bdb5bcad`](https://github.com/nix-community/home-manager/commit/bdb5bcad01ff7332fdcf4b128211e81905113f84) | `` home-cursor: improve icon compatibility `` |
=> chore(flake/home-manager): `6a94c1a5` -> `bdb5bcad`

flake.lock
| [`66ee5202`](https://github.com/NixOS/nixpkgs/commit/66ee520289a94519350a741924a52b41ae8237df) | `` grocy: replace @ma27 with @n0emis as maintainer ``                                       |
| [`ca499f69`](https://github.com/NixOS/nixpkgs/commit/ca499f6965b5db2aede9734706e288f4d6012fe8) | `` python.tests.tkinter: init ``                                                            |
| …
=> chore(flake/nixpkgs): `8ecc900b` -> `d680ded2`

flake.lock
| [`4e3e9483`](https://github.com/nix-community/nix-index-database/commit/4e3e9483620334a08f942d61cc834b45d12505aa) | `` flake.lock: Update `` |
=> chore(flake/nix-index-database): `f4d70d09` -> `4e3e9483`

flake.lock
| [`4becac13`](https://github.com/nix-community/nix-index-database/commit/4becac130db930e9de8c3fe58bfa245c119b9eeb) | `` update packages.nix to release 2023-08-20-034804 `` |
=> chore(flake/nix-index-database): `4e3e9483` -> `4becac13`

flake.lock
| [`958c0630`](https://github.com/nix-community/home-manager/commit/958c06303f43cf0625694326b7f7e5475b1a2d5c) | `` flake.lock: Update `` |
=> chore(flake/home-manager): `bdb5bcad` -> `958c0630`

flake.lock
| [`ea59b79f`](https://github.com/nix-community/home-manager/commit/ea59b79f31beaf4a8cb0ea2fc4dfba5732e4212a) | `` bat: generate cache file in XDG cache home ``            |
| [`ca4126e3`](https://github.com/nix-community/home-manager/commit/ca4126e3c568be23a0981c4d69aed078486c5fce) | `` nixos: only refer to `users.users` if needed ``          |
| [`a0ad9817`](https://github.com/nix-community/home-manager/commit/a0ad98174c7a1f9747a76025a83b50e37181 …
=> chore(flake/home-manager): `958c0630` -> `ea59b79f`

flake.lock
| [`8eb8c212`](https://github.com/nix-community/home-manager/commit/8eb8c212e50e2fd95af5849585a2eb819add0a1e) | `` qcal: add module `` |
=> chore(flake/home-manager): `ea59b79f` -> `8eb8c212`

flake.lock
| Commit                                                                                         | Message                                                                                                                              |
| ---------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------------------------------------------------------ |
| [`53d7ae9d`](https://github.com/NixOS/nixpkgs/commit/53d7ae9de93fd8a30b9c5d5db035d6f7edfe9487) | `` budgie.budgie-desktop: 10.7.2 -> 10.8 ``                                                                                          |
| [`6d2033e2`](https://github.com/NixOS/nixpkgs/commit/6d2033e2b997b9cccbad098ff7b54fbc54c4d9f0) …
=> chore(flake/nixpkgs): `d680ded2` -> `91a22f76`

flake.lock
| [`6a20e40a`](https://github.com/nix-community/home-manager/commit/6a20e40acaebf067da682661aa67da8b36812606) | `` flake.lock: Update `` |
=> chore(flake/home-manager): `8eb8c212` -> `6a20e40a`

flake.lock
| [`1721b3e7`](https://github.com/numtide/flake-utils/commit/1721b3e7c882f75f2301b00d48a2884af8c448ae) | `` README: add light commercial support offer `` |
=> chore(flake/flake-utils): `919d646d` -> `1721b3e7`

flake.lock
| [`180473db`](https://github.com/numtide/flake-utils/commit/180473db908bf08c74298bccdf969580237be716) | `` Add test to ensure no special handling of hydraJobs `` |
| [`9e0a97e0`](https://github.com/numtide/flake-utils/commit/9e0a97e02654b788ccdfaafe2c719bc0f8411cd6) | `` No special treatment for hydraJobs ``                  |
=> chore(flake/flake-utils): `1721b3e7` -> `f9e7cf81`

flake.lock
| [`22e5560c`](https://github.com/NixOS/nixpkgs/commit/22e5560c8e789172ca7f78b1917c964e6cc0776c) | `` klipper-genconf: remove AVR cross-compiler dependency ``                       |
| [`53771fcb`](https://github.com/NixOS/nixpkgs/commit/53771fcb75525d9a25abf3f8f57e31e87a4fd339) | `` nitter: unstable-2023-07-21 -> unstable-2023-08-08 ``                          |
| [`044e8c4e`](https://github.com/NixOS/nixpkgs/commit/044e8c4e443c6 …
=> chore(flake/nixpkgs): `91a22f76` -> `b85ed9dc`

flake.lock
| [`817e297f`](https://github.com/NixOS/nixos-hardware/commit/817e297fc3352fadc15f2c5306909aa9192d7d97) | `` Dell XPS 9560: More formatting in README ``        |
| [`79a18928`](https://github.com/NixOS/nixos-hardware/commit/79a189283ebaf2a6d384002aeab3a45588c151cc) | `` Dell XPS 9560: Fix README headers ``               |
| [`2455827f`](https://github.com/NixOS/nixos-hardware/commit/2455827f552d9ac86a939e47c4c59187e30b2036) | `` Dell XPS 9560: Fix README links `` …
=> chore(flake/nixos-hardware): `7f183653` -> `817e297f`

flake.lock
| [`42e427f3`](https://github.com/nix-community/nix-index-database/commit/42e427f380d8921b2c0c12f9abcfe0d604d34deb) | `` flake.lock: Update `` |
=> chore(flake/nix-index-database): `4becac13` -> `42e427f3`

flake.lock
| [`53d40cf1`](https://github.com/nix-community/nix-index-database/commit/53d40cf1bea235658ef8f6e8b8a1d033e2ecbfff) | `` update packages.nix to release 2023-08-27-032954 `` |
=> chore(flake/nix-index-database): `42e427f3` -> `53d40cf1`

flake.lock
| [`9706fb8e`](https://github.com/nix-community/home-manager/commit/9706fb8e441a7c56c68bb079480938ed505e8102) | `` flake.lock: Update `` |
=> chore(flake/home-manager): `6a20e40a` -> `9706fb8e`

flake.lock
| [`f8c5fd75`](https://github.com/nix-community/home-manager/commit/f8c5fd75092448ac134d7fb823556b37d3c821f5) | `` chromium: add support for dictionaries `` |
=> chore(flake/home-manager): `9706fb8e` -> `f8c5fd75`

flake.lock
| [`90e62f96`](https://github.com/nix-community/home-manager/commit/90e62f96c775162580091085831f89b49dba2ee3) | `` programs.yazi: add module (#4373) `` |
=> chore(flake/home-manager): `f8c5fd75` -> `90e62f96`

flake.lock
| [`43ec65ad`](https://github.com/nix-community/home-manager/commit/43ec65ad553dab80a8f619e6e3e888002772ce58) | `` Translate using Weblate (Danish) ``     |
| [`455cc8cf`](https://github.com/nix-community/home-manager/commit/455cc8cf1c768a1d85c30ea102c574cc77663101) | `` offlineimap: cleanup unused bindings `` |
| [`0962772e`](https://github.com/nix-community/home-manager/commit/0962772e0bc4631394b694df27331e9a3a5a5028) | `` antidote: cleanup unused bindings ``    |
| …
=> chore(flake/home-manager): `90e62f96` -> `43ec65ad`

flake.lock
| [`a61f1915`](https://github.com/NixOS/nixpkgs/commit/a61f1915d4f4d0c0cc2f46438a8fff5f6593eaa8) | `` h: 1.0.3 -> 1.0.4 ``                                                        |
| [`3d6dd9b4`](https://github.com/NixOS/nixpkgs/commit/3d6dd9b4afb10ae8bf05f802922baef6fea516d8) | `` stacktile: init at 1.0.0 ``                                                 |
| [`38b9aaf6`](https://github.com/NixOS/nixpkgs/commit/38b9aaf6682015f1d2fc7b7f4 …
=> chore(flake/nixpkgs): `b85ed9dc` -> `cf2004af`

flake.lock
| [`8bde7a65`](https://github.com/nix-community/home-manager/commit/8bde7a651b94ba30bd0baaa9c4a08aae88cc2e92) | `` ci: bump DeterminateSystems/update-flake-lock from 19 to 20 `` |
=> chore(flake/home-manager): `43ec65ad` -> `8bde7a65`

flake.lock
| Commit                                                                                         | Message                                                                                 |
| ---------------------------------------------------------------------------------------------- | --------------------------------------------------------------------------------------- |
| [`c0d989e0`](https://github.com/NixOS/nixpkgs/commit/c0d989e039dafa1c4a2a2d45945f12b22c78d6cf) | `` python311Packages.json-tricks: 3.17.2 -> 3.17.3 ``                                   |
| [`6bccb528`](https://github.com/NixOS/nixpkgs/commit/6bccb5287af838353ef766450f4c5c1ff40412a6) | `` python311Packages.casbin: 1.23.1 -> 1.24.0 ``                                        |
| …
=> chore(flake/nixpkgs): `cf2004af` -> `a999c1cc`

flake.lock
| Commit                                                                                         | Message                                                                                    |
| ---------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------------ |
| [`bd194f33`](https://github.com/NixOS/nixpkgs/commit/bd194f336c1e69842255803199118f3d19b97bf7) | `` pgbadger: 11.5 -> 12.2 ``                                                               |
| [`14aa0299`](https://github.com/NixOS/nixpkgs/commit/14aa0299977f7bfe84a4969526f4df138d30d543) | `` python311Packages.homematicip: 1.0.14 -> 1.0.15 ``                                      |
| …
=> chore(flake/nixpkgs): `a999c1cc` -> `3efb0f6f`

flake.lock
| [`a7eab56b`](https://github.com/nix-community/home-manager/commit/a7eab56be526bb0c052ffe187177268efabc4808) | `` programs.khal: add `settings` option (#4375) `` |
=> chore(flake/home-manager): `8bde7a65` -> `a7eab56b`

flake.lock
| Commit                                                                                         | Message                                                                                                               |
| ---------------------------------------------------------------------------------------------- | --------------------------------------------------------------------------------------------------------------------- |
| [`76fd17ac`](https://github.com/NixOS/nixpkgs/commit/76fd17ac22d892099775c22d0d54e209d3df27e2) | `` terraform-providers.ibm: 1.56.1 -> 1.56.2 ``                                                                       |
| [`13268f92`](https://github.com/NixOS/nixpkgs/commit/13268f92d27edd5b7a53e8c694e10e76c45a7137) | `` terraform-providers.linode: 2.6.0 -> …
=> chore(flake/nixpkgs): `3efb0f6f` -> `e7f38be3`

flake.lock
| [`f5c15668`](https://github.com/nix-community/home-manager/commit/f5c15668f9842dd4d5430787d6aa8a28a07f7c10) | `` tests: update to match latest TOML output `` |
=> chore(flake/home-manager): `a7eab56b` -> `f5c15668`

flake.lock
| [`d7c9dc08`](https://github.com/NixOS/nixpkgs/commit/d7c9dc08d9d9a817dd8611886b1ff2b2f958c812) | `` python311Packages.pyinsteon: update disabled ``                          |
| [`7a34883b`](https://github.com/NixOS/nixpkgs/commit/7a34883bfbb272d9149cfab413e75de9dedb7906) | `` python311Packages.pyinsteon: add changelog to meta ``                    |
| [`9c9d9f7f`](https://github.com/NixOS/nixpkgs/commit/9c9d9f7f2075eec3e1934d28ec9a3b5f94db3 …
=> chore(flake/nixpkgs): `e7f38be3` -> `3e52e76b`

flake.lock
| [`ba8a6e06`](https://github.com/NixOS/nixos-hardware/commit/ba8a6e0612d2c973d0029945d2bff94d37bb060e) | `` star64: linux: 5.15.115 -> 5.15.128 `` |
=> chore(flake/nixos-hardware): `817e297f` -> `fe0ea731`

flake.lock
| [`aa8aa7e2`](https://github.com/NixOS/nixpkgs/commit/aa8aa7e2ea35ce655297e8322dc82bf77a31d04b) | `` python310Packages.paddleocr: init at 2.7.0.1 ``                                  |
| [`83d358d2`](https://github.com/NixOS/nixpkgs/commit/83d358d2a297c321dc732facd0bdb89bd18c9ad2) | `` lunarml: unstable-2023-07-25 → unstable-2023-08-25 ``                            |
| …
=> chore(flake/nixpkgs): `3e52e76b` -> `aa8aa7e2`

flake.lock
| [`7ac2cd01`](https://github.com/nix-community/home-manager/commit/7ac2cd01ae5bf01e12e4517f38a89cb753c6bd6f) | `` tmpfiles: use only `xdg.configFile` `` |
=> chore(flake/home-manager): `f5c15668` -> `7ac2cd01`

flake.lock
| [`fae8af43`](https://github.com/nix-community/home-manager/commit/fae8af43e201a8929ce45a5ea46192bbd1ffff18) | `` Translate using Weblate (Polish) `` |
=> chore(flake/home-manager): `7ac2cd01` -> `fae8af43`

flake.lock
| [`c7ff716e`](https://github.com/nix-community/nix-index-database/commit/c7ff716eee877e60a6a729a74e13f8fe23efd54f) | `` flake.lock: Update `` |
=> chore(flake/nix-index-database): `53d40cf1` -> `c7ff716e`

flake.lock
| [`aca56a79`](https://github.com/nix-community/nix-index-database/commit/aca56a79afb82208af2b39d8459dd29c10989135) | `` update packages.nix to release 2023-09-03-032725 `` |
=> chore(flake/nix-index-database): `c7ff716e` -> `aca56a79`

flake.lock
| [`793de77d`](https://github.com/NixOS/nixos-hardware/commit/793de77d9f83418b428e8ba70d1e42c6507d0d35) | `` purism librem5r4: add configuration option for audio ``          |
| [`3284d060`](https://github.com/NixOS/nixos-hardware/commit/3284d0605cce3e49e35a28924f4f6cfa9edd8a60) | `` purism librem5r4: update uboot ``                                |
| [`6a1fb218`](https://github.com/NixOS/nixos-hardware/commit/6a1fb21810cc075f33d55a134c84d1039d …
=> chore(flake/nixos-hardware): `fe0ea731` -> `793de77d`

flake.lock
| [`8e49b883`](https://github.com/nix-community/home-manager/commit/8e49b883890ccb52c059abb152b00a416342ec1c) | `` flake.lock: Update `` |
=> chore(flake/home-manager): `fae8af43` -> `8e49b883`

flake.lock
| [`3690d7f9`](https://github.com/NixOS/nixpkgs/commit/3690d7f945bcd34e10a6e318ce534f9d384f4d54) | `` linux-rt_5_15: 5.15.125-rt66 -> 5.15.129-rt67 ``                            |
| [`265e6de1`](https://github.com/NixOS/nixpkgs/commit/265e6de15a7f817a5f21badc79882acfd83e122f) | `` ttop: 1.0.1 → 1.2.0 ``                                                      |
| [`6c9c7470`](https://github.com/NixOS/nixpkgs/commit/6c9c7470be852ed37663fdced …
=> chore(flake/nixpkgs): `aa8aa7e2` -> `e5699088`

flake.lock
| [`3c0e381f`](https://github.com/nix-community/home-manager/commit/3c0e381fef63e4fbc6c3292c9e9cbcf479c01794) | `` carapace: add module ``                             |
| [`886ea1d2`](https://github.com/nix-community/home-manager/commit/886ea1d213efd1082f419d066e89ef37635dc970) | `` accounts.email: fix runbox.com TLS setup (#4408) `` |
=> chore(flake/home-manager): `8e49b883` -> `3c0e381f`

flake.lock
| [`b22d7bab`](https://github.com/nix-community/home-manager/commit/b22d7bab30076bbb73744867d6c5bf7d6380570c) | `` flake.lock: Update `` |
=> chore(flake/home-manager): `3c0e381f` -> `b22d7bab`

flake.lock
| [`3c15feef`](https://github.com/NixOS/nixpkgs/commit/3c15feef7770eb5500a4b8792623e2d6f598c9c1) | `` root: 6.26.10 -> 6.28.06 (#215187) ``                                       |
| [`238a2f85`](https://github.com/NixOS/nixpkgs/commit/238a2f85cf6a2a610acd02791fdf5acc9f1f701a) | `` kraft: 0.6.4 -> 0.6.6 ``                                                    |
| [`85cd8cae`](https://github.com/NixOS/nixpkgs/commit/85cd8caee853dc525f2a280a6 …
=> chore(flake/nixpkgs): `e5699088` -> `3c15feef`

flake.lock
| Commit                                                                                         | Message                                                                 |
| ---------------------------------------------------------------------------------------------- | ----------------------------------------------------------------------- |
| [`0bffda19`](https://github.com/NixOS/nixpkgs/commit/0bffda19b8af722f8069d09d8b6a24594c80b352) | `` buildbot: 3.9.0 -> 3.9.2 ``                                          |
| [`6ab91385`](https://github.com/NixOS/nixpkgs/commit/6ab913850d39aae112a1397ca2491e82c7bd2465) | `` garage: 0.8.3 -> 0.8.4 (#253542) ``                                  |
| [`39cec7b9`](https://github.com/NixOS/nixpkgs/commit/39cec7b937c2075c0c53ab97fe20a5988c326a2d) | `` …
=> chore(flake/nixpkgs): `3c15feef` -> `0bffda19`

flake.lock
| Commit                                                                                                      | Message               |
| ----------------------------------------------------------------------------------------------------------- | --------------------- |
| [`91341cde`](https://github.com/nix-community/home-manager/commit/91341cde4143b10ee66e994a53c35d376ad6cdfb) | `` eza: add module `` |
=> chore(flake/home-manager): `b22d7bab` -> `91341cde`

flake.lock
| Commit                                                                                                      | Message              |
| ----------------------------------------------------------------------------------------------------------- | -------------------- |
| [`f1d4f49e`](https://github.com/nix-community/home-manager/commit/f1d4f49e716df353eb7851b2eec4afe58aa3b697) | `` just: simplify `` |
=> chore(flake/home-manager): `91341cde` -> `f1d4f49e`

flake.lock
| Commit                                                                                              | Message                       |
| --------------------------------------------------------------------------------------------------- | ----------------------------- |
| [`d0cfc042`](https://github.com/serokell/deploy-rs/commit/d0cfc042eba92eb206611c9e8784d41a2c053bab) | `` Update README.md (#227) `` |
=> chore(flake/deploy-rs): `724463b5` -> `d0cfc042`

flake.lock
| [`19c6a408`](https://github.com/nix-community/home-manager/commit/19c6a4081b14443420358262f8416149bd79561a) | `` emacs: add version for default.el package `` |
=> chore(flake/home-manager): `f1d4f49e` -> `19c6a408`

flake.lock
| [`a4f6862f`](https://github.com/NixOS/nixpkgs/commit/a4f6862fb17a1a325090a309b362cddba7292a61) | `` klipper: fix cross compilation ``                                                              |
| [`b90ab315`](https://github.com/NixOS/nixpkgs/commit/b90ab315c1407e6eb0dc53917c2d866d65e0eab2) | `` unit: remove `withPerldevel` option ``                                                         |
| …
=> chore(flake/nixpkgs): `0bffda19` -> `db9208ab`

flake.lock
| [`6f22fe45`](https://github.com/nix-community/nix-index-database/commit/6f22fe45afe3b1e9229aee8037ba1c2bb56c4937) | `` flake.lock: Update `` |
=> chore(flake/nix-index-database): `aca56a79` -> `6f22fe45`

flake.lock
| [`71d840d8`](https://github.com/nix-community/nix-index-database/commit/71d840d865b03ab1330d9b7f030a263991ee04e9) | `` update packages.nix to release 2023-09-10-033525 `` |
=> chore(flake/nix-index-database): `6f22fe45` -> `71d840d8`

flake.lock
| [`f9041d12`](https://github.com/nix-community/home-manager/commit/f9041d12a90e8bc0c90e03be2ebe26a6c6e6fd70) | `` home-manager: fix some completions commands `` |
=> chore(flake/home-manager): `19c6a408` -> `f9041d12`

flake.lock
| Commit                                                                                                       | Message                                    |
| ------------------------------------------------------------------------------------------------------------ | ------------------------------------------ |
| [`ca16236a`](https://github.com/cachix/pre-commit-hooks.nix/commit/ca16236a0e6930760e0562501ceb4e8796878a70) | `` Add hook for vale (linter for prose) `` |
| [`e38142d2`](https://github.com/cachix/pre-commit-hooks.nix/commit/e38142d21ea9b5af8e77602edb1cc41677a4c477) | `` Add flags to isort hook ``              |
=> chore(flake/pre-commit-hooks): `7e3517c0` -> `58e22ea8`

flake.lock
| Commit                                                                                                       | Message                                                  |
| ------------------------------------------------------------------------------------------------------------ | -------------------------------------------------------- |
| [`bc3a057e`](https://github.com/cachix/pre-commit-hooks.nix/commit/bc3a057e5738e336f8b7569c95d35487d5d5eeb5) | `` Add pre-commit hook for lychee (fast link checker) `` |
=> chore(flake/pre-commit-hooks): `58e22ea8` -> `4f883a76`

flake.lock
| [`c3c9f478`](https://github.com/danth/stylix/commit/c3c9f4784b4f08f6676340126858d936edbce1fa) | `` Add support for Hyprland (#145) ``              |
| [`c3d11959`](https://github.com/danth/stylix/commit/c3d119590887c16fcf9b003200aded139e454d3d) | `` epkgs.trivialBuild: set dummy version (#150) `` |
=> chore(flake/stylix): `beb35709` -> `c3c9f478`

flake.lock
| [`2b637f32`](https://github.com/nix-community/home-manager/commit/2b637f3289772168800e4c95fa4168741a5886f1) | `` Translate using Weblate (Czech) ``       |
| [`3dd5470e`](https://github.com/nix-community/home-manager/commit/3dd5470e59deab403a1c832cd047dd2ca08fc897) | `` Add translation using Weblate (Czech) `` |
| [`11c91750`](https://github.com/nix-community/home-manager/commit/11c91750b0e056342fbee01fcf87548dda960fba) | `` Translate using Weblate (Czech) ``       |
=> chore(flake/home-manager): `f9041d12` -> `2b637f32`

flake.lock
| [`f7848d3e`](https://github.com/nix-community/home-manager/commit/f7848d3e5f15ed02e3f286029697e41ee31662d7) | `` nixos: increase TimeoutStartSec from 1m30s to 5m `` |
=> chore(flake/home-manager): `2b637f32` -> `f7848d3e`

flake.lock
| Commit                                                                                                            | Message                            |
| ----------------------------------------------------------------------------------------------------------------- | ---------------------------------- |
| [`f4fc78e3`](https://github.com/nix-community/nix-index-database/commit/f4fc78e3b870344c6aa8a72d089d1cce100a3f23) | `` update mergify configuration `` |
=> chore(flake/nix-index-database): `71d840d8` -> `753d1e11`

flake.lock
| Commit                                                                                                | Message                                                                                                                                                                                        |
| ----------------------------------------------------------------------------------------------------- | ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| [`ca41b8a2`](https://github.com/NixOS/nixos-hardware/commit/ca41b8a227dd235b1b308217f116c7e6e84ad779) | `` build(deps): bump cachix/install-nix-action from 22 to 23 `` …
=> chore(flake/nixos-hardware): `793de77d` -> `ca41b8a2`

flake.lock
| Commit                                                                                                            | Message                                            |
| ----------------------------------------------------------------------------------------------------------------- | -------------------------------------------------- |
| [`9a5c4996`](https://github.com/nix-community/nix-index-database/commit/9a5c4996d0918a151269600dfdf6ad3b3748f6a4) | `` Bump cachix/install-nix-action from 22 to 23 `` |
| [`e18bb7ff`](https://github.com/nix-community/nix-index-database/commit/e18bb7ff330f3ddc132e0dd7331c6cd6ee3e65e9) | `` Bump actions/checkout from 3 to 4 ``            |
=> chore(flake/nix-index-database): `753d1e11` -> `9a5c4996`

flake.lock
| [`ac1c7c34`](https://github.com/nix-community/home-manager/commit/ac1c7c34dbf4f3f213f47a4cb8d09a4b4bb18b18) | `` exa: replace with eza `` |
=> chore(flake/home-manager): `f7848d3e` -> `ac1c7c34`

flake.lock
| [`5171f5ef`](https://github.com/nix-community/home-manager/commit/5171f5ef654425e09d9c2100f856d887da595437) | `` swaylock: document the need for host PAM configuration `` |
| [`ae2cc6a8`](https://github.com/nix-community/home-manager/commit/ae2cc6a88c19a61c23dba9faf64df85ddd09c510) | `` ci: bump actions/checkout from 3 to 4 ``                  |
| [`bfe38782`](https://github.com/nix-community/home-manager/commit/bfe38782355f2f10bd705c31ff2e71b6 …
=> chore(flake/home-manager): `ac1c7c34` -> `5171f5ef`

flake.lock
| Commit                                                                                              | Message                                                 |
| --------------------------------------------------------------------------------------------------- | ------------------------------------------------------- |
| [`f26e888c`](https://github.com/serokell/deploy-rs/commit/f26e888c41d28107de9dbc5b4e1553c1dfcf83db) | `` [#201] Deduce profile directory during activation `` |
=> chore(flake/deploy-rs): `d0cfc042` -> `31c32fb2`

flake.lock
| [`ff7b65b4`](https://github.com/numtide/flake-utils/commit/ff7b65b44d01cf9ba6a71320833626af21126384) | `` Bump cachix/install-nix-action from 22 to 23 (#106) `` |
| [`286e744c`](https://github.com/numtide/flake-utils/commit/286e744c9654ef158fd3b9ef2526966ba41ebf58) | `` Bump actions/checkout from 3 to 4 (#105) ``            |
=> chore(flake/flake-utils): `f9e7cf81` -> `ff7b65b4`

flake.lock
| [`a0ddf43b`](https://github.com/nix-community/home-manager/commit/a0ddf43b6268f1717afcda54133dea30435eb178) | `` xplr: add module `` |
=> chore(flake/home-manager): `5171f5ef` -> `a0ddf43b`

flake.lock
| [`3ccd87fc`](https://github.com/NixOS/nixos-hardware/commit/3ccd87fcdae4732fe33773cefa4375c641a057e7) | `` starfive visionfive2: update u-boot to SDK version v3.6.1 ``  |
| [`e158702c`](https://github.com/NixOS/nixos-hardware/commit/e158702cb8e39dc484c594a8bd733ca623f3309c) | `` refactor: use nixpkgs naming conventions ``                   |
| [`c49c1210`](https://github.com/NixOS/nixos-hardware/commit/c49c1210d664de999fe210e95c6e83cbfb8bbbc8) | …
=> chore(flake/nixos-hardware): `ca41b8a2` -> `3ccd87fc`

flake.lock
| Commit                                                                                                    | Message                                                                       |
| --------------------------------------------------------------------------------------------------------- | ----------------------------------------------------------------------------- |
| [`83f43769`](https://github.com/nix-community/lanzaboote/commit/83f437692968005e7f96b754b061789cc299af66) | `` uefi: move uefi code to separate workspace ``                              |
| [`64f17609`](https://github.com/nix-community/lanzaboote/commit/64f17609449c687abdf680d0ca7649ed28f6e99f) | `` flake: add cargo-machete to machete the unused crates in our Cargo.toml `` |
| …
=> chore(flake/lanzaboote): `9a9b0962` -> `3dc8778c`

flake.lock
| [`aed5ed97`](https://github.com/nix-community/home-manager/commit/aed5ed979eced3790a39d069f08884061bda3c82) | `` bat: allow adding custom syntaxes `` |
=> chore(flake/home-manager): `d12c8fc8` -> `aed5ed97`

flake.lock
| [`a8cde785`](https://github.com/nix-community/home-manager/commit/a8cde785062bdc2a6a52e330dfb461f969f4558d) | `` home-manager: update translation templates `` |
| [`f07207f8`](https://github.com/nix-community/home-manager/commit/f07207f8cab92d52b3871c760b8007ab32ff66cb) | `` home-manager: fix typo ``                     |
| [`5f5cb7a6`](https://github.com/nix-community/home-manager/commit/5f5cb7a61360ba6555cf0875c590c0fe0f698d5e) | `` carapace: add xgettext …
=> chore(flake/home-manager): `aed5ed97` -> `b62f5496`

flake.lock
| [`d9b88b43`](https://github.com/nix-community/home-manager/commit/d9b88b43524db1591fb3d9410a21428198d75d49) | `` Update translation files `` |
=> chore(flake/home-manager): `b62f5496` -> `d9b88b43`

flake.lock
| [`850b04d5`](https://github.com/NixOS/nixos-hardware/commit/850b04d59cbc003158b5258932dab6e26ed0b388) | `` star64: use stable opensbi release `` |
| [`16b8c06f`](https://github.com/NixOS/nixos-hardware/commit/16b8c06fd3d20dc52f867d44a3bf1aa75d911c7f) | `` star64: add mmc firmware updater ``   |
=> chore(flake/nixos-hardware): `3ccd87fc` -> `850b04d5`

flake.lock
| Commit                                                                                                    | Message                                     |
| --------------------------------------------------------------------------------------------------------- | ------------------------------------------- |
| [`0c7606cd`](https://github.com/nix-community/lanzaboote/commit/0c7606cd18add2846f4341d0035c602532c42342) | `` flake: use an appropriate description `` |
| [`e766f364`](https://github.com/nix-community/lanzaboote/commit/e766f364414f61b97a0af7e38bc881d652d4afc1) | `` Fix lzbt, stub path links ``             |
=> chore(flake/lanzaboote): `3dc8778c` -> `7ef2b137`

flake.lock
| Commit                                                                                                    | Message                                                                        |
| --------------------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------ |
| [`ff442cd0`](https://github.com/nix-community/lanzaboote/commit/ff442cd03266f8b982a7eb7f40c38c88c62d1f7d) | `` tool: introduce some more whitespace ``                                     |
| [`143a000f`](https://github.com/nix-community/lanzaboote/commit/143a000f369f829c23a720bafc5ba38048562347) | `` tool: separates use statements correctly with whitespace ``                 |
| …
=> chore(flake/lanzaboote): `7ef2b137` -> `45b529ca`

flake.lock
| Commit                                                                                                    | Message                       |
| --------------------------------------------------------------------------------------------------------- | ----------------------------- |
| [`8c6ef1f1`](https://github.com/nix-community/lanzaboote/commit/8c6ef1f190d84c9a9aabc737b8876072bc65629d) | `` flake: remove nixConfig `` |
=> chore(flake/lanzaboote): `45b529ca` -> `1255f8fc`

flake.lock
| Commit                                                                                                    | Message                          |
| --------------------------------------------------------------------------------------------------------- | -------------------------------- |
| [`3dab5531`](https://github.com/nix-community/lanzaboote/commit/3dab5531b1dfd252d5ede21659c2ea32a2e6ce74) | `` stub: remove TPM 1 support `` |
=> chore(flake/lanzaboote): `1255f8fc` -> `7f92dd1e`

flake.lock
| [`57025632`](https://github.com/NixOS/nixos-hardware/commit/570256327eb6ca6f7bebe8d93af49459092a0c43) | `` star64: fix boot from eMMC `` |
=> chore(flake/nixos-hardware): `850b04d5` -> `57025632`

flake.lock
| Commit                                                                                         | Message                                                          |
| ---------------------------------------------------------------------------------------------- | ---------------------------------------------------------------- |
| [`2ed2dc75`](https://github.com/ryantm/agenix/commit/2ed2dc758234f0ccdae47f7f0a007450858001e1) | `` dev: try switching to determinate systems installer action `` |
| [`54693c91`](https://github.com/ryantm/agenix/commit/54693c91d923fecb4cf04c4535e3d84f8dec7919) | `` version 0.14.0 ``                                             |
| [`1698ed38`](https://github.com/ryantm/agenix/commit/1698ed385d3142a5ff927d5eafe4642207652dcd) | `` Create …
=> chore(flake/agenix): `d8c973fd` -> `20deb735`

flake.lock
| Commit                                                                                         | Message                                                  |
| ---------------------------------------------------------------------------------------------- | -------------------------------------------------------- |
| [`fe4f564f`](https://github.com/ryantm/agenix/commit/fe4f564f13c6151df7983fc3449061dc71c37d8d) | `` fix(home): shellcheck failure for fixed secretsDir `` |
=> chore(flake/agenix): `20deb735` -> `da5d6f05`

flake.lock
| Commit                                                                                           | Message                                                    |
| ------------------------------------------------------------------------------------------------ | ---------------------------------------------------------- |
| [`c8f0bc5c`](https://github.com/LnL7/nix-darwin/commit/c8f0bc5c295b3612c1ff5dc31e0571f15617aa63) | `` time: bury useless `systemsetup -settimezone` output `` |
=> chore(flake/darwin): `4496ab26` -> `80bb201f`

flake.lock
| [`5ddcb3bf`](https://github.com/nix-community/nix-index-database/commit/5ddcb3bfb29aef87f92abc2a8edcef7f58f6602c) | `` flake.lock: Update `` |
=> chore(flake/nix-index-database): `9a5c4996` -> `5ddcb3bf`

flake.lock
| [`9d2bcc47`](https://github.com/nix-community/nix-index-database/commit/9d2bcc47110b3b6217dfebd6761ba20bc78aedf2) | `` update packages.nix to release 2023-09-17-033648 `` |
=> chore(flake/nix-index-database): `5ddcb3bf` -> `9d2bcc47`

flake.lock
| Commit                                                                                                | Message                         |
| ----------------------------------------------------------------------------------------------------- | ------------------------------- |
| [`b0f82bcf`](https://github.com/NixOS/nixos-hardware/commit/b0f82bcf524924fa9672be7f81292731d7d8c133) | `` replace bors with mergify `` |
=> chore(flake/nixos-hardware): `57025632` -> `b0f82bcf`

flake.lock
| Commit                                                                                              | Message                                            |
| --------------------------------------------------------------------------------------------------- | -------------------------------------------------- |
| [`b5625de9`](https://github.com/serokell/deploy-rs/commit/b5625de9c918d4ea318627fc1a18943ac8c1e1b1) | `` Replace jsonschema-cli with check-jsonschema `` |
=> chore(flake/deploy-rs): `31c32fb2` -> `57d5071e`

flake.lock
| Commit                                                                                                | Message                     |
| ----------------------------------------------------------------------------------------------------- | --------------------------- |
| [`161b0271`](https://github.com/NixOS/nixos-hardware/commit/161b027169b19d3a0ad6bd0a8948edf0c0fb0f64) | `` Fix typo in README.md `` |
=> chore(flake/nixos-hardware): `d53069de` -> `161b0271`

flake.lock
| [`e63a6b34`](https://github.com/nix-community/home-manager/commit/e63a6b34792884bfe4056d1ef561b5611589b8ad) | `` programs.i3status-rust: reload on config change (#4466) `` |
=> chore(flake/home-manager): `d9b88b43` -> `e63a6b34`

flake.lock
| Commit                                                                                              | Message                                       |
| --------------------------------------------------------------------------------------------------- | --------------------------------------------- |
| [`5617d39d`](https://github.com/serokell/deploy-rs/commit/5617d39d3a685539372260a8c38ee68a0abbc203) | `` [Chore] Run CI checks on 'pull_request' `` |
=> chore(flake/deploy-rs): `57d5071e` -> `e3f41832`

flake.lock
| [`f092a922`](https://github.com/nix-community/home-manager/commit/f092a9220220e390c76605b6c4e2238774050f8b) | `` programs.rio: add module (#4118) `` |
=> chore(flake/home-manager): `e63a6b34` -> `f092a922`

flake.lock
| [`feb70061`](https://github.com/nix-community/home-manager/commit/feb70061596134d403e14cc5ef7b01ab114d1dbd) | `` git: replace gitToInit with lib function `` |
=> chore(flake/home-manager): `f092a922` -> `feb70061`

flake.lock
| [`f5966ce3`](https://github.com/NixOS/nixpkgs/commit/f5966ce35f0d56b5a8a6bf62fb412b1532506cff) | `` replxx: init at 0.0.4 ``                                                  |
| [`df39696f`](https://github.com/NixOS/nixpkgs/commit/df39696f6b35b4e21cf15bb65518ee1b5f67ee3d) | `` chromium: temporarily work around stdenv/patchShebangs.sh bug ``          |
| [`c6201300`](https://github.com/NixOS/nixpkgs/commit/c62013004e42033c5f11cfff99d3ce5d0 …
=> chore(flake/nixpkgs): `ace5093e` -> `970a59bd`

flake.lock
| [`f6bb34a5`](https://github.com/NixOS/nixos-hardware/commit/f6bb34a52acbd78d34bea30bb1c8199d9b0d2bf3) | `` only trigger ci on master branch and pull requests `` |
| [`cf88c13c`](https://github.com/NixOS/nixos-hardware/commit/cf88c13ca636e7520bb6922cb31a800075657c75) | `` tests: set linux_latest as the default kernel ``      |
=> chore(flake/nixos-hardware): `161b0271` -> `f6bb34a5`

flake.lock
| [`92364581`](https://github.com/nix-community/home-manager/commit/92364581dd3ada6981c4ddc5def8a35a1b945e75) | `` tests: sort test list ``         |
| [`8045eb45`](https://github.com/nix-community/home-manager/commit/8045eb45a79b5e585df781c02500d33c9ed96ae0) | `` pasystray: add `extraOptions` `` |
=> chore(flake/home-manager): `feb70061` -> `92364581`

flake.lock
| [`cb4dc98f`](https://github.com/NixOS/nixos-hardware/commit/cb4dc98f776ddb6af165e6f06b2902efe31ca67a) | `` asus-zephyrus-ga402: remove unused kernel parameter `` |
=> chore(flake/nixos-hardware): `f6bb34a5` -> `cb4dc98f`

flake.lock
| [`ee9f5dc8`](https://github.com/nix-community/home-manager/commit/ee9f5dc8f691c69f9bd84194fdbf63d41efb6649) | `` flake.lock: Update `` |
=> chore(flake/home-manager): `92364581` -> `ee9f5dc8`

flake.lock
| [`f5b920f4`](https://github.com/nix-community/home-manager/commit/f5b920f4d2f920a1982ca844cfd22c8f1e82ed7e) | `` fluxbox: fix xsession command `` |
=> chore(flake/home-manager): `ee9f5dc8` -> `f5b920f4`

flake.lock
| [`7ee73f53`](https://github.com/nix-community/home-manager/commit/7ee73f5363bc0f4b0f8042665168c25c90dd16f9) | `` rofi-pass: add package option ``   |
| [`8aac47a1`](https://github.com/nix-community/home-manager/commit/8aac47a140de1153a90bcc509596c65f6d82d832) | `` waybar: fix service After value `` |
=> chore(flake/home-manager): `f5b920f4` -> `7ee73f53`

flake.lock
| [`6f882433`](https://github.com/nix-community/home-manager/commit/6f88243322c315360c1f31a8fc6c43006db51465) | `` starship: use `use` instead of `source` for nushell `` |
=> chore(flake/home-manager): `7ee73f53` -> `6f882433`

flake.lock
| [`3e7202c6`](https://github.com/nix-community/home-manager/commit/3e7202c6387b744dca4feb4217459512886761b5) | `` flake.lock: Update `` |
=> chore(flake/home-manager): `6f882433` -> `3e7202c6`

flake.lock
| [`0ed5f978`](https://github.com/nix-community/home-manager/commit/0ed5f9786bba801c59fb53eef497438040acd471) | `` Add translation using Weblate (Thai) `` |
| [`8847dd8b`](https://github.com/nix-community/home-manager/commit/8847dd8bf35a50e012088d6eef6010a6884b3632) | `` Translate using Weblate (Thai) ``       |
=> chore(flake/home-manager): `3e7202c6` -> `0ed5f978`

flake.lock
| [`408ba131`](https://github.com/nix-community/home-manager/commit/408ba13188ff9ce309fa2bdd2f81287d79773b00) | `` neomutt: fix STARTTLS `` |
=> chore(flake/home-manager): `0ed5f978` -> `408ba131`

flake.lock
| [`ae4acddb`](https://github.com/NixOS/nixpkgs/commit/ae4acddbb6fd69f29373731694213c425bd7c2d9) | `` prismlauncher: include libusb1 as a runtime dependency (#256124) ``      |
| [`c4604341`](https://github.com/NixOS/nixpkgs/commit/c4604341046500273fa1ab5366d07d509d2ff8c2) | `` nixos/vaultwarden: Fix doubly-nested `config` value. Fixes evaluation `` |
| [`fca4826d`](https://github.com/NixOS/nixpkgs/commit/fca4826dcd399813f85b61fec1442c781e345 …
=> chore(flake/nixpkgs): `970a59bd` -> `5ba549ea`

flake.lock
| Commit                                                                                         | Message                                                           |
| ---------------------------------------------------------------------------------------------- | ----------------------------------------------------------------- |
| [`da763b2c`](https://github.com/ryantm/agenix/commit/da763b2c4bfac0310e8c1d972199e10967ad38b8) | `` Don't need concatStringSep if using jq to parse json arrays `` |
| [`eb1386f3`](https://github.com/ryantm/agenix/commit/eb1386f3b246ae563c99ecadaaeff6b6d36fc9a5) | `` Use jq instead of sed ``                                       |
=> chore(flake/agenix): `572baca9` -> `7f9dfa30`

flake.lock
| Commit                                                                                         | Message                                                              |
| ---------------------------------------------------------------------------------------------- | -------------------------------------------------------------------- |
| [`115e5610`](https://github.com/ryantm/agenix/commit/115e561054afd80d22ac6225772ca89333112632) | `` fix: add --strict nix-instantiate to support builtins.readFile `` |
=> chore(flake/agenix): `7f9dfa30` -> `1f677b3e`

flake.lock
| Commit                                                                                            | Message                                                                         |
| ------------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------- |
| [`c659bb93`](https://github.com/lovesegfault/nix/commit/c659bb936465d93e55ca741f3f20ec0ccad4c6cc) | `` feat: add always-allow-substitutes ``                                        |
| [`f3005632`](https://github.com/lovesegfault/nix/commit/f3005632c417615d2cf3a6d102d0f4f041d8b2b7) | `` Re-enable systemd-nspawn test ``                                             |
| [`40a01441`](https://github.com/lovesegfault/nix/commit/40a014 …
=> chore(flake/nix): `a95057b7` -> `c659bb93`

flake.lock
| [`b658dbd8`](https://github.com/LnL7/nix-darwin/commit/b658dbd85a1c70a15759b470d7b88c0c95f497be) | `` Update README ``                       |
| [`6cd2f4ce`](https://github.com/LnL7/nix-darwin/commit/6cd2f4cea255623076722f9acbc3e0db2d0ee43d) | `` Replace hostname with LocalHostName `` |
| [`22419fdd`](https://github.com/LnL7/nix-darwin/commit/22419fddf7f6c4db378dde8e597a405436a292e5) | `` Use LocalHostName ``                   |
=> chore(flake/darwin): `afeddc41` -> `c286b23c`

flake.lock
| [`e0c70942`](https://github.com/nix-community/home-manager/commit/e0c70942c0e7178a56289adea20c056a3cda7c5e) | `` programs.sway: separate trayOutput values for sway (#4489) `` |
=> chore(flake/home-manager): `408ba131` -> `e0c70942`

flake.lock
| [`2d27bdcd`](https://github.com/nix-community/home-manager/commit/2d27bdcd640759a5fb1b48125fee7280adad95f7) | `` direnv: fix nushell syntax ``             |
| [`7413408b`](https://github.com/nix-community/home-manager/commit/7413408b047c12125cf3b76e5d8fa53c297ac1ee) | `` yazi: add fish and nushell integration `` |
=> chore(flake/home-manager): `e0c70942` -> `2d27bdcd`

flake.lock
| [`597e3de1`](https://github.com/nix-community/nix-index-database/commit/597e3de1d1422763ec5f3b183df14846060343e9) | `` flake.lock: Update `` |
=> chore(flake/nix-index-database): `9d2bcc47` -> `597e3de1`

flake.lock
| [`25d6369c`](https://github.com/nix-community/nix-index-database/commit/25d6369c232bbea1ec1f90226fd17982e7a0a647) | `` update packages.nix to release 2023-09-24-032915 `` |
=> chore(flake/nix-index-database): `597e3de1` -> `25d6369c`

flake.lock
| [`61283b30`](https://github.com/NixOS/nixos-hardware/commit/61283b30d11f27d5b76439d43f20d0c0c8ff5296) | `` framework/*: add fw-ectool for led control, etc `` |
| [`08add92f`](https://github.com/NixOS/nixos-hardware/commit/08add92f1745edd3418b1ea017f8732735a9d9b9) | `` Enabling hp-wmi driver after PR merge ``           |
| [`06178532`](https://github.com/NixOS/nixos-hardware/commit/061785322d93f63b0fa4882ac92030008932a083) | `` Add Omen 15-en0010ca `` …
=> chore(flake/nixos-hardware): `cb4dc98f` -> `61283b30`

flake.lock
| [`835465e8`](https://github.com/nix-community/home-manager/commit/835465e8ba2459034e4ab192b1c6db35d1c0d638) | `` lsd: allow user to configure colors `` |
=> chore(flake/home-manager): `2d27bdcd` -> `835465e8`

flake.lock
| [`4a633326`](https://github.com/nix-community/home-manager/commit/4a6333265ed8f3abf4769db60735522bbaa7819d) | `` flake.lock: Update ``                      |
| [`baf222f2`](https://github.com/nix-community/home-manager/commit/baf222f2fba7bbe6fd2289a6845c884f5cb499d8) | `` tests: add mainProgram to stub packages `` |
=> chore(flake/home-manager): `835465e8` -> `4a633326`

flake.lock
| Commit                                                                                                      | Message                 |
| ----------------------------------------------------------------------------------------------------------- | ----------------------- |
| [`a88df2fb`](https://github.com/nix-community/home-manager/commit/a88df2fb101778bfd98a17556b3a2618c6c66091) | `` bacon: add module `` |
=> chore(flake/home-manager): `4a633326` -> `a88df2fb`

flake.lock
| Commit                                                                                                         | Message                                   |
| -------------------------------------------------------------------------------------------------------------- | ----------------------------------------- |
| [`876ed8cf`](https://github.com/tinted-theming/base16-schemes/commit/876ed8cf1e27354027ccf140b045132b67452378) | `` Add gallery link to README.md (#31) `` |
=> chore(flake/base16-schemes): `d95123ca` -> `876ed8cf`

flake.lock
| Commit                                                                                                       | Message                                         |
| ------------------------------------------------------------------------------------------------------------ | ----------------------------------------------- |
| [`b239875e`](https://github.com/cachix/pre-commit-hooks.nix/commit/b239875ee4b00a71b8a3dafa0e5216075c1421ee) | `` Add hook for flynt ``                        |
| [`e468d8c5`](https://github.com/cachix/pre-commit-hooks.nix/commit/e468d8c5d419aa57d32d77aaffa7841e52a2b495) | `` Refactoring ``                               |
| [`e646271a`](https://github.com/cachix/pre-commit-hooks.nix/commit/e646271a37309fd1eec6b603a5fe576b665e14fa) | `` Use enum for verbosity for …
=> chore(flake/pre-commit-hooks): `4f883a76` -> `cb770e93`

flake.lock
| Commit                                                                                           | Message                                                             |
| ------------------------------------------------------------------------------------------------ | ------------------------------------------------------------------- |
| [`e58bcb92`](https://github.com/LnL7/nix-darwin/commit/e58bcb921bfd6e90b3e2d11a03ba32918a1cfad4) | `` programs.ssh: write ssh known_hosts only if there are any set `` |
=> chore(flake/darwin): `c286b23c` -> `e236a1e5`

flake.lock
| [`dd88dbc6`](https://github.com/nix-community/home-manager/commit/dd88dbc69438384bd94f8282584a86798750028c) | `` neovim: expose `finalPackage` `` |
=> chore(flake/home-manager): `a88df2fb` -> `dd88dbc6`

flake.lock
| [`0f4e5b49`](https://github.com/nix-community/home-manager/commit/0f4e5b4999fd6a42ece5da8a3a2439a50e48e486) | `` keychain: fix edge-cases in nushell integration `` |
=> chore(flake/home-manager): `dd88dbc6` -> `0f4e5b49`

flake.lock
| Commit                                                                                         | Message                                                                                                  |
| ---------------------------------------------------------------------------------------------- | -------------------------------------------------------------------------------------------------------- |
| [`6500b458`](https://github.com/NixOS/nixpkgs/commit/6500b4580c2a1f3d0f980d32d285739d8e156d92) | `` Revert "nixos/boot/rasbperrypi: add support for boot.initrd.secret with uboot (#240358)" (#257251) `` |
| [`3bf3656c`](https://github.com/NixOS/nixpkgs/commit/3bf3656cd084c806ee3b9e9a3247481829437c2a) | `` linux_testing: 6.6-rc2 -> 6.6-rc3 `` …
=> chore(flake/nixpkgs): `5ba549ea` -> `6500b458`

flake.lock
| [`adcfd6aa`](https://github.com/NixOS/nixos-hardware/commit/adcfd6aa860d1d129055039696bc457af7d50d0e) | `` Thinkpad X1 11th Gen: init ``                        |
| [`89ec952f`](https://github.com/NixOS/nixos-hardware/commit/89ec952fd2a481461a86ad581fde2e730e5a951d) | `` chore: Add @emiller88 to CODEOWNERS for framework `` |
=> chore(flake/nixos-hardware): `61283b30` -> `adcfd6aa`

flake.lock
| [`9d4cdf8c`](https://github.com/nix-community/home-manager/commit/9d4cdf8cc4da54beb5d2e927af7a259bb4a00645) | `` Translate using Weblate (Danish) ``     |
| [`1d813ff5`](https://github.com/nix-community/home-manager/commit/1d813ff5a677c2e97a4cb0726bbb3b6ebce1c8ed) | `` qt: remove qtstyleplugin-kvantum-qt4 `` |
=> chore(flake/home-manager): `0f4e5b49` -> `9d4cdf8c`

flake.lock
| Commit                                                                                                    | Message                                                                                |
| --------------------------------------------------------------------------------------------------------- | -------------------------------------------------------------------------------------- |
| [`7951cbc6`](https://github.com/nix-community/lanzaboote/commit/7951cbc66893e6ebf1d49a1fa048710240c0141c) | `` flake: bump to get systemd v254 ``                                                  |
| [`976faf9b`](https://github.com/nix-community/lanzaboote/commit/976faf9bf56a46a51d92777b04c0d3f9fc078074) | `` flake: use proper uefi target in general ``                                         |
| …
=> chore(flake/lanzaboote): `7f92dd1e` -> `644dc8a2`

flake.lock
| [`03fe55d3`](https://github.com/NixOS/nixpkgs/commit/03fe55d3540815409fce6b898528fc2c8e087cd2) | `` glasgow: fix on non-NixOS ``                                              |
| [`4d011cb1`](https://github.com/NixOS/nixpkgs/commit/4d011cb112133dfcb1bcc3a07a9768b5f60702bc) | `` glasgow: fix tests on darwin ``                                           |
| [`d2aef1a1`](https://github.com/NixOS/nixpkgs/commit/d2aef1a14553f41a12749070b8bbe082d …
=> chore(flake/nixpkgs): `6500b458` -> `8a86b98f`

flake.lock
| [`2ccb5cb5`](https://github.com/nix-community/home-manager/commit/2ccb5cb542357af20eb18c83f38571da7b3bcff6) | `` Translate using Weblate (Turkish) `` |
=> chore(flake/home-manager): `9d4cdf8c` -> `2ccb5cb5`

flake.lock
| [`4f02e35f`](https://github.com/nix-community/home-manager/commit/4f02e35f9d150573e1a710afa338846c2f6d850c) | `` direnv: add package options `` |
=> chore(flake/home-manager): `2ccb5cb5` -> `4f02e35f`

flake.lock
| [`d5e6d91b`](https://github.com/nix-community/lanzaboote/commit/d5e6d91b4ff2f85e38940d2b0f2b6828410f8456) | `` Fix eval in flakes when aliases are disabled `` |
| [`a55db483`](https://github.com/nix-community/lanzaboote/commit/a55db483fba64daa7b3de573433af2d12ad924b4) | `` nix/modules/uki: fix ukify build ``             |
=> chore(flake/lanzaboote): `644dc8a2` -> `8154cef1`

flake.lock
| Commit                                                                                           | Message                                                             |
| ------------------------------------------------------------------------------------------------ | ------------------------------------------------------------------- |
| [`ab817e5d`](https://github.com/LnL7/nix-darwin/commit/ab817e5d0e8561949dbc1a9640f88cde2990d862) | `` darwin-rebuild: add `-H` to sudo for `$systemConfig/activate` `` |
=> chore(flake/darwin): `e236a1e5` -> `792c2e01`

flake.lock
| [`ae896c81`](https://github.com/nix-community/home-manager/commit/ae896c810f501bf0c3a2fd7fc2de094dd0addf01) | `` home-manager: set profile path variables lazily `` |
| [`f1b7775d`](https://github.com/nix-community/home-manager/commit/f1b7775d2393f41acd2b46acaccf0ab6431dea8b) | `` awscli: add module ``                              |
=> chore(flake/home-manager): `4f02e35f` -> `ae896c81`

flake.lock
| [`686d4f15`](https://github.com/nix-community/nix-index-database/commit/686d4f15b4f01621da7ec4de123d530ebb3b23ac) | `` flake.lock: Update `` |
=> chore(flake/nix-index-database): `25d6369c` -> `686d4f15`

flake.lock
| [`031d4b22`](https://github.com/nix-community/nix-index-database/commit/031d4b22505fdea47bd53bfafad517cd03c26a4f) | `` update packages.nix to release 2023-10-01-033420 `` |
=> chore(flake/nix-index-database): `686d4f15` -> `031d4b22`

flake.lock
| [`209a24df`](https://github.com/nix-community/home-manager/commit/209a24dff2b1098f24013cb4877d86cd0ae67c21) | `` wpaperd: add wpaperd configuration `` |
=> chore(flake/home-manager): `ae896c81` -> `209a24df`

flake.lock
| [`86dbce6d`](https://github.com/NixOS/nixpkgs/commit/86dbce6d0788d602df543d08dfd9b692e69739e3) | `` audiobookshelf: init module ``                                                      |
| [`8d8e78c9`](https://github.com/NixOS/nixpkgs/commit/8d8e78c9c22952cce42e09de7e095137ffcedd0b) | `` maintainers: add wietsedv ``                                                        |
| …
=> chore(flake/nixpkgs): `8a86b98f` -> `f5892dda`

flake.lock
| Commit                                                                                                      | Message                 |
| ----------------------------------------------------------------------------------------------------------- | ----------------------- |
| [`6f9b5b83`](https://github.com/nix-community/home-manager/commit/6f9b5b83ad1f470b3d11b8a9fe1d5ef68c7d0e30) | `` khard: add module `` |
=> chore(flake/home-manager): `209a24df` -> `6f9b5b83`

flake.lock
| Commit                                                                                                         | Message                              |
| -------------------------------------------------------------------------------------------------------------- | ------------------------------------ |
| [`a9112eaa`](https://github.com/tinted-theming/base16-schemes/commit/a9112eaae86d9dd8ee6bb9445b664fba2f94037a) | `` Add everforest dark hard (#35) `` |
| [`4fa3a1b6`](https://github.com/tinted-theming/base16-schemes/commit/4fa3a1b6b40a2dc441935369f7295fa957a89238) | `` Add Oxocarbon (#34) ``            |
=> chore(flake/base16-schemes): `876ed8cf` -> `a9112eaa`

flake.lock
| Commit                                                                                                       | Message                      |
| ------------------------------------------------------------------------------------------------------------ | ---------------------------- |
| [`d67283c4`](https://github.com/cachix/pre-commit-hooks.nix/commit/d67283c4d985d69a7cf421e5956d3bc87f6ab3ce) | `` Add support for eclint `` |
=> chore(flake/pre-commit-hooks): `cb770e93` -> `033453f8`

flake.lock
| [`0ab3ee71`](https://github.com/NixOS/nixos-hardware/commit/0ab3ee718e964fb42dc57ace6170f19cb0b66532) | `` CODEOWNERS: add tomfitzhenry to Pine64 Pinebook Pro `` |
=> chore(flake/nixos-hardware): `adcfd6aa` -> `0ab3ee71`

flake.lock
| Commit                                                                                                 | Message                                      |
| ------------------------------------------------------------------------------------------------------ | -------------------------------------------- |
| [`2bf43d60`](https://github.com/edolstra/flake-compat/commit/2bf43d60c7596e26d6f56dde17a466b158a6abb4) | `` Change from rolling to tagged releases `` |
=> chore(flake/flake-compat): `6256b599` -> `2bf43d60`

flake.lock
| Commit                                                                                                 | Message                                           |
| ------------------------------------------------------------------------------------------------------ | ------------------------------------------------- |
| [`4f910c98`](https://github.com/edolstra/flake-compat/commit/4f910c9827911b1ec2bf26b5a062cd09f8d89f85) | `` Doh ``                                         |
| [`7ae5ae62`](https://github.com/edolstra/flake-compat/commit/7ae5ae625a69a4c160e7f5e975e8d5c06a7aee92) | `` Drop "flake = false" and suggest flakehub ``   |
| [`bc5e257a`](https://github.com/edolstra/flake-compat/commit/bc5e257a8d0c4df04652ecff9053d05b0dc9484e) | `` nix#7796: Ensure that `self.outPath == ./.` `` |
=> chore(flake/flake-compat): `2bf43d60` -> `4f910c98`

flake.lock
| [`3d65d139`](https://github.com/LnL7/nix-darwin/commit/3d65d1397403132bf95e8079074141f3d0ab7e37) | `` expose _module attr in realised sysconfig `` |
=> chore(flake/darwin): `792c2e01` -> `8b6ea26d`

flake.lock
| Commit                                                                                                    | Message                                       |
| --------------------------------------------------------------------------------------------------------- | --------------------------------------------- |
| [`7b4d1250`](https://github.com/nix-community/lanzaboote/commit/7b4d1250b7cc1db7e7014f2ec6e206ab07e6c1f4) | `` docs: Add troubleshooting documentation `` |
=> chore(flake/lanzaboote): `8154cef1` -> `bccf7738`

flake.lock
| [`55ce64c3`](https://github.com/nix-community/home-manager/commit/55ce64c3ca031eefb1adac85bb0025887ed7a221) | `` scmpuff: enable or disable aliases `` |
=> chore(flake/home-manager): `6f9b5b83` -> `55ce64c3`

flake.lock
| [`30d2dc8d`](https://github.com/nix-community/home-manager/commit/30d2dc8d689a9060290892164aa4000778e1b42b) | `` flake.lock: Update `` |
=> chore(flake/home-manager): `55ce64c3` -> `30d2dc8d`

flake.lock
| [`e63c30fe`](https://github.com/nix-community/home-manager/commit/e63c30fe9792b57dea1eab98be6871a0e42a33c9) | `` home-manager: fix assignment to read-only variable `` |
=> chore(flake/home-manager): `30d2dc8d` -> `e63c30fe`

flake.lock
| [`ba7d3435`](https://github.com/NixOS/nixpkgs/commit/ba7d34357137e50a2c5f32b8f05b4c96c9bd4942) | `` gitignore: add .nixos-test-history produced by test driver (#258456) `` |
| [`404d4db3`](https://github.com/NixOS/nixpkgs/commit/404d4db375715bce999ae4084c55873427e63022) | `` docs: clarify maintainer name format ``                                 |
| [`3e9edb76`](https://github.com/NixOS/nixpkgs/commit/3e9edb76cff800c8ce9a3b7bd076af2fd3ad6c93) …
=> chore(flake/nixpkgs): `f5892dda` -> `fdd898f8`

flake.lock
| [`4e52d9b7`](https://github.com/nix-community/home-manager/commit/4e52d9b7f7ed92bd98f9eb53f61d838a3928c9cb) | `` flake.lock: Update `` |
=> chore(flake/home-manager): `e63c30fe` -> `4e52d9b7`

flake.lock
| [`b0e0d826`](https://github.com/nix-community/home-manager/commit/b0e0d82696297964f231c37a38e3c64b22ae03e5) | `` zsh-abbr: add module `` |
=> chore(flake/home-manager): `4e52d9b7` -> `b0e0d826`

flake.lock
| [`2874c6fc`](https://github.com/nix-community/home-manager/commit/2874c6fce6de69eaedaa690b5fd6d3c70a2827af) | `` thefuck: add module `` |
=> chore(flake/home-manager): `b0e0d826` -> `2874c6fc`

flake.lock
| [`8aef005d`](https://github.com/nix-community/home-manager/commit/8aef005d44ee726911e9f793495bb40f2fbf5a05) | `` Translate using Weblate (Indonesian) `` |
=> chore(flake/home-manager): `2874c6fc` -> `8aef005d`

flake.lock
| Commit                                                                                                    | Message                                                |
| --------------------------------------------------------------------------------------------------------- | ------------------------------------------------------ |
| [`a78b9682`](https://github.com/nix-community/lanzaboote/commit/a78b9682b77cf0fb2d301f82d55ca5d887cbcafb) | `` docs: Improve troubleshooting documentation ``      |
| [`90a1adac`](https://github.com/nix-community/lanzaboote/commit/90a1adac54c083026d81eddc9e74b1d64754e5af) | `` tool: fix atomic write ``                           |
| [`4fd37670`](https://github.com/nix-community/lanzaboote/commit/4fd37670e28c990bc56abea2bfe45114fbdf7fc6) | `` tool: stop most …
=> chore(flake/lanzaboote): `bccf7738` -> `ac43ac30`

flake.lock
| Commit                                                                                                 | Message                                                          |
| ------------------------------------------------------------------------------------------------------ | ---------------------------------------------------------------- |
| [`0f9255e0`](https://github.com/edolstra/flake-compat/commit/0f9255e01c2351cc7d116c072cb317785dd33b33) | `` Force root sources like "./." into the Nix store ``           |
| [`5a16547d`](https://github.com/edolstra/flake-compat/commit/5a16547d46553d7bdd1dfc2cf418f5f7d236f6ad) | `` Prevent double copying and work around an apparent Nix bug `` |
=> chore(flake/flake-compat): `4f910c98` -> `0f9255e0`

flake.lock
| [`68f7d8c0`](https://github.com/nix-community/home-manager/commit/68f7d8c0fb0bfc67d1916dd7f06288424360d43a) | `` firefox: set ADD_DATE and LAST_MODIFIED of bookmarks to 1 `` |
=> chore(flake/home-manager): `8aef005d` -> `68f7d8c0`

flake.lock
| [`89c6109a`](https://github.com/NixOS/nixos-hardware/commit/89c6109adceb6fabf2ccda62ddfc4aa4fa19f25b) | `` star64: linux: 5.15.128 -> 5.15.131 `` |
=> chore(flake/nixos-hardware): `0ab3ee71` -> `89c6109a`

flake.lock
| [`6d05cccc`](https://github.com/NixOS/nixos-hardware/commit/6d05cccc80feaf93d5f3d6837f8c2db582b29cf8) | `` star64: set governor to schedutil `` |
=> chore(flake/nixos-hardware): `89c6109a` -> `6d05cccc`

flake.lock
| Commit                                                                                                       | Message                          |
| ------------------------------------------------------------------------------------------------------------ | -------------------------------- |
| [`1875015c`](https://github.com/cachix/pre-commit-hooks.nix/commit/1875015c254430daf78d24522f19bc957665b6ed) | `` Fix broken import (eclint) `` |
| [`13cee779`](https://github.com/cachix/pre-commit-hooks.nix/commit/13cee7793781f3137067c77b00aac7c9595fe7c5) | `` hooks: add psalm ``           |
| [`108539f9`](https://github.com/cachix/pre-commit-hooks.nix/commit/108539f9d8d3bde669bf1f8f5ad4f2c0aaab4ed1) | `` hooks: add phpstan ``         |
=> chore(flake/pre-commit-hooks): `033453f8` -> `b039621a`

flake.lock
| Commit                                                                                                       | Message                                  |
| ------------------------------------------------------------------------------------------------------------ | ---------------------------------------- |
| [`03843c0e`](https://github.com/cachix/pre-commit-hooks.nix/commit/03843c0e6e577e51e840f3e0475c1bb6c48aa559) | `` Add hook for mdl (Markdown linter) `` |
=> chore(flake/pre-commit-hooks): `b039621a` -> `66c352d3`

flake.lock
| [`f4ef5df9`](https://github.com/NixOS/nixos-hardware/commit/f4ef5df944429e2ce3308bdbe69da940fffc5942) | `` pine64-rockpro64: init ``                      |
| [`b31be8f1`](https://github.com/NixOS/nixos-hardware/commit/b31be8f11493e0f79a840370fd17153cd60b9009) | `` edit readme ``                                 |
| [`d79fe3a2`](https://github.com/NixOS/nixos-hardware/commit/d79fe3a25c2bf264ac37ef84fbf03a8d0641fca4) | `` add to flake ``                                |
| …
=> chore(flake/nixos-hardware): `6d05cccc` -> `f4ef5df9`

flake.lock
| [`79908fc2`](https://github.com/Mic92/nix-fast-build/commit/79908fc2a9768ac9b2ad14e8b94f37bb4ee3b71b) | `` don't propagated python when included in a devshell `` |
=> chore(flake/nix-fast-build): `9ebfd443` -> `79908fc2`

flake.lock
| [`141a0bd2`](https://github.com/NixOS/nixpkgs/commit/141a0bd2bd06e8f32b816d1f1109b5a6ea8f7f7e) | `` udiskie: install shell completions ``                                         |
| [`86aa82ce`](https://github.com/NixOS/nixpkgs/commit/86aa82cee24db88576d346d3e991844c17653ce8) | `` udiskie: 2.4.2 -> 2.5.0 ``                                                    |
| [`ad454fa3`](https://github.com/NixOS/nixpkgs/commit/ad454fa303d318d63 …
=> chore(flake/nixpkgs): `fdd898f8` -> `81e8f48e`

flake.lock
| [`bb2db418`](https://github.com/NixOS/nixos-hardware/commit/bb2db418b616fea536b1be7f6ee72fb45c11afe0) | `` chore: Add Dell XPS 15 9510 `` |
| [`455496f1`](https://github.com/NixOS/nixos-hardware/commit/455496f1b4a2318924326ba1cbde9b485a3dac57) | `` chore: Add DELL XPS 9510 ``    |
| [`93fcc5fb`](https://github.com/NixOS/nixos-hardware/commit/93fcc5fb824833e2c8fb03768d8ffb915024dc6b) | `` OLIMEX Teres-I: Init ``        |
=> chore(flake/nixos-hardware): `f4ef5df9` -> `bb2db418`

flake.lock
| [`44635279`](https://github.com/nix-community/home-manager/commit/44635279a0dfca43d2b980422f295def1aca0c08) | `` bat: allow setting themes/syntaxes without IFD `` |
=> chore(flake/home-manager): `68f7d8c0` -> `44635279`

flake.lock
| [`ed0770e9`](https://github.com/nix-community/home-manager/commit/ed0770e96225f998ea128549ad446d9b1568cb2c) | `` hyprland: allow customizing systemd `` |
=> chore(flake/home-manager): `44635279` -> `ed0770e9`

flake.lock
| [`b2a2133c`](https://github.com/nix-community/home-manager/commit/b2a2133c9a0b0aa4d06d72b5891275f263ee08df) | `` flake: fix nixpkgs `config` ``                   |
| [`31a27e48`](https://github.com/nix-community/home-manager/commit/31a27e48062742241ab06ccdbed189f28040cdaf) | `` fish: query pname and version for completions `` |
=> chore(flake/home-manager): `ed0770e9` -> `b2a2133c`

flake.lock
| Commit                                                                                         | Message                                                                                          |
| ---------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------------------ |
| [`e3d54cc7`](https://github.com/NixOS/nixpkgs/commit/e3d54cc7a272755d66814da329cdccf8725bd31f) | `` lefthook: 1.4.8 -> 1.5.1 ``                                                                   |
| [`42bea74b`](https://github.com/NixOS/nixpkgs/commit/42bea74b9f6ebd13c8b8d8512f3bd479c67b8910) | `` python311Packages.casbin: 1.31.0 -> 1.31.2 ``                                                 |
| …
=> chore(flake/nixpkgs): `81e8f48e` -> `87828a0e`
