lovesegfault/nix-config

flake.lock

| [`8cb486fb`](https://github.com/nix-community/nix-index-database/commit/8cb486fb2430d972188bd04ed2c29f7acbb9f472) | `` flake.lock: Update `` |

chore(flake/nix-index-database): `031d4b22` -> `8cb486fb`

---

flake.lock

| [`2902dc66`](https://github.com/nix-community/nix-index-database/commit/2902dc66f64f733bfb45754e984e958e9fe7faf9) | `` update packages.nix to release 2023-10-08-034126 `` |

chore(flake/nix-index-database): `8cb486fb` -> `2902dc66`

---

flake.lock

| [`3c1d8758`](https://github.com/nix-community/home-manager/commit/3c1d8758ac3f55ab96dcaf4d271c39da4b6e836d) | `` flake.lock: Update `` |

chore(flake/home-manager): `b2a2133c` -> `3c1d8758`

---

flake.lock

| Commit                                                                                         | Message                                         |
| ---------------------------------------------------------------------------------------------- | ----------------------------------------------- |
| [`b5fa96a9`](https://github.com/ryantm/agenix/commit/b5fa96a90e07cc099cc5247540449263caeedb16) | `` feat: remove empty newlines from jq query `` |

chore(flake/agenix): `1f677b3e` -> `e2f33927`

---

flake.lock

| Commit                                                                                         | Message                                                  |
| ---------------------------------------------------------------------------------------------- | -------------------------------------------------------- |
| [`dbc533dd`](https://github.com/ryantm/agenix/commit/dbc533ddc2568d5eaac1a39b9e638275aff3841c) | `` Revert "feat: remove empty newlines from jq query" `` |

chore(flake/agenix): `e2f33927` -> `daf42cb3`

---

flake.lock

| Commit                                                                                                       | Message                                         |
| ------------------------------------------------------------------------------------------------------------ | ----------------------------------------------- |
| [`67d6c44f`](https://github.com/cachix/pre-commit-hooks.nix/commit/67d6c44fe1f2c092417bd8395fe30420fa55ffde) | `` Switch type to one supported by precommit `` |

chore(flake/pre-commit-hooks): `8edf336c` -> `42e1b609`

---

flake.lock

| [`6dfbdc97`](https://github.com/nix-community/home-manager/commit/6dfbdc977e059f30376e23f70f67d9726d5c91b8) | `` unison: add package option `` |

chore(flake/home-manager): `3c1d8758` -> `6dfbdc97`

---

flake.lock

| [`6ea13c2d`](https://github.com/NixOS/nixos-hardware/commit/6ea13c2df412306793311f8b8c58f5cd9127fb55) | `` starfive visionfive2: update u-boot to SDK version v3.7.5 `` |

chore(flake/nixos-hardware): `bb2db418` -> `6ea13c2d`

---

flake.lock

| [`c2bbfcfc`](https://github.com/NixOS/nixos-hardware/commit/c2bbfcfc3d12351919f8df7c7d6528f41751d0a3) | `` fix compileDTS overlay for raspberry-pi (#754) `` |

chore(flake/nixos-hardware): `6ea13c2d` -> `c2bbfcfc`

---

flake.lock

| [`1f0dbe5f`](https://github.com/NixOS/nixpkgs/commit/1f0dbe5f10c3a15abbddcb0ea3358d4280f77af2) | `` fwupd: drop removed dell option ``                                        |
| [`41acc257`](https://github.com/NixOS/nixpkgs/commit/41acc25766fbc611cd10cb043bc7cab91d2fd088) | `` by-name: make the way of adding packages clearer ``                       |
| [`3e4c990c`](https://github.com/NixOS/nixpkgs/commit/3e4c990c91e212185da0868655fab15b6 …

chore(flake/nixpkgs): `87828a0e` -> `f99e5f03`

---

flake.lock

| Commit                                                                                                | Message                                                               |
| ----------------------------------------------------------------------------------------------------- | --------------------------------------------------------------------- |
| [`d6b554a8`](https://github.com/NixOS/nixos-hardware/commit/d6b554a85caac840430a822aae963c811e9c7e26) | `` pine64-pinebook-pro: remove superfluous ap6256-firmware package `` |
| [`922926aa`](https://github.com/NixOS/nixos-hardware/commit/922926aa1f58db7897c4cea756978d418b281545) | `` pine64-pinebook-pro: add initrd modules for boot-from-NVMe ``      |
| [`a6eecb4d`](https://github.com/NixOS/nixos-hardware/commit/a6eecb4d851240d7bc6622449c …

chore(flake/nixos-hardware): `c2bbfcfc` -> `d6b554a8`

---

flake.lock

| [`feceaa9d`](https://github.com/danth/stylix/commit/feceaa9d81725c0ca28ab46326b6dd1310a10dea) | `` Embed Xresources template to avoid IFD (#168) `` |

chore(flake/stylix): `eb007b79` -> `feceaa9d`

---

flake.lock

| [`fb6af288`](https://github.com/NixOS/nixos-hardware/commit/fb6af288f6cf0f00d3af60cf9d5110433b954565) | `` fix(common/gpu/amd): use new rocmPackages `` |
| [`3d4a18fa`](https://github.com/NixOS/nixos-hardware/commit/3d4a18fac8850697714bfc2307211268beb63715) | `` Microchip Icicle Kit BSP update ``           |

chore(flake/nixos-hardware): `d6b554a8` -> `fb6af288`

---

flake.lock

| [`17cadf65`](https://github.com/nix-community/lanzaboote/commit/17cadf6598c499bbbc839383a46eb8bf0c8c078a) | `` stub: update to latest uefi crates `` |

chore(flake/lanzaboote): `ac43ac30` -> `c865873f`

---

flake.lock

| [`d0a3fe03`](https://github.com/Mic92/nix-fast-build/commit/d0a3fe039c5ce3140b96473cab44b7a8bd0d34f5) | `` document how to evaluate single systems only `` |

chore(flake/nix-fast-build): `79908fc2` -> `d0a3fe03`

---

flake.lock

| [`ccd7abe1`](https://github.com/NixOS/nixpkgs/commit/ccd7abe1baa9784eb06fc1c129c869e20105b49b) | `` multimon-ng: 1.2.0 -> 1.3.0 ``                                          |
| [`4687df88`](https://github.com/NixOS/nixpkgs/commit/4687df882464f1f1946bd649e25c8ba16f63044c) | `` gerrit: use hash instead of sha256 ``                                   |
| [`5dcafc36`](https://github.com/NixOS/nixpkgs/commit/5dcafc36852cd8d96127f5cbfe42918bf262214e) …

chore(flake/nixpkgs): `f99e5f03` -> `5e4c2ada`

---

flake.lock

| [`0f317c2e`](https://github.com/nix-community/impermanence/commit/0f317c2e9e56550ce12323eb39302d251618f5b5) | `` Fix build with `documentation.nixos.includeAllModules = true;` `` |

chore(flake/impermanence): `e9643d08` -> `0f317c2e`

---

flake.lock

| Commit                                                                                                    | Message                                                              |
| --------------------------------------------------------------------------------------------------------- | -------------------------------------------------------------------- |
| [`16c67767`](https://github.com/nix-community/lanzaboote/commit/16c67767639ccc89ed48527e41d899a4cf376917) | `` Fix build with `documentation.nixos.includeAllModules = true;` `` |

chore(flake/lanzaboote): `c865873f` -> `62ffd894`

---

flake.lock

| [`a4a72ffd`](https://github.com/nix-community/home-manager/commit/a4a72ffd76f2c974601e7adff356e5c277e08077) | `` flake.lock: Update `` |

chore(flake/home-manager): `6bba6478` -> `a4a72ffd`

---

flake.lock

| [`d4a5076e`](https://github.com/nix-community/home-manager/commit/d4a5076ea8c2c063c45e0165f9f75f69ef583e20) | `` borgmatic: improve support for version 1.8.0 `` |
| [`9a2ce656`](https://github.com/nix-community/home-manager/commit/9a2ce6569752bb00b86c075ade7ffd47242f3827) | `` zsh: generalize zsh-history-substring-search `` |

chore(flake/home-manager): `a4a72ffd` -> `d4a5076e`

---

flake.lock

| [`a132935e`](https://github.com/nix-community/nix-index-database/commit/a132935e28f27a4aad7a7a2535a5bf45d711ef7b) | `` flake.lock: Update `` |

chore(flake/nix-index-database): `2902dc66` -> `a132935e`

---

flake.lock

| [`29977d07`](https://github.com/nix-community/nix-index-database/commit/29977d0796c058bbcfb2df5b18eb5badf1711007) | `` update packages.nix to release 2023-10-15-033241 `` |

chore(flake/nix-index-database): `a132935e` -> `29977d07`

---

flake.lock

| [`3b67ae3f`](https://github.com/nix-community/home-manager/commit/3b67ae3f665379c06999641f99d94dba75b53876) | `` services.cliphist: add module (#4445) `` |

chore(flake/home-manager): `d4a5076e` -> `3b67ae3f`

---

flake.lock

| [`78125bc6`](https://github.com/nix-community/home-manager/commit/78125bc681d12364cb65524eaa887354134053d0) | `` firefox: add test for duplicate profile id assertion `` |
| [`f033205b`](https://github.com/nix-community/home-manager/commit/f033205b251439bda16fd9071b163b6eacb4fdf6) | `` firefox: extract an overlay common to all tests ``      |

chore(flake/home-manager): `3b67ae3f` -> `78125bc6`

---

flake.lock

| Commit                                                                                                    | Message                                                   |
| --------------------------------------------------------------------------------------------------------- | --------------------------------------------------------- |
| [`bb5b2de5`](https://github.com/nix-community/lanzaboote/commit/bb5b2de5450ab6a725f35ab1512b59cbbcaf7830) | `` stub: pin goblin (again) ``                            |
| [`ace18ed4`](https://github.com/nix-community/lanzaboote/commit/ace18ed4bde61df6ab0d5fec2492f5170e9d4f39) | `` renovate: ignore goblin updates ``                     |
| [`eabbae0e`](https://github.com/nix-community/lanzaboote/commit/eabbae0e0cc4949c7da0e83d4052c3e4abd8b835) | `` …

chore(flake/lanzaboote): `82530e53` -> `778e2173`

---

flake.lock

| [`f6bb5c29`](https://github.com/nix-community/home-manager/commit/f6bb5c297372719a6ea1c369b2b1a1aa10580452) | `` docs: add stateVersion to the NixOS/nix-darwin example `` |

chore(flake/home-manager): `78125bc6` -> `f6bb5c29`

---

flake.lock

| [`b25161c6`](https://github.com/nix-community/home-manager/commit/b25161c6a2c3b7cabb9cfdc70c35007c8ecb7241) | `` darkman: add module ``             |
| [`132f9851`](https://github.com/nix-community/home-manager/commit/132f9851858986d78db0b08157256384bbc5738c) | `` home-manager: add .editorconfig `` |

chore(flake/home-manager): `f6bb5c29` -> `b25161c6`

---

flake.lock

| [`7a46e6cb`](https://github.com/nix-community/home-manager/commit/7a46e6cb3ca02a478bdafc53c0ac89da6efc050c) | `` im/fcitx5: fix missing plugins on Qt6 (#4468) `` |

chore(flake/home-manager): `b25161c6` -> `7a46e6cb`

---

flake.lock

| [`3433206e`](https://github.com/nix-community/home-manager/commit/3433206e51766b4164dad368a81325efbf343fbe) | `` qutebrowser: add greasemonkey userscript option ``       |
| [`54c1ca74`](https://github.com/nix-community/home-manager/commit/54c1ca74d949aa900f9723cef8408ddc32352a05) | `` flake.lock: Update ``                                    |
| [`84fa81c7`](https://github.com/nix-community/home-manager/commit/84fa81c7acb018c3c5a504dcefbc28a182c9 …

chore(flake/home-manager): `b3acf1dc` -> `3433206e`

---

flake.lock

| [`c5c1ea85`](https://github.com/nix-community/home-manager/commit/c5c1ea85181d2bb44e46e8a944a8a3f56ad88f19) | `` Translate using Weblate (Portuguese) `` |
| [`a969307e`](https://github.com/nix-community/home-manager/commit/a969307eb96651c73cacbc38157144cd023eb78c) | `` Translate using Weblate (Lithuanian) `` |
| [`92bf9c25`](https://github.com/nix-community/home-manager/commit/92bf9c2585a1a3105d34becb2ed41ae5022d292c) | `` Translate using Weblate (Turkish) ``    |

chore(flake/home-manager): `3433206e` -> `c5c1ea85`

---

flake.lock

| [`b2f73724`](https://github.com/danth/stylix/commit/b2f73724d11868d020207fb87fb2d9c3ae96976d) | `` Add font support for Xfce4 (#171) ``                     |
| [`4c1acb81`](https://github.com/danth/stylix/commit/4c1acb81642fc1721a0059232ebc41d254b5149b) | `` Zathura: remove default recolor configurations (#174) `` |

chore(flake/stylix): `feceaa9d` -> `b2f73724`

---

flake.lock

| Commit                                                                                           | Message                                                              |
| ------------------------------------------------------------------------------------------------ | -------------------------------------------------------------------- |
| [`e621b5ae`](https://github.com/LnL7/nix-darwin/commit/e621b5aea75810e7228a9ebc93f82b8b41008e7e) | `` Provide 'supportedFeatures' option to the linux builder module `` |

chore(flake/darwin): `8b6ea26d` -> `19f75c2b`

---

flake.lock

| [`72d53d51`](https://github.com/NixOS/nixos-hardware/commit/72d53d51704295f1645d20384cd13aecc182f624) | `` starfive visionfive2: combine 8gb dtb overlays ``                           |
| [`32264b21`](https://github.com/NixOS/nixos-hardware/commit/32264b21bb23fbc00672b3ed6fcfaa5489d03991) | `` purism/librem5r4: linuxPackages_librem5: 6.5.4-librem5 -> 6.5.6-librem5 ``  |
| …

chore(flake/nixos-hardware): `fb6af288` -> `72d53d51`

---

flake.lock

| [`853c81ee`](https://github.com/nix-community/lanzaboote/commit/853c81eef24c747c8f1c680023d63a0b6842f522) | `` chore(deps): lock file maintenance ``          |
| [`65003165`](https://github.com/nix-community/lanzaboote/commit/65003165c81b74367787be1408778ad4bc46e14b) | `` tests: downgrade from edk2 202308 to 202305 `` |
| [`0c7ca2b1`](https://github.com/nix-community/lanzaboote/commit/0c7ca2b1801fc72e4de8f64adba60feb54a489d9) | `` nix: remove unused follows `` …

chore(flake/lanzaboote): `778e2173` -> `0c38cbfa`

---

flake.lock

| Commit                                                                                                       | Message                                |
| ------------------------------------------------------------------------------------------------------------ | -------------------------------------- |
| [`3bda907f`](https://github.com/cachix/pre-commit-hooks.nix/commit/3bda907fc6d113dab04cf973a6135158e83b09e6) | `` flake-parts: update the template `` |

chore(flake/pre-commit-hooks): `42e1b609` -> `8cc349bf`

---

flake.lock

| [`ae631b0b`](https://github.com/nix-community/home-manager/commit/ae631b0b20f06f7d239d160723d228891ddb2fe0) | `` docs: fix option name `` |

chore(flake/home-manager): `c5c1ea85` -> `ae631b0b`

---

flake.lock

| Commit                                                                                                    | Message                                                    |
| --------------------------------------------------------------------------------------------------------- | ---------------------------------------------------------- |
| [`ec05d707`](https://github.com/nix-community/lanzaboote/commit/ec05d707f3d1a3e1a1540b8dab8abfeb171f25c8) | `` tool: always include version in PRETTY_NAME ``          |
| [`3da3049b`](https://github.com/nix-community/lanzaboote/commit/3da3049bef08f0d3e48fbbe611f61b358ef04c31) | `` tool: remove unhelpful wrappers and lightly refactor `` |

chore(flake/lanzaboote): `0c38cbfa` -> `4366cd1b`

---

flake.lock

| [`4c0bcf5d`](https://github.com/nix-community/home-manager/commit/4c0bcf5dff03c48c4b047c9ab304c74b2bcdcdeb) | `` exa: add aliases to nushell `` |

chore(flake/home-manager): `ae631b0b` -> `4c0bcf5d`

---

flake.lock

| [`81ab1462`](https://github.com/nix-community/home-manager/commit/81ab14626273ca38cba947d9a989c9d72b5e7593) | `` readme: major cleanup `` |

chore(flake/home-manager): `4c0bcf5d` -> `81ab1462`

---

flake.lock

| [`d1d9ae91`](https://github.com/nix-community/nix-index-database/commit/d1d9ae914431177d3898605aabbaad0d37803649) | `` flake.lock: Update `` |

chore(flake/nix-index-database): `29977d07` -> `d1d9ae91`

---

flake.lock

| [`5a200628`](https://github.com/nix-community/nix-index-database/commit/5a2006282caaf32663cdcd582c5b18809c7d7d8d) | `` update packages.nix to release 2023-10-22-034115 `` |

chore(flake/nix-index-database): `d1d9ae91` -> `5a200628`

---

flake.lock

| [`219d268a`](https://github.com/nix-community/home-manager/commit/219d268a69512ff520fe8da1739ac22d95d52355) | `` aerc: fix config paths on darwin `` |

chore(flake/home-manager): `81ab1462` -> `219d268a`

---

flake.lock

| [`9e88d05a`](https://github.com/danth/stylix/commit/9e88d05a851d4919ad5c729fdf0993817efacb02) | `` Apply dark mode to Qutebrowser (#175) ``   |
| [`71c2eb22`](https://github.com/danth/stylix/commit/71c2eb2214a90a3a75efa78b7176f614a9a7eb4c) | `` Fix cursor foreground in WezTerm (#177) `` |

chore(flake/stylix): `b2f73724` -> `9e88d05a`

---

flake.lock

| Commit                                                                                         | Message                                                                                   |
| ---------------------------------------------------------------------------------------------- | ----------------------------------------------------------------------------------------- |
| [`c9368669`](https://github.com/NixOS/nixpkgs/commit/c93686698322845b8057ed832460fd69a11b4cc7) | `` shopware-cli: 0.3.5 -> 0.3.6 ``                                                        |
| [`c22fed22`](https://github.com/NixOS/nixpkgs/commit/c22fed2281160f94c143eb26f0aeba238a6daa0d) | `` nixos/doc/manual/development/writing-documentation.xml: fix build command (#262044) `` |
| …

chore(flake/nixpkgs): `5e4c2ada` -> `7c9cc5a6`

---

flake.lock

| Commit                                                                                                | Message                                                                            |
| ----------------------------------------------------------------------------------------------------- | ---------------------------------------------------------------------------------- |
| [`80d98a7d`](https://github.com/NixOS/nixos-hardware/commit/80d98a7d55c6e27954a166cb583a41325e9512d7) | `` feat(tuxedo/pulse/15/gen2): use default 'hardware.amdgpu.loadInInitrd' ``       |
| [`cdf84962`](https://github.com/NixOS/nixos-hardware/commit/cdf849625bd019a433d8665ebcf9895c8bd1aceb) | `` refactor(tuxedo/pulse/15/gen2): simplify device expression ``                   |
| …

chore(flake/nixos-hardware): `72d53d51` -> `80d98a7d`

---

flake.lock

| Commit                                                                                        | Message                                               |
| --------------------------------------------------------------------------------------------- | ----------------------------------------------------- |
| [`91e46dec`](https://github.com/danth/stylix/commit/91e46dec675ec37fd3f9745754d10bb7e392db98) | `` Rofi: remove subjective non-color values (#179) `` |

chore(flake/stylix): `9e88d05a` -> `91e46dec`

---

flake.lock

| [`56386ae1`](https://github.com/nix-community/lanzaboote/commit/56386ae1c374deb728679c69e036af4e2b055aad) | `` fixtures: add snakeoil dbx pem ``     |
| [`e0511f43`](https://github.com/nix-community/lanzaboote/commit/e0511f43e79b93fd6ad98452c9b8c2265d4f49f9) | `` chore(deps): lock file maintenance `` |

chore(flake/lanzaboote): `4366cd1b` -> `bb380e19`

---

flake.lock

| [`6045b68e`](https://github.com/nix-community/home-manager/commit/6045b68ee725167ed0487f0fb88123202ba61923) | `` cava: add module `` |

chore(flake/home-manager): `f540f30f` -> `6045b68e`

---

flake.lock

| Commit                                                                                                       | Message                                           |
| ------------------------------------------------------------------------------------------------------------ | ------------------------------------------------- |
| [`8364aa05`](https://github.com/cachix/pre-commit-hooks.nix/commit/8364aa05c9e92d758dca0bd8a03c9fa400c41fd9) | `` Add optional settings to `latexindent` hook `` |

chore(flake/pre-commit-hooks): `8cc349bf` -> `bd38df3d`

---

flake.lock

| [`14b54157`](https://github.com/nix-community/home-manager/commit/14b54157201fd574b0fa1b3ce7394c9d3a87fbc1) | `` sxhkd: set scope OOMPolicy to continue `` |

chore(flake/home-manager): `6045b68e` -> `14b54157`

---

flake.lock

| [`b0741011`](https://github.com/Mic92/nix-fast-build/commit/b07410115ee89ee2c3a913f69c9bf8418562576f) | `` flake.lock: Update ``                           |
| [`7d1faaae`](https://github.com/Mic92/nix-fast-build/commit/7d1faaae0f9da1344a0a631fe066cccc4dd95180) | `` test for eval errors ``                         |
| [`c17a4127`](https://github.com/Mic92/nix-fast-build/commit/c17a41275e96aa619e98fd3ce6a7135c9e3bf15c) | `` document how to evaluate single systems only `` |

chore(flake/nix-fast-build): `d0a3fe03` -> `e76d62f7`

---

flake.lock

| [`160eb3d9`](https://github.com/LnL7/nix-darwin/commit/160eb3d99de1dd8e4d0542ab02a6831aa31c7204) | `` linux-builder: avoid /tmp for certs `` |

chore(flake/darwin): `19f75c2b` -> `afe83cbc`

---

flake.lock

| [`9954349d`](https://github.com/NixOS/nixpkgs/commit/9954349db2fa51d060843af9c92d77f55b158989) | `` breakpad: unstable-3b3469e -> 2023.01.27 ``                                              |
| [`8173b255`](https://github.com/NixOS/nixpkgs/commit/8173b255dc1ba7b24aa6d9fa80d3a2a3f1c1747e) | `` python3Packages.tblite: fix toml-f 0.4 compatibility ``                                  |
| …

chore(flake/nixpkgs): `8efd5d1e` -> `63678e9f`

---

flake.lock

| [`f92a54fe`](https://github.com/nix-community/home-manager/commit/f92a54fef4eacdbe86b0a2054054dd58b0e2a2a4) | `` wezterm: remove automatic config reload call `` |

chore(flake/home-manager): `1369d2ce` -> `f92a54fe`

---

flake.lock

| [`7a7987c7`](https://github.com/danth/stylix/commit/7a7987c7828050ef9a8ca6af07ca98485053776b) | `` Fix group variable changes in Hyprland module (#169) `` |

chore(flake/stylix): `91e46dec` -> `7a7987c7`

---

flake.lock

| [`1f0981f5`](https://github.com/nix-community/nix-index-database/commit/1f0981f5baeb78e3c89a8980ff1a39f06876fa8c) | `` update packages.nix to release 2023-10-29-033859 `` |
| [`ef1a36f6`](https://github.com/nix-community/nix-index-database/commit/ef1a36f692d7324a9c3648ce616111ddcb5d2373) | `` flake.lock: Update ``                               |

chore(flake/nix-index-database): `5a200628` -> `1f0981f5`

---

flake.lock

| Commit                                                                                                   | Message                                                                    |
| -------------------------------------------------------------------------------------------------------- | -------------------------------------------------------------------------- |
| [`e21f5944`](https://github.com/hercules-ci/flake-parts/commit/e21f594423a34944b2eece27e62f1fcca0c1c90a) | `` Fix error location ``                                                   |
| [`c8c8e566`](https://github.com/hercules-ci/flake-parts/commit/c8c8e5661e2b93f2459b0ed6da1cbe31c7dba347) | `` Remove errorLocation from the tests ``                                  |
| …

chore(flake/flake-parts): `c9afaba3` -> `f76e870d`

---

flake.lock

| [`b7f68a50`](https://github.com/nix-community/lanzaboote/commit/b7f68a50e6902f28c07a9f8d41df76f4c0a9315b) | `` linux_loader: improve code quality `` |

chore(flake/lanzaboote): `bb380e19` -> `a5e89456`

---

flake.lock

| [`03c2f52e`](https://github.com/nix-community/lanzaboote/commit/03c2f52ee9409811cfe0ad6f2b4deb13814e8704) | `` fix(deps): update all dependencies `` |

chore(flake/lanzaboote): `a5e89456` -> `1e974f66`

---

flake.lock

| Commit                                                                                                    | Message                                                  |
| --------------------------------------------------------------------------------------------------------- | -------------------------------------------------------- |
| [`3cb657f5`](https://github.com/nix-community/lanzaboote/commit/3cb657f5c3e6f8e009e5bf2854d60dd0360c4889) | `` tool: silence resolver version warning ``             |
| [`87d2087a`](https://github.com/nix-community/lanzaboote/commit/87d2087a7a5dfacb37579d2b4060c7334804d6f8) | `` tool: drop unused dependencies via machete ``         |
| [`1e5145a0`](https://github.com/nix-community/lanzaboote/commit/1e5145a0fad64518f1d3982a43e237e7ce34d6c3) | `` nix: trim …

chore(flake/lanzaboote): `1e974f66` -> `9c8d7c56`

---

flake.lock

| [`2ed44821`](https://github.com/nix-community/lanzaboote/commit/2ed44821338885c7628a1c63cb443bb74c7296e5) | `` chore(deps): lock file maintenance `` |

chore(flake/lanzaboote): `9c8d7c56` -> `8edc9ef7`

---

flake.lock

| [`18594916`](https://github.com/nix-community/lanzaboote/commit/1859491609d879b9403273684fb0aa41e980f283) | `` tests: add 5 minutes default timeout `` |

chore(flake/lanzaboote): `8edc9ef7` -> `781303ad`

---

flake.lock

| [`8e5416b4`](https://github.com/nix-community/home-manager/commit/8e5416b478e465985eec274bc3a018024435c106) | `` services.swayidle: change target to generic session (#3913) `` |

chore(flake/home-manager): `f92a54fe` -> `8e5416b4`

---

flake.lock

| [`9bc7d84b`](https://github.com/nix-community/home-manager/commit/9bc7d84b8213255ecd5eb6299afdb77c36ece71d) | `` zsh: made ZDOTDIR export to the shell (#4619) `` |

chore(flake/home-manager): `8e5416b4` -> `9bc7d84b`

---

flake.lock

| [`f40197be`](https://github.com/NixOS/nixos-hardware/commit/f40197be9ad0142b8612c4e47366945667ae4ef4) | `` pine64-rockpro64: add fancontrol `` |

chore(flake/nixos-hardware): `80d98a7d` -> `3162c7c1`

---

flake.lock

| Commit                                                                                                       | Message                                           |
| ------------------------------------------------------------------------------------------------------------ | ------------------------------------------------- |
| [`3db0e345`](https://github.com/cachix/pre-commit-hooks.nix/commit/3db0e3457be750234a1c6cb97e5ba4e63c592c26) | `` Specify files attribute for Elixir programs `` |

chore(flake/pre-commit-hooks): `bd38df3d` -> `dec10399`

---

flake.lock

| [`11d50c5d`](https://github.com/NixOS/nixos-hardware/commit/11d50c5d52472ed40d3cb109daad03c836d2b328) | `` raspberrypi."4": add DigiAMP+ overlay ``      |
| [`71e0de71`](https://github.com/NixOS/nixos-hardware/commit/71e0de7199f4117140ee6e9c699a0f160e9301d6) | `` feat(asus/rog-strix/g513im): added profile `` |

chore(flake/nixos-hardware): `3162c7c1` -> `11d50c5d`

---

flake.lock

| [`fc2a8842`](https://github.com/nix-community/home-manager/commit/fc2a8842ea5106640eb89ec522dde9120df82d8a) | `` k9s: add hotkey option (#4617) `` |

chore(flake/home-manager): `9bc7d84b` -> `fc2a8842`

---

flake.lock

| [`48b0a302`](https://github.com/nix-community/home-manager/commit/48b0a30202516e25d9885525fbb200a045f23f26) | `` granted: add module ``                            |
| [`a4218048`](https://github.com/nix-community/home-manager/commit/a421804890cd0581af03534886abae32a213c085) | `` borgmatic: preparing upcoming borgmatic change `` |

chore(flake/home-manager): `fc2a8842` -> `48b0a302`

---

flake.lock

| [`1ff0e1be`](https://github.com/Mic92/nix-fast-build/commit/1ff0e1beb6ff70419a1269248325417eaae294a9) | `` use nix bundled with nix-eval-jobs `` |
| [`013ccd65`](https://github.com/Mic92/nix-fast-build/commit/013ccd659ee944fa0be8e9324548958b8caa8616) | `` flake.lock: Update ``                 |

chore(flake/nix-fast-build): `e76d62f7` -> `1ff0e1be`

---

flake.lock

| Commit                                                                                                   | Message                  |
| -------------------------------------------------------------------------------------------------------- | ------------------------ |
| [`216e40a3`](https://github.com/hercules-ci/flake-parts/commit/216e40a3f8c92a62178c13f01631dadb202dcf16) | `` flake.lock: Update `` |

chore(flake/flake-parts): `f76e870d` -> `8c9fa254`

---

flake.lock

| Commit                                                                                              | Message                                                                                  |
| --------------------------------------------------------------------------------------------------- | ---------------------------------------------------------------------------------------- |
| [`50d640f4`](https://github.com/serokell/deploy-rs/commit/50d640f4032c32d5bddab31af493670ba1773518) | `` fixup! [Chore] Make activation wait timeout configurable ``                           |
| [`aeeee3c1`](https://github.com/serokell/deploy-rs/commit/aeeee3c1e3e9bfc38462cb315b6e19ee9fe6db70) | `` [Chore] Make activation wait timeout configurable ``                                  |
| …

chore(flake/deploy-rs): `e3f41832` -> `660180bb`

---

flake.lock

| [`831b4fa3`](https://github.com/nix-community/home-manager/commit/831b4fa31749208e576050c563e9773aafd04941) | `` clipmenu: set Environment to a list `` |

chore(flake/home-manager): `48b0a302` -> `831b4fa3`

---

flake.lock

| [`8765d4e3`](https://github.com/nix-community/home-manager/commit/8765d4e38aa0be53cdeee26f7386173e6c65618d) | `` thefuck: add fish integration (#4535) `` |

chore(flake/home-manager): `831b4fa3` -> `8765d4e3`

---

flake.lock

| [`87f84033`](https://github.com/NixOS/nixos-hardware/commit/87f8403371fa74d9ad21ed677403cc235f37b96c) | `` chore: Add OPENGL settings ``            |
| [`ce606807`](https://github.com/NixOS/nixos-hardware/commit/ce6068070b5fbbbdfdacfc38dff88b5ec6af87ec) | `` chore: Tunning WiFi ``                   |
| [`097764c8`](https://github.com/NixOS/nixos-hardware/commit/097764c8930ad8b0632f6eb9d96eb9c9b65a62f5) | `` Add HP Elitebook 845 g7 configuration `` |

chore(flake/nixos-hardware): `11d50c5d` -> `87f84033`

---

flake.lock

| [`1f55deaf`](https://github.com/nix-community/nix-index-database/commit/1f55deafa155d9541fd134bb74521d7390088de0) | `` flake.lock: Update `` |

chore(flake/nix-index-database): `1f0981f5` -> `1f55deaf`

---

flake.lock

| [`5388a400`](https://github.com/nix-community/nix-index-database/commit/5388a4002179d6778d212dc2fdcc7ac3fdbd5b65) | `` update packages.nix to release 2023-11-05-035517 `` |

chore(flake/nix-index-database): `1f55deaf` -> `5388a400`

---

flake.lock

| [`0c53ac44`](https://github.com/NixOS/nixos-hardware/commit/0c53ac44db615b86642aa0965e23e850b1042b0c) | `` star64: linux: force disable DRM_FBDEV_EMULATION `` |

chore(flake/nixos-hardware): `87f84033` -> `627bc9b8`

---

flake.lock

| Commit                                                                                                       | Message                                 |
| ------------------------------------------------------------------------------------------------------------ | --------------------------------------- |
| [`fe1e555f`](https://github.com/cachix/pre-commit-hooks.nix/commit/fe1e555fc51f01568212180d519f36c569254ef0) | `` Add git-annex hook ``                |
| [`841208dd`](https://github.com/cachix/pre-commit-hooks.nix/commit/841208dd849019fc3d9d0c8cc0e892e2cf69d483) | `` Add .editorconfig with used style `` |

chore(flake/pre-commit-hooks): `dec10399` -> `ea758da1`

---

flake.lock

| [`c067d57f`](https://github.com/nix-community/home-manager/commit/c067d57fc4552835987fd7611c3a6741ee32ebd5) | `` swayr: add module (#4322) `` |

chore(flake/home-manager): `8765d4e3` -> `c067d57f`

---

flake.lock

| [`76e7c05f`](https://github.com/nix-community/home-manager/commit/76e7c05f7d3d5ffac219450af824043da52af1cc) | `` home-cursor: fix typo in XDG data directory link `` |

chore(flake/home-manager): `c067d57f` -> `76e7c05f`

---

flake.lock

| [`6a844446`](https://github.com/nix-community/home-manager/commit/6a8444467c83c961e2f5ff64fb4f422e303c98d3) | `` systemd: add settings option (#4276) `` |

chore(flake/home-manager): `76e7c05f` -> `6a844446`

---

flake.lock

| [`ceb19c07`](https://github.com/nix-community/lanzaboote/commit/ceb19c0732136bd12d65f8561d45ed93cd89f398) | `` chore(deps): lock file maintenance `` |

chore(flake/lanzaboote): `781303ad` -> `241cedde`

---

flake.lock

| Commit                                                                                           | Message                                                |
| ------------------------------------------------------------------------------------------------ | ------------------------------------------------------ |
| [`70af8083`](https://github.com/LnL7/nix-darwin/commit/70af808347fbfd866e04da5fe2856cb1ae75eaa4) | `` linux-builder: change from `modules` to `config` `` |

chore(flake/darwin): `afe83cbc` -> `eb2b9b64`

---

flake.lock

| [`482a10db`](https://github.com/Mic92/nix-fast-build/commit/482a10dbd20a3134b01c439973ed00ffcc8eafd1) | `` --no-nom: fix help text `` |

chore(flake/nix-fast-build): `1ff0e1be` -> `482a10db`

---

flake.lock

| Commit                                                                                                    | Message                                                  |
| --------------------------------------------------------------------------------------------------------- | -------------------------------------------------------- |
| [`dd729cda`](https://github.com/nix-community/lanzaboote/commit/dd729cdaeb7d9335f7b7ac48be02df0c24293f02) | `` fix(deps): update rust crate serde_json to 1.0.108 `` |

chore(flake/lanzaboote): `241cedde` -> `bc0fd4e1`

---

flake.lock

| [`77c76498`](https://github.com/Mic92/nix-fast-build/commit/77c764981a9738aadb55b80e3e0891e6f2572477) | `` add no-link, out-link option `` |

chore(flake/nix-fast-build): `482a10db` -> `77c76498`

---

flake.lock

| [`5c6f7fd7`](https://github.com/danth/stylix/commit/5c6f7fd709be441505998fc51a25b645a44d359e) | `` Apply cursor theme to GDM :sparkles: `` |

chore(flake/stylix): `07795247` -> `5c6f7fd7`

---

flake.lock

| [`4fa7b5cd`](https://github.com/LnL7/nix-darwin/commit/4fa7b5cdd14a0fee6edc8c8924e57422b0dcc9ef) | `` Add security.pki.installCACerts config ``             |
| [`a4b4cf70`](https://github.com/LnL7/nix-darwin/commit/a4b4cf70dcf93353ff49a227a012b62cdc9629f8) | `` Update pkgs/nix-tools/darwin-rebuild.sh ``            |
| [`26a59d50`](https://github.com/LnL7/nix-darwin/commit/26a59d504b69448c1a7f1527ffc3f5e4999821fb) | `` fix(#798): darwin-rebuild support for Cyberark EPM `` |

chore(flake/darwin): `eb2b9b64` -> `0f1ad801`

---

flake.lock

| Commit                                                                                                | Message                                                                          |
| ----------------------------------------------------------------------------------------------------- | -------------------------------------------------------------------------------- |
| [`b689465d`](https://github.com/NixOS/nixos-hardware/commit/b689465d0c5d88e158e7d76094fca08cc0223aad) | `` Add note to mark change as temporary ``                                       |
| [`55b4caf9`](https://github.com/NixOS/nixos-hardware/commit/55b4caf931477fdfd70b86bae2ca000de18eab88) | `` Add 13-inch directory to framework and move new module ``                     |
| …

chore(flake/nixos-hardware): `627bc9b8` -> `b689465d`

---

flake.lock

| [`691cbcc0`](https://github.com/nix-community/home-manager/commit/691cbcc03af6ad1b5384c0e0e0b5f2298f58c5ce) | `` k9s: add aliases, plugins, views ``                 |
| [`e27be9db`](https://github.com/nix-community/home-manager/commit/e27be9db7b4ae5791f53d241b3661353c51a9677) | `` systemd: avoid creating an empty user.conf ``       |
| [`f5182ffc`](https://github.com/nix-community/home-manager/commit/f5182ffc4211860348fc7c78e0ba3a9d36f13aeb) | `` emacs: …

chore(flake/home-manager): `6a844446` -> `691cbcc0`

---

flake.lock

| Commit                                                                                                    | Message                                                      |
| --------------------------------------------------------------------------------------------------------- | ------------------------------------------------------------ |
| [`b7f3d607`](https://github.com/nix-community/lanzaboote/commit/b7f3d6070869a9ffde75a9788a752a93f358ed20) | `` feat(flake): perform final fixups to the flake outputs `` |

chore(flake/lanzaboote): `bc0fd4e1` -> `81975f3b`

---

flake.lock

| [`50e582b9`](https://github.com/nix-community/home-manager/commit/50e582b9f91e409ffd2e134017445d376659b32e) | `` swayidle: always restart systemd unit on failure `` |
| [`fad880ea`](https://github.com/nix-community/home-manager/commit/fad880ea934808072cd224152854d4257034bd24) | `` firefox: minor documentation fix ``                 |
| [`d78f6693`](https://github.com/nix-community/home-manager/commit/d78f6693ee382ee3b94bf48f2b0d0034ce2d902b) | `` firefox: …

chore(flake/home-manager): `691cbcc0` -> `50e582b9`

---

flake.lock

| [`d5736190`](https://github.com/nix-community/nix-index-database/commit/d573619090fce2bd9983dc48139671c18cbe696e) | `` flake.lock: Update `` |

chore(flake/nix-index-database): `5388a400` -> `d5736190`

---

flake.lock

| Commit                                                                                                      | Message                                                                                     |
| ----------------------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------------- |
| [`28072118`](https://github.com/nix-community/home-manager/commit/280721186ab75a76537713ec310306f0eba3e407) | `` firefox: support setting a separate default search engine in private browsing (#4114) `` |

chore(flake/home-manager): `50e582b9` -> `28072118`

---

flake.lock

| [`8aff4ca3`](https://github.com/nix-community/nix-index-database/commit/8aff4ca3dee60d1422489fe8d52c2f837b3ad113) | `` update packages.nix to release 2023-11-12-034340 `` |

chore(flake/nix-index-database): `d5736190` -> `8aff4ca3`

---

flake.lock

| Commit                                                                                           | Message                                  |
| ------------------------------------------------------------------------------------------------ | ---------------------------------------- |
| [`39a412d4`](https://github.com/LnL7/nix-darwin/commit/39a412d47ddb87f84e1a0d3eb168b0ce0d30498e) | `` Fix unbound variable `etcProblems` `` |

chore(flake/darwin): `0f1ad801` -> `e67f2bf5`

---

flake.lock

| [`df9bb8a4`](https://github.com/NixOS/nixos-hardware/commit/df9bb8a436607da124e8cfa0fd19e70e9d9e0b7b) | `` surface: linux 6.5.7 -> 6.5.11 ``                              |
| [`8bb2d5ca`](https://github.com/NixOS/nixos-hardware/commit/8bb2d5ca134832da48fe515a60a039d192f071a5) | `` surface: linux 6.1.57 -> 6.1.62 ``                             |
| [`27ac7d57`](https://github.com/NixOS/nixos-hardware/commit/27ac7d57bcfe6609281c1a31a1577470bcfd5db9) …

chore(flake/nixos-hardware): `b689465d` -> `df9bb8a4`

---

flake.lock

| Commit                                                                                                    | Message                                     |
| --------------------------------------------------------------------------------------------------------- | ------------------------------------------- |
| [`8e0d4226`](https://github.com/nix-community/lanzaboote/commit/8e0d422697bb36e077da801fbf615a726d3ecc18) | `` stub: remove nondeterminism in binary `` |

chore(flake/lanzaboote): `f8d26384` -> `2123d3a0`

---

flake.lock

| Commit                                                                                                | Message                                                                               |
| ----------------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------- |
| [`5689f3eb`](https://github.com/NixOS/nixos-hardware/commit/5689f3ebf899f644a1aabe8774d4f37eb2f6c2f9) | `` Fixed broken links in deprecation assertions for framework and surface modules. `` |

chore(flake/nixos-hardware): `df9bb8a4` -> `5689f3eb`

---

flake.lock

| Commit                                                                                                       | Message                                                 |
| ------------------------------------------------------------------------------------------------------------ | ------------------------------------------------------- |
| [`a22a571c`](https://github.com/cachix/pre-commit-hooks.nix/commit/a22a571c4b82f0e0ca46c1f7bbbe208029ac6fb0) | `` Fix hooksPath when configured from a subdirectory `` |

chore(flake/pre-commit-hooks): `ea758da1` -> `e558068c`

---

flake.lock

| [`ab1459a1`](https://github.com/nix-community/home-manager/commit/ab1459a1fb646c40419c732d05ec0bf2416d4506) | `` openstackclient: add module (#4530) `` |

chore(flake/home-manager): `28072118` -> `ab1459a1`

---

flake.lock

| Commit                                                                                                | Message                                                                                      |
| ----------------------------------------------------------------------------------------------------- | -------------------------------------------------------------------------------------------- |
| [`96805caf`](https://github.com/Mic92/nix-fast-build/commit/96805cafb2bc678ce15eda386989f9e79b28868b) | `` nix-fast-build: fix typo ``                                                               |
| [`3903f1d5`](https://github.com/Mic92/nix-fast-build/commit/3903f1d5b648c19bc1bbbfe4dc06eb965dc1a2cf) | `` increase large buffer for large lines `` …

chore(flake/nix-fast-build): `77c76498` -> `96805caf`

---

flake.lock

| Commit                                                                                         | Message                                                                                       |
| ---------------------------------------------------------------------------------------------- | --------------------------------------------------------------------------------------------- |
| [`f642d01e`](https://github.com/NixOS/nixpkgs/commit/f642d01e41fe3e90f480292ffcfb69cbb82ae515) | `` Revert "python311Packages.pyuavcan: add deprecation warning" ``                            |
| [`43402041`](https://github.com/NixOS/nixpkgs/commit/434020410f9735e5aada9761d88721b1370c94ee) | `` usql: 0.15.2 -> 0.16.0 ``                                                                  |
| …

chore(flake/nixpkgs): `e44462d6` -> `bf744fe9`

---

flake.lock

| [`c1a03312`](https://github.com/nix-community/home-manager/commit/c1a033122df8a3c74fda3780c83a104a7d60873c) | `` Translate using Weblate (French) ``  |
| [`18ce0de4`](https://github.com/nix-community/home-manager/commit/18ce0de460a6f291926fd4ca03f2df9b0a291c6f) | `` Translate using Weblate (Turkish) `` |
| [`f6c1a4f2`](https://github.com/nix-community/home-manager/commit/f6c1a4f23b99543270c1319500d3eefcd731586d) | `` Translate using Weblate (Italian) `` |

chore(flake/home-manager): `ab1459a1` -> `c1a03312`

---

flake.lock

| [`3feeb771`](https://github.com/nix-community/home-manager/commit/3feeb7715584fd45ed1389cec8fb15f6930e8dab) | `` firefox: add support for specifying policies (#4626) `` |

chore(flake/home-manager): `c1a03312` -> `3feeb771`

---

flake.lock

| [`ecd0a800`](https://github.com/nix-community/home-manager/commit/ecd0a800f716b80a6eac58a7ac34d6d33e6fa5ee) | `` Translate using Weblate (French) `` |

chore(flake/home-manager): `3feeb771` -> `ecd0a800`

---

flake.lock

| [`a15c3196`](https://github.com/danth/stylix/commit/a15c3196c1d620c18cbee8229092598384a89fef) | `` Fix default cursor in X11 (#189) `` |

chore(flake/stylix): `5c6f7fd7` -> `a15c3196`

---

flake.lock

| [`1721da31`](https://github.com/NixOS/nixos-hardware/commit/1721da31f9b30cbf4460c4ec5068b3b6174a4694) | `` starfive visionfive2: update kernel to 6.6.0 ``              |
| [`e27bf85b`](https://github.com/NixOS/nixos-hardware/commit/e27bf85b46cb6325d6052144d63a26935f8b1cfb) | `` starfive visionfive2: update u-boot to SDK version v3.8.2 `` |
| [`eb903ed8`](https://github.com/NixOS/nixos-hardware/commit/eb903ed873af4063bf400ac988b03465fef51129) | `` …

chore(flake/nixos-hardware): `5689f3eb` -> `1721da31`

---

flake.lock

| [`cabd674e`](https://github.com/nix-community/nix-index-database/commit/cabd674eb65b394a4d8c9c73091f408027fde28f) | `` flake.lock: Update `` |

chore(flake/nix-index-database): `8aff4ca3` -> `cabd674e`

---

flake.lock

| [`27920146`](https://github.com/nix-community/nix-index-database/commit/27920146e671a0d565aaa7452907383be14d8d82) | `` update packages.nix to release 2023-11-19-030847 `` |

chore(flake/nix-index-database): `cabd674e` -> `27920146`

---

flake.lock

| Commit                                                                                                      | Message                                                                       |
| ----------------------------------------------------------------------------------------------------------- | ----------------------------------------------------------------------------- |
| [`7af96988`](https://github.com/nix-community/home-manager/commit/7af969886b0792be6d1d2c13404052e6393a8eb3) | `` home-manager: improve comment in example configuration ``                  |
| [`6fd3a5b7`](https://github.com/nix-community/home-manager/commit/6fd3a5b728e71922945a388501886922bef11eaf) | `` flake.lock: Update ``                                                      |
| …

chore(flake/home-manager): `ecd0a800` -> `9a4725af`

---

flake.lock

| [`89e68213`](https://github.com/NixOS/nixos-hardware/commit/89e68213709d78509994178dc3e56643cc2af629) | `` add and use mkDisableOption ``             |
| [`a742fe3a`](https://github.com/NixOS/nixos-hardware/commit/a742fe3a04105756d6a700ef1e885b326b7e57cd) | `` raspberry-pi/4: add led disable overlay `` |
| [`9d09a745`](https://github.com/NixOS/nixos-hardware/commit/9d09a7452ccf99f2ddfca1a349758312cc5d569c) | `` raspberry-pi/4: format ``                  |

chore(flake/nixos-hardware): `1721da31` -> `2b00bc76`

---

flake.lock

| [`993fb02d`](https://github.com/nix-community/home-manager/commit/993fb02d20760067b8ee19c713d94cee07037759) | `` zsh: allow enabling syntax highlighters (#4360) `` |

chore(flake/home-manager): `9a4725af` -> `993fb02d`

---

flake.lock

| Commit                                                                                         | Message                                                                                    |
| ---------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------------ |
| [`e4ad9895`](https://github.com/NixOS/nixpkgs/commit/e4ad989506ec7d71f7302cc3067abd82730a4beb) | `` gleam: 0.32.2 -> 0.32.4 ``                                                              |
| [`995b8019`](https://github.com/NixOS/nixpkgs/commit/995b80195053953e0daac32c16342161bea887b2) | `` displaycal: 3.9.10 -> 3.9.11 ``                                                         |
| …

chore(flake/nixpkgs): `bf744fe9` -> `e4ad9895`

---

flake.lock

| [`1aabb0a3`](https://github.com/nix-community/home-manager/commit/1aabb0a31b25ad83cfaa37c3fe29053417cd9a0f) | `` picom: use getExe instead of hardcoded binary ``           |
| [`3de857fa`](https://github.com/nix-community/home-manager/commit/3de857fa7d996a60966cccb44fbfce8d3c4544d8) | `` qt: fix `qt.platformTheme = "gtk3"` ``                     |
| [`fff5204e`](https://github.com/nix-community/home-manager/commit/fff5204e5dbe8403d5ad1816c183 …

chore(flake/home-manager): `993fb02d` -> `1aabb0a3`

---

flake.lock

| [`c3abafb0`](https://github.com/NixOS/nixos-hardware/commit/c3abafb01cd7045dba522af29b625bd1e170c2fb) | `` chore: Add switcheroo service for Dual GPU ``     |
| [`fc126177`](https://github.com/NixOS/nixos-hardware/commit/fc126177f68500a53155a2b3a6bd2d711f5495d2) | `` chore: Activate nvidia powermanagement ``         |
| [`82cf9ae3`](https://github.com/NixOS/nixos-hardware/commit/82cf9ae3f663471552610e6ece2eeb3b43908a13) | `` framework/13-inch/12th-gen-intel: ec crash fix …

chore(flake/nixos-hardware): `2b00bc76` -> `c3abafb0`

---

flake.lock

| Commit                                                                                           | Message                                      |
| ------------------------------------------------------------------------------------------------ | -------------------------------------------- |
| [`319104a1`](https://github.com/LnL7/nix-darwin/commit/319104a1258fa71857aae4956a010f553da0cc9b) | `` Improve flakes documentation in README `` |

chore(flake/darwin): `e67f2bf5` -> `fb9ed3f0`

---

flake.lock

| [`134deb46`](https://github.com/nix-community/home-manager/commit/134deb46abd5d0889d913b8509413f6f38b0811e) | `` bat: support boolean flags in config `` |
| [`1bd1e864`](https://github.com/nix-community/home-manager/commit/1bd1e8646473235dfe76831812f8662b837cb184) | `` ruff: add module ``                     |

chore(flake/home-manager): `1aabb0a3` -> `134deb46`

---

flake.lock

| Commit                                                                                           | Message                                    |
| ------------------------------------------------------------------------------------------------ | ------------------------------------------ |
| [`89248225`](https://github.com/LnL7/nix-darwin/commit/892482250c3726b8f4b255d3aff7f4208bbfba97) | `` [yabai] Configure scripting addition `` |

chore(flake/darwin): `fb9ed3f0` -> `6e0f4e58`

---

flake.lock

| Commit                                                                                           | Message                          |
| ------------------------------------------------------------------------------------------------ | -------------------------------- |
| [`d4efdb7f`](https://github.com/LnL7/nix-darwin/commit/d4efdb7f88a633c8608084e565e2fde2998c33ed) | `` etc: add more known hashes `` |

chore(flake/darwin): `6e0f4e58` -> `c465a67a`

---

flake.lock

| [`cf9a7cd4`](https://github.com/NixOS/nixpkgs/commit/cf9a7cd48adb81814dd5d92747a06b4854e5f908) | `` xeus-cling: init at 0.15.3 ``                                            |
| [`1383b84d`](https://github.com/NixOS/nixpkgs/commit/1383b84d37d3dbca82c4c07bd0afe5d6e2ebaf35) | `` coq_kernel: init at 1.6.0 ``                                             |
| [`72edcc74`](https://github.com/NixOS/nixpkgs/commit/72edcc748a92377d0568c9536ece114dbabb9 …

chore(flake/nixpkgs): `e4ad9895` -> `19cbff58`

---

flake.lock

| [`49ae6b92`](https://github.com/LnL7/nix-darwin/commit/49ae6b92ffe7199622bdddcff13e649bdf12f9d0) | `` fix: tests failing to build on unstable Nix `` |

chore(flake/darwin): `c465a67a` -> `7e8d2927`

---

flake.lock

| Commit                                                                                           | Message                                                                                     |
| ------------------------------------------------------------------------------------------------ | ------------------------------------------------------------------------------------------- |
| [`09284ab0`](https://github.com/LnL7/nix-darwin/commit/09284ab00b2bf86b0d33bae8cf8b1a999bb512d9) | `` Install darwin-uninstall by default, which includes the 'empty' config it switches to `` |

chore(flake/darwin): `7e8d2927` -> `4b9b83d5`

---

flake.lock

| [`e1f3b36a`](https://github.com/nix-community/home-manager/commit/e1f3b36ab01573fd35cae57d21f45d520433df61) | `` home-manager: set unstable release to 24.05 `` |
| [`aeb2232d`](https://github.com/nix-community/home-manager/commit/aeb2232d7a32530d3448318790534d196bf9427a) | `` home-manager: set stable release to 23.11 ``   |

chore(flake/home-manager): `134deb46` -> `e1f3b36a`

---

flake.lock

| [`8cedd63e`](https://github.com/nix-community/home-manager/commit/8cedd63eede4c22deb192f1721dd67e7460e1ebe) | `` fish: support flexible abbreviations `` |

chore(flake/home-manager): `e1f3b36a` -> `8cedd63e`

---

flake.lock

| Commit                                                                                                       | Message                 |
| ------------------------------------------------------------------------------------------------------------ | ----------------------- |
| [`0067c7ce`](https://github.com/cachix/pre-commit-hooks.nix/commit/0067c7ce77ef4e8d671237f938c48716f9810df8) | `` Add golangci-lint `` |

chore(flake/pre-commit-hooks): `e558068c` -> `e5ee5c5f`

---

flake.lock

| Commit                                                                                        | Message                                               |
| --------------------------------------------------------------------------------------------- | ----------------------------------------------------- |
| [`8b3f6172`](https://github.com/danth/stylix/commit/8b3f61727f3b86c27096c3c014ae602aa40670ba) | `` Support GNOME 45 and Libadwaita updates :alien: `` |

chore(flake/stylix): `dbeef75e` -> `8b3f6172`

---

flake.lock

| Commit                                                                                         | Message                                                                                    |
| ---------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------------ |
| [`221acc91`](https://github.com/NixOS/nixpkgs/commit/221acc9183af496a813b1811f9c66b63c2d9677d) | `` esphome: 2023.11.2 -> 2023.11.3 (#269179) ``                                            |
| [`9b2b4ee6`](https://github.com/NixOS/nixpkgs/commit/9b2b4ee621619d34167f17b7f396495855ac6067) | `` lilypond: 2.24.2 -> 2.24.3 ``                                                           |
| …

chore(flake/nixpkgs): `19cbff58` -> `5a09cb4b`

---

flake.lock

| [`a462e731`](https://github.com/nix-community/home-manager/commit/a462e7315deaa8194b0821f726709bb7e51a850c) | `` yazi: update shell integrations and docs `` |

chore(flake/home-manager): `8cedd63e` -> `a462e731`

---

flake.lock

| [`d189d05f`](https://github.com/nix-community/nix-index-database/commit/d189d05f9de237d3b554c91029f9cb78efec8ace) | `` flake.lock: Update `` |

chore(flake/nix-index-database): `27920146` -> `d189d05f`

---

flake.lock

| [`bd3aec0e`](https://github.com/nix-community/nix-index-database/commit/bd3aec0ecb0fdde863a7ed2c6caa220c47e22c07) | `` update packages.nix to release 2023-11-26-030655 `` |

chore(flake/nix-index-database): `d189d05f` -> `bd3aec0e`

---

flake.lock

| Commit                                                                                                | Message                                                               |
| ----------------------------------------------------------------------------------------------------- | --------------------------------------------------------------------- |
| [`b006ec52`](https://github.com/NixOS/nixos-hardware/commit/b006ec52fce23b1d57f6ab4a42d7400732e9a0a2) | `` Bump linux-surface to a6eafcad32dc789ae92f42636b11e9aae6e7c879. `` |

chore(flake/nixos-hardware): `c3abafb0` -> `b006ec52`

---

flake.lock

| [`7c97c46d`](https://github.com/nix-community/home-manager/commit/7c97c46dc4f45f2a78df536a6ebe15252831b800) | `` signaturepdf: add service `` |
| [`8340c0b4`](https://github.com/nix-community/home-manager/commit/8340c0b4d9986a91ca0ef746637839df99c43d3e) | `` flake.lock: Update ``        |

chore(flake/home-manager): `a462e731` -> `7c97c46d`

---

flake.lock

| [`db1878f0`](https://github.com/nix-community/home-manager/commit/db1878f013b52ba5e4034db7c1b63e8d04173a86) | `` home-manager: add 24.05 as valid state version `` |

chore(flake/home-manager): `7c97c46d` -> `db1878f0`

---

flake.lock

| Commit                                                                                         | Message                                       |
| ---------------------------------------------------------------------------------------------- | --------------------------------------------- |
| [`4c486060`](https://github.com/ryantm/agenix/commit/4c4860609491a98c1e4a6f03e0ba27c0a23982c0) | `` only backup cleartext file if it exists `` |

chore(flake/agenix): `daf42cb3` -> `13ac9ac6`

---

flake.lock

| Commit                                                                                         | Message                                                                                       |
| ---------------------------------------------------------------------------------------------- | --------------------------------------------------------------------------------------------- |
| [`271a11a2`](https://github.com/NixOS/nixpkgs/commit/271a11a2d6145f0a4c842779599251e8efcb3d48) | `` ripgrep: 13.0.0 -> 14.0.1 ``                                                               |
| [`2ec2d682`](https://github.com/NixOS/nixpkgs/commit/2ec2d68238e57cd69edcb93e5b104abde10cca03) | `` coqPackages.VST: 2.12 → 2.13 ``                                                            |
| …

chore(flake/nixpkgs): `5a09cb4b` -> `8cfef698`

---

flake.lock

| Commit                                                                                                    | Message                                                 |
| --------------------------------------------------------------------------------------------------------- | ------------------------------------------------------- |
| [`d48eac71`](https://github.com/nix-community/lanzaboote/commit/d48eac71a41a517843e960a1ba4c22b67960ac34) | `` flake: remove moving away the `unsupportedChecks` `` |

chore(flake/lanzaboote): `cbafc8f8` -> `43582b56`

---

flake.lock

| [`41becba8`](https://github.com/NixOS/nixpkgs/commit/41becba8d22548cc15d7eabd8eb8737740fd3f54) | `` sysdig: 0.33.1 -> 0.34.1 ``                                                    |
| [`6007641a`](https://github.com/NixOS/nixpkgs/commit/6007641aff774f573a421d726a1cb2d38dd4903d) | `` dune_3: 3.11.1 -> 3.12.0 ``                                                    |
| [`edfc8aca`](https://github.com/NixOS/nixpkgs/commit/edfc8acaaf859 …

chore(flake/nixpkgs): `8cfef698` -> `e92039b5`

---

flake.lock

| [`ef908825`](https://github.com/nix-community/home-manager/commit/ef9088253c120d9b4dc26c5e41dd6c3c781ee9f0) | `` Translate using Weblate (Russian) ``             |
| [`3d154dab`](https://github.com/nix-community/home-manager/commit/3d154dab14aef8fcf510e291030cecc53b02985a) | `` Translate using Weblate (Russian) ``             |
| [`2a604e61`](https://github.com/nix-community/home-manager/commit/2a604e614f974af7e4f9296f1560ce275d2e3786) | `` Translate using …

chore(flake/home-manager): `db1878f0` -> `ef908825`

---

flake.lock

| [`41afa8d1`](https://github.com/nix-community/nix-index-database/commit/41afa8d1c061beda68502bcc67f2788f3a77042b) | `` update packages.nix to release 2023-12-03-030712 `` |

chore(flake/nix-index-database): `c0004959` -> `41afa8d1`

---

flake.lock

| [`a89745ed`](https://github.com/NixOS/nixos-hardware/commit/a89745edd5f657e2e5be5ed1bea86725ca78d92e) | `` surface: Allow specifying major versions for kernel `` |
| [`eb4e5743`](https://github.com/NixOS/nixos-hardware/commit/eb4e5743609d36c673a979850af2d90d5e3e26fa) | `` framework intel: Disable cros-usbpd-charger ``         |

chore(flake/nixos-hardware): `8772491e` -> `a89745ed`

---

flake.lock

| [`0d401071`](https://github.com/nix-community/home-manager/commit/0d4010711922388c80a115d62cdb7ba04c2ed738) | `` flake.lock: Update `` |

chore(flake/home-manager): `4a8545f5` -> `0d401071`

---

flake.lock

| [`fa194fc4`](https://github.com/NixOS/nixos-hardware/commit/fa194fc484fd7270ab324bb985593f71102e84d1) | `` build(deps): bump cachix/install-nix-action from 23 to 24 `` |

chore(flake/nixos-hardware): `a89745ed` -> `fa194fc4`

---

flake.lock

| [`ca9b6bc0`](https://github.com/NixOS/nixpkgs/commit/ca9b6bc0a755702153910fd8fe7228517957de5d) | `` nixVersions.nix_2_19: 2.19.1 -> 2.19.2 ``                                   |
| [`709a9f6f`](https://github.com/NixOS/nixpkgs/commit/709a9f6f065569451cd2ffd904cf2ffba7454529) | `` nixVersions.unstable: 2.18 -> 2.19 ``                                       |
| [`3773ebf4`](https://github.com/NixOS/nixpkgs/commit/3773ebf41aecaa303cd21da71 …

chore(flake/nixpkgs): `e92039b5` -> `91050ea1`

---

flake.lock

| [`ac721691`](https://github.com/nix-community/home-manager/commit/ac7216918cd65f3824ba7817dea8f22e61221eaf) | `` firefox: fix folders not showing in toolbar `` |

chore(flake/home-manager): `948703f3` -> `ac721691`

---

flake.lock

| Commit                                                                                                            | Message                                                       |
| ----------------------------------------------------------------------------------------------------------------- | ------------------------------------------------------------- |
| [`ca1f1798`](https://github.com/nix-community/nix-index-database/commit/ca1f1798f63ada20dffcb8b23039b00a597dafe9) | `` mergify: also merge dependabot ``                          |
| [`89f4a957`](https://github.com/nix-community/nix-index-database/commit/89f4a957a09b945eae6cc5032833b756ef155a11) | `` Bump cachix/install-nix-action from 23 to 24 ``            |
| [`9cbd0781`](https://github.com/nix-community/nix-index-database/commi …

chore(flake/nix-index-database): `41afa8d1` -> `ca1f1798`

---

flake.lock

| [`f10eb1b3`](https://github.com/nix-community/home-manager/commit/f10eb1b3ee8e5ee2891b34b6c9f12567f73f9693) | `` docs: apply nixfmt ``                             |
| [`613dbb35`](https://github.com/nix-community/home-manager/commit/613dbb35dbc142fd5cadca847f8677e64a502bfa) | `` docs: rename generated manual to `index.xhtml` `` |
| [`0a710464`](https://github.com/nix-community/home-manager/commit/0a710464932ae65238f583e69f887fea6bd72c0e) | `` docs: fix syntax …

chore(flake/home-manager): `ac721691` -> `7db6291d`

---

flake.lock

| [`efa36e89`](https://github.com/nix-community/home-manager/commit/efa36e896951bec8d96e38ea40a22c010bd1bd8f) | `` Translate using Weblate (Czech) `` |

chore(flake/home-manager): `7db6291d` -> `efa36e89`

---

flake.lock

| [`e6b7303b`](https://github.com/nix-community/home-manager/commit/e6b7303bd149723c57ca23f5a9428482d6b07306) | `` docs: fix broken links in README ``             |
| [`fa91c109`](https://github.com/nix-community/home-manager/commit/fa91c109b0dd12e680dd29010e262884f7b26186) | `` docs: use relative paths to static resources `` |

chore(flake/home-manager): `efa36e89` -> `e6b7303b`

---

flake.lock

| [`d1cd3e3f`](https://github.com/nix-community/nix-index-database/commit/d1cd3e3f6bb27177800761a5ab6487a8867f7f1b) | `` flake.lock: Update `` |

chore(flake/nix-index-database): `ca1f1798` -> `d1cd3e3f`

---

flake.lock

| [`58ecd98e`](https://github.com/nix-community/nix-index-database/commit/58ecd98e27e27fcbb27a51a588555c828b1ec56e) | `` update packages.nix to release 2023-12-10-030756 `` |

chore(flake/nix-index-database): `d1cd3e3f` -> `58ecd98e`

---

flake.lock

| [`093777ee`](https://github.com/nix-community/home-manager/commit/093777ee4ab07d70be46e8edb492865e12a865e0) | `` caffeine: remove ProtectHome service option `` |

chore(flake/home-manager): `e6b7303b` -> `093777ee`

---

flake.lock

| [`9a00befa`](https://github.com/nix-community/home-manager/commit/9a00befa13126e318fa4b895adeb84d383c9ab3f) | `` ci: bump cachix/cachix-action from 12 to 13 `` |

chore(flake/home-manager): `093777ee` -> `9a00befa`

---

flake.lock

| [`defbb9c5`](https://github.com/nix-community/home-manager/commit/defbb9c5857e157703e8fc7cf3c2ceb01cb95883) | `` hyprland: add option sourceFirst `` |

chore(flake/home-manager): `9a00befa` -> `defbb9c5`

---

flake.lock

| [`030edbb6`](https://github.com/NixOS/nixos-hardware/commit/030edbb68e69f2b97231479f98a9597024650df2) | `` lenovo: add ideapad s145-15api to readme.md ``       |
| [`b3211356`](https://github.com/NixOS/nixos-hardware/commit/b32113560acaadb92251efcd6bef67419797839b) | `` lenovo: reference ideapad s145-15api on flake.nix `` |
| [`c78145fc`](https://github.com/NixOS/nixos-hardware/commit/c78145fc512a703af114aec176658dee872e4e90) | `` lenovo: add config for ideapad …

chore(flake/nixos-hardware): `fa194fc4` -> `030edbb6`

---

flake.lock

| [`b5ad31b7`](https://github.com/danth/stylix/commit/b5ad31b710294038f9ed70efdf787db6a82d7327) | `` Set font face for kmscon (#195) `` |

chore(flake/stylix): `17a452c5` -> `b5ad31b7`

---

flake.lock

| Commit                                                                                                            | Message                                         |
| ----------------------------------------------------------------------------------------------------------------- | ----------------------------------------------- |
| [`68ee1b79`](https://github.com/nix-community/nix-index-database/commit/68ee1b7918c21f396552f5f7dfc378afbc2229d5) | `` Avoid calling builtins.import on modules. `` |

chore(flake/nix-index-database): `58ecd98e` -> `45d82e0a`

---

flake.lock

| Commit                                                                                                       | Message                                   |
| ------------------------------------------------------------------------------------------------------------ | ----------------------------------------- |
| [`d3708281`](https://github.com/cachix/pre-commit-hooks.nix/commit/d37082815fea8febd96babebf75eb4294cb899ff) | `` hooks: fix deno fmt/lint configPath `` |

chore(flake/pre-commit-hooks): `e5ee5c5f` -> `f99ed852`

---

flake.lock

| Commit                                                                                                       | Message           |
| ------------------------------------------------------------------------------------------------------------ | ----------------- |
| [`88990864`](https://github.com/cachix/pre-commit-hooks.nix/commit/889908642a8fcc1cd8a7be3d94ccfaf93c1800bd) | `` Add conform `` |

chore(flake/pre-commit-hooks): `f99ed852` -> `e1d203c2`

---

flake.lock

| Commit                                                                                              | Message                                 |
| --------------------------------------------------------------------------------------------------- | --------------------------------------- |
| [`99664561`](https://github.com/serokell/deploy-rs/commit/99664561ec91db45679c76c8816f42d420d9b7d3) | `` [Chore] Update "actions/checkout" `` |

chore(flake/deploy-rs): `514fa3bc` -> `2ccd5d99`

---

flake.lock

| [`0e7cd646`](https://github.com/nix-community/home-manager/commit/0e7cd646743249c6f4f257e8cfacf73ccf19e0b9) | `` docs: fix nix-darwin module configuration example `` |
| [`01a66e31`](https://github.com/nix-community/home-manager/commit/01a66e313f9386cbde1ed597aeb5c3a08661e2d9) | `` msmtp: add configurable package ``                   |
| [`b3c4e98a`](https://github.com/nix-community/home-manager/commit/b3c4e98aec170c04268451db00d7dbe2dad2f4a5) | `` …

chore(flake/home-manager): `defbb9c5` -> `0e7cd646`

---

flake.lock

| [`d9297efd`](https://github.com/nix-community/home-manager/commit/d9297efd3a1c3ebb9027dc68f9da0ac002ae94db) | `` awscli: only write config files when not empty `` |

chore(flake/home-manager): `0e7cd646` -> `d9297efd`

---

flake.lock

| [`7763c6fd`](https://github.com/NixOS/nixos-hardware/commit/7763c6fd1f299cb9361ff2abf755ed9619ef01d6) | `` Lenovo Legion 16achg6 support (#796) `` |

chore(flake/nixos-hardware): `fef05bf9` -> `7763c6fd`

---

flake.lock

| Commit                                                                                                       | Message                                                         |
| ------------------------------------------------------------------------------------------------------------ | --------------------------------------------------------------- |
| [`97f9b483`](https://github.com/cachix/pre-commit-hooks.nix/commit/97f9b48312ebe4129e0490ac589c58c9102f16ad) | `` Add require_serial hook config to pre-commit json ``         |
| [`51916ed7`](https://github.com/cachix/pre-commit-hooks.nix/commit/51916ed7a1d9d68b80f84b6f06d7a1f5696f1672) | `` Add fail_fast hook config to pre-commit json ``              |
| [`ef6d60d4`](https://github.com/cachix/pre-commit-hooks.nix/commit/ef6d60d47853d79 …

chore(flake/pre-commit-hooks): `e1d203c2` -> `007a45d0`

---

flake.lock

| Commit                                                                                              | Message                                                     |
| --------------------------------------------------------------------------------------------------- | ----------------------------------------------------------- |
| [`6d70659c`](https://github.com/serokell/deploy-rs/commit/6d70659c846b94e2ba4fef80441ae94b7fb2b5ea) | `` Automatically update flake.lock to the latest version `` |

chore(flake/deploy-rs): `2ccd5d99` -> `91532751`

---

flake.lock

| [`5e9d1fe1`](https://github.com/nix-community/home-manager/commit/5e9d1fe19f2d17cdfeb3b7e5e668f763e430cd28) | `` flake.lock: Update ``             |
| [`7a69b3e7`](https://github.com/nix-community/home-manager/commit/7a69b3e738a587915a374994e05e8e10f1216721) | `` ssh: add addKeysToAgent option `` |

chore(flake/home-manager): `d9297efd` -> `5e9d1fe1`

---

flake.lock

| [`0e2e443f`](https://github.com/nix-community/home-manager/commit/0e2e443ff24f9d75925e91b89d1da44b863734af) | `` hyprland: mark plugin setting as important `` |
| [`be97e96d`](https://github.com/nix-community/home-manager/commit/be97e96dab93e766b7ed57cf5529a49eb765fad3) | `` flake: add packages for tests ``              |
| [`7a88cded`](https://github.com/nix-community/home-manager/commit/7a88cdedbda35f808ed2f329a7a811e0511870f9) | `` hyprland: improve config reload …

chore(flake/home-manager): `5e9d1fe1` -> `0e2e443f`

---

flake.lock

| Commit                                                                                        | Message                         |
| --------------------------------------------------------------------------------------------- | ------------------------------- |
| [`41d21859`](https://github.com/danth/stylix/commit/41d218597590a89324a4b7c50cf0bf088a7214ba) | `` Add Firefox module (#191) `` |

chore(flake/stylix): `b5ad31b7` -> `41d21859`

---

flake.lock

| Commit                                                                                                         | Message                             |
| -------------------------------------------------------------------------------------------------------------- | ----------------------------------- |
| [`3d8cf655`](https://github.com/tinted-theming/base16-schemes/commit/3d8cf655eeb4ad741746c5abb3cc96454e68ef41) | `` Fix filenames of some schemes `` |

chore(flake/base16-schemes): `a9112eaa` -> `3d8cf655`

---

flake.lock

| [`abdc82d9`](https://github.com/nix-community/home-manager/commit/abdc82d930521448e47574b8ca1a0a450e861cca) | `` yazi: pass additional args to ya alias `` |

chore(flake/home-manager): `0e2e443f` -> `abdc82d9`

---

flake.lock

| Commit                                                                                                         | Message                                |
| -------------------------------------------------------------------------------------------------------------- | -------------------------------------- |
| [`2b6f2d06`](https://github.com/tinted-theming/base16-schemes/commit/2b6f2d0677216ddda50c9cabd6ee70fae4665f81) | `` Add deprecation notice to README `` |

chore(flake/base16-schemes): `3d8cf655` -> `2b6f2d06`

---

flake.lock

| [`5b339866`](https://github.com/nix-community/home-manager/commit/5b3398668b2b7f41607cf77fc9f1cb6402716882) | `` fish: Fix babelization of hm-session-vars `` |
| [`07754e93`](https://github.com/nix-community/home-manager/commit/07754e935a5e6f07f73e43c214f4f24f8ef82117) | `` docs: add considerate as maintainer ``       |
| [`6c82b1c9`](https://github.com/nix-community/home-manager/commit/6c82b1c9ce4dfb882cf53d1b9a09f01fbc9b0ba1) | `` docs: use .xhtml for appendices `` …

chore(flake/home-manager): `abdc82d9` -> `b00a03b6`

---

flake.lock

| [`e9b9ecef`](https://github.com/nix-community/home-manager/commit/e9b9ecef4295a835ab073814f100498716b05a96) | `` gtk: fix GTK 4 theme being ignored `` |

chore(flake/home-manager): `b00a03b6` -> `e9b9ecef`

---

flake.lock

| [`4aee2973`](https://github.com/nix-community/nix-index-database/commit/4aee297392b1f51fc690975d9b698ee230e372b7) | `` flake.lock: Update `` |

chore(flake/nix-index-database): `45d82e0a` -> `4aee2973`

---

flake.lock

| [`27edc98a`](https://github.com/nix-community/nix-index-database/commit/27edc98a32959b003e4bcef9719ad6f24e312343) | `` update packages.nix to release 2023-12-17-030802 `` |

chore(flake/nix-index-database): `4aee2973` -> `27edc98a`

---

flake.lock

| [`e4dba0bd`](https://github.com/nix-community/home-manager/commit/e4dba0bd01956170667458be7b45f68170a63651) | `` docs: set the manual version to "24.05 (unstable)" `` |
| [`a2e592cc`](https://github.com/nix-community/home-manager/commit/a2e592cc49850f32b59d0ab2a66ae0871f525c65) | `` home-manager: improve nix profile detection ``        |
| [`c22b41f0`](https://github.com/nix-community/home-manager/commit/c22b41f006d4c66d183d1e8baaca4b8f48062979) | `` …

chore(flake/home-manager): `e9b9ecef` -> `e4dba0bd`

---

flake.lock

| Commit                                                                                                            | Message                                          |
| ----------------------------------------------------------------------------------------------------------------- | ------------------------------------------------ |
| [`4605ccd7`](https://github.com/nix-community/nix-index-database/commit/4605ccd764fac78b9e4b5b058698cb9f04430b91) | `` Bump actions/upload-artifact from 3 to 4 ``   |
| [`4efa7c36`](https://github.com/nix-community/nix-index-database/commit/4efa7c3666cbae719e94b9c51f1284a11653b718) | `` Bump actions/download-artifact from 3 to 4 `` |

chore(flake/nix-index-database): `27edc98a` -> `4605ccd7`

---

flake.lock

| [`e8aaced7`](https://github.com/nix-community/home-manager/commit/e8aaced73ebaf6bfa8e3c6ab0a19cb184bc4d798) | `` home-manager: sort list packages output `` |

chore(flake/home-manager): `e4dba0bd` -> `e8aaced7`

---

flake.lock

| [`0c893cf0`](https://github.com/nix-community/impermanence/commit/0c893cf08a6c9559e482466340e82ac1f569937d) | `` README: Expand with more details on system setup and a better intro `` |

chore(flake/impermanence): `0f317c2e` -> `0c893cf0`

---

flake.lock

| [`554d7e6f`](https://github.com/nix-community/impermanence/commit/554d7e6fd13d5ff43e8738c128a2bd09b51c78d9) | `` forgot te replace `persistentStoragePath` occurrence `` |
| [`dc6d092d`](https://github.com/nix-community/impermanence/commit/dc6d092da5fb31a0cdb7ee430e99e1cc94ec1d00) | `` home-manager: add persistentStoragePath option ``       |

chore(flake/impermanence): `0c893cf0` -> `f1fe8fcf`

---

flake.lock

| [`bcfdc06b`](https://github.com/nix-community/impermanence/commit/bcfdc06b2372f196ac908cf60cc888d28db6b344) | `` Fix error when target is `/` `` |

chore(flake/impermanence): `f1fe8fcf` -> `123e9420`

---

flake.lock

| [`d14ac491`](https://github.com/danth/stylix/commit/d14ac4912a9ab02f8b49b761e9e4b9ae836171af) | `` Adds support for styling nixvim (#194) `` |

chore(flake/stylix): `41d21859` -> `d14ac491`

---

flake.lock

| [`ebeeef94`](https://github.com/nix-community/home-manager/commit/ebeeef94ab0cba72ca3b3a89b98658dcc1296c11) | `` docs: fix typo in nix-flakes.md `` |

chore(flake/home-manager): `e8aaced7` -> `ebeeef94`

---

flake.lock

| Commit                                                                                         | Message                                              |
| ---------------------------------------------------------------------------------------------- | ---------------------------------------------------- |
| [`93cec0ce`](https://github.com/ryantm/agenix/commit/93cec0ce6ed1061bf0973c5fef76b2d8e76d4810) | `` dev: add security label category ``               |
| [`221a1f22`](https://github.com/ryantm/agenix/commit/221a1f22e5333882419023c698d21fbfc3017642) | `` dev: add release-drafter ``                       |
| [`65fe5959`](https://github.com/ryantm/agenix/commit/65fe5959c3014be90cbc046f30288b6e14beff48) | `` create leading directories if they don't exist `` |
| …

chore(flake/agenix): `13ac9ac6` -> `93cec0ce`

---

flake.lock

| Commit                                                                                              | Message                                                     |
| --------------------------------------------------------------------------------------------------- | ----------------------------------------------------------- |
| [`56ba8c39`](https://github.com/serokell/deploy-rs/commit/56ba8c3929802fb00c4803452024e23cdb54cc99) | `` [Chore] Add missing documentation for timeout options `` |

chore(flake/deploy-rs): `91532751` -> `b709d63d`

---

flake.lock

| [`433120e4`](https://github.com/nix-community/home-manager/commit/433120e47d016c9960dd9c2b1821e97d223a6a39) | `` gradle: add module `` |

chore(flake/home-manager): `efc177c1` -> `433120e4`

---

flake.lock

| Commit                                                                                         | Message                                       |
| ---------------------------------------------------------------------------------------------- | --------------------------------------------- |
| [`564595d0`](https://github.com/ryantm/agenix/commit/564595d0ad4be7277e07fa63b5a991b3c645655d) | `` version 0.15.0 ``                          |
| [`9d3b37a1`](https://github.com/ryantm/agenix/commit/9d3b37a1177fedcce0a6c72ff4d337283a393fe2) | `` fix: update keys functions in agenix.sh `` |

chore(flake/agenix): `93cec0ce` -> `564595d0`

---

flake.lock

| Commit                                                                                         | Message                                    |
| ---------------------------------------------------------------------------------------------- | ------------------------------------------ |
| [`097aa18b`](https://github.com/ryantm/agenix/commit/097aa18b593a9f8215ce743a0796ae76b19b28d5) | `` contrib: add direct tests for agenix `` |

chore(flake/agenix): `564595d0` -> `17090d10`

---

flake.lock

| [`3bfaacf4`](https://github.com/nix-community/home-manager/commit/3bfaacf46133c037bb356193bd2f1765d9dc82c1) | `` direnv: Make lines shorter ``                           |
| [`bc52cdd5`](https://github.com/nix-community/home-manager/commit/bc52cdd5795e60850e860b5ccce7e8b9537d86f9) | `` direnv: Use ${getExe pkg} instead of ${pkg}/bin/pkg ``  |
| [`67c4c05c`](https://github.com/nix-community/home-manager/commit/67c4c05c29d2bd72cef7376c38351cb30af4d708 …

chore(flake/home-manager): `433120e4` -> `3bfaacf4`

---

flake.lock

| [`8b797c8e`](https://github.com/nix-community/home-manager/commit/8b797c8eea1eba7dfb47f6964103e6e0d134255f) | `` fish: escape abbr expansions once again ``         |
| [`b897544a`](https://github.com/nix-community/home-manager/commit/b897544a798d487044d7356ff4cf6d4748ac231a) | `` direnv: Fix nushell integration ENV_CONVERSIONS `` |

chore(flake/home-manager): `3bfaacf4` -> `8b797c8e`

---

flake.lock

| [`fb5ac0c8`](https://github.com/nix-community/home-manager/commit/fb5ac0c870a1b3ffea70e02ab1720d991ce812ae) | `` nix-index: use interactive shell init for Fish `` |
| [`19a78437`](https://github.com/nix-community/home-manager/commit/19a784373439032363daeba0a991e5e59bbad178) | `` zoxide: use interactive shell init for Fish ``    |

chore(flake/home-manager): `8b797c8e` -> `fb5ac0c8`

---

flake.lock

| Commit                                                                                         | Message                                              |
| ---------------------------------------------------------------------------------------------- | ---------------------------------------------------- |
| [`08dc5068`](https://github.com/ryantm/agenix/commit/08dc5068e6b5f8c985dba6490c219ea439f48ac1) | `` Revert "contrib: add direct tests for agenix " `` |

chore(flake/agenix): `17090d10` -> `d0d4ad5b`

---

flake.lock

| [`07c322a7`](https://github.com/nix-community/home-manager/commit/07c322a7cff03267fd881adae1afe63367c5d608) | `` aerc-accounts: support for maildirpp (#4653) `` |

chore(flake/home-manager): `fb5ac0c8` -> `07c322a7`

---

flake.lock

| [`f81fbc2b`](https://github.com/LnL7/nix-darwin/commit/f81fbc2bf78af3384dc435fdfb2e87c3a01ca047) | `` darwin-rebuild: fix sudo invocation on High Sierra `` |

chore(flake/darwin): `4b9b83d5` -> `010a625b`

---

flake.lock

| Commit                                                                                        | Message                            |
| --------------------------------------------------------------------------------------------- | ---------------------------------- |
| [`ecbbe933`](https://github.com/danth/stylix/commit/ecbbe933a97217b8211408a81a6c7a35db80633a) | `` Improve KDE theme :lipstick: `` |

chore(flake/stylix): `d14ac491` -> `ecbbe933`

---

flake.lock

| [`96f0794d`](https://github.com/danth/stylix/commit/96f0794dbd4b2ea499fe3c496a8e659bd4ffd68a) | `` Apply cursor theme to KDE :sparkles: `` |

chore(flake/stylix): `ecbbe933` -> `96f0794d`

---

flake.lock

| [`7184dfe6`](https://github.com/nix-community/home-manager/commit/7184dfe663ec35629802ed2a739147989173422a) | `` firefox: update docs example for nativeMessagingHosts `` |

chore(flake/home-manager): `07c322a7` -> `7184dfe6`

---

flake.lock

| [`de913414`](https://github.com/nix-community/home-manager/commit/de9134144b456104953c2533debb27a02787891f) | `` unison: better retry/restart reporting failures `` |

chore(flake/home-manager): `7184dfe6` -> `de913414`

---

flake.lock

| [`a2523ea0`](https://github.com/nix-community/home-manager/commit/a2523ea0343b056ba240abbac90ab5f116a7aa7b) | `` gpg-agent: add nushell integration `` |

chore(flake/home-manager): `de913414` -> `a2523ea0`

---

flake.lock

| Commit                                                                                         | Message                                        |
| ---------------------------------------------------------------------------------------------- | ---------------------------------------------- |
| [`6ce42cc7`](https://github.com/ryantm/agenix/commit/6ce42cc7684cb59b3a9390256f68909d7dfb9af0) | `` Fix CI for darwin ``                        |
| [`23d4d5d2`](https://github.com/ryantm/agenix/commit/23d4d5d29193a5ab1b1514375d578209a6119392) | `` maybe this fixes darwin checks? ``          |
| [`b6aa6180`](https://github.com/ryantm/agenix/commit/b6aa6180dbfc8a5df9296db264c01b49eb173f4c) | `` test removing installer ``                  |
| …

chore(flake/agenix): `d0d4ad5b` -> `457669db`

---

flake.lock

| [`1d4d588a`](https://github.com/nix-community/nix-index-database/commit/1d4d588a4671d08d25fb1f5f509d3eb24fceb074) | `` flake.lock: Update `` |

chore(flake/nix-index-database): `4605ccd7` -> `1d4d588a`

---

flake.lock

| [`6df37dc6`](https://github.com/NixOS/nixpkgs/commit/6df37dc6a77654682fe9f071c62b4242b5342e04) | `` vimPlugins.guard-nvim: init at 2023-11-27 ``                                   |
| [`d09d2d6a`](https://github.com/NixOS/nixpkgs/commit/d09d2d6a7a2fdfc3d39e5bcfe3dcbbd322597fd8) | `` vimPlugins.guard-collection: init at 2023-11-13 ``                             |
| [`6ee48dce`](https://github.com/NixOS/nixpkgs/commit/6ee48dcedd948 …

chore(flake/nixpkgs): `bc3575c6` -> `6df37dc6`

---

flake.lock

| [`f4340c1a`](https://github.com/nix-community/nix-index-database/commit/f4340c1a42c38d79293ba69bfd839fbd6268a538) | `` update packages.nix to release 2023-12-24-030633 `` |

chore(flake/nix-index-database): `1d4d588a` -> `f4340c1a`

---

flake.lock

| [`850eabce`](https://github.com/LnL7/nix-darwin/commit/850eabce441b39375cafb07fb779a8c0fa263bdd) | `` etc: add known hash for `/etc/shells` `` |

chore(flake/darwin): `010a625b` -> `f454cff5`

---

flake.lock

| Commit                                                                                                       | Message                  |
| ------------------------------------------------------------------------------------------------------------ | ------------------------ |
| [`88f314e1`](https://github.com/cachix/pre-commit-hooks.nix/commit/88f314e149eb5f65b161cd7d123fa4f624aa4121) | `` feat: add typstfmt `` |

chore(flake/pre-commit-hooks): `007a45d0` -> `7f35ec30`

---

flake.lock

| Commit                                                                                         | Message                                                       |
| ---------------------------------------------------------------------------------------------- | ------------------------------------------------------------- |
| [`a23aa271`](https://github.com/ryantm/agenix/commit/a23aa271bec82d3e962bafb994595c1c4a62b133) | `` dev: reland add direct tests for agenix ``                 |
| [`bc24f2e5`](https://github.com/ryantm/agenix/commit/bc24f2e510e045c70203cff80d34a8a024c38dec) | `` Revert "Revert "contrib: add direct tests for agenix "" `` |

chore(flake/agenix): `457669db` -> `417caa84`

---

flake.lock

| [`a1cbd987`](https://github.com/danth/stylix/commit/a1cbd98719daec528538d2b7d56279ddf68f90e6) | `` Configure KDE via a look and feel package :building_construction: `` |

chore(flake/stylix): `96f0794d` -> `a1cbd987`

---

flake.lock

| [`16fcb967`](https://github.com/nix-community/home-manager/commit/16fcb9674a71220313f91446e0c259bce5c20f0f) | `` home-environment: fix incompatible profile error `` |

chore(flake/home-manager): `a2523ea0` -> `16fcb967`

---

flake.lock

| [`d5a917ba`](https://github.com/nix-community/home-manager/commit/d5a917bab40daf4e5f82cd27162b8a6656d3beab) | `` Translate using Weblate (French) `` |

chore(flake/home-manager): `16fcb967` -> `d5a917ba`

---

flake.lock

| [`015a36e9`](https://github.com/nix-community/home-manager/commit/015a36e9c737d97356eb1627d4d7c7bd84976b85) | `` oh-my-posh: enable nushell integration `` |

chore(flake/home-manager): `d5a917ba` -> `015a36e9`

---

flake.lock

| Commit                                                                                        | Message                                                                |
| --------------------------------------------------------------------------------------------- | ---------------------------------------------------------------------- |
| [`7ccd1293`](https://github.com/danth/stylix/commit/7ccd1293a48f01eace7d0ce8d82af51919105b76) | `` Disable KDE behaviour which blocks Home Manager activation :bug: `` |

chore(flake/stylix): `a1cbd987` -> `7ccd1293`

---

flake.lock

| [`80679ea5`](https://github.com/nix-community/home-manager/commit/80679ea5074ab7190c4cce478c600057cfb5edae) | `` flake.lock: Update `` |

chore(flake/home-manager): `015a36e9` -> `80679ea5`

---

flake.lock

| Commit                                                                                                | Message                                                                                  |
| ----------------------------------------------------------------------------------------------------- | ---------------------------------------------------------------------------------------- |
| [`51c532cc`](https://github.com/NixOS/nixos-hardware/commit/51c532cc50e7960629c6e09ff7277441a01c236b) | `` Lenovo Legion 16achg6: Fix gpu configuration to work with both x11/wayland  (#802) `` |
| [`e4ded1ec`](https://github.com/NixOS/nixos-hardware/commit/e4ded1ec8e9c152910c2b077443e1d87cd81ad4a) | `` gpd-win-max-2-2023: init ``                                                           |

chore(flake/nixos-hardware): `7763c6fd` -> `51c532cc`

---

flake.lock

| [`05fc10e0`](https://github.com/NixOS/nixos-hardware/commit/05fc10e09377a5e28c54b723da8691daaf44b0b5) | `` add pyproject.toml for ruff lints ``    |
| [`e91914c6`](https://github.com/NixOS/nixos-hardware/commit/e91914c6cc8bfb3fb2a9bf6a95a0c62299672d4a) | `` apply ruff lints ``                     |
| [`453896ef`](https://github.com/NixOS/nixos-hardware/commit/453896efd821ef562793681568ac64caed3a3c8e) | `` tests/run.py: reformat with ruff ``     |
| …

chore(flake/nixos-hardware): `51c532cc` -> `05fc10e0`

---

flake.lock

| Commit                                                                                                | Message                                      |
| ----------------------------------------------------------------------------------------------------- | -------------------------------------------- |
| [`a15b6e52`](https://github.com/NixOS/nixos-hardware/commit/a15b6e525f5737a47b4ce28445c836996fb2ea8c) | `` apple-t2: avoid import-from-derivation `` |
| [`65753f5d`](https://github.com/NixOS/nixos-hardware/commit/65753f5d1144e3bf468a6bfe464011b12c840792) | `` speed up ci using nix-eval-jobs ``        |

chore(flake/nixos-hardware): `05fc10e0` -> `a15b6e52`

---

flake.lock

| Commit                                                                                                    | Message                                             |
| --------------------------------------------------------------------------------------------------------- | --------------------------------------------------- |
| [`872f9f3e`](https://github.com/nix-community/lanzaboote/commit/872f9f3ea8b2359e31efa5916dbb3b09d3cbf97c) | `` fix(deps): update rust crate anyhow to 1.0.76 `` |

chore(flake/lanzaboote): `9186a778` -> `47032189`

---

flake.lock

| [`8d16ac97`](https://github.com/nix-community/impermanence/commit/8d16ac97980b3641078dd7c11337bfaa77b45789) | `` lib: Remove sanitizeName, replace usage with escapeSystemdPath `` |

chore(flake/impermanence): `123e9420` -> `8d16ac97`

---

flake.lock

| [`3d599bd6`](https://github.com/nix-community/impermanence/commit/3d599bd65eb383bc36191ba39ed6084674b0d7b2) | `` Partial revert of 8d16ac97980b3641078dd7c11337bfaa77b45789 `` |

chore(flake/impermanence): `8d16ac97` -> `3d599bd6`

---

flake.lock

| [`4376b8a3`](https://github.com/Mic92/nix-fast-build/commit/4376b8a33b217ee2f78ba3dcff01a3e464d13a46) | `` fix missing awaits for AsyncExitStack `` |

chore(flake/nix-fast-build): `25e19950` -> `4376b8a3`

---

flake.lock

| [`9acb5b1a`](https://github.com/LnL7/nix-darwin/commit/9acb5b1adc50d29aa18dc4323bc4b63b05fdb59f) | `` Use native floats for mouse scaling `` |

chore(flake/darwin): `f454cff5` -> `8a832127`

---

flake.lock

| [`3175627f`](https://github.com/NixOS/nixpkgs/commit/3175627fb85400bcfadc3fa0167ce548b75affe3) | `` tun2socks: 2.5.1 -> 2.5.2 ``                                                        |
| [`2e9429a8`](https://github.com/NixOS/nixpkgs/commit/2e9429a8bf2f1e591ea2cc2e64569f9359006b5f) | `` trezor-suite: 23.10.1 -> 23.12.3 ``                                                 |
| …

chore(flake/nixpkgs): `6df37dc6` -> `5f64a12a`

---

flake.lock

| [`d1d95084`](https://github.com/nix-community/home-manager/commit/d1d950841d230490f308f5fcf8c0d4f2bd3f24a7) | `` gh: include version in settings `` |

chore(flake/home-manager): `80679ea5` -> `d1d95084`

---

flake.lock

| [`2939d490`](https://github.com/nix-community/home-manager/commit/2939d490366251d9ed5a0bd938275c590a1d6fa6) | `` gh: test for existence of hosts file `` |

chore(flake/home-manager): `d1d95084` -> `2939d490`

---

flake.lock

| [`45854459`](https://github.com/nix-community/home-manager/commit/458544594ba7f0333cf5718045ee7a8eaf5de433) | `` gpg-agent: don't set a default for pinentry `` |

chore(flake/home-manager): `2939d490` -> `45854459`

---

flake.lock

| [`c24c2985`](https://github.com/nix-community/home-manager/commit/c24c298562fe41b39909f632c5a7151bbf6b4628) | `` zsh.prezto: fix path in example for 'pmoduleDirs' `` |
| [`0f11c140`](https://github.com/nix-community/home-manager/commit/0f11c140657cc1d78febec4d6aca3836422600d2) | `` osmscout-server: add module ``                       |

chore(flake/home-manager): `45854459` -> `c24c2985`

---

flake.lock

| [`9c3b6122`](https://github.com/danth/stylix/commit/9c3b61224afab35604508d063f6a27894bffc273) | `` Fix stylixLookAndFeel failing on non-NixOS :bug: `` |

chore(flake/stylix): `7ccd1293` -> `9c3b6122`

---

flake.lock

| [`6e2afa5c`](https://github.com/nix-community/home-manager/commit/6e2afa5c3b8bb17bdc7c1a5be896aed177449f59) | `` sftpman: add module `` |

chore(flake/home-manager): `c24c2985` -> `6e2afa5c`

---

flake.lock

| [`f8a4a5c1`](https://github.com/nix-community/home-manager/commit/f8a4a5c18f4fee53ac3016a52a97df2aaeede65b) | `` gh: idempotently consider existing symlinks `` |

chore(flake/home-manager): `6e2afa5c` -> `f8a4a5c1`

---

flake.lock

| [`ba6b7501`](https://github.com/nix-community/home-manager/commit/ba6b75011b44e85b1b755b6c423f85d0817645f7) | `` alacritty: make compatible with alacritty 0.13 `` |

chore(flake/home-manager): `f8a4a5c1` -> `ba6b7501`

---

flake.lock

| [`30f9cdd6`](https://github.com/nix-community/home-manager/commit/30f9cdd69d1486a3d5cddaaabef7288d8ed389ee) | `` oh-my-posh: fix test under Darwin `` |

chore(flake/home-manager): `ba6b7501` -> `30f9cdd6`

---

flake.lock

| [`77c698fa`](https://github.com/nix-community/home-manager/commit/77c698fa4b3081b6019ad77d1bfedf06dbbde0db) | `` zsh: add support for zproof `` |

chore(flake/home-manager): `30f9cdd6` -> `77c698fa`

---

flake.lock

| [`df7f29a2`](https://github.com/nix-community/home-manager/commit/df7f29a231a483c88cbd00608db99634f854a8e1) | `` zoxide: fix use with recent Nushell `` |

chore(flake/home-manager): `77c698fa` -> `df7f29a2`

---

flake.lock

| [`2aff324c`](https://github.com/nix-community/home-manager/commit/2aff324cf65f5f98f89d878c056b779466b17db8) | `` bemenu: add module ``               |
| [`c48ae40d`](https://github.com/nix-community/home-manager/commit/c48ae40dbbb9193b4766c020bca116e127455ab9) | `` Translate using Weblate (German) `` |

chore(flake/home-manager): `df7f29a2` -> `2aff324c`

---

flake.lock

| Commit                                                                                                | Message                                                                             |
| ----------------------------------------------------------------------------------------------------- | ----------------------------------------------------------------------------------- |
| [`9c3a4125`](https://github.com/NixOS/nixos-hardware/commit/9c3a41257898f632792a6f948d43a6123ae9a5f2) | `` framework/13-inch/13th: document on how to get the fingerprint sensor to work `` |

chore(flake/nixos-hardware): `1bace8ce` -> `9c3a4125`

---

flake.lock

| [`22ae59fe`](https://github.com/NixOS/nixos-hardware/commit/22ae59fec26591ef72ce4ccb5538c42c5f090fe3) | `` Update dell/xps/13-9310/default.nix `` |
| [`72fea207`](https://github.com/NixOS/nixos-hardware/commit/72fea2077cbd6febb1fa83b697d1ae4950bfc75d) | `` Update config for xps-13-9010 ``       |

chore(flake/nixos-hardware): `9c3a4125` -> `22ae59fe`

---

flake.lock

| Commit                                                                                        | Message                                     |
| --------------------------------------------------------------------------------------------- | ------------------------------------------- |
| [`5a7f3f15`](https://github.com/danth/stylix/commit/5a7f3f15ccc2a272e5873bb44fe378ab5d99e0ff) | `` Add guide for creating modules :memo: `` |
| [`5b18f2a3`](https://github.com/danth/stylix/commit/5b18f2a33b4ea3fcf0cdea15b70f03afaf8e0d52) | `` Add screenshot of KDE :memo: ``          |

chore(flake/stylix): `9c3b6122` -> `5a7f3f15`

---

flake.lock

| Commit                                                                                           | Message                                            |
| ------------------------------------------------------------------------------------------------ | -------------------------------------------------- |
| [`f6cf46f7`](https://github.com/LnL7/nix-darwin/commit/f6cf46f7bc02650fb027b4e997dfc1365f4c8ff9) | `` GlobalPreferences: fix mouse scaling example `` |

chore(flake/darwin): `8a832127` -> `0a3afdc6`

---

flake.lock

| [`6a9bfbfa`](https://github.com/NixOS/nixpkgs/commit/6a9bfbfa1001235034f486b52791830451bf0bf1) | `` spire: 1.8.3 -> 1.8.7 ``                                                 |
| [`2f8686ce`](https://github.com/NixOS/nixpkgs/commit/2f8686ce1767836793797f97a498c47383bd934a) | `` nixos/frigate: restart the service on failure ``                         |
| [`b3a184a4`](https://github.com/NixOS/nixpkgs/commit/b3a184a4aabf53ab3f408291a006b2e5835a4 …

chore(flake/nixpkgs): `5f64a12a` -> `cfc3698c`

---

flake.lock

| Commit                                                                                                       | Message                        |
| ------------------------------------------------------------------------------------------------------------ | ------------------------------ |
| [`dfb9eeec`](https://github.com/cachix/pre-commit-hooks.nix/commit/dfb9eeec99272fcb2776d39ac634275715bc1549) | `` feat: add juliaformatter `` |

chore(flake/pre-commit-hooks): `7f35ec30` -> `9d3d7e18`

---

flake.lock

| [`2b2e6047`](https://github.com/nix-community/nix-index-database/commit/2b2e6047a258a5522b2ec8e5e01107bea7ae2d0c) | `` flake.lock: Update `` |

chore(flake/nix-index-database): `f4340c1a` -> `2b2e6047`

---

flake.lock

| Commit                                                                                           | Message              |
| ------------------------------------------------------------------------------------------------ | -------------------- |
| [`59bef440`](https://github.com/LnL7/nix-darwin/commit/59bef44059fbd0b80aed887c26f4cf74e517244a) | `` Fix type error `` |

chore(flake/darwin): `0a3afdc6` -> `1a41453c`

---

flake.lock

| [`d6510ce1`](https://github.com/nix-community/nix-index-database/commit/d6510ce144f5da7dd9bac667ba3d5a4946c00d11) | `` update packages.nix to release 2023-12-31-030821 `` |

chore(flake/nix-index-database): `2b2e6047` -> `d6510ce1`

---

flake.lock

| [`316bc983`](https://github.com/NixOS/nixos-hardware/commit/316bc98323fe3a7e7f72dbbbe68dce0cce3d4984) | `` Add TUXEDO InfinityBook Pro 14 - Gen7 config ``               |
| [`062e4810`](https://github.com/NixOS/nixos-hardware/commit/062e4810d8bee4954d32cf78145602e5b66c8704) | `` starfive visionfive2: update u-boot to SDK version v5.10.3 `` |

chore(flake/nixos-hardware): `22ae59fe` -> `316bc983`

---

flake.lock

| [`f06edaf1`](https://github.com/nix-community/home-manager/commit/f06edaf18b119da7bb301eebbf87971bbb9fb162) | `` lorri: unbreak due to too tight sandboxing `` |
| [`b7ef79bc`](https://github.com/nix-community/home-manager/commit/b7ef79bcf47c002bd6ae81a52bd3f233297edbde) | `` Translate using Weblate (Ukrainian) ``        |

chore(flake/home-manager): `2e8634c2` -> `f06edaf1`

---

flake.lock

| [`6e91c5df`](https://github.com/nix-community/home-manager/commit/6e91c5df192395753d8e6d55a0352109cb559790) | `` i3blocks: added configuration module `` |

chore(flake/home-manager): `f06edaf1` -> `6e91c5df`

---

flake.lock

| Commit                                                                                                | Message                                                               |
| ----------------------------------------------------------------------------------------------------- | --------------------------------------------------------------------- |
| [`f752581d`](https://github.com/NixOS/nixos-hardware/commit/f752581d6723a10da7dfe843e917a3b5e4d8115a) | `` Added file for HP EliteBook 845 G8 and updated flake and README `` |

chore(flake/nixos-hardware): `316bc983` -> `f752581d`

---

flake.lock

| [`da90576a`](https://github.com/NixOS/nixpkgs/commit/da90576aace1c178811ec136607e595d4f39dbae) | `` nixos/lxd-agent: fix evaluation regression caused by nixos/nixpkgs#271326 ``                   |
| [`5b2eefcc`](https://github.com/NixOS/nixpkgs/commit/5b2eefcc03d53975afae837bf15d94f142b94d71) | `` far2l: 2.4.1 -> 2.5.3 ``                                                                       |
| …

chore(flake/nixpkgs): `cfc3698c` -> `b0d36bd0`

---

flake.lock

| Commit                                                                                                | Message                                                                            |
| ----------------------------------------------------------------------------------------------------- | ---------------------------------------------------------------------------------- |
| [`5bf829d7`](https://github.com/NixOS/nixos-hardware/commit/5bf829d72ccdc05be3343afd81bd922d5748ef4e) | `` Update lenovo/legion/16aph8/default.nix
``                                     |
| [`a5028e96`](https://github.com/NixOS/nixos-hardware/commit/a5028e96cc8cabb78ab58edc251e122e9ac7c7b2) | `` Small cleanup ``                                                                |
| …

chore(flake/nixos-hardware): `f752581d` -> `5bf829d7`

---

flake.lock

| Commit                                                                                                | Message                                                                     |
| ----------------------------------------------------------------------------------------------------- | --------------------------------------------------------------------------- |
| [`8e34f334`](https://github.com/NixOS/nixos-hardware/commit/8e34f33464d77bea2d5cf7dc1066647b1ad2b324) | `` starfive visionfive2: write u-boot.itb to mtd2 ``                        |
| [`dd78777e`](https://github.com/NixOS/nixos-hardware/commit/dd78777e1275a646a214e66f9b9157d304250030) | `` starfive visionfive2: rework firmware build/update scripts ``            |
| [`637fba09`](https://github.com/NixOS/nixos-hardware/commit/63 …

chore(flake/nixos-hardware): `5bf829d7` -> `8e34f334`

---

flake.lock

| [`4d8f9020`](https://github.com/nix-community/home-manager/commit/4d8f90205c6c90be2e81d94d0e5eedf71c1ba34e) | `` zsh: fix zprof typo `` |

chore(flake/home-manager): `6e91c5df` -> `4d8f9020`

---

flake.lock

| [`fcbc70a7`](https://github.com/nix-community/home-manager/commit/fcbc70a7ee064f2b65dc1fac1717ca2a9813bbe6) | `` xdg-portal: add new module ``    |
| [`992b38f2`](https://github.com/nix-community/home-manager/commit/992b38f29cd7e50d88a2ae069133750beda010a4) | `` yazi: fix nushell integration `` |
| [`f772334b`](https://github.com/nix-community/home-manager/commit/f772334b357440e93e4c8f137d40b135720e3c83) | `` flake.lock: Update ``            |

chore(flake/home-manager): `4d8f9020` -> `fcbc70a7`

---

flake.lock

| [`4a703f10`](https://github.com/NixOS/nixpkgs/commit/4a703f1081fdb3736d56f343c0f8689511cc56b3) | `` emacsPackages.codeium: init at 1.6.13 ``                                   |
| [`86530be0`](https://github.com/NixOS/nixpkgs/commit/86530be0e330944072493b275ec534e229d7d2e5) | `` python310Packages.apprise: 1.7.0 -> 1.7.1 ``                               |
| [`a8cdcb94`](https://github.com/NixOS/nixpkgs/commit/a8cdcb9427def647e707056002cf0 …

chore(flake/nixpkgs): `b0d36bd0` -> `bd645e86`

---

flake.lock

| [`c36cb65c`](https://github.com/nix-community/home-manager/commit/c36cb65c4a0ba17ab9262ab3c30920429348746c) | `` xplr: support multiple plugins in cfg.plugins `` |

chore(flake/home-manager): `fcbc70a7` -> `c36cb65c`

---

flake.lock

| [`26b8adb3`](https://github.com/nix-community/home-manager/commit/26b8adb300e50efceb51fff6859a1a6ba1ade4f7) | `` github: fix broken links `` |

chore(flake/home-manager): `c36cb65c` -> `26b8adb3`

---

flake.lock

| Commit                                                                                                | Message                                                                    |
| ----------------------------------------------------------------------------------------------------- | -------------------------------------------------------------------------- |
| [`03e00336`](https://github.com/NixOS/nixos-hardware/commit/03e00336034c75e67609e953ded47c23de7f90f7) | `` framework amd: add pkgs import ``                                       |
| [`3a6288ef`](https://github.com/NixOS/nixos-hardware/commit/3a6288ef8332ea79b618d40c7f113363286fc161) | `` framework amd: apply headset mic fix on older kernels ``                |
| [`50944cf0`](https://github.com/NixOS/nixos-hardware/commit/50944c …

chore(flake/nixos-hardware): `8e34f334` -> `03e00336`

---

flake.lock

| [`17238531`](https://github.com/NixOS/nixos-hardware/commit/172385318068519900a7d71c1024242fa6af75f0) | `` microchip icicle-kit: Fixes to kernel `` |

chore(flake/nixos-hardware): `03e00336` -> `17238531`

---

flake.lock

| [`5243a943`](https://github.com/nix-community/nix-index-database/commit/5243a943a37fa010e9d8f141c07a6870fde1060b) | `` flake.lock: Update `` |

chore(flake/nix-index-database): `d6510ce1` -> `5243a943`

---

flake.lock

| [`f46800ac`](https://github.com/nix-community/nix-index-database/commit/f46800ac5a6e9f892fe36e50821c5d85794ecc62) | `` update packages.nix to release 2024-01-07-030820 `` |

chore(flake/nix-index-database): `5243a943` -> `f46800ac`

---

flake.lock

| [`c478b3d5`](https://github.com/NixOS/nixos-hardware/commit/c478b3d56969006e015e55aaece4931f3600c1b2) | `` surface: remove linux 6.1 ``                        |
| [`34bcc25f`](https://github.com/NixOS/nixos-hardware/commit/34bcc25fcd921666c0de80a0753f8a4feef3e0fb) | `` surface: set default kernel to major version 6.6 `` |
| [`5a721ef5`](https://github.com/NixOS/nixos-hardware/commit/5a721ef5f1460d01aa1571fab7f62efa51abf135) | `` surface: linux 6.6.8 -> 6.6.10 `` …

chore(flake/nixos-hardware): `17238531` -> `c478b3d5`

---

flake.lock

| Commit                                                                                                       | Message          |
| ------------------------------------------------------------------------------------------------------------ | ---------------- |
| [`a44c73ba`](https://github.com/cachix/pre-commit-hooks.nix/commit/a44c73ba3e41ed048363c6aff972185a9c7b641e) | `` add cljfmt `` |

chore(flake/pre-commit-hooks): `9d3d7e18` -> `44493e2b`

---

flake.lock

| [`b67fc24e`](https://github.com/NixOS/nixpkgs/commit/b67fc24e4acf7189590d229c2f286896527f849e) | `` electron_28: 28.1.0 -> 28.1.1 ``                                              |
| [`093a19a0`](https://github.com/NixOS/nixpkgs/commit/093a19a07c42f8d90c1b91825f4e7235010c3035) | `` electron_27: 27.2.0 -> 27.2.1 ``                                              |
| [`01aef81d`](https://github.com/NixOS/nixpkgs/commit/01aef81d1bee5ef14 …

chore(flake/nixpkgs): `bd645e86` -> `46ae0210`

---

flake.lock

| Commit                                                                                                       | Message                                                                      |
| ------------------------------------------------------------------------------------------------------------ | ---------------------------------------------------------------------------- |
| [`1a76afaf`](https://github.com/cachix/pre-commit-hooks.nix/commit/1a76afaf33ac9b1089a153ba1b3ff8cf5c8f918c) | `` fix(modules/hooks): 'settings.typos.exclude' implies '--force-exclude' `` |

chore(flake/pre-commit-hooks): `44493e2b` -> `ea07fa07`

---

flake.lock

| Commit                                                                                                       | Message                      |
| ------------------------------------------------------------------------------------------------------------ | ---------------------------- |
| [`132ffd57`](https://github.com/cachix/pre-commit-hooks.nix/commit/132ffd57209171cdca31916f47cfebe7584cdcad) | `` doc: improve README.md `` |

chore(flake/pre-commit-hooks): `ea07fa07` -> `ea96f0c0`

---

flake.lock

| [`b34a6075`](https://github.com/NixOS/nixos-hardware/commit/b34a6075e9e298c4124e35c3ccaf2210c1f3a43b) | `` xps-15-9560: disable broken bumblebee for now ``        |
| [`fe76fc35`](https://github.com/NixOS/nixos-hardware/commit/fe76fc35f7e4900718be13d15e3370a50b0fc79a) | `` framework amd: only apply suspend workaround on <6.7 `` |

chore(flake/nixos-hardware): `c478b3d5` -> `b34a6075`

---

flake.lock

| Commit                                                                                                       | Message                                                     |
| ------------------------------------------------------------------------------------------------------------ | ----------------------------------------------------------- |
| [`fbc317bf`](https://github.com/cachix/pre-commit-hooks.nix/commit/fbc317bff97af4dc4c9b98b92c1679c125473300) | `` hooks: flake8: add settings to extend the ignore list `` |
| [`911536a7`](https://github.com/cachix/pre-commit-hooks.nix/commit/911536a7bae59e7dd9169133d4eaf25d97d6c83b) | `` hooks: sort hooks alphabetically ``                      |
| [`4cb6caa8`](https://github.com/cachix/pre-commit-hooks.nix/commit/4cb6caa8db49fc54de99592362c0d63 …

chore(flake/pre-commit-hooks): `ea96f0c0` -> `b0265634`

---

flake.lock

| Commit                                                                                              | Message                                      |
| --------------------------------------------------------------------------------------------------- | -------------------------------------------- |
| [`3f919119`](https://github.com/serokell/deploy-rs/commit/3f91911972d4b1576b23e42feec9804bdcfb7fe0) | `` Remove note about unstable nix version `` |

chore(flake/deploy-rs): `b709d63d` -> `1776009f`

---

flake.lock

| [`e6ba94f1`](https://github.com/NixOS/nixpkgs/commit/e6ba94f191c169b0ed198353121e55bdcba8e41f) | `` pdal: add pkg-config and version tests ``                                      |
| [`51ae8643`](https://github.com/NixOS/nixpkgs/commit/51ae8643e49278898a4a82788b723950587d462e) | `` pdal: alphabetical re-ordering of dependencies ``                              |
| [`c6e8d2b3`](https://github.com/NixOS/nixpkgs/commit/c6e8d2b31ed1a …

chore(flake/nixpkgs): `46ae0210` -> `317484b1`

---

flake.lock

| [`93e804e7`](https://github.com/nix-community/home-manager/commit/93e804e7f8a1eb88bde6117cd5046501e66aa4bd) | `` docs: use alternative source of nmd `` |

chore(flake/home-manager): `e13aa9e2` -> `93e804e7`

---

flake.lock

| Commit                                                                                                   | Message                                                                         |
| -------------------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------- |
| [`528a7d0c`](https://github.com/hercules-ci/flake-parts/commit/528a7d0cb9668fb633d0ce39fb2255c94e4f8250) | `` transposition: Explain incomplete usage of transposition ``                  |
| [`3a0408e3`](https://github.com/hercules-ci/flake-parts/commit/3a0408e3acf785354d8a9b4074b9d4dbb0a12852) | `` perSystem: Check that inputs'.<name> is a flake, for better error message `` |
| …

chore(flake/flake-parts): `88a2cd81` -> `07f63952`

---

flake.lock

| Commit                                                                                                       | Message                           |
| ------------------------------------------------------------------------------------------------------------ | --------------------------------- |
| [`b568e6d3`](https://github.com/cachix/pre-commit-hooks.nix/commit/b568e6d3b8866f1256977fa49fefd12c4a806e86) | `` typos: unset pass_filenames `` |

chore(flake/pre-commit-hooks): `b0265634` -> `769a234f`

---

flake.lock

| Commit                                                                                                       | Message                         |
| ------------------------------------------------------------------------------------------------------------ | ------------------------------- |
| [`02a45958`](https://github.com/cachix/pre-commit-hooks.nix/commit/02a459585885f57c3fd93bb4e0b9b573a62a1ee5) | `` Add args to prettier hook `` |

chore(flake/pre-commit-hooks): `769a234f` -> `54d60d19`

---

flake.lock

| [`0912d26b`](https://github.com/nix-community/home-manager/commit/0912d26b30332ae6a90e1b321ff88e80492127dd) | `` gh: only run migration when required `` |
| [`7403ed49`](https://github.com/nix-community/home-manager/commit/7403ed49801e1a30ed0ffdec5b60c17f0cbf7bd5) | `` home-manager: internalize uninstall ``  |

chore(flake/home-manager): `93e804e7` -> `0912d26b`

---

flake.lock

| [`6217b735`](https://github.com/nix-community/home-manager/commit/6217b735988ef28fa07d9c4be92d06d5573defa3) | `` listenbrainz-mpd: use sdnotify when possible `` |

chore(flake/home-manager): `0912d26b` -> `6217b735`

---

flake.lock

| [`f2942f33`](https://github.com/nix-community/home-manager/commit/f2942f3385f1b35cc8a1abb03a45e29c9cb4d3c8) | `` Remove some formatting exceptions `` |

chore(flake/home-manager): `6217b735` -> `f2942f33`

---

flake.lock

| [`ef811636`](https://github.com/NixOS/nixos-hardware/commit/ef811636cc847355688804593282078bac7758d4) | `` Add fwupd to Dell XPS 13 7390 config `` |

chore(flake/nixos-hardware): `b34a6075` -> `ef811636`

---

flake.lock

| [`eea599cf`](https://github.com/nix-community/nix-index-database/commit/eea599cf923f54149ee7e58d8787d24092a10d21) | `` flake.lock: Update `` |

chore(flake/nix-index-database): `f46800ac` -> `eea599cf`

---

flake.lock

| Commit                                                                                         | Message                                                           |
| ---------------------------------------------------------------------------------------------- | ----------------------------------------------------------------- |
| [`2de745f1`](https://github.com/NixOS/nixpkgs/commit/2de745f11dbc413e747d5c2f41445db4d282e9a1) | `` mesa: 23.3.2 -> 23.3.3 ``                                      |
| [`13a6f426`](https://github.com/NixOS/nixpkgs/commit/13a6f4268742c16273ca8db92780a3fb504a4639) | `` virtualbox: fix build with libxml 2.12 + gcc 13 ``             |
| [`2c3dd4a4`](https://github.com/NixOS/nixpkgs/commit/2c3dd4a4f03ff284c0b5d3c5dc345d8ead745b1c) | `` mommy: 1.2.6 -> 1.3.0 `` …

chore(flake/nixpkgs): `317484b1` -> `9b19f5e7`

---

flake.lock

| [`274a40db`](https://github.com/nix-community/nix-index-database/commit/274a40dbf8be212697f3988471a4473987f8a886) | `` update packages.nix to release 2024-01-14-030810 `` |

chore(flake/nix-index-database): `eea599cf` -> `274a40db`

---

flake.lock

| Commit                                                                                                       | Message                                                                    |
| ------------------------------------------------------------------------------------------------------------ | -------------------------------------------------------------------------- |
| [`1e702924`](https://github.com/cachix/pre-commit-hooks.nix/commit/1e702924c524d782ddaf18551a0900eccaf6e804) | `` fix: add/fix all the missing hooks, for real this time ``               |
| [`05a6b4ce`](https://github.com/cachix/pre-commit-hooks.nix/commit/05a6b4ceef7f50d38c8295cad1c42deb06fef9d9) | `` feat: add check to ensure all hooks evaluate ``                         |
| …

chore(flake/pre-commit-hooks): `274ae397` -> `ffa9a5b9`

---

flake.lock

| Commit                                                                                                            | Message                                            |
| ----------------------------------------------------------------------------------------------------------------- | -------------------------------------------------- |
| [`49aaeecf`](https://github.com/nix-community/nix-index-database/commit/49aaeecf41ae0a0944e2c627cb515bcde428a1d1) | `` Bump cachix/install-nix-action from 24 to 25 `` |
| [`b211687b`](https://github.com/nix-community/nix-index-database/commit/b211687b4ff3a1e5f35bc545484db9d9ad866794) | `` Bump cachix/cachix-action from 13 to 14 ``      |

chore(flake/nix-index-database): `274a40db` -> `49aaeecf`

---

flake.lock

| [`a63273ff`](https://github.com/NixOS/nixos-hardware/commit/a63273ffc77532cc3cbc482ad5b4f9706e5289b6) | `` build(deps): bump cachix/install-nix-action from 24 to 25 `` |

chore(flake/nixos-hardware): `ef811636` -> `a63273ff`

---

flake.lock

| [`bee2202b`](https://github.com/NixOS/nixos-hardware/commit/bee2202bec57e521e3bd8acd526884b9767d7fa0) | `` Add support for Yoga Slim 7 Gen8 `` |

chore(flake/nixos-hardware): `a63273ff` -> `bee2202b`

---

flake.lock

| [`438cd262`](https://github.com/nix-community/lanzaboote/commit/438cd262e4111450c24c11eb64d99a636929c788) | `` chore(deps): update all dependencies `` |

chore(flake/lanzaboote): `11e29347` -> `e92070f3`

---

flake.lock

| [`78680cc5`](https://github.com/nix-community/lanzaboote/commit/78680cc51d81799bfd4a4bae818f509d7800764d) | `` chore(deps): lock file maintenance `` |
| [`e6df60de`](https://github.com/nix-community/lanzaboote/commit/e6df60debbf654307739e5bf0c6f1b20b9b9e36f) | `` make pre-commit-hooks-nix optional `` |

chore(flake/lanzaboote): `e92070f3` -> `be623b70`

---

flake.lock

| Commit                                                                                                    | Message                                                               |
| --------------------------------------------------------------------------------------------------------- | --------------------------------------------------------------------- |
| [`d7d63e6b`](https://github.com/nix-community/lanzaboote/commit/d7d63e6b6c58e14ddcab9eb9a26d0e2873f6ba87) | `` disable synthesis test on aarch64-linux ``                         |
| [`65330d81`](https://github.com/nix-community/lanzaboote/commit/65330d8172799ba0baf8dcfc17adb81f795a7b97) | `` fix hardcoded efi arch in tests ``                                 |
| [`1d3f28ac`](https://github.com/nix-community/lanzaboote/commit/1d3f28 …

chore(flake/lanzaboote): `be623b70` -> `5667bbc1`

---

flake.lock

| Commit                                                                                           | Message                                                     |
| ------------------------------------------------------------------------------------------------ | ----------------------------------------------------------- |
| [`c4ea346d`](https://github.com/LnL7/nix-darwin/commit/c4ea346d0f74bfaaeb6a0afbc27bbdf5963a153b) | `` Dedupe the WorkingDirectory path of the linux-builder `` |

chore(flake/darwin): `0dd382b7` -> `44a6ec1f`

---

flake.lock

| Commit                                                                                        | Message                                   |
| --------------------------------------------------------------------------------------------- | ----------------------------------------- |
| [`4ea34521`](https://github.com/danth/stylix/commit/4ea345211ec19f1fd4d4cc7c966f2e105628bd8e) | `` Make VSCode settings strings (#218) `` |

chore(flake/stylix): `9bc1900b` -> `4ea34521`

---

flake.lock

| [`4051e302`](https://github.com/LnL7/nix-darwin/commit/4051e3027dd0235eadb66b5f59d397f6db06f5dc) | `` Add type definition on fonts.fontDir.enable `` |

chore(flake/darwin): `44a6ec1f` -> `74ab0227`

---

flake.lock

| Commit                                                                                         | Message                                                                                   |
| ---------------------------------------------------------------------------------------------- | ----------------------------------------------------------------------------------------- |
| [`d6e9e26d`](https://github.com/NixOS/nixpkgs/commit/d6e9e26d2351c4aa26adcd7ec96d2cbe9c7aaf0b) | `` ocamlPackages.js_of_ocaml: 5.5.2 -> 5.6.0 ``                                           |
| [`9b8cffeb`](https://github.com/NixOS/nixpkgs/commit/9b8cffeb6bb5a990381a204dfbd45b98671d981a) | `` python311Packages.agate: 1.7.1 -> 1.9.1 (#280993) ``                                   |
| …

chore(flake/nixpkgs): `9b19f5e7` -> `c3e128f3`

---

flake.lock

| Commit                                                                                        | Message                                                       |
| --------------------------------------------------------------------------------------------- | ------------------------------------------------------------- |
| [`2d59480b`](https://github.com/danth/stylix/commit/2d59480b4531ce8d062d20a42560a266cb42b9d0) | `` alacritty: Use TOML template for recent versions (#219) `` |

chore(flake/stylix): `4ea34521` -> `2d59480b`

---

flake.lock

| [`e862ac6b`](https://github.com/NixOS/nixpkgs/commit/e862ac6b5ca280d3e41db71467f129839e47ee45) | `` element-{web,desktop}: 1.11.53 -> 1.11.54 (#281458) ``                    |
| [`01acbe0f`](https://github.com/NixOS/nixpkgs/commit/01acbe0fba4d0c5fb52fa6b86538750fa58e86fa) | `` libphonenumber: fix reproducible builds patch ``                          |
| [`c7f615d8`](https://github.com/NixOS/nixpkgs/commit/c7f615d8ab15c23961fd885123201f013 …

chore(flake/nixpkgs): `c3e128f3` -> `842d9d80`

---

flake.lock

| [`2064348e`](https://github.com/nix-community/home-manager/commit/2064348e555b6aa963da6372a8f14e6acb80a176) | `` hyprland: do not override existing plugins settings in config `` |
| [`d6185e83`](https://github.com/nix-community/home-manager/commit/d6185e83d864a4a73d5e6655ab7410c074c0657c) | `` docs, tests: revert to fetchTarball for nmd and nmt ``           |
| [`b84191db`](https://github.com/nix-community/home-manager/commit/b841 …

chore(flake/home-manager): `f2942f33` -> `2064348e`

---

flake.lock

| [`a9e3ce06`](https://github.com/danth/stylix/commit/a9e3ce064a778b386fb88fb152c02ae95aa2cbd2) | `` qutebrowser: Fix font name and size handling (#221) `` |

chore(flake/stylix): `2d59480b` -> `a9e3ce06`

---

flake.lock

| [`ce4b88c4`](https://github.com/nix-community/home-manager/commit/ce4b88c465d928f4f8b75d0920f1788d5b65ca94) | `` mcfly: add mcfly-fzf integration `` |

chore(flake/home-manager): `2064348e` -> `ce4b88c4`

---

flake.lock

| Commit                                                                                                       | Message                                       |
| ------------------------------------------------------------------------------------------------------------ | --------------------------------------------- |
| [`35ba4e74`](https://github.com/cachix/pre-commit-hooks.nix/commit/35ba4e74d7ad7f3475a1484f3b993ff7a3336aef) | `` fix(stylua): add --respect-ignores flag `` |

chore(flake/pre-commit-hooks): `ffa9a5b9` -> `f56597d5`

---

core/nixos.nix
flake.lock

| [`a34af9a9`](https://github.com/NixOS/nixpkgs/commit/a34af9a9556e205fe0a72014a335b96037b41823) | `` image/repart: add version and compression options ``                                     |
| [`c9e73449`](https://github.com/NixOS/nixpkgs/commit/c9e73449508b9ded9f7fdc0c8a0f81717139a669) | `` Update systemd-boot.nix ``                                                               |
| …

chore(flake/nixpkgs): `842d9d80` -> `bbe7d8f8`

---

flake.lock

| [`f1d47fc2`](https://github.com/LnL7/nix-darwin/commit/f1d47fc2dd43166cd832cb618a43e575a3fe7d27) | `` fix: set shell for new users, and only known ones `` |
| [`888533c3`](https://github.com/LnL7/nix-darwin/commit/888533c35fb0b46a8b537528b9990ab838ee3efc) | `` fix: user shell path handling ``                     |
| [`5cec74da`](https://github.com/LnL7/nix-darwin/commit/5cec74dae1bf439a3d137152e77badc7214ddc7c) | `` fix shell escaping in networking config ``           |

chore(flake/darwin): `74ab0227` -> `3ac7acd3`

---

flake.lock

| [`9b378afa`](https://github.com/nix-community/home-manager/commit/9b378afae72cb07471e19aefc30e8e05ef2d7a61) | `` hyprland: change plugins settings generation `` |

chore(flake/home-manager): `ce4b88c4` -> `9b378afa`

---

flake.lock

| [`244811b8`](https://github.com/nix-community/nix-index-database/commit/244811b8aaf7bd25d7e48bb300daf07eca9a9c96) | `` flake.lock: Update `` |

chore(flake/nix-index-database): `49aaeecf` -> `244811b8`

---

flake.lock

| [`928f2528`](https://github.com/nix-community/home-manager/commit/928f2528f9ee952ba0a47bbb1ece8d93ed66e784) | `` mise: add module `` |

chore(flake/home-manager): `9b378afa` -> `928f2528`

---

flake.lock

| [`f8e04fbc`](https://github.com/nix-community/nix-index-database/commit/f8e04fbcebcc24cebc91989981bd45f69b963ed7) | `` update packages.nix to release 2024-01-21-030727 `` |

chore(flake/nix-index-database): `244811b8` -> `f8e04fbc`

---

flake.lock

| [`a3be68d1`](https://github.com/LnL7/nix-darwin/commit/a3be68d105ebb640f7dc4be615f84fe00288e5d3) | `` Add option to disable zsh global compinit `` |

chore(flake/darwin): `3ac7acd3` -> `91c19ab2`

---

flake.lock

| Commit                                                                                                    | Message                                              |
| --------------------------------------------------------------------------------------------------------- | ---------------------------------------------------- |
| [`8985428c`](https://github.com/nix-community/lanzaboote/commit/8985428c5b62f75b5072e332c398e0c13bdce69c) | `` readme: make upstreaming section more timeless `` |

chore(flake/lanzaboote): `5667bbc1` -> `44b88813`

---

flake.lock

| Commit                                                                                                    | Message                                     |
| --------------------------------------------------------------------------------------------------------- | ------------------------------------------- |
| [`234e4da1`](https://github.com/nix-community/lanzaboote/commit/234e4da1f35da45fcd91fe4c589edae88883da07) | `` rust-toolchain: 1.70 -> 1.75 ``          |
| [`50247a68`](https://github.com/nix-community/lanzaboote/commit/50247a6890a3e2f80f5474ba99b143c0dfb16083) | `` flake: remove custom sbctl from shell `` |

chore(flake/lanzaboote): `44b88813` -> `7b91a7a3`

---

flake.lock

| [`2d47379a`](https://github.com/nix-community/home-manager/commit/2d47379ad591bcb14ca95a90b6964b8305f6c913) | `` flake.lock: Update ``                   |
| [`4af6720f`](https://github.com/nix-community/home-manager/commit/4af6720fff6cdc6188ccd4533365a202f6adeccc) | `` k9s: fix unnecessary test dependency `` |
| [`020399c2`](https://github.com/nix-community/home-manager/commit/020399c287afa853136b8089c315e238bf4b161d) | `` k9s: v0.29/v0.30 compatibility ``       |
| …

chore(flake/home-manager): `928f2528` -> `2d47379a`

---

flake.lock

| Commit                                                                                           | Message                                                               |
| ------------------------------------------------------------------------------------------------ | --------------------------------------------------------------------- |
| [`6b27542e`](https://github.com/LnL7/nix-darwin/commit/6b27542e861291993ba16f353f9da76b5bc0aa78) | `` Allow launchd serivceConfig.LimitLoadToSessionType to be a list `` |

chore(flake/darwin): `91c19ab2` -> `1e706ef3`

---

flake.lock

| [`80c76445`](https://github.com/nix-community/lanzaboote/commit/80c76445824791f31838e2626c35f6b139ac8581) | `` chore(deps): lock file maintenance `` |

chore(flake/lanzaboote): `df553744` -> `3c3f6d1b`

---

flake.lock

| Commit                                                                                         | Message                                                                                                |
| ---------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------------------------ |
| [`f3b08ca5`](https://github.com/NixOS/nixpkgs/commit/f3b08ca5a6be42e01f668a9f6224f403ccb08bb6) | `` nixos/clamav: fix network-online requires assert ``                                                 |
| [`e3839f3e`](https://github.com/NixOS/nixpkgs/commit/e3839f3e9042ef541ac713cd79d1c3eb359be1c4) | `` rye: 0.18.0 -> 0.19.0 `` …

chore(flake/nixpkgs): `bbe7d8f8` -> `612f9723`

---

flake.lock

| [`3df2a80f`](https://github.com/nix-community/home-manager/commit/3df2a80f3f85f91ea06e5e91071fa74ba92e5084) | `` zoxide: fix nushell 0.89 deprecation `` |
| [`3d0dc78e`](https://github.com/nix-community/home-manager/commit/3d0dc78e80031731240c979d87eed8e090d35439) | `` bemenu: allow floats in settings ``     |

chore(flake/home-manager): `2d47379a` -> `3df2a80f`

---

flake.lock

| Commit                                                                                        | Message                                           |
| --------------------------------------------------------------------------------------------- | ------------------------------------------------- |
| [`423c819d`](https://github.com/danth/stylix/commit/423c819d7702a78c52a80df7721d6c04bcbf2eab) | `` bemenu: move over to upstream module (#206) `` |
| [`bf31640f`](https://github.com/danth/stylix/commit/bf31640f49cb115508c31bf3bd0b4b80bb8ab71d) | `` doc: specify commit message format ``          |

chore(flake/stylix): `a9e3ce06` -> `423c819d`

---

flake.lock

| [`6b28ab2d`](https://github.com/nix-community/home-manager/commit/6b28ab2d798c1c84e24053d95f4ee1dd9d81e2fb) | `` tealdeer: add cache update activation script `` |

chore(flake/home-manager): `3df2a80f` -> `6b28ab2d`

---

flake.lock

| [`ff16da3a`](https://github.com/NixOS/nixos-hardware/commit/ff16da3a6b77941830b1971ef7107a2e7d4da714) | `` starfive visionfive2: update u-boot to 2024.01 `` |

chore(flake/nixos-hardware): `bee2202b` -> `ff16da3a`

---

flake.lock

| [`abff72bb`](https://github.com/NixOS/nixos-hardware/commit/abff72bb97ac85cdd192f32aecbed914ead928db) | `` surface: linux 6.6.10 -> 6.6.13 `` |

chore(flake/nixos-hardware): `ff16da3a` -> `e756ff62`

---

flake.lock

| Commit                                                                                        | Message                                        |
| --------------------------------------------------------------------------------------------- | ---------------------------------------------- |
| [`81de262b`](https://github.com/danth/stylix/commit/81de262bf170ce4152950402e17eba1453a3ebfe) | `` rofi: allow theme customizability (#230) `` |
| [`606a7983`](https://github.com/danth/stylix/commit/606a7983a0199004bdbeab898472e2ffd963dde5) | `` doc: update 'base16.nix' URL (#227) ``      |

chore(flake/stylix): `423c819d` -> `81de262b`

---

flake.lock

| [`e8481103`](https://github.com/nix-community/home-manager/commit/e84811035d7c8ec79ed6c687a97e19e2a22123c1) | `` treewide: deprecate `VERBOSE_ECHO` ``                     |
| [`190c6f46`](https://github.com/nix-community/home-manager/commit/190c6f46090a62ad025828bd8e16799d8fcdab1e) | `` home-manager: avoid running empty `nix profile remove` `` |
| [`42567290`](https://github.com/nix-community/home-manager/commit/425672900691a16a897fc47b4d5c3013 …

chore(flake/home-manager): `6b28ab2d` -> `e8481103`

---

flake.lock

| [`6359d40f`](https://github.com/nix-community/home-manager/commit/6359d40f6ec0b72a38e02b333f343c3d4929ec10) | `` firefox: implement native messaging hosts `` |

chore(flake/home-manager): `e8481103` -> `6359d40f`

---

flake.lock

| [`70688f19`](https://github.com/nix-community/home-manager/commit/70688f195a294a09d31d6bfe339bb090d443e949) | `` keepassx: remove module `` |

chore(flake/home-manager): `6359d40f` -> `70688f19`

---

flake.lock

| [`c7ce343d`](https://github.com/nix-community/home-manager/commit/c7ce343d9bf1a329056a4dd5b32ea8cc43b55e15) | `` home-manager: add extendModules attribute `` |
| [`c82e52b0`](https://github.com/nix-community/home-manager/commit/c82e52b0d96eb9f1c8334add871dce8e837d043b) | `` flake.lock: Update ``                        |
| [`03958aff`](https://github.com/nix-community/home-manager/commit/03958aff4415a5278d0ea462db370e9d770e904e) | `` firefox: add default containers `` …

chore(flake/home-manager): `70688f19` -> `c7ce343d`

---

flake.lock

| Commit                                                                                                | Message                  |
| ----------------------------------------------------------------------------------------------------- | ------------------------ |
| [`e57f8c26`](https://github.com/NixOS/nixos-hardware/commit/e57f8c264a4b6c2c8fef65dcd1adc13237004901) | `` Update default.nix `` |
| [`6b5d311c`](https://github.com/NixOS/nixos-hardware/commit/6b5d311cb66a153bffbdf96d5e9b79f1c3656a2e) | `` Fix patches.nix ``    |

chore(flake/nixos-hardware): `e756ff62` -> `f84eaffc`

---

flake.lock

| Commit                                                                                        | Message                                           |
| --------------------------------------------------------------------------------------------- | ------------------------------------------------- |
| [`1a5dee19`](https://github.com/danth/stylix/commit/1a5dee1957dc45e125013ae3919ff284cfb83cdc) | `` treewide: remove tailing whitespaces (#228) `` |

chore(flake/stylix): `81de262b` -> `1a5dee19`

---

flake.lock

| [`b2f56952`](https://github.com/nix-community/home-manager/commit/b2f56952074cb46e93902ecaabfb04dd93733434) | `` network-manager-applet: add XDG data directory `` |
| [`690764d2`](https://github.com/nix-community/home-manager/commit/690764d2dcfccf01ddfc9f19220c88182339f40f) | `` firefox: Reimplement FF native messaging ``       |

chore(flake/home-manager): `c7ce343d` -> `b2f56952`

---

flake.lock

| Commit                                                                                           | Message                                                              |
| ------------------------------------------------------------------------------------------------ | -------------------------------------------------------------------- |
| [`3a9755f9`](https://github.com/LnL7/nix-darwin/commit/3a9755f98dfc0589890ea54a870d9475e10b064f) | `` Use nixpkgs generators.toPlist for launchd service generation. `` |

chore(flake/darwin): `1e706ef3` -> `0108864c`

---

flake.lock

| [`2c1a58ea`](https://github.com/nix-community/nix-index-database/commit/2c1a58ea29af0bd3da947c6bb3e7a7704a2f972b) | `` flake.lock: Update `` |

chore(flake/nix-index-database): `f8e04fbc` -> `2c1a58ea`

---

flake.lock

| [`c782f2a4`](https://github.com/nix-community/nix-index-database/commit/c782f2a4f6fc94311ab5ef31df2f1149a1856181) | `` update packages.nix to release 2024-01-28-030920 `` |

chore(flake/nix-index-database): `2c1a58ea` -> `c782f2a4`

---

flake.lock

| [`ebba24a6`](https://github.com/nix-community/home-manager/commit/ebba24a6fefa3d749291be7192ef817736a10bd1) | `` wob: add module ``                              |
| [`7a461c70`](https://github.com/nix-community/home-manager/commit/7a461c70ed20e7e4a2af1710fdfb89ec70473e47) | `` firefox: fix darwin NativeMessagingHostsPath `` |
| [`e5f2a059`](https://github.com/nix-community/home-manager/commit/e5f2a0590a9387e17e6433b280e45d14f82683b4) | `` flake.lock: Update …

chore(flake/home-manager): `b2f56952` -> `ebba24a6`

---

flake.lock

| Commit                                                                                        | Message                                        |
| --------------------------------------------------------------------------------------------- | ---------------------------------------------- |
| [`7a7c9001`](https://github.com/danth/stylix/commit/7a7c90015de7454060e103e94bb4e6010b5aa062) | `` k9s: use new name for skin option (#232) `` |

chore(flake/stylix): `1a5dee19` -> `7a7c9001`

---

flake.lock

| [`4d54c29b`](https://github.com/nix-community/home-manager/commit/4d54c29bce71f8c261513e0662cc573d30f3e33e) | `` home-manager: remove the export of `run` `` |

chore(flake/home-manager): `ebba24a6` -> `4d54c29b`

---

flake.lock

| [`492944b0`](https://github.com/LnL7/nix-darwin/commit/492944b0f2c539240dc99392eb07f9064cb93c93) | `` Update darwin-rebuild.zsh-completions ``           |
| [`0f0478ef`](https://github.com/LnL7/nix-darwin/commit/0f0478efa68e442dd46fc64d46889da7c0859ad5) | `` Add zsh completions to darwin-rebuld by default `` |

chore(flake/darwin): `0108864c` -> `00538eec`

---

flake.lock

| [`d634c3ab`](https://github.com/nix-community/home-manager/commit/d634c3abafa454551f2083b054cd95c3f287be61) | `` tealdeer: add option to toggle update on activation `` |

chore(flake/home-manager): `4d54c29b` -> `d634c3ab`

---

flake.lock

| [`b60b914a`](https://github.com/hercules-ci/flake-parts/commit/b60b914ac6f706bdb6e55c0eadeffa732a60bd16) | `` dev: Make the test slightly more sensible ``  |
| [`14114c56`](https://github.com/hercules-ci/flake-parts/commit/14114c563acab4cee2828aa8dad9036d617e1ea2) | `` templates: make flake-parts input explicit `` |

chore(flake/flake-parts): `bffc4be1` -> `60c61400`

---

flake.lock

| Commit                                                                                           | Message                                                        |
| ------------------------------------------------------------------------------------------------ | -------------------------------------------------------------- |
| [`30311b6f`](https://github.com/LnL7/nix-darwin/commit/30311b6f90b333fcef1967a5fd139340c301b6f0) | `` services/yabai: Remove --check-sa and --install-sa flags `` |

chore(flake/darwin): `00538eec` -> `91b9daf6`

---

flake.lock

| [`42d7e506`](https://github.com/NixOS/nixos-hardware/commit/42d7e506777436d5e98ca02bd4a5f2da451cf485) | `` starfive visionfive2: update kernel to 6.6.0 `` |

chore(flake/nixos-hardware): `f84eaffc` -> `42d7e506`

---

flake.lock

| [`2db6a2a4`](https://github.com/nix-community/home-manager/commit/2db6a2a42930ffff0ffd690dec3f2c0b6f4fe66d) | `` docs: add style sheets and `scrubDerivations` `` |

chore(flake/home-manager): `d634c3ab` -> `2db6a2a4`

---

flake.lock

| [`83ce5906`](https://github.com/NixOS/nixos-hardware/commit/83ce5906a5b9a798ef2e653ddc12491c1b9e9929) | `` ga401: disable hardware.nvidia.powerManagement.enable `` |
| [`80223acd`](https://github.com/NixOS/nixos-hardware/commit/80223acd7f2cfe4ea103bc7e0d671f8a23b35990) | `` ga401: enable nvidia.dynamicBoost ``                     |

chore(flake/nixos-hardware): `42d7e506` -> `83ce5906`

---

flake.lock

| [`cc65e276`](https://github.com/NixOS/nixos-hardware/commit/cc65e27670abccced5997d4a93c4c930aef6fd0b) | `` Better default for amdgpuBusId ``          |
| [`ed01236e`](https://github.com/NixOS/nixos-hardware/commit/ed01236ece433b5fe96ebd7fe104f18f790aa066) | `` 16ach6h: Comment out failing edid line ``  |
| [`07e43b05`](https://github.com/NixOS/nixos-hardware/commit/07e43b0530503b6034eb82f47bb9ae4af34f9f93) | `` 16ach6h: Fix X11 setup ``                  |
| …

chore(flake/nixos-hardware): `83ce5906` -> `cc65e276`

---

flake.lock

| [`ccca01b5`](https://github.com/danth/stylix/commit/ccca01b5b0393119822b1888cb7c68e294fc115b) | `` nushell: add Home Manager module (#235) `` |

chore(flake/stylix): `7a7c9001` -> `ccca01b5`

---

flake.lock

| [`4d53427b`](https://github.com/nix-community/home-manager/commit/4d53427bce7bf3d17e699252fd84dc7468afc46e) | `` xfconf: fix config loading `` |

chore(flake/home-manager): `2db6a2a4` -> `4d53427b`

---

flake.lock

| Commit                                                                                                | Message                                                                                                                               |
| ----------------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------------------------------------------------------- |
| [`88712a12`](https://github.com/NixOS/nixos-hardware/commit/88712a124b9a15e8b487d9bec9847ba0aa876d2c) | `` Pick a better name than "versionsOfOption" ``                                                                                      |
| [`85a2b554`](https://github.com/NixOS/nixos-hardware/commit/85a2b5542eed …

chore(flake/nixos-hardware): `cc65e276` -> `83e571bb`

---

flake.lock

| Commit                                                                                           | Message                          |
| ------------------------------------------------------------------------------------------------ | -------------------------------- |
| [`4363d3b4`](https://github.com/LnL7/nix-darwin/commit/4363d3b42f71156c5de80c3cf9ff998ff0a5681a) | `` services/yabai: Remove IFD `` |

chore(flake/darwin): `91b9daf6` -> `bdbae6ec`

---

flake.lock

| Commit                                                                                         | Message                                                                                                     |
| ---------------------------------------------------------------------------------------------- | ----------------------------------------------------------------------------------------------------------- |
| [`f125235a`](https://github.com/NixOS/nixpkgs/commit/f125235a38e49a152d5f45c08254b4cb2f325fd6) | `` root: 6.30.02 -> 6.30.04 (#285339) ``                                                                    |
| [`21570187`](https://github.com/NixOS/nixpkgs/commit/215701875d8468071fecfbca276ff5b757dcf297) | `` dex-oidc: Fix embedded version string, add test (#285104) `` …

chore(flake/nixpkgs): `612f9723` -> `b8b232ae`

---

flake.lock

| [`880d9bc2`](https://github.com/nix-community/home-manager/commit/880d9bc2110f7cae59698f715b8ca42cdc53670c) | `` nix: fix generation of nix.conf for nix >= 2.20 `` |

chore(flake/home-manager): `4d53427b` -> `880d9bc2`

---

flake.lock

| [`1ca21064`](https://github.com/nix-community/home-manager/commit/1ca210648a6ca9b957efde5da957f3de6b1f0c45) | `` tests: reduce closure sizes `` |

chore(flake/home-manager): `880d9bc2` -> `1ca21064`

---

flake.lock

| [`e260ddfd`](https://github.com/nix-community/nix-index-database/commit/e260ddfd7ab5d360172870b9dfb0fa15093cdb29) | `` flake.lock: Update `` |

chore(flake/nix-index-database): `c782f2a4` -> `e260ddfd`

---

flake.lock

| [`3e3dad28`](https://github.com/nix-community/nix-index-database/commit/3e3dad2808379c522138e2e8b0eb73500721a237) | `` update packages.nix to release 2024-02-04-030719 `` |

chore(flake/nix-index-database): `e260ddfd` -> `3e3dad28`

---

flake.lock

| [`230836bb`](https://github.com/nix-community/home-manager/commit/230836bb7ca318aec7bad8442954da611d06a172) | `` hyprland: fix hyprctl crash `` |

chore(flake/home-manager): `1ca21064` -> `230836bb`

---

flake.lock

| [`edb53211`](https://github.com/NixOS/nixpkgs/commit/edb53211cc68405d02999852d892968f1d46c5c9) | `` python311Packages.iminuit: 2.24.0 -> 2.25.0 ``                          |
| [`ca1262a4`](https://github.com/NixOS/nixpkgs/commit/ca1262a4832b290d9f35c4b9c5f67f93144c7f2a) | `` lib: Add optionalDrvAttr to conditionally set drv attributes. ``        |
| [`6da57d02`](https://github.com/NixOS/nixpkgs/commit/6da57d024e1700cc808fa748823ed2ddb9db0067) …

chore(flake/nixpkgs): `b8b232ae` -> `e92b6015`

---

flake.lock

| [`4ab01785`](https://github.com/nix-community/home-manager/commit/4ab01785b85aac4dd0f0414f7c0ca4c007e64054) | `` flake.lock: Update ``                |
| [`9291f28f`](https://github.com/nix-community/home-manager/commit/9291f28f93a818e4496a6f71f6c77f59108d4d46) | `` Translate using Weblate (Turkish) `` |

chore(flake/home-manager): `230836bb` -> `4ab01785`

---

flake.lock

| [`f80df90c`](https://github.com/nix-community/home-manager/commit/f80df90c105d081a49d123c34a57ead9dac615b9) | `` fish: implement shellInitLast (after others) `` |

chore(flake/home-manager): `4ab01785` -> `f80df90c`

---

flake.lock

| [`4740f2cc`](https://github.com/nix-community/home-manager/commit/4740f2ccda184e9cc509d7a82b26d7271e0c79d9) | `` kitty: always export `KITTY_SHELL_INTEGRATION` ``    |
| [`1683c507`](https://github.com/nix-community/home-manager/commit/1683c507c2c58a502294330de940e2b4b51bdf75) | `` vdirsyncer: create postHook script when non-empty `` |

chore(flake/home-manager): `f80df90c` -> `4740f2cc`

---

flake.lock

| [`afcedcf2`](https://github.com/nix-community/home-manager/commit/afcedcf2c8e424d0465e823cf833eb3adebe1db7) | `` mcfly: add interfaceView option `` |
| [`a28b12d7`](https://github.com/nix-community/home-manager/commit/a28b12d7412324aa22a5f9df8909672dec33613e) | `` vscode: add openvscode-server ``   |

chore(flake/home-manager): `4740f2cc` -> `afcedcf2`

---

flake.lock

| [`3c6f2dd5`](https://github.com/nix-community/home-manager/commit/3c6f2dd59cb8c0b06ed1fe01f297e75bbaec3003) | `` himalaya: adjust module for v1.0.0-beta `` |
| [`274bd470`](https://github.com/nix-community/home-manager/commit/274bd470a544647d90d7491037fdf8af61b7d8d0) | `` nix-gc: add service ``                     |

chore(flake/home-manager): `afcedcf2` -> `3c6f2dd5`

---

flake.lock

| [`f65dcd6c`](https://github.com/nix-community/home-manager/commit/f65dcd6c15db0fc2045d56ef8fdf4a03aa52e81f) | `` neomutt: fix crypt_use_gpgme in newer versions ``      |
| [`7b4ea8d8`](https://github.com/nix-community/home-manager/commit/7b4ea8d82fdeaa71ab942a8a8f6f8add8afdfad0) | `` arrpc: add module ``                                   |
| [`13dbf262`](https://github.com/nix-community/home-manager/commit/13dbf2623d6465d5c4db54ce8a5a630dce79c3e9) | …

chore(flake/home-manager): `3c6f2dd5` -> `f65dcd6c`

---

flake.lock

| [`f99eace7`](https://github.com/nix-community/home-manager/commit/f99eace7c167b8a6a0871849493b1c613d0f1b80) | `` jetbrains-remote: add module `` |

chore(flake/home-manager): `f65dcd6c` -> `f99eace7`

---

flake.lock

| [`8b0d333f`](https://github.com/NixOS/nixpkgs/commit/8b0d333f546d6247c0c846ffbc9f7e89b4d06022) | `` nixos/archisteamfarm: allow bots.*.passwordFile to be null (#284978) `` |
| [`eaefae19`](https://github.com/NixOS/nixpkgs/commit/eaefae19673e8737f55fa61544876d645847a854) | `` moonraker: unstable-2023-12-16 -> unstable-2023-12-27 (#277239) ``      |
| [`3b71558f`](https://github.com/NixOS/nixpkgs/commit/3b71558f3e2db297197bf6c8e7c8ac0b7e83a4b8) …

chore(flake/nixpkgs): `e92b6015` -> `faf912b0`

---

flake.lock

| [`a2d8d6b4`](https://github.com/danth/stylix/commit/a2d8d6b460bb6c53cb09ce645fd041c0c308c0c8) | `` treewide: remove runtime fetch operations (#224) `` |

chore(flake/stylix): `ccca01b5` -> `a2d8d6b4`

---

flake.lock

| Commit                                                                                        | Message                                                             |
| --------------------------------------------------------------------------------------------- | ------------------------------------------------------------------- |
| [`9942fca8`](https://github.com/danth/stylix/commit/9942fca8707efbd8c3f6108549f098462425d1b3) | `` qutebrowser: use correct `fonts.web.size.default` type (#239) `` |

chore(flake/stylix): `a2d8d6b4` -> `9942fca8`

---

flake.lock

| [`7e62834e`](https://github.com/danth/stylix/commit/7e62834e25dc114ed249655c4f673fe67617a4c1) | `` wezterm: flip active and inactive tab colors (#246) `` |

chore(flake/stylix): `9942fca8` -> `7e62834e`

---

flake.lock

| [`b17c41ca`](https://github.com/danth/stylix/commit/b17c41ca43866609579ea9c9ef96532d8854b85f) | `` stylix: reduce duplication (#245) `` |

chore(flake/stylix): `f3b302dd` -> `b17c41ca`

---

flake.lock

| [`4c0357ff`](https://github.com/nix-community/home-manager/commit/4c0357ff874f8250fcae621d5626aba1c7161710) | `` sway: fix workspace 10 missing from default config (#4636) `` |

chore(flake/home-manager): `5b9156fa` -> `4c0357ff`

---

flake.lock

| [`fb0196ad`](https://github.com/nix-community/home-manager/commit/fb0196ad9d18554e035de27d4f2a906ba050b407) | `` imapnotify: enable STARTTLS if enabled in email account config (#5013) `` |

chore(flake/home-manager): `4c0357ff` -> `fb0196ad`

---

flake.lock

| [`d1d6ca9b`](https://github.com/nix-community/home-manager/commit/d1d6ca9b6552fc93032b76661c83061f1cd4e6e8) | `` flake.lock: Update `` |

chore(flake/home-manager): `fb0196ad` -> `d1d6ca9b`

---

flake.lock

| [`bfd0ae29`](https://github.com/nix-community/home-manager/commit/bfd0ae29a86eff4603098683b516c67e22184511) | `` emacs: use `overrideScope` instead of `overrideScope'` `` |

chore(flake/home-manager): `d1d6ca9b` -> `bfd0ae29`

---

flake.lock

| [`2fc7cf56`](https://github.com/nix-community/nix-index-database/commit/2fc7cf56050f0d3e1f793cfee0f88f894870035e) | `` flake.lock: Update `` |

chore(flake/nix-index-database): `3e3dad28` -> `2fc7cf56`

---

flake.lock

| [`a09cfdba`](https://github.com/nix-community/home-manager/commit/a09cfdbaf11c821340cff24d9ad1c264708ee12e) | `` neomutt: Initial IMAP support (#4597) `` |

chore(flake/home-manager): `bfd0ae29` -> `a09cfdba`

---

flake.lock

| [`0cb43457`](https://github.com/nix-community/nix-index-database/commit/0cb4345704123492e6d1f1068629069413c80de0) | `` update packages.nix to release 2024-02-11-030837 `` |

chore(flake/nix-index-database): `2fc7cf56` -> `0cb43457`

---

flake.lock

| [`21b07830`](https://github.com/nix-community/home-manager/commit/21b078306a2ab68748abf72650db313d646cf2ca) | `` flake.lock: Update `` |

chore(flake/home-manager): `a09cfdba` -> `21b07830`

---

flake.lock

| Commit                                                                                        | Message                              |
| --------------------------------------------------------------------------------------------- | ------------------------------------ |
| [`aca2d28f`](https://github.com/danth/stylix/commit/aca2d28f08e71bdd14192c3b20fb4df768ae1240) | `` stylix: bump base16.nix (#256) `` |

chore(flake/stylix): `b17c41ca` -> `aca2d28f`

---

flake.lock

| [`26bc3272`](https://github.com/nix-community/lanzaboote/commit/26bc32726cfa84a2a1a2f6c5f6560d336434782e) | `` chore(deps): lock file maintenance `` |

chore(flake/lanzaboote): `d9ec678b` -> `71fb5122`

---

flake.lock

| Commit                                                                                        | Message                                                 |
| --------------------------------------------------------------------------------------------- | ------------------------------------------------------- |
| [`50cae37c`](https://github.com/danth/stylix/commit/50cae37cfe23e5ad202ed53f48529139dfa0d008) | `` gnome: rename `overrideScope'` to `overrideScope` `` |

chore(flake/stylix): `aca2d28f` -> `50cae37c`

---

flake.lock

| [`2b68ccd7`](https://github.com/NixOS/nixos-hardware/commit/2b68ccd7475362b8c8d6a1805b403033ba6273a8) | `` gpd-win-max-2-2023: enable iio subsystem ``                           |
| [`c1db24a1`](https://github.com/NixOS/nixos-hardware/commit/c1db24a14b17b49d0d57096831ed6b469ea2ab4a) | `` gpd-win-max-2-2023: init BMI260  driver ``                            |
| [`d1117dcf`](https://github.com/NixOS/nixos-hardware/commit/d1117dcf09907f …

chore(flake/nixos-hardware): `6e5cc385` -> `2b68ccd7`

---

flake.lock

| [`5de0b3e5`](https://github.com/nix-community/lanzaboote/commit/5de0b3e54a05aaf0faa3ab42fea5ac09008109aa) | `` stub: rename sections for UKI compatibility ``  |
| [`14afe7ce`](https://github.com/nix-community/lanzaboote/commit/14afe7ce9b71560e2edd26ac78bba32145c0b593) | `` tests: check whether our UKIs are recognized `` |

chore(flake/lanzaboote): `71fb5122` -> `96181a46`

---

flake.lock

| Commit                                                                                         | Message                            |
| ---------------------------------------------------------------------------------------------- | ---------------------------------- |
| [`1f62cef4`](https://github.com/ryantm/agenix/commit/1f62cef426d11795bdd588e507c2845df8434e32) | `` fix: update docs for 5c1198a `` |

chore(flake/agenix): `417caa84` -> `8cb01a0e`

---

flake.lock

| [`f1b2f71c`](https://github.com/NixOS/nixos-hardware/commit/f1b2f71c86a5b1941d20608db0b1e88a07d31303) | `` Update repository path for nxp/imx `` |

chore(flake/nixos-hardware): `2b68ccd7` -> `f1b2f71c`

---

flake.lock

| [`7cea566f`](https://github.com/NixOS/nixpkgs/commit/7cea566f2571fcec7d69c84e04d066ba809d730b) | `` home-assistant: pin python-slugify at 8.0.1 ``                            |
| [`9c164371`](https://github.com/NixOS/nixpkgs/commit/9c164371865549575c5ca3eb4454f477fed88d6a) | `` python311Packages.correctionlib: fix build ``                             |
| [`016be1d8`](https://github.com/NixOS/nixpkgs/commit/016be1d8b30166a4b4d8e2f6864f1575b …

chore(flake/nixpkgs): `f8e2ebd6` -> `f9d39fb9`

---

flake.lock

| [`043ba285`](https://github.com/nix-community/home-manager/commit/043ba285c6dc20f36441d48525402bcb9743c498) | `` tests: add basic integration tests ``                 |
| [`7889bfb4`](https://github.com/nix-community/home-manager/commit/7889bfb4752b27c83c8ae9ca45f63b77fff7ef7b) | `` home-manager: overrideable URLs in generated flake `` |
| [`354643e6`](https://github.com/nix-community/home-manager/commit/354643e6c1ce0762d498e5e676e7970922c89208) | `` …

chore(flake/home-manager): `21b07830` -> `043ba285`

---

flake.lock

| [`3b27f2ac`](https://github.com/NixOS/nixpkgs/commit/3b27f2ac6eba07a4c9bbbfb963fb020b25438bec) | `` xfitter: fix for recent clang (#288816) ``                                        |
| [`bc010914`](https://github.com/NixOS/nixpkgs/commit/bc010914b07ad0e5e25d4eecc1669c2565d63479) | `` elegant-sddm: init at unstable-2024-02-08 ``                                      |
| …

chore(flake/nixpkgs): `f9d39fb9` -> `a4d4fe8c`

---

flake.lock

| [`3d6791b3`](https://github.com/nix-community/home-manager/commit/3d6791b3897b526c82920a2ab5f61d71985b3cf8) | `` home-manager: add Nix sanity check ``      |
| [`07fd4117`](https://github.com/nix-community/home-manager/commit/07fd41171ff8f263a9e4a95e17a3db1ff8a000c9) | `` home-manager: fix incorrect log message `` |

chore(flake/home-manager): `043ba285` -> `3d6791b3`

---

flake.lock

| Commit                                                                                              | Message                                          |
| --------------------------------------------------------------------------------------------------- | ------------------------------------------------ |
| [`5f694ef4`](https://github.com/serokell/deploy-rs/commit/5f694ef481610e8c4c77bb963b49e2d3b0d4db3c) | `` add support for entering password for sudo `` |

chore(flake/deploy-rs): `1776009f` -> `0a018779`

---

flake.lock

| Commit                                                                                         | Message                                                                                                           |
| ---------------------------------------------------------------------------------------------- | ----------------------------------------------------------------------------------------------------------------- |
| [`bcd1f4cd`](https://github.com/NixOS/nixpkgs/commit/bcd1f4cd63c9cf51cddeea8e79bb4a6413320a89) | `` seclists: 2023.4 -> 2024.1 ``                                                                                  |
| [`eb6f5177`](https://github.com/NixOS/nixpkgs/commit/eb6f517764dd57e5750ca969f9f8c084a94191af) | `` b4: 0.12.4 -> 0.13.0 `` …

chore(flake/nixpkgs): `a4d4fe8c` -> `5863c273`

---

flake.lock

| [`c52e2960`](https://github.com/nix-community/nix-index-database/commit/c52e2960c521613ba8ca180f476ea064e47db48e) | `` flake.lock: Update `` |

chore(flake/nix-index-database): `0cb43457` -> `c52e2960`

---

flake.lock

| [`17352eb2`](https://github.com/nix-community/nix-index-database/commit/17352eb241a8d158c4ac523b19d8d2a6c8efe127) | `` update packages.nix to release 2024-02-18-030707 `` |

chore(flake/nix-index-database): `c52e2960` -> `17352eb2`

---

flake.lock

| [`11edf9ca`](https://github.com/nix-community/home-manager/commit/11edf9cad78cce49d09436c8d725ae36b65671dc) | `` flake.lock: Update ``                  |
| [`309465d2`](https://github.com/nix-community/home-manager/commit/309465d20993095a1c6ee2d7eda6ef3588f165ff) | `` Translate using Weblate (Ukrainian) `` |
| [`7671ec19`](https://github.com/nix-community/home-manager/commit/7671ec1931daee86161c8da1115515447667545e) | `` Translate using Weblate (Swedish) ``   |
| …

chore(flake/home-manager): `3d6791b3` -> `11edf9ca`

---

flake.lock

| [`a54e05bc`](https://github.com/nix-community/home-manager/commit/a54e05bc12d88ff2df941d0dc1183cb5235fa438) | `` tealdeer: module improvements ``             |
| [`738527f8`](https://github.com/nix-community/home-manager/commit/738527f866e7848fa9fcef174ee78ec262fd00e5) | `` darwin: fonts: speed up font installation `` |

chore(flake/home-manager): `11edf9ca` -> `a54e05bc`

---

flake.lock

| [`6cfed923`](https://github.com/nix-community/lanzaboote/commit/6cfed923dbc398bccf5dbeb70fbcb80876975f46) | `` chore(deps): lock file maintenance `` |

chore(flake/lanzaboote): `098f0194` -> `470ba03c`

---

flake.lock

| [`70adeec2`](https://github.com/NixOS/nixpkgs/commit/70adeec24f6686fdbbba17d5d79a290b427367c2) | `` plots: refactor ``                                                                       |
| [`8ac91490`](https://github.com/NixOS/nixpkgs/commit/8ac914904ebe68d0f6be4ac2bc60165afc46979b) | `` pdfid: init at 0.2.8 ``                                                                  |
| …

chore(flake/nixpkgs): `5863c273` -> `b98a4e17`

---

flake.lock
nix/overlays/imv-no-freeimage.nix

| [`c82d4213`](https://github.com/NixOS/nixpkgs/commit/c82d4213f76cfe68c6b1de43f560e362a7a86ad1) | `` python311Packages.langchain: 0.1.6 -> 0.1.8 ``                                 |
| [`74214026`](https://github.com/NixOS/nixpkgs/commit/742140265720b43e39af6aea3c3730f5840b430a) | `` python311Packages.langchain-community: 0.0.19 -> 0.0.21 ``                     |
| [`339deb3b`](https://github.com/NixOS/nixpkgs/commit/339deb3b56295 …

chore(flake/nixpkgs): `b98a4e17` -> `0e74ca98`

---

flake.lock

| [`0b69d574`](https://github.com/nix-community/home-manager/commit/0b69d574162cfa6eb7919d5614a48d0185550891) | `` Translate using Weblate (Spanish) `` |
| [`3dda8e79`](https://github.com/nix-community/home-manager/commit/3dda8e795f12a4f67c287cef155939e1c5fbd0a3) | `` river: add module ``                 |

chore(flake/home-manager): `517601b3` -> `0b69d574`

---

flake.lock

| [`3f7d0bca`](https://github.com/NixOS/nixos-hardware/commit/3f7d0bca003eac1a1a7f4659bbab9c8f8c2a0958) | `` Add links to FA507RM ``                 |
| [`27cca741`](https://github.com/NixOS/nixos-hardware/commit/27cca741bf6c532ea9ba394be806b04cbcbaefa1) | `` Add files for Asus TUF A15 (FA507RM) `` |
| [`3610be0d`](https://github.com/NixOS/nixos-hardware/commit/3610be0dca3a3f46224af37eca0a655688d080be) | `` Import Intel GPU module ``              |

chore(flake/nixos-hardware): `106d3fec` -> `3f7d0bca`

---

flake.lock

| [`0e0e9669`](https://github.com/nix-community/home-manager/commit/0e0e9669547e45ea6cca2de4044c1a384fd0fe55) | `` zsh: fix broken ZDOTDIR when path contains spaces `` |

chore(flake/home-manager): `0b69d574` -> `0e0e9669`

---

flake.lock

| Commit                                                                                        | Message                     |
| --------------------------------------------------------------------------------------------- | --------------------------- |
| [`a38d900d`](https://github.com/danth/stylix/commit/a38d900ddf2c65658cd242afdee90c3ec2d6b810) | `` mangohud: init (#260) `` |

chore(flake/stylix): `50cae37c` -> `a38d900d`

---

flake.lock

| Commit                                                                                        | Message                 |
| --------------------------------------------------------------------------------------------- | ----------------------- |
| [`32fe070b`](https://github.com/danth/stylix/commit/32fe070be53d7d6891e21dcb2b1ebbfe45c3cf1e) | `` btop: init (#259) `` |

chore(flake/stylix): `a38d900d` -> `32fe070b`

---

flake.lock

| [`f4e2bea8`](https://github.com/NixOS/nixpkgs/commit/f4e2bea85e4e4ae057f2aa786e18a932a2b0b658) | `` python311Packages.mplhep: 0.3.33 -> 0.3.34 ``                            |
| [`6ef28826`](https://github.com/NixOS/nixpkgs/commit/6ef28826d81340f19b8a97b4fa3f46504bdcad6f) | `` abcmidi: 2024.02.11 -> 2024.02.19 ``                                     |
| [`6add9650`](https://github.com/NixOS/nixpkgs/commit/6add9650436e4976300c2a57ce5c290b798b1 …

chore(flake/nixpkgs): `0e74ca98` -> `cbc4211f`

---

flake.lock

| [`4e6d25a5`](https://github.com/nix-community/home-manager/commit/4e6d25a51bb3035af7db54cc8f7fcac23e9467dc) | `` lorri: systemd allow access to cache directories `` |

chore(flake/home-manager): `0e0e9669` -> `4e6d25a5`

---

flake.lock

| [`9a452c30`](https://github.com/NixOS/nixpkgs/commit/9a452c304c0d621f584daeb324593c3d59236a71) | `` obs-studio-plugins.obs-vertical-canvas: 1.4.0 -> 1.4.1 ``               |
| [`c37cffdd`](https://github.com/NixOS/nixpkgs/commit/c37cffdda5ccc4999593c78c67db37b8f8d0ecde) | `` urlwatch: cherry-pick lxml 5 compatibility fix ``                       |
| [`4dbe5e70`](https://github.com/NixOS/nixpkgs/commit/4dbe5e70abe5f35508ef34060eac49cf73d1083a) …

chore(flake/nixpkgs): `cbc4211f` -> `73de017e`

---

flake.lock

| [`4ee704cb`](https://github.com/nix-community/home-manager/commit/4ee704cb13a5a7645436f400b9acc89a67b9c08a) | `` xscreensaver: add package option `` |
| [`ae7a3b51`](https://github.com/nix-community/home-manager/commit/ae7a3b5137ca3522f2802b3183de8fe5287b13d2) | `` hyprland: fix reloading ``          |

chore(flake/home-manager): `4e6d25a5` -> `4ee704cb`

---

flake.lock

| [`1d085ea4`](https://github.com/nix-community/home-manager/commit/1d085ea4444d26aa52297758b333b449b2aa6fca) | `` yazi: update shell integrations (#5048) `` |

chore(flake/home-manager): `4ee704cb` -> `1d085ea4`

---

flake.lock

| [`d5f1ed71`](https://github.com/nix-community/impermanence/commit/d5f1ed7141fa407880ff5956ded2c88a307ca940) | `` readme: add blog post to further reading `` |

chore(flake/impermanence): `cd13c291` -> `a33ef102`

---

flake.lock

| [`1933be30`](https://github.com/nix-community/lanzaboote/commit/1933be309626e1dd906cb5aaac1eb90bf687bf8e) | `` fix(deps): update all dependencies `` |

chore(flake/lanzaboote): `73fec693` -> `cd0acfcd`

---

flake.lock

| [`441c545a`](https://github.com/nix-community/lanzaboote/commit/441c545ab5096e0ce019bbd7d682a4f46d6532c2) | `` chore(deps): lock file maintenance `` |

chore(flake/lanzaboote): `cd0acfcd` -> `e761c7ee`

---

flake.lock

| [`01467901`](https://github.com/NixOS/nixos-hardware/commit/01467901ec51dd92774040f2b3dff4f21f4e1c45) | `` dell-xps-15-9570: init ``                     |
| [`f12e5fd7`](https://github.com/NixOS/nixos-hardware/commit/f12e5fd7ec032da50b16417a907db84c90e109c8) | `` nxp imx8mp-evk/imx8mq-evk documentation ``    |
| [`53e2a96a`](https://github.com/NixOS/nixos-hardware/commit/53e2a96a9edb28bc5b6c0428cf1230b06b9aec8f) | `` nxp imx8m quad evaluation platform support `` |
| …

chore(flake/nixos-hardware): `3f7d0bca` -> `01467901`

---

flake.lock

| [`d465f481`](https://github.com/numtide/flake-utils/commit/d465f4819400de7c8d874d50b982301f28a84605) | `` Add the current system if --impure is used (#115) `` |

chore(flake/flake-utils): `1ef2e671` -> `d465f481`

---

flake.lock

| Commit                                                                                                | Message                         |
| ----------------------------------------------------------------------------------------------------- | ------------------------------- |
| [`33a97b58`](https://github.com/NixOS/nixos-hardware/commit/33a97b5814d36ddd65ad678ad07ce43b1a67f159) | `` add w520 to readme ``        |
| [`ce93797a`](https://github.com/NixOS/nixos-hardware/commit/ce93797a42b8300c3e8bcb550d7659935289eeaf) | `` add w520 ( copy of t520 ) `` |

chore(flake/nixos-hardware): `01467901` -> `33a97b58`

---

flake.lock

| [`ad98aebc`](https://github.com/LnL7/nix-darwin/commit/ad98aebc0f900fa9bef8dfa8f5bdb328ab93ccd3) | `` Fix doc render problem ``                          |
| [`2ffb75f9`](https://github.com/LnL7/nix-darwin/commit/2ffb75f9423eb85c4ba5fa043b356f83e0586163) | `` defaults: Add options for dragOnGesture feature `` |

chore(flake/darwin): `283d5977` -> `c2751db9`

---

flake.lock

| Commit                                                                                           | Message                                |
| ------------------------------------------------------------------------------------------------ | -------------------------------------- |
| [`9090c6f8`](https://github.com/LnL7/nix-darwin/commit/9090c6f8973a0eb5285a64c4af1bdde333d4f22d) | `` nix-darwin/programs.direnv: init `` |

chore(flake/darwin): `c2751db9` -> `70d162d4`

---

flake.lock

| Commit                                                                                                    | Message                                   |
| --------------------------------------------------------------------------------------------------------- | ----------------------------------------- |
| [`d470342a`](https://github.com/nix-community/lanzaboote/commit/d470342af6fb149ee5a7685f2ec3a984ddc68112) | `` tests: remove custom OVMF overrides `` |

chore(flake/lanzaboote): `614b538f` -> `eeb45682`

---

flake.lock

| Commit                                                                                           | Message                               |
| ------------------------------------------------------------------------------------------------ | ------------------------------------- |
| [`ee53e578`](https://github.com/LnL7/nix-darwin/commit/ee53e5785c437aa2e836c6ce3b9fbf3936bf511e) | `` `system.startup.chime`: init ``    |
| [`0363c18c`](https://github.com/LnL7/nix-darwin/commit/0363c18c3704c44d4a282ecbd1455b325bc37a77) | `` `system.nvram`: init (internal) `` |

chore(flake/darwin): `70d162d4` -> `8a15cb36`

---

flake.lock

| [`59e37017`](https://github.com/NixOS/nixos-hardware/commit/59e37017b9ed31dee303dbbd4531c594df95cfbc) | `` Add msi B550 a pro motherboard `` |

chore(flake/nixos-hardware): `33a97b58` -> `59e37017`

---

flake.lock

| Commit                                                                                           | Message                                                               |
| ------------------------------------------------------------------------------------------------ | --------------------------------------------------------------------- |
| [`3397ab3b`](https://github.com/LnL7/nix-darwin/commit/3397ab3b7736e345e168da0ecade5c96b8a7f042) | `` feat(nix): adapt nix.conf validation for different Nix versions `` |

chore(flake/darwin): `8a15cb36` -> `17c2ca3c`

---

flake.lock

| [`9f3299f2`](https://github.com/nix-community/nix-index-database/commit/9f3299f2e00d045242fca52c059d01019da6d0f2) | `` flake.lock: Update `` |

chore(flake/nix-index-database): `f070c7ee` -> `9f3299f2`

---

flake.lock

| [`93554c04`](https://github.com/nix-community/nix-index-database/commit/93554c04c2f1c02f4a383538e8848d511c3129e9) | `` update packages.nix to release 2024-03-03-030835 `` |

chore(flake/nix-index-database): `9f3299f2` -> `93554c04`

---

flake.lock

| Commit                                                                                           | Message                                  |
| ------------------------------------------------------------------------------------------------ | ---------------------------------------- |
| [`b620e32a`](https://github.com/LnL7/nix-darwin/commit/b620e32a761ef6376c1097e73b3f8283604e4982) | `` fix writing values with containers `` |

chore(flake/darwin): `17c2ca3c` -> `530f2650`

---

flake.lock

| Commit                                                                                           | Message                                       |
| ------------------------------------------------------------------------------------------------ | --------------------------------------------- |
| [`5c65cfb6`](https://github.com/LnL7/nix-darwin/commit/5c65cfb656c1a7879c750d342bfdcc082831a891) | `` Add support for persistent-apps in dock `` |

chore(flake/darwin): `e7d7a7f0` -> `daa03606`

---

flake.lock
nix/overlays/sway-unstable.nix

| [`c90d5b6f`](https://github.com/NixOS/nixpkgs/commit/c90d5b6f2cbd4227b567ea1f3b1d54f102907d49) | `` python311Packages.google-cloud-kms: 2.20.0 -> 2.21.2 ``                       |
| [`47f5ac28`](https://github.com/NixOS/nixpkgs/commit/47f5ac28cf6a9b9876741a2cb4021f869996cd5d) | `` python311Packages.google-cloud-kms: 2.19.2 -> 2.20.0 ``                       |
| [`e433a5be`](https://github.com/NixOS/nixpkgs/commit/e433a5be1a7da3b15 …

chore(flake/nixpkgs): `9099616b` -> `1536926e`

---

flake.lock

| [`bdea159f`](https://github.com/nix-community/home-manager/commit/bdea159ffab9865f808b8d92fd2bef33521867b2) | `` fcitx5: fix reference to fcitx5-with-addons `` |

chore(flake/home-manager): `23ff9821` -> `bdea159f`

---

flake.lock

| [`1d717f58`](https://github.com/nix-community/home-manager/commit/1d717f581b7b001b2a1293277a1d3386fca5b87e) | `` gpg-agent: Fix nushell integration `` |

chore(flake/home-manager): `3c7bacf1` -> `1d717f58`

---

flake.lock

| [`47717650`](https://github.com/nix-community/home-manager/commit/477176502a6e099192da61984cd5be896d0b5659) | `` flake.lock: Update `` |

chore(flake/home-manager): `1d717f58` -> `47717650`

---

flake.lock

| [`613384a5`](https://github.com/nix-community/home-manager/commit/613384a51119ea34af58eb5e611e7f31dd3970d6) | `` tests: include a service in integration tests `` |
| [`950673ce`](https://github.com/nix-community/home-manager/commit/950673cec79298d9a1072499e0181849545376e2) | `` pueue: always write configuration file ``        |

chore(flake/home-manager): `47717650` -> `613384a5`

---

flake.lock

| [`8d9fde0f`](https://github.com/nix-community/home-manager/commit/8d9fde0fba21425729905f795fe72c2840a20442) | `` i3/sway: remove sebtm maintainer ``               |
| [`692726d2`](https://github.com/nix-community/home-manager/commit/692726d2ad5727cf14c563d0f1d2c015c021d7a5) | `` Translate using Weblate (German) ``               |
| [`d19bf3ae`](https://github.com/nix-community/home-manager/commit/d19bf3ae21686854760cfc5e81f269ea51072563) | `` Add translation …

chore(flake/home-manager): `613384a5` -> `8d9fde0f`

---

flake.lock

| [`f240015a`](https://github.com/nix-community/home-manager/commit/f240015a3a2e03370cb86a820909af14ec1ed35a) | `` gallery-dl: add package option `` |

chore(flake/home-manager): `8d9fde0f` -> `f240015a`

---

flake.lock

| [`ad9254cd`](https://github.com/nix-community/home-manager/commit/ad9254cd9af9165000ecd6ef9c23c2b8ceda01c7) | `` vdirsyncer: fix verify option type (#5096) `` |

chore(flake/home-manager): `f240015a` -> `ad9254cd`

---

flake.lock

| [`cf111d1a`](https://github.com/nix-community/home-manager/commit/cf111d1a849ddfc38e9155be029519b0e2329615) | `` zsh: improve `shell{,Global}Aliases` `` |

chore(flake/home-manager): `ad9254cd` -> `cf111d1a`

---

flake.lock

| Commit                                                                                           | Message                                                                      |
| ------------------------------------------------------------------------------------------------ | ---------------------------------------------------------------------------- |
| [`5c270053`](https://github.com/LnL7/nix-darwin/commit/5c2700533ced5c216ee451f86093bbb39094b912) | `` darwin-uninstaller: Fix when using nixpkgs.config.allowAliases = false `` |

chore(flake/darwin): `daa03606` -> `55034006`

---

flake.lock

| [`8ca587c4`](https://github.com/NixOS/nixpkgs/commit/8ca587c437949f417082d6c0d6e9f54fd1a64a65) | `` dotnetCorePackages.dotnet_8.sdk: remove `updateScript` to fix eval ``          |
| [`4b2a7dc3`](https://github.com/NixOS/nixpkgs/commit/4b2a7dc32b01697940efb39af5f9b4d558140f9f) | `` nodePackages.grammarly-languageserver: mark broken ``                          |
| [`be2aa8ba`](https://github.com/NixOS/nixpkgs/commit/be2aa8babf336 …

chore(flake/nixpkgs): `b8697e57` -> `9df3e30c`

---

flake.lock

| [`417015af`](https://github.com/nix-community/home-manager/commit/417015af0dc2525557ab36528643c2d519ca4334) | `` himalaya: adjust code for v1.0.0-beta.3 ``          |
| [`0c65bfa3`](https://github.com/nix-community/home-manager/commit/0c65bfa3cf7e8621a6cd3da500f591e2e92a6259) | `` git-sync: allow passing extraPackages to service `` |
| [`1283bf6e`](https://github.com/nix-community/home-manager/commit/1283bf6ebbdee4d980b7551bed4c6596805e812c) | `` …

chore(flake/home-manager): `cf111d1a` -> `417015af`

---

flake.lock

| [`8b07ca54`](https://github.com/nix-community/home-manager/commit/8b07ca541939211d3cc437ddfd74ebdef3d72471) | `` rio: fix docbookisms ``                          |
| [`9a3a5b44`](https://github.com/nix-community/home-manager/commit/9a3a5b4402e49ac62badff01b095f222724500a0) | `` rio: use XDG config for both linux and darwin `` |

chore(flake/home-manager): `417015af` -> `8b07ca54`

---

flake.lock

| Commit                                                                                                            | Message                                  |
| ----------------------------------------------------------------------------------------------------------------- | ---------------------------------------- |
| [`56335944`](https://github.com/nix-community/nix-index-database/commit/56335944627b7360c31da13c73aa521d996637d8) | `` Document nix-locate usage. Fix #79 `` |

chore(flake/nix-index-database): `94a1e464` -> `2ad5ebce`

---

flake.lock

| [`692fe3e9`](https://github.com/Mic92/nix-fast-build/commit/692fe3e98f36b60c678d637235271b57910a7f80) | `` Update cachix/install-nix-action action to v26 `` |

chore(flake/nix-fast-build): `ef8f59a0` -> `692fe3e9`

---

flake.lock

| [`17431970`](https://github.com/nix-community/home-manager/commit/17431970b4ebc75a92657101ccffcfc9e1f9d8f0) | `` files: fix activation under Nix 2.3 ``                 |
| [`b3a9fb9d`](https://github.com/nix-community/home-manager/commit/b3a9fb9d05e5117413eb87867cebd0ecc2f59b7e) | `` treewide: stop `run` from discarding error messages `` |
| [`bfc438e9`](https://github.com/nix-community/home-manager/commit/bfc438e9b707502dce0474738eff562a38046dc1) | …

chore(flake/home-manager): `8b07ca54` -> `17431970`

---

flake.lock

| [`16311f1d`](https://github.com/nix-community/home-manager/commit/16311f1d3c518656f680b7d09e29e37826f9802e) | `` borgmatic: add option for pattern matching `` |

chore(flake/home-manager): `17431970` -> `16311f1d`

---

flake.lock

| [`02f6f489`](https://github.com/nix-community/nix-index-database/commit/02f6f489773c2ffa5596a329af23dc0505280259) | `` flake.lock: Update `` |

chore(flake/nix-index-database): `2ad5ebce` -> `02f6f489`

---

flake.lock

| [`851fcfd1`](https://github.com/nix-community/nix-index-database/commit/851fcfd130597c5c91071d46275111522d4fd595) | `` update packages.nix to release 2024-03-10-030724 `` |

chore(flake/nix-index-database): `02f6f489` -> `851fcfd1`

---

flake.lock

| [`fe4180ad`](https://github.com/nix-community/home-manager/commit/fe4180ad3f07a2064fed7875183509e7e0eb07cd) | `` bat: handle existing cache in activation script `` |
| [`fbec8983`](https://github.com/nix-community/home-manager/commit/fbec89838763831bd92e1b09222dc9477942930f) | `` flake.lock: Update ``                              |

chore(flake/home-manager): `b0b0c3d9` -> `fe4180ad`

---

flake.lock

| [`36f873df`](https://github.com/nix-community/home-manager/commit/36f873dfc8e2b6b89936ff3e2b74803d50447e0a) | `` pqiv: add extraConfig option `` |

chore(flake/home-manager): `fe4180ad` -> `36f873df`

---

flake.lock

| Commit                                                                                                            | Message                                            |
| ----------------------------------------------------------------------------------------------------------------- | -------------------------------------------------- |
| [`e76ff2df`](https://github.com/nix-community/nix-index-database/commit/e76ff2df6bfd2abe06abd8e7b9f217df941c1b07) | `` Bump softprops/action-gh-release from 1 to 2 `` |
| [`5f50845a`](https://github.com/nix-community/nix-index-database/commit/5f50845a681aa04f9235d28540419227a19dc6e6) | `` Bump cachix/install-nix-action from 25 to 26 `` |

chore(flake/nix-index-database): `851fcfd1` -> `e76ff2df`

---

flake.lock

| [`ad2fd7b9`](https://github.com/NixOS/nixos-hardware/commit/ad2fd7b978d5e462048729a6c635c45d3d33c9ba) | `` build(deps): bump cachix/install-nix-action from 25 to 26 `` |

chore(flake/nixos-hardware): `59e37017` -> `ad2fd7b9`

---

flake.lock

| [`b1d9ab70`](https://github.com/numtide/flake-utils/commit/b1d9ab70662946ef0850d488da1c9019f3a9752a) | `` Bump cachix/install-nix-action from 25 to 26 (#116) `` |

chore(flake/flake-utils): `d465f481` -> `b1d9ab70`

---

flake.lock

| [`23b92a2a`](https://github.com/nix-community/lanzaboote/commit/23b92a2a3078fd89e62e8635797b83a4a2373908) | `` chore(deps): lock file maintenance `` |

chore(flake/lanzaboote): `3881267e` -> `f0039ede`

---

flake.lock

| Commit                                                                                                    | Message                                          |
| --------------------------------------------------------------------------------------------------------- | ------------------------------------------------ |
| [`674773cf`](https://github.com/nix-community/lanzaboote/commit/674773cf74cf0ebe62ee230b28e3533286db5b55) | `` docs: add more framework-specific hints ``    |
| [`e92f808e`](https://github.com/nix-community/lanzaboote/commit/e92f808ea1c180fb182da201ecbb530b6e2d4454) | `` fix(deps): update rust crate clap to 4.5.2 `` |

chore(flake/lanzaboote): `f0039ede` -> `f143c542`

---

flake.lock

| Commit                                                                                                    | Message                                                      |
| --------------------------------------------------------------------------------------------------------- | ------------------------------------------------------------ |
| [`acf7fffc`](https://github.com/nix-community/lanzaboote/commit/acf7fffcc9f332d62b83e00764f8ec6f7ef96532) | `` tests: refactor into separate files called via runTest `` |
| [`e17ed9d6`](https://github.com/nix-community/lanzaboote/commit/e17ed9d6da110dd1b6203c36e43b917b718929de) | `` nix/modules/uki: use upstream systemdUkify ``             |

chore(flake/lanzaboote): `f143c542` -> `19ad7fd5`

---

flake.lock

| [`017b12de`](https://github.com/nix-community/home-manager/commit/017b12de5b899ef9b64e2c035ce257bfe95b8ae2) | `` neomutt: adding unmailboxes option `` |

chore(flake/home-manager): `36f873df` -> `017b12de`

---

flake.lock

| Commit                                                                                           | Message                                                                      |
| ------------------------------------------------------------------------------------------------ | ---------------------------------------------------------------------------- |
| [`66f85cb9`](https://github.com/LnL7/nix-darwin/commit/66f85cb9db2144fe6434caee80838cbf7cfd0176) | `` trezord: Add launchd user agent service module for configuring trezord `` |

chore(flake/darwin): `55034006` -> `c7ae5dc9`

---

flake.lock

| [`a500de54`](https://github.com/nix-community/home-manager/commit/a500de54b2e3067201a40cefa5f210f719423ddf) | `` eza: replace enableAliases with integration options `` |

chore(flake/home-manager): `017b12de` -> `a500de54`

---

flake.lock

| [`49a266d2`](https://github.com/nix-community/home-manager/commit/49a266d2ca59df8a03249550e73a54626181b65d) | `` hyprland: add option for per-input device configs `` |

chore(flake/home-manager): `a500de54` -> `49a266d2`

---

flake.lock

| [`1d51ce1d`](https://github.com/danth/stylix/commit/1d51ce1de46ea0ee8738831a1d48b7824b0200b9) | `` ci: also build on master and release branches (#281) `` |
| [`1adbaaf4`](https://github.com/danth/stylix/commit/1adbaaf45c166a79c9f089d2224cb27fb25b6bbf) | `` ci: checkout via Nix rather than action (#280) ``       |
| [`d0b264e2`](https://github.com/danth/stylix/commit/d0b264e216a1e80c16415af635c5b07b2d6606a0) | `` ci: use Magic Nix Cache (#279) ``                       |

chore(flake/stylix): `32a79692` -> `1d51ce1d`

---

flake.lock

| [`1b74e367`](https://github.com/nix-community/home-manager/commit/1b74e3679e90fe7ad142bb5f66610a0d92ac0165) | `` docs: update home-manager-option-search URL `` |
| [`dab2437c`](https://github.com/nix-community/home-manager/commit/dab2437ca0aa0b91bbb0ea72a9f10ee494833593) | `` flake.lock: Update ``                          |

chore(flake/home-manager): `49a266d2` -> `1b74e367`

---

flake.lock

| [`a82cdd28`](https://github.com/nix-community/home-manager/commit/a82cdd288e3570ac52cffe0abaf28fac7d967b68) | `` offlineimap: disable starttls if tls is disabled `` |
| [`0906e8df`](https://github.com/nix-community/home-manager/commit/0906e8dfe7a4a530799681be4be8ac5b48fddc0b) | `` eza: use `mkDefault` for aliases ``                 |
| [`31abb4f6`](https://github.com/nix-community/home-manager/commit/31abb4f6bc540dfa82562e81312cfdc77770f001) | `` docs: …

chore(flake/home-manager): `1b74e367` -> `a82cdd28`

---

flake.lock

| [`383296ff`](https://github.com/nix-community/home-manager/commit/383296ffa45b539c28bf79ec2a272f652838ddd1) | `` joplin-desktop: add module `` |

chore(flake/home-manager): `a82cdd28` -> `383296ff`

---

flake.lock

| [`2f0db7d4`](https://github.com/nix-community/home-manager/commit/2f0db7d418e781354d8a3c50e611e3b1cd413087) | `` joplin-desktop: fix maintainer field `` |

chore(flake/home-manager): `383296ff` -> `2f0db7d4`

---

flake.lock

| [`bb3a5198`](https://github.com/danth/stylix/commit/bb3a5198782171c4038e50342f3b8579c9eb7eae) | `` gnome: remove impure getFlake (#283) `` |

chore(flake/stylix): `1d51ce1d` -> `bb3a5198`

---

flake.lock

| [`eb64377e`](https://github.com/danth/stylix/commit/eb64377e66122de7a36ca7a611aa97ddf4c8e5e8) | `` lazygit: init (#284) `` |

chore(flake/stylix): `bb3a5198` -> `eb64377e`

---

flake.lock

| [`387d513d`](https://github.com/NixOS/nixpkgs/commit/387d513df5a0337cdc222c3b77b6fbe7a7949b3f) | `` protolint: 0.47.5 -> 0.48.0 ``                                            |
| [`7ce6d540`](https://github.com/NixOS/nixpkgs/commit/7ce6d540f0325b1ca8226b62d9372047d74fa229) | `` kde/plasma: 6.0.1 -> 6.0.2 ``                                             |
| [`96e439e0`](https://github.com/NixOS/nixpkgs/commit/96e439e0291fa37103ef6c5ad91739a96 …

chore(flake/nixpkgs): `3030f185` -> `0ad13a68`

---

flake.lock

| [`ec4096e9`](https://github.com/nix-community/home-manager/commit/ec4096e9000c0b3695c05576076449ad99e905e3) | `` eza: fix typo in docs ``            |
| [`bd9141ea`](https://github.com/nix-community/home-manager/commit/bd9141ea97d8ccd68b97aa2febfae44683881662) | `` fusuma: add missing dependencies `` |

chore(flake/home-manager): `58771949` -> `ec4096e9`

---

flake.lock

| [`601c22f8`](https://github.com/nix-community/home-manager/commit/601c22f8af61b9a2e47001474c595c78771aa3b2) | `` Translate using Weblate (Vietnamese) `` |

chore(flake/home-manager): `ec4096e9` -> `601c22f8`

---

flake.lock

| [`35536fc6`](https://github.com/nix-community/home-manager/commit/35536fc6d621a084b04a70a6478db2aebbe828ed) | `` docs: update beets and description of overriding packages `` |

chore(flake/home-manager): `601c22f8` -> `35536fc6`

---

flake.lock

| [`02954535`](https://github.com/nix-community/home-manager/commit/029545350c013721e12139c9102f1776ca8aa9bb) | `` activitywatch: add module `` |

chore(flake/home-manager): `096d9c04` -> `02954535`

---

flake.lock

| [`dc2f3812`](https://github.com/nix-community/home-manager/commit/dc2f3812b41f825ed466c24c4211160d75cb890c) | `` nix-gc: add daily frequency option `` |

chore(flake/home-manager): `ca922258` -> `dc2f3812`

---

flake.lock

| [`3ad5c12f`](https://github.com/nix-community/home-manager/commit/3ad5c12f3c9b36cb8185d3aef9adcab3f543660a) | `` zsh: set autosuggestion color `` |

chore(flake/home-manager): `dc2f3812` -> `3ad5c12f`

---

flake.lock

| [`c781b28a`](https://github.com/nix-community/home-manager/commit/c781b28add41b74423ab2e64496d4fc91192e13a) | `` zsh: add patterns option to syntax-highlighting ``  |
| [`b004e47e`](https://github.com/nix-community/home-manager/commit/b004e47e03577e1226e2fe2f1e56d67a6aa8489d) | `` zsh: correct link for syntax-highlighting styles `` |

chore(flake/home-manager): `3ad5c12f` -> `c781b28a`

---

flake.lock

| [`206f457f`](https://github.com/nix-community/home-manager/commit/206f457fffdb9a73596a4cb2211a471bd305243d) | `` prezto: be caseSensitive by default `` |

chore(flake/home-manager): `c781b28a` -> `206f457f`

---

flake.lock

| [`8284ac38`](https://github.com/nix-community/nix-index-database/commit/8284ac380c1a11806a7bf7ef84eb3d2428e14630) | `` flake.lock: Update `` |

chore(flake/nix-index-database): `e76ff2df` -> `8284ac38`

---

flake.lock

| [`e25efda8`](https://github.com/nix-community/nix-index-database/commit/e25efda85e39fcdc845e371971ac4384989c4295) | `` update packages.nix to release 2024-03-17-030743 `` |

chore(flake/nix-index-database): `8284ac38` -> `e25efda8`

---

flake.lock

| [`d4f1636c`](https://github.com/danth/stylix/commit/d4f1636c9341b314fac01c179162a93bf59bc27f) | `` nixvim: change property name to align with nixvim (#288) `` |

chore(flake/stylix): `eb64377e` -> `d4f1636c`

---

flake.lock

| [`7b3fca5a`](https://github.com/nix-community/home-manager/commit/7b3fca5adcf6c709874a8f2e0c364fe9c58db989) | `` docs: minor fixes of guidelines `` |

chore(flake/home-manager): `206f457f` -> `7b3fca5a`

---

flake.lock

| [`4d29962d`](https://github.com/danth/stylix/commit/4d29962d9800fd75c6fa50a8e8b639ad84b9c909) | `` vscode: various adjustments (#271) ``                  |
| [`edf739ee`](https://github.com/danth/stylix/commit/edf739eeb36bf72ed664057af882351e382c1c12) | `` doc: change selection background to `base02` (#290) `` |

chore(flake/stylix): `d4f1636c` -> `4d29962d`

---

flake.lock

| [`b2c63a26`](https://github.com/nix-community/lanzaboote/commit/b2c63a26473afa9371b24833b7cbd6f5696cd597) | `` chore(deps): lock file maintenance `` |

chore(flake/lanzaboote): `19ad7fd5` -> `67dbf85b`

---

flake.lock

| [`14d24033`](https://github.com/danth/stylix/commit/14d240334719b15d9adab127e9bd34cfe0f03098) | `` stylix: add gitignore file (#291) `` |

chore(flake/stylix): `4d29962d` -> `14d24033`

---

flake.lock

| [`daddbb14`](https://github.com/danth/stylix/commit/daddbb141b1ea353942d0d1070b8a03a7128fa05) | `` plymouth: fail if substitution does not apply (#293) `` |

chore(flake/stylix): `14d24033` -> `daddbb14`

---

flake.lock

| [`2221c7d6`](https://github.com/danth/stylix/commit/2221c7d61b2e10b17df6c6795b4678fb59a0a92a) | `` plymouth: remove `blackBackground` option (#294) `` |

chore(flake/stylix): `daddbb14` -> `2221c7d6`

---

flake.lock

| [`1e679b9a`](https://github.com/NixOS/nixos-hardware/commit/1e679b9a9970780cd5d4dfe755a74a8f96d33388) | `` Update readme ``                                 |
| [`5bf55b85`](https://github.com/NixOS/nixos-hardware/commit/5bf55b853241737b047af62a90ed2e9cf41bb892) | `` Add msi-b350-tomahawk module to flake ``         |
| [`1568f005`](https://github.com/NixOS/nixos-hardware/commit/1568f005e12aee4bfe815750cac888ef6cb81a4d) | `` add support for MSI B350 TOMAHAWK Motherboard `` |

chore(flake/nixos-hardware): `968952f9` -> `1e679b9a`

---

flake.lock

| [`baf76594`](https://github.com/nix-community/home-manager/commit/baf7659448ffa6ab6870dba1ca681a4868c3068a) | `` kime: remove documentation dependency on config `` |
| [`865bef34`](https://github.com/nix-community/home-manager/commit/865bef34355d7ad22141f44460ecf7f759f0ff77) | `` kime: fix configuration ``                         |

chore(flake/home-manager): `7b3fca5a` -> `baf76594`

---

flake.lock

| Commit                                                                                                       | Message                                                           |
| ------------------------------------------------------------------------------------------------------------ | ----------------------------------------------------------------- |
| [`fc79a53e`](https://github.com/cachix/pre-commit-hooks.nix/commit/fc79a53eceac62d582fd0f4a098aae065106f619) | `` README: refresh ``                                             |
| [`b9fb64c3`](https://github.com/cachix/pre-commit-hooks.nix/commit/b9fb64c31a82d2b681a561db8c9e09c0a13ca594) | `` Update hook descriptions ``                                    |
| [`df4a2111`](https://github.com/cachix/pre-commit-hooks.nix/commit/df4a211 …

chore(flake/pre-commit-hooks): `5df5a70a` -> `844ae66b`

---

flake.lock

| [`02246443`](https://github.com/nix-community/home-manager/commit/022464438a85450abb23d93b91aa82e0addd71fb) | `` Translate using Weblate (Korean) `` |

chore(flake/home-manager): `6665da45` -> `02246443`

---

flake.lock

| Commit                                                                                                       | Message            |
| ------------------------------------------------------------------------------------------------------------ | ------------------ |
| [`d0589a99`](https://github.com/cachix/pre-commit-hooks.nix/commit/d0589a997c1481c0d4bd31242196054fe18c61f4) | `` fix typstfmt `` |

chore(flake/pre-commit-hooks): `afe89ba2` -> `e8dc1b4f`

---

flake.lock

| Commit                                                                                                       | Message                                             |
| ------------------------------------------------------------------------------------------------------------ | --------------------------------------------------- |
| [`21307b20`](https://github.com/cachix/pre-commit-hooks.nix/commit/21307b20b0f24ae8738e1771ac0b4a026756b85c) | `` Rename deprecated flake outputs ``               |
| [`cbb3524c`](https://github.com/cachix/pre-commit-hooks.nix/commit/cbb3524cd65a4e71165c77842ac1c5827321cf64) | `` Remove treefmt package in the all-hooks check `` |
| [`8a980910`](https://github.com/cachix/pre-commit-hooks.nix/commit/8a9809104fbb6b8c829b95852fdce87a1f5c183a) | `` Fix treefmt …

chore(flake/pre-commit-hooks): `e8dc1b4f` -> `c75cea79`

---

flake.lock

| Commit                                                                                                       | Message                           |
| ------------------------------------------------------------------------------------------------------------ | --------------------------------- |
| [`8fc4dd7c`](https://github.com/cachix/pre-commit-hooks.nix/commit/8fc4dd7c1f12aeda9b1d001f18e243de563b357c) | `` feat: introduce black flags `` |

chore(flake/pre-commit-hooks): `c75cea79` -> `61846354`

---

flake.lock

| Commit                                                                                                       | Message                                                                |
| ------------------------------------------------------------------------------------------------------------ | ---------------------------------------------------------------------- |
| [`543d006f`](https://github.com/cachix/pre-commit-hooks.nix/commit/543d006fef3a86e0887d2f2a213bffa7afbf19d1) | `` fix option ``                                                       |
| [`cf361f56`](https://github.com/cachix/pre-commit-hooks.nix/commit/cf361f562612258d5f6272b0c567aaf2b5ff93df) | `` fix #356: provide a way to access all packages for enabled hooks `` |

chore(flake/pre-commit-hooks): `61846354` -> `543d006f`

---

flake.lock

| Commit                                                                                                       | Message                                      |
| ------------------------------------------------------------------------------------------------------------ | -------------------------------------------- |
| [`e611897d`](https://github.com/cachix/pre-commit-hooks.nix/commit/e611897ddfdde3ed3eaac4758635d7177ff78673) | `` fix flakes example for enabledPackages `` |

chore(flake/pre-commit-hooks): `543d006f` -> `e611897d`

---

flake.lock

| [`3583fea7`](https://github.com/nix-community/home-manager/commit/3583fea7866834f70960a374cb0f4a6d1ffd0fc0) | `` flake.lock: Update `` |

chore(flake/home-manager): `02246443` -> `3583fea7`

---

flake.lock

| [`1c2acec9`](https://github.com/nix-community/home-manager/commit/1c2acec99933f9835cc7ad47e35303de92d923a4) | `` xdg-portal: align with NixOS module `` |

chore(flake/home-manager): `3583fea7` -> `1c2acec9`

---

flake.lock

| [`19b87b9a`](https://github.com/nix-community/home-manager/commit/19b87b9ae6ecfd81104a2a36ef8364f1de1b54b1) | `` vdirsyncer: add urlCommand and userNameCommand options `` |

chore(flake/home-manager): `1c2acec9` -> `19b87b9a`

---

flake.lock

| [`1c2c5e4c`](https://github.com/nix-community/home-manager/commit/1c2c5e4cabba4c43504ef0f8cc3f3dfa284e2dbb) | `` home-manager: fix nix-build option `-q` `` |

chore(flake/home-manager): `19b87b9a` -> `1c2c5e4c`

---

flake.lock

| [`53d3e5d5`](https://github.com/danth/stylix/commit/53d3e5d5b36a5227b906e00d7e884dcfb7852403) | `` nixos-icons: recolor white logo (#297) `` |

chore(flake/stylix): `4da2d793` -> `53d3e5d5`

---

flake.lock

| [`d7b713a5`](https://github.com/nix-community/nix-index-database/commit/d7b713a5fed6f7c8d21de9c510ccd782cb36cd74) | `` flake.lock: Update `` |

chore(flake/nix-index-database): `e25efda8` -> `d7b713a5`

---

flake.lock

| [`34519f3b`](https://github.com/nix-community/nix-index-database/commit/34519f3bb678a5abbddf7b200ac5347263ee781b) | `` update packages.nix to release 2024-03-24-030726 `` |

chore(flake/nix-index-database): `d7b713a5` -> `34519f3b`

---

flake.lock

| [`b081de56`](https://github.com/NixOS/nixos-hardware/commit/b081de56dfc51d2b5b648d6ae2b106deeeb49d00) | `` 16ach6h: re-enable edid for internal display only `` |

chore(flake/nixos-hardware): `1e679b9a` -> `7559df1e`

---

flake.lock

| [`d4e2075c`](https://github.com/nix-community/lanzaboote/commit/d4e2075cc5183ed15ba661821b90fe75597a055d) | `` chore(deps): lock file maintenance `` |

chore(flake/lanzaboote): `ded8d237` -> `d67e1cc1`

---

flake.lock

| Commit                                                                                                       | Message                   |
| ------------------------------------------------------------------------------------------------------------ | ------------------------- |
| [`b54aac8e`](https://github.com/cachix/pre-commit-hooks.nix/commit/b54aac8e39a0a0f2ccf8cd95aa747f4b3489bcf8) | `` Add ripsecrets hook `` |

chore(flake/pre-commit-hooks): `e611897d` -> `db656fc3`

---

flake.lock

| [`7d47a32e`](https://github.com/cachix/git-hooks.nix/commit/7d47a32e5cd1ea481fab33c516356ce27c8cef4a) | `` rename to git-hooks.nix `` |

chore(flake/pre-commit-hooks): `db656fc3` -> `7d47a32e`

---

flake.lock

| [`179f6aca`](https://github.com/nix-community/home-manager/commit/179f6acaf7c068c7870542cdae72afec9427a5b0) | `` antidote: Use builtins.storeDir (#5182) `` |
| [`eb869521`](https://github.com/nix-community/home-manager/commit/eb869521cb6c895b6d351be0b9e010c578de0e4b) | `` darkman: allow no configuration ``         |

chore(flake/home-manager): `1c2c5e4c` -> `179f6aca`

---

flake.lock

| [`3142bdcc`](https://github.com/nix-community/home-manager/commit/3142bdcc470e1e291e1fbe942fd69e06bd00c5df) | `` readline: optionally place config file in XDG dir `` |

chore(flake/home-manager): `179f6aca` -> `3142bdcc`

---

flake.lock

| Commit                                                                                        | Message                                   |
| --------------------------------------------------------------------------------------------- | ----------------------------------------- |
| [`75fd2477`](https://github.com/danth/stylix/commit/75fd247712ac54d756b7c0bb7150dc6858d29522) | `` mangohud: remove `font_file` (#307) `` |

chore(flake/stylix): `53d3e5d5` -> `75fd2477`

---

flake.lock

| [`0d676ca9`](https://github.com/cachix/git-hooks.nix/commit/0d676ca9ca9df7f2d4d5fb0de511fed3a4b67fdf) | `` free up space on ci ``                |
| [`5da7bab7`](https://github.com/cachix/git-hooks.nix/commit/5da7bab7c34586b8a0a8c397d8c6b257fcceb96e) | `` Fix `nix flake check` on macOS ``     |
| [`dc6812ea`](https://github.com/cachix/git-hooks.nix/commit/dc6812ea2c8a21cca091ecb9ae0433d89e03efe4) | `` Silence git commit summary ``         |
| …

chore(flake/pre-commit-hooks): `7d47a32e` -> `c11e43ae`

---

flake.lock

| Commit                                                                                           | Message                         |
| ------------------------------------------------------------------------------------------------ | ------------------------------- |
| [`398510f6`](https://github.com/LnL7/nix-darwin/commit/398510f601cb1a1978a393814514f9ca9fbcfe72) | `` Add `nix.optimise` module `` |

chore(flake/darwin): `f0dd0838` -> `36524adc`

---

flake.lock

| Commit                                                                                        | Message                                                       |
| --------------------------------------------------------------------------------------------- | ------------------------------------------------------------- |
| [`bad1af63`](https://github.com/danth/stylix/commit/bad1af63ff330b397b87fc243d479701417740da) | `` kde: remove internal debugging logs (#304) ``              |
| [`504c54db`](https://github.com/danth/stylix/commit/504c54dbf1d91857b52133ee9c9bd4c526b3275c) | `` kde: remove redundant function declaration space (#305) `` |

chore(flake/stylix): `75fd2477` -> `bad1af63`

---

flake.lock

| Commit                                                                                        | Message                                                 |
| --------------------------------------------------------------------------------------------- | ------------------------------------------------------- |
| [`fdf8fd26`](https://github.com/danth/stylix/commit/fdf8fd261eba972e23e8926caeb3aa41c5e3ac68) | `` treewide: use Bash internal 'test' command (#311) `` |

chore(flake/stylix): `bad1af63` -> `fdf8fd26`

---

flake.lock

| [`784ca729`](https://github.com/nix-community/nix-index-database/commit/784ca7299336509ebcfb3702be28fcb0015e99cd) | `` flake.lock: Update `` |

chore(flake/nix-index-database): `34519f3b` -> `784ca729`

---

flake.lock

| [`30f2ec39`](https://github.com/nix-community/home-manager/commit/30f2ec39519f4f5a8a96af808c439e730c15aeab) | `` flake.lock: Update ``                   |
| [`c09deb86`](https://github.com/nix-community/home-manager/commit/c09deb869b2e7a4612e489d4bbb11517f78b618e) | `` Translate using Weblate (Vietnamese) `` |

chore(flake/home-manager): `c0ef0dab` -> `30f2ec39`

---

flake.lock

| [`2844b5f3`](https://github.com/nix-community/nix-index-database/commit/2844b5f3ad3b478468151bd101370b9d8ef8a3a7) | `` update packages.nix to release 2024-03-31-030752 `` |

chore(flake/nix-index-database): `784ca729` -> `2844b5f3`

---

flake.lock

| [`820be197`](https://github.com/nix-community/home-manager/commit/820be197ccf3adaad9a8856ef255c13b6cc561a6) | `` programs.khal: ability to set RGB color (#5192) `` |

chore(flake/home-manager): `30f2ec39` -> `820be197`

---

flake.lock

| Commit                                                                                                | Message                                      |
| ----------------------------------------------------------------------------------------------------- | -------------------------------------------- |
| [`d2f6f937`](https://github.com/cachix/git-hooks.nix/commit/d2f6f9376c38fb0c48526720793a17f10cd3ac10) | `` Add `package` options for hooks ``        |
| [`6caf5b27`](https://github.com/cachix/git-hooks.nix/commit/6caf5b27b7ef4ce9746a8ec08592c609ccde34a2) | `` Fix sort-file-contents description ``     |
| [`c6189c3d`](https://github.com/cachix/git-hooks.nix/commit/c6189c3db3343985cdb5223b12b920172ee22b03) | `` Revert unintended changes ``              |
| …

chore(flake/pre-commit-hooks): `9fc61b5e` -> `ffbf4694`

---

flake.lock

| Commit                                                                                              | Message                                   |
| --------------------------------------------------------------------------------------------------- | ----------------------------------------- |
| [`f10a3aa1`](https://github.com/serokell/deploy-rs/commit/f10a3aa17c9cbb1d217ab03369909af6fc29e1d0) | `` [Chore] Fix overlay ``                 |
| [`a9283526`](https://github.com/serokell/deploy-rs/commit/a92835264100583903dc408abe43d461ff7d4dca) | `` [OPS-1384] Introduce NixOS VM tests `` |

chore(flake/deploy-rs): `0a018779` -> `88b3059b`

---

flake.lock

| [`a0bdd9c1`](https://github.com/danth/stylix/commit/a0bdd9c15b23a5db48d29afe3b238333605c357c) | `` stylix: escape spaces in wallpaper path (#317) `` |

chore(flake/stylix): `3c6b34fb` -> `a0bdd9c1`

---

flake.lock

| Commit                                                                                                | Message                |
| ----------------------------------------------------------------------------------------------------- | ---------------------- |
| [`f3bb9549`](https://github.com/cachix/git-hooks.nix/commit/f3bb95498eaaa49a93bacaf196cdb6cf8e872cdf) | `` Fix link to docs `` |

chore(flake/pre-commit-hooks): `8ae5bb63` -> `f3bb9549`

---

flake.lock

| Commit                                                                                        | Message                                               |
| --------------------------------------------------------------------------------------------- | ----------------------------------------------------- |
| [`b6dbe9ac`](https://github.com/danth/stylix/commit/b6dbe9ac5d57d27d5620445f20cad2c353089f86) | `` kde: use provided `verboseEcho` function (#316) `` |

chore(flake/stylix): `a0bdd9c1` -> `b6dbe9ac`

---

flake.lock

| Commit                                                                                                | Message                     |
| ----------------------------------------------------------------------------------------------------- | --------------------------- |
| [`649fb51d`](https://github.com/cachix/git-hooks.nix/commit/649fb51def9772b420737dae9cf7289af80f0a8b) | `` add installation test `` |

chore(flake/pre-commit-hooks): `f3bb9549` -> `642dce09`

---

flake.lock

| [`80546b22`](https://github.com/nix-community/home-manager/commit/80546b220e95a575c66c213af1b09fe255299438) | `` Translate using Weblate (Norwegian Bokmål) `` |
| [`58e5ae81`](https://github.com/nix-community/home-manager/commit/58e5ae81ceb274a249ae69659f3150419673f14c) | `` Translate using Weblate (Romanian) ``         |
| [`aca33e99`](https://github.com/nix-community/home-manager/commit/aca33e99551250cfb23f384789d9fecea0254ac4) | `` Translate using Weblate …

chore(flake/home-manager): `4be04644` -> `80546b22`

---

flake.lock

| [`f9b9bc7c`](https://github.com/danth/stylix/commit/f9b9bc7c8e69942cd2583a3309f86fc5260f1275) | `` stylix: do not escape spaces in wallpaper path (#329) `` |

chore(flake/stylix): `b6dbe9ac` -> `f9b9bc7c`

---

flake.lock

| [`7e91f2a0`](https://github.com/nix-community/home-manager/commit/7e91f2a0ba4b62b88591279d54f741a13e36245b) | `` xmonad: fix cp failure if libFiles with subdirectories `` |

chore(flake/home-manager): `80546b22` -> `7e91f2a0`

---

flake.lock

| [`01b1660d`](https://github.com/nix-community/lanzaboote/commit/01b1660d82783cdde3973db45c78504678785fb6) | `` docs: BitLocker recovery key warning `` |

chore(flake/lanzaboote): `df7ac26b` -> `90a97cce`

---

flake.lock

| [`fe804aac`](https://github.com/nix-community/lanzaboote/commit/fe804aac25fc591c303fb417ec93a8bbad9c038c) | `` chore(deps): update all dependencies `` |

chore(flake/lanzaboote): `90a97cce` -> `999c0cb0`

---

flake.lock

| [`0c73c1b8`](https://github.com/nix-community/home-manager/commit/0c73c1b8da28a24c4fe842ced3f2548d5828b550) | `` zoxide: remove obsolete workaround `` |
| [`9de3aab0`](https://github.com/nix-community/home-manager/commit/9de3aab0917914baad72e32023834f9b39e77610) | `` kdeconnect: add package option ``     |

chore(flake/home-manager): `7e91f2a0` -> `0c73c1b8`

---

flake.lock

| Commit                                                                                                | Message                                                                 |
| ----------------------------------------------------------------------------------------------------- | ----------------------------------------------------------------------- |
| [`f3b95962`](https://github.com/NixOS/nixos-hardware/commit/f3b959627bca46a9f7052b8fbc464b8323e68c2c) | `` removed edid ``                                                      |
| [`a7825c5b`](https://github.com/NixOS/nixos-hardware/commit/a7825c5b9a9c69dddd1904789ebbe413c5b6bf15) | `` 15ach6h ``                                                           |
| [`a3746a14`](https://github.com/NixOS/nixos-hardware/commit/a3746a14c1240b57b2 …

chore(flake/nixos-hardware): `9a763a7a` -> `f3b95962`

---

flake.lock

| [`4676d72d`](https://github.com/nix-community/nix-index-database/commit/4676d72d872459e1e3a248d049609f110c570e9a) | `` update packages.nix to release 2024-04-07-030847 `` |

chore(flake/nix-index-database): `373c00eb` -> `4676d72d`

---

flake.lock

| [`a561ad6a`](https://github.com/nix-community/home-manager/commit/a561ad6ab38578c812cc9af3b04f2cc60ebf48c9) | `` flake.lock: Update `` |

chore(flake/home-manager): `b787726a` -> `a561ad6a`

---

flake.lock

| [`218ab789`](https://github.com/NixOS/nixos-hardware/commit/218ab789fdabbed9a755539b1520a9c628e153ce) | `` milkv/pioneer: fix u-root cross-compilation `` |
| [`f4a07223`](https://github.com/NixOS/nixos-hardware/commit/f4a07223a336f966eb6546b42eadfd288c4c5e2e) | `` milkv/pioneer: init ``                         |

chore(flake/nixos-hardware): `f3b95962` -> `1e3b3a35`

---

flake.lock

| [`6c2316d1`](https://github.com/cachix/git-hooks.nix/commit/6c2316d1b2903cecc3692b6b75fdf078e735ebcd) | `` Filter out nulls from enabledPackages `` |
| [`eb9778d3`](https://github.com/cachix/git-hooks.nix/commit/eb9778d3a17b192708d2c8da2ce0f22be5e465b3) | `` Set the default hook package to null ``  |

chore(flake/pre-commit-hooks): `e35aed5f` -> `70f50401`

---

flake.lock

| [`40a99619`](https://github.com/nix-community/home-manager/commit/40a99619da804a78a0b166e5c6911108c059c3a8) | `` fzf: add compatibility with fzf≥0.48.0 `` |

chore(flake/home-manager): `a561ad6a` -> `40a99619`

---

flake.lock

| [`41e6854d`](https://github.com/NixOS/nixos-hardware/commit/41e6854df791c23e30a91cd48790c647bde28d0d) | `` surface: linux 6.6.13 -> 6.6.25 `` |

chore(flake/nixos-hardware): `1e3b3a35` -> `05aa46a1`

---

flake.lock

| Commit                                                                                                      | Message               |
| ----------------------------------------------------------------------------------------------------------- | --------------------- |
| [`b00d0e4f`](https://github.com/nix-community/home-manager/commit/b00d0e4fe9cba0047f54e77418ddda5f17e6ef2c) | `` bun: add module `` |

chore(flake/home-manager): `40a99619` -> `b00d0e4f`

---

flake.lock

| [`18f89ef7`](https://github.com/nix-community/home-manager/commit/18f89ef74f0d48635488ccd6a5e30dc9d48a3a87) | `` firefox: add containersForce flag `` |

chore(flake/home-manager): `b00d0e4f` -> `18f89ef7`

---

flake.lock

| [`805adee8`](https://github.com/NixOS/nixos-hardware/commit/805adee81c82efbe50cac7398c4de05769488ed9) | `` Add Lenovo legion 16ARHA7 (#906) `` |

chore(flake/nixos-hardware): `05aa46a1` -> `805adee8`

---

flake.lock

| [`e1c4bac1`](https://github.com/NixOS/nixos-hardware/commit/e1c4bac14beb8c409d0534382cf967171706b9d9) | `` Lenovo ThinkPad Z13 Gen 2 (#844) ``  |
| [`79a20e2a`](https://github.com/NixOS/nixos-hardware/commit/79a20e2ac0dddeaf6a482a547181361f061f7955) | `` common/pc: remove libinput.enable `` |

chore(flake/nixos-hardware): `805adee8` -> `e1c4bac1`

---

flake.lock

| Commit                                                                                        | Message                                                       |
| --------------------------------------------------------------------------------------------- | ------------------------------------------------------------- |
| [`58761b51`](https://github.com/danth/stylix/commit/58761b51f86be18a4638ba59ba1debd01d71323a) | `` doc: add mention of `lib.stylix.pixel` to tricks (#327) `` |

chore(flake/stylix): `f9b9bc7c` -> `58761b51`

---

flake.lock

| [`c630a7d3`](https://github.com/danth/stylix/commit/c630a7d3ee4530e6a0e20ddf45ad813fc8b6da1b) | `` plymouth: lock URL version (#335) `` |

chore(flake/stylix): `58761b51` -> `c630a7d3`

---

flake.lock

| [`406f7930`](https://github.com/danth/stylix/commit/406f793045ce82689194273cb7e7c4ad0fec530c) | `` stylix: escape spaces in wallpaper path (#318) `` |

chore(flake/stylix): `c630a7d3` -> `406f7930`

---

flake.lock

| Commit                                                                                                | Message                |
| ----------------------------------------------------------------------------------------------------- | ---------------------- |
| [`5069220c`](https://github.com/cachix/git-hooks.nix/commit/5069220c7f47ff139c7c1b01b6996684859d838b) | `` Add lacheck hook `` |

chore(flake/git-hooks): `70f50401` -> `40e6053e`

---

flake.lock

| Commit                                                                                                | Message              |
| ----------------------------------------------------------------------------------------------------- | -------------------- |
| [`f58b2525`](https://github.com/NixOS/nixos-hardware/commit/f58b25254be441cd2a9b4b444ed83f1e51244f1f) | `` macmini4: init `` |

chore(flake/nixos-hardware): `e1c4bac1` -> `f58b2525`

---

flake.lock

| [`40ab43ae`](https://github.com/nix-community/home-manager/commit/40ab43ae98cb3e6f07eaeaa3f3ed56d589da21b0) | `` foot: set PATH in server's systemd unit file `` |

chore(flake/home-manager): `31357486` -> `40ab43ae`

---

flake.lock

| [`8fdf3295`](https://github.com/nix-community/home-manager/commit/8fdf329526f06886b53b94ddf433848a0d142984) | `` neovim: enable use of external package manager (#5225) `` |

chore(flake/home-manager): `40ab43ae` -> `8fdf3295`

---

flake.lock

| [`83866ed8`](https://github.com/danth/stylix/commit/83866ed8800ed39519a79ea30b18c8eb21f26080) | `` plymouth: remove substituteInPlace to fix build failure (#338) `` |

chore(flake/stylix): `406f7930` -> `83866ed8`

---

flake.lock

| [`630a0992`](https://github.com/nix-community/home-manager/commit/630a0992b3627c64e34f179fab68e3d48c6991c0) | `` nushell: fix nushell config path on darwin `` |
| [`4cc3c916`](https://github.com/nix-community/home-manager/commit/4cc3c91601b6083c3715516d5d891fa46c679e59) | `` flake.lock: Update ``                         |
| [`f33d5086`](https://github.com/nix-community/home-manager/commit/f33d5086d3f9128aba126135ea2a901c121ebf06) | `` rio: remove redundant …

chore(flake/home-manager): `8fdf3295` -> `630a0992`

---

flake.lock

| [`9f32c66a`](https://github.com/nix-community/home-manager/commit/9f32c66a51d05e6d4ec0dea555bbff9135749ec7) | `` k9s: configuration files in Darwin without XDG `` |
| [`76a1650c`](https://github.com/nix-community/home-manager/commit/76a1650c45df8ed130e66eeeb8275a149562c4c5) | `` k9s: fix typos in configuration file names ``     |

chore(flake/home-manager): `630a0992` -> `9f32c66a`

---

flake.lock

| [`1c43dcfa`](https://github.com/nix-community/home-manager/commit/1c43dcfac48a2d622797f7ab741670fdbcf8f609) | `` ci: bump peaceiris/actions-gh-pages from 3 to 4 `` |
| [`59d50bc5`](https://github.com/nix-community/home-manager/commit/59d50bc582bdf439df096a9ae1781e6c9c8a7523) | `` espanso: enable module on darwin ``                |

chore(flake/home-manager): `9f32c66a` -> `1c43dcfa`

---

flake.lock

| [`6a8ed263`](https://github.com/NixOS/nixpkgs/commit/6a8ed263b8f8661fcfd1d9d2056f9b7154c81258) | `` python312Packages.snakemake-interface-executor-plugins: 9.1.0 -> 9.1.1 ``   |
| [`a8fe1602`](https://github.com/NixOS/nixpkgs/commit/a8fe160216fa928972e8d51457e45cf8a7721eb8) | `` python312Packages.python-telegram-bot: 21.0.1 -> 21.1 ``                    |
| [`d76c4a6d`](https://github.com/NixOS/nixpkgs/commit/d76c4a6d8afcfa06c4e2cc849 …

chore(flake/nixpkgs): `4cba8b53` -> `cfd6b5fc`

---

flake.lock

| [`53f978f2`](https://github.com/NixOS/nixos-hardware/commit/53f978f270d660103fe96ac9d8d84655f82f8b2e) | `` link offical wiki page instead of unoffical `` |

chore(flake/nixos-hardware): `f58b2525` -> `f2d364de`

---

flake.lock

| [`f46814ec`](https://github.com/nix-community/home-manager/commit/f46814ec7cbef9c2aef18ca1cbe89f2bb1e8c394) | `` treewide: prefer the official wiki `` |
| [`93b917d4`](https://github.com/nix-community/home-manager/commit/93b917d49f0b2ab75ff91e17573e112b95fdd95c) | `` flake.lock: Update ``                 |

chore(flake/home-manager): `fa8c16e2` -> `f46814ec`

---

flake.lock

| [`6f976e53`](https://github.com/NixOS/nixos-hardware/commit/6f976e53752e5b9ab08f9a3b1b0b9c67815c9754) | `` surface: linux-surface to 6.8.6 `` |
| [`699723a7`](https://github.com/NixOS/nixos-hardware/commit/699723a72878912a7f8ae4b18d57eea68836c0fa) | `` surface: linux-surface to 6.8.1 `` |

chore(flake/nixos-hardware): `f2d364de` -> `6f976e53`

---

flake.lock

| [`178e2689`](https://github.com/nix-community/home-manager/commit/178e26895b3aef028a00a32fb7e7ed0fc660645c) | `` home-manager: error out on missing option argument `` |

chore(flake/home-manager): `f46814ec` -> `178e2689`

---

flake.lock

| Commit                                                                                           | Message                                          |
| ------------------------------------------------------------------------------------------------ | ------------------------------------------------ |
| [`1098e60e`](https://github.com/LnL7/nix-darwin/commit/1098e60e92afc5e30611a3933ad783d99e198734) | `` ci, readme: update stable nixpkgs to 23.11 `` |
| [`81f7aab5`](https://github.com/LnL7/nix-darwin/commit/81f7aab5edf705d851415762d1bfe4fa836bbce7) | `` Update ShowDate in menuExtraClock ``          |

chore(flake/darwin): `36524adc` -> `eb25dc61`

---

flake.lock

| [`54e35e0e`](https://github.com/nix-community/home-manager/commit/54e35e0e1c1b6b4888c34423335a448ab3ec78d5) | `` qt: use warnings API ``             |
| [`be2b1761`](https://github.com/nix-community/home-manager/commit/be2b17615c536c31d0ea4989a959298b115353b3) | `` qt: fix adwaita decorations link `` |
| [`b31019d6`](https://github.com/nix-community/home-manager/commit/b31019d64f9ddd1a869fa8fdb371c32c7ed9b578) | `` qt: add adwaita platform theme ``   |
| …

chore(flake/home-manager): `178e2689` -> `ff1c3646`

---

flake.lock

| [`4c0599b6`](https://github.com/NixOS/nixpkgs/commit/4c0599b6ce6e408b46f13c69ab1c9d5d25834bcd) | `` firefox-bin-unwrapped: 125.0 -> 125.0.1 ``                                |
| [`283867bd`](https://github.com/NixOS/nixpkgs/commit/283867bd9ac846d5051905c408aa5a8fd3163837) | `` firefox-unwrapped: 125.0 -> 125.0.1 ``                                    |
| [`60807215`](https://github.com/NixOS/nixpkgs/commit/608072151ba6978a86f0ea69d21c4f43d …

chore(flake/nixpkgs): `cfd6b5fc` -> `66adc1e4`

---

flake.lock

| Commit                                                                                                      | Message              |
| ----------------------------------------------------------------------------------------------------------- | -------------------- |
| [`ffc3600f`](https://github.com/nix-community/home-manager/commit/ffc3600f4009ca39b6cb63b24127ca4f93792854) | `` fd: add module `` |

chore(flake/home-manager): `ff1c3646` -> `ffc3600f`

---

flake.lock

| [`8ff7bb3f`](https://github.com/nix-community/home-manager/commit/8ff7bb3f4d82a05a52d5242ec454bba14f5d6cc6) | `` tofi: add module ``                        |
| [`f3506ba8`](https://github.com/nix-community/home-manager/commit/f3506ba86cbc5f8620ea6b4e108146702a4627e9) | `` bash: add bash package to home.packages `` |

chore(flake/home-manager): `ffc3600f` -> `8ff7bb3f`

---

flake.lock

| [`5d48925b`](https://github.com/NixOS/nixos-hardware/commit/5d48925b815fd202781bfae8fb6f45c07112fdb2) | `` Removed commented dpi settings ``          |
| [`3638bc8f`](https://github.com/NixOS/nixos-hardware/commit/3638bc8fab3de21e116909423f289feb4950a0c8) | `` Redirected users to the fwupd wiki page `` |
| [`6f1e7c42`](https://github.com/NixOS/nixos-hardware/commit/6f1e7c42376cbc14c6a3d46e8471e58d36b8c5c7) | `` added framework 16 ``                      |

chore(flake/nixos-hardware): `6f976e53` -> `5d48925b`

---

flake.lock

| [`b1a5b3d6`](https://github.com/nix-community/home-manager/commit/b1a5b3d6a524c80c7dd20888bff227d52adf5f03) | `` vdirsyncer: set `postHook` to null when not set (#5294) `` |
| [`b62cad68`](https://github.com/nix-community/home-manager/commit/b62cad68b754224caec1e3b0dbadf86821b0b255) | `` spotify-player: add module ``                              |
| [`b5b2b1ac`](https://github.com/nix-community/home-manager/commit/b5b2b1ac63458357e205bcb2df2d …

chore(flake/home-manager): `8ff7bb3f` -> `b1a5b3d6`

---

flake.lock

| [`0184c818`](https://github.com/nix-community/home-manager/commit/0184c8180f5cbb8e3a54a239b874fe849d3073cb) | `` neomutt: add some options `` |

chore(flake/home-manager): `b1a5b3d6` -> `0184c818`

---

flake.lock

| [`dc906b19`](https://github.com/nix-community/home-manager/commit/dc906b197bc20c518e497fb040bb8240543fa634) | `` kdeconnect: require "tray.target" for kdeconnect `` |

chore(flake/home-manager): `0184c818` -> `dc906b19`

---

flake.lock

| [`068dd4ae`](https://github.com/nix-community/home-manager/commit/068dd4ae292b5bf64bda18a48bcd80f39dd76257) | `` alacritty: cleanup after 0.13 merge in nixpkgs ``     |
| [`7ca7025c`](https://github.com/nix-community/home-manager/commit/7ca7025cf2fa88bebc2190955c44263c3989b706) | `` alacritty: fix escape sequence in example and test `` |

chore(flake/home-manager): `dc906b19` -> `068dd4ae`

---

flake.lock

| Commit                                                                                           | Message                          |
| ------------------------------------------------------------------------------------------------ | -------------------------------- |
| [`def1e23b`](https://github.com/LnL7/nix-darwin/commit/def1e23be848848400d1d097d4f044e3c401f9dd) | `` treewide: remove lib.mdDoc `` |

chore(flake/darwin): `eb25dc61` -> `9e7c20ff`

---

flake.lock

| [`6a171bfd`](https://github.com/nix-community/home-manager/commit/6a171bfd84ee9b3df83f6eb76dab042219978439) | `` kconfig: add module `` |

chore(flake/home-manager): `1f305c36` -> `6a171bfd`

---

flake.lock

| [`938357cb`](https://github.com/nix-community/home-manager/commit/938357cb234e85da37109df2cdd9cc59ab9c1cc0) | `` hyprland: remove enableNvidiaPatches option `` |

chore(flake/home-manager): `6a171bfd` -> `938357cb`

---

flake.lock

| [`7c61e400`](https://github.com/nix-community/home-manager/commit/7c61e400a99f33cdff3118c1e4032bcb049e1a30) | `` Translate using Weblate (Turkish) ``    |
| [`991f6faf`](https://github.com/nix-community/home-manager/commit/991f6fafce729e6d7d64107a66e445114194b778) | `` Translate using Weblate (Portuguese) `` |
| [`5682ccdc`](https://github.com/nix-community/home-manager/commit/5682ccdcaf72aef74be97e4b683545a9de27c386) | `` Translate using Weblate (Spanish) ``    |

chore(flake/home-manager): `938357cb` -> `7c61e400`

---

flake.lock

| [`057117a4`](https://github.com/nix-community/home-manager/commit/057117a401a34259c9615ce62218aea7afdee4d3) | `` kdeconnect: fix "tray.target" requires `` |
| [`a2040822`](https://github.com/nix-community/home-manager/commit/a20408227466032a16e73893b09a67092258cf67) | `` firefox: fix test ``                      |
| [`3a435342`](https://github.com/nix-community/home-manager/commit/3a435342e2e5e2bff1d3331c2bd9e70f25693ea2) | `` sway: check config file validity ``       |
| …

chore(flake/home-manager): `7c61e400` -> `057117a4`

---

flake.lock

| Commit                                                                                        | Message                                                            |
| --------------------------------------------------------------------------------------------- | ------------------------------------------------------------------ |
| [`5749cf16`](https://github.com/danth/stylix/commit/5749cf162340b230e86fa75571b3cb6ce7f11441) | `` nixos-icons: `white.svg` -> `nix-snowflake-white.svg` (#343) `` |

chore(flake/stylix): `b36fb34a` -> `5749cf16`

---

flake.lock

| [`be659309`](https://github.com/nix-community/nix-index-database/commit/be6593097ad7635defd5e08560cf9952b75f0046) | `` flake.lock: Update `` |

chore(flake/nix-index-database): `93aed672` -> `be659309`

---

flake.lock

| [`07ece11b`](https://github.com/nix-community/nix-index-database/commit/07ece11b22217b8459df589f858e92212b74f1a1) | `` update packages.nix to release 2024-04-21-030753 `` |

chore(flake/nix-index-database): `be659309` -> `07ece11b`

---

flake.lock

| [`4cec20db`](https://github.com/nix-community/home-manager/commit/4cec20dbf5c0a716115745ae32531e34816ecbbe) | `` flake.lock: Update `` |

chore(flake/home-manager): `057117a4` -> `4cec20db`

---

flake.lock

| [`ad83c154`](https://github.com/nix-community/home-manager/commit/ad83c154bdfedad9807e86dd0633729ea3b116c5) | `` qt: fix `qt.platformTheme = "gtk3"` ``    |
| [`147b5a5e`](https://github.com/nix-community/home-manager/commit/147b5a5e1c04e1f27e30b6df720966422fb4bc09) | `` qt: fix platform theme package install `` |

chore(flake/home-manager): `4cec20db` -> `ad83c154`

---

flake.lock

| [`2846d523`](https://github.com/nix-community/home-manager/commit/2846d5230a3c3923618eabb367deaf8885df580f) | `` joplin-desktop: allow undefined options `` |

chore(flake/home-manager): `ad83c154` -> `2846d523`

---

flake.lock

| [`845c6745`](https://github.com/danth/stylix/commit/845c6745108b0ee76361a3d677a2e1df1d3d9487) | `` nixos-icons: remove rendered version of logo (#344) `` |

chore(flake/stylix): `5749cf16` -> `845c6745`

---

flake.lock

| [`670d9ecc`](https://github.com/nix-community/home-manager/commit/670d9ecc3e46a6e3265c203c2d136031a3d3548e) | `` poetry: add module `` |

chore(flake/home-manager): `2846d523` -> `670d9ecc`

---

flake.lock

| Commit                                                                                                | Message                                                                       |
| ----------------------------------------------------------------------------------------------------- | ----------------------------------------------------------------------------- |
| [`f0dcdc1b`](https://github.com/cachix/git-hooks.nix/commit/f0dcdc1b204360250028d6496e265a73049b0e14) | `` Update modules/hooks.nix ``                                                |
| [`f3a2deee`](https://github.com/cachix/git-hooks.nix/commit/f3a2deee819fe462affd678758c969ec4516923e) | `` Remove packageOverrides from the base hook module ``                       |
| …

chore(flake/git-hooks): `40e6053e` -> `2ac4dcbf`

---

flake.lock

| [`e2e7ea9b`](https://github.com/nix-community/home-manager/commit/e2e7ea9b8f3de1e6a09f4fc512eae75f6e413a10) | `` kconfig: fix missing quoting ``      |
| [`2ad154bd`](https://github.com/nix-community/home-manager/commit/2ad154bd1be2441ac8c624704587734dddb9f41a) | `` Translate using Weblate (Swedish) `` |

chore(flake/home-manager): `46833c31` -> `e2e7ea9b`

---

flake.lock

| [`1451d286`](https://github.com/nix-community/home-manager/commit/1451d2866d9ef3739c20f964c9c8bd6db39cc373) | `` foot: unset PATH in server's systemd unit file `` |

chore(flake/home-manager): `e2e7ea9b` -> `1451d286`

---

flake.lock

| [`267cf91e`](https://github.com/danth/stylix/commit/267cf91e0340076e1057cb14930fa8437f591b5a) | `` doc: add documentation for testbeds (#347) ``                     |
| [`2f29ecd3`](https://github.com/danth/stylix/commit/2f29ecd3e4c0ebf75f46647b4c4fb7261b978aac) | `` alacritty: replace base16-alacritty with a custom theme (#346) `` |

chore(flake/stylix): `845c6745` -> `267cf91e`

---

flake.lock

| [`e866aae5`](https://github.com/nix-community/home-manager/commit/e866aae5bbbcfe6798ca05d3004a4e62f1828954) | `` amberol: add module `` |

chore(flake/home-manager): `1451d286` -> `e866aae5`

---

flake.lock

| [`67de98ae`](https://github.com/nix-community/home-manager/commit/67de98ae6eed5ad6f91b1142356d71a87ba97f21) | `` tealdeer: documentation typo `` |

chore(flake/home-manager): `e866aae5` -> `67de98ae`

---

flake.lock

| Commit                                                                                        | Message                                   |
| --------------------------------------------------------------------------------------------- | ----------------------------------------- |
| [`0fe277a3`](https://github.com/danth/stylix/commit/0fe277a3641a849478a94c7900c2d5a90609a306) | `` treewide: remove `lib.mdDoc` (#349) `` |

chore(flake/stylix): `267cf91e` -> `0fe277a3`

---

flake.lock

| [`797f8d80`](https://github.com/NixOS/nixos-hardware/commit/797f8d8082c7cc3259cba7275c699d4991b09ecc) | `` TUXEDO Pulse 14 Gen3: init `` |
| [`c056352c`](https://github.com/NixOS/nixos-hardware/commit/c056352c4c63f8b9707ebf4f8a8fcc1d5b7950a8) | `` fix mergify configuration ``  |

chore(flake/nixos-hardware): `5d48925b` -> `797f8d80`

---

flake.lock

| Commit                                                                                                            | Message                                      |
| ----------------------------------------------------------------------------------------------------------------- | -------------------------------------------- |
| [`dcb6ac44`](https://github.com/nix-community/nix-index-database/commit/dcb6ac44922858ce3a5b46f77a36d6030181460c) | `` hm: Symlink per default only if needed `` |
| [`622b16b7`](https://github.com/nix-community/nix-index-database/commit/622b16b7d8b8697e40cb2e1d10e37188df02bfc2) | `` update to new merge configuration ``      |
| [`ed94c127`](https://github.com/nix-community/nix-index-database/commit/ed94c127153dccb088aa1a6c47d01cfdbdd07bc7) | `` mergify: also …

chore(flake/nix-index-database): `07ece11b` -> `dcb6ac44`

---

flake.lock

| Commit                                                                                           | Message                                                     |
| ------------------------------------------------------------------------------------------------ | ----------------------------------------------------------- |
| [`ec06ea88`](https://github.com/LnL7/nix-darwin/commit/ec06ea883757c6075c61d1426f40719742d51f59) | `` nix-daemon: increase SoftResourceLimits.NumberOfFiles `` |

chore(flake/darwin): `9e7c20ff` -> `230a1970`

---

flake.lock

| [`9052a48b`](https://github.com/cachix/git-hooks.nix/commit/9052a48b2ad895e0cb3d28d874fe1d423566bd54) | `` refactor: move `rec` keyword to minimize formatting impact `` |
| [`bf98b7f1`](https://github.com/cachix/git-hooks.nix/commit/bf98b7f1d0983c091376d5191994d29927d51075) | `` feat: add deprecation warning for `rome` hook ``              |
| [`8f2d990b`](https://github.com/cachix/git-hooks.nix/commit/8f2d990b994d242f53fd725b50ec8ef9a4d8c512) | …

chore(flake/git-hooks): `2ac4dcbf` -> `6fb82e44`

---

flake.lock

| [`bfa7c064`](https://github.com/nix-community/home-manager/commit/bfa7c06436771e3a0c666ccc6ee01e815d4c33aa) | `` swayosd: add custom style option ``                |
| [`33a20182`](https://github.com/nix-community/home-manager/commit/33a20182e3164f451b6a4ac2ecadcab5c2c36703) | `` home-manager: improve session variables comment `` |

chore(flake/home-manager): `67de98ae` -> `bfa7c064`

---

flake.lock

| [`0c5704ec`](https://github.com/nix-community/home-manager/commit/0c5704eceefcb7bb238a958f532a86e3b59d76db) | `` home-manager: make newsReadIdsFile more reliable ``       |
| [`6864ca2d`](https://github.com/nix-community/home-manager/commit/6864ca2d2657d57a041110dcaf8be0c4b71346c0) | `` Add translation using Weblate (Icelandic) ``              |
| [`3ebcff8d`](https://github.com/nix-community/home-manager/commit/3ebcff8d1219c9e0fb3c880ef7959fec …

chore(flake/home-manager): `bfa7c064` -> `0c5704ec`

---

flake.lock

| Commit                                                                                               | Message                                               |
| ---------------------------------------------------------------------------------------------------- | ----------------------------------------------------- |
| [`c6aaf729`](https://github.com/numtide/treefmt-nix/commit/c6aaf729f34a36c445618580a9f95a48f5e4e03f) | `` ruff: allow both checking and formatting (#175) `` |

chore(flake/treefmt): `49dc4a92` -> `c6aaf729`

---

flake.lock

| Commit                                                                                         | Message                               |
| ---------------------------------------------------------------------------------------------- | ------------------------------------- |
| [`2c1d1fb1`](https://github.com/ryantm/agenix/commit/2c1d1fb13467184256e352b00ed2d89046c16cd6) | `` fix: allow for newlines in keys `` |

chore(flake/agenix): `1381a759` -> `24a7ea39`

---

flake.lock

| [`9821d2c5`](https://github.com/NixOS/nixos-hardware/commit/9821d2c5438edbb567190377bcec4b640ad100c6) | `` asus/pro-ws-x570-ace: init ``                                         |
| [`1bcf7164`](https://github.com/NixOS/nixos-hardware/commit/1bcf716420ac6152edcd1277c743292da6b87529) | `` starfive visionfive2: use nixpkgs default u-boot version ``           |
| [`7e3a3f31`](https://github.com/NixOS/nixos-hardware/commit/7e3a3f31706760 …

chore(flake/nixos-hardware): `797f8d80` -> `9821d2c5`

---

flake.lock

| [`c1609d58`](https://github.com/nix-community/home-manager/commit/c1609d584a6b5e9e6a02010f51bd368cb4782f8e) | `` xdg-portal: improve description of `enable` option `` |
| [`26e72d85`](https://github.com/nix-community/home-manager/commit/26e72d85e6fbda36bf2266f1447215501ec376fd) | `` home-manager: set module class to "homeManager" ``    |

chore(flake/home-manager): `0c5704ec` -> `c1609d58`

---

flake.lock

| [`53db5e10`](https://github.com/NixOS/nixos-hardware/commit/53db5e1070d07e750030bf65f1b9963df8f0c678) | `` protectli/vp4670: add Super I/O kernel module `` |

chore(flake/nixos-hardware): `9821d2c5` -> `53db5e10`

---

flake.lock

| [`3a859831`](https://github.com/nix-community/nix-index-database/commit/3a85983125dea5cf40b86e28b50fcd7f84546e53) | `` flake.lock: Update `` |

chore(flake/nix-index-database): `dcb6ac44` -> `3a859831`

---

flake.lock

| [`941c4973`](https://github.com/nix-community/nix-index-database/commit/941c4973c824509e0356be455d89613611f76c8a) | `` update packages.nix to release 2024-04-28-030722 `` |

chore(flake/nix-index-database): `3a859831` -> `941c4973`

---

flake.lock

| [`02002a08`](https://github.com/nix-community/home-manager/commit/02002a08b489b43e3ac1400609a9bf1b7c08e384) | `` flake.lock: Update `` |
| [`d1980931`](https://github.com/nix-community/home-manager/commit/d1980931de8252b6ac1104b7191fd68bbbe3a291) | `` psd: add module ``    |

chore(flake/home-manager): `c1609d58` -> `02002a08`

---

flake.lock

| [`c002bc08`](https://github.com/nix-community/home-manager/commit/c002bc08c8ea6c87198f3024e8bfd6fdb1c90c9e) | `` cliphist: support images in clipboard history `` |

chore(flake/home-manager): `02002a08` -> `c002bc08`

---

flake.lock

| [`9fe79591`](https://github.com/nix-community/home-manager/commit/9fe79591c1005ce6f93084ae7f7dab0a2891440d) | `` direnv: add nix-direnv to lib instead of sourcing `` |

chore(flake/home-manager): `c002bc08` -> `9fe79591`

---

flake.lock

| [`804480fc`](https://github.com/NixOS/nixpkgs/commit/804480fc088b9f64ec6f906621bc7a83d014731a) | `` maintainers: remove msfjarvis ``                                            |
| [`f0d119ad`](https://github.com/NixOS/nixpkgs/commit/f0d119ad91d0d7d25816b10d9c1e7653ecd5c5d3) | `` gitu: 0.17.1 -> 0.19.2 ``                                                   |
| [`e8da6935`](https://github.com/NixOS/nixpkgs/commit/e8da693588000806c4a23d8c7 …

chore(flake/nixpkgs): `66adc1e4` -> `58a1abdb`

---

flake.lock

| [`2af7c78b`](https://github.com/nix-community/home-manager/commit/2af7c78b7bb9cf18406a193eba13ef9f99388f49) | `` thefuck: add nushell integration `` |

chore(flake/home-manager): `9fe79591` -> `2af7c78b`

---

flake.lock

| [`b8d81ef1`](https://github.com/nix-community/home-manager/commit/b8d81ef15ed8ec4c72ffc610279d39aa0c4ccbf0) | `` mpv: add extraInput option `` |

chore(flake/home-manager): `2af7c78b` -> `b8d81ef1`

---

flake.lock

| [`1a91cb7c`](https://github.com/nix-community/home-manager/commit/1a91cb7cdbcf6b18c27bbead57241baf279d4513) | `` neomutt: allow binds to override vimKeys ``      |
| [`7ec0ae18`](https://github.com/nix-community/home-manager/commit/7ec0ae18cda5e3aae80996d35f6d0ebd418f1ac8) | `` Translate using Weblate (Japanese) ``            |
| [`ba97ffcf`](https://github.com/nix-community/home-manager/commit/ba97ffcfb2bd3ef026bb0a14d8808e9926f57fd7) | `` Translate using …

chore(flake/home-manager): `b8d81ef1` -> `1a91cb7c`

---

flake.lock

| [`68d680c1`](https://github.com/NixOS/nixos-hardware/commit/68d680c1b7c0e67a9b2144d6776583ee83664ef4) | `` Changed the kernel parameter ``      |
| [`fc738b1f`](https://github.com/NixOS/nixos-hardware/commit/fc738b1ff669bcb355165489453c685f853d9ae0) | `` kernel mkDefault added for kernel `` |
| [`627652ae`](https://github.com/NixOS/nixos-hardware/commit/627652ae642e24ed5119ddc08115c42845609929) | `` Updated read me ``                   |
| …

chore(flake/nixos-hardware): `53db5e10` -> `68d680c1`

---

flake.lock

| [`f8e6694e`](https://github.com/nix-community/home-manager/commit/f8e6694edabe4aaa7a85aac47b43ea5d978b116d) | `` files: make collision error message more helpful `` |
| [`56326598`](https://github.com/nix-community/home-manager/commit/563265988637c27ba3abe39acb9be3ba2cb35a29) | `` swaync: add module ``                               |
| [`0125041f`](https://github.com/nix-community/home-manager/commit/0125041fc9ca3127fe95cf53f15c49c482ebaf70) | `` …

chore(flake/home-manager): `1a91cb7c` -> `f8e6694e`

---

flake.lock

| [`091eaa3a`](https://github.com/cachix/git-hooks.nix/commit/091eaa3a4130a2d447901e4f14a2b0f061fcd90e) | `` Fix and document lacheck hook `` |

chore(flake/git-hooks): `6fb82e44` -> `2849da03`

---

flake.lock

| [`3c0df2a7`](https://github.com/nix-community/home-manager/commit/3c0df2a7e43b432b739d8e9d289dcb362a44b308) | `` freetube: add module `` |

chore(flake/home-manager): `f8e6694e` -> `3c0df2a7`

---

flake.lock

| [`6d3b6dc9`](https://github.com/nix-community/home-manager/commit/6d3b6dc9222c12b951169becdf4b0592ee9576ef) | `` conky: add module ``           |
| [`28ef93bb`](https://github.com/nix-community/home-manager/commit/28ef93bb8e5208ae4230f59efe7b96e115e5ddd2) | `` maintainers: add kaleocheng `` |

chore(flake/home-manager): `3c0df2a7` -> `6d3b6dc9`

---

flake.lock

| [`43d23b16`](https://github.com/danth/stylix/commit/43d23b1609b87f6a4100db2a09bd118c52c78766) | `` bat: use config instead of env variable (#353) `` |

chore(flake/stylix): `0fe277a3` -> `43d23b16`

---

flake.lock

| [`9036fe9e`](https://github.com/nix-community/home-manager/commit/9036fe9ef8e15a819fa76f47a8b1f287903fb848) | `` flake.lock: Update ``                |
| [`67d0e7db`](https://github.com/nix-community/home-manager/commit/67d0e7db8827abc3634c02de62f3e651a0c92d8c) | `` Translate using Weblate (Persian) `` |

chore(flake/home-manager): `6d3b6dc9` -> `9036fe9e`

---

core/nix.nix
flake.lock
hosts/poincare/default.nix
nix/overlays/nix-latest.nix

| Commit                                                                                         | Message                                                                                 |
| ---------------------------------------------------------------------------------------------- | --------------------------------------------------------------------------------------- |
| [`a1de57d6`](https://github.com/NixOS/nixpkgs/commit/a1de57d6fc1c292db47c2b0debf404d46dd6dc49) | `` nixos/all-tests: skip hibernate test for now ``                                      |
| [`f674b11e`](https://github.com/NixOS/nixpkgs/commit/f674b11e2a834f6413599731ff13a0821e11d6ab) | `` eza: 0.18.13 -> 0.18.14 ``                                                           |
| …

chore(flake/nixpkgs): `58a1abdb` -> `63c3a29c`

---

flake.lock

| [`3f017311`](https://github.com/NixOS/nixos-hardware/commit/3f017311191fe6d501ca2496a835d012f656ee9c) | `` lenovo/thinkpad/l480: init `` |

chore(flake/nixos-hardware): `68d680c1` -> `3f017311`

---

flake.lock

| Commit                                                                                                      | Message                      |
| ----------------------------------------------------------------------------------------------------------- | ---------------------------- |
| [`e0825ea2`](https://github.com/nix-community/home-manager/commit/e0825ea2112d09d9f0680833cd716f6aee3b973f) | `` swaync: fix style path `` |

chore(flake/home-manager): `9036fe9e` -> `e0825ea2`

---

flake.lock

| [`7a20d550`](https://github.com/nix-community/nix-index-database/commit/7a20d550bed76a862e355181d1eb5f23a6c86272) | `` flake.lock: Update `` |

chore(flake/nix-index-database): `941c4973` -> `7a20d550`
