lovesegfault/nix-config

- flake.lock
| [`a362555e`](https://github.com/nix-community/nix-index-database/commit/a362555e9dbd4ecff3bb98969bbdb8f79fe87f10) | `` update packages.nix to release 2024-05-05-030852 `` |
> chore(flake/nix-index-database): `7a20d550` -> `a362555e`

- flake.lock
| [`753176b5`](https://github.com/NixOS/nixos-hardware/commit/753176b57b3fcddb140c1c012868e62c025120bd) | `` Add fingerprint support for Lenovo Legion 16ARHA7 `` |
| [`d623635b`](https://github.com/NixOS/nixos-hardware/commit/d623635bb7d9262c0422af8f74599c6b3cf60180) | `` surface: linux 6.8.6 -> 6.8.9 ``                     |
> chore(flake/nixos-hardware): `3f017311` -> `753176b5`

- flake.lock
| [`f69bf670`](https://github.com/nix-community/home-manager/commit/f69bf670d29d3921e00cc626d174654769d743c6) | `` cliphist: add extraOptions option `` |
| [`2a44f4d0`](https://github.com/nix-community/home-manager/commit/2a44f4d09f891d8a9d72b9a7331fa8d94b066119) | `` flake.lock: Update ``                |
> chore(flake/home-manager): `e0825ea2` -> `f69bf670`

- flake.lock
| [`3dfe05aa`](https://github.com/nix-community/home-manager/commit/3dfe05aa9b5646995ace887931fa60269a039777) | `` wlsunset: update options `` |
| [`fdaaf543`](https://github.com/nix-community/home-manager/commit/fdaaf543bad047639ef0b356ea2e6caec2f1215c) | `` hypridle: add module ``     |
> chore(flake/home-manager): `f69bf670` -> `3dfe05aa`

- flake.lock
| [`2b87a111`](https://github.com/nix-community/home-manager/commit/2b87a11125f988a9f67ee63eeaa3682bc841d9b5) | `` git: add realName inside From field `` |
> chore(flake/home-manager): `3dfe05aa` -> `2b87a111`

- flake.lock
| [`8a4adfe4`](https://github.com/NixOS/nixos-hardware/commit/8a4adfe48b68b50ef62e9a299898093436269b6d) | `` raspberry-pi/5: don't use overlay ``            |
| [`1d11c108`](https://github.com/NixOS/nixos-hardware/commit/1d11c108000d498af656dfa3ede9ce25839c9948) | `` raspberry-pi/5: add kernel version assertion `` |
| [`11d92d24`](https://github.com/NixOS/nixos-hardware/commit/11d92d24440b390d7d7998a383e4f64daf1fa1c3) | `` raspberry-pi/5: add to flake.nix ``             |
| …
> chore(flake/nixos-hardware): `753176b5` -> `8a4adfe4`

- flake.lock
| [`e148ccbe`](https://github.com/NixOS/nixos-hardware/commit/e148ccbecbd2fe4dc4768fba67f6db828466ad06) | `` framework: install framework-tool ``              |
| [`88eb241b`](https://github.com/NixOS/nixos-hardware/commit/88eb241bbd87e21bbf6c8be7319fe997550b90f8) | `` framework/16-inch: moved out of the CPU folder `` |
> chore(flake/nixos-hardware): `8a4adfe4` -> `e148ccbe`

- flake.lock
| [`6ebe7be2`](https://github.com/nix-community/home-manager/commit/6ebe7be2e67be7b9b54d61ce5704f6fb466c536f) | `` gnome-shell: add module `` |
> chore(flake/home-manager): `2b87a111` -> `6ebe7be2`

- flake.lock
| Commit                                                                                        | Message                  |
| --------------------------------------------------------------------------------------------- | ------------------------ |
| [`61c024f8`](https://github.com/danth/stylix/commit/61c024f839ceb9787c1441fae718dc2077bde2ce) | `` gitui: init (#354) `` |
> chore(flake/stylix): `43d23b16` -> `61c024f8`

- flake.lock
| [`d1659c9e`](https://github.com/NixOS/nixos-hardware/commit/d1659c9eb8af718118fb4bbe2c86797c8b8623eb) | `` Update flake.nix for ThinkPad A475 `` |
| [`00e73a45`](https://github.com/NixOS/nixos-hardware/commit/00e73a4509f9112f33188a24e56d9cc61523fd3b) | `` Update README.md for ThinkPad A475 `` |
| [`1a770577`](https://github.com/NixOS/nixos-hardware/commit/1a770577450681a835733a0f50a87a71ff5e4ee0) | `` added thinkpad a470 ``                |
> chore(flake/nixos-hardware): `e148ccbe` -> `d1659c9e`

- flake.lock
| [`6e277d95`](https://github.com/nix-community/home-manager/commit/6e277d9566de9976f47228dd8c580b97488734d4) | `` jujutsu: add ediff option `` |
> chore(flake/home-manager): `6ebe7be2` -> `6e277d95`

- flake.lock
| Commit                                                                                         | Message                                |
| ---------------------------------------------------------------------------------------------- | -------------------------------------- |
| [`07479c2e`](https://github.com/ryantm/agenix/commit/07479c2e7396acaaaac5925483498154034ea80a) | `` update link to nixos wiki (#258) `` |
> chore(flake/agenix): `24a7ea39` -> `07479c2e`

- flake.lock
| [`8f7abd22`](https://github.com/danth/stylix/commit/8f7abd2252d0d773ca202cf2c190b47d439f045d) | `` vscode: improve text contrast for diffs and merges (#358) `` |
> chore(flake/stylix): `61c024f8` -> `8f7abd22`

- flake.lock
| [`a4e2b790`](https://github.com/NixOS/nixos-hardware/commit/a4e2b7909fc1bdf30c30ef21d388fde0b5cdde4a) | `` helios4: remove need for overlay ``                      |
| [`6cb18a66`](https://github.com/NixOS/nixos-hardware/commit/6cb18a664904afae03501ee613797f502030ee37) | `` purism/librem/5r4: make it usuable without an overlay `` |
> chore(flake/nixos-hardware): `d1659c9e` -> `a4e2b790`

- flake.lock
| Commit                                                                                         | Message                                                                                   |
| ---------------------------------------------------------------------------------------------- | ----------------------------------------------------------------------------------------- |
| [`e027db61`](https://github.com/NixOS/nixpkgs/commit/e027db61dc24e1efbf15a1624bc59fcbe890b773) | `` python311Packages.pettingzoo: init at 1.24.3 ``                                        |
| [`8224753d`](https://github.com/NixOS/nixpkgs/commit/8224753ddf178ecb7e86b742506010b9f3d03c46) | `` python311Packages.pytest-markdown-docs: init at 0.5.1 ``                               |
| …
> chore(flake/nixpkgs): `63c3a29c` -> `b211b392`

- flake.lock
| [`19752692`](https://github.com/danth/stylix/commit/197526923a2929b223bab3e36d3aa240f5f84870) | `` gnome: update to GNOME 46 (#357) `` |
> chore(flake/stylix): `f1bb5c50` -> `19752692`

- flake.lock
| Commit                                                                                         | Message        |
| ---------------------------------------------------------------------------------------------- | -------------- |
| [`63a57d8d`](https://github.com/ryantm/agenix/commit/63a57d8dfb16daca46721fdc505fee7cc2eb4cbf) | `` Fix typo `` |
> chore(flake/agenix): `07479c2e` -> `8d37c5bd`

- flake.lock
| [`f61917cb`](https://github.com/nix-community/home-manager/commit/f61917cbaa6dba317e757aefd0bbb56403aff2f8) | `` fastfetch: add module `` |
> chore(flake/home-manager): `6e277d95` -> `f61917cb`

- flake.lock
| [`4855bfb6`](https://github.com/nix-community/home-manager/commit/4855bfb6ce20225a1b0e2aae2379da909ab38350) | `` kanshi: update configuration to better match upstream `` |
> chore(flake/home-manager): `f61917cb` -> `4855bfb6`

- flake.lock
| [`22374331`](https://github.com/nix-community/home-manager/commit/223743313bab8b0b44a57eaf9573de9f69082b4d) | `` hyprpaper: add module `` |
| [`c6ddd80f`](https://github.com/nix-community/home-manager/commit/c6ddd80fb1e5a286b3a5cb32ef94a2e4e346a9d3) | `` hyprlock: add module ``  |
> chore(flake/home-manager): `4855bfb6` -> `22374331`

- flake.lock
| [`e6a31590`](https://github.com/nix-community/home-manager/commit/e6a315900db775da3bb3138bab8caa70dafdaf9e) | `` flake.lock: Update ``                                    |
| [`f55718ae`](https://github.com/nix-community/home-manager/commit/f55718aec361f6a5101f07e3203106f85d6cad20) | `` hyprland: add support for XDG autostart using systemd `` |
> chore(flake/home-manager): `22374331` -> `e6a31590`

- flake.lock
| [`f2c5ba5e`](https://github.com/nix-community/home-manager/commit/f2c5ba5e720fd584d83f2f97399dac0d26ae60b9) | `` fontconfig: add defaultFonts.* options `` |
> chore(flake/home-manager): `e6a31590` -> `f2c5ba5e`

- flake.lock
| [`5514ed32`](https://github.com/nix-community/home-manager/commit/5514ed321087f0b5af42564352d135acad4ff055) | `` yambar: add module `` |
> chore(flake/home-manager): `f2c5ba5e` -> `5514ed32`

- flake.lock
| [`d7682620`](https://github.com/nix-community/home-manager/commit/d7682620185f213df384c363288093b486b2883f) | `` jujutsu: switch to XDG config home ``                 |
| [`d939ce58`](https://github.com/nix-community/home-manager/commit/d939ce585c611c00ca44145a74acab04c20619ad) | `` mopidy: make scan service depend on `mopidy-local` `` |
| [`15d7ec30`](https://github.com/nix-community/home-manager/commit/15d7ec30511199349c6cf8b6cbdc5e205a6a15e8) | `` …
> chore(flake/home-manager): `5514ed32` -> `d7682620`

- flake.lock
| Commit                                                                                        | Message                                  |
| --------------------------------------------------------------------------------------------- | ---------------------------------------- |
| [`f83376bf`](https://github.com/danth/stylix/commit/f83376bfdc375e54196e953665997ede027eae86) | `` doc: update NixOS wiki link (#363) `` |
> chore(flake/stylix): `19752692` -> `f83376bf`

- flake.lock
| [`03c449f9`](https://github.com/nix-community/nix-index-database/commit/03c449f9a0d87c3cca9b0c6002bd3782790215cf) | `` flake.lock: Update `` |
> chore(flake/nix-index-database): `a362555e` -> `03c449f9`

- flake.lock
| [`f9027322`](https://github.com/nix-community/nix-index-database/commit/f9027322f48b427da23746aa359a6510dfcd0228) | `` update packages.nix to release 2024-05-12-030850 `` |
> chore(flake/nix-index-database): `03c449f9` -> `f9027322`

- flake.lock
| Commit                                                                                        | Message                                                 |
| --------------------------------------------------------------------------------------------- | ------------------------------------------------------- |
| [`98039f33`](https://github.com/danth/stylix/commit/98039f333191b25720759c35c527a291a85cf28a) | `` gnome: change panel background to `base01` (#360) `` |
> chore(flake/stylix): `f83376bf` -> `98039f33`

- flake.lock
| [`b5f4ca49`](https://github.com/danth/stylix/commit/b5f4ca49df372c3d26ce04b1554fb02a0107cc8d) | `` stylix: provide root access in testbeds (#362) `` |
> chore(flake/stylix): `98039f33` -> `b5f4ca49`

- flake.lock
| [`cfff239d`](https://github.com/Mic92/nix-fast-build/commit/cfff239d93716e92f6467f8953d8f8c12da1892a) | `` Update cachix/install-nix-action action to v27 `` |
> chore(flake/nix-fast-build): `071d4468` -> `cfff239d`

- flake.lock
| [`772de835`](https://github.com/NixOS/nixos-hardware/commit/772de835d56f2f83277c57fcf1afb5a280c08589) | `` Remove buildUBoot function from U-Boot build `` |
> chore(flake/nixos-hardware): `a4e2b790` -> `772de835`

- flake.lock
| Commit                                                                                                | Message                                                            |
| ----------------------------------------------------------------------------------------------------- | ------------------------------------------------------------------ |
| [`ff1be1e3`](https://github.com/NixOS/nixos-hardware/commit/ff1be1e3cdf884df0935ab28745ab13c3c26d828) | `` Add missing default xps-15-9570 module to flake.nix ``          |
| [`d68be3e5`](https://github.com/NixOS/nixos-hardware/commit/d68be3e5e21d829ebce080d96747508fc27ea4e3) | `` Fixed error ``                                                  |
| [`9f730206`](https://github.com/NixOS/nixos-hardware/commit/9f7302060cdf9fa7e306bf00815b7188346c9d …
> chore(flake/nixos-hardware): `772de835` -> `ff1be1e3`

- flake.lock
| [`af8e54c9`](https://github.com/numtide/treefmt-nix/commit/af8e54c9622fd902b0f34d6988955ece73ba82a1) | `` choose local that is compatible with macOS (#176) `` |
> chore(flake/treefmt): `c6aaf729` -> `af8e54c9`

- flake.lock
| Commit                                                                                               | Message                                           |
| ---------------------------------------------------------------------------------------------------- | ------------------------------------------------- |
| [`9ce80293`](https://github.com/numtide/treefmt-nix/commit/9ce802936aec6c01c46671fa9e1a56cbbe08fdaf) | `` feat: make treefmt settings a freeform type `` |
> chore(flake/treefmt): `af8e54c9` -> `2fba33a1`

- flake.lock
| [`b55712de`](https://github.com/NixOS/nixos-hardware/commit/b55712de78725c8fcde422ee0a0fe682046e73c3) | `` apple/t2: update to kernel 6.9 `` |
> chore(flake/nixos-hardware): `ff1be1e3` -> `b55712de`

- flake.lock
| [`76e7daf5`](https://github.com/danth/stylix/commit/76e7daf5a16d442ac98e844582f7dc1354610886) | `` doc: explain using `lib.stylix.colors` (#328) ``            |
| [`4a4c82f0`](https://github.com/danth/stylix/commit/4a4c82f03ccf71707550bca3b39928c68c40644e) | `` grub: use fc-match format option rather than grep (#368) `` |
> chore(flake/stylix): `b5f4ca49` -> `76e7daf5`

- flake.lock
| [`c5f9740d`](https://github.com/nix-community/nix-index-database/commit/c5f9740d79d5307dc7a739c652dc1146554d39a6) | `` flake.lock: Update `` |
> chore(flake/nix-index-database): `f9027322` -> `c5f9740d`

- flake.lock
| [`6b94c48c`](https://github.com/nix-community/nix-index-database/commit/6b94c48c3bb22d5181333c3fb71beff44116e251) | `` update packages.nix to release 2024-05-19-030652 `` |
> chore(flake/nix-index-database): `c5f9740d` -> `6b94c48c`

- flake.lock
| [`f0cf5687`](https://github.com/NixOS/nixos-hardware/commit/f0cf56878046c42ec2096a2ade89203e7348917b) | `` common/gpu/intel: add extraPackages32 ``                 |
| [`e85c7a78`](https://github.com/NixOS/nixos-hardware/commit/e85c7a78d2657f852a931db3e782c4fab8196fb7) | `` lenovo/thinkpad/t14/amd/gen3: enable amd_pstate ``       |
| [`81f14570`](https://github.com/NixOS/nixos-hardware/commit/81f14570232388b80e62874b2a8153ee53362891) | `` …
> chore(flake/nixos-hardware): `b55712de` -> `f0cf5687`

- flake.lock
| [`d9e0b262`](https://github.com/NixOS/nixos-hardware/commit/d9e0b26202fd500cf3e79f73653cce7f7d541191) | `` build(deps): bump cachix/install-nix-action from 26 to 27 `` |
> chore(flake/nixos-hardware): `f0cf5687` -> `d9e0b262`

- flake.lock
| [`81df8443`](https://github.com/danth/stylix/commit/81df8443556335016d6f0bc22630a95776a56d8b) | `` vesktop: init (#365) `` |
> chore(flake/stylix): `76e7daf5` -> `81df8443`

- flake.lock
| Commit                                                                                        | Message                                                                    |
| --------------------------------------------------------------------------------------------- | -------------------------------------------------------------------------- |
| [`e7543c51`](https://github.com/danth/stylix/commit/e7543c51eff9e73c85450c473e1f24513a5e0a0f) | `` doc: fix link for "Installing Home Manager as a NixOS module" (#385) `` |
| [`23cbb966`](https://github.com/danth/stylix/commit/23cbb966386dda61720266ec4406b6633ba07317) | `` doc: refresh screenshots (#382) ``                                      |
| [`f9bf9764`](https://github.com/danth/stylix/commit/f9bf97645b41c5fcf28f044ab2b72f1b60a8ef9c) | …
> chore(flake/stylix): `81df8443` -> `e7543c51`

- flake.lock
| [`25dedb0d`](https://github.com/nix-community/home-manager/commit/25dedb0d52c20448f6a63cc346df1adbd6ef417e) | `` version: allow 24.11 as state version `` |
> chore(flake/home-manager): `e3ad5108` -> `25dedb0d`

- flake.lock
| [`290c8aef`](https://github.com/danth/stylix/commit/290c8aef476ce98fff9cefc059284429d561a085) | `` doc: Plasma 6 → Plasma 5 (#387) `` |
> chore(flake/stylix): `e7543c51` -> `290c8aef`

- flake.lock
| [`850cb322`](https://github.com/nix-community/home-manager/commit/850cb322046ef1a268449cf1ceda5fd24d930b05) | `` ci: make dependabot consider the release-24.05 `` |
> chore(flake/home-manager): `25dedb0d` -> `850cb322`

- flake.lock
| Commit                                                                                         | Message                                          |
| ---------------------------------------------------------------------------------------------- | ------------------------------------------------ |
| [`1746e4f5`](https://github.com/ryantm/agenix/commit/1746e4f5ec0849a50c2b7b634b4b84e3e09c6f87) | `` agenix: fix installCheckPhase with Nix 2.3 `` |
> chore(flake/agenix): `8d37c5bd` -> `c2fc0762`

- flake.lock
| [`d179da4e`](https://github.com/nix-community/home-manager/commit/d179da4e81bcd4227e8abf4b62b92c4ae214ae39) | `` home-manager: prepare 24.11-pre ``     |
| [`548ba194`](https://github.com/nix-community/home-manager/commit/548ba194d0676849424657cc41c59ab57d94b344) | `` home-manager: prepare release 24.05 `` |
> chore(flake/home-manager): `850cb322` -> `d179da4e`

- flake.lock
| [`e4611630`](https://github.com/nix-community/home-manager/commit/e4611630c3cc8ed618b48d92f6291f65be9f7913) | `` ci: fix manual build in sourcehut build `` |
> chore(flake/home-manager): `d179da4e` -> `e4611630`

- flake.lock
| [`693705f2`](https://github.com/nix-community/nix-index-database/commit/693705f22a9d378c203ad5304a7e630c6b03048f) | `` flake.lock: Update `` |
> chore(flake/nix-index-database): `e0638db3` -> `693705f2`

- flake.lock
| [`6e4a2b3b`](https://github.com/nix-community/nix-index-database/commit/6e4a2b3b7c60aae5dac8c21117a134a4a56648da) | `` update packages.nix to release 2024-05-26-030820 `` |
> chore(flake/nix-index-database): `693705f2` -> `6e4a2b3b`

- flake.lock
| [`d789d9a2`](https://github.com/NixOS/nixos-hardware/commit/d789d9a2de2cea67655d38b7a37a30bdb1838e8b) | `` Add Surface Pro 9 to Readme ``                                |
| [`1af5ef15`](https://github.com/NixOS/nixos-hardware/commit/1af5ef15469a55bef1a9136324437e4ddede2c5c) | `` Add Readme for Surface Pro 9 ``                               |
| [`7caa5b2a`](https://github.com/NixOS/nixos-hardware/commit/7caa5b2a35c4ae70328f853b3fe24870cb35a8a6) | …
> chore(flake/nixos-hardware): `d9e0b262` -> `d789d9a2`

- flake.lock
| [`6a35d196`](https://github.com/nix-community/home-manager/commit/6a35d1969e4626a0f8d285e60b6cfd331e2687a9) | `` ci: bump cachix/cachix-action from 13 to 15 `` |
> chore(flake/home-manager): `e4611630` -> `6a35d196`

- flake.lock
| Commit                                                                                                | Message                        |
| ----------------------------------------------------------------------------------------------------- | ------------------------------ |
| [`2e7d6c56`](https://github.com/NixOS/nixos-hardware/commit/2e7d6c568063c83355fe066b8a8917ee758de1b8) | `` asus/zenbook/ux371: init `` |
> chore(flake/nixos-hardware): `d789d9a2` -> `2e7d6c56`

- flake.lock
| [`05e6ba83`](https://github.com/nix-community/home-manager/commit/05e6ba83eb3585ce0aff7b41e4bd0e317d05ad4a) | `` Translate using Weblate (Danish) ``               |
| [`517682ed`](https://github.com/nix-community/home-manager/commit/517682ed21a19c193f09f043ecd8dc4002a962c3) | `` Translate using Weblate (Japanese) ``             |
| [`cd29501b`](https://github.com/nix-community/home-manager/commit/cd29501b799c2621276376fb714cd2532fb2f0f7) | `` Translate using …
> chore(flake/home-manager): `6a35d196` -> `05e6ba83`

- flake.lock
| [`5d151429`](https://github.com/nix-community/home-manager/commit/5d151429e1e79107acf6d06dcc5ace4e642ec239) | `` kanshi: fix configuration example `` |
| [`b2a4ddf6`](https://github.com/nix-community/home-manager/commit/b2a4ddf657e6ad87569665545ffaf7dd5e9a02af) | `` flake.lock: Update ``                |
> chore(flake/home-manager): `05e6ba83` -> `5d151429`

- flake.lock
| [`00a11ba2`](https://github.com/danth/stylix/commit/00a11ba2f0b52f761c0bc77daebb00cb4d44ba09) | `` wpaperd: init (#383) `` |
> chore(flake/stylix): `290c8aef` -> `00a11ba2`

- flake.lock
| Commit                                                                                                            | Message                                                    |
| ----------------------------------------------------------------------------------------------------------------- | ---------------------------------------------------------- |
| [`ff80cb4a`](https://github.com/nix-community/nix-index-database/commit/ff80cb4a11bb87f3ce8459be6f16a25ac86eb2ac) | `` build(deps): bump cachix/cachix-action from 14 to 15 `` |
> chore(flake/nix-index-database): `6e4a2b3b` -> `ff80cb4a`

- flake.lock
| [`9a20e17a`](https://github.com/NixOS/nixos-hardware/commit/9a20e17a73b052d6be912adcee220cb483477094) | `` added lenovo legion 15ach6h to README ``    |
| [`6d24140f`](https://github.com/NixOS/nixos-hardware/commit/6d24140f51333fc5021dea0ae5faef1bd19020be) | `` added lenovo legion 15ach6h to flake.nix `` |
> chore(flake/nixos-hardware): `2e7d6c56` -> `9a20e17a`

- flake.lock
| [`939375b3`](https://github.com/nix-community/home-manager/commit/939375b39661c7b5d2533c9cd7be6117ed98896a) | `` khal: add package option ``                          |
| [`7e769959`](https://github.com/nix-community/home-manager/commit/7e769959e8ec80333bb262d685333003bf013c1b) | `` hyprland: onChange: remove subshell comment ``       |
| [`7ac529c2`](https://github.com/nix-community/home-manager/commit/7ac529c22129ee9fb024744ede18f73e6b148ede) | `` …
> chore(flake/home-manager): `5d151429` -> `939375b3`

- flake.lock
| [`10c7c219`](https://github.com/nix-community/home-manager/commit/10c7c219b7dae5795fb67f465a0d86cbe29f25fa) | `` listenbrainz-mpd: fix config example `` |
| [`90010df1`](https://github.com/nix-community/home-manager/commit/90010df15878762ff359e4fe391355a9dcad0bcf) | `` topgrade: update example config ``      |
> chore(flake/home-manager): `939375b3` -> `10c7c219`

- flake.lock
| Commit                                                                                                | Message                                                       |
| ----------------------------------------------------------------------------------------------------- | ------------------------------------------------------------- |
| [`806e9d4a`](https://github.com/NixOS/nixos-hardware/commit/806e9d4a933dd1e75592e88894d4bd2f296f5bbf) | `` Fix typo for IdeaPad 3 15alc6 in README.md ``              |
| [`d664fb04`](https://github.com/NixOS/nixos-hardware/commit/d664fb04deaa8e344ce86b485a7a8d685238a4c3) | `` add Lenovo IdeaPad 3 15alc6 ``                             |
| [`a44ddc27`](https://github.com/NixOS/nixos-hardware/commit/a44ddc27b1180dfa1037201871d1c717e8f69372) | `` Revert …
> chore(flake/nixos-hardware): `9a20e17a` -> `806e9d4a`

- flake.lock
| [`5234b3d4`](https://github.com/danth/stylix/commit/5234b3d467aa803ad8d3fe898ef5673246045984) | `` gnome: use internal `mkEnableTarget` function (#397) `` |
| [`659dd55a`](https://github.com/danth/stylix/commit/659dd55a32e79d4e17be0d10dfcbc1862e39ef5a) | `` waybar: put font-family string in quotes (#391) ``      |
> chore(flake/stylix): `00a11ba2` -> `5234b3d4`

- flake.lock
| [`9e060313`](https://github.com/NixOS/nixos-hardware/commit/9e0603134617ec23ce67e1806e905ca07abc92d3) | `` Revert "starfive visionfive2: use mainline kernel" ``     |
| [`1e3c2a85`](https://github.com/NixOS/nixos-hardware/commit/1e3c2a85da63a4eb6dae4fa978064e47bcdbbe74) | `` Revert "starfive visionfive2: enable required drivers" `` |
> chore(flake/nixos-hardware): `806e9d4a` -> `8251761f`

- flake.lock
| [`29c69d9a`](https://github.com/nix-community/home-manager/commit/29c69d9a466e41d46fd3a7a9d0591ef9c113c2ae) | `` kdeconnect: fix service with 24.05 package version `` |
| [`60b85414`](https://github.com/nix-community/home-manager/commit/60b85414b49d5d69816c2453865adb6cc39df33a) | `` Translate using Weblate (Korean) ``                   |
> chore(flake/home-manager): `1b589257` -> `29c69d9a`

- flake.lock
| Commit                                                                                               | Message                                                                                     |
| ---------------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------------- |
| [`752ef440`](https://github.com/numtide/treefmt-nix/commit/752ef44008444e9f3e449459a8d5f96276170a7a) | `` Fix issue where options to ruff could end up before the verb in the generated command `` |
> chore(flake/treefmt): `2fba33a1` -> `52b66cad`

- flake.lock
| Commit                                                                                               | Message                                                                 |
| ---------------------------------------------------------------------------------------------------- | ----------------------------------------------------------------------- |
| [`03b982b7`](https://github.com/numtide/treefmt-nix/commit/03b982b77df58d5974c61c6022085bafe780c1cf) | `` feat(dprint): allow custom options for external formatters (#180) `` |
> chore(flake/treefmt): `52b66cad` -> `03b982b7`

- flake.lock
| Commit                                                                                        | Message                             |
| --------------------------------------------------------------------------------------------- | ----------------------------------- |
| [`ebaed9d4`](https://github.com/danth/stylix/commit/ebaed9d4bf258f4eda7d0690c4092fadcbeefa9d) | `` console: adjust colors (#404) `` |
> chore(flake/stylix): `5234b3d4` -> `ebaed9d4`

- flake.lock
| Commit                                                                                        | Message                                                                          |
| --------------------------------------------------------------------------------------------- | -------------------------------------------------------------------------------- |
| [`99bcaa55`](https://github.com/danth/stylix/commit/99bcaa552096ccff21658a9eb6a1e8397b10eb78) | `` stylix: standardize `autoEnable` and `mkEnableTarget` documentation (#398) `` |
> chore(flake/stylix): `ebaed9d4` -> `99bcaa55`

- flake.lock
| Commit                                                                                        | Message                                                      |
| --------------------------------------------------------------------------------------------- | ------------------------------------------------------------ |
| [`266db7f0`](https://github.com/danth/stylix/commit/266db7f00cad4a465e0ce43d91798fda10716212) | `` stylix: simplify 'mkEnableTarget' documentation (#399) `` |
> chore(flake/stylix): `99bcaa55` -> `266db7f0`

- flake.lock
| [`7b49d396`](https://github.com/NixOS/nixos-hardware/commit/7b49d3967613d9aacac5b340ef158d493906ba79) | `` starfive visionfive2: drop dtb overlay for 8GB version `` |
| [`69fe2563`](https://github.com/NixOS/nixos-hardware/commit/69fe256333b66ba6814290a0e1fda7cdba61807d) | `` starfive visionfive2: let u-boot set device tree name ``  |
> chore(flake/nixos-hardware): `8251761f` -> `7b49d396`

- flake.lock
| [`3befd5d6`](https://github.com/danth/stylix/commit/3befd5d693a2669dc7d2086b57298838ff71f24b) | `` vim: interface colorscheme (#401) `` |
> chore(flake/stylix): `266db7f0` -> `3befd5d6`

- flake.lock
| Commit                                                                                               | Message                                     |
| ---------------------------------------------------------------------------------------------------- | ------------------------------------------- |
| [`3eb96ca1`](https://github.com/numtide/treefmt-nix/commit/3eb96ca1ae9edf792a8e0963cc92fddfa5a87706) | `` hclfmt: only format .hcl files (#182) `` |
> chore(flake/treefmt): `03b982b7` -> `3eb96ca1`

- flake.lock
| [`bc96f07c`](https://github.com/nix-community/nix-index-database/commit/bc96f07c804e4c6983b63716ead93e0416bf9cf0) | `` flake.lock: Update `` |
> chore(flake/nix-index-database): `ff80cb4a` -> `bc96f07c`

- flake.lock
| [`972a52be`](https://github.com/nix-community/nix-index-database/commit/972a52bee3991ae1f1899e6452e0d7c01ee566d9) | `` update packages.nix to release 2024-06-02-030640 `` |
> chore(flake/nix-index-database): `bc96f07c` -> `972a52be`

- flake.lock
| [`07b2c41d`](https://github.com/nix-community/home-manager/commit/07b2c41d2df2878a5c71229a66fb1f8ccef71c47) | `` ci: bump all actions versions (#5496) ``   |
| [`83bfe1ba`](https://github.com/nix-community/home-manager/commit/83bfe1bac8e0d930f36cee6874bd17e77c8754d1) | `` nix-gc: add `persistent` option (#5490) `` |
> chore(flake/home-manager): `9b53a10f` -> `07b2c41d`

- flake.lock
| [`85a0a92c`](https://github.com/danth/stylix/commit/85a0a92c3173ceebbca9b7ec692db79cff8ce91a) | `` zathura: add transparency to highlight colors (#394) `` |
> chore(flake/stylix): `c760f63a` -> `85a0a92c`

- flake.lock
| Commit                                                                                                | Message                    |
| ----------------------------------------------------------------------------------------------------- | -------------------------- |
| [`82b2e20f`](https://github.com/NixOS/nixos-hardware/commit/82b2e20fbffe6a5f0555701af136ad3e734a5faa) | `` Update Inspiron 5509 `` |
> chore(flake/nixos-hardware): `7b49d396` -> `82b2e20f`

- flake.lock
| [`d6c6cf6f`](https://github.com/NixOS/nixos-hardware/commit/d6c6cf6f5fead4057d8fb2d5f30aa8ac1727f177) | `` apple/t2: update to kernel 6.9.2 `` |
> chore(flake/nixos-hardware): `82b2e20f` -> `d6c6cf6f`

- flake.lock
| [`1d3826ce`](https://github.com/danth/stylix/commit/1d3826ceed91ae67562f28ee2e135813a11e47a6) | `` gtk: change accent color (#413) `` |
> chore(flake/stylix): `85a0a92c` -> `1d3826ce`

- flake.lock
| Commit                                                                                                    | Message                                               |
| --------------------------------------------------------------------------------------------------------- | ----------------------------------------------------- |
| [`01a5b2d6`](https://github.com/nix-community/lanzaboote/commit/01a5b2d62d349e95300e1d52e49896a358cfc477) | `` stub: Fix encoding of StubPcrKernelImage ``        |
| [`e7da28d2`](https://github.com/nix-community/lanzaboote/commit/e7da28d23d69570e65d73f356c3e91849ce213f9) | `` stub: Fix encoding of TPM log entries ``           |
| [`788f6df6`](https://github.com/nix-community/lanzaboote/commit/788f6df6870e0fc98be3bf5c81ded6e52d346a8e) | `` tests: Add regression …
> chore(flake/lanzaboote): `2eb19b87` -> `990e300e`

- flake.lock
| Commit                                                                                                    | Message                                                          |
| --------------------------------------------------------------------------------------------------------- | ---------------------------------------------------------------- |
| [`8d5cb360`](https://github.com/nix-community/lanzaboote/commit/8d5cb360249f29983461d5cabec75633434087a1) | `` tests.systemd-pcrlock: simplify and make more reproducible `` |
| [`b98c3d51`](https://github.com/nix-community/lanzaboote/commit/b98c3d514112353355a170a90110672edf8b3527) | `` rust/uefi: add explicit resolver to remove warning ``         |
| [`0397e0ce`](https://github.com/nix-community/lanzaboote/commit/0397e0ce03e736936c9d3ebb88 …
> chore(flake/lanzaboote): `990e300e` -> `2675cac7`

- flake.lock
| [`35b31cd1`](https://github.com/nix-community/lanzaboote/commit/35b31cd1598259171fb2c1d037dca5db030aa55d) | `` chore(deps): lock file maintenance `` |
> chore(flake/lanzaboote): `2675cac7` -> `e8850266`

- flake.lock
| [`057a7996`](https://github.com/NixOS/nixos-hardware/commit/057a7996d012f342a38a26261ee529cebb1755ef) | `` hidpi: drop legacy options `` |
> chore(flake/nixos-hardware): `d6c6cf6f` -> `057a7996`

- flake.lock
| [`4fc1c45a`](https://github.com/numtide/treefmt-nix/commit/4fc1c45a5f50169f9f29f6a98a438fb910b834ed) | `` go: exclude the vendor/ folder (#181) ``   |
| [`ab12b891`](https://github.com/numtide/treefmt-nix/commit/ab12b891c5784ea0296076e6ac819c27975f9db8) | `` add support for --tree-root-file (#183) `` |
> chore(flake/treefmt): `3eb96ca1` -> `4fc1c45a`

- flake.lock
| [`f0ddd45f`](https://github.com/danth/stylix/commit/f0ddd45fbe8d72964e4b92701fe2243da7e48937) | `` treewide: change window manager style guide (#414) `` |
> chore(flake/stylix): `1d3826ce` -> `f0ddd45f`

- flake.lock
| Commit                                                                                        | Message                        |
| --------------------------------------------------------------------------------------------- | ------------------------------ |
| [`ca3247ed`](https://github.com/danth/stylix/commit/ca3247ed8cfbf369f3fe1b7a421579812a95c101) | `` tofi: use opacity (#410) `` |
> chore(flake/stylix): `f0ddd45f` -> `ca3247ed`

- flake.lock
| [`412a5428`](https://github.com/nix-community/nix-index-database/commit/412a5428da031950f767db91bf7864ac442cdcd8) | `` flake.lock: Update `` |
> chore(flake/nix-index-database): `4ac3639c` -> `412a5428`

- flake.lock
| [`55184c76`](https://github.com/nix-community/nix-index-database/commit/55184c7660d580878f7a2bc344629b1b36b5de1c) | `` update packages.nix to release 2024-06-09-030647 `` |
> chore(flake/nix-index-database): `412a5428` -> `55184c76`

- flake.lock
| Commit                                                                                                            | Message                                   |
| ----------------------------------------------------------------------------------------------------------------- | ----------------------------------------- |
| [`afc8f5a6`](https://github.com/nix-community/nix-index-database/commit/afc8f5a6a2c00a89a6d6bdcaf4157797960f10f7) | `` flake: capitalize NixOS ``             |
| [`4949c3ea`](https://github.com/nix-community/nix-index-database/commit/4949c3eac75f949bf3a0f8cb40e63b98009dff67) | `` modules: lint and standardize ``       |
| [`a1578050`](https://github.com/nix-community/nix-index-database/commit/a1578050b6d24e3525135d60c227d322c70abed9) | `` wrappers: rework to use …
> chore(flake/nix-index-database): `55184c76` -> `afc8f5a6`

- flake.lock
| [`a157a81d`](https://github.com/nix-community/nix-index-database/commit/a157a81d0a4bc909b2b6666dd71909bcdc8cd0d6) | `` update generated.nix to release 2024-06-09-074536 `` |
| [`25d61492`](https://github.com/nix-community/nix-index-database/commit/25d61492b32cc4eb46b0854c8a0c79b685d5e9f2) | `` reformat with nixfmt ``                              |
| [`b26661c0`](https://github.com/nix-community/nix-index-database/commit/b26661c0b9d25622ff7003 …
> chore(flake/nix-index-database): `afc8f5a6` -> `a157a81d`

- flake.lock
| [`27979f1c`](https://github.com/nix-community/impermanence/commit/27979f1c3a0d3b9617a3563e2839114ba7d48d3f) | `` README: Grammar fix ``                                 |
| [`f6a5d85f`](https://github.com/nix-community/impermanence/commit/f6a5d85f70f66a40907f7e6ef06b2d78e9de1880) | `` README: Document the NixOS module's `enable` option `` |
> chore(flake/impermanence): `a33ef102` -> `27979f1c`

- flake.lock
| Commit                                                                                                    | Message                                     |
| --------------------------------------------------------------------------------------------------------- | ------------------------------------------- |
| [`b1589082`](https://github.com/nix-community/lanzaboote/commit/b158908292e5376d08cf1af432d7db08c5e8d994) | `` flake.nix: remove superfluous follow ``  |
| [`c93ca771`](https://github.com/nix-community/lanzaboote/commit/c93ca7718839fc5fef024da4983ae304fd7fa1d0) | `` uefi: rename config to remove warning `` |
| [`3028f853`](https://github.com/nix-community/lanzaboote/commit/3028f853d93398866ef7c5143dec951016140a34) | `` flake.nix: remove craneLib warning ``    |
| …
> chore(flake/lanzaboote): `e8850266` -> `547c7bfe`

- flake.lock
| Commit                                                                                                    | Message                         |
| --------------------------------------------------------------------------------------------------------- | ------------------------------- |
| [`1b4d62e1`](https://github.com/nix-community/lanzaboote/commit/1b4d62e1555fcb67b3e8c8f2a7070d946bbeee06) | `` rust: update 1.75 -> 1.78 `` |
> chore(flake/lanzaboote): `547c7bfe` -> `56ed078d`

- flake.lock
| Commit                                                                                                            | Message                                                       |
| ----------------------------------------------------------------------------------------------------------------- | ------------------------------------------------------------- |
| [`aa9e3a7a`](https://github.com/nix-community/nix-index-database/commit/aa9e3a7a29fbae410741831d138df942fa70316a) | `` Pass final into the mkPackages function instead of prev `` |
> chore(flake/nix-index-database): `ab78ec24` -> `88ad3d75`

- flake.lock
| [`7682713f`](https://github.com/danth/stylix/commit/7682713f6af1d32a33f8c4e3d3d141af5ad1761a) | `` stylix: add 'stylix.enable' option (#244) `` |
> chore(flake/stylix): `ca3247ed` -> `7682713f`

- flake.lock
| Commit                                                                                              | Message                                              |
| --------------------------------------------------------------------------------------------------- | ---------------------------------------------------- |
| [`20261c64`](https://github.com/serokell/deploy-rs/commit/20261c6428220b0a849e9745d682711144907b49) | `` add test for allow_hyphen_values of --ssh-opts `` |
| [`ddf42d72`](https://github.com/serokell/deploy-rs/commit/ddf42d723837cb8545aced7980f892947408e234) | `` allow --ssh-opts that starts with hyphen ``       |
| [`e8189232`](https://github.com/serokell/deploy-rs/commit/e8189232236e9ac5977dca025d2c9af651092b23) | `` Link to new official wiki ``                      |
> chore(flake/deploy-rs): `b3ea6f33` -> `9c314763`

- flake.lock
| Commit                                                                                        | Message                                        |
| --------------------------------------------------------------------------------------------- | ---------------------------------------------- |
| [`daac8f59`](https://github.com/danth/stylix/commit/daac8f591f28f89b0301a80bcbea643efa2007ef) | `` stylix: enable Stylix in testbeds (#418) `` |
> chore(flake/stylix): `7682713f` -> `daac8f59`

- flake.lock
| [`f060e405`](https://github.com/danth/stylix/commit/f060e4059b408b2cc1891ce655d0f6bef4e21a5b) | `` stylix: clean up `fromOs` (#407) `` |
> chore(flake/stylix): `daac8f59` -> `f060e405`

- flake.lock
| [`c7b821ba`](https://github.com/NixOS/nixpkgs/commit/c7b821ba2e1e635ba5a76d299af62821cbcb09f3) | `` luaPackages.neotest: enable tests ``                                         |
| [`4b08ae13`](https://github.com/NixOS/nixpkgs/commit/4b08ae13db65671f72072885810250c103c3da2b) | `` linux_testing: 6.10-rc1 -> 6.10-rc2 ``                                       |
| [`fd6ca8d0`](https://github.com/NixOS/nixpkgs/commit/fd6ca8d0f59a0a76bafb1 …
> chore(flake/nixpkgs): `051f9206` -> `c7b821ba`

- flake.lock
| Commit                                                                                              | Message                                         |
| --------------------------------------------------------------------------------------------------- | ----------------------------------------------- |
| [`e7638a78`](https://github.com/serokell/deploy-rs/commit/e7638a7867b01739f24c73dfadc5e0b0a3a13b95) | `` better error messages: provide node names `` |
> chore(flake/deploy-rs): `9c314763` -> `ea0aaeb2`

- flake.lock
| [`e59d2c17`](https://github.com/danth/stylix/commit/e59d2c1725b237c362e4a62f5722f5b268d566c7) | `` swaylock: remove `optionalAttrs` (#420) `` |
> chore(flake/stylix): `f060e405` -> `e59d2c17`

- flake.lock
| [`892f76bd`](https://github.com/nix-community/home-manager/commit/892f76bd0aa09a0f7f73eb41834b8a904b6d0fad) | `` mpv: fix package if wrapMpv not found `` |
> chore(flake/home-manager): `3d65009e` -> `892f76bd`

- flake.lock
| [`1cb529bf`](https://github.com/numtide/treefmt-nix/commit/1cb529bffa880746a1d0ec4e0f5076876af931f1) | `` feat(programs): add d2 (#185) `` |
> chore(flake/treefmt): `4fc1c45a` -> `1cb529bf`

- flake.lock
| Commit                                                                                                    | Message                        |
| --------------------------------------------------------------------------------------------------------- | ------------------------------ |
| [`ce9c2a60`](https://github.com/nix-community/lanzaboote/commit/ce9c2a605c0ab19e3a3e25fbce1b6dfad18e3ac9) | `` treewide: 0.3.0 -> 0.4.1 `` |
> chore(flake/lanzaboote): `56ed078d` -> `b627ccd9`

- flake.lock
| Commit                                                                                              | Message                                |
| --------------------------------------------------------------------------------------------------- | -------------------------------------- |
| [`c92c07eb`](https://github.com/serokell/deploy-rs/commit/c92c07eb2e210a140cc798b27a223cf8ed95628d) | `` add meta.mainProgram to rust drv `` |
> chore(flake/deploy-rs): `ea0aaeb2` -> `254e9d15`

- flake.lock
| [`900ad98d`](https://github.com/NixOS/nixpkgs/commit/900ad98d98ef554734d9c7d8afb3c2822e515e1d) | `` nom: 2.4.0 -> 2.5.0 ``                                                       |
| [`fd95d51c`](https://github.com/NixOS/nixpkgs/commit/fd95d51c69b26b3b3d29f4b89f5d44ca51eb50db) | `` go-ethereum: 1.14.4 -> 1.14.5 ``                                             |
| [`af47703d`](https://github.com/NixOS/nixpkgs/commit/af47703d0de0eacd7c0e9 …
> chore(flake/nixpkgs): `c7b821ba` -> `57d6973a`

- flake.lock
| [`9e848e17`](https://github.com/NixOS/nixos-hardware/commit/9e848e173ca83adf884815c66edc08652ef9ade8) | `` add Dell Latitude 9430 ``                                                   |
| [`f17f79c7`](https://github.com/NixOS/nixos-hardware/commit/f17f79c796381b93e13a6d83580be780da8f9697) | `` rpi4: bluetooth fix ``                                                      |
| …
> chore(flake/nixos-hardware): `58b52b0d` -> `9e848e17`

- flake.lock
| Commit                                                                                                    | Message                  |
| --------------------------------------------------------------------------------------------------------- | ------------------------ |
| [`17051193`](https://github.com/nix-community/lanzaboote/commit/17051193f58400777f00e38084b494a17aa11f51) | `` flake.lock: Update `` |
> chore(flake/lanzaboote): `b627ccd9` -> `f93f71dd`

- flake.lock
| [`b92cf84a`](https://github.com/nix-community/lanzaboote/commit/b92cf84a064921e8b3b398bab977b1d6f4b0bafe) | `` treewide: add sort-key support ``              |
| [`41583aad`](https://github.com/nix-community/lanzaboote/commit/41583aadc52c7d6ba06b26350610ef00f64b8761) | `` tests: set default boot loader timeout to 0 `` |
| [`ff858022`](https://github.com/nix-community/lanzaboote/commit/ff85802227a9693fb58f1a06713d5e3d2e28ea90) | `` tool: reorganize integration tests `` …
> chore(flake/lanzaboote): `f93f71dd` -> `7cb05fab`

- flake.lock
| [`d7500313`](https://github.com/NixOS/nixos-hardware/commit/d75003136c0fc94ee60e51806c2801ff572d06a6) | `` framework: Better firmware update instructions and troubleshooting `` |
> chore(flake/nixos-hardware): `9e848e17` -> `d7500313`

- flake.lock
| Commit                                                                                               | Message                                  |
| ---------------------------------------------------------------------------------------------------- | ---------------------------------------- |
| [`e75ba0a6`](https://github.com/numtide/treefmt-nix/commit/e75ba0a6bb562d2ce275db28f6a36a2e4fd81391) | `` ruff: enable --fix on check (#184) `` |
> chore(flake/treefmt): `1cb529bf` -> `e75ba0a6`

- flake.lock
| [`9ed6009b`](https://github.com/LnL7/nix-darwin/commit/9ed6009b2152128bbcd4e40841160b0bdc0274ba) | `` launchd: add LowPriorityBackgroundIO config `` |
> chore(flake/darwin): `315aa649` -> `139ea5dd`

- flake.lock
| [`73c6955b`](https://github.com/danth/stylix/commit/73c6955b4572346cc10f43a459949fe646efbde0) | `` vscode: fixed search match opacity (#427) `` |
> chore(flake/stylix): `e59d2c17` -> `73c6955b`

- flake.lock
| [`291c3ee6`](https://github.com/NixOS/nixos-hardware/commit/291c3ee610d94e39fa40f1051ebb14b56a57a5d9) | `` treewide: drop hardware.amdgpu.amdvlk option `` |
> chore(flake/nixos-hardware): `ae5c8dcc` -> `239c3864`

- flake.lock
| [`50261c06`](https://github.com/NixOS/nixpkgs/commit/50261c0602f9df33074dae65c871d354517db4f7) | `` config.rust: update references from rustc ``                               |
| [`9c51d83b`](https://github.com/NixOS/nixpkgs/commit/9c51d83ba84f61e9ad7ccb8062d0760006dd7ad5) | `` forgejo: 7.0.3 -> 7.0.4 ``                                                 |
| [`6e11b531`](https://github.com/NixOS/nixpkgs/commit/6e11b53199679aeefd1023870a9b4 …
> chore(flake/nixpkgs): `57d6973a` -> `e9ee548d`

- flake.lock
| [`7941795d`](https://github.com/danth/stylix/commit/7941795d444c590f053ba64a84a9c5339e672a3e) | `` vim: fix missing lib prefix (#433) ``           |
| [`64c5bd0f`](https://github.com/danth/stylix/commit/64c5bd0fbe410475b2cbfc3e8166c161432e69c0) | `` vscode: fix typo in template.mustache (#434) `` |
| [`76d6ca22`](https://github.com/danth/stylix/commit/76d6ca2224adef72f482e46fd61d66d2ef57fb66) | `` treewide: remove use of `with lib` (#425) ``    |
> chore(flake/stylix): `73c6955b` -> `7941795d`

- flake.lock
| [`a7fbda1f`](https://github.com/danth/stylix/commit/a7fbda1fd965cc22e62463896a4af0342cb00e6a) | `` vim: use maintained fork of base16-vim (#428) `` |
> chore(flake/stylix): `7941795d` -> `a7fbda1f`

- flake.lock
| [`0cd56215`](https://github.com/NixOS/nixos-hardware/commit/0cd562157274df3783840bdcb0ce6d9c4cf4aa29) | `` amd/cpu/raphael-igpu: enable scatter/gather for kernel 6.6+ `` |
> chore(flake/nixos-hardware): `239c3864` -> `0cd56215`

- flake.lock
| [`63e899d1`](https://github.com/nix-community/nix-index-database/commit/63e899d13904d9052d6dc6248be096d5e77b08ab) | `` flake.lock: Update `` |
> chore(flake/nix-index-database): `963639a8` -> `63e899d1`

- flake.lock
| [`6af2c5e5`](https://github.com/nix-community/nix-index-database/commit/6af2c5e58c20311276f59d247341cafeebfcb6f4) | `` update generated.nix to release 2024-06-16-025740 `` |
> chore(flake/nix-index-database): `63e899d1` -> `6af2c5e5`

- flake.lock
| Commit                                                                                               | Message                                                                                     |
| ---------------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------------- |
| [`21a992b1`](https://github.com/numtide/treefmt-nix/commit/21a992b1bfc56ab89ec135393501e43b0faee60b) | `` chore: Avoid accidental circular definition of `pkgs`; More descriptive `defaultText` `` |
| [`d81b6a54`](https://github.com/numtide/treefmt-nix/commit/d81b6a54e6ba3b272d29c089da69f8fecf4f04c5) | `` chore: fmt ``                                                                            |
| …
> chore(flake/treefmt): `e75ba0a6` -> `68eb1dc3`

- flake.lock
| [`29044a02`](https://github.com/danth/stylix/commit/29044a02428f12c9d590a8f424ef2024b4f0898c) | `` plymouth: use logo from `nixos-icons` (#424) `` |
| [`25106f20`](https://github.com/danth/stylix/commit/25106f203f1fc711e26e75fc6eaab4a6e18805a7) | `` emacs: change 256 color source (#436) ``        |
> chore(flake/stylix): `a7fbda1f` -> `29044a02`

- flake.lock
| Commit                                                                                        | Message                                                          |
| --------------------------------------------------------------------------------------------- | ---------------------------------------------------------------- |
| [`80e8e1e2`](https://github.com/danth/stylix/commit/80e8e1e2f613bdc8749461899f0959312eb4a54e) | `` treewide: add linters and apply pending suggestions (#426) `` |
> chore(flake/stylix): `29044a02` -> `80e8e1e2`

- flake.lock
| [`cde8f7e1`](https://github.com/NixOS/nixos-hardware/commit/cde8f7e11f036160b0fd6a9e07dc4c8e4061cf06) | `` Lenovo 16ACH6H: use zenpower kernel module `` |
> chore(flake/nixos-hardware): `0cd56215` -> `cde8f7e1`

- flake.lock
| Commit                                                                                                    | Message                                                     |
| --------------------------------------------------------------------------------------------------------- | ----------------------------------------------------------- |
| [`4567a8f6`](https://github.com/nix-community/lanzaboote/commit/4567a8f6dd01d31f202c79485cd1a361aa0d3f68) | `` module: revert sort-key from lanzaboote back to lanza `` |
> chore(flake/lanzaboote): `7cb05fab` -> `662482b2`

- flake.lock
| [`233ea120`](https://github.com/nix-community/lanzaboote/commit/233ea120acc8741ef804e529d4ff28328dceae46) | `` chore(deps): lock file maintenance `` |
> chore(flake/lanzaboote): `662482b2` -> `93dd69a5`

- flake.lock
- flake.nix
- graphical/fonts.nix
| [`7d4f8672`](https://github.com/LnL7/nix-darwin/commit/7d4f8672101536674ca5d75d91161474739a83e2) | `` fonts: remove `fonts.fontDir.enable` ``              |
| [`adf578e3`](https://github.com/LnL7/nix-darwin/commit/adf578e398445f981a36ad919928f23a1dd5ee12) | `` fonts: reimplement and rename to `fonts.packages` `` |
| [`27517d2d`](https://github.com/LnL7/nix-darwin/commit/27517d2d182629cf32020b9c77cffdc462a34c01) | `` fonts: refactor `system.build.fonts` ``              |
| …
> chore(flake/darwin): `ff988d78` -> `58b905ea`

- flake.lock
| Commit                                                                                         | Message                                                                                      |
| ---------------------------------------------------------------------------------------------- | -------------------------------------------------------------------------------------------- |
| [`ee82ceab`](https://github.com/NixOS/nixpkgs/commit/ee82ceaba6b1229e9d99970a40f34338bf8967de) | `` wxc: init at 1.0.0.2 ``                                                                   |
| [`852c13ca`](https://github.com/NixOS/nixpkgs/commit/852c13ca9b6806ce54855f4c1b138662ed47b72d) | `` libbsd: fix version script with lld 17+ ``                                                |
| …
> chore(flake/nixpkgs): `e9ee548d` -> `b60ebf54`

- flake.lock
| Commit                                                                                                    | Message                            |
| --------------------------------------------------------------------------------------------------------- | ---------------------------------- |
| [`71084fec`](https://github.com/nix-community/lanzaboote/commit/71084fec0bfeec7f8ee5f18fa83ed8f9fffdb524) | `` readme: fix matrix room link `` |
> chore(flake/lanzaboote): `93dd69a5` -> `6fa7bc05`

- flake.lock
| Commit                                                                                                | Message                   |
| ----------------------------------------------------------------------------------------------------- | ------------------------- |
| [`acb4f0e9`](https://github.com/NixOS/nixos-hardware/commit/acb4f0e9bfa8ca2d6fca5e692307b5c994e7dbda) | `` link to matrix room `` |
> chore(flake/nixos-hardware): `cde8f7e1` -> `acb4f0e9`

- flake.lock
| [`d7830d05`](https://github.com/nix-community/home-manager/commit/d7830d05421d0ced83a0f007900898bdcaf2a2ca) | `` flake.lock: Update `` |
> chore(flake/home-manager): `0dd1c149` -> `d7830d05`

- flake.lock
| [`9a04830f`](https://github.com/cachix/git-hooks.nix/commit/9a04830f93ea80c9fc0bf4cf883a4fcf30d0944c) | `` fix: pyright has moved out of nodePackages `` |
> chore(flake/git-hooks): `cc4d466c` -> `ed4ce202`

- flake.lock
| [`48580409`](https://github.com/nix-community/disko/commit/48580409a2df1b0364116541228df3bcc84fc3a4) | `` also add indentation to the hooks `` |
| [`248f65b9`](https://github.com/nix-community/disko/commit/248f65b9c40f3f6e62bb1079b598553fcc321758) | `` fix option type in `mkHook` ``       |
> chore(flake/disko): `8262659f` -> `48580409`

- flake.lock
| [`e1174d99`](https://github.com/nix-community/disko/commit/e1174d991944a01eaaa04bc59c6281edca4c0e6e) | `` flake.lock: Update `` |
> chore(flake/disko): `48580409` -> `e1174d99`

- flake.lock
| [`7d16e393`](https://github.com/cachix/git-hooks.nix/commit/7d16e39360278891ba80ce1660f2963972298250) | `` feat: fix reuse not found in flake check `` |
| [`21e0e90f`](https://github.com/cachix/git-hooks.nix/commit/21e0e90ff4d64f6aa47a8439d0b39e746fe2e7c3) | `` feat: add reuse ``                          |
> chore(flake/git-hooks): `ed4ce202` -> `97c0dc86`

- flake.lock
| [`6997a2e3`](https://github.com/cachix/git-hooks.nix/commit/6997a2e345cc90f65e0fb30571f089749a5a4263) | `` chore(deps): update cachix/install-nix-action action to v27 `` |
> chore(flake/git-hooks): `e4ea49a8` -> `8cd35b94`

- flake.lock
| [`0307a32b`](https://github.com/NixOS/nixos-hardware/commit/0307a32b553f81056edd6455168c635aeda6743b) | `` system76/gaze18: add comment about implication of adding driSupport32Bit `` |
| [`4d6b7dfa`](https://github.com/NixOS/nixos-hardware/commit/4d6b7dfa61ccf39b90bb980d702de3130c940c50) | `` system76/gaze18: drop redundant driSupport ``                               |
| …
> chore(flake/nixos-hardware): `acb4f0e9` -> `0307a32b`

- flake.lock
| Commit                                                                                         | Message                                                                                 |
| ---------------------------------------------------------------------------------------------- | --------------------------------------------------------------------------------------- |
| [`1758e909`](https://github.com/NixOS/nixpkgs/commit/1758e909a40884b7acbee784accd62d3c46bbdc3) | `` kdePackages.marknote: remove duplicate dependency ``                                 |
| [`98f4cfff`](https://github.com/NixOS/nixpkgs/commit/98f4cfffa268dc17239c1b23e90fbeeb486170c9) | `` nixos/plasma6: install krdp ``                                                       |
| …
> chore(flake/nixpkgs): `b60ebf54` -> `c00d587b`

- flake.lock
| [`083823b7`](https://github.com/NixOS/nixos-hardware/commit/083823b7904e43a4fc1c7229781417e875359a42) | `` gpu/amd: drop hardware.amdgpu.opencl option `` |
| [`144f53f5`](https://github.com/NixOS/nixos-hardware/commit/144f53f534c553dadbf80388e930d0bb494f7b58) | `` common: remove deprecated modules ``           |
> chore(flake/nixos-hardware): `0307a32b` -> `083823b7`

- flake.lock
| [`cd886711`](https://github.com/nix-community/home-manager/commit/cd886711998fe5d9ff7979fdd4b4cbd17b1f1511) | `` blanket: add module `` |
> chore(flake/home-manager): `c559542f` -> `cd886711`

- flake.lock
| [`d8feb6f8`](https://github.com/nix-community/impermanence/commit/d8feb6f8bf957b1bbcf4fd568881ebb98d9a0be4) | `` nixos: Disable module if no persistent storage paths are defined... `` |
| [`8ea418ec`](https://github.com/nix-community/impermanence/commit/8ea418ec4f149e420788e9f42e007fa3a40610a2) | `` nixos: Remove unused library function imports ``                       |
> chore(flake/impermanence): `27979f1c` -> `363b3e86`

- flake.lock
| [`837e7129`](https://github.com/nix-community/impermanence/commit/837e71297fd30f38ec293dd1b018c15591df99db) | `` nixos: avoid side effects to fileSystems if possible `` |
> chore(flake/impermanence): `363b3e86` -> `23c1f063`

- flake.lock
| [`6a9a1e51`](https://github.com/nix-community/home-manager/commit/6a9a1e51bbb8c301eae5aa63c9fc3c751ec5315b) | `` flake.lock: Update ``                            |
| [`8be82697`](https://github.com/nix-community/home-manager/commit/8be82697f797ce2190b6e2d7b11cd384076caae7) | `` ssh-agent: fix evaluation of maintainer field `` |
> chore(flake/home-manager): `cd886711` -> `6a9a1e51`

- flake.lock
| [`6b1f90a8`](https://github.com/nix-community/home-manager/commit/6b1f90a8ff92e81638ae6eb48cd62349c3e387bb) | `` stalonetray: move config file to XDG_CONFIG_HOME ``                         |
| [`216d51eb`](https://github.com/nix-community/home-manager/commit/216d51eb22f9ce1a4c50a4737a4adcdb42fb6306) | `` yazi: Fix expected structure of flavors ``                                  |
| …
> chore(flake/home-manager): `6a9a1e51` -> `6b1f90a8`

- flake.lock
| [`50d4d13f`](https://github.com/nix-community/disko/commit/50d4d13fbac5db81f8c1e79d95ad87a2970b9201) | `` flake.lock: Update `` |
> chore(flake/disko): `e1174d99` -> `50d4d13f`

- flake.lock
| [`065a23ed`](https://github.com/numtide/treefmt-nix/commit/065a23edceff48f948816b795ea8cc6c0dee7cdf) | `` Corrected invalid hyperlink in readme (#187) `` |
> chore(flake/treefmt): `68eb1dc3` -> `065a23ed`

- flake.lock
| [`31b8b84b`](https://github.com/cachix/git-hooks.nix/commit/31b8b84b0ce9f517993e49afe4688a36b470e198) | `` dev: remove deprecated lib.mdDoc `` |
> chore(flake/git-hooks): `8cd35b94` -> `cfb96902`

- flake.lock
| [`324caa94`](https://github.com/cachix/git-hooks.nix/commit/324caa94a6596ad4ded781e54f8032ab6d46f590) | `` chore(deps): lock file maintenance `` |
> chore(flake/git-hooks): `cfb96902` -> `0ff4381b`

- flake.lock
| [`caabc425`](https://github.com/NixOS/nixos-hardware/commit/caabc425565bbd5c8640630b0bf6974961a49242) | `` feat: Update CODEOWNERS for Tuxedo Pulse Laptops `` |
> chore(flake/nixos-hardware): `c3e48cbd` -> `caabc425`

- flake.lock
| [`823f3a7a`](https://github.com/NixOS/nixpkgs/commit/823f3a7adee68b51091985cb3b8b153bddb2bd22) | `` CODEOWNERS: remove dasj from multiple locations (#322162) ``                    |
| [`c40c66f3`](https://github.com/NixOS/nixpkgs/commit/c40c66f3fbf04a65c302e7e1d13907cbf3078386) | `` vimPlugins.rocks-config-nvim: init at 1.5.0 ``                                  |
| [`dc044660`](https://github.com/NixOS/nixpkgs/commit/dc0446608 …
> chore(flake/nixpkgs): `a71e967e` -> `2893f56d`

- flake.lock
| [`aab67495`](https://github.com/NixOS/nixos-hardware/commit/aab67495e34365045f9dfbe58725cc6fa03607b7) | `` fix: Add an upgrade ``                                 |
| [`1a59c3d5`](https://github.com/NixOS/nixos-hardware/commit/1a59c3d5ac53ed9266eba2bd65b09e6bfcc9ad7d) | `` fix: Improve doc for Tuxedo Pulse Gen3 power issues `` |
> chore(flake/nixos-hardware): `caabc425` -> `aab67495`

- flake.lock
| [`b6a12627`](https://github.com/nix-community/disko/commit/b6a1262796b2990ec3cc60bb2ec23583f35b2f43) | `` lvm_vg: add lvm thinpool/thinlv support `` |
> chore(flake/disko): `dd4d1663` -> `b6a12627`

- flake.lock
| [`901bc809`](https://github.com/NixOS/nixos-hardware/commit/901bc809b5d3e73a609a167385df23311d81b39c) | `` asus/zephyrus/ga402x: drop redundand vdpau drivers ``    |
| [`b7d8d5c7`](https://github.com/NixOS/nixos-hardware/commit/b7d8d5c78812a0a82fdfc817208e530d476d2313) | `` lenovo/yoga/7/14ARH7: remove redundant vdpau packages `` |
| [`a5abf337`](https://github.com/NixOS/nixos-hardware/commit/a5abf3379dc986f6952cc8c6999ddc1bf9d0ee13) | `` zephyrus/ga402x: …
> chore(flake/nixos-hardware): `aab67495` -> `901bc809`

- flake.lock
| [`7a88ff6a`](https://github.com/nix-community/home-manager/commit/7a88ff6ad1e001043f876ebdb1d7460cdfe874d2) | `` systemd: fix sd-switch error on empty target directory `` |
> chore(flake/home-manager): `92a26bf6` -> `7a88ff6a`

- flake.lock
| [`607f969f`](https://github.com/nix-community/home-manager/commit/607f969f5dca2dc100cbc53e24ab49ac24ef8987) | `` systemd: don't try to restart templates `` |
> chore(flake/home-manager): `7a88ff6a` -> `607f969f`

- flake.lock
| [`8767dbf5`](https://github.com/nix-community/disko/commit/8767dbf5d723b1b6834f4d09b217da7c31580d58) | `` flake.lock: Update `` |
> chore(flake/disko): `b6a12627` -> `8767dbf5`

- flake.lock
| [`14aadcba`](https://github.com/NixOS/nixos-hardware/commit/14aadcba1a26c8c142453839f888afd0db8b2041) | `` common/gpu/nvidia: vaapiVdpau -> libva-vdpau-driver `` |
> chore(flake/nixos-hardware): `901bc809` -> `14aadcba`

- flake.lock
| [`3980e781`](https://github.com/NixOS/nixos-hardware/commit/3980e7816c99d9e4da7a7b762e5b294055b73b2f) | `` enable bluetooth support for Yoga 6 13ALC6. (#1013) `` |
> chore(flake/nixos-hardware): `14aadcba` -> `3980e781`

- flake.lock
| Commit                                                                                               | Message                                                            |
| ---------------------------------------------------------------------------------------------------- | ------------------------------------------------------------------ |
| [`96cab883`](https://github.com/nix-community/disko/commit/96cab883dba9ce7aac422973704ec390a9d8f994) | `` zfs: when dataset already exist, only update dataset options `` |
> chore(flake/disko): `8767dbf5` -> `e8ef4773`

- flake.lock
| [`115311bc`](https://github.com/nix-community/disko/commit/115311bc395f24c1b553338fec4b3aa28cbf5ae2) | `` zfs: try to import zpool in incremental mode `` |
> chore(flake/disko): `e8ef4773` -> `115311bc`

- flake.lock
| [`f50e2779`](https://github.com/nix-community/home-manager/commit/f50e2779edbc905ab131ce7ce36b14a09ab44f3c) | `` flake.lock: Update ``           |
| [`19e2f43e`](https://github.com/nix-community/home-manager/commit/19e2f43e0b0aec2067e5101f7d1ec75a43f64778) | `` rbw: fix url option examples `` |
> chore(flake/home-manager): `1a4f12ae` -> `f50e2779`

- flake.lock
| [`7e68e55d`](https://github.com/nix-community/home-manager/commit/7e68e55d2e16d3a1e92a679430728c35a30fd24e) | `` glance: add module `` |
> chore(flake/home-manager): `f50e2779` -> `7e68e55d`

- flake.lock
| [`423b86a7`](https://github.com/nix-community/disko/commit/423b86a7f756421325e71663ada79a199bf13408) | `` disko-install: don't copy channel `` |
> chore(flake/disko): `115311bc` -> `423b86a7`

- flake.lock
| [`23127426`](https://github.com/NixOS/nixos-hardware/commit/231274268ff2250d4730e274b808f66ef91b6381) | `` gpu/amd: Remove `loadInInitrd` option `` |
> chore(flake/nixos-hardware): `3980e781` -> `23127426`

- flake.lock
| [`90995582`](https://github.com/NixOS/nixpkgs/commit/909955825b3a2d0ccf080b8030b9459f41e0fc29) | `` emacsPackages.rime: fix build error in darwin (#322873) ``                |
| [`3d530bea`](https://github.com/NixOS/nixpkgs/commit/3d530bea8d981894aa996162efe7de9d75a32cc9) | `` btrfs-progs: 6.9.1 -> 6.9.2 ``                                            |
| [`f6c43dab`](https://github.com/NixOS/nixpkgs/commit/f6c43dab739c8bcce80577c80cefeaea0 …
> chore(flake/nixpkgs): `2893f56d` -> `b2852eb9`

- flake.lock
| [`c2f806e6`](https://github.com/nix-community/home-manager/commit/c2f806e60ac55c604708250ba0ebcf96bccbbafe) | `` pulseeffects: fix test evaluation `` |
> chore(flake/home-manager): `7e68e55d` -> `c2f806e6`

- flake.lock
| [`36317d4d`](https://github.com/nix-community/home-manager/commit/36317d4d38887f7629876b0e43c8d9593c5cc48d) | `` direnv: add silent option `` |
> chore(flake/home-manager): `c2f806e6` -> `36317d4d`

- flake.lock
| [`a59f00f5`](https://github.com/NixOS/nixos-hardware/commit/a59f00f5ac65b19382617ba00f360f8bc07ed3ac) | `` raspberry-pi/3: remove ttyAMA0 from console list `` |
| [`43ea86cc`](https://github.com/NixOS/nixos-hardware/commit/43ea86cc8c77dcb5f622766050f1c3315088c419) | `` remove probably not necessary library ``            |
| [`8d5e6d92`](https://github.com/NixOS/nixos-hardware/commit/8d5e6d9278a2214cf1ec7cb04a4016b1184edc73) | `` Raspberry Pi 3: try to fix tests `` …
> chore(flake/nixos-hardware): `23127426` -> `a59f00f5`

- flake.lock
| [`33ff922c`](https://github.com/nix-community/nix-index-database/commit/33ff922c8f1d070a530cf6a7215d8673baeeb9ed) | `` flake.lock: Update `` |
> chore(flake/nix-index-database): `4293f532` -> `33ff922c`

- flake.lock
| [`2b0d5f3a`](https://github.com/nix-community/nix-index-database/commit/2b0d5f3a4229c581e2bb839ac0b992feb366eba5) | `` update generated.nix to release 2024-06-30-025731 `` |
> chore(flake/nix-index-database): `33ff922c` -> `2b0d5f3a`

- flake.lock
| Commit                                                                                                            | Message                                 |
| ----------------------------------------------------------------------------------------------------------------- | --------------------------------------- |
| [`838a910d`](https://github.com/nix-community/nix-index-database/commit/838a910df0f7e542de2327036b2867fd68ded3a2) | `` Add comma option to darwin module `` |
> chore(flake/nix-index-database): `2b0d5f3a` -> `838a910d`

- flake.lock
| [`d185770e`](https://github.com/nix-community/disko/commit/d185770ea261fb5cf81aa5ad1791b93a7834d12c) | `` examples: drop priority as we now have a reasonable default `` |
| [`05f4e223`](https://github.com/nix-community/disko/commit/05f4e223b59c03c04bc757d51ce17662bb69f115) | `` gpt: move boot partitions to the front of disko ``             |
> chore(flake/disko): `423b86a7` -> `d185770e`

- flake.lock
| Commit                                                                                               | Message                                   |
| ---------------------------------------------------------------------------------------------------- | ----------------------------------------- |
| [`05635b03`](https://github.com/numtide/treefmt-nix/commit/05635b039ab9c20d7047464d4ccd2281ad3f2a04) | `` doc: fix treefmt configuration link `` |
> chore(flake/treefmt): `065a23ed` -> `8df5ff62`

- flake.lock
| [`501a51f7`](https://github.com/nix-community/lanzaboote/commit/501a51f7ce737c23befd31964f600ad628c10df5) | `` fix(deps): update all dependencies `` |
> chore(flake/lanzaboote): `6fa7bc05` -> `0e6457c9`

- flake.lock
| Commit                                                                                         | Message                                                                               |
| ---------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------- |
| [`3e9099f2`](https://github.com/NixOS/nixpkgs/commit/3e9099f2ec2a47c1cd4cdc6e9898566ff6470f8d) | `` zeal: 0.7.0 -> 0.7.1 ``                                                            |
| [`6a4da10b`](https://github.com/NixOS/nixpkgs/commit/6a4da10b0b7d6924fd7a5bc973c7af628a8a5a7d) | `` signal-desktop-beta: 7.14.0-beta.1 -> 7.15.0-beta.1 ``                             |
| …
> chore(flake/nixpkgs): `b2852eb9` -> `2741b4b4`

- flake.lock
| Commit                                                                                                            | Message                                                           |
| ----------------------------------------------------------------------------------------------------------------- | ----------------------------------------------------------------- |
| [`5f154bf6`](https://github.com/nix-community/nix-index-database/commit/5f154bf6c2b17d5751e45fbcf1bc520a92066089) | `` nixos-module: disable programs.command-not-found by default `` |
> chore(flake/nix-index-database): `838a910d` -> `2917972e`

- flake.lock
| Commit                                                                                               | Message                                                        |
| ---------------------------------------------------------------------------------------------------- | -------------------------------------------------------------- |
| [`e37341c3`](https://github.com/numtide/treefmt-nix/commit/e37341c358cd47be849d30dae50d16eb52c4b572) | `` flake: add comment why we need allowUnfree ``               |
| [`6762408e`](https://github.com/numtide/treefmt-nix/commit/6762408e830ac5c87c2f7c904344d4f85b7d54f4) | `` terraform: default on opensource opentofu for formatting `` |
> chore(flake/treefmt): `8df5ff62` -> `a103c909`

- flake.lock
| Commit                                                                                               | Message                                                                    |
| ---------------------------------------------------------------------------------------------------- | -------------------------------------------------------------------------- |
| [`895b2713`](https://github.com/nix-community/disko/commit/895b2713e10da5930644bed860d0b985302d3248) | `` build(deps): bump DeterminateSystems/update-flake-lock from 22 to 23 `` |
> chore(flake/disko): `d185770e` -> `544a80a6`

- flake.lock
| Commit                                                                                               | Message                                             |
| ---------------------------------------------------------------------------------------------------- | --------------------------------------------------- |
| [`8aa5b403`](https://github.com/numtide/treefmt-nix/commit/8aa5b4034b89b65fd3169505536ae0f82bec1784) | `` gdformat: use gdtoolkit_4 package ``             |
| [`6d63a367`](https://github.com/numtide/treefmt-nix/commit/6d63a367d0c6738bf714811bfb6b80a6ea8727db) | `` chore: remove lib.mdDoc, which is now default `` |
| [`9dfd0b09`](https://github.com/numtide/treefmt-nix/commit/9dfd0b09a6a710a5e3c3d6fa649ef0bedbe5f5a9) | `` nixfmt: use rfc-style by default ``              |
| …
> chore(flake/treefmt): `a103c909` -> `bdb63550`

- flake.lock
| [`6e253f12`](https://github.com/NixOS/nixos-hardware/commit/6e253f12b1009053eff5344be5e835f604bb64cd) | `` pine64/pinebook-pro: remove obsolete issue docs `` |
> chore(flake/nixos-hardware): `a59f00f5` -> `6e253f12`

- flake.lock
| [`a28173cf`](https://github.com/NixOS/nixpkgs/commit/a28173cf76309e2da256a8f505e6b6a5eba5d845) | `` agdaPackages.generics: init at 1.0.1 ``                                   |
| [`b294dd81`](https://github.com/NixOS/nixpkgs/commit/b294dd81ccb8a17352b31d98ec22942c1b4db94f) | `` shotwell: 0.32.6 -> 0.32.7 ``                                             |
| [`d1e0f30c`](https://github.com/NixOS/nixpkgs/commit/d1e0f30cb2b0f4fd69b81ea189ea9fa03 …
> chore(flake/nixpkgs): `2741b4b4` -> `00d80d13`

- flake.lock
| [`58268b4d`](https://github.com/nix-community/home-manager/commit/58268b4d7745f6747be18033e6f10011466ce8d4) | `` flake.lock: Update ``                       |
| [`e9158314`](https://github.com/nix-community/home-manager/commit/e9158314725af06854009b829d2249d0d6c23c79) | `` yazi: allow literal string for `initLua` `` |
| [`269cc18d`](https://github.com/nix-community/home-manager/commit/269cc18d945dd44bcbc22d58df3876a5d0dbac0b) | `` sway: fix systemd variables example `` …
> chore(flake/home-manager): `36e2f9da` -> `58268b4d`

- flake.lock
| [`0a30138c`](https://github.com/nix-community/home-manager/commit/0a30138c694ab3b048ac300794c2eb599dc40266) | `` mpd: specify dependency of service on socket `` |
> chore(flake/home-manager): `58268b4d` -> `0a30138c`

- flake.lock
| [`64679cd7`](https://github.com/nix-community/disko/commit/64679cd7f318c9b6595902b47d4585b1d51d5f9e) | `` flake.lock: Update `` |
> chore(flake/disko): `544a80a6` -> `64679cd7`

- flake.lock
| [`e3582e51`](https://github.com/nix-community/home-manager/commit/e3582e5151498bc4d757e8361431ace8529e7bb7) | `` sway: unfail units before starting session target `` |
| [`b7b55e28`](https://github.com/nix-community/home-manager/commit/b7b55e285cfc92e84f243012516bbc414691b747) | `` sway: stop sway-session.target on exit ``            |
> chore(flake/home-manager): `bbe6e947` -> `e3582e51`

- flake.lock
| [`6d61f720`](https://github.com/nix-community/nix-index-database/commit/6d61f72020aa748ed1cec87b21e6739be71b13c5) | `` flake.lock: Update `` |
> chore(flake/nix-index-database): `2917972e` -> `6d61f720`

- flake.lock
| [`ca551ae1`](https://github.com/nix-community/nix-index-database/commit/ca551ae1d2144db88b23b405758958dd4d6b2733) | `` update generated.nix to release 2024-07-07-025737 `` |
> chore(flake/nix-index-database): `6d61f720` -> `ca551ae1`

- flake.lock
| Commit                                                                                                            | Message                                       |
| ----------------------------------------------------------------------------------------------------------------- | --------------------------------------------- |
| [`685e40e1`](https://github.com/nix-community/nix-index-database/commit/685e40e1348007d2cf76747a201bab43d86b38cb) | `` README: add warning to remove nix-index `` |
> chore(flake/nix-index-database): `ca551ae1` -> `685e40e1`

- flake.lock
| Commit                                                                                               | Message                                                      |
| ---------------------------------------------------------------------------------------------------- | ------------------------------------------------------------ |
| [`e1d7bd5e`](https://github.com/numtide/treefmt-nix/commit/e1d7bd5ec6fc389eb3a90e232c4150338bf6a508) | `` exclude some file types by default (#194) ``              |
| [`1675903b`](https://github.com/numtide/treefmt-nix/commit/1675903bb0dbb0f92723d96e2d42c62103e47a5e) | `` {shellcheck,shfmt}: also format .bash and .envrc files `` |
> chore(flake/treefmt): `bdb63550` -> `6fc8bded`

- flake.lock
| [`f1a00e7f`](https://github.com/nix-community/disko/commit/f1a00e7f55dc266ef286cc6fc8458fa2b5ca2414) | `` flake.lock: Update `` |
> chore(flake/disko): `64679cd7` -> `f1a00e7f`

- flake.lock
| Commit                                                                                                | Message                                                               |
| ----------------------------------------------------------------------------------------------------- | --------------------------------------------------------------------- |
| [`72d3c007`](https://github.com/NixOS/nixos-hardware/commit/72d3c007024ce47d838bb38693c8773812f54bf2) | `` Added new model to flake.nix and README ``                         |
| [`00f9c4bb`](https://github.com/NixOS/nixos-hardware/commit/00f9c4bb0628983bc017d7644f67d49ae66bdbfa) | `` Fix Lenovo Thinkpad T14s not powering off ``                       |
| [`da0aa7b5`](https://github.com/NixOS/nixos-hardware/commit/da0aa7b533d49e6319c603e07b …
> chore(flake/nixos-hardware): `6e253f12` -> `72d3c007`

- flake.lock
| [`8b63fe8c`](https://github.com/numtide/treefmt-nix/commit/8b63fe8cf7892c59b3df27cbcab4d5644035d72f) | `` add actionlint (#146) `` |
> chore(flake/treefmt): `6fc8bded` -> `8b63fe8c`

- flake.lock
| [`11e7fbf7`](https://github.com/cachix/git-hooks.nix/commit/11e7fbf782eec015600836938006bd635791bf2c) | `` feat: add cabal-gild ``         |
| [`0f6f5fd8`](https://github.com/cachix/git-hooks.nix/commit/0f6f5fd8deb35b9213397af6d0512e8f7fe5752d) | `` chore: update to nixos 24.05 `` |
| [`6283849b`](https://github.com/cachix/git-hooks.nix/commit/6283849b803cf115bc0bea4a69e456ced9def947) | `` fixed typstyle argument ``      |
> chore(flake/git-hooks): `2b6bd3c8` -> `8d6a17d0`

- flake.lock
| Commit                                                                                         | Message                                                     |
| ---------------------------------------------------------------------------------------------- | ----------------------------------------------------------- |
| [`760751b6`](https://github.com/ryantm/agenix/commit/760751b6d1d07bebad4b836c4014f6f20bc6db68) | `` README: Add warning about HNDL and PQS in theat model `` |
> chore(flake/agenix): `3a567357` -> `de96bd90`

- flake.lock
| [`f749fabe`](https://github.com/nix-community/home-manager/commit/f749fabeccb1587e4c1562e4f818cf33b8f77a51) | `` atuin: use 'lib.getExe' `` |
> chore(flake/home-manager): `2fb5c1e0` -> `f749fabe`

- flake.lock
| Commit                                                                                               | Message                        |
| ---------------------------------------------------------------------------------------------------- | ------------------------------ |
| [`203f5aa1`](https://github.com/numtide/treefmt-nix/commit/203f5aa13af95a6f0b98e9659802ea05eff46755) | `` mypy: add package option `` |
> chore(flake/treefmt): `8b63fe8c` -> `750dfb55`

- flake.lock
| [`c085b984`](https://github.com/nix-community/home-manager/commit/c085b984ff2808bf322f375b10fea5a415a9c43d) | `` gnome-keyring: update package ``                    |
| [`57d85c6c`](https://github.com/nix-community/home-manager/commit/57d85c6c6d625c45bbf848ed77fbdb5794aa8414) | `` xdg-desktop-entries: allow `terminal` to be null `` |
| [`f79d950a`](https://github.com/nix-community/home-manager/commit/f79d950ac23a4c63e60bb71475d3321fbd9ace2d) | `` atuin: …
> chore(flake/home-manager): `f749fabe` -> `c085b984`

- flake.lock
| [`786965e1`](https://github.com/nix-community/disko/commit/786965e1b1ed3fd2018d78399984f461e2a44689) | `` flake.lock: Update `` |
> chore(flake/disko): `f1a00e7f` -> `786965e1`

- flake.lock
| Commit                                                                                               | Message                                         |
| ---------------------------------------------------------------------------------------------------- | ----------------------------------------------- |
| [`5b002f8a`](https://github.com/numtide/treefmt-nix/commit/5b002f8a53ed04c1a4177e7b00809d57bd2c696f) | `` actionlint: also lint action files (#197) `` |
> chore(flake/treefmt): `750dfb55` -> `5b002f8a`

- flake.lock
| [`b8d2660e`](https://github.com/nix-community/nix-index-database/commit/b8d2660effd14ecb431adc0f2e5c7e7b55e91781) | `` flake.lock: Update `` |
> chore(flake/nix-index-database): `685e40e1` -> `b8d2660e`

- flake.lock
| [`5fe5b0cd`](https://github.com/nix-community/nix-index-database/commit/5fe5b0cdf1268112dc96319388819b46dc051ef4) | `` update generated.nix to release 2024-07-14-025924 `` |
> chore(flake/nix-index-database): `b8d2660e` -> `5fe5b0cd`

- flake.lock
| Commit                                                                                               | Message                                |
| ---------------------------------------------------------------------------------------------------- | -------------------------------------- |
| [`ea771188`](https://github.com/numtide/treefmt-nix/commit/ea771188cdd4b2b3461e032301e2bc4c58980117) | `` format md/yaml ``                   |
| [`c737821f`](https://github.com/numtide/treefmt-nix/commit/c737821f24582d11de2dd121ac91bead4d254d05) | `` enable formatter for all files ``   |
| [`ec5432d4`](https://github.com/numtide/treefmt-nix/commit/ec5432d416a20c6489ef20e2968a5623340c1d47) | `` clang-format: add *.hh extension `` |
> chore(flake/treefmt): `5b002f8a` -> `b92afa15`

- flake.lock
| [`bad37694`](https://github.com/nix-community/disko/commit/bad376945de7033c7adc424c02054ea3736cf7c4) | `` flake.lock: Update `` |
> chore(flake/disko): `786965e1` -> `bad37694`

- flake.lock
| [`587776af`](https://github.com/cachix/git-hooks.nix/commit/587776afda8e6a57a8a8db9c2fe9cf11e3ecfc16) | `` Allow importing modules into the inner module system. `` |
> chore(flake/git-hooks): `8d6a17d0` -> `622291c0`

- flake.lock
| Commit                                                                                               | Message                                           |
| ---------------------------------------------------------------------------------------------------- | ------------------------------------------------- |
| [`0fb28f23`](https://github.com/numtide/treefmt-nix/commit/0fb28f237f83295b4dd05e342f333b447c097398) | `` module-option: ignore npm lock files (#200) `` |
> chore(flake/treefmt): `b92afa15` -> `0fb28f23`

- flake.lock
| Commit                                                                                                | Message                                                                    |
| ----------------------------------------------------------------------------------------------------- | -------------------------------------------------------------------------- |
| [`c5013aa7`](https://github.com/NixOS/nixos-hardware/commit/c5013aa7ce2c7ec90acee5d965d950c8348db751) | `` common/gpu/nvidia: use lib.mkDefault for hardware.nvidia.modesetting `` |
| [`6b745e23`](https://github.com/NixOS/nixos-hardware/commit/6b745e2331ba42e2f744434dcef1fe31ef9a4ced) | `` common-gpu-nvidia: enable modesetting by default ``                     |
| [`c5925d86`](https://github.com/NixOS/nixos-hardware/commit/c5925d …
> chore(flake/nixos-hardware): `72d3c007` -> `c5013aa7`

- flake.lock
- hosts/jung/roon.nix
- nix/overlays/fix-lollypop.nix
- nix/overlays/truecolor-check.nix
- users/bemeurer/nixos.nix
| Commit                                                                                         | Message                                                                                          |
| ---------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------------------ |
| [`bdf5d0a3`](https://github.com/NixOS/nixpkgs/commit/bdf5d0a3be9b2aaecbc586ba34a46012cc35f2bd) | `` numad: 0.5 -> 0.5-unstable-2023-09-06 (#315168) ``                                            |
| [`a828d5e0`](https://github.com/NixOS/nixpkgs/commit/a828d5e0780120d37d5be6255b0e0dde8321b966) | `` sequoia-sqop: 0.34.0 -> 0.35.0 ``                                                             |
| …
> chore(flake/nixpkgs): `9f4128e0` -> `693bc46d`

- flake.lock
| [`e8e8d9a3`](https://github.com/nix-community/disko/commit/e8e8d9a3a9c1d0e654ccda7834bf0288a9d15c47) | `` flake.lock: Update `` |
> chore(flake/disko): `bad37694` -> `e8e8d9a3`

- flake.lock
| [`9a816e3d`](https://github.com/NixOS/nixos-hardware/commit/9a816e3d1c0649a7c88370c8eb80071f5891a4d8) | `` asus-rog-strix-g713ie: init ``                   |
| [`9a187879`](https://github.com/NixOS/nixos-hardware/commit/9a187879f47ba2cad0f737913d99ebc893125ee6) | `` lenovo-thinkpad-z13-gen2: move to asound.conf `` |
> chore(flake/nixos-hardware): `c5013aa7` -> `ede1f14c`

- flake.lock
| [`108f27f7`](https://github.com/NixOS/nixos-hardware/commit/108f27f71e67f43c74d2c2737749556fd6380341) | `` Remove BTRFS related setting `` |
> chore(flake/nixos-hardware): `ede1f14c` -> `bb90787e`

- flake.lock
| Commit                                                                                               | Message                                                |
| ---------------------------------------------------------------------------------------------------- | ------------------------------------------------------ |
| [`50104496`](https://github.com/numtide/treefmt-nix/commit/50104496fb55c9140501ea80d183f3223d13ff65) | `` actionlint: revert including action files (#203) `` |
> chore(flake/treefmt): `0fb28f23` -> `50104496`

- flake.lock
| [`d8bfbbf6`](https://github.com/NixOS/nixos-hardware/commit/d8bfbbf614881a110059f14bc2a5d28c5df115e5) | `` fix: Add more aliases to 24.05-compat ``             |
| [`3501b9c0`](https://github.com/NixOS/nixos-hardware/commit/3501b9c0962d0644041cd4e9243f817c1d7418ba) | `` flake.nix: export paths instead of imported files `` |
> chore(flake/nixos-hardware): `bb90787e` -> `d8bfbbf6`

- flake.lock
| Commit                                                                                                | Message                         |
| ----------------------------------------------------------------------------------------------------- | ------------------------------- |
| [`71b92eab`](https://github.com/NixOS/nixos-hardware/commit/71b92eab15920df202dd6256c2e2a58cc6e48641) | `` asus-rog-strix-x570: init `` |
> chore(flake/nixos-hardware): `d8bfbbf6` -> `71b92eab`

- flake.lock
| [`ece5b120`](https://github.com/NixOS/nixos-hardware/commit/ece5b120143233d5d19a5e6034ae8bc879c21e7a) | `` update README for omen 16-n0280nd `` |
| [`89a33c8e`](https://github.com/NixOS/nixos-hardware/commit/89a33c8e93a64d4f65ca3a2c7bc9da24216aa0b9) | `` omen 16-n0280nd: init ``             |
> chore(flake/nixos-hardware): `71b92eab` -> `ece5b120`

- flake.lock
| [`ab165a8a`](https://github.com/NixOS/nixos-hardware/commit/ab165a8a6cd12781d76fe9cbccb9e975d0fb634f) | `` codeowners: Add Lyndeno for XPS-9560 ``             |
| [`05672b50`](https://github.com/NixOS/nixos-hardware/commit/05672b50f70e47df282e974e07534d38df4f8fd1) | `` dell/xps/15-9560: fix graphics options ``           |
| [`6a4ecebc`](https://github.com/NixOS/nixos-hardware/commit/6a4ecebce56727d0ae538b1277725cb03181124e) | `` dell/xps/15-9560: use graphics option …
> chore(flake/nixos-hardware): `ece5b120` -> `ab165a8a`

- flake.lock
| [`bec6e3cd`](https://github.com/nix-community/disko/commit/bec6e3cde912b8acb915fecdc509eda7c973fb42) | `` examples: rename vdb -> main `` |
> chore(flake/disko): `e8e8d9a3` -> `bec6e3cd`

- flake.lock
| [`888bfb10`](https://github.com/numtide/treefmt-nix/commit/888bfb10a9b091d9ed2f5f8064de8d488f7b7c97) | `` flake-modules.nix: allow empty specification (#204) `` |
> chore(flake/treefmt): `50104496` -> `888bfb10`

- flake.lock
| Commit                                                                                                    | Message                                                                      |
| --------------------------------------------------------------------------------------------------------- | ---------------------------------------------------------------------------- |
| [`9d205aa0`](https://github.com/nix-community/lanzaboote/commit/9d205aa0f9c4f93852aae2ec62e20a9893f9452b) | `` chore(deps): lock file maintenance ``                                     |
| [`2cee36f1`](https://github.com/nix-community/lanzaboote/commit/2cee36f14d9016b3d9147ffd0bc76dfb965b10e1) | `` stub: simplify `compute_pad4` ``                                          |
| …
> chore(flake/lanzaboote): `0e6457c9` -> `60e4578f`

- flake.lock
| [`bd8d2d4a`](https://github.com/nix-community/nix-index-database/commit/bd8d2d4adca7fc53dd1e8ae150bb6a26953eebb0) | `` flake.lock: Update `` |
> chore(flake/nix-index-database): `5fe5b0cd` -> `bd8d2d4a`

- flake.lock
| [`b6db9fd8`](https://github.com/nix-community/nix-index-database/commit/b6db9fd8dc59bb2ccb403f76d16ba8bbc1d5263d) | `` update generated.nix to release 2024-07-21-025749 `` |
> chore(flake/nix-index-database): `bd8d2d4a` -> `b6db9fd8`

- flake.lock
| Commit                                                                                                    | Message                                 |
| --------------------------------------------------------------------------------------------------------- | --------------------------------------- |
| [`0dba013c`](https://github.com/nix-community/lanzaboote/commit/0dba013cf35c296800b9e362cfe834c2aef81bd0) | `` Drop no longer existing overwrite `` |
> chore(flake/lanzaboote): `60e4578f` -> `f3b4ade1`

- flake.lock
| [`2f5df5dc`](https://github.com/nix-community/disko/commit/2f5df5dcceb8473dd5715c4ae92f9b0d5f87fff9) | `` flake.lock: Update `` |
> chore(flake/disko): `bec6e3cd` -> `2f5df5dc`

- flake.lock
| [`4698b1ef`](https://github.com/nix-community/disko/commit/4698b1ef375e9c904037e0b2049aa73d39ac1b2d) | `` disko: add nixos-install-tools to PATH `` |
> chore(flake/disko): `2f5df5dc` -> `4698b1ef`

- flake.lock
| [`405b6548`](https://github.com/NixOS/nixos-hardware/commit/405b654893aba16c8014de6a17e84439d3fb8e46) | `` Add Lenovo Thinkpad T14 Gen5 `` |
> chore(flake/nixos-hardware): `ab165a8a` -> `405b6548`

- flake.lock
| [`8db8970b`](https://github.com/numtide/treefmt-nix/commit/8db8970be1fb8be9c845af7ebec53b699fe7e009) | `` feat(module): add meta.maintainers attribute (#205) `` |
| [`b3ee1836`](https://github.com/numtide/treefmt-nix/commit/b3ee183659bdd73bb2297cd130385a9554482ea2) | `` swift-format: remove broken formatter from checks ``   |
| [`499d9b8a`](https://github.com/numtide/treefmt-nix/commit/499d9b8a947bbf62b5d52f0d265d1059ac179b66) | `` feat: update nixpkgs input `` …
> chore(flake/treefmt): `888bfb10` -> `8db8970b`

- flake.lock
| [`465ea1f9`](https://github.com/nix-community/home-manager/commit/465ea1f994a4e2b498b847c35caa205af7b261df) | `` swayosd: avoid restarting too quickly `` |
> chore(flake/home-manager): `7560dc94` -> `465ea1f9`

- flake.lock
| [`af70fc50`](https://github.com/nix-community/home-manager/commit/af70fc502a15d7e1e4c5a4c4fc8e06c2ec561e0c) | `` flake.lock: Update `` |
> chore(flake/home-manager): `465ea1f9` -> `af70fc50`

- flake.lock
| [`a7432eba`](https://github.com/NixOS/nixos-hardware/commit/a7432ebaefc9a400dcda399d48b949230378d784) | `` framework/16-inch: Mark keyboard as internal for libinput `` |
| [`b501c5fb`](https://github.com/NixOS/nixos-hardware/commit/b501c5fbf657b4bbe2a61a66fc1483ad0ec40d7b) | `` Add configuration for Lenovo IdeaPad Gaming 3 15ach6 ``      |
> chore(flake/nixos-hardware): `405b6548` -> `a7432eba`

- flake.lock
| [`55e874b9`](https://github.com/nix-community/disko/commit/55e874b9c14764cb791e5740f0e92202e41393fc) | `` flake.lock: Update `` |
> chore(flake/disko): `4698b1ef` -> `55e874b9`

- flake.lock
| Commit                                                                                                | Message                                                                          |
| ----------------------------------------------------------------------------------------------------- | -------------------------------------------------------------------------------- |
| [`5bd0371d`](https://github.com/NixOS/nixos-hardware/commit/5bd0371d3ff4c121b03450de8cfd643547b11fe1) | `` Create lenovo-yoga-7-14ARH7-amdgpu and lenovo-yoga-7-14ARH7-nvidia entries `` |
| [`226e5178`](https://github.com/NixOS/nixos-hardware/commit/226e517854aec947b139e28e9edb6394fe256d32) | `` surface: fix default kernel version ``                                        |
| …
> chore(flake/nixos-hardware): `a7432eba` -> `5bd0371d`

- flake.lock
| Commit                                                                                                | Message                                                                          |
| ----------------------------------------------------------------------------------------------------- | -------------------------------------------------------------------------------- |
| [`d3c993c8`](https://github.com/NixOS/nixos-hardware/commit/d3c993c851ad40bbab7e08d566138ff72cd8744f) | `` Lenovo ThinkPad X1 (12th Gen): init ``                                        |
| [`60d3bae3`](https://github.com/NixOS/nixos-hardware/commit/60d3bae3845050d36328fbfc9a0e95b82a25f2f1) | `` Add deprecation explanation ``                                                |
| …
> chore(flake/nixos-hardware): `5bd0371d` -> `d3c993c8`

- flake.lock
| [`5b01cea8`](https://github.com/nix-community/disko/commit/5b01cea8b5753de9c2febd27203c530be14745ff) | `` flake.lock: Update `` |
> chore(flake/disko): `55e874b9` -> `5b01cea8`

- flake.lock
| [`0b4d40f9`](https://github.com/NixOS/nixos-hardware/commit/0b4d40f95a68ef0a6785f6b938ac8c1383321dbf) | `` surface: linux 6.9.3 -> 6.9.9 ``                       |
| [`10917438`](https://github.com/NixOS/nixos-hardware/commit/109174381137e88eae61a3537e07e9ef58ba6a98) | `` surface: linux-surface arch-6.9.3-1 to arch-6.9.9-1 `` |
> chore(flake/nixos-hardware): `d3c993c8` -> `0b4d40f9`

- flake.lock
| [`e88eb66c`](https://github.com/LnL7/nix-darwin/commit/e88eb66c2b5e7066786f5d6343f3737567a71734) | `` `mapAttrsFlatten` -> `mapAttrsToList` `` |
> chore(flake/darwin): `72bbc11a` -> `980c7066`

- flake.lock
| [`8c86cd5f`](https://github.com/nix-community/lanzaboote/commit/8c86cd5f1ab60aa1c7f1d905d5ec965bf7f6c76c) | `` chore(deps): lock file maintenance `` |
> chore(flake/lanzaboote): `f3b4ade1` -> `2250c381`

- flake.lock
| [`a5662388`](https://github.com/LnL7/nix-darwin/commit/a566238826fc77b2322b62cd52c321db8c30a1f4) | `` defaults: only restart Dock when user is logged in `` |
> chore(flake/darwin): `980c7066` -> `0413754b`

- flake.lock
| [`b7b55739`](https://github.com/NixOS/nixos-hardware/commit/b7b55739f75fd5eaca6b1867d11919896d9b404b) | `` fix link text for Omen 14-fb0798ng `` |
> chore(flake/nixos-hardware): `0b4d40f9` -> `e67b60fb`

- flake.lock
| [`6d367e9d`](https://github.com/nix-community/nix-index-database/commit/6d367e9d5e8941d73ae73d43ec7f3661ecc2dcdb) | `` flake.lock: Update `` |
> chore(flake/nix-index-database): `b6db9fd8` -> `6d367e9d`

- flake.lock
| [`c0ca47e8`](https://github.com/nix-community/nix-index-database/commit/c0ca47e8523b578464014961059999d8eddd4aae) | `` update generated.nix to release 2024-07-28-025730 `` |
> chore(flake/nix-index-database): `6d367e9d` -> `c0ca47e8`

- flake.lock
| [`a11cfcd0`](https://github.com/nix-community/home-manager/commit/a11cfcd0a18fdf6257808da631a956800af764bf) | `` micro: add package option ``                               |
| [`ea72cf54`](https://github.com/nix-community/home-manager/commit/ea72cf548fafb2876232a3ae22fcc03d5fb354de) | `` jujutsu: support darwin guidelines for config placement `` |
| [`9fdadb1c`](https://github.com/nix-community/home-manager/commit/9fdadb1cb65093015fc8cd65a592 …
> chore(flake/home-manager): `d0240a06` -> `a11cfcd0`

- flake.lock
| [`587fcca6`](https://github.com/nix-community/home-manager/commit/587fcca66e9d11c8e2357053c096a8a727c120ab) | `` eww: add terminal integration options `` |
> chore(flake/home-manager): `a11cfcd0` -> `587fcca6`

- flake.lock
| [`792757f6`](https://github.com/nix-community/home-manager/commit/792757f643cedc13f02098d8ed506d82e19ec1da) | `` firefox: support firefox derivatives `` |
> chore(flake/home-manager): `587fcca6` -> `792757f6`

- flake.lock
| [`1e6f8a7b`](https://github.com/nix-community/disko/commit/1e6f8a7b4634fc051cc9361959bf414fcf17e094) | `` flake.lock: Update `` |
> chore(flake/disko): `5b01cea8` -> `1e6f8a7b`

- flake.lock
| [`eab049fe`](https://github.com/NixOS/nixos-hardware/commit/eab049fe178c11395d65a858ba1b56461ba9652d) | `` surface: linux 6.9.9 -> 6.9.12 `` |
> chore(flake/nixos-hardware): `e67b60fb` -> `eab049fe`

- flake.lock
| [`5c633986`](https://github.com/nix-community/lanzaboote/commit/5c6339864f045dc3e3fd545956ad17d94decca01) | `` fix(deps): update all dependencies `` |
> chore(flake/lanzaboote): `2250c381` -> `0bc91abf`

- flake.lock
| [`89670e27`](https://github.com/nix-community/home-manager/commit/89670e27e101b9b30f5900fc1eb6530258d316b1) | `` home-manager: ignore hostname -f lookup errors `` |
> chore(flake/home-manager): `792757f6` -> `89670e27`

- flake.lock
| [`4fcd54df`](https://github.com/nix-community/home-manager/commit/4fcd54df7cbb1d79cbe81209909ee8514d6b17a4) | `` firefox: fix userChrome example `` |
> chore(flake/home-manager): `d34aaf7b` -> `4fcd54df`

- flake.lock
| [`4af1e89b`](https://github.com/nix-community/lanzaboote/commit/4af1e89bdc4b1f45b69ce806bdbcf6841bc01680) | `` chore(deps): lock file maintenance `` |
> chore(flake/lanzaboote): `0bc91abf` -> `f5a3a7df`

- flake.lock
| Commit                                                                                               | Message                      |
| ---------------------------------------------------------------------------------------------------- | ---------------------------- |
| [`768acdb0`](https://github.com/numtide/treefmt-nix/commit/768acdb06968e53aa1ee8de207fd955335c754b7) | `` feat: add gleam (#206) `` |
> chore(flake/treefmt): `8db8970b` -> `768acdb0`

- flake.lock
| [`14c33316`](https://github.com/NixOS/nixos-hardware/commit/14c333162ba53c02853add87a0000cbd7aa230c2) | `` treewide: remove uses of lib.mdDoc `` |
> chore(flake/nixos-hardware): `eab049fe` -> `14c33316`

- flake.lock
| Commit                                                                                         | Message                                  |
| ---------------------------------------------------------------------------------------------- | ---------------------------------------- |
| [`40012e5e`](https://github.com/ryantm/agenix/commit/40012e5ed4affbb5af7ea59770eb8d8fd1a5991b) | `` Remove import for NixOS/HM modules `` |
> chore(flake/agenix): `de96bd90` -> `3f1dae07`

- flake.lock
| [`7e1b215a`](https://github.com/nix-community/disko/commit/7e1b215a0a96efb306ad6440bf706d2b307dc267) | `` flake.lock: Update `` |
> chore(flake/disko): `1e6f8a7b` -> `7e1b215a`

- flake.lock
| [`d4ad8de1`](https://github.com/nix-community/nix-index-database/commit/d4ad8de1d6220d3f853c1d7b97da0c59344ab59a) | `` flake.lock: Update `` |
> chore(flake/nix-index-database): `c0ca47e8` -> `d4ad8de1`

- flake.lock
| [`97ca0a0f`](https://github.com/nix-community/nix-index-database/commit/97ca0a0fca0391de835f57e44f369a283e37890f) | `` update generated.nix to release 2024-08-04-025735 `` |
> chore(flake/nix-index-database): `d4ad8de1` -> `97ca0a0f`

- flake.lock
| [`0257e44f`](https://github.com/nix-community/disko/commit/0257e44f4ad472b54f19a6dd1615aee7fa48ed49) | `` flake.lock: Update `` |
> chore(flake/disko): `7e1b215a` -> `0257e44f`

- flake.lock
| [`2d366523`](https://github.com/cachix/git-hooks.nix/commit/2d366523b68afee27c0ddb40cd0f46c7c51ef563) | `` docs: add ruff-format to python list `` |
| [`509f5059`](https://github.com/cachix/git-hooks.nix/commit/509f50596bd654cbf4c124589d3a608879978341) | `` feat: add ruff-format ``                |
> chore(flake/git-hooks): `f451c193` -> `650538dc`

- flake.lock
| [`54ac8605`](https://github.com/cachix/git-hooks.nix/commit/54ac86058e30d476ae0ff4c428d40a8c3eb2581e) | `` fix: change ruff format hook name `` |
> chore(flake/git-hooks): `650538dc` -> `06939f6b`

- core/nixos.nix
- flake.lock
| [`57d30c7a`](https://github.com/NixOS/nixpkgs/commit/57d30c7a61d8fb3d8964a1f60c37f8f9c0b34a9c) | `` nixos/wg-quick: add generatePrivateKeyFile option (#331253) ``                  |
| [`12955826`](https://github.com/NixOS/nixpkgs/commit/129558261d9f1fb92c99f93ef259c698bc93db20) | `` buildkite-agent: 3.59.0 -> 3.76.1 (#331340) ``                                  |
| [`a18c10b8`](https://github.com/NixOS/nixpkgs/commit/a18c10b8c …
> chore(flake/nixpkgs): `9f918d61` -> `d0495308`

- flake.lock
| [`ffc1f95f`](https://github.com/nix-community/disko/commit/ffc1f95f6c28e1c6d1e587b51a2147027a3e45ed) | `` flake.lock: Update `` |
> chore(flake/disko): `0257e44f` -> `ffc1f95f`

- flake.lock
| [`107bb46e`](https://github.com/NixOS/nixos-hardware/commit/107bb46eef1f05e86fc485ee8af9b637e5157988) | `` surface: linux 6.9.12 -> 6.10.3 ``                      |
| [`e6d16f1b`](https://github.com/NixOS/nixos-hardware/commit/e6d16f1b6b4a3ab6f717f62965a8c1d23e6a502e) | `` surface: linux-surface arch-6.9.9-1 -> arch-6.10.3-1 `` |
> chore(flake/nixos-hardware): `14c33316` -> `107bb46e`

- flake.lock
| Commit                                                                                                   | Message                                                   |
| -------------------------------------------------------------------------------------------------------- | --------------------------------------------------------- |
| [`c53face7`](https://github.com/lovesegfault/vim-config/commit/c53face747c57ad16b9ca460f094a49f7f0f4962) | `` fix(telescope): disable annoying frecency safe mode `` |
> chore(flake/lovesegfault-vim-config): `fc89de0f` -> `c53face7`

- flake.lock
| [`6b923384`](https://github.com/lovesegfault/vim-config/commit/6b923384f655d72bfff779cd1acc1b3ff6add030) | `` chore(flake/nixvim): 1b135ded -> fab51138 `` |
> chore(flake/lovesegfault-vim-config): `c53face7` -> `6b923384`

- flake.lock
| Commit                                                                                                   | Message                                  |
| -------------------------------------------------------------------------------------------------------- | ---------------------------------------- |
| [`56f193e9`](https://github.com/lovesegfault/vim-config/commit/56f193e9fbba1799ee40e436975e2404013b77d5) | `` feat(lsp): add crates-nvim support `` |
> chore(flake/lovesegfault-vim-config): `6b923384` -> `56f193e9`

- flake.lock
| [`fcfca55f`](https://github.com/lovesegfault/vim-config/commit/fcfca55f6359371baf70235077dd9f6ffead7121) | `` chore(flake/nixvim): fab51138 -> 4852f94f ``    |
| [`1f67c46b`](https://github.com/lovesegfault/vim-config/commit/1f67c46bead9f358ccf811a3038b90a272c6a13b) | `` chore(flake/git-hooks): 3c977f1c -> c7012d0c `` |
> chore(flake/lovesegfault-vim-config): `56f193e9` -> `fcfca55f`

- flake.lock
| Commit                                                                                         | Message                                                |
| ---------------------------------------------------------------------------------------------- | ------------------------------------------------------ |
| [`e3413992`](https://github.com/ryantm/agenix/commit/e3413992fbc77176f5827949fd3d645288db1223) | `` age-home: Use curly-brackets for XDG_RUNTIME_DIR `` |
> chore(flake/agenix): `3f1dae07` -> `f6291c59`

- flake.lock
| [`5a3a9f95`](https://github.com/numtide/treefmt-nix/commit/5a3a9f956673111759d9643cf1a3ab81ee94cbf4) | `` fix: only eval enable option if visible (#214) `` |
> chore(flake/treefmt-nix): `768acdb0` -> `5a3a9f95`

- flake.lock
| Commit                                                                                               | Message                        |
| ---------------------------------------------------------------------------------------------------- | ------------------------------ |
| [`14c092e0`](https://github.com/numtide/treefmt-nix/commit/14c092e0326de759e16b37535161b3cb9770cea3) | `` Add renovate.json (#215) `` |
> chore(flake/treefmt-nix): `5a3a9f95` -> `14c092e0`

- flake.lock
| [`dfe45103`](https://github.com/NixOS/nixos-hardware/commit/dfe45103b691b66a9f5b22cbec99d32ee31e0a52) | `` lenovo/legion/16arha7: fix kernel check for speaker patch ``           |
| [`72b83c83`](https://github.com/NixOS/nixos-hardware/commit/72b83c838d756b6d019017cfafd645b314f85097) | `` asus-fx506hm: use nvidia-open by default ``                            |
| [`6ed55216`](https://github.com/NixOS/nixos-hardware/commit/6ed5521636 …
> chore(flake/nixos-hardware): `107bb46e` -> `dfe45103`

- flake.lock
| [`89681e85`](https://github.com/nix-community/nix-index-database/commit/89681e856ae1f342d0de07454b3d6a702b253db9) | `` flake.lock: Update `` |
> chore(flake/nix-index-database): `97ca0a0f` -> `89681e85`

- flake.lock
| Commit                                                                                                | Message                                                                                                                                                 |
| ----------------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------------------------------------------------------------------------- |
| [`c54cf53e`](https://github.com/NixOS/nixos-hardware/commit/c54cf53e022b0b3c1d3b8207aa0f9b194c24f0cf) | `` Tidy-up idents ``                                                                                                                                    |
| …
> chore(flake/nixos-hardware): `dfe45103` -> `c54cf53e`

- flake.lock
| [`4d99d0ca`](https://github.com/nix-community/nix-index-database/commit/4d99d0ca3cd57d65481a1ba749818b52b5a3fb3b) | `` update generated.nix to release 2024-08-11-025748 `` |
> chore(flake/nix-index-database): `89681e85` -> `4d99d0ca`

- flake.lock
| Commit                                                                                                            | Message                                 |
| ----------------------------------------------------------------------------------------------------------------- | --------------------------------------- |
| [`ec78079a`](https://github.com/nix-community/nix-index-database/commit/ec78079a904d7d55e81a0468d764d0fffb50ac06) | `` document which channel is indexed `` |
> chore(flake/nix-index-database): `4d99d0ca` -> `ec78079a`

- flake.lock
| Commit                                                                                               | Message                                                            |
| ---------------------------------------------------------------------------------------------------- | ------------------------------------------------------------------ |
| [`c9f97032`](https://github.com/numtide/treefmt-nix/commit/c9f97032be6816fa234f24803b8ae79dc7753a91) | `` fixup! fix: only eval enable option if visible (#214) (#218) `` |
> chore(flake/treefmt-nix): `14c092e0` -> `c9f97032`

- flake.lock
| [`e0e50b70`](https://github.com/lovesegfault/vim-config/commit/e0e50b70ebfb923f90f27305484332e5e81fa4b0) | `` chore(flake/nixpkgs): cb9a96f2 -> 5e0ca229 ``     |
| [`a9f1adf9`](https://github.com/lovesegfault/vim-config/commit/a9f1adf95baf88354506bcdb0f825cda5be10fba) | `` chore(flake/treefmt-nix): 768acdb0 -> c9f97032 `` |
| [`52cffce9`](https://github.com/lovesegfault/vim-config/commit/52cffce9a78937476c7ac132bd3d703679e51345) | `` chore(flake/nixvim): 4852f94f …
> chore(flake/lovesegfault-vim-config): `fcfca55f` -> `8dbf0a29`

- flake.lock
| [`0d510fe4`](https://github.com/nix-community/disko/commit/0d510fe40b56ed74907a021d7e1ffd0042592914) | `` flake.lock: Update `` |
> chore(flake/disko): `ffc1f95f` -> `0d510fe4`

- flake.lock
| Commit                                                                                                   | Message                                  |
| -------------------------------------------------------------------------------------------------------- | ---------------------------------------- |
| [`a53726a3`](https://github.com/lovesegfault/vim-config/commit/a53726a3039241a37dc7ce060608a8f6898d2d69) | `` fix(cmp): apply completion on <CR> `` |
> chore(flake/lovesegfault-vim-config): `8dbf0a29` -> `a53726a3`

- flake.lock
| Commit                                                                                               | Message                                                     |
| ---------------------------------------------------------------------------------------------------- | ----------------------------------------------------------- |
| [`349de7bc`](https://github.com/numtide/treefmt-nix/commit/349de7bc435bdff37785c2466f054ed1766173be) | `` fix: unset PRJ_ROOT to prevent impure behavior (#220) `` |
| [`f28662bc`](https://github.com/numtide/treefmt-nix/commit/f28662bca45de748787024a72930450a13115fe4) | `` {shellcheck,shfmt}: include `*.envrc.*` files (#221) ``  |
> chore(flake/treefmt-nix): `c9f97032` -> `349de7bc`

- flake.lock
| [`8229d116`](https://github.com/lovesegfault/vim-config/commit/8229d1162f3aabfb2759d92dca708efdba594a8d) | `` chore(flake/nixvim): f13bdef0 -> dbf6f7bc ``      |
| [`af9de5b3`](https://github.com/lovesegfault/vim-config/commit/af9de5b3b0185cd7c29251a179f61fb0b4bf1395) | `` chore(flake/treefmt-nix): c9f97032 -> 349de7bc `` |
> chore(flake/lovesegfault-vim-config): `a53726a3` -> `8229d116`

- flake.lock
| Commit                                                                                                   | Message                                |
| -------------------------------------------------------------------------------------------------------- | -------------------------------------- |
| [`3b745af0`](https://github.com/lovesegfault/vim-config/commit/3b745af0641d08cdbc8545da3559e0ad91230ed7) | `` feat: enable codelldb and dap-ui `` |
| [`e697defb`](https://github.com/lovesegfault/vim-config/commit/e697defb6dadb87089d95c07c032f12c6b749c9e) | `` feat: enable noice ``               |
> chore(flake/lovesegfault-vim-config): `8229d116` -> `3b745af0`

- flake.lock
| [`b7d1a23d`](https://github.com/lovesegfault/vim-config/commit/b7d1a23d896c38fa50e5272cb443bdf658b424e6) | `` chore(flake/nixpkgs): 5e0ca229 -> a58bc8ad `` |
> chore(flake/lovesegfault-vim-config): `3b745af0` -> `b7d1a23d`

- flake.lock
| [`fc6a179f`](https://github.com/numtide/treefmt-nix/commit/fc6a179f7a48fbf33c8c704dcda9f8435454089d) | `` mypy: allow adding custom paths to the shell `` |
> chore(flake/treefmt-nix): `349de7bc` -> `4a6d7dcc`

- flake.lock
| Commit                                                                                               | Message                                                                                |
| ---------------------------------------------------------------------------------------------------- | -------------------------------------------------------------------------------------- |
| [`d8a1d5e1`](https://github.com/nix-community/disko/commit/d8a1d5e1f0885d151801ef3e35251a475f53691e) | `` make-disk-image: allow vmTools qemu usage to be overriden by disko configuration `` |
| [`de015d2a`](https://github.com/nix-community/disko/commit/de015d2a44632ea1102522e609c0beba0e57a18b) | `` make-disk-image: allow pkgs to be overriden by disko configuration ``               |
| …
> chore(flake/disko): `0d510fe4` -> `f1e929d1`

- flake.lock
| [`276a0d05`](https://github.com/nix-community/disko/commit/276a0d055a720691912c6a34abb724e395c8e38a) | `` flake.lock: Update `` |
> chore(flake/disko): `f1e929d1` -> `276a0d05`

- flake.lock
| [`28bc2ed3`](https://github.com/lovesegfault/vim-config/commit/28bc2ed3770fae8da6f1dc64e81b6badb853a818) | `` chore(flake/nixvim): dbf6f7bc -> a96aa973 ``      |
| [`c173d8eb`](https://github.com/lovesegfault/vim-config/commit/c173d8ebe60608d7110522d7712ef435da61f5d4) | `` chore(flake/treefmt-nix): 349de7bc -> 4a6d7dcc `` |
> chore(flake/lovesegfault-vim-config): `b7d1a23d` -> `28bc2ed3`

- flake.lock
| Commit                                                                                                   | Message                                                   |
| -------------------------------------------------------------------------------------------------------- | --------------------------------------------------------- |
| [`e6bde458`](https://github.com/lovesegfault/vim-config/commit/e6bde458eed8ca3821d9d1b57a2f2e237b2e017c) | `` fix: bufferline diagnostics rename ``                  |
| [`12012c61`](https://github.com/lovesegfault/vim-config/commit/12012c6199c0384ef247bec993f868b65bd4bf1c) | `` Revert "chore(flake/nixpkgs): 5e0ca229 -> a58bc8ad" `` |
> chore(flake/lovesegfault-vim-config): `28bc2ed3` -> `e6bde458`

- flake.lock
| [`8b884663`](https://github.com/lovesegfault/vim-config/commit/8b88466382a22ea68c722344ce660c43bb4a437e) | `` chore(flake/nixpkgs): 5e0ca229 -> c3aa7b89 `` |
| [`6d9262f1`](https://github.com/lovesegfault/vim-config/commit/6d9262f183fe70fd498129362aaa73dc93c97865) | `` chore(flake/nixvim): a96aa973 -> ebd2182b ``  |
> chore(flake/lovesegfault-vim-config): `e6bde458` -> `8b884663`

- flake.lock
| [`7d94c09b`](https://github.com/numtide/treefmt-nix/commit/7d94c09bdbd4aa8f659d8aea10a17976896225fc) | `` feat: update nixpkgs input `` |
> chore(flake/treefmt-nix): `4a6d7dcc` -> `1d077395`

- flake.lock
| [`4aa3e707`](https://github.com/lovesegfault/vim-config/commit/4aa3e7073212ae2ce39a2f40f91cff8835a13693) | `` chore(flake/nixvim): 00f32f04 -> 78fc4be6 `` |
> chore(flake/lovesegfault-vim-config): `1520d675` -> `4aa3e707`

- flake.lock
| [`e68b726d`](https://github.com/lovesegfault/vim-config/commit/e68b726d228908bfb8671d926efbd126045de738) | `` chore(flake/treefmt-nix): 4a6d7dcc -> 1d077395 `` |
> chore(flake/lovesegfault-vim-config): `4aa3e707` -> `e68b726d`

- flake.lock
| [`39bc3e8c`](https://github.com/nix-community/nix-index-database/commit/39bc3e8c43432e8f6066cac179b30e3d58b3d4c5) | `` flake.lock: Update `` |
> chore(flake/nix-index-database): `ec78079a` -> `39bc3e8c`

- flake.lock
| [`392828aa`](https://github.com/nix-community/nix-index-database/commit/392828aafbed62a6ea6ccab13728df2e67481805) | `` update generated.nix to release 2024-08-18-025734 `` |
> chore(flake/nix-index-database): `39bc3e8c` -> `392828aa`

- flake.lock
| [`25988610`](https://github.com/nix-community/home-manager/commit/2598861031b78aadb4da7269df7ca9ddfc3e1671) | `` bash: add package option `` |
> chore(flake/home-manager): `086f619d` -> `25988610`

- flake.lock
| [`1a0a69e2`](https://github.com/nix-community/disko/commit/1a0a69e2aa159e853f457452263863fc33a5bee5) | `` Fix options.json rendering `` |
> chore(flake/disko): `276a0d05` -> `fd43891a`

- flake.lock
| [`6fdcca6b`](https://github.com/lovesegfault/vim-config/commit/6fdcca6ba8b1088a64255d67d8e37a18174fcc77) | `` chore(flake/nixvim): 78fc4be6 -> 7a11b66f `` |
> chore(flake/lovesegfault-vim-config): `e68b726d` -> `6fdcca6b`

- flake.lock
| [`4e719b38`](https://github.com/nix-community/disko/commit/4e719b38fa7c85f4f65d0308ca7084c91e7bdd6d) | `` flake.lock: Update `` |
> chore(flake/disko): `fd43891a` -> `4e719b38`

- flake.lock
| [`b09c4643`](https://github.com/NixOS/nixos-hardware/commit/b09c46430ffcf18d575acf5c339b38ac4e1db5d2) | `` Add Dell Latitude 5490 ``                               |
| [`feefc78f`](https://github.com/NixOS/nixos-hardware/commit/feefc78fbc4b205485eda0c1d9202c8f9288778a) | `` surface: linux 6.10.3 -> 6.10.5 ``                      |
| [`15c3e009`](https://github.com/NixOS/nixos-hardware/commit/15c3e00913f854e9a1e7d2df522fc5c00495e04c) | `` mergify: merge in …
> chore(flake/nixos-hardware): `c54cf53e` -> `b09c4643`

- flake.lock
| [`213f8050`](https://github.com/nix-community/impermanence/commit/213f8050c9e9ddd8382224f962bf46f1ce5ac54f) | `` nixos: Add assertion for persisting UIDs/GIDs `` |
> chore(flake/impermanence): `23c1f063` -> `9de98e03`

- flake.lock
- flake.nix
| Commit                                                                                         | Message                                                                                                 |
| ---------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------------------------- |
| [`34445ddb`](https://github.com/NixOS/nixpkgs/commit/34445ddb2de798c51bb54ccb4fa87f89b2de48d8) | `` pkgs/README: recommend & redirect to pkgs/by-name in versioning section ``                           |
| [`b4e3bdd7`](https://github.com/NixOS/nixpkgs/commit/b4e3bdd7f91e83e81f5fd85361635a4998475248) | `` python312Packages.pyfunctional: init at 1.4.3 (#329947) `` …
> chore(flake/nixpkgs): `5e0ca229` -> `8a335419`

- flake.lock
| [`07c51172`](https://github.com/lovesegfault/vim-config/commit/07c511721dbca9e700ec02f8289b5741f8cde2fb) | `` chore(flake/nixpkgs): c3aa7b89 -> 8a335419 `` |
| [`e2c402a2`](https://github.com/lovesegfault/vim-config/commit/e2c402a2b40db46f04f1661eb55ca193c850e5d6) | `` chore(flake/nixvim): 7a11b66f -> 312db6b6 ``  |
> chore(flake/lovesegfault-vim-config): `6fdcca6b` -> `07c51172`

- flake.lock
| [`03fe473c`](https://github.com/nix-community/impermanence/commit/03fe473c731cda2900bae9894b8dfc68e3492db5) | `` nixos: Formatting fixes ``                                                |
| [`785dd659`](https://github.com/nix-community/impermanence/commit/785dd6597b4fdc7f9f3b96a8f351be611ed56757) | `` nixos: Add option to toggle warnings ``                                   |
| …
> chore(flake/impermanence): `9de98e03` -> `03fe473c`

- flake.lock
| Commit                                                                                               | Message          |
| ---------------------------------------------------------------------------------------------------- | ---------------- |
| [`cc86fe1a`](https://github.com/nix-community/disko/commit/cc86fe1a7c5171f1949cc76b98dbd990cfb70b0c) | `` f2fs: init `` |
> chore(flake/disko): `4e719b38` -> `93d5cff6`

- flake.lock
| Commit                                                                                               | Message                                        |
| ---------------------------------------------------------------------------------------------------- | ---------------------------------------------- |
| [`ffc718f1`](https://github.com/nix-community/disko/commit/ffc718f15430274d236c564ef8474333aaa0bcd4) | `` module: fix options.json rendering again `` |
> chore(flake/disko): `93d5cff6` -> `c7b14da2`

- flake.lock
| Commit                                                                                               | Message                                                                |
| ---------------------------------------------------------------------------------------------------- | ---------------------------------------------------------------------- |
| [`5715bc02`](https://github.com/nix-community/disko/commit/5715bc02df0a1fa0250bdda196fa2c4c697ddc9c) | `` Update docs/interactive-vm.md ``                                    |
| [`a7656d48`](https://github.com/nix-community/disko/commit/a7656d4827d69c8c4892ec95105f7793470cbe9b) | `` Update README.md ``                                                 |
| [`a574d68d`](https://github.com/nix-community/disko/commit/a574d68d370d84f2e526c7b4cb0 …
> chore(flake/disko): `c7b14da2` -> `64335715`

- flake.lock
| [`5b36e65c`](https://github.com/nix-community/disko/commit/5b36e65c7c6eea6d4452e9e4f1f72ea376d8928f) | `` Fix the manual by fixing string escape `` |
> chore(flake/disko): `64335715` -> `74a12fdf`

- flake.lock
| [`ceb3a3ef`](https://github.com/lovesegfault/vim-config/commit/ceb3a3eff0af0531cf15fe5dfa2fdd8cd566ba59) | `` chore(flake/nixvim): 851edc8d -> b7f419a7 ``    |
| [`1726be53`](https://github.com/lovesegfault/vim-config/commit/1726be530b151406e293dd0595f0cefa0e939030) | `` chore(flake/git-hooks): 1064a45e -> 6cedaa7c `` |
> chore(flake/lovesegfault-vim-config): `a69de7d0` -> `ceb3a3ef`

- flake.lock
| [`4b866c99`](https://github.com/nix-community/disko/commit/4b866c9942d0f771ae934f04ca9859936f9bfbcf) | `` flake.lock: Update `` |
> chore(flake/disko): `74a12fdf` -> `4b866c99`

- flake.lock
| Commit                                                                                               | Message                    |
| ---------------------------------------------------------------------------------------------------- | -------------------------- |
| [`070f8347`](https://github.com/numtide/treefmt-nix/commit/070f834771efa715f3e74cd8ab93ecc96fabc951) | `` add toml-sort (#224) `` |
> chore(flake/treefmt-nix): `1d077395` -> `070f8347`

- flake.lock
| Commit                                                                                               | Message                                                            |
| ---------------------------------------------------------------------------------------------------- | ------------------------------------------------------------------ |
| [`43573714`](https://github.com/nix-community/disko/commit/435737144be0259559ca3b43f7d72252b1fdcc1b) | `` swap: don't create filesystem if randomEncryption is enabled `` |
| [`f6b2e005`](https://github.com/nix-community/disko/commit/f6b2e0052d9c4a22c36e38a402c14f6f42603843) | `` zfs_fs: Fix errors when not changing mountpoint ``              |
> chore(flake/disko): `4b866c99` -> `43573714`

- flake.lock
| [`293ab384`](https://github.com/lovesegfault/vim-config/commit/293ab384ed7886c9983cc0351be4ddc46a46529d) | `` chore(flake/nixpkgs): 8a335419 -> c374d94f ``     |
| [`eae6182d`](https://github.com/lovesegfault/vim-config/commit/eae6182d8c3f0cc13d2b4e412df07a85070c7bb3) | `` chore(flake/nixvim): b7f419a7 -> 1854d591 ``      |
| [`4065638d`](https://github.com/lovesegfault/vim-config/commit/4065638df6af1ff150e00050d5ffdd5b5308d472) | `` chore(flake/treefmt-nix): …
> chore(flake/lovesegfault-vim-config): `ceb3a3ef` -> `293ab384`

- flake.lock
| [`5dc25356`](https://github.com/nix-community/home-manager/commit/5dc25356567119127f046b347c3060a8dd607365) | `` Translate using Weblate (Hungarian) `` |
> chore(flake/home-manager): `b18f3ebc` -> `5dc25356`

- flake.lock
| [`c2cd2a52`](https://github.com/nix-community/home-manager/commit/c2cd2a52e02f1dfa1c88f95abeb89298d46023be) | `` submodule-support: add default values for top-level configs `` |
> chore(flake/home-manager): `5dc25356` -> `c2cd2a52`

- flake.lock
| [`403d66ed`](https://github.com/nix-community/impermanence/commit/403d66ed8dcd350ba9af97f53fc636c5dc25ddeb) | `` removed obsolete word `` |
> chore(flake/impermanence): `03fe473c` -> `c7f5b394`

- flake.lock
| [`1c84c314`](https://github.com/NixOS/nixos-hardware/commit/1c84c314db42dd40ed6cf9293b9451ec2e7ebee4) | `` 16ach6h: Use the hardware.display module ``      |
| [`d3600fc2`](https://github.com/NixOS/nixos-hardware/commit/d3600fc29620a5fba432f3180ca9c7a84e3f8889) | `` xps13-9380: enable fwupd ``                      |
| [`59bcb4c4`](https://github.com/NixOS/nixos-hardware/commit/59bcb4c4e19bf4edfa95a14a58776a67d0171ce0) | `` lenovo/p14s/intel: init with gen3 ``             | …
> chore(flake/nixos-hardware): `b09c4643` -> `1c84c314`

- flake.lock
| [`97d97fba`](https://github.com/lovesegfault/vim-config/commit/97d97fba7c4e40d335ea85b838b165ced23a29fb) | `` chore(flake/nixvim): 4c8d3559 -> 8234ee85 `` |
> chore(flake/lovesegfault-vim-config): `35af94ee` -> `97d97fba`

- flake.lock
| Commit                                                                                           | Message                                                |
| ------------------------------------------------------------------------------------------------ | ------------------------------------------------------ |
| [`2bd4949a`](https://github.com/LnL7/nix-darwin/commit/2bd4949af3984b1b568f65e68a12a1410d7ba03d) | `` etc: add known hash for DetSys installer 0.20.0+ `` |
> chore(flake/darwin): `ea319a73` -> `ac5694a0`

- flake.lock
| [`f65c9d6e`](https://github.com/nix-community/nix-index-database/commit/f65c9d6efae4ee39f4341aaed073cf2d56fb0ecb) | `` update generated.nix to release 2024-08-25-025816 `` |
| [`fc681ad7`](https://github.com/nix-community/nix-index-database/commit/fc681ad740f0adee9777504accce70a78d3a49b2) | `` flake.lock: Update ``                                |
> chore(flake/nix-index-database): `392828aa` -> `f65c9d6e`

- flake.lock
| [`9fc19be2`](https://github.com/NixOS/nixos-hardware/commit/9fc19be21f0807d6be092d70bf0b1de0c00ac895) | `` doc: add missing Apple iMac entry `` |
> chore(flake/nixos-hardware): `1c84c314` -> `9fc19be2`

- flake.lock
| Commit                                                                                                            | Message                                |
| ----------------------------------------------------------------------------------------------------------------- | -------------------------------------- |
| [`e333d62b`](https://github.com/nix-community/nix-index-database/commit/e333d62b70b179da1dd78d94315e8a390f2d12e5) | `` README: mention nix-darwin usage `` |
> chore(flake/nix-index-database): `f65c9d6e` -> `e333d62b`

- flake.lock
| [`b09eb605`](https://github.com/nix-community/disko/commit/b09eb605e376c9e95c87c0ef3fcb8008e11c8368) | `` flake.lock: Update `` |
> chore(flake/disko): `43573714` -> `b09eb605`

- flake.lock
| [`c3e1df8d`](https://github.com/lovesegfault/vim-config/commit/c3e1df8da889ae862bf17cfeb886921080f9c95c) | `` chore(flake/nixpkgs): c374d94f -> d0e1602d `` |
| [`6668f74e`](https://github.com/lovesegfault/vim-config/commit/6668f74e284eb2c1b0545f77687215d2e39605f3) | `` chore(flake/nixvim): 8234ee85 -> eac092c8 ``  |
> chore(flake/lovesegfault-vim-config): `97d97fba` -> `c3e1df8d`

- flake.lock
| Commit                                                                                               | Message                |
| ---------------------------------------------------------------------------------------------------- | ---------------------- |
| [`517664d2`](https://github.com/nix-community/disko/commit/517664d2fd762ea53f63fcf5f60e73dfd2a8566b) | `` Fix writeDashBin `` |
> chore(flake/disko): `b09eb605` -> `b89a6112`

- flake.lock
| [`74020a84`](https://github.com/lovesegfault/vim-config/commit/74020a84966d9ec3a1f0f57e61c1934f1635892b) | `` chore(flake/nixvim): eac092c8 -> 48141474 ``    |
| [`e6edf7cc`](https://github.com/lovesegfault/vim-config/commit/e6edf7cc70508e49815db28fe2ed63e52f1ba8df) | `` chore(flake/git-hooks): c8a54057 -> 1cd12de6 `` |
> chore(flake/lovesegfault-vim-config): `c3e1df8d` -> `74020a84`

- flake.lock
| [`3ffd842a`](https://github.com/numtide/treefmt-nix/commit/3ffd842a5f50f435d3e603312eefa4790db46af5) | `` feat(programs): add fish_indent (#199) ``                    |
| [`eb283bca`](https://github.com/numtide/treefmt-nix/commit/eb283bca8b2bac3634747eafcaa57ebd71e2cdcb) | `` globally ignore go.mod/go.sum (#222) ``                      |
| [`0b9a6936`](https://github.com/numtide/treefmt-nix/commit/0b9a69360f18b7da94ee2c4395eb025901a62f29) | `` …
> chore(flake/treefmt-nix): `070f8347` -> `3ffd842a`

- flake.lock
| [`c4e1b82a`](https://github.com/NixOS/nixos-hardware/commit/c4e1b82a91c7b1b4c74aa39c573ddbf31a49d3e9) | `` gpu/intel: cleanup vdpau variable `` |
> chore(flake/nixos-hardware): `9fc19be2` -> `c4e1b82a`

- flake.lock
| Commit                                                                                                | Message                     |
| ----------------------------------------------------------------------------------------------------- | --------------------------- |
| [`95c3dfe6`](https://github.com/NixOS/nixos-hardware/commit/95c3dfe6ef2e96ddc1ccdd7194e3cda02ca9a8ef) | `` Apple iMac 14,2: init `` |
> chore(flake/nixos-hardware): `c4e1b82a` -> `95c3dfe6`

- flake.lock
| [`511388d8`](https://github.com/nix-community/disko/commit/511388d837178979de66d14ca4a2ebd5f7991cd3) | `` flake.lock: Update `` |
> chore(flake/disko): `b89a6112` -> `511388d8`

- flake.lock
| [`544db369`](https://github.com/LnL7/nix-darwin/commit/544db3691c98a9bcc56b360cf3cf20bd41257ca3) | `` Add sha256 for DeterminateSystems Nix installer 0.22.0 `` |
> chore(flake/darwin): `ac5694a0` -> `c8d3157d`

- flake.lock
| [`6d65ecb8`](https://github.com/lovesegfault/vim-config/commit/6d65ecb853dca2f7154eee8aabcef21ed10f8645) | `` chore(flake/nixpkgs): d0e1602d -> 71e91c40 `` |
| [`c1cd9cd1`](https://github.com/lovesegfault/vim-config/commit/c1cd9cd13b0ae80e02fd16debb1cc99e4a3a4c81) | `` chore(flake/nixvim): 70e9532e -> 2704133f ``  |
> chore(flake/lovesegfault-vim-config): `d443fe59` -> `6d65ecb8`

- flake.lock
| Commit                                                                                                   | Message                                    |
| -------------------------------------------------------------------------------------------------------- | ------------------------------------------ |
| [`1957ef2c`](https://github.com/hercules-ci/flake-parts/commit/1957ef2c4ba04e213c59380a19e46c9fcee38d0e) | `` Dogfood flakeModules.partitions ``      |
| [`0d5122e8`](https://github.com/hercules-ci/flake-parts/commit/0d5122e84c0d7606363f89f0924245317c2fe3a0) | `` Add flakeModules.partitions ``          |
| [`c07ef7e5`](https://github.com/hercules-ci/flake-parts/commit/c07ef7e578fbb1a2e964615e0faee1949371cd22) | `` Dogfood lib.mkFlake ``                  |
| …
> chore(flake/flake-parts): `8471fe90` -> `1e6fc322`

- flake.lock
| Commit                                                                                                   | Message                                             |
| -------------------------------------------------------------------------------------------------------- | --------------------------------------------------- |
| [`f112e301`](https://github.com/hercules-ci/flake-parts/commit/f112e301b33a8c0fbe7f65eac7a793e2dd8d3bf6) | `` Fix test ``                                      |
| [`1728089f`](https://github.com/hercules-ci/flake-parts/commit/1728089f3e8a28df678f60cc52cff4219ade477d) | `` flakeModules.partitions: Improve and fix docs `` |
| [`358ab837`](https://github.com/hercules-ci/flake-parts/commit/358ab8370e9726e60c16cb299c8138228fb0301e) | `` reference to Nix manual `` …
> chore(flake/flake-parts): `1e6fc322` -> `af510d4a`

- flake.lock
| [`0fc330c2`](https://github.com/lovesegfault/vim-config/commit/0fc330c2c9f51cec12ed00a3ee0d65eacbe6bb04) | `` chore(flake/nixvim): 2704133f -> 56208f9e ``      |
| [`b33e85d2`](https://github.com/lovesegfault/vim-config/commit/b33e85d2a2b5389beac5dc0c08b1f4b4c9365245) | `` chore(flake/flake-parts): 8471fe90 -> af510d4a `` |
> chore(flake/lovesegfault-vim-config): `6d65ecb8` -> `0fc330c2`

- flake.lock
| [`8962b84c`](https://github.com/lovesegfault/vim-config/commit/8962b84c3b1d4bef743ff9bf79204529ad80f772) | `` chore(flake/nixvim): 56208f9e -> caefb266 `` |
> chore(flake/lovesegfault-vim-config): `0fc330c2` -> `8962b84c`

- flake.lock
| [`32058e91`](https://github.com/nix-community/nix-index-database/commit/32058e9138248874773630c846563b1a78ee7a5b) | `` update generated.nix to release 2024-09-01-031416 `` |
| [`78ccfbc4`](https://github.com/nix-community/nix-index-database/commit/78ccfbc4a41fa8461b23aa1a999f9c3ced1882c9) | `` flake.lock: Update ``                                |
> chore(flake/nix-index-database): `e333d62b` -> `32058e91`

- flake.lock
| Commit                                                                                           | Message                                                         |
| ------------------------------------------------------------------------------------------------ | --------------------------------------------------------------- |
| [`75d14c62`](https://github.com/LnL7/nix-darwin/commit/75d14c62cbc4360cbd1a1b5c52dbd17b8bd08892) | `` gpg: Suppress stderr from gpg-connect-agent on shell init `` |
> chore(flake/darwin): `c8d3157d` -> `7c4b53a7`

- flake.lock
| [`a3f57937`](https://github.com/lovesegfault/vim-config/commit/a3f57937438b766945b3c973355f166134a98af5) | `` chore(flake/nixpkgs): 71e91c40 -> 12228ff1 ``     |
| [`6abc9f5d`](https://github.com/lovesegfault/vim-config/commit/6abc9f5dfc8394d1de46e9541f463866c5bdf2e9) | `` chore(flake/flake-parts): af510d4a -> 567b938d `` |
> chore(flake/lovesegfault-vim-config): `8962b84c` -> `a3f57937`

- flake.lock
| [`96073e64`](https://github.com/nix-community/disko/commit/96073e6423623d4a8027e9739d2af86d6422ea7a) | `` flake.lock: Update `` |
> chore(flake/disko): `511388d8` -> `96073e64`

- flake.lock
| [`14b9565b`](https://github.com/numtide/treefmt-nix/commit/14b9565b02f77e3c1c89293a05e703942d62fbde) | `` mypy: fix python path not beeing set ``                      |
| [`966dfb4a`](https://github.com/numtide/treefmt-nix/commit/966dfb4afff31af74f5a7a9a34d80f869fb3b4af) | `` mypy: don't set any PYTHONPATH if we don't have a package `` |
| [`c8a2bda8`](https://github.com/numtide/treefmt-nix/commit/c8a2bda80cd465167f4ccc021d91877a84205fe4) | `` mypy: …
> chore(flake/treefmt-nix): `3ffd842a` -> `23c2b0d9`

- flake.lock
| [`65e10308`](https://github.com/numtide/treefmt-nix/commit/65e10308caf73e744c6e408307c9f1887a1fd4c7) | `` feat: update nixpkgs input `` |
> chore(flake/treefmt-nix): `23c2b0d9` -> `9fb342d1`

- flake.lock
| [`e8742c24`](https://github.com/lovesegfault/vim-config/commit/e8742c241e9fe2c081a77044eb51f43ad74c98b2) | `` chore(flake/treefmt-nix): 3ffd842a -> 9fb342d1 `` |
> chore(flake/lovesegfault-vim-config): `a3f57937` -> `e8742c24`

- flake.lock
| [`70a22d25`](https://github.com/nix-community/disko/commit/70a22d25a2695caca52379aa94c514941fe687c3) | `` Switch to qcow2 in the interactive VM. `` |
> chore(flake/disko): `96073e64` -> `85538a44`

- flake.lock
| [`099b6cca`](https://github.com/nix-community/disko/commit/099b6cca33cd283ca6b2aafe6ce96154f1b2300c) | `` btrfs: add swap priority, options `` |
| [`39b40917`](https://github.com/nix-community/disko/commit/39b4091769fd4c7974c6866e9c8448da92e45ccf) | `` swap: add mountOptions ``            |
> chore(flake/disko): `85538a44` -> `099b6cca`

- flake.lock
| Commit                                                                                                    | Message                                                                               |
| --------------------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------- |
| [`8373faed`](https://github.com/nix-community/lanzaboote/commit/8373faed37a49eeff3a07f4ab4af1d11b10930fe) | `` chore: remove comment about error bubbling with sbsign ``                          |
| [`30713d76`](https://github.com/nix-community/lanzaboote/commit/30713d769ad9b990272a56870976b1283916369f) | `` chore(naming): rename LanzabooteSigner into Signer ``                              |
| …
> chore(flake/lanzaboote): `f5a3a7df` -> `e7bd94e0`

- flake.lock
| Commit                                                                                               | Message                                                            |
| ---------------------------------------------------------------------------------------------------- | ------------------------------------------------------------------ |
| [`8f0f75f1`](https://github.com/nix-community/disko/commit/8f0f75f1a8a6764d52be25d2d2e89866b25502b4) | `` zpool: better error message if zpool has no assigned devices `` |
| [`736c8150`](https://github.com/nix-community/disko/commit/736c8150b93f413ff976b80e3e4d7970f408a4f3) | `` disk-deactivate: also clear zpool labels ``                     |
| [`c789d113`](https://github.com/nix-community/disko/commit/c789d113c623e2d162fbb19a87c29ba4518396c6) …
> chore(flake/disko): `099b6cca` -> `e55f9a86`

- flake.lock
| [`24bc1f98`](https://github.com/NixOS/nixos-hardware/commit/24bc1f98d8db75306bceb82cdb345a1189bc2064) | `` lenovo: fix unstable wifi on Yoga laptops `` |
> chore(flake/nixos-hardware): `95c3dfe6` -> `24bc1f98`

- flake.lock
| Commit                                                                                                | Message                                                                                               |
| ----------------------------------------------------------------------------------------------------- | ----------------------------------------------------------------------------------------------------- |
| [`366ddc33`](https://github.com/NixOS/nixos-hardware/commit/366ddc33ff1b93d95ef3809d12ce0fba74c8d316) | `` flake.nix: don't expose nvidia modules
``                                                         |
| [`ca005ac1`](https://github.com/NixOS/nixos-hardware/commit/ca005ac1e8392f1da8bb06f64b84dfee226f543a) | `` fix: spelling errors `` …
> chore(flake/nixos-hardware): `24bc1f98` -> `366ddc33`

- flake.lock
| [`12acfdef`](https://github.com/NixOS/nixos-hardware/commit/12acfdefc1d352a382f5e875fc9a6c48ab989e08) | `` dell-xps-17-9700: Add nvidia architecture `` |
| [`dec757bf`](https://github.com/NixOS/nixos-hardware/commit/dec757bf4ebd310df00b19e54daa6ef1b241ec21) | `` dell-xps-15-9560: Add nvidia architecture `` |
| [`9f9cf89d`](https://github.com/NixOS/nixos-hardware/commit/9f9cf89d3370df3ffc307e77ca881b9a4dd76095) | `` dell-xps-15-9550: Add nvidia architecture `` |
| …
> chore(flake/nixos-hardware): `366ddc33` -> `f7e31ff8`

- flake.lock
| [`19fba44e`](https://github.com/NixOS/nixos-hardware/commit/19fba44ecefcedab6cc3c299074732c0764a7a98) | `` lenovo-legion-16ach6h: Add nvidia architecture ``           |
| [`a5e2826f`](https://github.com/NixOS/nixos-hardware/commit/a5e2826fc2b75cb6f1ac012fa3dd80602817ef67) | `` Set mkDefault for enabling bluetooth. ``                    |
| [`aa3739f4`](https://github.com/NixOS/nixos-hardware/commit/aa3739f4ab414b2b0b212cf235d0682f14de3d4a) | `` …
> chore(flake/nixos-hardware): `f7e31ff8` -> `ba7bb376`

- flake.lock
| [`3b6e461e`](https://github.com/NixOS/nixos-hardware/commit/3b6e461e6d4ef6c6f419172626b4296e143d58e9) | `` lenovo-legion-15arh05h: add NVIDIA architecture `` |
| [`6776df50`](https://github.com/NixOS/nixos-hardware/commit/6776df50ee0b5ae8ce8d5f3f652b101934eeb2b7) | `` Adding Asus Zephyrus G16 GU605MY ``                |
> chore(flake/nixos-hardware): `ba7bb376` -> `85810799`

- flake.lock
| [`731717e8`](https://github.com/lovesegfault/vim-config/commit/731717e8d5159c1dc8469ee547da2cc1d9d908e9) | `` chore(flake/nixvim): caefb266 -> 3f9cf9f9 `` |
> chore(flake/lovesegfault-vim-config): `e8742c24` -> `731717e8`

- flake.lock
| [`ace1cedf`](https://github.com/NixOS/nixos-hardware/commit/ace1cedf3ecfbac81b29522d71009878951a69eb) | `` msigl65: add initial configuration (#1106) `` |
> chore(flake/nixos-hardware): `85810799` -> `ace1cedf`

- flake.lock
| [`c50dd00a`](https://github.com/NixOS/nixos-hardware/commit/c50dd00a787ad747c65153a24a3dbd1e638f7e26) | `` system76-gaze18: Add nvidia architecture ``                 |
| [`75ac0969`](https://github.com/NixOS/nixos-hardware/commit/75ac0969d8207867df3f541bf64133dd91e4a213) | `` omen-16-n0280nd: Add nvidia architecture ``                 |
| [`d6e07be2`](https://github.com/NixOS/nixos-hardware/commit/d6e07be2cd9e8fcbb47499475ed11cbe19645464) | `` …
> chore(flake/nixos-hardware): `ace1cedf` -> `880be1ab`

- flake.lock
| [`e1b6f307`](https://github.com/LnL7/nix-darwin/commit/e1b6f307ecfa88e9759646b22c8b9ece580e1b78) | `` linux-builder: make `package.nixosConfig` accurate `` |
> chore(flake/darwin): `7c4b53a7` -> `92bd25c2`

- flake.lock
| [`7d569851`](https://github.com/nix-community/home-manager/commit/7d569851e95e8b360a3d7a2f52c5fc6a597a7657) | `` flake.lock: Update ``                      |
| [`5b95e061`](https://github.com/nix-community/home-manager/commit/5b95e0611b498fac7c8425d1b1bc4cacfd64e7f0) | `` Translate using Weblate (Hungarian) ``     |
| [`b00bdf59`](https://github.com/nix-community/home-manager/commit/b00bdf59c0aa5515a0a8e1773fa19128e7efa181) | `` xdg: add option 'xdg.stateFile' ``         | …
> chore(flake/home-manager): `471e3eb0` -> `7d569851`

- flake.lock
| Commit                                                                                           | Message                                                                    |
| ------------------------------------------------------------------------------------------------ | -------------------------------------------------------------------------- |
| [`c3341753`](https://github.com/LnL7/nix-darwin/commit/c334175319949f6887dcab89afb32f1bb38e9f88) | `` nixos/github-runner: quote comma separators so as to pass shellcheck `` |
| [`97e0f727`](https://github.com/LnL7/nix-darwin/commit/97e0f7275966cfab018aaee1a0d1e5ce74cd8901) | `` users: allow arbitrary group IDs ``                                     |
> chore(flake/darwin): `92bd25c2` -> `76559183`

- flake.lock
| [`127ccc3e`](https://github.com/nix-community/home-manager/commit/127ccc3eb7e36fa75e8c3fbd8a343154f66cc1c6) | `` i3/sway: support str type for font size `` |
> chore(flake/home-manager): `7d569851` -> `127ccc3e`

- flake.lock
| [`9ded619d`](https://github.com/nix-community/impermanence/commit/9ded619dfb84584fac1faa2645aaf0d2ad4a2520) | `` nixos: Consider regular filesystem mounts in /var/lib/nixos warning `` |
> chore(flake/impermanence): `c7f5b394` -> `63f4d044`

- flake.lock
| [`04a1cda0`](https://github.com/NixOS/nixos-hardware/commit/04a1cda0c1725094a4db703cccbb956b7558f5a6) | `` starlabs: init, add starlite 5 tablet ``               |
| [`502e0aed`](https://github.com/NixOS/nixos-hardware/commit/502e0aed3102124d7034a2ed2ed245e35c9b9a4e) | `` apple-macbook-pro-8-1: add README.md ``                |
| [`1b3a5471`](https://github.com/NixOS/nixos-hardware/commit/1b3a5471263d91705dc6ab8bc2597013befe0561) | `` Treewide: Add new profile …
> chore(flake/nixos-hardware): `880be1ab` -> `04a1cda0`

- flake.lock
| [`64227544`](https://github.com/nix-community/nix-index-database/commit/642275444c5a9defce57219c944b3179bf2adaa9) | `` update generated.nix to release 2024-09-08-030302 `` |
| [`0fbe4bbd`](https://github.com/nix-community/nix-index-database/commit/0fbe4bbdd0cd8b255f0182653814dec3accde827) | `` flake.lock: Update ``                                |
> chore(flake/nix-index-database): `32058e91` -> `64227544`

- flake.lock
| Commit                                                                                                | Message                                                                                       |
| ----------------------------------------------------------------------------------------------------- | --------------------------------------------------------------------------------------------- |
| [`755813cb`](https://github.com/NixOS/nixos-hardware/commit/755813cba87f62a9da1492d9473efea2b17b9386) | `` asus/zephyrus/gu605my: enable asusd by default and fix mic mute button ``                  |
| [`cfb3537b`](https://github.com/NixOS/nixos-hardware/commit/cfb3537b1562e45d9ddfb2b26896b6d12fe525ca) | `` asus/zephyrus/gu605my: fixed architecture and added dynamic boost as enabled by …
> chore(flake/nixos-hardware): `04a1cda0` -> `755813cb`

- flake.lock
| Commit                                                                                         | Message                                                                                       |
| ---------------------------------------------------------------------------------------------- | --------------------------------------------------------------------------------------------- |
| [`87c8bf47`](https://github.com/NixOS/nixpkgs/commit/87c8bf47ee4ae706a7144719c2a409fb006150eb) | `` kubernetes-helmPlugins.helm-diff: 3.9.9 -> 3.9.10 ``                                       |
| [`6350c71d`](https://github.com/NixOS/nixpkgs/commit/6350c71d9bea84b0562df8d24956bc1079d53169) | `` music-player: format ``                                                                    |
| …
> chore(flake/nixpkgs): `12228ff1` -> `574d1eac`

- flake.lock
| [`d44fcf46`](https://github.com/lovesegfault/vim-config/commit/d44fcf46668ae01f8c14319547f8d50e7f27e180) | `` chore(flake/nixvim): 5330427e -> facf6b2d `` |
> chore(flake/lovesegfault-vim-config): `d8cb12c9` -> `d44fcf46`

- flake.lock
| [`f8afac41`](https://github.com/lovesegfault/vim-config/commit/f8afac41ce4f15296c0eb4a6b3f8624e490ce34f) | `` chore(deps): bump DeterminateSystems/nix-installer-action from 13 to 14 `` |
> chore(flake/lovesegfault-vim-config): `d44fcf46` -> `f8afac41`

- flake.lock
| [`15f64efc`](https://github.com/LnL7/nix-darwin/commit/15f64efcaf936f3b77955018d29b4802be6b144f) | `` zsh: prefer Nix completions these from Zsh package ``  |
| [`4d59f660`](https://github.com/LnL7/nix-darwin/commit/4d59f660bc41ba35b1f6df829e8e0b7706b35ee7) | `` zsh: move fpath init from /etc/zshrc to /etc/zshenv `` |
> chore(flake/darwin): `5b2d8e9a` -> `4c96bd69`

- flake.lock
| Commit                                                                                           | Message                                                                 |
| ------------------------------------------------------------------------------------------------ | ----------------------------------------------------------------------- |
| [`95f063ea`](https://github.com/LnL7/nix-darwin/commit/95f063ea069e1752ddede8c9823a1b75ddd7858a) | `` tests/users-groups: update for `lib.escapeShellArg` change ``        |
| [`dea497f6`](https://github.com/LnL7/nix-darwin/commit/dea497f67a641d2d85f5673c3695f0fe43d46f64) | `` tests/networking-hostname: update for `lib.escapeShellArg` change `` |
> chore(flake/darwin): `4c96bd69` -> `8220423c`

- flake.lock
| [`a75942b4`](https://github.com/lovesegfault/vim-config/commit/a75942b4a18f797544ff6fe55beb41cb45550502) | `` chore(flake/nixvim): facf6b2d -> fc7e9b29 `` |
> chore(flake/lovesegfault-vim-config): `f8afac41` -> `a75942b4`

- flake.lock
| Commit                                                                                                   | Message                        |
| -------------------------------------------------------------------------------------------------------- | ------------------------------ |
| [`666e6d81`](https://github.com/lovesegfault/vim-config/commit/666e6d816323299295c1655df8e42c1aec93ad3e) | `` feat: enable vim-matchup `` |
> chore(flake/lovesegfault-vim-config): `a75942b4` -> `666e6d81`

- flake.lock
| [`fac3b211`](https://github.com/lovesegfault/vim-config/commit/fac3b211f41bb802be009e6188aa744f4d7b639f) | `` chore(flake/nixvim): fc7e9b29 -> 11c133e8 `` |
> chore(flake/lovesegfault-vim-config): `666e6d81` -> `fac3b211`

- flake.lock
| [`0943a50e`](https://github.com/nix-community/disko/commit/0943a50ee76a889623c6f9e8d21f60c3bdbeed55) | `` interactive-vm: convert into NixOS module ``      |
| [`ba66c22e`](https://github.com/nix-community/disko/commit/ba66c22ec110eed24ff0010b5623e18a2a5f128d) | `` Add `virtualisation.vmVariantWithDisko` option `` |
> chore(flake/disko): `e55f9a86` -> `495c2d76`

- flake.lock
| Commit                                                                                               | Message                                                |
| ---------------------------------------------------------------------------------------------------- | ------------------------------------------------------ |
| [`59fb64b3`](https://github.com/nix-community/disko/commit/59fb64b36b0a1961f6d4c6d5b8db45cc35d040f2) | `` make-disk-image: automatically add ZFS to kernel `` |
> chore(flake/disko): `495c2d76` -> `59fb64b3`

- flake.lock
| [`e8106163`](https://github.com/lovesegfault/vim-config/commit/e8106163a47025ffcd8af2acafbecff934d72cdd) | `` chore(flake/flake-parts): 567b938d -> bcef6817 `` |
> chore(flake/lovesegfault-vim-config): `fac3b211` -> `e8106163`

- flake.lock
| [`c82fc8cf`](https://github.com/nix-community/home-manager/commit/c82fc8cf3f75e667ad9dd3e5df721119b63723b3) | `` home-manager: use `hostname` from GNU inetutils `` |
| [`2b1957a0`](https://github.com/nix-community/home-manager/commit/2b1957a0a3db7d63c1844abb84223655c30a7eb0) | `` home-manager: fix early exit due to FQDN error ``  |
> chore(flake/home-manager): `da8406a6` -> `c82fc8cf`

- flake.lock
| [`433e6866`](https://github.com/nix-community/home-manager/commit/433e686675ba24176fe3383916a4bd1c9799c676) | `` autorandr: configModule.extraConfig ``              |
| [`ef506124`](https://github.com/nix-community/home-manager/commit/ef506124579ff6280a43a9596bb2a5049872bf8e) | `` gpg-agent: add launchd service agent and sockets `` |
> chore(flake/home-manager): `c82fc8cf` -> `433e6866`

- flake.lock
| [`4c8647b1`](https://github.com/nix-community/home-manager/commit/4c8647b1ed35d0e1822c7997172786dfa18cd7da) | `` trayscale: add module ``                          |
| [`daaf0c2f`](https://github.com/nix-community/home-manager/commit/daaf0c2f8da6c7b5dc04dd62a3d98422f259551b) | `` kanshi: add support for output aliases ``         |
| [`cb3ab592`](https://github.com/nix-community/home-manager/commit/cb3ab5928cbe8ac3cfee7010ccad4c31dbc1fb5f) | `` helix: add …
> chore(flake/home-manager): `433e6866` -> `4c8647b1`

- flake.lock
| [`0f0b7f40`](https://github.com/nix-community/disko/commit/0f0b7f409d84fa0c843f9612deef8bb115628c56) | `` ci(Mergify): configuration update `` |
> chore(flake/disko): `59fb64b3` -> `4ef99d8e`

- flake.lock
| [`7923c691`](https://github.com/nix-community/home-manager/commit/7923c691527d2ee85fe028c6e780ac3bf8606f06) | `` neovide: add module `` |
> chore(flake/home-manager): `4c8647b1` -> `7923c691`

- flake.lock
| [`503af483`](https://github.com/nix-community/home-manager/commit/503af483e1b328691ea3a434d331995595fb2e3d) | `` eza: add support for fish abbreviations `` |
| [`076c78ed`](https://github.com/nix-community/home-manager/commit/076c78edede4e7abc71af0b1610fb1fc1c0fac29) | `` fish: add `preferAbbrs` option ``          |
> chore(flake/home-manager): `7923c691` -> `503af483`

- flake.lock
| [`ed9914d7`](https://github.com/lovesegfault/vim-config/commit/ed9914d7b0ff1caaee4cc76f44ecdc43c04b7441) | `` chore(flake/nixvim): 11c133e8 -> 4e5bd1d7 `` |
> chore(flake/lovesegfault-vim-config): `e8106163` -> `ed9914d7`

- flake.lock
| [`7edf6cca`](https://github.com/nix-community/home-manager/commit/7edf6ccaec8001cb20368bf1bf6a677178cae07b) | `` Add translation using Weblate (Hindi) ``     |
| [`e94bee95`](https://github.com/nix-community/home-manager/commit/e94bee957400c8f871d9b9ea54308e15d664242c) | `` Translate using Weblate (Hindi) ``           |
| [`898eaef7`](https://github.com/nix-community/home-manager/commit/898eaef7ea906ddc8e86d57957f2a701878bfb05) | `` Translate using Weblate (Russian) `` …
> chore(flake/home-manager): `503af483` -> `7edf6cca`

- flake.lock
| [`6c1a461a`](https://github.com/nix-community/home-manager/commit/6c1a461a444e6ccb3f3e42bb627b510c3a722a57) | `` mopidy: reduce test closure size ``          |
| [`c6e4ec39`](https://github.com/nix-community/home-manager/commit/c6e4ec39df78245f7ce678476ff068515763345b) | `` z-lua: add support for fish abbreviations `` |
| [`0d118885`](https://github.com/nix-community/home-manager/commit/0d118885b2840447b5b7f2b6097b4511ed3d02e9) | `` lsd: add support for fish …
> chore(flake/home-manager): `7edf6cca` -> `6c1a461a`

- flake.lock
| Commit                                                                                               | Message                                                                    |
| ---------------------------------------------------------------------------------------------------- | -------------------------------------------------------------------------- |
| [`1eb54f6e`](https://github.com/nix-community/disko/commit/1eb54f6efc1f34073d9a641a6d6d16a534c36555) | `` build(deps): bump DeterminateSystems/update-flake-lock from 23 to 24 `` |
> chore(flake/disko): `4ef99d8e` -> `3632080c`

- flake.lock
| [`c753aba4`](https://github.com/lovesegfault/vim-config/commit/c753aba4dfa280644bc025bcba064295777ab6ff) | `` chore(flake/nixvim): 4e5bd1d7 -> f1881b4e `` |
> chore(flake/lovesegfault-vim-config): `ed9914d7` -> `c753aba4`

- flake.lock
| [`0a2fba62`](https://github.com/nix-community/nix-index-database/commit/0a2fba621b6bbf06be0b4edd974236e3d2fcc1a9) | `` flake.lock: Update `` |
> chore(flake/nix-index-database): `64227544` -> `0a2fba62`

- flake.lock
| [`cc4d4a4b`](https://github.com/nix-community/disko/commit/cc4d4a4b91612b210748366f447a992a950f6b34) | `` make-disk-image: convert into NixOS module `` |
> chore(flake/disko): `3632080c` -> `51e3a7e5`

- flake.lock
- hosts/poincare/default.nix
- nix/darwin.nix
| Commit                                                                                           | Message                                                                    |
| ------------------------------------------------------------------------------------------------ | -------------------------------------------------------------------------- |
| [`953d02ba`](https://github.com/LnL7/nix-darwin/commit/953d02ba5958df017d9682f727d10a75cb8a0391) | `` {bash,zsh}: remove nix-shell early return in /etc/{bashrc,zshenv} ``    |
| [`04e3cfc8`](https://github.com/LnL7/nix-darwin/commit/04e3cfc822568d354b540a3207121af27b699057) | `` version: make `system.stateVersion` mandatory ``                        |
| [`537097b3`](https://github.com/LnL7/nix-darwin/commit/537097b3312b6089535d715b5f4a6e2 …
> chore(flake/darwin): `f4f18f3d` -> `21fe31f2`

- flake.lock
| [`86a67829`](https://github.com/lovesegfault/vim-config/commit/86a6782985eecb1d1a37e1fe4f73689d0e696b95) | `` chore(flake/nixvim): f1881b4e -> 95b322a5 `` |
> chore(flake/lovesegfault-vim-config): `c753aba4` -> `86a67829`

- flake.lock
| [`b9ab7e57`](https://github.com/NixOS/nixos-hardware/commit/b9ab7e57c5d1d456cdeef252d345f3bca9c55851) | `` build(deps): bump cachix/install-nix-action from V27 to 28 `` |
> chore(flake/nixos-hardware): `166dee4f` -> `b9ab7e57`

- flake.lock
| [`4ee6bd22`](https://github.com/NixOS/nixos-hardware/commit/4ee6bd22af1bd75bb403e2f0e1af0161eb69cccc) | `` framework: fix outdated documentation on fw-ectool `` |
> chore(flake/nixos-hardware): `b9ab7e57` -> `dc8b0296`

- flake.lock
| [`521fc3d5`](https://github.com/nix-community/disko/commit/521fc3d5ad1fad5bebc00b3387bb40dd7d5b7cf9) | `` build(deps): bump cachix/install-nix-action from V27 to 28 `` |
> chore(flake/disko): `51e3a7e5` -> `22ee467a`

- flake.lock
| [`607417b2`](https://github.com/lovesegfault/vim-config/commit/607417b27b6992a1a58c239c833af0fc49763b0c) | `` chore(flake/nixvim): 95b322a5 -> 2e3083e4 `` |
> chore(flake/lovesegfault-vim-config): `86a67829` -> `607417b2`

- flake.lock
| [`5cf05d4d`](https://github.com/numtide/treefmt-nix/commit/5cf05d4d96842affc3e8f2c1e7e707e4f5d82a99) | `` inputs: use `nixpkgs-unstable` instead of `nixos-unstable` `` |
> chore(flake/treefmt-nix): `9fb342d1` -> `77dd46bf`

- flake.lock
| Commit                                                                                               | Message                                                                  |
| ---------------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------ |
| [`fa06cc1b`](https://github.com/numtide/flake-utils/commit/fa06cc1b3d9f8261138ab7e1bc54d115cfcdb6ea) | `` lib: eachDefaultSystemPassThrough/eachSystemPassThrough: init ``      |
| [`58351e44`](https://github.com/numtide/flake-utils/commit/58351e44283ebaf4fa49c4ec1e50754f6ec9ed5e) | `` lib: eachSystem: optimize hot path by assuming rare --impure usage `` |
| [`db82e07b`](https://github.com/numtide/flake-utils/commit/db82e07bd4c49c5e191 …
> chore(flake/flake-utils): `b1d9ab70` -> `c1dfcf08`

- flake.lock
| [`88b015b9`](https://github.com/nix-community/disko/commit/88b015b9eb65edefc0b6501980a3d53cd1764637) | `` make-disk-image: fix spelling for `--help` `` |
| [`d52ca376`](https://github.com/nix-community/disko/commit/d52ca37645b7bd48efeea0e40299713f1c9e04ba) | `` docs: rename `vdb` -> `main` ``               |
> chore(flake/disko): `22ee467a` -> `88b015b9`

- flake.lock
| Commit                                                                                               | Message                                                |
| ---------------------------------------------------------------------------------------------------- | ------------------------------------------------------ |
| [`d32d1504`](https://github.com/nix-community/disko/commit/d32d1504c77d7f6ba7e033357dcf638baceab9b7) | `` zpool: support updating zfsprops on root dataset `` |
| [`a9eeea33`](https://github.com/nix-community/disko/commit/a9eeea33793bc8c16fd72d4d7db60c5d51a419d6) | `` zfs_fs: support updating mountpoint properly ``     |
> chore(flake/disko): `88b015b9` -> `d32d1504`

- flake.lock
| [`4a4a8b14`](https://github.com/nix-community/home-manager/commit/4a4a8b145463ccfef579bb0e26275c97bf0b5bf2) | `` firefox: fix languagepacks policy `` |
> chore(flake/home-manager): `a9c9cc6e` -> `4a4a8b14`

- flake.lock
| [`d2493de5`](https://github.com/nix-community/home-manager/commit/d2493de5cd1da06b6a4c3e97f4e7d5dd791df457) | `` ci: remove 23.11 from dependabot ``          |
| [`4974dfb2`](https://github.com/nix-community/home-manager/commit/4974dfb26e1c84d22bfdf943d41a33c9e51209a8) | `` thunderbird: change settings type to json `` |
> chore(flake/home-manager): `4a4a8b14` -> `d2493de5`

- flake.lock
| [`4550dd59`](https://github.com/lovesegfault/vim-config/commit/4550dd594b45c0840fdb62c18d41abc497c4c4e4) | `` chore(flake/treefmt-nix): 9fb342d1 -> 77dd46bf `` |
> chore(flake/lovesegfault-vim-config): `607417b2` -> `4550dd59`

- flake.lock
| [`8ca3f4a2`](https://github.com/lovesegfault/vim-config/commit/8ca3f4a2bd1f4ae06a74d3107cf9faeea78872a1) | `` chore(flake/nixpkgs): 574d1eac -> 99dc8785 `` |
> chore(flake/lovesegfault-vim-config): `4550dd59` -> `8ca3f4a2`

- flake.lock
| [`41266e63`](https://github.com/numtide/treefmt-nix/commit/41266e63a00c55b488f8f977051d4bd20e77f644) | `` feat(programs): add dart format (#232) `` |
> chore(flake/treefmt-nix): `77dd46bf` -> `41266e63`

- flake.lock
| [`32f4fb0b`](https://github.com/NixOS/nixos-hardware/commit/32f4fb0b11fcf3395317ca97a627aa39395d9bff) | `` apple-t2: remove ifd and cleanup drv `` |
> chore(flake/nixos-hardware): `dc8b0296` -> `270ddd75`

- flake.lock
| [`23a4ea7a`](https://github.com/NixOS/nixos-hardware/commit/23a4ea7a0d1c5cb52f6f3ace8ce5b85da9e3b9e6) | `` lenovo-yoga-6-13ALC6: add mkDefault for bluetooth `` |
> chore(flake/nixos-hardware): `270ddd75` -> `abb44860`

- flake.lock
| [`5545a2a9`](https://github.com/lovesegfault/vim-config/commit/5545a2a98e27cba4e3201a58b5c4b5dfe2e78d87) | `` chore(flake/nixvim): 2e3083e4 -> 6cbf441c `` |
> chore(flake/lovesegfault-vim-config): `8ca3f4a2` -> `5545a2a9`

- flake.lock
| [`93a5b01a`](https://github.com/lovesegfault/vim-config/commit/93a5b01aebfeae287ecf0904734f9d87ed99b632) | `` chore(flake/treefmt-nix): 77dd46bf -> 41266e63 `` |
| [`bc9a8829`](https://github.com/lovesegfault/vim-config/commit/bc9a8829c982a2265cb644c9097179e64d766915) | `` chore(flake/nixvim): 6cbf441c -> 9307b201 ``      |
> chore(flake/lovesegfault-vim-config): `5545a2a9` -> `93a5b01a`

- flake.lock
| [`284529ce`](https://github.com/numtide/treefmt-nix/commit/284529cebe0f41f459210c617100d6d723ae37a7) | `` Add meson to README ``   |
| [`434a5069`](https://github.com/numtide/treefmt-nix/commit/434a50690c715fe3a2b35852433a29763f54fdf9) | `` Add meson example ``     |
| [`2ca2bf4e`](https://github.com/numtide/treefmt-nix/commit/2ca2bf4e3e821451e8936549279024f08ef5a139) | `` Add meson's formatter `` |
> chore(flake/treefmt-nix): `41266e63` -> `829338a3`

- flake.lock
| Commit                                                                                                | Message                                                                             |
| ----------------------------------------------------------------------------------------------------- | ----------------------------------------------------------------------------------- |
| [`10d5e0ec`](https://github.com/NixOS/nixos-hardware/commit/10d5e0ecc32984c1bf1a9a46586be3451c42fd94) | `` asus-rog-strix-x570: add nct6775 kernel module for temperature and fan sensor `` |
| [`1c8c4f2c`](https://github.com/NixOS/nixos-hardware/commit/1c8c4f2c79468be23fcd7f87f8cee519e564cba2) | `` apple/t2: bump kernel to 6.11 ``                                                 |
> chore(flake/nixos-hardware): `abb44860` -> `10d5e0ec`

- flake.lock
| [`c5853dcb`](https://github.com/nix-community/disko/commit/c5853dcb32ad4a7711af9513ddfc49da171d5f00) | `` module: throw if no disks are defined ``             |
| [`706a1722`](https://github.com/nix-community/disko/commit/706a1722f6844ec749d6557c034a9eb6cff18c48) | `` module: always populate `system.build` attributes `` |
> chore(flake/disko): `d32d1504` -> `a31fe5ef`

- flake.lock
| [`01abe60f`](https://github.com/numtide/treefmt-nix/commit/01abe60f41e6227ca2b68759dba975e764a2f3fe) | `` chore: fmt ``                      |
| [`c58f3be1`](https://github.com/numtide/treefmt-nix/commit/c58f3be12ab7d4bc589604c413cf0ac50575e28c) | `` feat(programs): add latexindent `` |
> chore(flake/treefmt-nix): `829338a3` -> `ee41a466`

- flake.lock
| [`1f7b8188`](https://github.com/nix-community/home-manager/commit/1f7b8188a9c9c5ba32f9a8351c55f42ecc22b77c) | `` zoxide: replace outdated flag in "options" example ``         |
| [`87c7d4df`](https://github.com/nix-community/home-manager/commit/87c7d4df161d0eafc0c8fe93a98ba5247a83d969) | `` firefox: fix policies availability ``                         |
| [`451606f4`](https://github.com/nix-community/home-manager/commit/451606f4a843752f …
> chore(flake/home-manager): `75781766` -> `1f7b8188`

- flake.lock
| [`3646c278`](https://github.com/nix-community/disko/commit/3646c27805de33af846d35a5aa545e5a22711048) | `` update project logo `` |
> chore(flake/disko): `a31fe5ef` -> `624fd864`

- flake.lock
| [`1786e2af`](https://github.com/nix-community/home-manager/commit/1786e2afdbc48e9038f7cff585069736e1d0ed44) | `` firefox: fix incorrect condition `` |
> chore(flake/home-manager): `b5e09b85` -> `1786e2af`

- flake.lock
| [`2cf3abce`](https://github.com/nix-community/home-manager/commit/2cf3abce034432cb357c0a6a670481819c55f564) | `` neovim: use `home.shellAliases` `` |
> chore(flake/home-manager): `1786e2af` -> `2cf3abce`

- flake.lock
| [`8d7e352a`](https://github.com/nix-community/home-manager/commit/8d7e352a4b25ac2d88a881ffa3472680af916ddc) | `` poweralertd: Enable passing CLI args to the daemon ``          |
| [`6b191238`](https://github.com/nix-community/home-manager/commit/6b1912380e5577063401f58a2deb985fdc7cdc60) | `` ci: bump DeterminateSystems/update-flake-lock from 23 to 24 `` |
| [`f48b181f`](https://github.com/nix-community/home-manager/commit/f48b181f0161 …
> chore(flake/home-manager): `2cf3abce` -> `8d7e352a`

- flake.lock
| [`4803bf55`](https://github.com/nix-community/home-manager/commit/4803bf558bdf20cb067aceb8830b7ad70113f4e3) | `` swayidle: make -w optional `` |
> chore(flake/home-manager): `8d7e352a` -> `4803bf55`

- flake.lock
| Commit                                                                                               | Message                                   |
| ---------------------------------------------------------------------------------------------------- | ----------------------------------------- |
| [`9adb48e6`](https://github.com/nix-community/disko/commit/9adb48e682a42a52b83f9093b55020913a0f911f) | `` add workaround for flakey zfs tests `` |
| [`93c1dde4`](https://github.com/nix-community/disko/commit/93c1dde4190ecde415de3a47ba42163306b06998) | `` tests/f2fs: add compression ``         |
| [`da8bfaf1`](https://github.com/nix-community/disko/commit/da8bfaf1d5b8b4ca1d1a46aea116ebabf35d8d2a) | `` shellcheck: also disable SC2054 ``     |
| …
> chore(flake/disko): `624fd864` -> `0fe77990`

- flake.lock
| [`0b052dd8`](https://github.com/nix-community/home-manager/commit/0b052dd8119005c6ba819db48bcc657e48f401b7) | `` swayidle: minor cleanups `` |
> chore(flake/home-manager): `4803bf55` -> `0b052dd8`

- flake.lock
| [`51994df8`](https://github.com/nix-community/disko/commit/51994df8ba24d5db5459ccf17b6494643301ad28) | `` imageBuilder: add defaultText `` |
> chore(flake/disko): `0fe77990` -> `51994df8`

- flake.lock
| [`b8d53aac`](https://github.com/lovesegfault/vim-config/commit/b8d53aac054f6e75fd0545f588944c365647129e) | `` chore(flake/nixpkgs): 99dc8785 -> c04d5652 `` |
| [`409993ec`](https://github.com/lovesegfault/vim-config/commit/409993ece9a9f47441cb39c2ee7e3ed9bc6d165b) | `` chore(flake/nixvim): 400d1d92 -> 3211ce35 ``  |
> chore(flake/lovesegfault-vim-config): `b819b6c7` -> `b8d53aac`

- flake.lock
| [`b493dfd4`](https://github.com/NixOS/nixos-hardware/commit/b493dfd4a8cf9552932179e56ff3b5819a9b8381) | `` update flakes ``                                    |
| [`1e27e79a`](https://github.com/NixOS/nixos-hardware/commit/1e27e79ab2697ec1b7b84edccd32d5f4e79946e6) | `` CONTRIBUTING.md: Update testing instructions ``     |
| [`d64ae016`](https://github.com/NixOS/nixos-hardware/commit/d64ae0165303096700cb101f8d7e35eb9ba3aa4e) | `` test/run: format file and remove …
> chore(flake/nixos-hardware): `10d5e0ec` -> `b493dfd4`

- flake.lock
| [`3215f516`](https://github.com/lovesegfault/vim-config/commit/3215f5168d2848a8f3fa35d1b066902dedebb3ea) | `` chore(flake/nixvim): 3211ce35 -> 2bc6a949 `` |
> chore(flake/lovesegfault-vim-config): `b8d53aac` -> `3215f516`

- flake.lock
| [`034c45dd`](https://github.com/LnL7/nix-darwin/commit/034c45dd0cac806b527e64c143020676e1070769) | `` feat: use wait4path with script launchd option `` |
> chore(flake/darwin): `c03f85fa` -> `f5927529`

- flake.lock
| Commit                                                                                           | Message                                                       |
| ------------------------------------------------------------------------------------------------ | ------------------------------------------------------------- |
| [`db92fac3`](https://github.com/LnL7/nix-darwin/commit/db92fac3a9552ac3338977dcaf4cd15acf4aac08) | `` flake: match NixOS definition of `nixpkgs.flake.source` `` |
> chore(flake/darwin): `f5927529` -> `bd7d1e39`

- flake.lock
| [`230536ce`](https://github.com/NixOS/nixos-hardware/commit/230536ce884a14aab03518da71d417f57461805b) | `` update tests flake lock ``                   |
| [`cbcd0302`](https://github.com/NixOS/nixos-hardware/commit/cbcd0302c724608acbdbc6d1350c75014bcec272) | `` starfive visionfive2: use mainline kernel `` |
> chore(flake/nixos-hardware): `b493dfd4` -> `d0cb432a`

- flake.lock
| Commit                                                                                               | Message               |
| ---------------------------------------------------------------------------------------------------- | --------------------- |
| [`49b22d48`](https://github.com/nix-community/disko/commit/49b22d486c2bd1ce3102881c948e58c14b58152a) | `` delete old logo `` |
> chore(flake/disko): `51994df8` -> `49b22d48`

- flake.lock
| Commit                                                                                               | Message                                               |
| ---------------------------------------------------------------------------------------------------- | ----------------------------------------------------- |
| [`35dfece1`](https://github.com/numtide/treefmt-nix/commit/35dfece10c642eb52928a48bee7ac06a59f93e9a) | `` feat: add typos, a spellchecking program (#239) `` |
> chore(flake/treefmt-nix): `ee41a466` -> `35dfece1`

- flake.lock
| Commit                                                                                               | Message                                                     |
| ---------------------------------------------------------------------------------------------------- | ----------------------------------------------------------- |
| [`b1d6bed2`](https://github.com/nix-community/disko/commit/b1d6bed240abef5f5373e88fc7909f493013e557) | `` interactive-vm: use host pkgs in the launcher script. `` |
| [`e72de070`](https://github.com/nix-community/disko/commit/e72de0702d21b62ffd384b6da4ba46a274242458) | `` add workaround for failing zpool import test ``          |
> chore(flake/disko): `49b22d48` -> `b1d6bed2`

- flake.lock
| [`22c38239`](https://github.com/lovesegfault/vim-config/commit/22c382398e3e97e9c13ef28af0afcf72e1fa6c71) | `` chore(flake/nixpkgs): c04d5652 -> 9357f4f2 `` |
| [`83a15b9f`](https://github.com/lovesegfault/vim-config/commit/83a15b9f5f8e5bfcaf44241fc0df85b31a1be629) | `` chore(flake/nixvim): b473bdc5 -> 47364df4 ``  |
| [`92faa9a7`](https://github.com/lovesegfault/vim-config/commit/92faa9a746be19530212f989bf1f62fb913a0449) | `` fix: enable web-devicons explicitly ``        | …
> chore(flake/lovesegfault-vim-config): `3215f516` -> `22c38239`

- flake.lock
| [`6d2914c6`](https://github.com/nix-community/disko/commit/6d2914c62c5ca27276b75f1cc75e11356984cb0b) | `` Add binlore for disko and disko-install `` |
> chore(flake/disko): `b1d6bed2` -> `c61e50b6`

- flake.lock
| [`6d42596a`](https://github.com/nix-community/disko/commit/6d42596a35d34918a905e8539a44d3fc91f42b5b) | `` lvm: add missing dm-snapshot `` |
> chore(flake/disko): `c61e50b6` -> `6d42596a`

- flake.lock
| [`7448d149`](https://github.com/nix-community/impermanence/commit/7448d149b0489f709aa6841d5d2af0635f14d69f) | `` nixos: Fix duplicate definition causing syntax error ``                |
| [`1bfbbfae`](https://github.com/nix-community/impermanence/commit/1bfbbfae306143c737f320f8f90dd6e09e79250d) | `` nixos: Create persisted dirs marked as needed for boot before mount `` |
> chore(flake/impermanence): `63f4d044` -> `8514fff0`

- flake.lock
| [`f1cc1f3b`](https://github.com/lovesegfault/vim-config/commit/f1cc1f3bed7fccf75e2de1d9dd10da4b845ebf79) | `` chore(flake/nixvim): 47364df4 -> 8f991cc8 ``      |
| [`3c00fe1f`](https://github.com/lovesegfault/vim-config/commit/3c00fe1f8a6f59d01c1596038a8664a3738e5a08) | `` chore(flake/treefmt-nix): ee41a466 -> 35dfece1 `` |
> chore(flake/lovesegfault-vim-config): `22c38239` -> `f1cc1f3b`

- flake.lock
| [`1f8e67e9`](https://github.com/nix-community/disko/commit/1f8e67e945fcfc54bfca5c4d082569b3115a466b) | `` Always add dm-snapshot when LVM is used `` |
> chore(flake/disko): `6d42596a` -> `c1c472f4`

- flake.lock
| Commit                                                                                               | Message                                    |
| ---------------------------------------------------------------------------------------------------- | ------------------------------------------ |
| [`9ee50d37`](https://github.com/numtide/treefmt-nix/commit/9ee50d37acbbc37fc51335d9bfd0f4c8d2d9867b) | `` meson: format all meson files (#242) `` |
> chore(flake/treefmt-nix): `35dfece1` -> `9ee50d37`

- flake.lock
| [`a83bf1f8`](https://github.com/lovesegfault/vim-config/commit/a83bf1f85437ee8205fd08d4a65c5c2e10ca78ac) | `` chore(flake/treefmt-nix): 35dfece1 -> 1bff2ba6 `` |
| [`b43ad19d`](https://github.com/lovesegfault/vim-config/commit/b43ad19d67eaa80cf0cb567f4de363a9f3d22926) | `` chore(flake/nixvim): 8f991cc8 -> 7bda0f1c ``      |
> chore(flake/lovesegfault-vim-config): `f1cc1f3b` -> `a83bf1f8`

- flake.lock
| Commit                                                                                               | Message                                                                         |
| ---------------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------- |
| [`18c5410f`](https://github.com/nix-community/disko/commit/18c5410fdfa506cab20e678c58a4fecfd1d47006) | `` make-disk-image: use memSize as default build-memory in diskoImagesScript `` |
> chore(flake/disko): `c1c472f4` -> `1879e489`

- flake.lock
| [`72c867c4`](https://github.com/nix-community/disko/commit/72c867c4396b4ba81de13049191210b6ff065702) | `` Run nix fmt ``                            |
| [`4c4c869c`](https://github.com/nix-community/disko/commit/4c4c869c2de0fe697ec1e3a50f245c8f31f8b49a) | `` flake: add --check option to formatter `` |
> chore(flake/disko): `1879e489` -> `67dc29be`

- flake.lock
| [`57e6b30d`](https://github.com/nix-community/home-manager/commit/57e6b30d181ae6baff0909a61544ecbe1f642936) | `` direnv: work around nushell bug `` |
> chore(flake/home-manager): `c124568e` -> `57e6b30d`

- flake.lock
| [`853e7bd2`](https://github.com/nix-community/home-manager/commit/853e7bd24f875bac2e3a0cf72f993e917d0f8cf5) | `` direnv: even better nushell fix `` |
> chore(flake/home-manager): `57e6b30d` -> `853e7bd2`

- flake.lock
| [`ffe2d07e`](https://github.com/nix-community/home-manager/commit/ffe2d07e771580a005e675108212597e5b367d2d) | `` direnv: hopefully final nushell fix ``          |
| [`0afc2f0f`](https://github.com/nix-community/home-manager/commit/0afc2f0f19470e45a3941926a330f2db55ac2fbf) | `` river: reduce risk of large rebuilds in test `` |
> chore(flake/home-manager): `853e7bd2` -> `ffe2d07e`

- flake.lock
| [`8ba5f379`](https://github.com/lovesegfault/vim-config/commit/8ba5f379fa2668ae4aed4de8fac2278a2a9eae02) | `` chore(flake/nixpkgs): 9357f4f2 -> 30439d93 `` |
| [`5fa1c022`](https://github.com/lovesegfault/vim-config/commit/5fa1c022df9bc71fda4e90b384f013980984fcf0) | `` chore(flake/nixvim): 7bda0f1c -> 6a1bf6bd ``  |
> chore(flake/lovesegfault-vim-config): `a83bf1f8` -> `8ba5f379`

- flake.lock
| [`879b29ae`](https://github.com/numtide/treefmt-nix/commit/879b29ae9a0378904fbbefe0dadaed43c8905754) | `` feat: add nixfmt-classic (#238) `` |
> chore(flake/treefmt-nix): `1bff2ba6` -> `879b29ae`

- flake.lock
| Commit                                                                                                | Message                                                                            |
| ----------------------------------------------------------------------------------------------------- | ---------------------------------------------------------------------------------- |
| [`d830ad47`](https://github.com/NixOS/nixos-hardware/commit/d830ad47cc992b4a46b342bbc79694cbd0e980b2) | `` feat: add galp5-1650 ``                                                         |
| [`f4d60b37`](https://github.com/NixOS/nixos-hardware/commit/f4d60b3777bef2b3f11d5c87c78d5c4b510145cb) | `` Remove fonts.fontconfig.dpi in Lenovo Thinkpad X1 6th Gen QHD ``                |
| …
> chore(flake/nixos-hardware): `d0cb432a` -> `d830ad47`

- flake.lock
| [`f4329332`](https://github.com/lovesegfault/vim-config/commit/f432933228f6a631d960db3628fb5d8773909646) | `` chore(flake/treefmt-nix): 1bff2ba6 -> 879b29ae `` |
| [`fec70dab`](https://github.com/lovesegfault/vim-config/commit/fec70dabff2aa89b0993ad8582d9d1890f24667c) | `` chore(flake/nixvim): 6a1bf6bd -> b5c19b6a ``      |
> chore(flake/lovesegfault-vim-config): `8ba5f379` -> `f4329332`

- flake.lock
| Commit                                                                                              | Message                                       |
| --------------------------------------------------------------------------------------------------- | --------------------------------------------- |
| [`a1eb366d`](https://github.com/serokell/deploy-rs/commit/a1eb366d134308e6e8db781e15b05c6f2cf3de83) | `` doc: add option doc for interactiveSudo `` |
> chore(flake/deploy-rs): `3867348f` -> `aa07eb05`

- flake.lock
| [`8c307827`](https://github.com/lovesegfault/vim-config/commit/8c30782707e9a518a114f55b767945139067af3d) | `` chore(flake/nixpkgs): 30439d93 -> 1925c603 `` |
> chore(flake/lovesegfault-vim-config): `f4329332` -> `8c307827`

- flake.lock
| [`c1f051bf`](https://github.com/NixOS/nixos-hardware/commit/c1f051bf032273b9f0e707c8826eb25122d279fa) | `` Add 'mkDefault' to several settings for Asus Zephyrus GA402X ``             |
| [`1c62abd2`](https://github.com/NixOS/nixos-hardware/commit/1c62abd2dd79652fedebebe196ed194a4573f573) | `` Disable USB wakeup on the 8295 ITE Device on Asus Zephyrus GA402X laptop `` |
> chore(flake/nixos-hardware): `d830ad47` -> `c1f051bf`

- flake.lock
| [`b709e1cc`](https://github.com/nix-community/disko/commit/b709e1cc33fcde71c7db43850a55ebe6449d0959) | `` interactive-vm: override `forceImportRoot` `` |
> chore(flake/disko): `67dc29be` -> `b709e1cc`

- flake.lock
| [`2061ba26`](https://github.com/NixOS/nixos-hardware/commit/2061ba2611eb29efb24ffe4d730fc29ad20503a2) | `` dell-precision-5560: remove redundant config `` |
| [`a4e69fc9`](https://github.com/NixOS/nixos-hardware/commit/a4e69fc9ba6728f7ea9c8b7cb9c72b3744885880) | `` dell-precision-5560: add README ``              |
| [`c97623b4`](https://github.com/NixOS/nixos-hardware/commit/c97623b428306711dc07dc68fd98b9f0b882ba3c) | `` dell-precision-5560: cleanup ``                 |
| …
> chore(flake/nixos-hardware): `c1f051bf` -> `fb08bde0`

- flake.lock
| [`a8fb3f78`](https://github.com/nix-community/impermanence/commit/a8fb3f78a9c9f36ac5f391e86a8836f3e4055531) | `` nixos: Fix create-needed-for-boot-dirs dependencies for zfs `` |
> chore(flake/impermanence): `8514fff0` -> `fff0d95c`

- flake.lock
| [`0ad811c1`](https://github.com/lovesegfault/vim-config/commit/0ad811c1f49ba8daafff705c2da2bf5c8c04d71e) | `` chore(flake/nixvim): b5c19b6a -> 2c4e4681 ``    |
| [`0ce367bf`](https://github.com/lovesegfault/vim-config/commit/0ce367bf26f9342523876742cd68254576174ae5) | `` chore(flake/git-hooks): 4e743a69 -> 85f7a717 `` |
> chore(flake/lovesegfault-vim-config): `8c307827` -> `0ad811c1`

- flake.lock
| [`8e8c6cba`](https://github.com/NixOS/nixos-hardware/commit/8e8c6cbad12ef805268b4e380a7298fbc275898d) | `` Add new profile for HP Laptop 14s dq2024nf `` |
> chore(flake/nixos-hardware): `fb08bde0` -> `8e8c6cba`

- flake.lock
| [`e88d3715`](https://github.com/NixOS/nixos-hardware/commit/e88d37154f74e2bc2545514612dd20a16bb3e2f0) | `` Framework 16: use upstream libinput keyboard detection `` |
> chore(flake/nixos-hardware): `8e8c6cba` -> `e88d3715`

- flake.lock
| Commit                                                                                                | Message                                                                              |
| ----------------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------ |
| [`f5c239fa`](https://github.com/NixOS/nixos-hardware/commit/f5c239fa9acb27f0a5326ba2949c00fada89ca9f) | `` asus/zephyrus/ga402x/shared.nix: no need to override default of mkEnableOption `` |
| [`1bc47d8a`](https://github.com/NixOS/nixos-hardware/commit/1bc47d8abfb98fda9e90d357d14abded85163b6c) | `` asus/zenbook/ux371: enable xe driver explicitly ``                                |
| …
> chore(flake/nixos-hardware): `e88d3715` -> `f5c239fa`

- flake.lock
| [`82f2b478`](https://github.com/nix-community/impermanence/commit/82f2b4785afc723786af248c5e8b7c5ba9d48fca) | `` nixos: Fix create-needed-for-boot-dirs label-adressed dependencies `` |
> chore(flake/impermanence): `fff0d95c` -> `d0b38e55`

- flake.lock
| [`f15445bc`](https://github.com/lovesegfault/vim-config/commit/f15445bcbb79cbccf4273e412211bbcbe330a449) | `` chore(flake/nixvim): 2c4e4681 -> 5f4a4b47 `` |
> chore(flake/lovesegfault-vim-config): `0ad811c1` -> `f15445bc`

- flake.lock
| [`11c43c83`](https://github.com/NixOS/nixos-hardware/commit/11c43c830e533dad1be527ecce379fcf994fbbb5) | `` build(deps): bump cachix/install-nix-action from V28 to 29 `` |
> chore(flake/nixos-hardware): `f5c239fa` -> `11c43c83`

- flake.lock
| [`92b2c8b4`](https://github.com/lovesegfault/vim-config/commit/92b2c8b4b305d8966a0fa535cd2d1b4dfba2c850) | `` refactor(cmp): use luaConfig.post for autopairs setup `` |
> chore(flake/lovesegfault-vim-config): `f15445bc` -> `92b2c8b4`

- flake.lock
| [`9ea2edc4`](https://github.com/lovesegfault/vim-config/commit/9ea2edc4f3721607176857f5a5f0e945a8454060) | `` chore(flake/nixpkgs): 1925c603 -> 06cf0e1d `` |
> chore(flake/lovesegfault-vim-config): `92b2c8b4` -> `9ea2edc4`

- flake.lock
| Commit                                                                                                    | Message                                                 |
| --------------------------------------------------------------------------------------------------------- | ------------------------------------------------------- |
| [`386df64c`](https://github.com/nix-community/lanzaboote/commit/386df64c34fff7ac44a7cd42bbf42e93b6da2bf3) | `` chore(deps): update uefi to 0.31.0 ``                |
| [`97cf4280`](https://github.com/nix-community/lanzaboote/commit/97cf428067be91757e7d23edc3d5d02e1f5cf5c2) | `` stub: Drop duplicate calls to uefi::helpers::init `` |
> chore(flake/lanzaboote): `e7bd94e0` -> `e2365a1d`

- flake.lock
| Commit                                                                                               | Message                                                                          |
| ---------------------------------------------------------------------------------------------------- | -------------------------------------------------------------------------------- |
| [`4e30bc79`](https://github.com/nix-community/disko/commit/4e30bc7921b913b66cd22fa7f0f0371d6519907b) | `` zfs-with-vdevs: increase pool import timeout ``                               |
| [`fc3ba698`](https://github.com/nix-community/disko/commit/fc3ba6985ff1d636b2ed5fda6553ebc7f1ed0c95) | `` only set boot.initrd.preDeviceCommands if we boot with script-based stage1 `` |
| …
> chore(flake/disko): `b709e1cc` -> `037be889`

- flake.lock
| [`b9c99485`](https://github.com/nix-community/disko/commit/b9c99485aa0c6fb4021cbb4a7556b832ac6d8c65) | `` Fix and comment luks-encrypted btrfs raid example `` |
| [`ba436edc`](https://github.com/nix-community/disko/commit/ba436edc9dafb10733d00b1da5fcb0415c4d9f46) | `` Test luks-encrypted btrfs raid ``                    |
| [`c312692a`](https://github.com/nix-community/disko/commit/c312692abe6441fc8e9ac21f76a607e9f2cfb3f7) | `` Create luks-btrfs-raid.nix `` …
> chore(flake/disko): `037be889` -> `6c5ba9ec`

- flake.lock
| [`81103783`](https://github.com/lovesegfault/vim-config/commit/81103783792f4984e2012fb992df1f730da1e84f) | `` chore(flake/git-hooks): 85f7a717 -> 2f5ae3fc ``   |
| [`462fc9ee`](https://github.com/lovesegfault/vim-config/commit/462fc9eecc3761b37f498db77661ccf4c664906b) | `` chore(flake/flake-parts): bcef6817 -> 3d04084d `` |
> chore(flake/lovesegfault-vim-config): `9ea2edc4` -> `81103783`

- flake.lock
| [`da8f4924`](https://github.com/nix-community/disko/commit/da8f49246ce226b70feaf132d9b73a4cb7595f10) | `` docs: Fix /boot security hole warning in examples `` |
> chore(flake/disko): `6c5ba9ec` -> `da8f4924`

- flake.lock
| [`568727a8`](https://github.com/nix-community/disko/commit/568727a884ae7cd9f266bd19aea655def8cafd78) | `` build(deps): bump cachix/install-nix-action from V28 to 29 `` |
| [`fa0c181a`](https://github.com/nix-community/disko/commit/fa0c181a83ea8e8dc3eb5e632f2cd7a2bf5e51ea) | `` docs: Fix grammar in offline installer ``                     |
> chore(flake/disko): `da8f4924` -> `568727a8`

- flake.lock
| Commit                                                                                                   | Message                       |
| -------------------------------------------------------------------------------------------------------- | ----------------------------- |
| [`7de959be`](https://github.com/lovesegfault/vim-config/commit/7de959bec3c4ec85327d54e2a836141bbc63b9f8) | `` feat(lsp): enable ts-ls `` |
> chore(flake/lovesegfault-vim-config): `81103783` -> `7de959be`

- flake.lock
| Commit                                                                                               | Message                                                    |
| ---------------------------------------------------------------------------------------------------- | ---------------------------------------------------------- |
| [`a10a0cbe`](https://github.com/numtide/treefmt-nix/commit/a10a0cbe2196120aa90e4f86d459376e1d108d58) | `` wrapper: add treefmt-nix executable to output (#243) `` |
> chore(flake/treefmt-nix): `879b29ae` -> `a10a0cbe`

- flake.lock
| Commit                                                                                               | Message                                  |
| ---------------------------------------------------------------------------------------------------- | ---------------------------------------- |
| [`1b17d96a`](https://github.com/nix-community/disko/commit/1b17d96ac5a2f7e8b3e3608b3484595b3df4940c) | `` Grammar update on disko-install.md `` |
> chore(flake/disko): `568727a8` -> `57440000`

- flake.lock
| Commit                                                                                               | Message                                                      |
| ---------------------------------------------------------------------------------------------------- | ------------------------------------------------------------ |
| [`4446c7a6`](https://github.com/numtide/treefmt-nix/commit/4446c7a6fc0775df028c5a3f6727945ba8400e64) | `` zig: include .zon (#244) ``                               |
| [`861c66dd`](https://github.com/numtide/treefmt-nix/commit/861c66ddc5f45e39a831222adeda3c0325c4e1b1) | `` buildifier: include all .bazel files by default (#245) `` |
> chore(flake/treefmt-nix): `a10a0cbe` -> `4446c7a6`

- flake.lock
| [`af31a493`](https://github.com/lovesegfault/vim-config/commit/af31a493ce3062619ab9b2c25d988f572fba0e8e) | `` chore(flake/treefmt-nix): 879b29ae -> 4446c7a6 `` |
> chore(flake/lovesegfault-vim-config): `e3fd2b06` -> `af31a493`

- flake.lock
| [`30e04f3d`](https://github.com/nix-community/home-manager/commit/30e04f3d477256de3eb6a7cff608e220087537d4) | `` pass-secret-service: add GNUPGHOME to service env vars `` |
> chore(flake/home-manager): `437ec620` -> `30e04f3d`

- flake.lock
| [`b7ca02c7`](https://github.com/NixOS/nixos-hardware/commit/b7ca02c7565fbf6d27ff20dd6dbd49c5b82eef28) | `` add dell xps 9315 ``                                        |
| [`a53ca667`](https://github.com/NixOS/nixos-hardware/commit/a53ca667df44b1e02659f73f720bb20fc4b202bd) | `` lenovo/thinkpad/t480s: add hardware acceleration support `` |
| [`7200fdc7`](https://github.com/NixOS/nixos-hardware/commit/7200fdc70facade9676f8548de37ab23f71a4687) | `` …
> chore(flake/nixos-hardware): `11c43c83` -> `b7ca02c7`

- flake.lock
| [`48ebb577`](https://github.com/nix-community/disko/commit/48ebb577855fb2398653f033b3b2208a9249203d) | `` docs/interactive-vms: simplify usage to just one nix run ``    |
| [`28c5af1e`](https://github.com/nix-community/disko/commit/28c5af1e16f4f34ad1a2c0356f20f5742857789d) | `` interactive-vm: allow to override virtualisation.memorySize `` |
> chore(flake/disko): `57440000` -> `48ebb577`

- flake.lock
| [`6fc87452`](https://github.com/lovesegfault/vim-config/commit/6fc8745297a8f2514ab6123f21cd624ed1d82322) | `` chore(flake/nixpkgs): 06cf0e1d -> bc947f54 ``   |
| [`2088ae46`](https://github.com/lovesegfault/vim-config/commit/2088ae46e70c87e9980fb2a22fb9288b8b97d702) | `` chore(flake/git-hooks): 5f58871c -> 1211305a `` |
> chore(flake/lovesegfault-vim-config): `af31a493` -> `6fc87452`

- flake.lock
| Commit                                                                                                    | Message                                              |
| --------------------------------------------------------------------------------------------------------- | ---------------------------------------------------- |
| [`98cf6500`](https://github.com/nix-community/lanzaboote/commit/98cf6500402b25b3160b39ebc763fffcf26eade1) | `` linux-bootloader: simplify get_loader_features `` |
> chore(flake/lanzaboote): `e2365a1d` -> `0bc127c6`

- flake.lock
| [`4600f863`](https://github.com/lovesegfault/vim-config/commit/4600f863795b8d45c5bde614541567586555d5c7) | `` chore(flake/nixvim): 0ca98d02 -> 33d030d2 `` |
> chore(flake/lovesegfault-vim-config): `6fc87452` -> `4600f863`

- flake.lock
| [`ecfcd787`](https://github.com/NixOS/nixos-hardware/commit/ecfcd787f373f43307d764762e139a7cdeb9c22b) | `` build(deps): bump cachix/install-nix-action from 29 to 30 `` |
> chore(flake/nixos-hardware): `b7ca02c7` -> `ecfcd787`

- flake.lock
| [`bc623830`](https://github.com/nix-community/home-manager/commit/bc623830e619cef86a2d3750625ffe4e24ea7e64) | `` ci: bump cachix/install-nix-action from 27 to 30 `` |
> chore(flake/home-manager): `509dbf8d` -> `bc623830`

- flake.lock
| [`fcf5e608`](https://github.com/nix-community/home-manager/commit/fcf5e608ac65f64463bc0ccc5ea86f2170f20689) | `` kitty: allow float values in settings (#5925) `` |
> chore(flake/home-manager): `bc623830` -> `fcf5e608`

- flake.lock
| [`3ac39b2a`](https://github.com/nix-community/home-manager/commit/3ac39b2a8b7cbfc0f96628d8a84867c885bc988b) | `` zathura: Fix the type for config options (#5934) `` |
> chore(flake/home-manager): `fcf5e608` -> `3ac39b2a`

- flake.lock
| [`d39ee334`](https://github.com/nix-community/disko/commit/d39ee334984fcdae6244f5a8e6ab857479cbaefe) | `` build(deps): bump cachix/install-nix-action from 29 to 30 `` |
> chore(flake/disko): `48ebb577` -> `d39ee334`

- flake.lock
| [`03863036`](https://github.com/nix-community/home-manager/commit/038630363e7de57c36c417fd2f5d7c14773403e4) | `` xdg-mime type package options (#5920) ``        |
| [`271c83e2`](https://github.com/nix-community/home-manager/commit/271c83e21ea81f39a42ad128384e0e6804956a88) | `` firefox: organize tests by submodule (#5698) `` |
> chore(flake/home-manager): `3ac39b2a` -> `03863036`

- flake.lock
| [`afd8ff57`](https://github.com/lovesegfault/vim-config/commit/afd8ff57f9745ac15082f9df1281609323f720c7) | `` chore(flake/nixvim): 33d030d2 -> abc7f450 `` |
> chore(flake/lovesegfault-vim-config): `4600f863` -> `afd8ff57`

- flake.lock
| [`c9fd4820`](https://github.com/LnL7/nix-darwin/commit/c9fd4820d5e33422d2a9311898e098ba492dbd34) | `` programs/bash: move to completion.* `` |
> chore(flake/darwin): `8c8388ad` -> `48b50b3b`

- flake.lock
| [`e2d8d42e`](https://github.com/lovesegfault/vim-config/commit/e2d8d42ed27712118dd4f150a5aebc997b811422) | `` chore(flake/nixpkgs): bc947f54 -> c31898ad `` |
> chore(flake/lovesegfault-vim-config): `afd8ff57` -> `e2d8d42e`

- flake.lock
| [`9cbe04cc`](https://github.com/lovesegfault/vim-config/commit/9cbe04cc7d549cf4359887dfc75d448c700150d7) | `` fix(lsp): chase upstream server renames ``   |
| [`1f68101a`](https://github.com/lovesegfault/vim-config/commit/1f68101acae07025de55efa75f00fc6a40b61c6b) | `` chore(flake/nixvim): abc7f450 -> eda14029 `` |
> chore(flake/lovesegfault-vim-config): `e2d8d42e` -> `9cbe04cc`

- flake.lock
| [`d4aae470`](https://github.com/lovesegfault/vim-config/commit/d4aae470a6a90b720f9d931e8eaea0969f13a180) | `` chore(flake/nixvim): eda14029 -> 61ec3976 `` |
> chore(flake/lovesegfault-vim-config): `9cbe04cc` -> `d4aae470`

- flake.lock
| [`d47d3325`](https://github.com/nix-community/home-manager/commit/d47d33254fbf4fdbdee9f1f14095f689662e479d) | `` home-manager-manual: expose options.json `` |
| [`d3ee25c0`](https://github.com/nix-community/home-manager/commit/d3ee25c07848725e924a74a4813de2ad0f5d0878) | `` Translate using Weblate (Hindi) ``          |
> chore(flake/home-manager): `03863036` -> `d47d3325`

- flake.lock
| [`8bb5d53c`](https://github.com/nix-community/home-manager/commit/8bb5d53c5847d9a9b2ad1bda49f9aa9df0de282a) | `` docs: add XDG_*_HOME mentions to xdg.*Home options `` |
> chore(flake/home-manager): `d47d3325` -> `8bb5d53c`

- flake.lock
| [`342a1d68`](https://github.com/nix-community/home-manager/commit/342a1d682386d3a1d74f9555cb327f2f311dda6e) | `` flake.lock: Update ``    |
| [`03f8e0b3`](https://github.com/nix-community/home-manager/commit/03f8e0b3b3ca4f49d11bf0264dbff465d6ae9aae) | `` snixembed: add module `` |
> chore(flake/home-manager): `8bb5d53c` -> `342a1d68`

- flake.lock
| [`83af197c`](https://github.com/lovesegfault/vim-config/commit/83af197c783cc501e9b8c24b1409f339aad501aa) | `` chore(flake/git-hooks): 1211305a -> 4ebefcac `` |
| [`baef3812`](https://github.com/lovesegfault/vim-config/commit/baef38121c88db9ecc1743072dd097843edeeefc) | `` chore(flake/nixvim): 61ec3976 -> af650ba9 ``    |
> chore(flake/lovesegfault-vim-config): `d4aae470` -> `83af197c`

- flake.lock
| [`f00157ca`](https://github.com/lovesegfault/vim-config/commit/f00157cad708a6d583c8d69e3119d96329abff7c) | `` chore(flake/nixpkgs): c31898ad -> 5633bcff `` |
> chore(flake/lovesegfault-vim-config): `83af197c` -> `f00157ca`

- flake.lock
| Commit                                                                                                    | Message                                                           |
| --------------------------------------------------------------------------------------------------------- | ----------------------------------------------------------------- |
| [`7a367fa6`](https://github.com/nix-community/lanzaboote/commit/7a367fa69893eb9a3c6586663bf20ab2f6103a9e) | `` module: replace hard-coded executable paths with lib.getExe `` |
> chore(flake/lanzaboote): `0bc127c6` -> `3326a0b3`

- flake.lock
| [`4c298a03`](https://github.com/nix-community/disko/commit/4c298a031a0631c46b53f82d345763f14eb18f82) | `` Fix issue when config path contains spaces ``   |
| [`efe75285`](https://github.com/nix-community/disko/commit/efe752857867a85c5706bf0a0e50852d4c06bcee) | `` disko cli: remove requirement for leading ./ `` |
> chore(flake/disko): `d39ee334` -> `4c298a03`

- flake.lock
| [`6af4e02b`](https://github.com/nix-community/disko/commit/6af4e02b9cf2a4126af542c9e299f13228cfe2e0) | `` Fix mergify deprecation warning `` |
> chore(flake/disko): `4c298a03` -> `6af4e02b`

- flake.lock
| [`58283095`](https://github.com/nix-community/home-manager/commit/582830954264080aae93f751c3cdc58df600d2d1) | `` vifm: add module `` |
> chore(flake/home-manager): `342a1d68` -> `58283095`

- flake.lock
| [`6a3d0eb6`](https://github.com/cachix/git-hooks.nix/commit/6a3d0eb6b64920b33683111bce68d1f4a9ef51dd) | `` statix: skip adding `--ignore` if empty ``   |
| [`1fe5afc7`](https://github.com/cachix/git-hooks.nix/commit/1fe5afc78489820f5586a9c90f91358a169604a7) | `` statix: fix broken list option `--ignore` `` |
| [`6ce0397f`](https://github.com/cachix/git-hooks.nix/commit/6ce0397f4bd8af17e83639f7c561a64799fd81ae) | `` feat(rustfmt): add settings ``               |
> chore(flake/git-hooks): `4ebefcac` -> `06bb5971`

- flake.lock
| [`65ae9c14`](https://github.com/nix-community/home-manager/commit/65ae9c147349829d3df0222151f53f79821c5134) | `` git: add module for `git maintenance` (#5772) `` |
> chore(flake/home-manager): `58283095` -> `65ae9c14`

- flake.lock
| [`c7ef3964`](https://github.com/nix-community/disko/commit/c7ef3964b6befa877e76316ae88f3ef251cae573) | `` docs: add "latest" tag to flake references `` |
| [`aee84b5f`](https://github.com/nix-community/disko/commit/aee84b5fb390d713a98efed2b56bd7d6f873fb48) | `` disko cli: add --version command ``           |
> chore(flake/disko): `6af4e02b` -> `c7ef3964`

- flake.lock
| Commit                                                                                               | Message                           |
| ---------------------------------------------------------------------------------------------------- | --------------------------------- |
| [`9788e5d4`](https://github.com/nix-community/disko/commit/9788e5d45805aee2c3bece9c17d6715668c5ed95) | `` release: Fix release script `` |
> chore(flake/disko): `c7ef3964` -> `9788e5d4`

- flake.lock
| [`a3619332`](https://github.com/nix-community/disko/commit/a3619332369e1d254c68be5f019b3a8632e79bbc) | `` release: reset released flag `` |
| [`ff0a4717`](https://github.com/nix-community/disko/commit/ff0a471763faaaca1859fd6de80f44fa0fce91a6) | `` release: v1.8.2 ``              |
> chore(flake/disko): `9788e5d4` -> `a3619332`

- flake.lock
| [`bdbdb725`](https://github.com/nix-community/disko/commit/bdbdb725d632863bdedb80baabf21327614dd237) | `` fix: wrong attr path ``            |
| [`8c1668ed`](https://github.com/nix-community/disko/commit/8c1668edeccc0680d044453fd9612dac673b67b0) | `` release: fix wrong push command `` |
> chore(flake/disko): `a3619332` -> `bdbdb725`

- flake.lock
| [`2b13611e`](https://github.com/nix-community/home-manager/commit/2b13611eaed8326789f76f70d21d06fbb14e3e47) | `` floorp: add module `` |
> chore(flake/home-manager): `65ae9c14` -> `2b13611e`

- flake.lock
| [`ca0662ed`](https://github.com/NixOS/nixos-hardware/commit/ca0662edb06f07d7b57c1b92037a112b4fc2c82f) | `` fix ordering ``            |
| [`664b7847`](https://github.com/NixOS/nixos-hardware/commit/664b784722aee2fb139bfe6542406f16c0c4c457) | `` add tuxedo aura 15 gen1 `` |
> chore(flake/nixos-hardware): `ecfcd787` -> `ca0662ed`

- flake.lock
| [`a8dd1b21`](https://github.com/NixOS/nixos-hardware/commit/a8dd1b21995964b115b1e3ec639dd6ce24ab9806) | `` add dell inspiron 7460 (#1177) `` |
| [`6f71da56`](https://github.com/NixOS/nixos-hardware/commit/6f71da566f481d1593d447c31556759732299d13) | `` apple/t2: add tiny-dfr option ``  |
> chore(flake/nixos-hardware): `ca0662ed` -> `a8dd1b21`

- flake.lock
| [`ed832370`](https://github.com/nix-community/disko/commit/ed8323704aefc65755f43527cb1dff6124748b69) | `` fixed logo suffix in INDEX.md `` |
> chore(flake/disko): `bdbdb725` -> `b6215392`

- flake.lock
| Commit                                                                                                    | Message                                                            |
| --------------------------------------------------------------------------------------------------------- | ------------------------------------------------------------------ |
| [`45609e42`](https://github.com/nix-community/lanzaboote/commit/45609e422bbedf3d69dad9e6fff4f0e5475aa529) | `` uefi: Drop RuntimeServices param from ensure_efi_variable ``    |
| [`1388d533`](https://github.com/nix-community/lanzaboote/commit/1388d533281fe6df247b9220127e2f24b61e72f4) | `` stub: Drop RuntimeServices param from get_secure_boot_status `` |
> chore(flake/lanzaboote): `3326a0b3` -> `6634ab61`

- flake.lock
| [`9a3e5efd`](https://github.com/lovesegfault/vim-config/commit/9a3e5efdab1a94976700ef49bae53c394ecbb36c) | `` chore(flake/nixvim): 2e1b3b7d -> 619e2436 ``    |
| [`a35a030f`](https://github.com/lovesegfault/vim-config/commit/a35a030f47e14727b968679bfa686608977431dd) | `` chore(flake/git-hooks): eb74e0be -> ff68f917 `` |
> chore(flake/lovesegfault-vim-config): `edc4ba82` -> `9a3e5efd`

- flake.lock
| Commit                                                                                           | Message                               |
| ------------------------------------------------------------------------------------------------ | ------------------------------------- |
| [`d32e6de0`](https://github.com/LnL7/nix-darwin/commit/d32e6de094e87ba8eeef0be8c5696f7b14365af2) | `` defaults: don't output Dock PID `` |
> chore(flake/darwin): `fd0e3ed3` -> `ccf8cc56`

- flake.lock
| [`3b2e19fe`](https://github.com/nix-community/disko/commit/3b2e19fe7c667a4fb2da3d6bb5ae6ee3e3552f74) | `` disko cli: fix misleading error message `` |
> chore(flake/disko): `b6215392` -> `3b2e19fe`

- flake.lock
| Commit                                                                                           | Message                          |
| ------------------------------------------------------------------------------------------------ | -------------------------------- |
| [`6347a9dc`](https://github.com/LnL7/nix-darwin/commit/6347a9dcd1e43b9a5d43b837cfa4ca0073c2eb0e) | `` skhd: add `skhd` to `PATH` `` |
> chore(flake/darwin): `ccf8cc56` -> `a60ac02f`

- flake.lock
| Commit                                                                                               | Message                                                    |
| ---------------------------------------------------------------------------------------------------- | ---------------------------------------------------------- |
| [`3b778f10`](https://github.com/nix-community/disko/commit/3b778f10eb275573da9f5c8a7a49e774200b87e5) | `` docs: add docs on how to use imageName in disk type. `` |
| [`ef408f7f`](https://github.com/nix-community/disko/commit/ef408f7f9ada76d63de2b2260d613b2c3a07181c) | `` options: add imageName option to disk type. ``          |
| [`9938afb4`](https://github.com/nix-community/disko/commit/9938afb4350e214d3e720100688ec9979ba702e3) | `` options: make extraPostVM …
> chore(flake/disko): `3b2e19fe` -> `3b778f10`

- flake.lock
| Commit                                                                                                    | Message                                                                          |
| --------------------------------------------------------------------------------------------------------- | -------------------------------------------------------------------------------- |
| [`da466293`](https://github.com/nix-community/lanzaboote/commit/da466293dcc80abc666ddf1bfc30d2e26068d238) | `` uefi: Use system_table_boot when calling convert_device_path_to_text ``       |
| [`3f78a16e`](https://github.com/nix-community/lanzaboote/commit/3f78a16e19189ff096a2c008533fc3effe86bdf4) | `` linux-bootloader: Drop most uses of BootServices from export_efi_variables `` |
| …
> chore(flake/lanzaboote): `a71d589c` -> `97ad865c`

- flake.lock
| Commit                                                                                               | Message                                        |
| ---------------------------------------------------------------------------------------------------- | ---------------------------------------------- |
| [`9ab6ae4e`](https://github.com/nix-community/disko/commit/9ab6ae4e632016caac1c7e82e15b12b8c672ed76) | `` disko-install: make output deterministic `` |
> chore(flake/disko): `3b778f10` -> `9ab6ae4e`

- flake.lock
| Commit                                                                                                    | Message                                             |
| --------------------------------------------------------------------------------------------------------- | --------------------------------------------------- |
| [`387c699e`](https://github.com/nix-community/lanzaboote/commit/387c699e87d102ca42bfb5e1cf2142b14c963970) | `` uefi: fix typos ``                               |
| [`8d98fd8b`](https://github.com/nix-community/lanzaboote/commit/8d98fd8be08d7bff045e0fa1d226c8fa0882ba65) | `` flake: drop unused nixpkgs override for crane `` |
| [`739cb589`](https://github.com/nix-community/lanzaboote/commit/739cb589e461b7baabb1dfe16b5cad51fdec615f) | `` chore(deps): lock file …
> chore(flake/lanzaboote): `97ad865c` -> `7ada9263`

- flake.lock
| Commit                                                                                                    | Message                                                      |
| --------------------------------------------------------------------------------------------------------- | ------------------------------------------------------------ |
| [`84ae860b`](https://github.com/nix-community/lanzaboote/commit/84ae860be74b5e2b2843dffac06848bdf0657334) | `` stub: Drop handle and table params from main ``           |
| [`998d1270`](https://github.com/nix-community/lanzaboote/commit/998d1270bfe7a93b6ca322cf289c62785cfecbf4) | `` stub: Drop SystemTable param from boot_linux ``           |
| [`ed4cd445`](https://github.com/nix-community/lanzaboote/commit/ed4cd445135a1d6eb57a579d171e8c3d17f0e153) …
> chore(flake/lanzaboote): `7ada9263` -> `bd01eac8`

- flake.lock
| [`b1eff05d`](https://github.com/lovesegfault/vim-config/commit/b1eff05d91deea3ea79738a089dfaa200442eeb0) | `` chore(flake/nixpkgs): 5633bcff -> a3c0b3b2 `` |
| [`e29ac01e`](https://github.com/lovesegfault/vim-config/commit/e29ac01e1f2aa138a67ea46f7b00cab7e2037427) | `` chore(flake/nixvim): 619e2436 -> 429f2e8d ``  |
> chore(flake/lovesegfault-vim-config): `9a3e5efd` -> `b1eff05d`

- flake.lock
| Commit                                                                                                    | Message                                                |
| --------------------------------------------------------------------------------------------------------- | ------------------------------------------------------ |
| [`8b848c3b`](https://github.com/nix-community/lanzaboote/commit/8b848c3b4f2a099fb6871540b12be5462865a2cf) | `` fix(tool): better error if public key is missing `` |
| [`6fdd9ad7`](https://github.com/nix-community/lanzaboote/commit/6fdd9ad750f233ebe2e7acf5833b30b70018d028) | `` stub: fix compilation after uefi crate update ``    |
| [`295ce01b`](https://github.com/nix-community/lanzaboote/commit/295ce01b28c43b5bbde32345c9a210a8541b1cfa) | `` fix(deps): update …
> chore(flake/lanzaboote): `bd01eac8` -> `2fa1368f`

- flake.lock
| [`ee6d65f0`](https://github.com/nix-community/impermanence/commit/ee6d65f0b2060c92cf6658f89553d75629c02552) | `` add: default nixos module ``                     |
| [`f4aab16c`](https://github.com/nix-community/impermanence/commit/f4aab16cd83c5a354840c215d69e57b61274c1c5) | `` mount-file: allow file to exist if it's empty `` |
> chore(flake/impermanence): `dff77f78` -> `e3374575`

- flake.lock
| [`c8760cee`](https://github.com/nix-community/disko/commit/c8760cee70cf166ad6bcee0bd9f0bba934a3a651) | `` cli: stop using system dependencies in destroy step `` |
> chore(flake/disko): `9ab6ae4e` -> `c8760cee`

- flake.lock
- hosts/riemann/default.nix
- users/bemeurer/core/default.nix
| [`a3c0b3b2`](https://github.com/NixOS/nixpkgs/commit/a3c0b3b21515f74fd2665903d4ce6bc4dc81c77c) | `` Revert "nixos/tests/networking: test nameservers via DHCP" ``             |
| [`0932441e`](https://github.com/NixOS/nixpkgs/commit/0932441e91d13ea710cc60439fb006828d40350d) | `` miniaudicle: 1.5.2.0 -> 1.5.3.0 ``                                        |
| [`310061a7`](https://github.com/NixOS/nixpkgs/commit/310061a7f9d3bf03c4bb762dc5dca99f7 …
> chore(flake/nixpkgs): `5633bcff` -> `a3c0b3b2`

- flake.lock
| [`9c1a1c7d`](https://github.com/nix-community/home-manager/commit/9c1a1c7df49a9b28539ccb509b36d0b81e41391c) | `` activitywatch: reduce test closure `` |
> chore(flake/home-manager): `78a7a070` -> `9c1a1c7d`

- flake.lock
| Commit                                                                                                      | Message                      |
| ----------------------------------------------------------------------------------------------------------- | ---------------------------- |
| [`e78cbb20`](https://github.com/nix-community/home-manager/commit/e78cbb20276f09c1802e62d2f77fc93ec32da268) | `` zed-editor: add module `` |
> chore(flake/home-manager): `9c1a1c7d` -> `e78cbb20`

- flake.lock
| [`4f49a3d9`](https://github.com/lovesegfault/vim-config/commit/4f49a3d90b0f80150d2c6c541bea2e62d4387cdc) | `` chore(flake/nixvim): 717e7060 -> 3c7b6ae5 `` |
> chore(flake/lovesegfault-vim-config): `681c87d2` -> `4f49a3d9`

- flake.lock
| [`d986489c`](https://github.com/numtide/treefmt-nix/commit/d986489c1c757f6921a48c1439f19bfb9b8ecab5) | `` nufmt: init (#250) `` |
> chore(flake/treefmt-nix): `5307ba60` -> `d986489c`

- flake.lock
| [`346973b3`](https://github.com/nix-community/home-manager/commit/346973b338365240090eded0de62f7edce4ce3d1) | `` tests/firefox: add shared path test ``                 |
| [`2ffb68e2`](https://github.com/nix-community/home-manager/commit/2ffb68e20981d78bfcc73b2271f2dfa003df182c) | `` thunderbird: conditional search file ``                |
| [`d4a3186d`](https://github.com/nix-community/home-manager/commit/d4a3186de0eeb37d1e43ed65791b0af677e440a1) | …
> chore(flake/home-manager): `e78cbb20` -> `346973b3`

- flake.lock
| [`09a0c0c0`](https://github.com/nix-community/home-manager/commit/09a0c0c02953318bf94425738c7061ffdc4cba75) | `` cmus: add module `` |
> chore(flake/home-manager): `346973b3` -> `09a0c0c0`

- flake.lock
| [`a6a3179d`](https://github.com/nix-community/disko/commit/a6a3179ddf396dfc28a078e2f169354d0c137125) | `` cli: stop using system dependencies in destroy step `` |
> chore(flake/disko): `d7d57edb` -> `a6a3179d`

- flake.lock
| [`6a20b8bd`](https://github.com/lovesegfault/vim-config/commit/6a20b8bde90f245633b9b201b1e55c37255fa2ec) | `` chore(flake/nixpkgs): a3c0b3b2 -> 5785b6bb ``     |
| [`68ffb4bd`](https://github.com/lovesegfault/vim-config/commit/68ffb4bd4fdb178c9ac01291ed75024315151958) | `` chore(flake/nixvim): 3c7b6ae5 -> 036e1166 ``      |
| [`878ad462`](https://github.com/lovesegfault/vim-config/commit/878ad4620d556730ddf5436efb7a017e2a53c517) | `` chore(flake/treefmt-nix): …
> chore(flake/lovesegfault-vim-config): `4f49a3d9` -> `6a20b8bd`

- flake.lock
| [`802b3cb2`](https://github.com/nix-community/home-manager/commit/802b3cb2d45ad66619ea8ad19b280baa460556d2) | `` espanso: use `launcher` command on Linux `` |
> chore(flake/home-manager): `09a0c0c0` -> `802b3cb2`

- flake.lock
| [`122f7054`](https://github.com/nix-community/home-manager/commit/122f70545b29ccb922e655b08acfe05bfb44ec68) | `` firefox: change container.json version to 5 `` |
> chore(flake/home-manager): `802b3cb2` -> `122f7054`

- flake.lock
| Commit                                                                                                | Message                                                                           |
| ----------------------------------------------------------------------------------------------------- | --------------------------------------------------------------------------------- |
| [`f682feda`](https://github.com/NixOS/nixos-hardware/commit/f682fedae05303287c07c859423203c578db4213) | `` gpd-win-max-2-2023/bmi260: 0.0.2 -> 1.0.0 ``                                   |
| [`99918dfb`](https://github.com/NixOS/nixos-hardware/commit/99918dfbd7a86e18071ddc72e81a2f3ffe5bcea5) | `` dell-precision-5490: make force_probe conditional ``                           |
| …
> chore(flake/nixos-hardware): `a8dd1b21` -> `f682feda`

- flake.lock
| Commit                                                                                                | Message                      |
| ----------------------------------------------------------------------------------------------------- | ---------------------------- |
| [`38279034`](https://github.com/NixOS/nixos-hardware/commit/38279034170b1e2929b2be33bdaedbf14a57bfeb) | `` Add Asus Zenbook ux535 `` |
> chore(flake/nixos-hardware): `f682feda` -> `38279034`

- flake.lock
| [`a6a3a09e`](https://github.com/lovesegfault/vim-config/commit/a6a3a09e1e01020bd257df9da355996e31f63d9e) | `` chore(flake/nixpkgs): 5785b6bb -> 4c2fcb09 `` |
| [`1c7e864a`](https://github.com/lovesegfault/vim-config/commit/1c7e864a570d5bfe857aca8984726aded4b22220) | `` chore(flake/nixvim): 036e1166 -> c4ad4d0b ``  |
> chore(flake/lovesegfault-vim-config): `6a20b8bd` -> `a6a3a09e`

- flake.lock
| [`8f38d8a4`](https://github.com/NixOS/nixos-hardware/commit/8f38d8a4754cf673c2609c4ed399630db87e678b) | `` dell/xps/15-9520: use alder-lake gpu profile ``        |
| [`be33295d`](https://github.com/NixOS/nixos-hardware/commit/be33295d69d8864d58df99e5c5602ebff5bf5dd3) | `` gpu/intel/tiger-lake: simplify conditionals ``         |
| [`86a33c3e`](https://github.com/NixOS/nixos-hardware/commit/86a33c3e32822c62127c70766d56731dadfbed5c) | `` common/gpu/intel: update …
> chore(flake/nixos-hardware): `38279034` -> `8f38d8a4`

- flake.lock
| [`9da64c8f`](https://github.com/NixOS/nixos-hardware/commit/9da64c8fd97274d6cd2fda6bc161abc229aeb6c9) | `` dell/xps/15-9520: add alder-lake gpu profile ``          |
| [`3854ace1`](https://github.com/NixOS/nixos-hardware/commit/3854ace106bd53c1780bc05bcb0e63bade2cd2e5) | `` Revert "dell/xps/15-9520: use alder-lake gpu profile" `` |
> chore(flake/nixos-hardware): `8f38d8a4` -> `9da64c8f`

- flake.lock
| [`9fcf30fc`](https://github.com/NixOS/nixos-hardware/commit/9fcf30fccf8435f6390efec4a4d38e69c2268a36) | `` Make starfive-visionfive-2 merge with sd-image module `` |
> chore(flake/nixos-hardware): `9da64c8f` -> `9fcf30fc`

- flake.lock
| [`2f1e0073`](https://github.com/lovesegfault/vim-config/commit/2f1e0073e89c8fc5b6ca268271e4c6b31f493d0f) | `` chore(flake/nixvim): c4ad4d0b -> 47b563d4 `` |
> chore(flake/lovesegfault-vim-config): `a6a3a09e` -> `2f1e0073`

- flake.lock
| [`7495e877`](https://github.com/NixOS/nixos-hardware/commit/7495e877539919988c9ebe4ae0f47343982da0e5) | `` treewide: Switch from gpu/intel to cpu/intel where applicable `` |
| [`c058019c`](https://github.com/NixOS/nixos-hardware/commit/c058019ce1b72c7d450f5e2b3f0921bd205e9f79) | `` common/cpu/intel: add architecture-specific modules ``           |
> chore(flake/nixos-hardware): `9fcf30fc` -> `7495e877`

- flake.lock
| [`cc2d3c0e`](https://github.com/NixOS/nixos-hardware/commit/cc2d3c0e060f981905d52337340ee6ec8b8eb037) | `` flake.nix: don't expose alder-lake module ``                        |
| [`77ec51c2`](https://github.com/NixOS/nixos-hardware/commit/77ec51c21c8bc6974f93ae39c102d9d1c6b7859f) | `` common-gpu-intel-kaby-lake: enable HuC firmware loading ``          |
| [`796768cb`](https://github.com/NixOS/nixos-hardware/commit/796768cbc486e24f9154b3 …
> chore(flake/nixos-hardware): `7495e877` -> `cc2d3c0e`

- flake.lock
| [`1bd74d16`](https://github.com/lovesegfault/vim-config/commit/1bd74d16ebd630f4c6eb05e97e894b4299c933a6) | `` chore(flake/nixvim): 47b563d4 -> 0562e519 `` |
> chore(flake/lovesegfault-vim-config): `2f1e0073` -> `1bd74d16`

- flake.lock
| Commit                                                                                               | Message                                                                           |
| ---------------------------------------------------------------------------------------------------- | --------------------------------------------------------------------------------- |
| [`4be2aadf`](https://github.com/nix-community/disko/commit/4be2aadf13b67ffbb993deb73adff77c46b728fc) | `` lib: use lib.escapeShellArg for concatenated paths ``                          |
| [`ca47da60`](https://github.com/nix-community/disko/commit/ca47da60e569c7d355b5ccbaebb2a407231bacd8) | `` disko: fix improper handling of whitespace ``                                  |
| …
> chore(flake/disko): `a6a3179d` -> `4be2aadf`

- flake.lock
| Commit                                                                                           | Message                                            |
| ------------------------------------------------------------------------------------------------ | -------------------------------------------------- |
| [`cbb190ec`](https://github.com/LnL7/nix-darwin/commit/cbb190eccbc01f9b492fab11185a9cd729562ec6) | `` ci: update Nix to match versions in nixpkgs ``  |
| [`8724129d`](https://github.com/LnL7/nix-darwin/commit/8724129dc862432dc5e5c548f1af48f38c4368c4) | `` ci: don't run tests twice for PRs from forks `` |
> chore(flake/darwin): `a001f44c` -> `64d9d1ae`

- flake.lock
| [`aac86347`](https://github.com/numtide/treefmt-nix/commit/aac86347fb5063960eccb19493e0cadcdb4205ca) | `` Add rubocop (#251) `` |
> chore(flake/treefmt-nix): `d986489c` -> `aac86347`

- flake.lock
| [`5d92f60f`](https://github.com/lovesegfault/vim-config/commit/5d92f60fb7dabbcce05541e8234ea22e7f4345b5) | `` chore(flake/nixpkgs): 4c2fcb09 -> 1997e4aa ``     |
| [`e8fca7a2`](https://github.com/lovesegfault/vim-config/commit/e8fca7a247cb2f84499b5622af2301bf7a879f35) | `` chore(flake/nixvim): 0562e519 -> b076f006 ``      |
| [`a8629422`](https://github.com/lovesegfault/vim-config/commit/a86294226e1de01aba94325c1030150695ee5ead) | `` chore(flake/treefmt-nix): …
> chore(flake/lovesegfault-vim-config): `1bd74d16` -> `5d92f60f`

- flake.lock
| Commit                                                                                                | Message                                                       |
| ----------------------------------------------------------------------------------------------------- | ------------------------------------------------------------- |
| [`64d900ab`](https://github.com/NixOS/nixos-hardware/commit/64d900abe40057393148bc0283d35c2254dd4f57) | `` Unload brcmfmac_wcc (if loaded) before brcmfmac (#1200) `` |
> chore(flake/nixos-hardware): `22e8de27` -> `64d900ab`

- flake.lock
| Commit                                                                                               | Message                                    |
| ---------------------------------------------------------------------------------------------------- | ------------------------------------------ |
| [`09a77670`](https://github.com/nix-community/disko/commit/09a776702b004fdf9c41a024e1299d575ee18a7d) | `` fix: avoid calling splitString ""... `` |
> chore(flake/disko): `4be2aadf` -> `09a77670`

- flake.lock
| [`43d1e9c2`](https://github.com/lovesegfault/vim-config/commit/43d1e9c20351f6fc738fc36accb86da57b75686d) | `` chore(flake/nixvim): b076f006 -> 029eafd7 `` |
> chore(flake/lovesegfault-vim-config): `5d92f60f` -> `43d1e9c2`

- flake.lock
| Commit                                                                                                | Message                                                                 |
| ----------------------------------------------------------------------------------------------------- | ----------------------------------------------------------------------- |
| [`e8a2f6d5`](https://github.com/NixOS/nixos-hardware/commit/e8a2f6d5513fe7b7d15701b2d05404ffdc3b6dda) | `` common/gpu/intel: Disable intel-ocl due to web.archive.org outage `` |
> chore(flake/nixos-hardware): `64d900ab` -> `e8a2f6d5`

- flake.lock
| Commit                                                                                           | Message                                                                       |
| ------------------------------------------------------------------------------------------------ | ----------------------------------------------------------------------------- |
| [`b089e7e7`](https://github.com/LnL7/nix-darwin/commit/b089e7e7266403ddda9f96bfd8c5adf9a0f0f6b5) | `` users: switch back to using `dscl` for deleting users ``                   |
| [`b7027502`](https://github.com/LnL7/nix-darwin/commit/b702750226a86abb029440641bfa994ff650cf99) | `` users: ensure Full Disk Access is granted before trying to create users `` |
| [`2be05de0`](https://github.com/LnL7/nix-darwin/commit/2be05de06ed8e634c83 …
> chore(flake/darwin): `5f05c2c3` -> `04193f18`

- flake.lock
| [`e96e908b`](https://github.com/lovesegfault/vim-config/commit/e96e908bf5eff4600a69c75d6551ae9a68e67d5c) | `` chore(flake/nixpkgs): 1997e4aa -> 2768c7d0 `` |
> chore(flake/lovesegfault-vim-config): `fdfbb222` -> `e96e908b`

- flake.lock
| Commit                                                                                           | Message                                                              |
| ------------------------------------------------------------------------------------------------ | -------------------------------------------------------------------- |
| [`f7372597`](https://github.com/LnL7/nix-darwin/commit/f737259769ef4722ed956bcaaab67509b96c23cc) | `` power,sleep: Add options to control restart and sleep behavior `` |
| [`5907cbbb`](https://github.com/LnL7/nix-darwin/commit/5907cbbb31d9de387349efb825864a9ee598e6ba) | `` networking: Add wakeOnLan option ``                               |
> chore(flake/darwin): `04193f18` -> `8c675759`

- flake.lock
| Commit                                                                                           | Message                                                           |
| ------------------------------------------------------------------------------------------------ | ----------------------------------------------------------------- |
| [`c98bb238`](https://github.com/LnL7/nix-darwin/commit/c98bb238b16ba2cfc8eb9d5d5a18b79f8caacf25) | `` darwin-rebuild: Align usage description with implementation `` |
> chore(flake/darwin): `8c675759` -> `7840909b`

- flake.lock
| [`eea1bc60`](https://github.com/nix-community/home-manager/commit/eea1bc607249f0b79fb437b5e9709aa6d2218bac) | `` gpg-agent: use $TTY parameter in zsh integration `` |
| [`454e8d6b`](https://github.com/nix-community/home-manager/commit/454e8d6b15aafb02fd22bba0edc4cc0b06dd0f41) | `` granted: use assume directly ``                     |
| [`0a0b1b18`](https://github.com/nix-community/home-manager/commit/0a0b1b18bdd16d3f810178c7aec9eca730699631) | `` …
> chore(flake/home-manager): `a4353cc4` -> `eea1bc60`

- flake.lock
| [`8bd6e0a1`](https://github.com/nix-community/home-manager/commit/8bd6e0a1a805c373686e21678bb07f23293d357b) | `` nixgl: add support for channel-based configuration ``  |
| [`7a587970`](https://github.com/nix-community/home-manager/commit/7a5879707bb49c350aee7ab270c917584d430193) | `` nixgl: API rework for flexibility and dual-GPU ``      |
| [`e61f8796`](https://github.com/nix-community/home-manager/commit/e61f87969ae179139164c7fb5e0bb76b791144e5) | …
> chore(flake/home-manager): `eea1bc60` -> `5feb9dba`

- flake.lock
| [`c77c3bb2`](https://github.com/nix-community/home-manager/commit/c77c3bb23390a9ba91860e721edde54856fc5f7a) | `` yazi: enable shell integration values by default `` |
> chore(flake/home-manager): `5feb9dba` -> `c77c3bb2`

- flake.lock
| [`0c0268a3`](https://github.com/nix-community/home-manager/commit/0c0268a3c80d30b989d0aadbd65f38d4fa27a9a0) | `` eza: add color option ``                       |
| [`c0e23159`](https://github.com/nix-community/home-manager/commit/c0e23159872e2e2135c7eb5cf96cd36cfe6ee1f4) | `` git-credential-oauth: add extraFlags option `` |
| [`6cc03e33`](https://github.com/nix-community/home-manager/commit/6cc03e337aa1d0222e5942f58839d965075a9781) | `` nix-gc: add …
> chore(flake/home-manager): `c77c3bb2` -> `0c0268a3`

- flake.lock
| [`58cd8324`](https://github.com/nix-community/disko/commit/58cd832497f9c87cb4889744b86aba4284fd0474) | `` lvm_vg: fix size=100% leading to crash `` |
> chore(flake/disko): `09a77670` -> `58cd8324`

- flake.lock
| [`a3a535fb`](https://github.com/lovesegfault/vim-config/commit/a3a535fbffc228d8a8c553c626d80567c3b7d090) | `` chore(flake/nixvim): 4726334e -> 2ef948ed `` |
> chore(flake/lovesegfault-vim-config): `e96e908b` -> `a3a535fb`

- flake.lock
| [`05d9bee4`](https://github.com/nix-community/home-manager/commit/05d9bee4a5155758aec3c3807c0e342b9f253522) | `` git-credential-oauth: fix use of mkIf and add tests `` |
> chore(flake/home-manager): `93435d27` -> `05d9bee4`

- flake.lock
| [`e8341405`](https://github.com/nix-community/home-manager/commit/e83414058edd339148dc142a8437edb9450574c8) | `` flake.lock: Update `` |
> chore(flake/home-manager): `05d9bee4` -> `e8341405`

- flake.lock
| Commit                                                                                               | Message                                                                                         |
| ---------------------------------------------------------------------------------------------------- | ----------------------------------------------------------------------------------------------- |
| [`bae131e5`](https://github.com/numtide/treefmt-nix/commit/bae131e525cc8718da22fbeb8d8c7c43c4ea502a) | `` just: include .justfile (#246) ``                                                            |
| [`35b549ca`](https://github.com/numtide/treefmt-nix/commit/35b549cac94ee1fa41dbe662ba93ce9b6f458120) | `` cmake-format: init (#248) `` …
> chore(flake/treefmt-nix): `aac86347` -> `bae131e5`

- flake.lock
| [`89e458a3`](https://github.com/nix-community/disko/commit/89e458a3bb3693e769bfb2b2447c3fe72092d498) | `` UX: be specific if disko-install failed or succeeded (#847) `` |
> chore(flake/disko): `58cd8324` -> `89e458a3`

- flake.lock
| [`59b6e11b`](https://github.com/NixOS/nixos-hardware/commit/59b6e11bea99805b02ab38c8f9d8ba21fee58874) | `` Set missing lib.literalExpression `` |
> chore(flake/nixos-hardware): `e8a2f6d5` -> `6906ac67`

- flake.lock
| [`bdc80871`](https://github.com/lovesegfault/vim-config/commit/bdc80871d28b113b8aad7743e08da89ee5a94b9b) | `` chore(flake/nixpkgs): 2768c7d0 -> 18536bf0 ``     |
| [`3b1d67d6`](https://github.com/lovesegfault/vim-config/commit/3b1d67d6f1c995a0fcbf88a21d8272f83ba4c1ff) | `` chore(flake/treefmt-nix): aac86347 -> bae131e5 `` |
| [`724fccf6`](https://github.com/lovesegfault/vim-config/commit/724fccf60bfbccda6dcf4970fef8968bc4382641) | `` chore(flake/nixvim): 2ef948ed …
> chore(flake/lovesegfault-vim-config): `a3a535fb` -> `bdc80871`

- flake.lock
| [`95aaea00`](https://github.com/nix-community/lanzaboote/commit/95aaea008dc85c461633f6a748fd2a846580d85a) | `` chore(deps): lock file maintenance `` |
> chore(flake/lanzaboote): `e3978795` -> `0ad4ce46`

- flake.lock
| Commit                                                                                               | Message                                   |
| ---------------------------------------------------------------------------------------------------- | ----------------------------------------- |
| [`9ef337e4`](https://github.com/numtide/treefmt-nix/commit/9ef337e492a5555d8e17a51c911ff1f02635be15) | `` yamlfmt: add settings option (#193) `` |
> chore(flake/treefmt-nix): `bae131e5` -> `9ef337e4`

- flake.lock
| Commit                                                                                               | Message                                                             |
| ---------------------------------------------------------------------------------------------------- | ------------------------------------------------------------------- |
| [`bba79f6b`](https://github.com/nix-community/disko/commit/bba79f6b5eea35713f27815acbcda8775025e4c3) | `` disk-image: Fix "unexpected argument 'customQemu'" eval error `` |
> chore(flake/disko): `89e458a3` -> `3163b272`

- flake.lock
| [`0e55423b`](https://github.com/nix-community/disko/commit/0e55423bf8c241cf18676a8b8424c7eadd170ffc) | `` release: reset released flag `` |
| [`ab58501b`](https://github.com/nix-community/disko/commit/ab58501b2341bc5e0fc88f2f5983a679b075ddf5) | `` release: v1.9.0 ``              |
> chore(flake/disko): `3163b272` -> `0e55423b`

- flake.lock
| [`b15ceeff`](https://github.com/lovesegfault/vim-config/commit/b15ceeff3061a1a80d2915400ab119c652d9a774) | `` chore(flake/treefmt-nix): bae131e5 -> 9ef337e4 `` |
> chore(flake/lovesegfault-vim-config): `bdc80871` -> `b15ceeff`

- flake.lock
| [`e9077856`](https://github.com/NixOS/nixos-hardware/commit/e9077856732b7b2607120de06932aeb0c9b34f80) | `` lenovo/z/gen2/z13: Add modem fcc unlock `` |
> chore(flake/nixos-hardware): `6906ac67` -> `07d15e89`

- flake.lock
| [`39792850`](https://github.com/nix-community/disko/commit/3979285062d6781525cded0f6c4ff92e71376b55) | `` treewide: Fix using pkgs.{build,host}Platform alias `` |
> chore(flake/disko): `0e55423b` -> `39792850`

- flake.lock
| [`7c28ebf4`](https://github.com/lovesegfault/vim-config/commit/7c28ebf4bcfa48aa4002c3d4e6c1576d7c5a1e68) | `` refactor: fix noice move into settings ``    |
| [`470e4025`](https://github.com/lovesegfault/vim-config/commit/470e402518d4b909d02783cc05943f7f0d41c545) | `` chore(flake/nixvim): a20fbbc4 -> a4c3ad01 `` |
> chore(flake/lovesegfault-vim-config): `b15ceeff` -> `7c28ebf4`

- flake.lock
| [`142695a6`](https://github.com/lovesegfault/vim-config/commit/142695a6394aa1199f5c63276b0f9fe935dcda88) | `` chore(flake/nixvim): a4c3ad01 -> 7d882356 `` |
> chore(flake/lovesegfault-vim-config): `7c28ebf4` -> `142695a6`

- flake.lock
| [`746901bb`](https://github.com/numtide/treefmt-nix/commit/746901bb8dba96d154b66492a29f5db0693dbfcc) | `` nixpkgs-fmt: add `includes` and `excludes` options (#254) `` |
> chore(flake/treefmt-nix): `9ef337e4` -> `746901bb`

- flake.lock
| [`580d5885`](https://github.com/lovesegfault/vim-config/commit/580d58859ee52084c5983f5f621f36f252bee671) | `` chore(flake/treefmt-nix): 9ef337e4 -> 746901bb `` |
| [`4ba2615e`](https://github.com/lovesegfault/vim-config/commit/4ba2615e58cb793f32f58735837f3e8b7e012559) | `` chore(flake/git-hooks): 3c3e88f0 -> af8a16fe ``   |
> chore(flake/lovesegfault-vim-config): `142695a6` -> `580d5885`

- flake.lock
| [`2b84c693`](https://github.com/nix-community/impermanence/commit/2b84c693b9cf192807ecf910883b4ee16db7390a) | `` Update README.md with home-manager example ``         |
| [`21d60a0d`](https://github.com/nix-community/impermanence/commit/21d60a0db992bbad818ae26a145b23171399a1a1) | `` Use plural attribute names and add default modules `` |
| [`7a207dd3`](https://github.com/nix-community/impermanence/commit/7a207dd317524d86d8b2aa846072b703aec12f11) | `` …
> chore(flake/impermanence): `e3374575` -> `32800b01`

- flake.lock
| Commit                                                                                                | Message                                                                                |
| ----------------------------------------------------------------------------------------------------- | -------------------------------------------------------------------------------------- |
| [`da14839a`](https://github.com/NixOS/nixos-hardware/commit/da14839ac5f38ee6adbdb4e6db09b5eef6d6ccdc) | `` remove broadcom_sta since it was likely already added by nixos-generate-hardware `` |
| [`8cf35efb`](https://github.com/NixOS/nixos-hardware/commit/8cf35efba11b0ab1f4e50aac7a5fdeb42ea5b85c) | `` macbook air 7 ``                                                                    |
| …
> chore(flake/nixos-hardware): `07d15e89` -> `da14839a`

- flake.lock
| Commit                                                                                                      | Message                                                                                                     |
| ----------------------------------------------------------------------------------------------------------- | ----------------------------------------------------------------------------------------------------------- |
| [`e447a0e8`](https://github.com/nix-community/impermanence/commit/e447a0e827c3b9b3dd482bef8561cc26f4cd0a7d) | `` Allow disabling of persistant storage location in home-manager like is possible in the nixos version. `` |
> chore(flake/impermanence): `32800b01` -> `0d09341b`

- flake.lock
| [`87668665`](https://github.com/lovesegfault/vim-config/commit/8766866570234f4aeab3b7ef3d145b1d2d99243e) | `` chore(flake/nixpkgs): 18536bf0 -> 807e9154 `` |
| [`b58d14bc`](https://github.com/lovesegfault/vim-config/commit/b58d14bcdc96a917ebb728d1abe6804c13809631) | `` chore(flake/nixvim): 7d882356 -> 42ea1626 ``  |
> chore(flake/lovesegfault-vim-config): `580d5885` -> `87668665`

- flake.lock
| [`1743615b`](https://github.com/nix-community/home-manager/commit/1743615b61c7285976f85b303a36cdf88a556503) | `` podman: add module `` |
> chore(flake/home-manager): `8ca921e5` -> `1743615b`

- flake.lock
| [`3515023c`](https://github.com/lovesegfault/vim-config/commit/3515023c6f38600b666ffb984ae58752abe7092d) | `` chore(flake/flake-parts): 3d04084d -> 506278e7 `` |
| [`79852722`](https://github.com/lovesegfault/vim-config/commit/79852722b9ce877fb2ada7c687fb45213a8051b1) | `` chore(flake/nixvim): 42ea1626 -> 356896f5 ``      |
> chore(flake/lovesegfault-vim-config): `87668665` -> `3515023c`

- flake.lock
| [`be00f015`](https://github.com/NixOS/nixos-hardware/commit/be00f01542ad0a2b9962ec691c5709944847686c) | `` framework/bluetooth.nix: add EOL remark ``               |
| [`e4ad9ce3`](https://github.com/NixOS/nixos-hardware/commit/e4ad9ce38fa09e2f28ba15e830e17e367bf39a6c) | `` Framework: add workaround for Bluetooth device issues `` |
> chore(flake/nixos-hardware): `da14839a` -> `be00f015`

- flake.lock
| Commit                                                                                                | Message                   |
| ----------------------------------------------------------------------------------------------------- | ------------------------- |
| [`d3986e78`](https://github.com/NixOS/nixos-hardware/commit/d3986e78856a70d0b38d9e88dc39390556c2e962) | `` minisforum/v3: init `` |
> chore(flake/nixos-hardware): `be00f015` -> `d3986e78`

- flake.lock
| [`f6e0cd5c`](https://github.com/NixOS/nixos-hardware/commit/f6e0cd5c47d150c4718199084e5764f968f1b560) | `` Updated README ``                      |
| [`bcf80dc1`](https://github.com/NixOS/nixos-hardware/commit/bcf80dc17c840b79625bea50bd40ab4332b9295e) | `` Added Lenovo Ideadpad Slim 5 16IAH8 `` |
| [`8a906c9d`](https://github.com/NixOS/nixos-hardware/commit/8a906c9d3471439853aa05f6ec8ee1d3e6618c0d) | `` Added Lenovo Ideadpad 16AHP9 ``        |
> chore(flake/nixos-hardware): `d3986e78` -> `f6e0cd5c`

- flake.lock
| Commit                                                                                           | Message                                                              |
| ------------------------------------------------------------------------------------------------ | -------------------------------------------------------------------- |
| [`63f4d40e`](https://github.com/LnL7/nix-darwin/commit/63f4d40e551e7b29fbe586967c03eea1e6a70ce4) | `` tmux: remove `programs.tmux.defaultCommand` ``                    |
| [`1588cb2e`](https://github.com/LnL7/nix-darwin/commit/1588cb2e997fb37a4eab78da13808faf49df903f) | `` environment: remove misleading `environment.loginShell` option `` |
> chore(flake/darwin): `e56d80b2` -> `f203352c`

- flake.lock
| Commit                                                                                                | Message                                                                                                                                                         |
| ----------------------------------------------------------------------------------------------------- | --------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| [`f6581f1c`](https://github.com/NixOS/nixos-hardware/commit/f6581f1c3b137086e42a08a906bdada63045f991) | `` framework: workaround display issues on AMD GPUs `` …
> chore(flake/nixos-hardware): `f6e0cd5c` -> `f6581f1c`

- flake.lock
| [`3ed3f0ea`](https://github.com/nix-community/impermanence/commit/3ed3f0eaae9fcc0a8331e77e9319c8a4abd8a71a) | `` nixos: Work around systemd-machine-id-commit issue (#229) `` |
| [`491695be`](https://github.com/nix-community/impermanence/commit/491695bea3f03fbb09aca07379cc78f23c31cfc9) | `` nixos: Use mkMerge to allow duplicate definitions ``         |
| [`0ee1aee7`](https://github.com/nix-community/impermanence/commit/0ee1aee7a617ac5f17ad …
> chore(flake/impermanence): `0d09341b` -> `3ed3f0ea`

- flake.lock
| [`5e287600`](https://github.com/lovesegfault/vim-config/commit/5e287600475a924ab2b6d32dcfa7e13f189c1d90) | `` feat(lsp): autoarchive/eval inputs in nixd ``                              |
| [`4ae3f2c7`](https://github.com/lovesegfault/vim-config/commit/4ae3f2c71dd279267dd6000c68f4abaa336253f7) | `` chore(deps): bump DeterminateSystems/nix-installer-action from 14 to 15 `` |
| …
> chore(flake/lovesegfault-vim-config): `3515023c` -> `5e287600`

- flake.lock
| [`6ec4ba94`](https://github.com/NixOS/nixpkgs/commit/6ec4ba94c59f48a58eb33e7641763fe3ddab29ba) | `` nix-unit: 2.23.0 -> 2.24.0 ``                                          |
| [`c8fd06c3`](https://github.com/NixOS/nixpkgs/commit/c8fd06c3b23554bddf54148244bc3ef81aefba52) | `` nixos/tests/acme: wait for server to run before starting the target `` |
| [`75584cdd`](https://github.com/NixOS/nixpkgs/commit/75584cdd1406f1625faff4cd60ebaa9a83f2bec6) | …
> chore(flake/nixpkgs): `807e9154` -> `76612b17`

- flake.lock
| [`b87ed055`](https://github.com/cachix/git-hooks.nix/commit/b87ed055fb24db57ab528319d1e2026a6b8907d7) | `` feat(treefmt): add options to settings and disable cache by default `` |
| [`26f0d52b`](https://github.com/cachix/git-hooks.nix/commit/26f0d52b005bce294591c120585d6993c62cb8cb) | `` chore(deps): lock file maintenance ``                                  |
| [`04db8c18`](https://github.com/cachix/git-hooks.nix/commit/04db8c18ca …
> chore(flake/git-hooks): `af8a16fe` -> `cd1af27a`

- flake.lock
| Commit                                                                                               | Message                                                                     |
| ---------------------------------------------------------------------------------------------------- | --------------------------------------------------------------------------- |
| [`7d4cbcd2`](https://github.com/nix-community/disko/commit/7d4cbcd2352889f62b0944bdae84d09531de1732) | `` cli: Fix legacy aliases ``                                               |
| [`6bfa3a18`](https://github.com/nix-community/disko/commit/6bfa3a18d4625753bf653123e1d8a3b309eeaadd) | `` tests/interactive-cryptsetup: make waiting for passphrase more robust `` |
| [`21b2de0a`](https://github.com/nix-community/disko/commit/21b2de0 …
> chore(flake/disko): `39792850` -> `486250f4`

- flake.lock
| [`896019f0`](https://github.com/nix-community/nix-index-database/commit/896019f04b22ce5db4c0ee4f89978694f44345c3) | `` update generated.nix to release 2024-11-10-031357 `` |
| [`ddbdec98`](https://github.com/nix-community/nix-index-database/commit/ddbdec986ea89b1febebce875ff6660d38cf82da) | `` flake.lock: Update ``                                |
| [`cc2ddbf2`](https://github.com/nix-community/nix-index-database/commit/cc2ddbf2df8ef7cc933543 …
> chore(flake/nix-index-database): `0e3a8778` -> `896019f0`

- flake.lock
| Commit                                                                                           | Message                                                                      |
| ------------------------------------------------------------------------------------------------ | ---------------------------------------------------------------------------- |
| [`2bacd8db`](https://github.com/LnL7/nix-darwin/commit/2bacd8db310f479fab713829663d4b36913553cf) | `` environment: fix `lowPrio` support in `environment.systemPackages` ``     |
| [`8b27551e`](https://github.com/LnL7/nix-darwin/commit/8b27551e094666e6beb273c484392fa205bb0c97) | `` users: warn users to use `pkgs.bashInteractive` instead of `pkgs.bash` `` |
| [`5eb88645`](https://github.com/LnL7/nix-darwin/commit/5eb88645f74396d4b80fdf7 …
> chore(flake/darwin): `e30d226a` -> `839fd2a2`

- flake.lock
| [`69d89d55`](https://github.com/lovesegfault/vim-config/commit/69d89d55aacff483ea61d33cf34580616ef47f64) | `` refactor(lsp): unlimit nil_ls eval memory `` |
> chore(flake/lovesegfault-vim-config): `5e287600` -> `69d89d55`

- flake.lock
| [`67fbc7aa`](https://github.com/LnL7/nix-darwin/commit/67fbc7aa24cf0f4b5322b6f99fb3856bb9a1ab08) | `` checks: add check to ensure Homebrew is installed `` |
> chore(flake/darwin): `839fd2a2` -> `6c71c49e`

- flake.lock
| [`968da3b1`](https://github.com/lovesegfault/vim-config/commit/968da3b12ed2b630d94b34df6cd2123de55de390) | `` chore(flake/nixpkgs): 807e9154 -> 76612b17 ``   |
| [`68b6a44f`](https://github.com/lovesegfault/vim-config/commit/68b6a44ff67c1bf3eff5014d44da5b744154e724) | `` chore(flake/git-hooks): af8a16fe -> cd1af27a `` |
> chore(flake/lovesegfault-vim-config): `69d89d55` -> `968da3b1`

- flake.lock
| Commit                                                                                               | Message                           |
| ---------------------------------------------------------------------------------------------------- | --------------------------------- |
| [`11707dc2`](https://github.com/numtide/flake-utils/commit/11707dc2f618dd54ca8739b309ec4fc024de578b) | `` README: add new logo (#120) `` |
> chore(flake/flake-utils): `c1dfcf08` -> `11707dc2`

- flake.lock
| [`ee8ff6d5`](https://github.com/nix-community/home-manager/commit/ee8ff6d53fca9adec60238f63eb632300d0dffa0) | `` espanso: fix test for nixpkgs update ``        |
| [`7e42a37b`](https://github.com/nix-community/home-manager/commit/7e42a37bf7dffd7fe4c2b14e42161433d7182d66) | `` spotify-player: fix test for nixpkgs update `` |
| [`40746b5c`](https://github.com/nix-community/home-manager/commit/40746b5c77e9ab3fc2196802b637676574aaeb48) | `` alacritty: fix test for …
> chore(flake/home-manager): `60bb1109` -> `ee8ff6d5`

- flake.lock
| [`3b34ffba`](https://github.com/lovesegfault/vim-config/commit/3b34ffba355b192ff96b8d0aa2e41bab0b270051) | `` chore(flake/nixvim): 6f210158 -> f11a877b `` |
> chore(flake/lovesegfault-vim-config): `968da3b1` -> `3b34ffba`

- flake.lock
| [`9c7de558`](https://github.com/nix-community/disko/commit/9c7de5582ed980715a87fdb60c15e3d59cc750dd) | `` destroy: Fix shellcheck warning in nixos 24.05 `` |
> chore(flake/disko): `486250f4` -> `9c7de558`

- flake.lock
| [`35b05500`](https://github.com/nix-community/home-manager/commit/35b055009afd0107b69c286fca34d2ad98940d57) | `` kanshi: add package to home.packages ``        |
| [`3c044aef`](https://github.com/nix-community/home-manager/commit/3c044aefe610ceeec9cf3e83e55fa62715df27e2) | `` git-sync: add example to repository option ``  |
| [`cd21d2e6`](https://github.com/nix-community/home-manager/commit/cd21d2e61b2da9cc5b96f848ac6fd3c4dc377a1b) | `` git-sync: fix crash when …
> chore(flake/home-manager): `ee8ff6d5` -> `35b05500`

- flake.lock
| [`5fd852c4`](https://github.com/nix-community/disko/commit/5fd852c4155a689098095406500d0ae3d04654a8) | `` flake.lock: Update `` |
> chore(flake/disko): `9c7de558` -> `5fd852c4`
