flake.lock

| [`a01f2e23`](https://github.com/lovesegfault/vim-config/commit/a01f2e2358994301916ddc1f8abb646ba99067ce) | `` chore(flake/nixpkgs): 76612b17 -> dc460ec7 `` |
| [`d65f47dc`](https://github.com/lovesegfault/vim-config/commit/d65f47dc7a518e8e6e5ea36bd4703c4caf8d2590) | `` chore(flake/nixvim): f11a877b -> ccae4350 ``  |

chore(flake/lovesegfault-vim-config): `3b34ffba` -> `a01f2e23`

---

flake.lock

| Commit                                                                                           | Message                                       |
| ------------------------------------------------------------------------------------------------ | --------------------------------------------- |
| [`dae70299`](https://github.com/LnL7/nix-darwin/commit/dae702993d18c608f07e9d320ccba816e9bce064) | `` activate-system: remove `enable` option `` |

chore(flake/darwin): `6c71c49e` -> `f86f158e`

---

flake.lock

| [`0639755d`](https://github.com/lovesegfault/vim-config/commit/0639755d6d034a23972b9aeff01af7b8226cb36e) | `` chore(flake/nixvim): ccae4350 -> be455f7f `` |

chore(flake/lovesegfault-vim-config): `a01f2e23` -> `0639755d`

---

flake.lock

| [`0c657fd1`](https://github.com/NixOS/nixos-hardware/commit/0c657fd1342d7996874a19c6e5540fd6ab3cf876) | `` feat(Intel CoffeeLake): Added support ``    |
| [`dd93bef7`](https://github.com/NixOS/nixos-hardware/commit/dd93bef722ed86b56afda26902519ef69a52836d) | `` Reference intel core ultra in flake ``      |
| [`ccc638b2`](https://github.com/NixOS/nixos-hardware/commit/ccc638b24f7c29db45838588b5e747fddb1239af) | `` framework: Add Intel Core Ultra Series 1 `` |

chore(flake/nixos-hardware): `f6581f1c` -> `0c657fd1`

---

flake.lock

| [`c2c275fb`](https://github.com/NixOS/nixos-hardware/commit/c2c275fbb2e656948ba6e1f67b8ddd430f158c5f) | `` Add information on Gigabyte B650M Aorus Elite AX `` |

chore(flake/nixos-hardware): `0c657fd1` -> `c2c275fb`

---

flake.lock

| [`cb649938`](https://github.com/nix-community/disko/commit/cb64993826fa7a477490be6ccb38ba1fa1e18fa8) | `` cli: Fix "attribute missing" error when using flake `` |
| [`eaa51560`](https://github.com/nix-community/disko/commit/eaa51560df5352e501f9ada705282701d89c257d) | `` cli: Show error if flake's disko is incompatible ``    |
| [`9f97bd09`](https://github.com/nix-community/disko/commit/9f97bd0995b9bcee01b35dab6ba64ca6c1eb8caf) | `` lib: Fix jsonTypes evaluation …

chore(flake/disko): `5fd852c4` -> `cb649938`

---

flake.lock

| [`d154a557`](https://github.com/nix-community/home-manager/commit/d154a557da07645aaea3b3375317c234cf2eed82) | `` aerc: add support of account gpg config (#5298) ``                 |
| [`192f123e`](https://github.com/nix-community/home-manager/commit/192f123e4b5a4605c30566409ccacffc416e45c4) | `` nixos: add `key` to shared module to allow disabling it (#6017) `` |
| [`400e3c01`](https://github.com/nix-community/home-manager/com …

chore(flake/home-manager): `1d0862ee` -> `d154a557`

---

flake.lock

| Commit                                                                                                      | Message                                                                                                            |
| ----------------------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------------------------------------ |
| [`c7c25176`](https://github.com/nix-community/home-manager/commit/c7c251761235282acfc681accf8d3deea6681cc0) | `` {gtk, dunst}: replace `pkgs.gnome.adwaita-icon-theme` with `pkgs.adwaita-icon-theme` in the examples (#5712) `` |

chore(flake/home-manager): `d154a557` -> `c7c25176`

---

flake.lock

| [`1bd5616e`](https://github.com/nix-community/home-manager/commit/1bd5616e33c0c54d7a5b37db94160635a9b27aeb) | `` lib/file-type: Make `force` option visible (#6003) `` |

chore(flake/home-manager): `c7c25176` -> `1bd5616e`

---

flake.lock

| Commit                                                                                                | Message                                                                    |
| ----------------------------------------------------------------------------------------------------- | -------------------------------------------------------------------------- |
| [`672ac2ac`](https://github.com/NixOS/nixos-hardware/commit/672ac2ac86f7dff2f6f3406405bddecf960e0db6) | `` framework: Add `hardware.framework.laptop13.audioEnhancement` option `` |

chore(flake/nixos-hardware): `c2c275fb` -> `672ac2ac`

---

flake.lock

| [`2340727a`](https://github.com/lovesegfault/vim-config/commit/2340727a075e01c921c20157a880a31af6e8445c) | `` chore(flake/nixpkgs): dc460ec7 -> 5e4fbfb6 `` |
| [`74c4cc63`](https://github.com/lovesegfault/vim-config/commit/74c4cc631208ca95770a3e6962966bc9eb0b1352) | `` chore(flake/nixvim): be455f7f -> 9d99d7cf ``  |

chore(flake/lovesegfault-vim-config): `0639755d` -> `2340727a`

---

flake.lock

| [`0918bb02`](https://github.com/nix-community/home-manager/commit/0918bb02385a6897e7a0180d23ee4587491eb0d4) | `` ci: make dependabot consider release-24.11 ``           |
| [`aecd341d`](https://github.com/nix-community/home-manager/commit/aecd341dfead1c3ef7a3c15468ecd71e8343b7c6) | `` firefox: improve search engine disclaimer generation `` |

chore(flake/home-manager): `5056a1cf` -> `0918bb02`

---

flake.lock

| [`19da9e2b`](https://github.com/lovesegfault/vim-config/commit/19da9e2be0ce76eddc59e7217c8838aa2ca002dc) | `` chore(flake/nixvim): 9d99d7cf -> 5bc3fa69 `` |

chore(flake/lovesegfault-vim-config): `2340727a` -> `19da9e2b`

---

flake.lock

| Commit                                                                                           | Message                                                           |
| ------------------------------------------------------------------------------------------------ | ----------------------------------------------------------------- |
| [`4720d452`](https://github.com/LnL7/nix-darwin/commit/4720d452f8095703d1978700a1ea4f94eb3c1520) | `` manualHTML: support --redirects option in nixos-render-docs `` |

chore(flake/darwin): `34588d57` -> `c60b5c92`

---

flake.lock

| [`f3a2ff69`](https://github.com/nix-community/home-manager/commit/f3a2ff69586f3a54b461526e5702b1a2f81e740a) | `` zsh-abbr: update source path (#6084) `` |
| [`05d3b621`](https://github.com/nix-community/home-manager/commit/05d3b6215afa733fed6f025a59a562f98330acc3) | `` home-manager: prepare 25.05-pre ``      |

chore(flake/home-manager): `0918bb02` -> `f3a2ff69`

---

flake.lock

| [`639d1520`](https://github.com/nix-community/disko/commit/639d1520df9417ca2761536c3072688569e83c80) | `` flake.lock: Update `` |

chore(flake/disko): `cb649938` -> `639d1520`

---

flake.lock

| [`579b9a2f`](https://github.com/numtide/treefmt-nix/commit/579b9a2fd0020cd9cd81a4ef4eab2dca4d20c94c) | `` typstyle: init (#261) `` |

chore(flake/treefmt-nix): `746901bb` -> `579b9a2f`

---

flake.lock

| [`ad6fc7ce`](https://github.com/nix-community/lanzaboote/commit/ad6fc7ce540f0bd4161bbcf3f023e2c356f42f8b) | `` fix(deps): update all dependencies `` |

chore(flake/lanzaboote): `cef39a78` -> `2f48272f`

---

flake.lock

| [`705cf376`](https://github.com/nix-community/home-manager/commit/705cf3763a6d6074c1b7edb3ff0bb44efa7f091b) | `` Translate using Weblate (Ukrainian) `` |
| [`094265fc`](https://github.com/nix-community/home-manager/commit/094265fca0e000f8af3c38e4dde0e459f91d59f0) | `` Translate using Weblate (Italian) ``   |
| [`0bd5e9c7`](https://github.com/nix-community/home-manager/commit/0bd5e9c76c9f2f486f4bec0524e16026547df414) | `` librewolf: hide bookmarks option ``    |
| …

chore(flake/home-manager): `f3a2ff69` -> `705cf376`

---

flake.lock

| Commit                                                                                               | Message                       |
| ---------------------------------------------------------------------------------------------------- | ----------------------------- |
| [`675d4a7f`](https://github.com/numtide/treefmt-nix/commit/675d4a7fc531799ae8dfca1986b79be7660559e2) | `` dnscontrol: init (#262) `` |

chore(flake/treefmt-nix): `579b9a2f` -> `675d4a7f`

---

flake.lock

| [`a42fa14b`](https://github.com/nix-community/home-manager/commit/a42fa14b53ceab66274a21da480c9f8e06204173) | `` syncthing: expand declarative configuration `` |

chore(flake/home-manager): `705cf376` -> `a42fa14b`

---

flake.lock

| [`8586e25e`](https://github.com/lovesegfault/vim-config/commit/8586e25e94f0a603a903530349fa91b24e742eb5) | `` chore(flake/nix-github-actions): e04df33f -> 7b5f051d `` |

chore(flake/lovesegfault-vim-config): `19da9e2b` -> `8586e25e`

---

flake.lock

| Commit                                                                                               | Message                                                                         |
| ---------------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------- |
| [`5f5c2787`](https://github.com/numtide/treefmt-nix/commit/5f5c2787576f3e39bbc2ebdbf8521b3177c5c19c) | `` feat: update nixpkgs input (#260) ``                                         |
| [`a3e1cc8f`](https://github.com/numtide/treefmt-nix/commit/a3e1cc8f9ff919ab58f026b718377d133a2b4488) | `` just: fix includes config for both hidden and non-hidden justfiles (#263) `` |

chore(flake/treefmt-nix): `675d4a7f` -> `5f5c2787`

---

flake.lock

| [`d37f154d`](https://github.com/nix-community/home-manager/commit/d37f154dba0d4c015f17a24314e89b77a7ba5ff3) | `` flake.lock: Update `` |

chore(flake/home-manager): `a42fa14b` -> `d37f154d`

---

flake.lock

| [`a46e7020`](https://github.com/nix-community/home-manager/commit/a46e702093a5c46e192243edbd977d5749e7f294) | `` espanso: fix test failure `` |

chore(flake/home-manager): `d37f154d` -> `a46e7020`

---

flake.lock

| Commit                                                                                               | Message                                                              |
| ---------------------------------------------------------------------------------------------------- | -------------------------------------------------------------------- |
| [`da52cf40`](https://github.com/nix-community/disko/commit/da52cf40206d7d1a419d07640eb47b2fb9ac2c21) | `` Add explanatory comment to examples/zfs-over-legacy.nix (#886) `` |

chore(flake/disko): `639d1520` -> `da52cf40`

---

flake.lock

| [`51b7bc9c`](https://github.com/lovesegfault/vim-config/commit/51b7bc9cf17bc02edea3c253b1015b47302c4ac6) | `` chore(flake/treefmt-nix): 746901bb -> 5f5c2787 ``                          |
| [`45036332`](https://github.com/lovesegfault/vim-config/commit/45036332895f0ed80f3d483e780f988055c9545f) | `` chore(flake/git-hooks): cd1af27a -> 3308484d ``                            |
| …

chore(flake/lovesegfault-vim-config): `8586e25e` -> `51b7bc9c`

---

flake.lock

| [`f291b894`](https://github.com/lovesegfault/vim-config/commit/f291b894b3ed7853708223a694ec44165c9b2a09) | `` chore(flake/nixvim): c674f10d -> 929bb0cd `` |

chore(flake/lovesegfault-vim-config): `51b7bc9c` -> `f291b894`

---

flake.lock

| [`c3b83db7`](https://github.com/nix-community/disko/commit/c3b83db725d33e74d41324df6dc55d9098510483) | `` module: Expose tests.enableOCR ``    |
| [`feeb365e`](https://github.com/nix-community/disko/commit/feeb365e31effdfef92a21176f88941fb2a7f126) | `` module: Expose tests.bootCommands `` |

chore(flake/disko): `da52cf40` -> `c3b83db7`

---

flake.lock

| [`92ad6784`](https://github.com/nix-community/disko/commit/92ad678418917a6826f9eabb34995b2b8e58229e) | `` Add examples for all special zpool vdev types ``     |
| [`caad5484`](https://github.com/nix-community/disko/commit/caad548415edb0cfe20d29a363aa98137fd7cc2b) | `` Make vdev sort only move empty modes to the start `` |
| [`d192ffd9`](https://github.com/nix-community/disko/commit/d192ffd9449cab0f31a86c3205384c20f45b288e) | `` Fix zpool create for disk vdev after …

chore(flake/disko): `c3b83db7` -> `a0c384e0`

---

flake.lock

| [`62003fda`](https://github.com/numtide/treefmt-nix/commit/62003fdad7a5ab7b6af3ea9bd7290e4c220277d0) | `` feat: sqlfluff support (#258) `` |

chore(flake/treefmt-nix): `5f5c2787` -> `62003fda`

---

flake.lock

| [`d5808aee`](https://github.com/NixOS/nixpkgs/commit/d5808aee19c06e9e6b2603d0b600de34ed890de8) | `` handheld-daemon-ui: init at 3.2.3 (#305027) ``                                      |
| [`46cc4292`](https://github.com/NixOS/nixpkgs/commit/46cc4292da55da3aadf5b7d306b1f00aa91d2b0c) | `` libretro.mame2003-plus: unstable-2024-10-05 -> unstable-2024-11-19 ``               |
| …

chore(flake/nixpkgs): `5e4fbfb6` -> `23e89b7d`

---

flake.lock

| [`9f4d6424`](https://github.com/lovesegfault/vim-config/commit/9f4d6424fec041714981a07a1e983fdbd5a07e16) | `` chore(flake/treefmt-nix): 5f5c2787 -> 62003fda `` |

chore(flake/lovesegfault-vim-config): `f291b894` -> `9f4d6424`

---

flake.lock

| [`34ae1178`](https://github.com/lovesegfault/vim-config/commit/34ae1178f106cb8522a8777d8329389dc5160f00) | `` chore(flake/nixpkgs): 5e4fbfb6 -> 23e89b7d `` |
| [`b77d27e8`](https://github.com/lovesegfault/vim-config/commit/b77d27e8341727283eeb3fbecafcf90329ced5df) | `` chore(flake/nixvim): 929bb0cd -> 2f71c425 ``  |

chore(flake/lovesegfault-vim-config): `9f4d6424` -> `34ae1178`

---

flake.lock

| Commit                                                                                               | Message                         |
| ---------------------------------------------------------------------------------------------------- | ------------------------------- |
| [`37f8f47c`](https://github.com/numtide/treefmt-nix/commit/37f8f47cb618eddee0c0dd31a582b1cd3013c7f6) | `` README: new format (#259) `` |

chore(flake/treefmt-nix): `62003fda` -> `37f8f47c`

---

flake.lock

| [`0e5eb607`](https://github.com/nix-community/disko/commit/0e5eb607f0f941a538f32b7d5af193fa51b6cfab) | `` flake.lock: Update `` |

chore(flake/disko): `a0c384e0` -> `97c0c4d7`

---

flake.lock

| [`cc4b2b32`](https://github.com/lovesegfault/vim-config/commit/cc4b2b32577c43fbeb7df734caaf74a07dd1e125) | `` chore(flake/treefmt-nix): 62003fda -> 37f8f47c `` |

chore(flake/lovesegfault-vim-config): `34ae1178` -> `cc4b2b32`

---

flake.lock

| Commit                                                                                           | Message                                                                       |
| ------------------------------------------------------------------------------------------------ | ----------------------------------------------------------------------------- |
| [`095ba550`](https://github.com/LnL7/nix-darwin/commit/095ba5502c83c5fd8173a1b0dbc99a0e1be7e42d) | `` default: expose all the `darwin-*` commands ``                             |
| [`d57e7486`](https://github.com/LnL7/nix-darwin/commit/d57e74864bccd31e081443733bfaee1eda85a242) | `` uninstaller: always specify `--extra-experimental-features` first ``       |
| [`2ca27ba7`](https://github.com/LnL7/nix-darwin/commit/2ca27ba780bb072e9fb …

chore(flake/darwin): `61cee201` -> `edabc790`

---

flake.lock

| Commit                                                                                               | Message                                  |
| ---------------------------------------------------------------------------------------------------- | ---------------------------------------- |
| [`3a8a8713`](https://github.com/nix-community/disko/commit/3a8a8713bf64f79696c4784ad3cf0fa988ca7938) | `` fix: restore nix 2.3 compatibility `` |

chore(flake/disko): `97c0c4d7` -> `84dd8eea`

---

flake.lock

| Commit                                                                                               | Message                                                                             |
| ---------------------------------------------------------------------------------------------------- | ----------------------------------------------------------------------------------- |
| [`fd3e326e`](https://github.com/nix-community/disko/commit/fd3e326e9a75f919463184a53ca2ee9c31e4ebdf) | `` disable swap in disko-install ``                                                 |
| [`eb1bb9fe`](https://github.com/nix-community/disko/commit/eb1bb9fe2739efc7a6ee82b2cd120c403d8e2632) | `` disko-install: allow to override mountpoints and don't manage them in dry-run `` |
| …

chore(flake/disko): `84dd8eea` -> `abc8baff`

---

flake.lock

| Commit                                                                                               | Message              |
| ---------------------------------------------------------------------------------------------------- | -------------------- |
| [`705df926`](https://github.com/numtide/treefmt-nix/commit/705df92694af7093dfbb27109ce16d828a79155f) | `` doc fix (#264) `` |

chore(flake/treefmt-nix): `37f8f47c` -> `705df926`

---

flake.lock

| [`858583c6`](https://github.com/lovesegfault/vim-config/commit/858583c6343172e4b3dd1bf3872ccf8da9ea44f3) | `` chore(flake/nixvim): 85759f23 -> a81a03a3 ``      |
| [`5daac50c`](https://github.com/lovesegfault/vim-config/commit/5daac50cc9be0ccbdaa4ee8c669a194ecf4a6c97) | `` chore(flake/nixvim): c1271fa1 -> 85759f23 ``      |
| [`d30c6cd9`](https://github.com/lovesegfault/vim-config/commit/d30c6cd9a2991f52bb258d9d14beaf16b701afc9) | `` chore(flake/nixvim): 2f71c425 …

chore(flake/lovesegfault-vim-config): `cc4b2b32` -> `858583c6`

---

flake.lock

| Commit                                                                                                            | Message                                                       |
| ----------------------------------------------------------------------------------------------------------------- | ------------------------------------------------------------- |
| [`fdc58afc`](https://github.com/nix-community/nix-index-database/commit/fdc58afcc31a59b679b676071b94442b3f83bbec) | `` darwin-module: stop setting unused comma.package option `` |
| [`bedc30c6`](https://github.com/nix-community/nix-index-database/commit/bedc30c64442579943c1c6e7579db263d810884f) | `` add missing include for home-manager ``                    |
| [`0ef970b7`](https://github.com/nix-community/nix-index-database/commi …

chore(flake/nix-index-database): `bdba2469` -> `f4a5ca57`

---

flake.lock

| [`10c399bb`](https://github.com/NixOS/nixos-hardware/commit/10c399bbac631ca6f750619d46bfdbeeb152efe1) | `` Added Lenovo Ideapad 16AHP9 to Flake.nix `` |

chore(flake/nixos-hardware): `672ac2ac` -> `45348ad6`

---

flake.lock

| [`82ed8010`](https://github.com/LnL7/nix-darwin/commit/82ed8010ffb17b637cbbd916398ee3a4027cfb10) | `` ci: extend timeout and remove `tmate` `` |
| [`caa23e87`](https://github.com/LnL7/nix-darwin/commit/caa23e878f7f6fecb978bb91c1d208bf94a62c43) | `` github-runner: make `umask` quiet ``     |
| [`23f312e4`](https://github.com/LnL7/nix-darwin/commit/23f312e48a252e348fc8884f2abc7975f976aac0) | `` nix-tools: set `meta.mainProgram` ``     |

chore(flake/darwin): `edabc790` -> `3c52583b`

---

flake.lock

| Commit                                                                                               | Message                                                       |
| ---------------------------------------------------------------------------------------------------- | ------------------------------------------------------------- |
| [`3e83c110`](https://github.com/nix-community/disko/commit/3e83c1103855ea50fffc573277d5c680f357d8e3) | `` Fix evaluation when a GPT partition is left unformatted `` |
| [`8d80e4e8`](https://github.com/nix-community/disko/commit/8d80e4e8fc7a586d51575aa4f80daee5f6db0a85) | `` flake.lock: Update ``                                      |
| [`0433c7e8`](https://github.com/nix-community/disko/commit/0433c7e8832da9ab622d8a69abe45249f1f41f37) | `` also …

chore(flake/disko): `abc8baff` -> `2ed5e30f`

---

flake.lock

| Commit                                                                                                   | Message                                           |
| -------------------------------------------------------------------------------------------------------- | ------------------------------------------------- |
| [`69dcbf35`](https://github.com/lovesegfault/vim-config/commit/69dcbf35b93b8332f2ff3433ad2e83f5179b4a64) | `` fix: use nixfmt instead of nixfmt-rfc-style `` |
| [`40f9e6bf`](https://github.com/lovesegfault/vim-config/commit/40f9e6bf55600299b83bc1d8237a783b12ac648b) | `` refactor: migrate to nixfmt-rfc-style ``       |

chore(flake/lovesegfault-vim-config): `858583c6` -> `69dcbf35`

---

flake.lock

| Commit                                                                                           | Message                                                          |
| ------------------------------------------------------------------------------------------------ | ---------------------------------------------------------------- |
| [`25e0b606`](https://github.com/LnL7/nix-darwin/commit/25e0b6064eed7a4ffeca7bacbba9dcca6fa8cc86) | `` system: fix detection and ownership of /etc/synthetic.conf `` |

chore(flake/darwin): `3c52583b` -> `6ab87b7c`

---

flake.lock

| Commit                                                                                               | Message                                         |
| ---------------------------------------------------------------------------------------------------- | ----------------------------------------------- |
| [`255e11e8`](https://github.com/nix-community/disko/commit/255e11e83102a574336e4831ad82e199d280e84d) | `` module: add default for tests.bootCommand `` |

chore(flake/disko): `2ed5e30f` -> `869ba3a8`

---

flake.lock

| Commit                                                                                               | Message                                                      |
| ---------------------------------------------------------------------------------------------------- | ------------------------------------------------------------ |
| [`84637a7a`](https://github.com/numtide/treefmt-nix/commit/84637a7ab04179bdc42aa8fd0af1909fba76ad0c) | `` options: default projectRootFile to .git/config (#267) `` |

chore(flake/treefmt-nix): `705df926` -> `84637a7a`

---

flake.lock

| [`5fb6eabb`](https://github.com/lovesegfault/vim-config/commit/5fb6eabbe85bb0f1cab9e433e911b2d8133d1ddc) | `` chore(flake/treefmt-nix): 705df926 -> 84637a7a `` |
| [`defa1a36`](https://github.com/lovesegfault/vim-config/commit/defa1a368bcad31276fcfca22e8c2bd389287f46) | `` chore(flake/nixvim): a81a03a3 -> 8b19d154 ``      |

chore(flake/lovesegfault-vim-config): `69dcbf35` -> `5fb6eabb`

---

flake.lock

| Commit                                                                                                 | Message                                                            |
| ------------------------------------------------------------------------------------------------------ | ------------------------------------------------------------------ |
| [`baa7aa7b`](https://github.com/edolstra/flake-compat/commit/baa7aa7bd0a570b3b9edd0b8da859fee3ffaa4d4) | `` Check for pure eval mode before calling `builtins.storePath` `` |
| [`b7cd5940`](https://github.com/edolstra/flake-compat/commit/b7cd594063b9118c198bbdb4c22c19ca0919822a) | `` README: fix node name look-up ``                                |

chore(flake/flake-compat): `0f9255e0` -> `4a4fe463`

---

flake.lock

| Commit                                                                                                 | Message                  |
| ------------------------------------------------------------------------------------------------------ | ------------------------ |
| [`a1b45cd4`](https://github.com/edolstra/flake-compat/commit/a1b45cd4a224023888702a60d6830bc0ab40c038) | `` Return all outputs `` |

chore(flake/flake-compat): `e3408d6a` -> `9ed2ac15`

---

flake.lock

| [`ff6e5963`](https://github.com/nix-community/disko/commit/ff6e5963531d7b8a82dc0d5836697cfe27ff957a) | `` fix new logo in quickstart.md `` |

chore(flake/disko): `869ba3a8` -> `341482e2`

---

flake.lock

| Commit                                                                                                   | Message                                               |
| -------------------------------------------------------------------------------------------------------- | ----------------------------------------------------- |
| [`e651b078`](https://github.com/lovesegfault/vim-config/commit/e651b078ff3979a6da797f30a3f2e828cbafc66c) | `` chore(flake/nixvim): 7eb106ab -> fc9178d1 ``       |
| [`c1bf2b72`](https://github.com/lovesegfault/vim-config/commit/c1bf2b7285d8b3a163eba0f888b9cef821123a7d) | `` chore(flake/flake-compat): 4a4fe463 -> 9ed2ac15 `` |

chore(flake/lovesegfault-vim-config): `7bd5d2ce` -> `e651b078`

---

flake.lock

| [`2f7739d0`](https://github.com/nix-community/home-manager/commit/2f7739d01080feb4549524e8f6927669b61c6ee3) | `` kakoune: add colorSchemePackage option ``         |
| [`b7219652`](https://github.com/nix-community/home-manager/commit/b7219652387ce4331ae49ddac8b0286f50e0ed68) | `` mopidy: ignore collisions between extensions ``   |
| [`de7d67b8`](https://github.com/nix-community/home-manager/commit/de7d67b8bae8aa2ac920fa10918c89ce44b66d00) | `` mopidy: make …

chore(flake/home-manager): `a9953635` -> `2f7739d0`

---

flake.lock

| Commit                                                                                               | Message                                                                  |
| ---------------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------ |
| [`6209c381`](https://github.com/numtide/treefmt-nix/commit/6209c381904cab55796c5d7350e89681d3b2a8ef) | `` google-java-format: add `aospStyle`, `includes`, `excludes` (#256) `` |
| [`4dadf4ff`](https://github.com/numtide/treefmt-nix/commit/4dadf4ff139114771292b5ad25b437f70bf7bec1) | `` texfmt: init (#266) ``                                                |

chore(flake/treefmt-nix): `84637a7a` -> `6209c381`

---

flake.lock

| [`aa006252`](https://github.com/nix-community/disko/commit/aa006252c848b90f322ffb1535a67d579e0ef06f) | `` add unmount feature `` |

chore(flake/disko): `341482e2` -> `a75ba3b8`

---

flake.lock

| [`819f6822`](https://github.com/nix-community/home-manager/commit/819f682269f4e002884702b87e445c82840c68f2) | `` lorri: fix ReadWritePaths for new gcroots behavior `` |

chore(flake/home-manager): `2f7739d0` -> `819f6822`

---

flake.lock

| Commit                                                                                               | Message                                                        |
| ---------------------------------------------------------------------------------------------------- | -------------------------------------------------------------- |
| [`5655a13a`](https://github.com/nix-community/disko/commit/5655a13ac97b98f1644e4f4b81a10a6c4668f4cf) | `` make-disk-image: Compare against correct nixpkgs version `` |

chore(flake/disko): `a75ba3b8` -> `b71e3fac`

---

flake.lock

| [`0e9accbc`](https://github.com/lovesegfault/vim-config/commit/0e9accbc2d7ee7cfceb7143060f6794d8a563fcf) | `` chore(flake/treefmt-nix): 84637a7a -> 6209c381 `` |
| [`8b8edf4b`](https://github.com/lovesegfault/vim-config/commit/8b8edf4b5076fe16dde820336b3363566a82f956) | `` chore(flake/nixvim): fc9178d1 -> 05331006 ``      |

chore(flake/lovesegfault-vim-config): `e651b078` -> `0e9accbc`

---

flake.lock

| [`3faa3002`](https://github.com/nix-community/disko/commit/3faa300212095bc5ceed32825d788553242612ec) | `` disk-image: Fix compatibility with nixpkgs unstable `` |

chore(flake/disko): `b71e3fac` -> `2814a522`

---

flake.lock

| [`d13ffb38`](https://github.com/danth/stylix/commit/d13ffb381c83b6139b9d67feff7addf18f8408fe) | `` vim: add target attribute to prevent build failure (#652) `` |
| [`5f912cec`](https://github.com/danth/stylix/commit/5f912cecb4e1c5c794316c4b79b9b5d57d43e100) | `` river: init (#651) ``                                        |
| [`f3c2f5a1`](https://github.com/danth/stylix/commit/f3c2f5a1796cbba1e1685270cf0f5a66f118ea96) | `` stylix: set GTK icon theme (#603) `` …

chore(flake/stylix): `7689e621` -> `d13ffb38`

---

flake.lock
graphical/fonts.nix
users/bemeurer/graphical/default.nix

| [`970e93b9`](https://github.com/NixOS/nixpkgs/commit/970e93b9f82e2a0f3675757eb0bfc73297cc6370) | `` terraform-providers.doppler: 1.11.0 -> 1.12.0 ``                                               |
| [`f8b32a49`](https://github.com/NixOS/nixpkgs/commit/f8b32a49213a9ccc1c1a38379aa071c532f1e29c) | `` terraform-providers.yandex: 0.130.0 -> 0.133.0 ``                                              |
| …

chore(flake/nixpkgs): `4633a7c7` -> `970e93b9`

---

flake.lock

| [`fd6e7174`](https://github.com/lovesegfault/vim-config/commit/fd6e7174388280a865d7b9d33b1283810a5fcd09) | `` chore(flake/nixpkgs): 4633a7c7 -> 970e93b9 `` |
| [`ec1c2e7d`](https://github.com/lovesegfault/vim-config/commit/ec1c2e7dc6e2f61dc97a59a94a11ef5bd7674eac) | `` chore(flake/nixvim): 05331006 -> 060f4b4c ``  |

chore(flake/lovesegfault-vim-config): `0e9accbc` -> `fd6e7174`

---

flake.lock

| [`6e0b7f81`](https://github.com/nix-community/nix-index-database/commit/6e0b7f81367069589a480b91603a10bcf71f3103) | `` update generated.nix to release 2024-12-01-033612 `` |
| [`fc9c0def`](https://github.com/nix-community/nix-index-database/commit/fc9c0def2633a44750f1f1cd9f03ab6c5ad5c7bb) | `` flake.lock: Update ``                                |

chore(flake/nix-index-database): `f4a5ca57` -> `6e0b7f81`

---

flake.lock

| [`09e5dfb6`](https://github.com/LnL7/nix-darwin/commit/09e5dfb67ee27355d78d35a4f4ab747c230cb9b8) | `` defaults: add `EnableTiledWindowMargins` option `` |

chore(flake/darwin): `6ab87b7c` -> `e30a3622`

---

flake.lock

| [`4964f3c6`](https://github.com/nix-community/home-manager/commit/4964f3c6fc17ae4578e762d3dc86b10fe890860e) | `` home-manager: prepare 24.11 release `` |
| [`8eeda281`](https://github.com/nix-community/home-manager/commit/8eeda281e70cbadabb7f0095c5f34e354e85f307) | `` flake.lock: Update ``                  |

chore(flake/home-manager): `819f6822` -> `4964f3c6`

---

flake.lock

| Commit                                                                                                | Message                                                                                  |
| ----------------------------------------------------------------------------------------------------- | ---------------------------------------------------------------------------------------- |
| [`fe01780d`](https://github.com/NixOS/nixos-hardware/commit/fe01780d356d70fd119a19277bff71d3e78dad00) | `` Update flake.nix ``                                                                   |
| [`93183259`](https://github.com/NixOS/nixos-hardware/commit/9318325957572aae826cc37d4378412b0d49d5dc) | `` 「✨」 feat(Dell Precision 5530): Added Nvidia support and some other feature (#1254) `` |
| …

chore(flake/nixos-hardware): `45348ad6` -> `fe01780d`

---

flake.lock

| [`0188252d`](https://github.com/Mic92/nix-fast-build/commit/0188252d0883d23b621e39daf340c6bc74ea95ee) | `` add buildbot to mergify `` |
| [`86f2973d`](https://github.com/Mic92/nix-fast-build/commit/86f2973d0e0f28d1bc2e92ebbad90993d61e784f) | `` add dependabot ``          |
| [`f24c6c44`](https://github.com/Mic92/nix-fast-build/commit/f24c6c44e11f4f8a20fe4e756079ffdb4005c744) | `` update flake lock ``       |

chore(flake/nix-fast-build): `f51f479d` -> `f67312c5`

---

flake.lock

| [`86327350`](https://github.com/nix-community/home-manager/commit/863273505016a1e88e4ffaec48d1b767104c5652) | `` kubecolor: add module ``        |
| [`e71e678d`](https://github.com/nix-community/home-manager/commit/e71e678d18d1a24e01d823ccb72df13f9e82f65b) | `` nix-your-shell: add module ``   |
| [`7f78e2d1`](https://github.com/nix-community/home-manager/commit/7f78e2d1c6a9db76444e02a73f0669ebb79f8833) | `` yazi: update keymap config ``   |
| …

chore(flake/home-manager): `4964f3c6` -> `86327350`

---

flake.lock

| [`95f5dc09`](https://github.com/Mic92/nix-fast-build/commit/95f5dc09a725a1916fd064f01eb3be9a5f487095) | `` nixfmt: disable on riscv64 `` |
| [`4cd5ea09`](https://github.com/Mic92/nix-fast-build/commit/4cd5ea094fc56122c28e5da1800a8f7ec6a7b52b) | `` reformat test.yml ``          |
| [`5390a457`](https://github.com/Mic92/nix-fast-build/commit/5390a45760c0d48da0692f6b6231836886c4d40f) | `` flake.lock: Update ``         |

chore(flake/nix-fast-build): `f67312c5` -> `95f5dc09`

---

flake.lock

| [`5fdab448`](https://github.com/lovesegfault/vim-config/commit/5fdab448adb15968ccd741e8968aa86388583af1) | `` chore(flake/nixvim): 060f4b4c -> 80e49e7f `` |

chore(flake/lovesegfault-vim-config): `fd6e7174` -> `5fdab448`

---

flake.lock

| [`c1fee8d4`](https://github.com/nix-community/home-manager/commit/c1fee8d4a60b89cae12b288ba9dbc608ff298163) | `` alot: make package used by module configurable `` |

chore(flake/home-manager): `86327350` -> `c1fee8d4`

---

flake.lock

| [`567bae1e`](https://github.com/LnL7/nix-darwin/commit/567bae1e17fdd10eccc9d5c6ec20e3d98d498de7) | `` defaults: expose-group-by-app -> expose-group-apps `` |

chore(flake/darwin): `e30a3622` -> `c6b65d94`

---

flake.lock

| [`c6c90887`](https://github.com/NixOS/nixos-hardware/commit/c6c90887f84c02ce9ebf33b95ca79ef45007bf88) | `` drop acpi_call from nixos-hardware `` |

chore(flake/nixos-hardware): `fe01780d` -> `c6c90887`

---

flake.lock

| [`873e39d5`](https://github.com/nix-community/home-manager/commit/873e39d5f4437d2f3ab06881fea8e63e45e1d011) | `` podman-container: fix tests and failing podman 5.3.0 service `` |
| [`d2e2bda6`](https://github.com/nix-community/home-manager/commit/d2e2bda6c050a61d51b8e395ad66b8fa48318e07) | `` nix-your-shell: fix creating required directory ``              |

chore(flake/home-manager): `c1fee8d4` -> `873e39d5`

---

flake.lock

| Commit                                                                                        | Message                      |
| --------------------------------------------------------------------------------------------- | ---------------------------- |
| [`74ee1ed5`](https://github.com/danth/stylix/commit/74ee1ed5057e44edbcc36aa189a91d31eda60485) | `` kubecolor: init (#657) `` |

chore(flake/stylix): `d13ffb38` -> `74ee1ed5`

---

flake.lock

| [`67a130b9`](https://github.com/nix-community/disko/commit/67a130b984603fbbcf5dd538399bb1240a570a23) | `` tree-wide: Remove all uses of lib.mdDoc `` |

chore(flake/disko): `2814a522` -> `785c1e02`

---

flake.lock

| [`fd814511`](https://github.com/lovesegfault/vim-config/commit/fd814511e73b00218abd7a7dbd78455f79a3132a) | `` chore(flake/nixpkgs): 970e93b9 -> ac35b104 `` |
| [`00c36e51`](https://github.com/lovesegfault/vim-config/commit/00c36e5183d9204db924b6f90e1ce312c07eb43f) | `` chore(flake/nixvim): 80e49e7f -> e680b367 ``  |

chore(flake/lovesegfault-vim-config): `5fdab448` -> `fd814511`

---

flake.lock

| [`bf23fe41`](https://github.com/nix-community/home-manager/commit/bf23fe41082aa0289c209169302afd3397092f22) | `` tmux: add 'focusEvents' `` |

chore(flake/home-manager): `873e39d5` -> `bf23fe41`

---

flake.lock

| [`49717b5a`](https://github.com/numtide/treefmt-nix/commit/49717b5af6f80172275d47a418c9719a31a78b53) | `` README: fix deadlinks `` |

chore(flake/treefmt-nix): `6209c381` -> `49717b5a`

---

flake.lock

| Commit                                                                                                | Message        |
| ----------------------------------------------------------------------------------------------------- | -------------- |
| [`c6cddc7b`](https://github.com/NixOS/nixos-hardware/commit/c6cddc7bb2bb8339bf9c19ab40ec9e2b48299e3c) | `` fix eval `` |

chore(flake/nixos-hardware): `c6c90887` -> `cceee0a3`

---

flake.lock

| [`111c75d7`](https://github.com/danth/stylix/commit/111c75d73439fe4bea2cdfbeb60aeeb6ea770220) | `` sway: handle cursor names containing spaces (#654) `` |

chore(flake/stylix): `74ee1ed5` -> `111c75d7`

---

flake.lock

| Commit                                                                                        | Message                                  |
| --------------------------------------------------------------------------------------------- | ---------------------------------------- |
| [`ffba1f1b`](https://github.com/danth/stylix/commit/ffba1f1bab63ea49541f812c72a4fcf305461d67) | `` gnome: update to GNOME 47.2 (#658) `` |

chore(flake/stylix): `111c75d7` -> `ffba1f1b`

---

flake.lock

| [`5b5de433`](https://github.com/nix-community/home-manager/commit/5b5de4338fad32dc709c900b4dcbbcd98b20dc4c) | `` kakoune: fix color scheme package XDG file ``             |
| [`256ec265`](https://github.com/nix-community/home-manager/commit/256ec2653e79363022a6042285dde3935816cea4) | `` flake.lock: Update ``                                     |
| [`dfdf59b2`](https://github.com/nix-community/home-manager/commit/dfdf59b2d539941aea5c26666c9ab809 …

chore(flake/home-manager): `bf23fe41` -> `5b5de433`

---

flake.lock

| [`6c3a7a0b`](https://github.com/nix-community/home-manager/commit/6c3a7a0b72c19ec994b85c57a1712d177bd809b2) | `` qt: reduce test closure ``           |
| [`8f4f57f9`](https://github.com/nix-community/home-manager/commit/8f4f57f9a67367881b1a36f93856ffef8646d428) | `` qt: update tooling for Plasma 6 ``   |
| [`70803283`](https://github.com/nix-community/home-manager/commit/70803283187c8f775ff561be4117e5b1a11b296e) | `` Translate using Weblate (Finnish) `` |

chore(flake/home-manager): `5b5de433` -> `6c3a7a0b`

---

flake.lock

| Commit                                                                                           | Message                                                               |
| ------------------------------------------------------------------------------------------------ | --------------------------------------------------------------------- |
| [`0f9576ce`](https://github.com/LnL7/nix-darwin/commit/0f9576cedc9b23ec8b01302daae919bc6018c3ca) | `` nix: fix Lix version detection in auto-optimise-store assertion `` |

chore(flake/darwin): `c6b65d94` -> `e7a71f8e`

---

flake.lock

| [`ad48eb25`](https://github.com/nix-community/home-manager/commit/ad48eb25cd0b00ce730da00fa1f8e6e6c27b397d) | `` etesync-dav: update default server URL ``                 |
| [`b1c19f1d`](https://github.com/nix-community/home-manager/commit/b1c19f1dcbc2429c16d5e6259dbff4f12dd8a89d) | `` home-cursor: use `profileExtra` instead of `initExtra` `` |
| [`30f66eaa`](https://github.com/nix-community/home-manager/commit/30f66eaa3209e13f32f98df5a150542b …

chore(flake/home-manager): `6c3a7a0b` -> `ad48eb25`

---

flake.lock

| [`1cd17a2f`](https://github.com/nix-community/home-manager/commit/1cd17a2f76f7711b06d5d59f1746cef602974498) | `` mangohud: fix a non-working example ``                |
| [`3a7fc9cd`](https://github.com/nix-community/home-manager/commit/3a7fc9cd71a844aae9c6b6bb44700cea9539bc13) | `` zsh: make autosuggest strategy accept more options `` |

chore(flake/home-manager): `ad48eb25` -> `1cd17a2f`

---

flake.lock

| Commit                                                                                                   | Message                                               |
| -------------------------------------------------------------------------------------------------------- | ----------------------------------------------------- |
| [`f65dd240`](https://github.com/lovesegfault/vim-config/commit/f65dd240bfd24bb89f916e30ed5a14ee662d5113) | `` chore(flake/flake-compat): 9ed2ac15 -> ff81ac96 `` |
| [`ece365f3`](https://github.com/lovesegfault/vim-config/commit/ece365f32c3435e0dbbdd938a07544fc1a3cb268) | `` chore(flake/flake-parts): e37654df -> 205b12d8 ``  |
| [`0be8f660`](https://github.com/lovesegfault/vim-config/commit/0be8f6606bf6e88f4ed8ee5a8de62d7389062e97) | `` chore(flake/git-hooks): …

chore(flake/lovesegfault-vim-config): `31b6caaa` -> `f65dd240`

---

flake.lock

| Commit                                                                                           | Message                                      |
| ------------------------------------------------------------------------------------------------ | -------------------------------------------- |
| [`55d46b89`](https://github.com/LnL7/nix-darwin/commit/55d46b8997e16e52d8a05232f4444124e04ba686) | `` test(aerospace): assert config values ``  |
| [`9a595560`](https://github.com/LnL7/nix-darwin/commit/9a5955601847c728ffb98e70b89a359390b24d28) | `` fix(aerospace): allow startup commands `` |

chore(flake/darwin): `e7a71f8e` -> `55d07816`

---

flake.lock

| [`0daaded6`](https://github.com/nix-community/home-manager/commit/0daaded612b0e6eaed0a63fc9d0778d8f05940fe) | `` starship: replace `eval` with `source` for fish ``   |
| [`86ee1290`](https://github.com/nix-community/home-manager/commit/86ee1290d76bcd5f7ee6c80f181288a28ab0dca0) | `` starship: add `enableInteractive` option for fish `` |

chore(flake/home-manager): `1cd17a2f` -> `0daaded6`

---

flake.lock

| [`f6a7af7c`](https://github.com/lovesegfault/vim-config/commit/f6a7af7c2778d33e6af87fba796ba52bdf7a0671) | `` chore(flake/nixvim): 78bfbf7b -> 277dbeb6 `` |

chore(flake/lovesegfault-vim-config): `f65dd240` -> `f6a7af7c`

---

flake.lock

| [`65912bc6`](https://github.com/nix-community/home-manager/commit/65912bc6841cf420eb8c0a20e03df7cbbff5963f) | `` imapnotify: provide an option for setting PATH `` |

chore(flake/home-manager): `0daaded6` -> `65912bc6`

---

flake.lock

| [`eb918dbf`](https://github.com/danth/stylix/commit/eb918dbffa24c4dae497f3ce3173660f948d5237) | `` doc: standardize license formatting (#661) ``            |
| [`32882de1`](https://github.com/danth/stylix/commit/32882de122465d5ac9d4cf0b08b969c879334bc7) | `` doc: update copyright and include contributors (#659) `` |

chore(flake/stylix): `ffba1f1b` -> `eb918dbf`

---

flake.lock

| [`7e54a93a`](https://github.com/numtide/treefmt-nix/commit/7e54a93a3ba74f971779b73ef62d787aa54c9099) | `` feat: update nixpkgs input `` |

chore(flake/treefmt-nix): `49717b5a` -> `50862ba6`

---

flake.lock

| [`6e588a35`](https://github.com/lovesegfault/vim-config/commit/6e588a355abd70a574a75bfd62b801b75495f090) | `` chore(flake/nixvim): 277dbeb6 -> 6348336d ``      |
| [`e56ef329`](https://github.com/lovesegfault/vim-config/commit/e56ef3297b442a1c78f71f8f9bd1b0a9cf3bc161) | `` chore(flake/treefmt-nix): 49717b5a -> 50862ba6 `` |

chore(flake/lovesegfault-vim-config): `f6a7af7c` -> `6e588a35`

---

flake.lock

| [`d00c6f6d`](https://github.com/nix-community/home-manager/commit/d00c6f6d0ad16d598bf7e2956f52c1d9d5de3c3a) | `` nix: simplify tests ``                   |
| [`63eb786e`](https://github.com/nix-community/home-manager/commit/63eb786e047fbb101041103f86162cd72d105d79) | `` xresources: simplify tests ``            |
| [`0b42cc1b`](https://github.com/nix-community/home-manager/commit/0b42cc1b1c7a38f32334f217eadbc7b83b3ef44c) | `` cmus: reduce test closure ``             |
| …

chore(flake/home-manager): `65912bc6` -> `d00c6f6d`

---

flake.lock

| Commit                                                                                        | Message                                                                      |
| --------------------------------------------------------------------------------------------- | ---------------------------------------------------------------------------- |
| [`c6547e2b`](https://github.com/danth/stylix/commit/c6547e2b2685db495c70b1f54dc08b6ed31b9a7b) | `` hyprland: remove with statement ``                                        |
| [`5282744c`](https://github.com/danth/stylix/commit/5282744c3439eac8db271ad1c6f3692ca04d4776) | `` hyprland: reduce local variable scopes ``                                 |
| [`638f30a6`](https://github.com/danth/stylix/commit/638f30a67e938495adfc992aa025b4b00bf3f4 …

chore(flake/stylix): `eb918dbf` -> `e309d64f`

---

flake.lock

| Commit                                                                                                   | Message                                           |
| -------------------------------------------------------------------------------------------------------- | ------------------------------------------------- |
| [`bea76622`](https://github.com/lovesegfault/vim-config/commit/bea76622d3205e336077cd2d347f0945c7830172) | `` refactor: replace whitespace-nvim with trim `` |
| [`1bdab40b`](https://github.com/lovesegfault/vim-config/commit/1bdab40b5713073c8f4e2f71ffc68ce4452412e1) | `` refactor: use vim-suda option ``               |

chore(flake/lovesegfault-vim-config): `6e588a35` -> `bea76622`

---

flake.lock
hosts/spinoza/sway.nix

| Commit                                                                                         | Message                                                                                                                      |
| ---------------------------------------------------------------------------------------------- | ---------------------------------------------------------------------------------------------------------------------------- |
| [`897a55c3`](https://github.com/NixOS/nixpkgs/commit/897a55c324ae42633aeabe78d7c3a413e547c438) | `` hyprlauncher: 0.2.2 -> 0.2.7 ``                                                                                           |
| [`57efa159`](https://github.com/NixOS/nixpkgs/commit/57efa159d816a2229cb5d2a8a3e2ec1db850c373) | `` jq-lsp: 0.1.4 -> …

chore(flake/nixpkgs): `55d15ad1` -> `d0797a04`

---

flake.lock

| [`3f031c16`](https://github.com/lovesegfault/vim-config/commit/3f031c16dd24f3b20b88f9ccdd4ce860bda6c356) | `` chore(flake/nixpkgs): 55d15ad1 -> d0797a04 `` |
| [`0aed2594`](https://github.com/lovesegfault/vim-config/commit/0aed25943a4d1c8e71341660fa140b740852bd18) | `` chore(flake/nixvim): 6348336d -> ae78face ``  |

chore(flake/lovesegfault-vim-config): `bea76622` -> `3f031c16`

---

flake.lock

| Commit                                                                                           | Message                                                                     |
| ------------------------------------------------------------------------------------------------ | --------------------------------------------------------------------------- |
| [`8752b6ae`](https://github.com/LnL7/nix-darwin/commit/8752b6ae3c0d6b44ca4ef28e50503f8efcec0096) | `` github-runner: add instructions for triggering a runner registration ``  |
| [`22cde06f`](https://github.com/LnL7/nix-darwin/commit/22cde06f497b97cbab4186292f9fd82487bbfecc) | `` github-runner: fix service not starting ``                               |
| [`06e1d770`](https://github.com/LnL7/nix-darwin/commit/06e1d770687a832a13aa23f37cd …

chore(flake/darwin): `55d07816` -> `a35b08d0`

---

flake.lock

| [`f1e477a7`](https://github.com/nix-community/nix-index-database/commit/f1e477a7dd11e27e7f98b646349cd66bbabf2fb8) | `` update generated.nix to release 2024-12-08-032901 `` |
| [`871d3049`](https://github.com/nix-community/nix-index-database/commit/871d304912084543002cd90a32d5ccc3f88b30f5) | `` flake.lock: Update ``                                |

chore(flake/nix-index-database): `6e0b7f81` -> `f1e477a7`

---

flake.lock

| [`629be24f`](https://github.com/numtide/treefmt-nix/commit/629be24f6330f013b013a61abe2d866e43c87aba) | `` escape names in formatter names `` |

chore(flake/treefmt-nix): `50862ba6` -> `357cda84`

---

flake.lock

| Commit                                                                                         | Message                                                                                  |
| ---------------------------------------------------------------------------------------------- | ---------------------------------------------------------------------------------------- |
| [`882ff1b9`](https://github.com/NixOS/nixpkgs/commit/882ff1b923f74821589dd571d6a9e9b955f42fc6) | `` satellite: 0.5.0 -> 0.9.0 ``                                                          |
| [`6ad564a3`](https://github.com/NixOS/nixpkgs/commit/6ad564a324d33163e41fcc8d5aeff42b9c14b260) | `` satellite: refactor ``                                                                |
| …

chore(flake/nixpkgs): `d0797a04` -> `22c3f2cf`

---

flake.lock

| [`53a8da6b`](https://github.com/lovesegfault/vim-config/commit/53a8da6b44738cdcbecbee9a2833b9781947afb0) | `` chore(flake/nixpkgs): d0797a04 -> 22c3f2cf `` |

chore(flake/lovesegfault-vim-config): `f22e494d` -> `53a8da6b`

---

flake.lock

| [`9ebaa80a`](https://github.com/nix-community/home-manager/commit/9ebaa80a227eaca9c87c53ed515ade013bc2bca9) | `` thunderbird: set the correct SMTP server for aliases (#6177) `` |
| [`f63c15c1`](https://github.com/nix-community/home-manager/commit/f63c15c137f9e446af897c15218c1af9f06d91ad) | `` isync/mbsync: update module for 1.5.0 changes (#5918) ``        |

chore(flake/home-manager): `d00c6f6d` -> `9ebaa80a`

---

flake.lock

| Commit                                                                                               | Message                                                             |
| ---------------------------------------------------------------------------------------------------- | ------------------------------------------------------------------- |
| [`0ce9d149`](https://github.com/numtide/treefmt-nix/commit/0ce9d149d99bc383d1f2d85f31f6ebd146e46085) | `` 🆙 Include all opentofu-compatible files for Terraform (#275) `` |

chore(flake/treefmt-nix): `357cda84` -> `0ce9d149`

---

flake.lock

| Commit                                                                                                  | Message                                      |
| ------------------------------------------------------------------------------------------------------- | -------------------------------------------- |
| [`d5024d07`](https://github.com/tinted-theming/schemes/commit/d5024d07713029d21aa45263e164913a0dfab0b6) | `` Update Deep Oceanic Next colors  (#37) `` |

chore(flake/tinted-schemes): `61058a8d` -> `d5024d07`

---

flake.lock

| [`17d9c1ac`](https://github.com/lovesegfault/vim-config/commit/17d9c1acdbe50b14d7be7e5d329e73a6d11200d6) | `` chore(flake/nixvim): 4b5364a6 -> cf7e026c ``      |
| [`d3fe8aea`](https://github.com/lovesegfault/vim-config/commit/d3fe8aead4d6936430a0b3b3c0810f213192fc8d) | `` chore(flake/treefmt-nix): 357cda84 -> 0ce9d149 `` |

chore(flake/lovesegfault-vim-config): `53a8da6b` -> `17d9c1ac`

---

flake.lock

| [`e952e949`](https://github.com/nix-community/home-manager/commit/e952e94955dcc6fa2120c1430789fc41363f5237) | `` atuin: Prepare for daemon socket path in 18.4.0 ``       |
| [`77a792a0`](https://github.com/nix-community/home-manager/commit/77a792a0418227e69a2ba26728b47f2b8cf3b6ec) | `` atuin: Do not hard code prefix for daemon socket path `` |

chore(flake/home-manager): `9ebaa80a` -> `e952e949`

---

flake.lock

| [`5a69e8c6`](https://github.com/danth/stylix/commit/5a69e8c65787a962cb3b7ebd855942029a8cba5a) | `` ci: fix typo in target branch placeholder `` |
| [`b08769f6`](https://github.com/danth/stylix/commit/b08769f64e6f82a619abb44420539c93aaa2882a) | `` ci: implement automated backports (#664) ``  |
| [`23d9debf`](https://github.com/danth/stylix/commit/23d9debfdc43c996a1b0de94ebee0e2cde5ad79a) | `` vscode: extensive fonts ``                   |

chore(flake/stylix): `e309d64f` -> `5a69e8c6`

---

flake.lock

| Commit                                                                                        | Message                                                                |
| --------------------------------------------------------------------------------------------- | ---------------------------------------------------------------------- |
| [`bc25f3d6`](https://github.com/danth/stylix/commit/bc25f3d69d3bb54548b772d7c2771e65cc37dc10) | `` emacs: set font for all frames, not just for new ones (#656) ``     |
| [`dd6605be`](https://github.com/danth/stylix/commit/dd6605be798b52bf588dadfda4431acf4145c1ed) | `` doc: encourage adding testbeds for new modules (#673) ``            |
| [`81148743`](https://github.com/danth/stylix/commit/81148743b9de7a5764c29f64bb9f388d0cea030e) | `` doc: remove …

chore(flake/stylix): `5a69e8c6` -> `bc25f3d6`

---

flake.lock

| [`cf737e2e`](https://github.com/NixOS/nixos-hardware/commit/cf737e2eba82b603f54f71b10cb8fd09d22ce3f5) | `` apple/t2: kernel 6.12.2 -> 6.12.4 `` |

chore(flake/nixos-hardware): `e563803a` -> `cf737e2e`

---

flake.lock

| [`6a25f0a9`](https://github.com/lovesegfault/vim-config/commit/6a25f0a9cb4bafe61400c35d825a175fda8a61ce) | `` chore(flake/nixpkgs): 22c3f2cf -> a73246e2 `` |
| [`ec2bf001`](https://github.com/lovesegfault/vim-config/commit/ec2bf00135de6a75e9e8ffe5969b4cf9dc1b500a) | `` chore(flake/nixvim): cf7e026c -> b7526066 ``  |

chore(flake/lovesegfault-vim-config): `17d9c1ac` -> `6a25f0a9`

---

flake.lock

| [`f26aa4b7`](https://github.com/nix-community/home-manager/commit/f26aa4b76fb7606127032d33ac73d7d507d82758) | `` gpg-agent: fix GCR DBus package note ``          |
| [`c6a5fbfd`](https://github.com/nix-community/home-manager/commit/c6a5fbfd99bccfafbe99a6bb87b351c8fb7de70a) | `` qt: install kio when qt.platformTheme = "kde" `` |
| [`8772bae5`](https://github.com/nix-community/home-manager/commit/8772bae58c0a1390727aaf13802debfa29757d67) | `` nushell: allow …

chore(flake/home-manager): `e952e949` -> `f26aa4b7`

---

flake.lock

| [`6e5b2d9e`](https://github.com/nix-community/home-manager/commit/6e5b2d9e8014b5572e3367937a329e7053458d34) | `` home-manager: support username with special chars (#5609) `` |

chore(flake/home-manager): `f26aa4b7` -> `6e5b2d9e`

---

flake.lock

| [`5dbe71fa`](https://github.com/lovesegfault/vim-config/commit/5dbe71fa4e1e59aedbb62e4e4003d59bc1349d8c) | `` chore(flake/nixvim): b7526066 -> c7b109f5 `` |

chore(flake/lovesegfault-vim-config): `6a25f0a9` -> `5dbe71fa`

---

flake.lock

| [`9c74188e`](https://github.com/nix-community/disko/commit/9c74188ec6ab9c7abbc6aa9c6a22413ac4c838a7) | `` flake.lock: Update `` |

chore(flake/disko): `785c1e02` -> `0f31ad73`

---

flake.lock

| Commit                                                                                        | Message                                                                      |
| --------------------------------------------------------------------------------------------- | ---------------------------------------------------------------------------- |
| [`ccee6332`](https://github.com/danth/stylix/commit/ccee633284cde8a9f825004e00dd84a31b10e6c6) | `` ci: prevent unexpected flake.nix and flake.lock inconsistencies (#674) `` |

chore(flake/stylix): `bc25f3d6` -> `ccee6332`

---

flake.lock

| [`15151bb5`](https://github.com/nix-community/home-manager/commit/15151bb5e7d6e352247ecaeeeefc34d0f306b287) | `` gpg: fix hash of test (#6200) `` |

chore(flake/home-manager): `6e5b2d9e` -> `15151bb5`

---

flake.lock

| [`46bc9d6d`](https://github.com/lovesegfault/vim-config/commit/46bc9d6d6c5b4f3c144924fd658f2cd8acb27c14) | `` chore(flake/nixvim): c7b109f5 -> 6fcf389a `` |

chore(flake/lovesegfault-vim-config): `5dbe71fa` -> `46bc9d6d`

---

flake.lock

| [`3066cc58`](https://github.com/nix-community/home-manager/commit/3066cc58f552421a2c5414e78407fa5603405b1e) | `` kanshi: dont write config in absence of nix settings (#6198) `` |
| [`e526fd2b`](https://github.com/nix-community/home-manager/commit/e526fd2b1a40e4ca0b5e07e87b8c960281c67412) | `` gnome-shell: fix extensions' default (#6199) ``                 |

chore(flake/home-manager): `15151bb5` -> `3066cc58`

---

flake.lock

| Commit                                                                                         | Message                                                                                         |
| ---------------------------------------------------------------------------------------------- | ----------------------------------------------------------------------------------------------- |
| [`362f987f`](https://github.com/NixOS/nixpkgs/commit/362f987f977ae628b5299f88f6d76a170ba18df6) | `` codesnap: init at 0.8.2 ``                                                                   |
| [`518ae8fd`](https://github.com/NixOS/nixpkgs/commit/518ae8fd583e3e2ba9bc7c5b3643b3d7823a77aa) | `` ci/eval: add rebuildsByPlatform to the comparison result ``                                  |
| …

chore(flake/nixpkgs): `a73246e2` -> `5d67ea6b`

---

flake.lock

| Commit                                                                                               | Message                                                      |
| ---------------------------------------------------------------------------------------------------- | ------------------------------------------------------------ |
| [`d32f2d17`](https://github.com/nix-community/disko/commit/d32f2d1750d61a476a236526b725ec5a32e16342) | `` release: reset released flag ``                           |
| [`65a44150`](https://github.com/nix-community/disko/commit/65a441502c9382d41ada1adbc9bd31d6c9b00fe2) | `` release: v1.10.0 ``                                       |
| [`a0c967fe`](https://github.com/nix-community/disko/commit/a0c967fef4d74b263610d9087be8efa7b1bdcd04) | `` Add extraArgs to …

chore(flake/disko): `0f31ad73` -> `d32f2d17`

---

flake.lock

| [`66c5d8b6`](https://github.com/nix-community/home-manager/commit/66c5d8b62818ec4c1edb3e941f55ef78df8141a8) | `` zed-editor: fix always generating settings.json `` |

chore(flake/home-manager): `3066cc58` -> `66c5d8b6`

---

flake.lock

| Commit                                                                                        | Message                      |
| --------------------------------------------------------------------------------------------- | ---------------------------- |
| [`a9e37799`](https://github.com/danth/stylix/commit/a9e3779949925ef22f5a215c5f49cf520dea30b1) | `` librewolf: init (#679) `` |

chore(flake/stylix): `ccee6332` -> `a9e37799`

---

flake.lock

| [`07f6d67f`](https://github.com/lovesegfault/vim-config/commit/07f6d67f412633d82822abe5a98fb64c26451a7e) | `` chore(flake/nixpkgs): a73246e2 -> 5d67ea6b `` |
| [`aa1312b9`](https://github.com/lovesegfault/vim-config/commit/aa1312b938271ed48b2443789ba68f9f592bea45) | `` chore(flake/nixvim): 6fcf389a -> c1810144 ``  |

chore(flake/lovesegfault-vim-config): `46bc9d6d` -> `07f6d67f`

---

flake.lock

| [`c6323585`](https://github.com/nix-community/impermanence/commit/c6323585fa0035d780e3d8906eb1b24b65d19a48) | `` mount-file: Use findmnt instead of mount `` |

chore(flake/impermanence): `3ed3f0ea` -> `c6323585`

---

flake.lock

| [`311d6cf3`](https://github.com/nix-community/nix-index-database/commit/311d6cf3ad3f56cb051ffab1f480b2909b3f754d) | `` update generated.nix to release 2024-12-15-032933 `` |
| [`ad035087`](https://github.com/nix-community/nix-index-database/commit/ad03508704b42d0a0b9acb79978965e2f2373bbe) | `` flake.lock: Update ``                                |

chore(flake/nix-index-database): `f1e477a7` -> `311d6cf3`

---

flake.lock

| [`3e7d7910`](https://github.com/cachix/git-hooks.nix/commit/3e7d791061be477b20a9d4e1f57872a51a392a57) | `` bugfix: remove before/after options from config json file `` |

chore(flake/git-hooks): `c2b3567b` -> `4c8e75ef`

---

flake.lock

| Commit                                                                                                | Message                                                                                |
| ----------------------------------------------------------------------------------------------------- | -------------------------------------------------------------------------------------- |
| [`2c69d710`](https://github.com/cachix/git-hooks.nix/commit/2c69d710c20b8856e18d01fd4f6d265175167eec) | `` chore: add a default priority to `cabal2nix` which ensures it runs after `hpack` `` |
| [`8a8d2b81`](https://github.com/cachix/git-hooks.nix/commit/8a8d2b81f465bb693c676a285f1ba93b4d3a8931) | `` make sure that clang-tools is in the same version across all platforms ``           |

chore(flake/git-hooks): `4c8e75ef` -> `aa9f40c9`

---

flake.lock

| [`56456210`](https://github.com/NixOS/nixpkgs/commit/56456210e9bfc57dbc3f33846e40770bc2c8498f) | `` blender: 4.3.0 -> 4.3.1 (#364446) ``                                         |
| [`bef38c59`](https://github.com/NixOS/nixpkgs/commit/bef38c59f3f4f14ba7cdce2dd85aefe607139a7d) | `` melonDS: 1.0rc-unstable-2024-11-27 -> 1.0rc-unstable-2024-12-05 (#364697) `` |
| [`5c941d44`](https://github.com/NixOS/nixpkgs/commit/5c941d4463d46b982fb9a …

chore(flake/nixpkgs): `5d67ea6b` -> `3566ab72`

---

flake.lock

| Commit                                                                                               | Message                                    |
| ---------------------------------------------------------------------------------------------------- | ------------------------------------------ |
| [`dcd15a37`](https://github.com/nix-community/disko/commit/dcd15a37f7496aab14ea46789d606dbb326a0e37) | `` make-disk-image fix virtiofs support `` |
| [`d3e3aa7a`](https://github.com/nix-community/disko/commit/d3e3aa7a1413f24367b6ab375b823e5c1fefc560) | `` flake.lock: Update ``                   |

chore(flake/disko): `d32f2d17` -> `a08bfe06`

---

flake.lock

| [`83ecd509`](https://github.com/nix-community/home-manager/commit/83ecd50915a09dca928971139d3a102377a8d242) | `` docs: fix typo in 24.11 release notes `` |

chore(flake/home-manager): `66c5d8b6` -> `83ecd509`

---

flake.lock

| [`b12e3147`](https://github.com/NixOS/nixos-hardware/commit/b12e314726a4226298fe82776b4baeaa7bcf3dcd) | `` microsoft/surface: Update to kernel 6.12.4 `` |

chore(flake/nixos-hardware): `cf737e2e` -> `b12e3147`

---

flake.lock

| [`45a887c6`](https://github.com/lovesegfault/vim-config/commit/45a887c6afd59d23d1d5b5c8c8fded398adb7632) | `` chore(flake/git-hooks): aa9f40c9 -> 0bb4be58 `` |

chore(flake/lovesegfault-vim-config): `e267046a` -> `45a887c6`

---

flake.lock

| [`11302530`](https://github.com/lovesegfault/vim-config/commit/11302530858aafe9e457a0535961e7dcdfd7219a) | `` chore(flake/git-hooks): 0bb4be58 -> 0ddd26d0 `` |

chore(flake/lovesegfault-vim-config): `45a887c6` -> `11302530`

---

flake.lock

| [`a2d66f25`](https://github.com/danth/stylix/commit/a2d66f25478103ac9b4adc6d6713794f7005221e) | `` treewide: extend stylix.imageScalingMode support `` |

chore(flake/stylix): `a9e37799` -> `a2d66f25`

---

flake.lock

| [`77306ff5`](https://github.com/NixOS/nixpkgs/commit/77306ff547b51e819ba617b140bb355e1d719f31) | `` chore(mergify): remove not relevant Tag check (#365804) ``                       |
| [`e5d90d92`](https://github.com/NixOS/nixpkgs/commit/e5d90d92ae07e4843dcc5a4d8195ec29c96d8e4d) | `` python312Packages.llama-index-multi-modal-llms-openai: 0.3.0 -> 0.4.0 ``         |
| …

chore(flake/nixpkgs): `3566ab72` -> `d3c42f18`

---

flake.lock

| Commit                                                                                               | Message                           |
| ---------------------------------------------------------------------------------------------------- | --------------------------------- |
| [`76159fc7`](https://github.com/numtide/treefmt-nix/commit/76159fc74eeac0599c3618e3601ac2b980a29263) | `` Fix copy-paste error (#279) `` |

chore(flake/treefmt-nix): `0ce9d149` -> `76159fc7`

---

flake.lock

| [`f0d020ef`](https://github.com/lovesegfault/vim-config/commit/f0d020efb7eb9efe094d13f7d05788a5f3ed048c) | `` chore(flake/nixpkgs): 3566ab72 -> d3c42f18 ``     |
| [`4fa79549`](https://github.com/lovesegfault/vim-config/commit/4fa79549cf737f4d114d9d4f813e7d8f73fa6c9c) | `` chore(flake/treefmt-nix): 0ce9d149 -> 76159fc7 `` |

chore(flake/lovesegfault-vim-config): `11302530` -> `f0d020ef`

---

flake.lock

| [`832920a6`](https://github.com/nix-community/home-manager/commit/832920a60833533eaabcc93ab729801bf586fa0c) | `` thunderbird: add profileVersion `` |

chore(flake/home-manager): `83ecd509` -> `832920a6`

---

flake.lock

| [`1395379a`](https://github.com/nix-community/home-manager/commit/1395379a7a36e40f2a76e7b9936cc52950baa1be) | `` home-manager: improve path handling when building news `` |

chore(flake/home-manager): `832920a6` -> `1395379a`

---

flake.lock

| Commit                                                                                               | Message                                               |
| ---------------------------------------------------------------------------------------------------- | ----------------------------------------------------- |
| [`d8f3cfc5`](https://github.com/nix-community/disko/commit/d8f3cfc582356736eac3c46164cfc11a31aa082b) | `` zfs: run load-key on mount ``                      |
| [`60375cf0`](https://github.com/nix-community/disko/commit/60375cf09645dd08f401af187e036771df31ec7e) | `` cli: remove traceValSeq that shouldn't be there `` |
| [`194a9965`](https://github.com/nix-community/disko/commit/194a9965d1531b6be224a249b0398c9dddd60a88) | `` flake.lock: Update `` …

chore(flake/disko): `a08bfe06` -> `2ee76c86`

---

flake.lock

| [`65712f5a`](https://github.com/numtide/treefmt-nix/commit/65712f5af67234dad91a5a4baee986a8b62dbf8f) | `` perltidy: init (#281) `` |

chore(flake/treefmt-nix): `76159fc7` -> `65712f5a`

---

flake.lock

| [`80a71785`](https://github.com/lovesegfault/vim-config/commit/80a717855b4bb3dd7b4df2f30a1024d42b7c7e33) | `` chore(flake/treefmt-nix): 76159fc7 -> 65712f5a `` |

chore(flake/lovesegfault-vim-config): `f0d020ef` -> `80a71785`

---

flake.lock

| [`62aa3abc`](https://github.com/nix-community/impermanence/commit/62aa3abc281b58781908efebb7c42a029294a737) | `` nixos: Fix the machine-id workaround to also work on first boot `` |
| [`ad544a2b`](https://github.com/nix-community/impermanence/commit/ad544a2b324f3960a9fb3c24635f7aeb7ae8e88d) | `` mount-file, create-directories: Remove some unnecessary quoting `` |
| [`0e9480d6`](https://github.com/nix-community/impermanence/com …

chore(flake/impermanence): `c6323585` -> `0ab2f858`

---

flake.lock

| [`f342df3a`](https://github.com/nix-community/home-manager/commit/f342df3ad938f205a913973b832f52c12546aac6) | `` flake.lock: Update ``                    |
| [`db9a98e1`](https://github.com/nix-community/home-manager/commit/db9a98e178b57a8aff46b3482dfccb3f4d8d4ce3) | `` pay-respects: add module ``              |
| [`99f54cdf`](https://github.com/nix-community/home-manager/commit/99f54cdfef395bb3de1c7b8dd422412de65b038d) | `` yazi: fix example option for settings `` |

chore(flake/home-manager): `1395379a` -> `f342df3a`

---

flake.lock

| Commit                                                                                        | Message                                     |
| --------------------------------------------------------------------------------------------- | ------------------------------------------- |
| [`4f489c63`](https://github.com/danth/stylix/commit/4f489c63932f014be856475154bf342f8a40f5ff) | `` vscode: don't round font sizes (#691) `` |

chore(flake/stylix): `a2d66f25` -> `4f489c63`

---

flake.lock

| [`780dddb7`](https://github.com/lovesegfault/vim-config/commit/780dddb71aaf0d68c6b9f5ed02c8c503b7eef484) | `` chore(flake/git-hooks): 0ddd26d0 -> f0f0dc49 `` |

chore(flake/lovesegfault-vim-config): `80a71785` -> `780dddb7`

---

flake.lock

| [`51160a09`](https://github.com/nix-community/home-manager/commit/51160a097a850839b7eae7ef08d0d3e7e353dfc3) | `` thunderbird: implement `extensions` for profiles `` |

chore(flake/home-manager): `f342df3a` -> `51160a09`

---

flake.lock

| [`d583b2d1`](https://github.com/nix-community/nix-index-database/commit/d583b2d142f0428313df099f4a2dcf2a0496aa78) | `` update generated.nix to release 2024-12-22-031612 `` |
| [`af62b107`](https://github.com/nix-community/nix-index-database/commit/af62b10745e18133fbc6ed164baf4846c75ef5d5) | `` flake.lock: Update ``                                |

chore(flake/nix-index-database): `311d6cf3` -> `d583b2d1`

---

flake.lock

| [`f6abeb02`](https://github.com/NixOS/nixos-hardware/commit/f6abeb027b4b874ad5a6fa59c2cfdee71e373a56) | `` raspberry-pi-4: fix devicetree filter `` |
| [`5e6a5463`](https://github.com/NixOS/nixos-hardware/commit/5e6a54633451002608cec7cc999c5ccdecda2c33) | `` raspberry-pi-4: add tv-hat overlay ``    |

chore(flake/nixos-hardware): `b12e3147` -> `e8516a23`

---

flake.lock

| [`cb27edb5`](https://github.com/nix-community/home-manager/commit/cb27edb5221d2f2920a03155f8becc502cf60e35) | `` waybar: add systemd restart triggers `` |
| [`f47b6c15`](https://github.com/nix-community/home-manager/commit/f47b6c153ad31187a519bd569ccbcb20acb16ce0) | `` cavalier: add module ``                 |
| [`c903b1f6`](https://github.com/nix-community/home-manager/commit/c903b1f6fbfc2039963806df896f698331b77aa8) | `` flake.lock: Update ``                   |

chore(flake/home-manager): `51160a09` -> `cb27edb5`

---

flake.lock

| [`aec7be45`](https://github.com/danth/stylix/commit/aec7be45cf896c52c38ee99b7e1a21f4c6d4ccd4) | `` xresources: convert font size to a string `` |
| [`be3a33d5`](https://github.com/danth/stylix/commit/be3a33d58999e92b98152aedcc59238f1c299f87) | `` cava: add rainbow theme option (#638) ``     |
| [`75f38f9e`](https://github.com/danth/stylix/commit/75f38f9edffba44cf2f18f4df89850f9c3cb1ddb) | `` stylix: use floats for font sizes ``         |

chore(flake/stylix): `4f489c63` -> `4d87b96c`

---

flake.lock

| [`1f74238a`](https://github.com/nix-community/home-manager/commit/1f74238a4c8e534a1b6be72cb5153043071ffd17) | `` xresources: allow floating point values `` |

chore(flake/home-manager): `cb27edb5` -> `1f74238a`

---

flake.lock

| [`53dec229`](https://github.com/lovesegfault/vim-config/commit/53dec229c46269ac92849e57cfca09e9fb3f1be2) | `` chore(flake/nixpkgs): d3c42f18 -> d70bd19e `` |

chore(flake/lovesegfault-vim-config): `780dddb7` -> `53dec229`

---

flake.lock

| [`edb8b00e`](https://github.com/nix-community/home-manager/commit/edb8b00e4d17b2116b60eca50f38ac68f12b9ab4) | `` Translate using Weblate (Czech) `` |

chore(flake/home-manager): `1f74238a` -> `edb8b00e`

---

flake.lock

| [`d000479f`](https://github.com/nix-community/impermanence/commit/d000479f4f41390ff7cf9204979660ad5dd16176) | `` ci: Add merge_group to check triggers ``                                     |
| [`fdd77e33`](https://github.com/nix-community/impermanence/commit/fdd77e33769ad3df528a728dc91aaee77f9bccec) | `` nixos: Fix boot for ZFS systems using non-systemd initrd ``                  |
| …

chore(flake/impermanence): `0ab2f858` -> `d000479f`

---

flake.lock

| [`1db3c42d`](https://github.com/NixOS/nixos-hardware/commit/1db3c42d93e460f71f6cfd5ae20e669bc31b9a80) | `` surface: linux 6.12.4 -> 6.12.6 ``                      |
| [`73866b43`](https://github.com/NixOS/nixos-hardware/commit/73866b432618e6c542f45a9057eef6d5ac9a69cb) | `` dell-precision-5560: enable fwupd ``                    |
| [`68283046`](https://github.com/NixOS/nixos-hardware/commit/6828304671c6a1c4d104585887b6a7ad22208a58) | `` dell-precision-5560: …

chore(flake/nixos-hardware): `e8516a23` -> `def1d472`

---

flake.lock

| [`8264bfe3`](https://github.com/nix-community/home-manager/commit/8264bfe3a064d704c57df91e34b795b6ac7bad9e) | `` mu: add integration tests ``                        |
| [`7349b015`](https://github.com/nix-community/home-manager/commit/7349b01505d18cd60ba0e573e78c234b742056ef) | `` mu: reinitialize when personal addresses change ``  |
| [`8bea1a20`](https://github.com/nix-community/home-manager/commit/8bea1a2005c64a8c9c430d0dddb6b2e5db5f6f12) | `` nixgl: …

chore(flake/home-manager): `edb8b00e` -> `8264bfe3`

---

flake.lock

| Commit                                                                                               | Message                                                              |
| ---------------------------------------------------------------------------------------------------- | -------------------------------------------------------------------- |
| [`e41e948c`](https://github.com/numtide/treefmt-nix/commit/e41e948cf097cbf96ba4dff47a30ea6891af9f33) | `` README: fix the formatter example to include the system (#284) `` |

chore(flake/treefmt-nix): `65712f5a` -> `e41e948c`

---

flake.lock

| Commit                                                                                                   | Message                                                |
| -------------------------------------------------------------------------------------------------------- | ------------------------------------------------------ |
| [`47eeafce`](https://github.com/lovesegfault/vim-config/commit/47eeafce89ce74e41c8c8e7a282959669700d7e8) | `` fix: enableSurround -> settings.surround_enabled `` |
| [`622781a7`](https://github.com/lovesegfault/vim-config/commit/622781a7fe37e7ae3608ff5d5b8dbc280589fa3c) | `` chore(flake/nixvim): ec24d496 -> 450cccf4 ``        |

chore(flake/lovesegfault-vim-config): `53dec229` -> `47eeafce`

---

flake.lock

| Commit                                                                                                    | Message                                               |
| --------------------------------------------------------------------------------------------------------- | ----------------------------------------------------- |
| [`9f2c57f2`](https://github.com/nix-community/lanzaboote/commit/9f2c57f2b3e9010ce54e259100ca37ec9de3b6f0) | `` docs: Use new pkiBundle default location ``        |
| [`7cec007d`](https://github.com/nix-community/lanzaboote/commit/7cec007ddc45d8887f79f151c0de1a900e22c4a3) | `` docs: Add Framework Core Ultra Series 1 warning `` |

chore(flake/lanzaboote): `26a59c1b` -> `93e6f0d7`

---

flake.lock

| [`f1b1786e`](https://github.com/nix-community/home-manager/commit/f1b1786ea77739dcd181b920d430e30fb1608b8a) | `` swayr: avoid IFD `` |

chore(flake/home-manager): `8264bfe3` -> `f1b1786e`

---

flake.lock

| [`79690a9a`](https://github.com/lovesegfault/vim-config/commit/79690a9a76d0a328ab56407c459ff617d4175397) | `` chore(flake/nixvim): 450cccf4 -> 8938e09d ``      |
| [`f69c1728`](https://github.com/lovesegfault/vim-config/commit/f69c17281ff692a1c669c28b969f82bea37db018) | `` chore(flake/treefmt-nix): 65712f5a -> e41e948c `` |

chore(flake/lovesegfault-vim-config): `47eeafce` -> `79690a9a`

---

flake.lock

| [`35b98d20`](https://github.com/nix-community/home-manager/commit/35b98d20ca8f4ca1f6a2c30b8a2c8bb305a36d84) | `` treewide: change pacien to euxane ``        |
| [`afbf007b`](https://github.com/nix-community/home-manager/commit/afbf007bb5e05b7837be5485e221ea50c4fd4f1b) | `` tests: add integration test for nh ``       |
| [`64272584`](https://github.com/nix-community/home-manager/commit/64272584091a47e3762d1bfb40638fbe58dd756d) | `` tests: change to wait for network.target …

chore(flake/home-manager): `f1b1786e` -> `35b98d20`

---

flake.lock

| [`9e09d30a`](https://github.com/numtide/treefmt-nix/commit/9e09d30a644c57257715902efbb3adc56c79cf28) | `` sqruff: init (#283) `` |

chore(flake/treefmt-nix): `e41e948c` -> `9e09d30a`

---

flake.lock

| Commit                                                                                        | Message                                                               |
| --------------------------------------------------------------------------------------------- | --------------------------------------------------------------------- |
| [`079feceb`](https://github.com/danth/stylix/commit/079fecebad5f616561726359c89cedd811c8a722) | `` firefox: leverage Home Manager's mkFirefoxModule pattern (#695) `` |
| [`a70154ec`](https://github.com/danth/stylix/commit/a70154ec03034cfd1a88868dc0259456fc618435) | `` doc: resolve 'magick convert' deprecation warning (#697) ``        |

chore(flake/stylix): `4d87b96c` -> `079feceb`

---

flake.lock

| [`c9e56673`](https://github.com/lovesegfault/vim-config/commit/c9e56673fb96157812f3c06da4a08908184db932) | `` chore(flake/treefmt-nix): e41e948c -> 9e09d30a `` |
| [`dec5f6b8`](https://github.com/lovesegfault/vim-config/commit/dec5f6b832fd801cb71a956c930b237d938bd5f3) | `` chore(flake/nixvim): 8938e09d -> ca3c7e29 ``      |

chore(flake/lovesegfault-vim-config): `79690a9a` -> `c9e56673`

---

flake.lock

| [`c8470746`](https://github.com/nix-community/nix-index-database/commit/c8470746a9f4d1ab4c7563db7da995595ed64ca2) | `` update generated.nix to release 2024-12-25-204532 `` |
| [`f3ea8bd1`](https://github.com/nix-community/nix-index-database/commit/f3ea8bd11b980aefb1324b0d71d7aee09db1c0a8) | `` set small db as default for comma ``                 |
| [`07f7fcb8`](https://github.com/nix-community/nix-index-database/commit/07f7fcb8de6ee50a472a11 …

chore(flake/nix-index-database): `d583b2d1` -> `c8470746`

---

flake.lock

| Commit                                                                                                            | Message                                                          |
| ----------------------------------------------------------------------------------------------------------------- | ---------------------------------------------------------------- |
| [`e609cc6e`](https://github.com/nix-community/nix-index-database/commit/e609cc6e0f9037b2bb02bd1104afcc1f6f936d33) | `` Revert "update generated.nix to release 2024-12-25-204532" `` |

chore(flake/nix-index-database): `c8470746` -> `02dadaef`

---

flake.lock

| Commit                                                                                           | Message                                    |
| ------------------------------------------------------------------------------------------------ | ------------------------------------------ |
| [`2c86af2e`](https://github.com/LnL7/nix-darwin/commit/2c86af2e996ac6abbf9e1711f36c28d33b328df6) | `` programs.ssh: add extraConfig option `` |

chore(flake/darwin): `a35b08d0` -> `bc03f781`

---

flake.lock

| [`7e3246f6`](https://github.com/nix-community/nix-index-database/commit/7e3246f6ad43b44bc1c16d580d7bf6467f971530) | `` update generated.nix to release 2024-12-26-140211 `` |
| [`0a961f69`](https://github.com/nix-community/nix-index-database/commit/0a961f691c4da1e7edc0c23afd6e8d6765499ce0) | `` Omit symlinks to avoid a file collision ``           |

chore(flake/nix-index-database): `02dadaef` -> `7e3246f6`

---

flake.lock

| [`963e77a3`](https://github.com/danth/stylix/commit/963e77a3a4fc2be670d5a9a6cbeb249b8a43808a) | `` gtk: add support for theming Flatpak applications (#693) `` |

chore(flake/stylix): `079feceb` -> `963e77a3`

---

flake.lock

| [`8ff05bc4`](https://github.com/lovesegfault/vim-config/commit/8ff05bc4388dd47c31cbc5022cc8f9b8db9c7aef) | `` chore(flake/nixvim): ca3c7e29 -> 1671f861 `` |

chore(flake/lovesegfault-vim-config): `c9e56673` -> `8ff05bc4`

---

flake.lock

| [`b7a7cd5d`](https://github.com/nix-community/home-manager/commit/b7a7cd5dd1a74a9fe86ed4e016f91c78483b527a) | `` pqiv: fix condition for writing pqivrc file `` |
| [`19398e50`](https://github.com/nix-community/home-manager/commit/19398e505a80db1a1c41207ee89e1b1770c5dcf6) | `` lesspipe: allow configuring package ``         |

chore(flake/home-manager): `35b98d20` -> `b7a7cd5d`

---

flake.lock

| [`85f8af0e`](https://github.com/lovesegfault/vim-config/commit/85f8af0ea5f15bbb2d9b5d76671e59fd199f94e5) | `` chore(flake/nixvim): 1671f861 -> 0307cdf2 `` |

chore(flake/lovesegfault-vim-config): `8ff05bc4` -> `85f8af0e`

---

flake.lock

| [`7c674c67`](https://github.com/NixOS/nixos-hardware/commit/7c674c6734f61157e321db595dbfcd8523e04e19) | `` surface: linux 6.12.6 -> 6.12.7 `` |

chore(flake/nixos-hardware): `def1d472` -> `7c674c67`

---

flake.lock

| Commit                                                                                           | Message                                                          |
| ------------------------------------------------------------------------------------------------ | ---------------------------------------------------------------- |
| [`daf9d9fe`](https://github.com/LnL7/nix-darwin/commit/daf9d9fe5d5a7a5ef25aa446582f8c656aab2b9b) | `` fix(zsh): correct the path of zsh-fast-syntax-highlighting `` |
| [`2165857a`](https://github.com/LnL7/nix-darwin/commit/2165857a24668cc3cb09c052eb0d518a1dfa6d3f) | `` fish: add package option ``                                   |

chore(flake/darwin): `bc03f781` -> `53a0c2fe`

---

flake.lock

| [`8358582d`](https://github.com/lovesegfault/vim-config/commit/8358582d71d384ba13d353f471e6cc174aafbeab) | `` chore(flake/nixvim): 0307cdf2 -> f4b0b81e `` |

chore(flake/lovesegfault-vim-config): `85f8af0e` -> `8358582d`

---

flake.lock

| [`55ab1e1d`](https://github.com/nix-community/nix-index-database/commit/55ab1e1df5daf2476e6b826b69a82862dcbd7544) | `` update generated.nix to release 2024-12-29-031725 `` |
| [`6d3f0273`](https://github.com/nix-community/nix-index-database/commit/6d3f02734423ba59679a15f529b95da15d265d0e) | `` flake.lock: Update ``                                |

chore(flake/nix-index-database): `7e3246f6` -> `55ab1e1d`

---

flake.lock

| [`7d9940a4`](https://github.com/nix-community/disko/commit/7d9940a4df94ac45f328808482673be126b34ef7) | `` doc: simple xfs with options `` |

chore(flake/disko): `3a4de9fa` -> `84a5b936`

---

flake.lock

| [`b8e184eb`](https://github.com/LnL7/nix-darwin/commit/b8e184ebf271367cf1c93d942e71ae51d2a248cb) | `` refactor: use enum as option type ``         |
| [`19bc0d6c`](https://github.com/LnL7/nix-darwin/commit/19bc0d6cbeacb20c5ca865d06c274152c42ffd22) | `` tests: add screencapture.target test case `` |
| [`25fb5271`](https://github.com/LnL7/nix-darwin/commit/25fb52710582c19ad811d1ac9a2fe9d8920c0a66) | `` feat: add screencapture.target option ``     |

chore(flake/darwin): `53a0c2fe` -> `713da7b7`

---

flake.lock

| Commit                                                                                           | Message                                                                                                 |
| ------------------------------------------------------------------------------------------------ | ------------------------------------------------------------------------------------------------------- |
| [`aefd56bb`](https://github.com/LnL7/nix-darwin/commit/aefd56bb562b26ae799e261b1ead27682bf0d8ff) | `` aerospace: add workspace-to-monitor-force-assignment option and fix on-window-detected type #1208 `` |

chore(flake/darwin): `713da7b7` -> `71a3a075`

---

flake.lock

| [`defb43d4`](https://github.com/danth/stylix/commit/defb43d450dfc472682e64749334bd6f9ade91a5) | `` zathura: add testbed ``                          |
| [`6741c2ef`](https://github.com/danth/stylix/commit/6741c2ef6cb881acaf6904c6dc1a6a5cd181994f) | `` wezterm: add testbed ``                          |
| [`efb0e6f5`](https://github.com/danth/stylix/commit/efb0e6f59d0b8df5539acb239cd757402ba845b9) | `` vesktop: add testbed ``                          |
| …

chore(flake/stylix): `963e77a3` -> `71eea3f0`

---

flake.lock

| [`a4ed4168`](https://github.com/danth/stylix/commit/a4ed4168fb83289374f24cb8a039c6983637a076) | `` foot: update desktop file name in testbed (#707) `` |

chore(flake/stylix): `71eea3f0` -> `a4ed4168`

---

flake.lock

| Commit                                                                                               | Message                                           |
| ---------------------------------------------------------------------------------------------------- | ------------------------------------------------- |
| [`942ec968`](https://github.com/numtide/treefmt-nix/commit/942ec9683c8645af5ee5fd9088a413db41ff91d5) | `` README: count the number of programs (#286) `` |
| [`1deca81a`](https://github.com/numtide/treefmt-nix/commit/1deca81ad14b383a32db518af97af3ae3b77f8ed) | `` feat: add 'goimports' formatter (#285) ``      |

chore(flake/treefmt-nix): `9e09d30a` -> `942ec968`

---

flake.lock

| [`472a8823`](https://github.com/lovesegfault/vim-config/commit/472a8823da2a56602111f6b4232609c1654ea8e3) | `` chore(flake/nixvim): f4b0b81e -> c04dda02 `` |

chore(flake/lovesegfault-vim-config): `8358582d` -> `472a8823`

---

flake.lock

| [`56c0ecd7`](https://github.com/numtide/treefmt-nix/commit/56c0ecd79f7ba01a0ec027da015df751d6ca3ae7) | `` schema: add global.on-unmatched option ``       |
| [`d7f8fa42`](https://github.com/numtide/treefmt-nix/commit/d7f8fa424443db3f5e518811c89e0f9c2033c997) | `` fmt: enable deadnix ``                          |
| [`3b6b91ef`](https://github.com/numtide/treefmt-nix/commit/3b6b91ef00f5fb4ab1e09cd4872e91e86c72e4e9) | `` fmt: fix check ``                               |
| …

chore(flake/treefmt-nix): `942ec968` -> `56c0ecd7`

---

flake.lock

| [`bc9bb1af`](https://github.com/lovesegfault/vim-config/commit/bc9bb1af8d66bac3d96f00b5ff9bc3619fb71243) | `` chore(flake/nixvim): 7896856d -> 81c1ef20 ``      |
| [`37745e16`](https://github.com/lovesegfault/vim-config/commit/37745e16c23c35b95e771d47dbcd8c7ec1ec24e4) | `` chore(flake/flake-parts): f2f7418c -> b905f6fc `` |
| [`b0eedcb3`](https://github.com/lovesegfault/vim-config/commit/b0eedcb3b7e963bc96f5ce793ca0d59e05c96d7e) | `` chore(flake/treefmt-nix): …

chore(flake/lovesegfault-vim-config): `472a8823` -> `bc9bb1af`

---

flake.lock

| Commit                                                                                               | Message                                                                                 |
| ---------------------------------------------------------------------------------------------------- | --------------------------------------------------------------------------------------- |
| [`13c913f5`](https://github.com/numtide/treefmt-nix/commit/13c913f5deb3a5c08bb810efd89dc8cb24dd968b) | `` odinfmt: init (#296) ``                                                              |
| [`1788ca5a`](https://github.com/numtide/treefmt-nix/commit/1788ca5acd4b542b923d4757d4cfe4183cc6a92d) | `` mdformat: maintainer add; add settings: `end-of-line`, `number`, `wrapper` (#294) `` |
| …

chore(flake/treefmt-nix): `56c0ecd7` -> `13c913f5`

---

flake.lock

| [`816a6ae8`](https://github.com/nix-community/nix-index-database/commit/816a6ae88774ba7e74314830546c29e134e0dffb) | `` update generated.nix to release 2025-01-05-031613 `` |
| [`ff2883e9`](https://github.com/nix-community/nix-index-database/commit/ff2883e99aa3ab84e1cea129c0aad4f4b6dd1fec) | `` flake.lock: Update ``                                |

chore(flake/nix-index-database): `55ab1e1d` -> `816a6ae8`

---

flake.lock

| Commit                                                                                               | Message                                                        |
| ---------------------------------------------------------------------------------------------------- | -------------------------------------------------------------- |
| [`5be012e9`](https://github.com/nix-community/disko/commit/5be012e91700ee3549fa2da481207ac715667652) | `` fix: Apply umask=0077 to /boot partition in all examples `` |
| [`c315045f`](https://github.com/nix-community/disko/commit/c315045f42b9be08d0a2af299c4f2335f7819c54) | `` flake.lock: Update ``                                       |

chore(flake/disko): `84a5b936` -> `49f8aa79`

---

flake.lock

| [`20665c6e`](https://github.com/nix-community/home-manager/commit/20665c6efa83d71020c8730f26706258ba5c6b2a) | `` home-manager: remove path: URI type for flake default `` |
| [`172b91bf`](https://github.com/nix-community/home-manager/commit/172b91bfb2b7f5c4a8c6ceac29fd53a01ef07196) | `` Translate using Weblate (German) ``                      |
| [`4795ebe6`](https://github.com/nix-community/home-manager/commit/4795ebe6cc6e5f60a3e66e3627b4f182ac47 …

chore(flake/home-manager): `10e99c43` -> `20665c6e`

---

flake.lock

| [`a06a8b2c`](https://github.com/Mic92/nix-fast-build/commit/a06a8b2c079f7b6dab491a12555387bdb737cc44) | `` flake.lock: Update ``                                          |
| [`19e76bc7`](https://github.com/Mic92/nix-fast-build/commit/19e76bc7cad95248befdce9c86fb6e1e088056c6) | `` mergify: delete old merge branches ``                          |
| [`908c3aca`](https://github.com/Mic92/nix-fast-build/commit/908c3aca3486120a575b6057bcddef07a810224f) …

chore(flake/nix-fast-build): `ed736c65` -> `a06a8b2c`

---

flake.lock

| Commit                                                                                           | Message                                                                                            |
| ------------------------------------------------------------------------------------------------ | -------------------------------------------------------------------------------------------------- |
| [`6ee6262d`](https://github.com/LnL7/nix-darwin/commit/6ee6262d2468cf053f39cb53ea6272af337f2cf7) | `` Add --ignore-dependencies option for casks ``                                                   |
| [`89be82cb`](https://github.com/LnL7/nix-darwin/commit/89be82cb2b19b6371a786af6eb9effc79babb70f) | `` power: quote in string triggered shellcheck SC2016 `` …

chore(flake/darwin): `71a3a075` -> `ba9b3173`

---

flake.lock

| Commit                                                                                                   | Message                      |
| -------------------------------------------------------------------------------------------------------- | ---------------------------- |
| [`edd8ef57`](https://github.com/lovesegfault/vim-config/commit/edd8ef574701a8f9a4eb3183ad087431c649bec4) | `` fix(lsp): disable lldb `` |

chore(flake/lovesegfault-vim-config): `bc9bb1af` -> `edd8ef57`

---

flake.lock

| [`5c430231`](https://github.com/nix-community/home-manager/commit/5c4302313d9207f7ec0886d68f8ff4a3c71209a1) | `` neomutt: added missing sort options (#6283) `` |

chore(flake/home-manager): `20665c6e` -> `5c430231`

---

flake.lock
hardware/sound.nix

| [`1d5cb8a3`](https://github.com/NixOS/nixpkgs/commit/1d5cb8a3330cbc7f323177591672fc6f1a31cae1) | `` pretix: fix tests after 2025-01-01 ``                                  |
| [`c4d943e9`](https://github.com/NixOS/nixpkgs/commit/c4d943e9eed5b3d717ae70289e440c4a22976630) | `` perlPackages.Testutf8: fix homepage ``                                 |
| [`1f3d0b2d`](https://github.com/NixOS/nixpkgs/commit/1f3d0b2d471358a782b8fe5779d0e37e4f4e0903) | …

chore(flake/nixpkgs): `d70bd19e` -> `8f3e1f80`

---

flake.lock

| Commit                                                                                                | Message         |
| ----------------------------------------------------------------------------------------------------- | --------------- |
| [`4f339f6b`](https://github.com/NixOS/nixos-hardware/commit/4f339f6be2b61662f957c2ee9eda0fa597d8a6d6) | `` oversight `` |

chore(flake/nixos-hardware): `ca30f850` -> `4f339f6b`

---

flake.lock

| [`47b64f25`](https://github.com/lovesegfault/vim-config/commit/47b64f25e5d8a597cc4908f7e0fe87a10f361777) | `` chore(flake/nixpkgs): d70bd19e -> 8f3e1f80 `` |
| [`f43815ee`](https://github.com/lovesegfault/vim-config/commit/f43815ee9506344e1241613b3476d4d651849d74) | `` chore(flake/nixvim): 81c1ef20 -> 0ebc64a2 ``  |

chore(flake/lovesegfault-vim-config): `edd8ef57` -> `47b64f25`

---

flake.lock

| Commit                                                                                        | Message                                                             |
| --------------------------------------------------------------------------------------------- | ------------------------------------------------------------------- |
| [`a8399897`](https://github.com/danth/stylix/commit/a8399897e85510de8698f9a3737d91143af704ef) | `` treewide: remove redundant empty line in testbeds (#760) ``      |
| [`6d986760`](https://github.com/danth/stylix/commit/6d9867604efd73274bbe40fe974af66e9e3faa04) | `` treewide: reduce indentation level with lib.singleton (#754) ``  |
| [`8be9e8ad`](https://github.com/danth/stylix/commit/8be9e8ad9a238ce11fc3a1a00d4baffa4eb9ed28) | `` ci: update Ubuntu runner …

chore(flake/stylix): `5c84f02f` -> `168306ce`

---

flake.lock

| [`45bcdbc9`](https://github.com/nix-community/home-manager/commit/45bcdbc910dc5131943bb6f7edb156617898fd1a) | `` gpg-agent: fix compatibility with sh when enableSshSupport (#6287) `` |

chore(flake/home-manager): `5c430231` -> `45bcdbc9`

---

flake.lock

| [`fcc4259c`](https://github.com/nix-community/home-manager/commit/fcc4259cdbcb76138b48ed36b4f41c521910db0d) | `` treewide: stub tests (#6275) `` |
| [`456e599f`](https://github.com/nix-community/home-manager/commit/456e599f9101ed153dde268b4401c5d294ba6c8c) | `` wayfire: add module (#6066) ``  |

chore(flake/home-manager): `45bcdbc9` -> `fcc4259c`

---

flake.lock

| [`7e008565`](https://github.com/nix-community/home-manager/commit/7e00856596891850ba5ad4c5ecd2ed74468c08c5) | `` flake.lock: Update ``        |
| [`54b330ac`](https://github.com/nix-community/home-manager/commit/54b330ac067e74314f8ca6b38af6fcfbd17f3e9e) | `` go: add telemetry options `` |

chore(flake/home-manager): `fcc4259c` -> `7e008565`

---

flake.lock

| [`9e856ad0`](https://github.com/LnL7/nix-darwin/commit/9e856ad0c1a677d1585e53a634c4abe487601c51) | `` nix: merge `nix.settings.trusted-users` by default `` |

chore(flake/darwin): `ba9b3173` -> `57733bd1`

---

flake.lock

| [`65f2bb26`](https://github.com/lovesegfault/vim-config/commit/65f2bb26cc13cf5f7a48d8ffdeb17471bb1ec2ff) | `` chore(flake/nixvim): 0ebc64a2 -> 83153e96 `` |

chore(flake/lovesegfault-vim-config): `47b64f25` -> `65f2bb26`

---

flake.lock

| [`b9ca21dc`](https://github.com/nix-community/disko/commit/b9ca21dc6c3038f0389f9382b8b406c2f7bfcd6d) | `` export nixosModule as file `` |
| [`b8aecf15`](https://github.com/nix-community/disko/commit/b8aecf159f474d8d2bfc7100d278a1ede8de1a6c) | `` flake.lock: Update ``         |

chore(flake/disko): `49f8aa79` -> `4d5d07d3`

---

flake.lock

| Commit                                                                                                   | Message                                        |
| -------------------------------------------------------------------------------------------------------- | ---------------------------------------------- |
| [`e80daee7`](https://github.com/lovesegfault/vim-config/commit/e80daee781904025fa3f05c717b3364331e7e599) | `` fix: include <cr> in Trim binding ``        |
| [`7faf6fbd`](https://github.com/lovesegfault/vim-config/commit/7faf6fbddebf292c7056361b3584c3cb7519b0f1) | `` fix: remove stale nixpkgs-stable follows `` |

chore(flake/lovesegfault-vim-config): `65f2bb26` -> `e80daee7`

---

flake.lock

| [`8870dcaf`](https://github.com/NixOS/nixos-hardware/commit/8870dcaff63dfc6647fb10648b827e9d40b0a337) | `` surface: linux 6.12.8 -> 6.12.9 ``                      |
| [`d73a04da`](https://github.com/NixOS/nixos-hardware/commit/d73a04dabfc4db21fca65b9d58eaea23573858ba) | `` gpu/intel/tiger-lake: don't try to use Xe by default `` |

chore(flake/nixos-hardware): `4f339f6b` -> `8870dcaf`

---

flake.lock

| Commit                                                                                                            | Message               |
| ----------------------------------------------------------------------------------------------------------------- | --------------------- |
| [`a2200b49`](https://github.com/nix-community/nix-index-database/commit/a2200b499efa01ca8646173e94cdfcc93188f2b8) | `` Add default.nix `` |

chore(flake/nix-index-database): `816a6ae8` -> `a2200b49`

---

flake.lock

| [`39809a3d`](https://github.com/lovesegfault/vim-config/commit/39809a3d7c9e93746214f530522f3ca00bd4b95b) | `` chore(flake/nixpkgs): 8f3e1f80 -> bffc22eb `` |
| [`e3633a4f`](https://github.com/lovesegfault/vim-config/commit/e3633a4fb8e4043a4166ce24db68f292ef4fd4b0) | `` chore(flake/nixvim): 83153e96 -> 67de8484 ``  |

chore(flake/lovesegfault-vim-config): `e80daee7` -> `39809a3d`

---

flake.lock

| [`2532b500`](https://github.com/nix-community/home-manager/commit/2532b500c3ed2b8940e831039dcec5a5ea093afc) | `` ollama: add module (#5735) `` |

chore(flake/home-manager): `d4aebb94` -> `2532b500`

---

flake.lock

| Commit                                                                                                   | Message                                 |
| -------------------------------------------------------------------------------------------------------- | --------------------------------------- |
| [`ab4569df`](https://github.com/lovesegfault/vim-config/commit/ab4569dfbdcbc6e241b76e311ddfcc8e9651c0e6) | `` feat(completion): add tmux source `` |
| [`704247dd`](https://github.com/lovesegfault/vim-config/commit/704247ddd6332d1d8ce88c98a3d832a02c6853f1) | `` feat: replace cmp with blink ``      |

chore(flake/lovesegfault-vim-config): `39809a3d` -> `ab4569df`

---

flake.lock

| [`f1e00319`](https://github.com/danth/stylix/commit/f1e003194cb528bbd4eda50b781d1f703611782d) | `` zed: convert font sizes from pt to px (#766) `` |

chore(flake/stylix): `168306ce` -> `f1e00319`

---

flake.lock

| [`79a12e65`](https://github.com/nix-community/disko/commit/79a12e659bb3fd055e61922fec7b70426464c6d6) | `` disko: fix postVM beeing empty ``                             |
| [`ade21e2c`](https://github.com/nix-community/disko/commit/ade21e2c96b68a33f3614eea1fcdaa36c9ef77d3) | `` Fix typo ``                                                   |
| [`fe89f379`](https://github.com/nix-community/disko/commit/fe89f379e7ed69194264a0cfdcbcd6ff922d8bc3) | `` …

chore(flake/disko): `b1a94497` -> `33827d2b`

---

flake.lock

| Commit                                                                                                | Message                  |
| ----------------------------------------------------------------------------------------------------- | ------------------------ |
| [`906af17f`](https://github.com/Mic92/nix-fast-build/commit/906af17fcd50c84615a4660d9c08cf89c01cef7d) | `` bump version 1.1.0 `` |
| [`be543d30`](https://github.com/Mic92/nix-fast-build/commit/be543d30c2eb44936a2713a032a8790a4ab8a5c3) | `` add release script `` |
| [`d9dc56ab`](https://github.com/Mic92/nix-fast-build/commit/d9dc56ab1ae7a270361f649f597300b93ce66acf) | `` flake.lock: Update `` |

chore(flake/nix-fast-build): `a06a8b2c` -> `906af17f`

---

flake.lock

| [`3f4cc692`](https://github.com/lovesegfault/vim-config/commit/3f4cc6926418cd6f01b666af63a9d693da27693c) | `` chore(flake/nixvim): 67de8484 -> 2fc2132a `` |

chore(flake/lovesegfault-vim-config): `ab4569df` -> `3f4cc692`

---

flake.lock

| Commit                                                                                           | Message                    |
| ------------------------------------------------------------------------------------------------ | -------------------------- |
| [`be4c1b89`](https://github.com/LnL7/nix-darwin/commit/be4c1b897accbdfc3429e99b5bd5234c5663776e) | `` openssh: init module `` |

chore(flake/darwin): `57733bd1` -> `6ace2f2d`

---

flake.lock

| [`271e5bd7`](https://github.com/nix-community/nix-index-database/commit/271e5bd7c57e1f001693799518b10a02d1123b12) | `` update generated.nix to release 2025-01-12-031855 `` |
| [`eb593fb1`](https://github.com/nix-community/nix-index-database/commit/eb593fb1ddcbafe3d4280f0c301222f2223d18a8) | `` flake.lock: Update ``                                |

chore(flake/nix-index-database): `a2200b49` -> `271e5bd7`

---

flake.lock

| [`c64bed13`](https://github.com/nix-community/impermanence/commit/c64bed13b562fc3bb454b48773d4155023ac31b7) | `` README: Fix potential btrfs reset script corruption `` |

chore(flake/impermanence): `d000479f` -> `c64bed13`

---

flake.lock

| Commit                                                                                               | Message              |
| ---------------------------------------------------------------------------------------------------- | -------------------- |
| [`f275b063`](https://github.com/nix-community/disko/commit/f275b06323f9b13666cb5e93856af3dd3b910990) | `` Fix minor typo `` |

chore(flake/disko): `33827d2b` -> `f720e64e`

---

flake.lock

| [`fb773084`](https://github.com/danth/stylix/commit/fb773084f74b2ddec103a2459847dabd2a65874c) | `` doc: fix two titles not using sentence case (#769) ``   |
| [`0a20c8d0`](https://github.com/danth/stylix/commit/0a20c8d0ede42be2ab75038f868f6b961d9d827f) | `` ci: standardize output redirection formatting (#756) `` |

chore(flake/stylix): `f1e00319` -> `fb773084`

---

flake.lock

| [`74f963ab`](https://github.com/lovesegfault/vim-config/commit/74f963abea465bb83c9813c627a1f702004bd221) | `` chore(flake/nixpkgs): bffc22eb -> 130595eb `` |
| [`627d7da7`](https://github.com/lovesegfault/vim-config/commit/627d7da70dbd1121b5142996c534b1cd94062a65) | `` chore(flake/nixvim): 2fc2132a -> 35d6c126 ``  |

chore(flake/lovesegfault-vim-config): `3f4cc692` -> `74f963ab`

---

.envrc
flake.lock

| [`dd252f51`](https://github.com/NixOS/nixpkgs/commit/dd252f51784f8a5c586126e3fd23491aba361c9b) | `` lziprecover: 1.24 -> 1.25 ``                                             |
| [`e1af25de`](https://github.com/NixOS/nixpkgs/commit/e1af25de8294bf775466bbdef3f55ea961c970b8) | `` home-assistant-custom-lovelace-modules.weather-card: 1.5.0 -> 2.0.0b0 `` |
| [`9c6b6bf1`](https://github.com/NixOS/nixpkgs/commit/9c6b6bf1979bb5deacdb423626aa2cefcb29c …

chore(flake/nixpkgs): `bffc22eb` -> `ed4a395e`

---

flake.lock

| [`9616d81f`](https://github.com/nix-community/home-manager/commit/9616d81f98032d1ee9bec68ab4b6a8c833add88c) | `` mangohud: make `false` values actually disable (#6299) `` |

chore(flake/home-manager): `2532b500` -> `9616d81f`

---

flake.lock

| [`934e2bfe`](https://github.com/danth/stylix/commit/934e2bfe7954d6c94f25d45cb12a8b3547825699) | `` vencord: init (#768) `` |

chore(flake/stylix): `fb773084` -> `934e2bfe`

---

flake.lock

| Commit                                                                                           | Message                                                    |
| ------------------------------------------------------------------------------------------------ | ---------------------------------------------------------- |
| [`e33d37c4`](https://github.com/LnL7/nix-darwin/commit/e33d37c41f8040631f0cc16b032a1cf214aeeb4e) | `` {readme,examples/flake}: update for release branches `` |
| [`d5aeb4e5`](https://github.com/LnL7/nix-darwin/commit/d5aeb4e5b17c4e17b4eb515e088d6ea6babd14d8) | `` checks: recommend `sudo nix-channel` ``                 |
| [`efba3517`](https://github.com/LnL7/nix-darwin/commit/efba3517fcd8f034e01dfda1c94a865d11aaf69f) | `` eval-config: implement release branch checks `` …

chore(flake/darwin): `6ace2f2d` -> `bd921223`

---

flake.lock

| Commit                                                                                         | Message                                                                                        |
| ---------------------------------------------------------------------------------------------- | ---------------------------------------------------------------------------------------------- |
| [`01c1ec8f`](https://github.com/NixOS/nixpkgs/commit/01c1ec8f5fb4c95653afe0984df9bd9a948286d1) | `` osmium-tool: fix build ``                                                                   |
| [`2686ec7e`](https://github.com/NixOS/nixpkgs/commit/2686ec7e75c3912056075a83d50079b3ebeb5cd1) | `` xilinx-bootgen: xilinx_v2024.1 -> xilinx_v2024.2 ``                                         |
| …

chore(flake/nixpkgs): `ed4a395e` -> `9abb87b5`

---

flake.lock

| Commit                                                                                        | Message                                                                       |
| --------------------------------------------------------------------------------------------- | ----------------------------------------------------------------------------- |
| [`965d1cb7`](https://github.com/danth/stylix/commit/965d1cb7c84170200b4f05e68ebd27a88d171e8c) | `` zathura: set background opacity with stylix.opacity.applications (#770) `` |

chore(flake/stylix): `934e2bfe` -> `965d1cb7`

---

flake.lock

| Commit                                                                                                  | Message                                                              |
| ------------------------------------------------------------------------------------------------------- | -------------------------------------------------------------------- |
| [`5c6d92f2`](https://github.com/tinted-theming/schemes/commit/5c6d92f20e5761e0bfd78ee88cb9fca72189c0cf) | `` Update tinted-theming gallery links in various README.md (#38) `` |

chore(flake/tinted-schemes): `d5024d07` -> `5c6d92f2`

---

flake.lock

| [`c197891c`](https://github.com/lovesegfault/vim-config/commit/c197891c791de130eeb9344aeb6017aa846e340d) | `` feat: enable zen-mode ``                      |
| [`2e9ce564`](https://github.com/lovesegfault/vim-config/commit/2e9ce56419549736509ebe47e1be32f43dcc6e31) | `` chore(flake/nixpkgs): 130595eb -> 9abb87b5 `` |
| [`c9dad750`](https://github.com/lovesegfault/vim-config/commit/c9dad75023f1506f66f2ce029420e02794641f9c) | `` chore(flake/nixvim): 35d6c126 -> 4282b73a ``  |

chore(flake/lovesegfault-vim-config): `74f963ab` -> `c197891c`

---

flake.lock

| Commit                                                                                                   | Message                                             |
| -------------------------------------------------------------------------------------------------------- | --------------------------------------------------- |
| [`b66b114b`](https://github.com/lovesegfault/vim-config/commit/b66b114ba30dc4ad2dbe90ca1858dc12a1e9661a) | `` ci: use macos-latest ``                          |
| [`25534f48`](https://github.com/lovesegfault/vim-config/commit/25534f488d4266e9ea1818f37d7570dcd157eafd) | `` ci: stop forcing usage of cachix from nixpkgs `` |

chore(flake/lovesegfault-vim-config): `c197891c` -> `b66b114b`

---

flake.lock

| Commit                                                                                         | Message                                                               |
| ---------------------------------------------------------------------------------------------- | --------------------------------------------------------------------- |
| [`4d0d81e6`](https://github.com/ryantm/agenix/commit/4d0d81e6061f1add4af464618491439f6d819118) | `` fix: bad indentation in ci ``                                      |
| [`96b7e4f9`](https://github.com/ryantm/agenix/commit/96b7e4f9eb4db2763db2699322fa2a544184d1eb) | `` contrib: improve readability of age.identityPaths default value `` |
| [`989ade28`](https://github.com/ryantm/agenix/commit/989ade28509c66d7abfa53613359d332ae506222) | `` feat: …

chore(flake/agenix): `f6291c59` -> `e600439e`

---

flake.lock

| Commit                                                                                                   | Message                                                |
| -------------------------------------------------------------------------------------------------------- | ------------------------------------------------------ |
| [`f34d9726`](https://github.com/lovesegfault/vim-config/commit/f34d972643302f43aef4ff14535fad71bfd8f9d2) | `` feat: add some more colorschemes ``                 |
| [`ef258ffe`](https://github.com/lovesegfault/vim-config/commit/ef258ffea6d91f48c49ada55de613e9e19b5c13a) | `` refactor(lualine): use auto theme ``                |
| [`5f54c743`](https://github.com/lovesegfault/vim-config/commit/5f54c743d4e05def34f509a75af3e08f776fda3f) | `` feat(telescope): enable …

chore(flake/lovesegfault-vim-config): `b66b114b` -> `f34d9726`

---

flake.lock

| Commit                                                                                                | Message                                                                                                      |
| ----------------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------------------------------ |
| [`b6786066`](https://github.com/NixOS/nixos-hardware/commit/b678606690027913f3434dea3864e712b862dde5) | `` lenovo-z13-gen2: networking.networkmanager.fccUnlockScripts → networking.modemmanager.fccUnlockScripts `` |
| [`06c52bbc`](https://github.com/NixOS/nixos-hardware/commit/06c52bbc795a853d3c84ae2226652f3aa3b51db9) | `` Lenovo IdeaCentre K330 `` …

chore(flake/nixos-hardware): `8870dcaf` -> `b6786066`

---

flake.lock

| [`370ee386`](https://github.com/lovesegfault/vim-config/commit/370ee386cc54e1fe091e66438a718bc361a24e1a) | `` chore(flake/nixpkgs): 9abb87b5 -> eb62e6aa `` |
| [`6ad6e365`](https://github.com/lovesegfault/vim-config/commit/6ad6e365e617265aa1ddf7d332767ba095c2b57c) | `` chore(flake/nixvim): 4282b73a -> 5b068e7f ``  |

chore(flake/lovesegfault-vim-config): `f34d9726` -> `370ee386`

---

flake.lock

| [`0dfec9de`](https://github.com/nix-community/home-manager/commit/0dfec9deb275854a56c97c356c40ef72e3a2e632) | `` hyprlock: remove with lib; ``                |
| [`a1f180af`](https://github.com/nix-community/home-manager/commit/a1f180af1710c2b4a2b9e1a8f6d8871840497393) | `` hyprlock: add bezier to importantPrefixes `` |

chore(flake/home-manager): `fc52a210` -> `0dfec9de`

---

flake.lock

| [`a88c4d26`](https://github.com/danth/stylix/commit/a88c4d264a4379b7fe5a9e75ed51bea96f8dd407) | `` stylix: update all flake inputs (#774) `` |

chore(flake/stylix): `2985ee9b` -> `a88c4d26`

---

flake.lock

| [`c53bfaa1`](https://github.com/nix-community/disko/commit/c53bfaa13a8de4995b22f7ac13c4c34e46fb368a) | `` zfs_volume: fix eval of _unmount if content is null ``       |
| [`1ae7c794`](https://github.com/nix-community/disko/commit/1ae7c794d93d79497aade51261634532202bcfda) | `` zfs_volume: add zfs_volume without content to zfs example `` |

chore(flake/disko): `f720e64e` -> `bf0abfde`

---

flake.lock

| [`97871d41`](https://github.com/numtide/treefmt-nix/commit/97871d416166803134ba64597a1006f3f670fbde) | `` pinact: init (#300) `` |

chore(flake/treefmt-nix): `13c913f5` -> `97871d41`

---

flake.lock

| [`12851ae7`](https://github.com/nix-community/home-manager/commit/12851ae7467bad8ef422b20806ab4d6d81e12d29) | `` thunderbird: Enable tests for Darwin (#6324) `` |

chore(flake/home-manager): `0dfec9de` -> `12851ae7`

---

flake.lock

| Commit                                                                                           | Message                                                        |
| ------------------------------------------------------------------------------------------------ | -------------------------------------------------------------- |
| [`4075a3c2`](https://github.com/LnL7/nix-darwin/commit/4075a3c23aa7996acc960e61df9f21038136d08a) | `` Add support for additional window tiling options ``         |
| [`f959b887`](https://github.com/LnL7/nix-darwin/commit/f959b8878b2a2e27f2df024930e52cb68b0528be) | `` defaults-write: fix activation script conditionalization `` |
| [`47174f38`](https://github.com/LnL7/nix-darwin/commit/47174f38689dba3221883db5f908f7e3ef924ef6) | `` doc/manual: use …

chore(flake/darwin): `bd921223` -> `09414c7e`

---

flake.lock

| [`a7829bb0`](https://github.com/numtide/treefmt-nix/commit/a7829bb0c193c1595e36e1c034591646dc5598c5) | `` add katexochen as maintainer `` |

chore(flake/treefmt-nix): `97871d41` -> `d1ed3b38`

---

flake.lock

| [`a0046af1`](https://github.com/nix-community/home-manager/commit/a0046af169ce7b1da503974e1b22c48ef4d71887) | `` Translations update from Hosted Weblate `` |

chore(flake/home-manager): `12851ae7` -> `a0046af1`

---

flake.lock

| [`ef85bf78`](https://github.com/lovesegfault/vim-config/commit/ef85bf782fff8f80d55b6fc28e5b35e342c38a04) | `` chore(flake/treefmt-nix): 97871d41 -> d1ed3b38 `` |
| [`9241f149`](https://github.com/lovesegfault/vim-config/commit/9241f149d51e7b4053b0bc6509bae560c634f6e6) | `` chore(flake/nixvim): d4c67764 -> aa839cf9 ``      |

chore(flake/lovesegfault-vim-config): `8e1d388d` -> `ef85bf78`

---

flake.lock

| Commit                                                                                           | Message                                                                        |
| ------------------------------------------------------------------------------------------------ | ------------------------------------------------------------------------------ |
| [`8abb2e72`](https://github.com/LnL7/nix-darwin/commit/8abb2e7244b998a9d73818baa744044f8882e68b) | `` nix: add hashes for Determinate Systems installer v0.33.0 and v0.34.0 ``    |
| [`2fe899db`](https://github.com/LnL7/nix-darwin/commit/2fe899db70f8d2e9162e9ff44eef4f734787b5b1) | `` nix: check `/etc/nix/nix.custom.conf` hash ``                               |
| [`ff1d6384`](https://github.com/LnL7/nix-darwin/commit/ff1d6384dfa276f …

chore(flake/darwin): `09414c7e` -> `87131f51`

---

flake.lock

| [`e00ed7e7`](https://github.com/danth/stylix/commit/e00ed7e7f4b828f8b12c5056a6167890e59854ce) | `` wpaperd: fix image scaling modes (#710) `` |

chore(flake/stylix): `a88c4d26` -> `e00ed7e7`

---

flake.lock

| [`1e364297`](https://github.com/nix-community/home-manager/commit/1e36429705f9af2d00a517ba46a4f21ef8a8194f) | `` sbt: allow irregular plugins to be configured `` |
| [`495de1e1`](https://github.com/nix-community/home-manager/commit/495de1e197e7e113ad8877dad4c29a66482a093c) | `` Translate using Weblate (Danish) ``              |

chore(flake/home-manager): `a0046af1` -> `1e364297`

---

flake.lock

| Commit                                                                                        | Message                     |
| --------------------------------------------------------------------------------------------- | --------------------------- |
| [`51ad2cec`](https://github.com/danth/stylix/commit/51ad2cec11e773a949bdbec88bed2524f098f49a) | `` cavalier: init (#758) `` |

chore(flake/stylix): `e00ed7e7` -> `51ad2cec`

---

flake.lock

| [`97d7946b`](https://github.com/nix-community/home-manager/commit/97d7946b5e107dd03cc82f21165251d4e0159655) | `` {hypridle, hyrpaper}: remove with lib; (#6318) ``    |
| [`1c75a4c1`](https://github.com/nix-community/home-manager/commit/1c75a4c151dfe417c73ae3f87a6eba0b009c438c) | `` syncthing: have tray wait for bar to load (#6290) `` |

chore(flake/home-manager): `1e364297` -> `97d7946b`

---

flake.lock

| [`ee5bbd95`](https://github.com/lovesegfault/vim-config/commit/ee5bbd953b6befed62e76bcdc28db541112c6f47) | `` chore(flake/nixvim): aa839cf9 -> cbf960e5 `` |

chore(flake/lovesegfault-vim-config): `ef85bf78` -> `ee5bbd95`

---

flake.lock

| [`744d3306`](https://github.com/nix-community/nix-index-database/commit/744d330659e207a1883d2da0141d35e520eb87bd) | `` update generated.nix to release 2025-01-19-031135 `` |
| [`5b1c0594`](https://github.com/nix-community/nix-index-database/commit/5b1c05942acc51e9cb5a4ad214b2292f8401af67) | `` flake.lock: Update ``                                |

chore(flake/nix-index-database): `271e5bd7` -> `744d3306`

---

flake.lock

| Commit                                                                                                      | Message                                                                                     |
| ----------------------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------------- |
| [`f8ef4541`](https://github.com/nix-community/home-manager/commit/f8ef4541bb8a54a8b52f19b52912119e689529b3) | `` nixpkgs: lib.isFunction replaces builtins.isFunction in check for overlayType (#6338) `` |

chore(flake/home-manager): `97d7946b` -> `f8ef4541`

---

flake.lock

| Commit                                                                                                    | Message                                                     |
| --------------------------------------------------------------------------------------------------------- | ----------------------------------------------------------- |
| [`0952e5c7`](https://github.com/nix-community/lanzaboote/commit/0952e5c7412f4e14119ca745a4809965da1e5ec2) | `` fix(tool): parse osrel sections without trailing null `` |

chore(flake/lanzaboote): `93e6f0d7` -> `64d20cb2`

---

flake.lock

| [`cb3173dc`](https://github.com/NixOS/nixos-hardware/commit/cb3173dc5c746fa95bca1f035a7e4d2b588894ac) | `` include Dell Latitude 549 in flake.nix (#1316) `` |
| [`abe22227`](https://github.com/NixOS/nixos-hardware/commit/abe22227d7e8ef0077ba863804b3755545fbf5f7) | `` xiaomi/redmibook/16-pro-2024: init ``             |

chore(flake/nixos-hardware): `b6786066` -> `cb3173dc`

---

flake.lock

| Commit                                                                                                | Message                                                                      |
| ----------------------------------------------------------------------------------------------------- | ---------------------------------------------------------------------------- |
| [`61c79181`](https://github.com/NixOS/nixos-hardware/commit/61c79181e77ef774ab0468b28a24bc2647d498d6) | `` feat: HP probook 440G5 config ``                                          |
| [`b5399578`](https://github.com/NixOS/nixos-hardware/commit/b5399578399a07741f5a9025445e9e886d4f8d71) | `` update readme to mention power profile / nvidia-powerd troubleshooting `` |
| …

chore(flake/nixos-hardware): `cb3173dc` -> `61c79181`

---

flake.lock

| [`9786661d`](https://github.com/nix-community/home-manager/commit/9786661d57c476021c8a0c3e53bf9fa2b4f3328b) | `` fcitx5: allow to set fcitx5-with-addons (#5770) `` |

chore(flake/home-manager): `f8ef4541` -> `9786661d`

---

flake.lock

| Commit                                                                                                   | Message                                   |
| -------------------------------------------------------------------------------------------------------- | ----------------------------------------- |
| [`62d58208`](https://github.com/lovesegfault/vim-config/commit/62d5820830ba35a8507b640566e3909264ae9334) | `` ci: enable ubuntu-24.04-arm runners `` |

chore(flake/lovesegfault-vim-config): `c7d2d3aa` -> `62d58208`

---

flake.lock

| Commit                                                                                           | Message                                                                    |
| ------------------------------------------------------------------------------------------------ | -------------------------------------------------------------------------- |
| [`87b61d66`](https://github.com/LnL7/nix-darwin/commit/87b61d666632de823338039e6a10785b15519ae4) | `` eval-config: omit `enableNixpkgsReleaseCheck` from `lib.evalModules` `` |
| [`5665d6c0`](https://github.com/LnL7/nix-darwin/commit/5665d6c05ef73b904e3a8bc37c35b7be1d923f4d) | `` darwin-rebuild: pass `${extraBuildFlags[@]}` to `nix-instantiate` ``    |
| [`94adbd62`](https://github.com/LnL7/nix-darwin/commit/94adbd6259190f49104f2edfe82d8e8 …

chore(flake/darwin): `87131f51` -> `46d0fa4d`

---

flake.lock

| [`268daf22`](https://github.com/danth/stylix/commit/268daf22a1f93a00b7efc74c367d6711ca7f18e1) | `` eog: init (#781) ``                       |
| [`6b69fd47`](https://github.com/danth/stylix/commit/6b69fd47fa86a3258b73168524cd196132549162) | `` firefox: support floorp browser (#785) `` |
| [`76b1f6eb`](https://github.com/danth/stylix/commit/76b1f6eb1d401e91571f7691abd6b0a976eb34cd) | `` stylix: add jq to runtimeInputs (#782) `` |

chore(flake/stylix): `51ad2cec` -> `268daf22`

---

flake.lock

| [`1b761e38`](https://github.com/lovesegfault/vim-config/commit/1b761e38b3c446506cf3bfc35bf835bcc504bde5) | `` chore(flake/nixvim): 8fb2fe22 -> 115994f1 `` |

chore(flake/lovesegfault-vim-config): `62d58208` -> `1b761e38`

---

flake.lock

| [`bb14224f`](https://github.com/nix-community/home-manager/commit/bb14224f51ae4caed12a7b26f245d042c8cf8553) | `` mu: allow option to set muhome ``  |
| [`0b8df9ee`](https://github.com/nix-community/home-manager/commit/0b8df9eeb66941ef32e5761ecf4cddff91e5c020) | `` lsd: add support for icons.yaml `` |

chore(flake/home-manager): `9786661d` -> `bb14224f`

---

flake.lock

| [`96dee79b`](https://github.com/nix-community/home-manager/commit/96dee79b178d295b716052feca3ee46abc085abe) | `` lsd: remove with lib; `` |

chore(flake/home-manager): `bb14224f` -> `96dee79b`

---

flake.lock

| Commit                                                                                           | Message                        |
| ------------------------------------------------------------------------------------------------ | ------------------------------ |
| [`c3954c51`](https://github.com/LnL7/nix-darwin/commit/c3954c51c4a02a9ed5455252c09b7b1690cb59bf) | `` checks: remove `runLink` `` |

chore(flake/darwin): `46d0fa4d` -> `65cc1fa8`

---

flake.lock

| [`4481a16d`](https://github.com/nix-community/home-manager/commit/4481a16d1ac5bff4a77c608cefe08c9b9efe840d) | `` yazi: improve fish integration `` |

chore(flake/home-manager): `96dee79b` -> `4481a16d`

---

flake.lock

| [`491af690`](https://github.com/lovesegfault/vim-config/commit/491af6901f677d99d5c29d69c1a01c13ecfc2cb2) | `` chore(flake/treefmt-nix): d1ed3b38 -> f2cc121d ``        |
| [`29696891`](https://github.com/lovesegfault/vim-config/commit/296968916f3d8f0176ab03b2762a0705fb8d04c1) | `` chore(flake/nix-github-actions): 7b5f051d -> f4158fa0 `` |

chore(flake/lovesegfault-vim-config): `a9fe6398` -> `491af690`

---

flake.lock

| Commit                                                                                                  | Message                                            |
| ------------------------------------------------------------------------------------------------------- | -------------------------------------------------- |
| [`ae31625b`](https://github.com/tinted-theming/schemes/commit/ae31625ba47aeaa4bf6a98cf11a8d4886f9463d9) | `` Fix variant since icy is a dark scheme (#36) `` |

chore(flake/tinted-schemes): `5c6d92f2` -> `ae31625b`

---

flake.lock

| [`cefb1889`](https://github.com/nix-community/home-manager/commit/cefb1889b96ddd1dac3dd4734e894f4cadab7802) | `` Translate using Weblate (Czech) `` |

chore(flake/home-manager): `4481a16d` -> `cefb1889`

---

flake.lock

| [`36c39ff0`](https://github.com/danth/stylix/commit/36c39ff014a8abbc682a073b2c5ba6cea77cf41e) | `` gnome: fix foreground color of transparent panels (#788) `` |

chore(flake/stylix): `268daf22` -> `36c39ff0`

---

flake.lock

| [`76f8382d`](https://github.com/lovesegfault/vim-config/commit/76f8382db1e4b11d45f0762e0b741065f2ca971d) | `` chore(flake/nixvim): 342161bf -> a2a4befd `` |

chore(flake/lovesegfault-vim-config): `491af690` -> `76f8382d`

---

flake.lock

| [`0db5c8bf`](https://github.com/nix-community/home-manager/commit/0db5c8bfcce78583ebbde0b2abbc95ad93445f7c) | `` ghostty: add keybinds to settings example `` |
| [`01d01729`](https://github.com/nix-community/home-manager/commit/01d0172933845daaf3392f6b8c3953995e912f6e) | `` wezterm: update expected test result ``      |
| [`b17008a7`](https://github.com/nix-community/home-manager/commit/b17008a795066bd3b4da86d7614a3be0efb0092e) | `` swayr: update expected test result …

chore(flake/home-manager): `cefb1889` -> `0db5c8bf`

---

flake.lock

| [`9e4d5190`](https://github.com/NixOS/nixpkgs/commit/9e4d5190a9482a1fb9d18adf0bdb83c6e506eaab) | `` kubernetes: 1.32.0 -> 1.32.1 (#374210) ``                               |
| [`0b9b3ab5`](https://github.com/NixOS/nixpkgs/commit/0b9b3ab50446126c7aea4f8e65087e7bd50d60e1) | `` python312Packages.sagemaker-core: 1.0.17 -> 1.0.19 ``                   |
| [`e1996d7b`](https://github.com/NixOS/nixpkgs/commit/e1996d7bdaf4eafdb85690079b9e02b25dc14e4f) …

chore(flake/nixpkgs): `eb62e6aa` -> `9e4d5190`

---

flake.lock

| [`dcb9da16`](https://github.com/lovesegfault/vim-config/commit/dcb9da16ea25ac0967b964ce686b0238e2e4f263) | `` chore(flake/nixpkgs): eb62e6aa -> 9e4d5190 `` |

chore(flake/lovesegfault-vim-config): `76f8382d` -> `dcb9da16`

---

flake.lock

| Commit                                                                                                    | Message                        |
| --------------------------------------------------------------------------------------------------------- | ------------------------------ |
| [`ec7372a9`](https://github.com/nix-community/lanzaboote/commit/ec7372a988fffd661831a81468f4c2d330288066) | `` treewide: 0.4.1 -> 0.4.2 `` |

chore(flake/lanzaboote): `64d20cb2` -> `a65905a0`

---

flake.lock

| [`e594886e`](https://github.com/danth/stylix/commit/e594886eb0951a0a0c28ffa333a9df6fb13857a1) | `` nixcord: init (#767) `` |

chore(flake/stylix): `36c39ff0` -> `e594886e`

---

flake.lock

| [`1f494394`](https://github.com/lovesegfault/vim-config/commit/1f4943941c326e91cb0f3d47be4236b1b2e17357) | `` chore(flake/nixvim): a2a4befd -> aab2b817 `` |

chore(flake/lovesegfault-vim-config): `dcb9da16` -> `1f494394`

---

flake.lock

| [`7b9ece1b`](https://github.com/nix-community/home-manager/commit/7b9ece1bf3c8780cde9b975b28c2d9ccd7e9cdb9) | `` tealdeer: update docs link `` |

chore(flake/home-manager): `0db5c8bf` -> `7b9ece1b`

---

flake.lock

| [`a0428685`](https://github.com/nix-community/home-manager/commit/a0428685572b134f6594e7d7f5db5e1febbab2d7) | `` nh: remove PATH assignment in nh-clean systemd unit `` |
| [`a2362a64`](https://github.com/nix-community/home-manager/commit/a2362a64964c406ba3b289a474fbde573f4b7fc9) | `` nh: check osConfig for null before accessing ``        |

chore(flake/home-manager): `7b9ece1b` -> `a0428685`

---

flake.lock

| [`b43b1f04`](https://github.com/NixOS/nixpkgs/commit/b43b1f04c0d2003941b561c7fbfc7c9bb0e043b8) | `` python312Packages.vector: 1.6.0 -> 1.6.1 (#375927) ``                           |
| [`c86f1904`](https://github.com/NixOS/nixpkgs/commit/c86f190448145d603a817a63cb4f32c5e10e7338) | `` mysqltuner: 1.8.3 -> 2.6.0 ``                                                   |
| [`f0413353`](https://github.com/NixOS/nixpkgs/commit/f0413353a …

chore(flake/nixpkgs): `9e4d5190` -> `0aa47554`

---

flake.lock

| [`dfad538f`](https://github.com/NixOS/nixos-hardware/commit/dfad538f751a5aa5d4436d9781ab27a6128ec9d4) | `` dell/latitude/7420: init ``                                         |
| [`76590935`](https://github.com/NixOS/nixos-hardware/commit/7659093598c593aafb3e3ecd6a1ea9e6e2023faf) | `` gpd/pocket-4: default kernel version to 6.12 to fix amdgpu error `` |
| [`c2aa5756`](https://github.com/NixOS/nixos-hardware/commit/c2aa5756c0ee18607c38f7 …

chore(flake/nixos-hardware): `93680277` -> `dfad538f`

---

flake.lock

| [`daf04c59`](https://github.com/nix-community/home-manager/commit/daf04c5950b676f47a794300657f1d3d14c1a120) | `` ollama: add darwin support ``                   |
| [`1b9fe46e`](https://github.com/nix-community/home-manager/commit/1b9fe46e9fc3575eeb63ef42d73144e397593904) | `` home-manager: move tests into new test flake `` |
| [`b93e17c7`](https://github.com/nix-community/home-manager/commit/b93e17c73cca670460d0604c00ba0571eb5d4cad) | `` neovim: fix flaky test …

chore(flake/home-manager): `a0428685` -> `daf04c59`

---

flake.lock

| [`75bfbc80`](https://github.com/lovesegfault/vim-config/commit/75bfbc800b341399d73f71a50d8bffdca53fc4b5) | `` chore(flake/nixpkgs): 9e4d5190 -> 0aa47554 `` |
| [`a72940df`](https://github.com/lovesegfault/vim-config/commit/a72940dfb8e0ae226d7d79e67c304a0de7d3b5b3) | `` chore(flake/nixvim): aab2b817 -> 5fda6e09 ``  |

chore(flake/lovesegfault-vim-config): `1f494394` -> `75bfbc80`

---

flake.lock

| [`4b3e914c`](https://github.com/nix-community/impermanence/commit/4b3e914cdf97a5b536a889e939fb2fd2b043a170) | `` fix(home): order of operations causing issue with files ``    |
| [`44e4c998`](https://github.com/nix-community/impermanence/commit/44e4c998504e285d4cdb76c1cdeca0e48c0896bf) | `` docs(home): improve method docs ``                            |
| [`5e884ea8`](https://github.com/nix-community/impermanence/commit/5e884ea82a9b35c8 …

chore(flake/impermanence): `c64bed13` -> `4b3e914c`

---

flake.lock

| Commit                                                                                        | Message                                                                      |
| --------------------------------------------------------------------------------------------- | ---------------------------------------------------------------------------- |
| [`7c1c3259`](https://github.com/danth/stylix/commit/7c1c3259283f2da9c3d15c9096e7b8864f82bd4c) | `` ci: remove Magic Nix Cache (#745) ``                                      |
| [`5e8be752`](https://github.com/danth/stylix/commit/5e8be7521e8f7cc927c92f24f8753e64ec050cdf) | `` treewide: simplify and standardize message convention (#796) ``           |
| [`58b54b66`](https://github.com/danth/stylix/commit/58b54b664b7c67929cd0b5e6221cecbed3eab2 …

chore(flake/stylix): `e594886e` -> `7c1c3259`

---

flake.lock

| [`58e296da`](https://github.com/lovesegfault/vim-config/commit/58e296dae016d6df72d1977ac6b0ee5c990e384c) | `` chore(flake/nixvim): 5fda6e09 -> d7df5832 `` |

chore(flake/lovesegfault-vim-config): `75bfbc80` -> `58e296da`

---

flake.lock

| [`92b7e18b`](https://github.com/NixOS/nixpkgs/commit/92b7e18b22734f0de238c92e695f5e93408addb4) | `` socalabs-sid: init at 1.1.0 (#372081) ``                                      |
| [`b376e96f`](https://github.com/NixOS/nixpkgs/commit/b376e96f521d932948aa3a62f7878bce3d26ef11) | `` quartus-prime-lite: add missing runtime dependency xorg.libXscrnSaver ``      |
| [`14ce74a5`](https://github.com/NixOS/nixpkgs/commit/14ce74a5ef2e36a24 …

chore(flake/nixpkgs): `0aa47554` -> `825479c3`

---

flake.lock

| [`79b7b8ea`](https://github.com/nix-community/nix-index-database/commit/79b7b8eae3243fc5aa9aad34ba6b9bbb2266f523) | `` update generated.nix to release 2025-01-26-030915 `` |
| [`a07b10ac`](https://github.com/nix-community/nix-index-database/commit/a07b10ac6326546b93920b6345ee18f41bba6849) | `` flake.lock: Update ``                                |

chore(flake/nix-index-database): `744d3306` -> `79b7b8ea`

---

flake.lock

| [`d6951d0b`](https://github.com/danth/stylix/commit/d6951d0b2ffe74e4779a180e9b6a0e17627756e1) | `` vesktop: change theme location on nix-darwin (#784) `` |

chore(flake/stylix): `7c1c3259` -> `d6951d0b`

---

flake.lock

| [`b5b78887`](https://github.com/LnL7/nix-darwin/commit/b5b7888793329a8c70c216cae9db8a0180b3dcda) | `` nix-tools: set `$NIX_PATH` ``                          |
| [`4d0ae698`](https://github.com/LnL7/nix-darwin/commit/4d0ae6980d128baecf7e7f636e4df4a95740d628) | `` nix-tools: overwrite `$PATH` rather than prepending `` |
| [`3d95b013`](https://github.com/LnL7/nix-darwin/commit/3d95b013516aa3c97e645ad803d1a497097dab90) | `` nix-tools: make `systemPath` more readable `` …

chore(flake/darwin): `65cc1fa8` -> `62ba0a22`

---

flake.lock

| [`e005ab8e`](https://github.com/lovesegfault/vim-config/commit/e005ab8e0ed6471ae8da623b65c19c10cb0407f1) | `` chore(flake/nixpkgs): 0aa47554 -> 852ff1d9 `` |
| [`c4095ef3`](https://github.com/lovesegfault/vim-config/commit/c4095ef3799e3af5a90314b47d53a70b7644f435) | `` chore(flake/nixvim): d7df5832 -> 8e5422bf ``  |

chore(flake/lovesegfault-vim-config): `58e296da` -> `e005ab8e`

---

flake.lock

| Commit                                                                                        | Message                                                           |
| --------------------------------------------------------------------------------------------- | ----------------------------------------------------------------- |
| [`6103431c`](https://github.com/danth/stylix/commit/6103431cd2f9d4352e5493a4063cf57e307d355c) | `` doc: Update tricks per tinted-theming schema changes (#792) `` |
| [`d5f02b54`](https://github.com/danth/stylix/commit/d5f02b541064763ada8b917834d55142af07b55c) | `` ghostty: be consistent with other terminals (#806) ``          |

chore(flake/stylix): `d6951d0b` -> `6103431c`

---

flake.lock

| [`173cc4d4`](https://github.com/NixOS/nixpkgs/commit/173cc4d47099a0de48a45cb04bad0a38b7fcad04) | `` todiff: remove ``                                                                |
| [`a51f81e5`](https://github.com/NixOS/nixpkgs/commit/a51f81e58f2d42becb75417466ad92f180407a7a) | `` buildpack: 0.36.2 -> 0.36.4 ``                                                   |
| …

chore(flake/nixpkgs): `825479c3` -> `852ff1d9`

---

flake.lock

| [`e1ae908b`](https://github.com/nix-community/home-manager/commit/e1ae908bcc30af792b0bb0a52e53b03d2577255e) | `` flake.lock: Update `` |

chore(flake/home-manager): `daf04c59` -> `e1ae908b`

---

flake.lock

| Commit                                                                                           | Message                                                        |
| ------------------------------------------------------------------------------------------------ | -------------------------------------------------------------- |
| [`4bff4bc8`](https://github.com/LnL7/nix-darwin/commit/4bff4bc8ae105dbc3a56ed5255fbde9495cbf4c1) | `` {activation-scripts,activate-system}: purify environment `` |
| [`ff80eacd`](https://github.com/LnL7/nix-darwin/commit/ff80eacd0f756fa2c410f9128b114eeb0b4e5bc5) | `` activation-scripts: remove `_status` ``                     |
| [`0e87d3d3`](https://github.com/LnL7/nix-darwin/commit/0e87d3d3914321ceea5b10a87f48b6ff6179e190) | `` activate-system: don’t …

chore(flake/darwin): `62ba0a22` -> `5c12a6f4`

---

flake.lock

| [`55418e8f`](https://github.com/danth/stylix/commit/55418e8fc8d4696af619176a22cefcfac56ad2ef) | `` stylix: downgrade and lock base16-vim input (#811) `` |
| [`e646a134`](https://github.com/danth/stylix/commit/e646a134db5f4dcaf4fff4e8232229ae5f468cef) | `` waybar: fix typo (#810) ``                            |
| [`e81bd0cf`](https://github.com/danth/stylix/commit/e81bd0cffadaffecd18b65301628cc4b9b0dbea3) | `` waybar: add addCss option (#804) ``                   |

chore(flake/stylix): `6103431c` -> `55418e8f`

---

flake.lock

| Commit                                                                                           | Message                                                                     |
| ------------------------------------------------------------------------------------------------ | --------------------------------------------------------------------------- |
| [`cc9c8408`](https://github.com/LnL7/nix-darwin/commit/cc9c8408bb9f29b4afe919eff4ad922d054cf591) | `` Revert "{activation-scripts,activate-system}: purify environment" ``     |
| [`3509925a`](https://github.com/LnL7/nix-darwin/commit/3509925a8634f08b764922577d169757b94df97b) | `` readme: make `darwin-rebuild` use more explicit ``                       |
| [`2733527a`](https://github.com/LnL7/nix-darwin/commit/2733527a586bad9939edc829017 …

chore(flake/darwin): `5c12a6f4` -> `349a74c6`

---

flake.lock

| [`077cb071`](https://github.com/lovesegfault/vim-config/commit/077cb0719d1c9946c399ac529ef76f601120bdf6) | `` chore: use new dap-ui setting ``             |
| [`e4499275`](https://github.com/lovesegfault/vim-config/commit/e4499275b3a88c412e92e6a13b07f16cec34db39) | `` chore(flake/nixvim): 8e5422bf -> af4483c0 `` |

chore(flake/lovesegfault-vim-config): `e005ab8e` -> `077cb071`

---

flake.lock

| [`aebddca7`](https://github.com/lovesegfault/vim-config/commit/aebddca75ebe2657f735166838da7a0fd7010d05) | `` chore(flake/nixvim): af4483c0 -> eeafe2a7 ``      |
| [`b5225883`](https://github.com/lovesegfault/vim-config/commit/b522588360b081c59649c934180237430cb93fb3) | `` chore(flake/treefmt-nix): f2cc121d -> bebf27d0 `` |

chore(flake/lovesegfault-vim-config): `077cb071` -> `aebddca7`

---

flake.lock

| [`d71828a7`](https://github.com/nix-community/home-manager/commit/d71828a7dd0dc53cf3994e8737c84b4180cc6dfa) | `` ghostty: allow darwin users to manager their config (#6300) `` |
| [`c4650fb9`](https://github.com/nix-community/home-manager/commit/c4650fb9c0c4c8f7e1a43e6d72378246a4b50f3b) | `` cliphist: support multiple systemdTargets properly (#5669) ``  |
| [`5dc1c2e4`](https://github.com/nix-community/home-manager/commit/5dc1c2e40410 …

chore(flake/home-manager): `e1ae908b` -> `420a0d95`

---

flake.lock

| [`18d0a984`](https://github.com/nix-community/disko/commit/18d0a984cc2bc82cf61df19523a34ad463aa7f54) | `` flake.lock: Update `` |

chore(flake/disko): `bf0abfde` -> `18d0a984`

---

flake.lock

| Commit                                                                                                      | Message                                                                                                    |
| ----------------------------------------------------------------------------------------------------------- | ---------------------------------------------------------------------------------------------------------- |
| [`697ba131`](https://github.com/nix-community/home-manager/commit/697ba1319fdc58c94dc94cd7908df554dc48d970) | `` waybar: allow setting systemd.target to null (#6241) ``                                                 |
| [`6fbbfb92`](https://github.com/nix-community/home-manager/commit/6fbbfb92409bf999fd80b78c7f7bc145d2d36f39) | `` Revert "thunderbird: …

chore(flake/home-manager): `420a0d95` -> `697ba131`

---

flake.lock

| [`86a0d627`](https://github.com/nix-community/home-manager/commit/86a0d627cae02e8cc5d29eeb03de97f8c652a4bb) | `` home-manger: fix runtime closure (#5174) ``       |
| [`9ce5d0b8`](https://github.com/nix-community/home-manager/commit/9ce5d0b888a054945121394297ad34173d135547) | `` xdg-autostart: add module (#5251) ``              |
| [`7636b248`](https://github.com/nix-community/home-manager/commit/7636b248675e00d887ec0e6932c316d87f36dbf3) | `` hyprland: make …

chore(flake/home-manager): `697ba131` -> `86a0d627`

---

flake.lock

| [`d963ed33`](https://github.com/nix-community/home-manager/commit/d963ed335b890a70ed53eecf14cdb21528eda9b8) | `` linux-wallpaperengine: add module ``               |
| [`41f3dbd7`](https://github.com/nix-community/home-manager/commit/41f3dbd795fd89017232c1a6a90dc9d760334ef8) | `` linux-wallpaperengine: add ckgxrg as maintainer `` |

chore(flake/home-manager): `86a0d627` -> `d963ed33`

---

flake.lock

| [`ebfd73e5`](https://github.com/lovesegfault/vim-config/commit/ebfd73e554c4417036d700719c10ff59d3f0aea9) | `` chore(flake/nixvim): eeafe2a7 -> f584d1d7 `` |

chore(flake/lovesegfault-vim-config): `aebddca7` -> `ebfd73e5`

---

flake.lock

| Commit                                                                                        | Message                                                          |
| --------------------------------------------------------------------------------------------- | ---------------------------------------------------------------- |
| [`b00c9f46`](https://github.com/danth/stylix/commit/b00c9f46ae6c27074d24d2db390f0ac5ebcc329f) | `` nixcord: theme Vencord and Vesktop instead of just Vencord `` |
| [`d9df2b42`](https://github.com/danth/stylix/commit/d9df2b4200ba53a0944c3d2c6d242095e523d3d9) | `` kde: add decorations option and polish code (#772) ``         |

chore(flake/stylix): `55418e8f` -> `b00c9f46`

---

flake.lock

| Commit                                                                                           | Message                                                                                          |
| ------------------------------------------------------------------------------------------------ | ------------------------------------------------------------------------------------------------ |
| [`f1cf8c4f`](https://github.com/LnL7/nix-darwin/commit/f1cf8c4f5a853683494cd93acbdecedb61dfc179) | `` checks: fix sw_vers parameter for macOSVersion (`--productVersion`, not `-productVersion`) `` |

chore(flake/darwin): `349a74c6` -> `49b807fa`

---

flake.lock

| [`aa6d3bfe`](https://github.com/lovesegfault/vim-config/commit/aa6d3bfebc5f7b1801886d9bd8e5d17f622d1ca6) | `` chore(flake/nixvim): f584d1d7 -> 93df574b `` |

chore(flake/lovesegfault-vim-config): `ebfd73e5` -> `aa6d3bfe`

---

flake.lock

| [`a8159195`](https://github.com/nix-community/home-manager/commit/a8159195bfaef3c64df75d3b1e6a68d49d392be9) | `` flake-module: fix naming ``              |
| [`234613d7`](https://github.com/nix-community/home-manager/commit/234613d77c939ff2e2c0f2c476a56d80930e5b8b) | `` neovim: remove with lib ``               |
| [`86b0f304`](https://github.com/nix-community/home-manager/commit/86b0f3049c3a5f3e8ec13a54a323ed3e2587ed93) | `` hyprland: add null package tests ``      |
| …

chore(flake/home-manager): `bf2a029b` -> `a8159195`

---

flake.lock

| [`917b75f2`](https://github.com/lovesegfault/vim-config/commit/917b75f290cd4b8ba7612a28bcc5c92947639879) | `` chore(flake/nixpkgs): 852ff1d9 -> 9d3ae807 `` |
| [`592622e1`](https://github.com/lovesegfault/vim-config/commit/592622e17bb24249b9174b27bdd0f4d8167d8fd1) | `` chore(flake/nixvim): 93df574b -> c75e4ea3 ``  |

chore(flake/lovesegfault-vim-config): `aa6d3bfe` -> `917b75f2`

---

flake.lock

| [`801ddd86`](https://github.com/nix-community/home-manager/commit/801ddd8693481866c2cfb1efd44ddbae778ea572) | `` hyprland: use package stubs ``                          |
| [`9afd0220`](https://github.com/nix-community/home-manager/commit/9afd02201332756d4bbad273202ecc96049c53b2) | `` wayfire-stubs: add stubs for wayfire tests ``           |
| [`c4f28f28`](https://github.com/nix-community/home-manager/commit/c4f28f282f54fc15a60a3b258ecce77a44327958 …

chore(flake/home-manager): `a8159195` -> `801ddd86`

---

flake.lock

| [`34b64e4e`](https://github.com/NixOS/nixos-hardware/commit/34b64e4e1ddb14e3ffc7db8d4a781396dbbab773) | `` dell-inspiron-3442: init ``                    |
| [`21fa5853`](https://github.com/NixOS/nixos-hardware/commit/21fa58535d4a77283e4a85dccaf05dd0cf7af800) | `` apple/t2: kernel 6.12.4 -> 6.13 ``             |
| [`95c8efc0`](https://github.com/NixOS/nixos-hardware/commit/95c8efc0cb78ed190c03c6bd97f6dbbcdc0caaf8) | `` apple/t2: remove apple_set_os loader option `` |
| …

chore(flake/nixos-hardware): `dfad538f` -> `34b64e4e`

---

flake.lock

| [`055c6705`](https://github.com/nix-community/home-manager/commit/055c67056d87577a39af4144ad5eadb093cfb97d) | `` fcitx5: add waylandFrontend option to not set env vars (#5431) `` |

chore(flake/home-manager): `801ddd86` -> `055c6705`

---

flake.lock

| [`8544cd09`](https://github.com/nix-community/home-manager/commit/8544cd092047a7e92d0dce011108a563de7fc0f2) | `` lapce: add module (#5752) `` |

chore(flake/home-manager): `055c6705` -> `8544cd09`

---

flake.lock

| [`dae6d346`](https://github.com/nix-community/home-manager/commit/dae6d3460c8bab3ac9f38a86affe45b32818e764) | `` git: add default value null to programs.git.signing.key (#6032) `` |

chore(flake/home-manager): `8544cd09` -> `dae6d346`

---

flake.lock

| [`4d159cf9`](https://github.com/lovesegfault/vim-config/commit/4d159cf978006edcf8f81eb6d9e9e255b0f80082) | `` chore(flake/flake-parts): b905f6fc -> 32ea77a0 `` |
| [`e10a1591`](https://github.com/lovesegfault/vim-config/commit/e10a1591a64f5327b495174e068c52d2d1feda18) | `` chore(flake/nixvim): c75e4ea3 -> 2b039331 ``      |

chore(flake/lovesegfault-vim-config): `917b75f2` -> `4d159cf9`

---

flake.lock

| [`18fa9f32`](https://github.com/nix-community/home-manager/commit/18fa9f323d8adbb0b7b8b98a8488db308210ed93) | `` yazi: add main.lua support to plugins (#6394) `` |

chore(flake/home-manager): `dae6d346` -> `18fa9f32`

---

flake.lock

| [`46a8f5fc`](https://github.com/nix-community/nix-index-database/commit/46a8f5fc9552b776bfc5c5c96ea3bede33f68f52) | `` update generated.nix to release 2025-02-02-030235 `` |
| [`9000a22f`](https://github.com/nix-community/nix-index-database/commit/9000a22fbd820eedba37fc29a4b9652bfc3068c2) | `` flake.lock: Update ``                                |

chore(flake/nix-index-database): `79b7b8ea` -> `46a8f5fc`

---

flake.lock

| [`b8be6f78`](https://github.com/NixOS/nixos-hardware/commit/b8be6f78b073bbb5368b085953ba366c132eccf5) | `` codeowners: remove tomfitzhenry from pinebook-pro `` |

chore(flake/nixos-hardware): `34b64e4e` -> `537286c3`

---

flake.lock

| [`6299dcab`](https://github.com/lovesegfault/vim-config/commit/6299dcab62349aa18d55dcfd1d652bef71b51950) | `` chore(flake/nixpkgs): 9d3ae807 -> 3a228057 `` |
| [`d37108ba`](https://github.com/lovesegfault/vim-config/commit/d37108ba133258293dccfb5379c41e50b4077b5c) | `` chore(flake/nixvim): 2b039331 -> c284a509 ``  |
| [`2dcc2d9c`](https://github.com/lovesegfault/vim-config/commit/2dcc2d9c260bff1046ce9d62491c078408262c59) | `` ci: move arm to ubuntu 22.04 ``               |

chore(flake/lovesegfault-vim-config): `4d159cf9` -> `6299dcab`

---

flake.lock

| [`066ba0c5`](https://github.com/nix-community/home-manager/commit/066ba0c5cfddbc9e0dddaec73b1561ad38aa8abe) | `` flake-module: rename `homeModules` to `homeManagerModules` (#6392) `` |

chore(flake/home-manager): `18fa9f32` -> `066ba0c5`

---

flake.lock
users/bemeurer/graphical/linux.nix

| Commit                                                                                        | Message                                                                    |
| --------------------------------------------------------------------------------------------- | -------------------------------------------------------------------------- |
| [`d513f59d`](https://github.com/danth/stylix/commit/d513f59da5856978c363d2f82103f708f4a6024d) | `` stylix: update and simplify flake-compat instructions (#816) ``         |
| [`bae5cbb8`](https://github.com/danth/stylix/commit/bae5cbb8fb36bd74c5303df4f9727e640a15b10b) | `` doc: expand description of font units (#819) ``                         |
| [`596d6644`](https://github.com/danth/stylix/commit/596d6644077d6d25ff713e93b55efc867979959d) | …

chore(flake/stylix): `b00c9f46` -> `d513f59d`

---

flake.lock

| [`274dda76`](https://github.com/lovesegfault/vim-config/commit/274dda76d165b12f884caa1a875222b983ee5e97) | `` chore(flake/nixvim): c284a509 -> 6288354d `` |

chore(flake/lovesegfault-vim-config): `6299dcab` -> `274dda76`

---

flake.lock

| [`8b5ef473`](https://github.com/NixOS/nixos-hardware/commit/8b5ef47338c924c827c00dec69cf7108744fe199) | `` framework/13-inch/12th-gen-intel: add hdmi audio fix `` |

chore(flake/nixos-hardware): `537286c3` -> `9bdd53f5`

---

flake.lock

| [`092e406b`](https://github.com/lovesegfault/vim-config/commit/092e406b5ab4ca463d744bb74a676569e0479aab) | `` chore(flake/treefmt-nix): bebf27d0 -> 64dbb922 `` |

chore(flake/lovesegfault-vim-config): `274dda76` -> `092e406b`

---

flake.lock

| Commit                                                                                           | Message                                                                                |
| ------------------------------------------------------------------------------------------------ | -------------------------------------------------------------------------------------- |
| [`7c72c013`](https://github.com/LnL7/nix-darwin/commit/7c72c013b160627540b8b465a05ba258f47a16d8) | `` nixpkgs: make config.nixpkgs.{buildPlatform,hostPlatform} write only ``             |
| [`5084b332`](https://github.com/LnL7/nix-darwin/commit/5084b33265f1c14551af63e61ec8bb75fec3ccbc) | `` git-blame-ignore-revs: add `nixpkgs` module formatting commit ``                    |
| …

chore(flake/darwin): `49b807fa` -> `ae406c04`

---

flake.lock

| Commit                                                                                                      | Message                                                                           |
| ----------------------------------------------------------------------------------------------------------- | --------------------------------------------------------------------------------- |
| [`f20b7a8a`](https://github.com/nix-community/home-manager/commit/f20b7a8ab527a2482f13754dc00b2deaddc34599) | `` firefox: fix referencing firefox fork name in profile-specific docs (#6407) `` |
| [`3b6fde96`](https://github.com/nix-community/home-manager/commit/3b6fde96d8b41a4a21cbacba8de7debf7ea78021) | `` Translate using Weblate (Russian) ``                                           |
| …

chore(flake/home-manager): `59971126` -> `f20b7a8a`

---

flake.lock

| Commit                                                                                                   | Message                              |
| -------------------------------------------------------------------------------------------------------- | ------------------------------------ |
| [`b6cee0bb`](https://github.com/lovesegfault/vim-config/commit/b6cee0bb7bcd72fa8d392e42223c0801bbbb5270) | `` ci: move all arm jobs to 22.04 `` |

chore(flake/lovesegfault-vim-config): `092e406b` -> `b6cee0bb`

---

flake.lock

| [`3557e37f`](https://github.com/lovesegfault/vim-config/commit/3557e37f9a91273df0059e113c9a338d221a2aa6) | `` chore(flake/nixpkgs): 3a228057 -> 799ba5bf `` |
| [`0f8e6cca`](https://github.com/lovesegfault/vim-config/commit/0f8e6ccaf4b8a6031756991a56559e2710f05f06) | `` chore(flake/nixvim): 6288354d -> 11a80c1a ``  |

chore(flake/lovesegfault-vim-config): `b6cee0bb` -> `3557e37f`

---

flake.lock

| [`30ea6fed`](https://github.com/nix-community/home-manager/commit/30ea6fed4e4b41693cebc2263373dd810de4de49) | `` firefox: fix referencing name in profile-specific docs `` |

chore(flake/home-manager): `f20b7a8a` -> `30ea6fed`

---

flake.lock

| Commit                                                                                               | Message                                                                |
| ---------------------------------------------------------------------------------------------------- | ---------------------------------------------------------------------- |
| [`ff356885`](https://github.com/nix-community/disko/commit/ff3568858c54bd306e9e1f2886f0f781df307dff) | `` style: make it prettier ``                                          |
| [`68ef26bb`](https://github.com/nix-community/disko/commit/68ef26bb78dd4e6298bd273362a1f89a14beccc1) | `` fix: use zfs kernel module which corresponds to user-space tools `` |

chore(flake/disko): `18d0a984` -> `ff356885`

---

flake.lock

| [`f99c704f`](https://github.com/nix-community/home-manager/commit/f99c704fe3a4cf8d72b2d568ec80bc38be1a9407) | `` bash: Make sure HISTFILE's directory exists ``  |
| [`15bd6736`](https://github.com/nix-community/home-manager/commit/15bd673658c189491cd896f06b3dd8f09bb0dfe4) | `` firefox: remove old unused test file (#6403) `` |

chore(flake/home-manager): `30ea6fed` -> `f99c704f`

---

flake.lock

| [`43379927`](https://github.com/nix-community/home-manager/commit/433799271274c9f2ab520a49527ebfe2992dcfbd) | `` wayland: create tray.target if xsession is not enabled (#6332) `` |

chore(flake/home-manager): `f99c704f` -> `43379927`

---

flake.lock

| [`9635acbd`](https://github.com/lovesegfault/vim-config/commit/9635acbd9fa59b5aac46c2b2759435583756fefe) | `` chore(flake/nixvim): 11a80c1a -> 5024ef21 `` |

chore(flake/lovesegfault-vim-config): `3557e37f` -> `9635acbd`

---

flake.lock

| Commit                                                                                         | Message                                                                                                           |
| ---------------------------------------------------------------------------------------------- | ----------------------------------------------------------------------------------------------------------------- |
| [`3282b5f2`](https://github.com/NixOS/nixpkgs/commit/3282b5f2cb02f86539d0015720efeffda82f3a66) | `` python312Packages.thinc: relax blis constraint ``                                                              |
| [`41b9be71`](https://github.com/NixOS/nixpkgs/commit/41b9be717760853e2b8f727734182461177142bf) | `` Revert "python3Packages.thinc: 8.3.0 -> 9.1.1" `` …

chore(flake/nixpkgs): `3a228057` -> `550e11f2`

---

flake.lock

| [`127dd418`](https://github.com/lovesegfault/vim-config/commit/127dd418c58da57052d8dc05647da911a1ecaf4b) | `` chore(flake/treefmt-nix): 64dbb922 -> 4f09b473 `` |
| [`2ea42019`](https://github.com/lovesegfault/vim-config/commit/2ea4201994d21f7a81029bbda692296c0df3d42d) | `` chore(flake/nixvim): 5024ef21 -> e7f20a60 ``      |

chore(flake/lovesegfault-vim-config): `9635acbd` -> `127dd418`

---

flake.lock

| [`c32e4b2e`](https://github.com/lovesegfault/vim-config/commit/c32e4b2e1674fd2e627c7ade6f1ce098872ae39c) | `` chore(flake/nixpkgs): 799ba5bf -> 550e11f2 `` |

chore(flake/lovesegfault-vim-config): `127dd418` -> `c32e4b2e`

---

flake.lock

| [`830a2ca7`](https://github.com/NixOS/nixpkgs/commit/830a2ca72eb06ff87c1f851cec637feaedebd30f) | `` vangers: init at 2.0-unstable-2024-09-30 ``                                      |
| [`e8d0b02a`](https://github.com/NixOS/nixpkgs/commit/e8d0b02af0958823c955aaab3c82b03f54411d91) | `` Add rocqPackages.bignums ``                                                      |
| …

chore(flake/nixpkgs): `550e11f2` -> `a3eaf5e8`

---

flake.lock

| [`947eef9e`](https://github.com/nix-community/home-manager/commit/947eef9e99c42346cf0aac2bebe1cd94924c173b) | `` neovim: disable neovim-coc-config test `` |

chore(flake/home-manager): `43379927` -> `947eef9e`

---

flake.lock

| [`708770fc`](https://github.com/danth/stylix/commit/708770fcb045b6efb4c419ff7be9760d010699bc) | `` wayfire: init (#765) `` |
| [`b3ef236d`](https://github.com/danth/stylix/commit/b3ef236d22572618828f9e7019362cc89d877bd0) | `` glance: init (#827) ``  |
| [`87791e06`](https://github.com/danth/stylix/commit/87791e0665bd345127b7f35aca6e9195e74ef39c) | `` halloy: init (#825) ``  |

chore(flake/stylix): `d513f59d` -> `708770fc`

---

flake.lock

| Commit                                                                                           | Message                                                            |
| ------------------------------------------------------------------------------------------------ | ------------------------------------------------------------------ |
| [`d634e28f`](https://github.com/LnL7/nix-darwin/commit/d634e28f67b5e1fc82b3ea107fbd9b3a3abf3a7b) | `` users: use `launchctl managername` to determine session type `` |
| [`0824c138`](https://github.com/LnL7/nix-darwin/commit/0824c13801d18722a5dd7827f575f5c42e80ad43) | `` checks: fix macOS version check exit code ``                    |
| [`3f6f5124`](https://github.com/LnL7/nix-darwin/commit/3f6f512406d852afa0e54118b2002896da66fd3e) | `` users: fix typo …

chore(flake/darwin): `ae406c04` -> `3f4351d2`

---

flake.lock

| [`bf9a1a06`](https://github.com/nix-community/home-manager/commit/bf9a1a068919ccdfa7d130873936c5fd4c826e85) | `` Translate using Weblate (Swedish) ``    |
| [`90a4374b`](https://github.com/nix-community/home-manager/commit/90a4374b174edb88a2e36889ee39ce45a186c7f6) | `` Translate using Weblate (Portuguese) `` |

chore(flake/home-manager): `947eef9e` -> `bf9a1a06`

---

flake.lock

| Commit                                                                                           | Message                                                                             |
| ------------------------------------------------------------------------------------------------ | ----------------------------------------------------------------------------------- |
| [`da331139`](https://github.com/LnL7/nix-darwin/commit/da3311397a1a2ba1a02f026cce1700a3556279cc) | `` Revert "nixpkgs: make config.nixpkgs.{buildPlatform,hostPlatform} write only" `` |

chore(flake/darwin): `3f4351d2` -> `0b6f96a6`

---

flake.lock

| [`5af1b9a0`](https://github.com/nix-community/home-manager/commit/5af1b9a0f193ab6138b89a8e0af8763c21bbf491) | `` treewide: standardize shell integration options `` |

chore(flake/home-manager): `bf9a1a06` -> `5af1b9a0`

---

flake.lock

| [`895d81b6`](https://github.com/nix-community/nix-index-database/commit/895d81b6228bbd50a6ef22f5a58a504ca99763ea) | `` update generated.nix to release 2025-02-09-031200 `` |
| [`3e945f71`](https://github.com/nix-community/nix-index-database/commit/3e945f71fc42396bc15d90be67796ee922d5c162) | `` flake.lock: Update ``                                |

chore(flake/nix-index-database): `46a8f5fc` -> `895d81b6`

---

flake.lock

| Commit                                                                                        | Message                                                                     |
| --------------------------------------------------------------------------------------------- | --------------------------------------------------------------------------- |
| [`e72aa84d`](https://github.com/danth/stylix/commit/e72aa84da1c6982c11620a4154ded8c603f33f46) | `` {vencord,vesktop}: revert attempt to support fonts (#844) ``             |
| [`7818098f`](https://github.com/danth/stylix/commit/7818098f4df4ee73667036c65909cf311d36968b) | `` treewide: remove trailing whitespaces and add trailing newline (#841) `` |
| [`be606eaa`](https://github.com/danth/stylix/commit/be606eaa87dfcf22c98f80453b42ec40dcbcdf36) …

chore(flake/stylix): `ff8ce4f3` -> `e72aa84d`

---

flake.lock

| [`ad2e0790`](https://github.com/lovesegfault/vim-config/commit/ad2e0790c461d87f22b41d499fe1a32f45047d79) | `` chore(flake/nixvim): e7f20a60 -> 13341a4c `` |

chore(flake/lovesegfault-vim-config): `c32e4b2e` -> `ad2e0790`

---

flake.lock

| [`84933941`](https://github.com/nix-community/lanzaboote/commit/849339412ceacddd2f71742b8491542933ed64a3) | `` docs: Fix nix-collect-garbage command syntax `` |

chore(flake/lanzaboote): `a65905a0` -> `3bdeebbc`

---

flake.lock

| [`eb5f8175`](https://github.com/danth/stylix/commit/eb5f81756731a3eefa42b1caf494ba5a9c8aedb4) | `` {vencord,vesktop}: support fonts without IFD (#846) `` |
| [`2c1d493c`](https://github.com/danth/stylix/commit/2c1d493c5f5af6caec9f02a5c3d88d84ee2f10b8) | `` qt: respect stylix.enable (#847) ``                    |

chore(flake/stylix): `e72aa84d` -> `eb5f8175`

---

flake.lock

| [`4af2686c`](https://github.com/danth/stylix/commit/4af2686c1c62176d0ce28c4d55e813ae5ed52b6f) | `` nixcord: use new template format (#852) ``       |
| [`7f0154c3`](https://github.com/danth/stylix/commit/7f0154c371a847d23eace73f6daaa814d2d42261) | `` neovim: fix SignColumn transparency (#628) ``    |
| [`65eae5aa`](https://github.com/danth/stylix/commit/65eae5aaa2169ed4f6a066b4da698cb0e07b2719) | `` kde: fix KDE apps ignoring colorscheme (#850) `` |

chore(flake/stylix): `eb5f8175` -> `4af2686c`

---

flake.lock

| Commit                                                                                                      | Message                                                                                    |
| ----------------------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------------ |
| [`e5854b98`](https://github.com/nix-community/home-manager/commit/e5854b98cd759b91c83ba5caa5ff32f274f1dc78) | `` flake-module: change type from lazyAttrsOf raw to lazyAttrsOf deferredModule (#6408) `` |
| [`5795f792`](https://github.com/nix-community/home-manager/commit/5795f792abf38e4f2701b4f7454deeb8e2575ae4) | `` yazi: organization tweak `` …

chore(flake/home-manager): `b0bd29bb` -> `e5854b98`

---

flake.lock

| Commit                                                                                           | Message                                |
| ------------------------------------------------------------------------------------------------ | -------------------------------------- |
| [`c31b6e8a`](https://github.com/LnL7/nix-darwin/commit/c31b6e8a0305fee46238387a3462ec060e377500) | `` homebrew: use `mas` from Nixpkgs `` |

chore(flake/darwin): `0b6f96a6` -> `a36049da`

---

flake.lock

| [`ba4a1a11`](https://github.com/nix-community/home-manager/commit/ba4a1a110204c27805d1a1b5c8b24b3a0da4d063) | `` ludusavi: create Ludusavi module (#5626) `` |

chore(flake/home-manager): `e5854b98` -> `ba4a1a11`

---

flake.lock

| [`8f351726`](https://github.com/nix-community/home-manager/commit/8f351726c5841d86854e7fa6003ea472352f5208) | `` git-worktree-switcher: use lib.hm.shell.mkShellIntegrationOption `` |
| [`9c8169b4`](https://github.com/nix-community/home-manager/commit/9c8169b4466391999b1ad5ea86be4e79d560af52) | `` git-worktree-switcher: init module ``                               |
| …

chore(flake/home-manager): `ba4a1a11` -> `8f351726`

---

flake.lock

| [`f0a31d38`](https://github.com/nix-community/home-manager/commit/f0a31d38e6de48970ce1fe93e6ea343e20a9c80a) | `` neomutt: fix default for 'map' in macros/binds (#6429) `` |

chore(flake/home-manager): `8f351726` -> `f0a31d38`

---

flake.lock

| [`83bd3a26`](https://github.com/nix-community/home-manager/commit/83bd3a26ac0526ae04fa74df46738bb44b89dcdd) | `` email: add migadu.com flavor `` |

chore(flake/home-manager): `f0a31d38` -> `83bd3a26`

---

flake.lock

| Commit                                                                                         | Message                                                                                 |
| ---------------------------------------------------------------------------------------------- | --------------------------------------------------------------------------------------- |
| [`64e75cd4`](https://github.com/NixOS/nixpkgs/commit/64e75cd44acf21c7933d61d7721e812eac1b5a0a) | `` oh-my-zsh: Fix template (#380911) ``                                                 |
| [`f580aca5`](https://github.com/NixOS/nixpkgs/commit/f580aca59ba9fbd25dc6515c382b4f56d5441347) | `` _389-ds-base: fix cargo deps vendoring ``                                            |
| …

chore(flake/nixpkgs): `a3eaf5e8` -> `64e75cd4`

---

flake.lock

| [`e86de61b`](https://github.com/danth/stylix/commit/e86de61bb8f5f2b6459d0be3e3291ad16db4b777) | `` gnome: fix Home Manager activation (#860) `` |

chore(flake/stylix): `d8289c3f` -> `e86de61b`

---

flake.lock

| [`15b59d41`](https://github.com/nix-community/home-manager/commit/15b59d4191b993ebdfcb1f61b834fced217882ba) | `` eww: fix eww source creation ``                                   |
| [`d303453b`](https://github.com/nix-community/home-manager/commit/d303453b134cff1dec350ae2e50fec34d06bee73) | `` eww: add null configDir test ``                                   |
| [`1f6fa878`](https://github.com/nix-community/home-manager/commit/ …

chore(flake/home-manager): `83bd3a26` -> `15b59d41`

---

flake.lock

| [`674dda4e`](https://github.com/lovesegfault/vim-config/commit/674dda4ef669fe95fc87494c905d94b485ec051c) | `` chore(flake/nixpkgs): 550e11f2 -> 64e75cd4 `` |

chore(flake/lovesegfault-vim-config): `ad2e0790` -> `674dda4e`

---

flake.lock

| Commit                                                                                                      | Message                                                                                                           |
| ----------------------------------------------------------------------------------------------------------- | ----------------------------------------------------------------------------------------------------------------- |
| [`c9d343cf`](https://github.com/nix-community/home-manager/commit/c9d343cfa0565671cc7e8d5aefebaf61cc840abd) | `` docs(zellij): `programs.zellij.settings` are serialized as `kdl` and not `yaml` from version 0.32.0 (#6010) `` |

chore(flake/home-manager): `15b59d41` -> `c9d343cf`

---

flake.lock

| [`61a7777e`](https://github.com/lovesegfault/vim-config/commit/61a7777e9a791ea3f72472f67d34cfa3adb19853) | `` chore(flake/nixvim): 78b6f8e1 -> 7f29e4b2 `` |

chore(flake/lovesegfault-vim-config): `1264cd35` -> `61a7777e`

---

flake.lock

| Commit                                                                                               | Message                                                       |
| ---------------------------------------------------------------------------------------------------- | ------------------------------------------------------------- |
| [`e5115915`](https://github.com/nix-community/disko/commit/e51159153b5fbe5c41caab41a7212df93c42d34b) | `` make-disk-image: format natively ``                        |
| [`64383404`](https://github.com/nix-community/disko/commit/64383404151be67ac1804fce50e139bab7eaebb3) | `` make-disk-image: add binfmt emulation ``                   |
| [`85942f35`](https://github.com/nix-community/disko/commit/85942f35d345daf4d402c05a8ee0c52f414a2168) | `` Revert "Fix: …

chore(flake/disko): `40da43e8` -> `e5115915`

---

flake.lock

| Commit                                                                                           | Message                                                                      |
| ------------------------------------------------------------------------------------------------ | ---------------------------------------------------------------------------- |
| [`5926058a`](https://github.com/LnL7/nix-darwin/commit/5926058aecd67ec1bf5030b5a419c260876ea9ba) | `` nix: place `extra-`prefixed settings after their non-prefixed variants `` |
| [`731910af`](https://github.com/LnL7/nix-darwin/commit/731910af010086c4dbe23eb6ae79d81bcec703aa) | `` {activation-scripts,activate-system}: check `gcroots` before linking ``   |
| [`cd445c54`](https://github.com/LnL7/nix-darwin/commit/cd445c546561d5ca4e9124c …

chore(flake/darwin): `a6746213` -> `678b2264`

---

flake.lock

| [`9f8f1c54`](https://github.com/lovesegfault/vim-config/commit/9f8f1c545777cb3848a42310aba28e4b1b1e3d5f) | `` chore(flake/nixpkgs): 64e75cd4 -> 2ff53fe6 `` |
| [`88d432d7`](https://github.com/lovesegfault/vim-config/commit/88d432d7688fee93bf300de1d7af1ffb5edebef6) | `` chore(flake/nixvim): 7f29e4b2 -> a39e0a65 ``  |

chore(flake/lovesegfault-vim-config): `61a7777e` -> `9f8f1c54`

---

flake.lock

| [`4edb87a2`](https://github.com/nix-community/disko/commit/4edb87a2ac9010da6fea50fc56d67e123fca85f4) | `` test explicit gpt uuid optoin ``                  |
| [`a825e29a`](https://github.com/nix-community/disko/commit/a825e29a3b8246fa42a0b6ea38aab620c73ac783) | `` Use regex for UUID, adjust documentation a bit `` |
| [`bf440582`](https://github.com/nix-community/disko/commit/bf440582c49d48696a6bcbc2bc90d617be1f214d) | `` Use `concatMapStrings` ``                         | …

chore(flake/disko): `e5115915` -> `4edb87a2`

---

flake.lock

| Commit                                                                                               | Message                                   |
| ---------------------------------------------------------------------------------------------------- | ----------------------------------------- |
| [`5d6c85c1`](https://github.com/nix-community/disko/commit/5d6c85c1d0bd634d46a9604e93bce935a06e033b) | `` Update tests/zfs-encrypted-root.nix `` |
| [`d478e2f9`](https://github.com/nix-community/disko/commit/d478e2f9f3dd7b305e9a8a4fd234cfe52c770823) | `` zfs: add example for encrypted root `` |

chore(flake/disko): `4edb87a2` -> `5d6c85c1`

---

flake.lock

| [`7dcd5cda`](https://github.com/nix-community/disko/commit/7dcd5cda34cba135e4851b92bae6deb859af3884) | `` add .git-blame-ignore-revs `` |
| [`ff2d853a`](https://github.com/nix-community/disko/commit/ff2d853a8451a802786878e70324a4781d40d62d) | `` treewide: format all files `` |
| [`c23ac289`](https://github.com/nix-community/disko/commit/c23ac2891c78e89766e58a1c075d903db53baf6f) | `` setup treefmt ``              |

chore(flake/disko): `5d6c85c1` -> `7dcd5cda`

---

flake.lock

| Commit                                                                                               | Message         |
| ---------------------------------------------------------------------------------------------------- | --------------- |
| [`eb0e21b3`](https://github.com/nix-community/disko/commit/eb0e21b33bb9a0d948a2355bf4da35ca70a4c8f2) | `` Fix typos `` |

chore(flake/disko): `7dcd5cda` -> `eb0e21b3`

---

flake.lock

| Commit                                                                                               | Message                              |
| ---------------------------------------------------------------------------------------------------- | ------------------------------------ |
| [`fa5746ec`](https://github.com/nix-community/disko/commit/fa5746ecea1772cf59b3f34c5816ab3531478142) | `` types disk: fix deviceOrdering `` |

chore(flake/disko): `eb0e21b3` -> `fa5746ec`

---

flake.lock

| [`ff06c95b`](https://github.com/lovesegfault/vim-config/commit/ff06c95bd78a21d2f7d67e9097f9ea9e17646873) | `` chore(flake/nixvim): a39e0a65 -> b8c55873 `` |

chore(flake/lovesegfault-vim-config): `9f8f1c54` -> `ff06c95b`

---

flake.lock

| [`ae15068e`](https://github.com/nix-community/nix-index-database/commit/ae15068e79e22b76c344f0d7f8aed1bb1c5b0b63) | `` update generated.nix to release 2025-02-16-031500 `` |
| [`52ef1072`](https://github.com/nix-community/nix-index-database/commit/52ef1072d57cfd0b4d2c375d646e7420ae2f5901) | `` flake.lock: Update ``                                |

chore(flake/nix-index-database): `895d81b6` -> `ae15068e`

---

flake.lock

| [`4c63819e`](https://github.com/lovesegfault/vim-config/commit/4c63819e64081b749cd5ce681153399c561095d7) | `` chore(flake/nixpkgs): 2ff53fe6 -> 8bb37161 `` |
| [`3b66922d`](https://github.com/lovesegfault/vim-config/commit/3b66922d50fc667878ea68b53b40b72518111cc0) | `` chore(flake/nixvim): b8c55873 -> d636d254 ``  |

chore(flake/lovesegfault-vim-config): `ff06c95b` -> `4c63819e`

---

flake.lock

| [`be1e4321`](https://github.com/nix-community/disko/commit/be1e4321c9fb3a4bc2c061dafcdb424937a74dad) | `` tests/disko-install: make faster by optimizing closure size `` |

chore(flake/disko): `fa5746ec` -> `be1e4321`

---

flake.lock

| [`662fa98b`](https://github.com/nix-community/home-manager/commit/662fa98bf488daa82ce8dc2bc443872952065ab9) | `` nixpkgs-disabled: warn instead of assert (#6466) ``                     |
| [`25870c66`](https://github.com/nix-community/home-manager/commit/25870c6600660c93c5aa10f0f328a5eecd60150b) | `` nixos/common: fix `options` reference (#6473) ``                        |
| …

chore(flake/home-manager): `5031c6d2` -> `662fa98b`

---

flake.lock

| [`af4a5806`](https://github.com/nix-community/disko/commit/af4a580628e98302bb922c01e1169ce08d7bee57) | `` docs/disko-images: fix codeblocks ``      |
| [`dc4687a5`](https://github.com/nix-community/disko/commit/dc4687a53d8246a60349018684663afcd7485397) | `` docs: disko-images: add binfmt section `` |

chore(flake/disko): `be1e4321` -> `af4a5806`

---

flake.lock

| [`3e2ea8a4`](https://github.com/NixOS/nixos-hardware/commit/3e2ea8a49d4d76276b0f4e2041df8ca5c0771371) | `` feat: Add support for Dell XPS 15-9530 with NVIDIA graphics `` |
| [`08c94a8b`](https://github.com/NixOS/nixos-hardware/commit/08c94a8b62d784a610cbaa5d2da8a13b405c2c4f) | `` docs: Add README file for Dell XPS 15 9530 ``                  |
| [`e47365f3`](https://github.com/NixOS/nixos-hardware/commit/e47365f377fddfaae2a62109ed3dfd8922c6795f) …

chore(flake/nixos-hardware): `2eccff41` -> `3e2ea8a4`

---

flake.lock

| Commit                                                                                                  | Message                                                                       |
| ------------------------------------------------------------------------------------------------------- | ----------------------------------------------------------------------------- |
| [`283facbd`](https://github.com/tinted-theming/schemes/commit/283facbd2aa74e345972f00e56a11d901e6f01f9) | `` Fixes Brushtrees being marked as dark despite being a light theme (#39) `` |

chore(flake/tinted-schemes): `ae31625b` -> `283facbd`

---

flake.lock

| [`edad23eb`](https://github.com/nix-community/home-manager/commit/edad23ebc1bcc226ef5eb57c8d779b9b425adca1) | `` mako: add max-history option (#6009) ``       |
| [`f4f6dd26`](https://github.com/nix-community/home-manager/commit/f4f6dd26985f1e44721325cb6d783d0cf4cd4dbc) | `` git: fix setting format on >=25.05 (#6480) `` |

chore(flake/home-manager): `9d0d48f4` -> `edad23eb`

---

flake.lock

| [`d7963c89`](https://github.com/lovesegfault/vim-config/commit/d7963c891bf3af8211ae668b11b5e01cbd6f4fe4) | `` chore(flake/treefmt-nix): 4f09b473 -> 3d0579f5 `` |
| [`006e7822`](https://github.com/lovesegfault/vim-config/commit/006e7822236a75e9a195dee7ecd52c96810781fe) | `` chore(flake/nixvim): d636d254 -> 3a66c8a3 ``      |

chore(flake/lovesegfault-vim-config): `4dc026fe` -> `d7963c89`

---

flake.lock

| Commit                                                                                        | Message                                                             |
| --------------------------------------------------------------------------------------------- | ------------------------------------------------------------------- |
| [`7feb1c29`](https://github.com/danth/stylix/commit/7feb1c29bf39ebe6b2984b2f77f9ad38f486e311) | `` discord: combine nixcord, vencord, and vesktop modules (#854) `` |

chore(flake/stylix): `21d68dab` -> `7feb1c29`

---

flake.lock

| [`6c93eea8`](https://github.com/nix-community/home-manager/commit/6c93eea85daddd0dc8d4a3a687473461f3122961) | `` firefox: add HPSaucii maintainer ``                |
| [`27ffa351`](https://github.com/nix-community/home-manager/commit/27ffa35178bc6f359293a8809d32c5da23aaabc7) | `` firefox: add support for configuring extensions `` |
| [`3a0cf8f1`](https://github.com/nix-community/home-manager/commit/3a0cf8f1aae507ec9bb8c141369458ca0244a01b) | `` maintainers: …

chore(flake/home-manager): `edad23eb` -> `6c93eea8`

---

flake.lock

| [`3d964824`](https://github.com/lovesegfault/vim-config/commit/3d9648240706c8b0277c00ed48e7912d0b644844) | `` chore(flake/nixpkgs): 8bb37161 -> d74a2335 `` |

chore(flake/lovesegfault-vim-config): `d7963c89` -> `3d964824`

---

flake.lock

| Commit                                                                                               | Message              |
| ---------------------------------------------------------------------------------------------------- | -------------------- |
| [`15dbf8ce`](https://github.com/nix-community/disko/commit/15dbf8cebd8e2655a883b74547108e089f051bf0) | `` docs: fix typo `` |

chore(flake/disko): `af4a5806` -> `15dbf8ce`

---

flake.lock

| [`5cfbf5cc`](https://github.com/nix-community/home-manager/commit/5cfbf5cc37a3bd1da07ae84eea1b828909c4456b) | `` flake: don't import modules (#6481) ``      |
| [`69dfc316`](https://github.com/nix-community/home-manager/commit/69dfc316c5b5f2de1d68e477393fecbf19a0cdba) | `` mise: enable nushell integration (#6363) `` |

chore(flake/home-manager): `6c93eea8` -> `5cfbf5cc`

---

flake.lock

| [`d171b19c`](https://github.com/danth/stylix/commit/d171b19c1c76c32f9c8303a43d0176257aa25034) | `` qt: add temporary warnings for plasma6 (#845) `` |

chore(flake/stylix): `7feb1c29` -> `d171b19c`

---

flake.lock

| [`eb7b19c2`](https://github.com/danth/stylix/commit/eb7b19c26030c534664c840405c995a493a98013) | `` plymouth: support question and message widgets (#842) `` |
| [`9343b660`](https://github.com/danth/stylix/commit/9343b660c914a95d4a90f6bd40cda7c87b401445) | `` stylix: fix palette generator caching (#867) ``          |

chore(flake/stylix): `d171b19c` -> `eb7b19c2`

---

flake.lock

| [`a135aae1`](https://github.com/nix-community/home-manager/commit/a135aae1be749a10227413f9eb944a6f887dab86) | `` flake.nix: remove deprecations (#6485) `` |

chore(flake/home-manager): `5cfbf5cc` -> `a135aae1`

---

flake.lock

| [`ffc49528`](https://github.com/lovesegfault/vim-config/commit/ffc4952886f1d8aac192248de78c7dced0ca0b13) | `` chore(flake/nixvim): 3a66c8a3 -> 0ab99471 `` |

chore(flake/lovesegfault-vim-config): `3d964824` -> `ffc49528`

---

flake.lock

| [`97ac0801`](https://github.com/nix-community/home-manager/commit/97ac0801d187b2911e8caa45316399de12f6f199) | `` firefox: prevent extensions settings override (#6490) `` |
| [`4044ad19`](https://github.com/nix-community/home-manager/commit/4044ad191fb07bf3b17714d6aedec1960bc079d4) | `` fish: accept multiple events (#6489) ``                  |

chore(flake/home-manager): `a135aae1` -> `97ac0801`

---

flake.lock

| [`e21d0798`](https://github.com/LnL7/nix-darwin/commit/e21d07988b30adbd5b77d16f9fa40b7d5fc00a09) | `` dock: refactor persistent-apps option `` |
| [`02ba211e`](https://github.com/LnL7/nix-darwin/commit/02ba211ea19fb4e5a5da2e24a6ebbed526f5231d) | `` dock: allow setting tile-types ``        |

chore(flake/darwin): `678b2264` -> `6ab392f6`

---

flake.lock

| [`1c189f01`](https://github.com/nix-community/home-manager/commit/1c189f011447810af939a886ba7bee33532bb1f9) | `` tests/home-cursor: init (#6496) `` |

chore(flake/home-manager): `97ac0801` -> `1c189f01`

---

flake.lock

| [`21b287c5`](https://github.com/lovesegfault/vim-config/commit/21b287c51d4d47a4360a0e906bb95555546a366e) | `` chore(flake/nixpkgs): d74a2335 -> 73cf49b8 `` |

chore(flake/lovesegfault-vim-config): `ffc49528` -> `21b287c5`

---

flake.lock

| Commit                                                                                                      | Message                                                                                  |
| ----------------------------------------------------------------------------------------------------------- | ---------------------------------------------------------------------------------------- |
| [`0c0b0ac8`](https://github.com/nix-community/home-manager/commit/0c0b0ac8af6ca76b1fcb514483a9bd73c18f1e8c) | `` flake-module: use raw for homeConfgurations and deferredModule for modules (#6504) `` |

chore(flake/home-manager): `1c189f01` -> `0c0b0ac8`

---

flake.lock

| Commit                                                                                        | Message                                                 |
| --------------------------------------------------------------------------------------------- | ------------------------------------------------------- |
| [`c424b223`](https://github.com/danth/stylix/commit/c424b22396c5e40d2513ce03f94d0aa6d9cdd38f) | `` swaylock: avoid inadvertently installing Swaylock `` |
| [`07797994`](https://github.com/danth/stylix/commit/0779799431088b10e0499ef04c2c7901df1087a4) | `` rio: init (#882) ``                                  |

chore(flake/stylix): `aeb550ad` -> `c424b223`

---

flake.lock

| Commit                                                                                                | Message                                                                                             |
| ----------------------------------------------------------------------------------------------------- | --------------------------------------------------------------------------------------------------- |
| [`18e9f975`](https://github.com/NixOS/nixos-hardware/commit/18e9f9753e9ae261bcc7d3abe15745686991fd30) | `` dell-xps-15-9570: fix imports, refactor (closer to recent profiles and more explicit) (#1331) `` |

chore(flake/nixos-hardware): `3e2ea8a4` -> `18e9f975`

---

flake.lock

| [`8b6edfdf`](https://github.com/danth/stylix/commit/8b6edfdfa87e725cd7b593b390f15e6556449269) | `` {vencord,vesktop}: remove duplicate testbeds (#885) `` |

chore(flake/stylix): `c424b223` -> `8b6edfdf`

---

flake.lock

| [`3c822853`](https://github.com/nix-community/home-manager/commit/3c82285348bc811b723014cf4dba2f87e7ffc885) | `` vinegar: add module (#6494) `` |

chore(flake/home-manager): `0c0b0ac8` -> `3c822853`

---

flake.lock

| Commit                                                                                                  | Message                             |
| ------------------------------------------------------------------------------------------------------- | ----------------------------------- |
| [`59d9dc3b`](https://github.com/tinted-theming/schemes/commit/59d9dc3b27f76862aa35ea46289561e086f531ff) | `` Added Valua ColorScheme (#40) `` |

chore(flake/tinted-schemes): `283facbd` -> `59d9dc3b`

---

flake.lock

| Commit                                                                                                      | Message                                                                       |
| ----------------------------------------------------------------------------------------------------------- | ----------------------------------------------------------------------------- |
| [`bdf73272`](https://github.com/nix-community/home-manager/commit/bdf73272a8408fedc7ca86d5ea47192f6d2dad54) | `` swayimg: add module (#6506) ``                                             |
| [`1a78a4c7`](https://github.com/nix-community/home-manager/commit/1a78a4c7fe9d484c1de9ff0e46007f1970fd0a73) | `` firefox: fix build failure when package is null ``                         |
| …

chore(flake/home-manager): `3c822853` -> `bdf73272`

---

flake.lock

| [`9f74e14a`](https://github.com/nix-community/home-manager/commit/9f74e14a2d9af4c6f2024cca7813b830b020f45e) | `` fcitx5: make boot after graphical session (#6432) ``               |
| [`6eed33a3`](https://github.com/nix-community/home-manager/commit/6eed33a3acb933224917964879634826716a3e5d) | `` jetbrains-remote: do not fail if files do not exist yet (#6502) `` |
| [`dde2fba6`](https://github.com/nix-community/home-manager/com …

chore(flake/home-manager): `bdf73272` -> `9f74e14a`

---

flake.lock

| [`765cb91e`](https://github.com/nix-community/home-manager/commit/765cb91e9d5ab06ed8c92c25fc0e51d6c11d43cb) | `` psd: add missing module config options (#6230) `` |
| [`62d038f4`](https://github.com/nix-community/home-manager/commit/62d038f499b94d406df790dec04e201d222e5098) | `` nushell: reenable test ``                         |
| [`f0837fa6`](https://github.com/nix-community/home-manager/commit/f0837fa6730ad497f0329722263e2ef4683b09cf) | `` flake.lock: …

chore(flake/home-manager): `9f74e14a` -> `765cb91e`

---

flake.lock

| [`f4a07823`](https://github.com/nix-community/home-manager/commit/f4a07823a298deff0efb0db30f9318511de7c232) | `` chromium: add nativeMessagingHosts option (#6019) ``         |
| [`2b382e49`](https://github.com/nix-community/home-manager/commit/2b382e499aa2fa7ac78bdf1cee079d45fb3a0334) | `` earthly: init module (#6265) ``                              |
| [`c31b4e33`](https://github.com/nix-community/home-manager/commit/c31b4e330e40a4fbf55c …

chore(flake/home-manager): `765cb91e` -> `f4a07823`

---

flake.lock

| [`a51e94e5`](https://github.com/nix-community/home-manager/commit/a51e94e51c7df10f078a2530ce125df7410b4f33) | `` clipse: add module (#5777) ``                              |
| [`34d524f3`](https://github.com/nix-community/home-manager/commit/34d524f3edcf3a04c00ad2c09c24ec9d35d937f9) | `` imapnotify-accounts: remove with lib ``                    |
| [`dd21b9af`](https://github.com/nix-community/home-manager/commit/dd21b9afd5fefb0c80c396286970 …

chore(flake/home-manager): `f4a07823` -> `a51e94e5`

---

flake.lock

| [`cb3f6e9b`](https://github.com/nix-community/home-manager/commit/cb3f6e9b59d3a5e51ef9f7da2b8418d5c72aaef8) | `` htop: write-protect entire configuration directory ``                     |
| [`61d8f836`](https://github.com/nix-community/home-manager/commit/61d8f8366fc327a42cc212d62dfff06ae0c3f195) | `` htop: export defaultFields into lib ``                                    |
| …

chore(flake/home-manager): `a51e94e5` -> `cb3f6e9b`

---

flake.lock

| [`fb568d75`](https://github.com/nix-community/home-manager/commit/fb568d75cf6c81f30d49eeb73787e9b56454ba16) | `` targets/darwin: allow configuring application linking (#4809) `` |

chore(flake/home-manager): `cb3f6e9b` -> `fb568d75`

---

flake.lock

| [`ed030a78`](https://github.com/nix-community/home-manager/commit/ed030a787938cae01d693ebaad52bbb672a4a69d) | `` chromium: optional nativeMessagingHosts (#6515) ``            |
| [`3b6550f7`](https://github.com/nix-community/home-manager/commit/3b6550f710e754bc9f58c09583f2fa51d9fd14ed) | `` git: add option to use riff as diff tool (#5748) ``           |
| [`6b7cd508`](https://github.com/nix-community/home-manager/commit/6b7cd50812e884a5 …

chore(flake/home-manager): `fb568d75` -> `ed030a78`

---

flake.lock

| [`46579253`](https://github.com/nix-community/nix-index-database/commit/465792533d03e6bb9dc849d58ab9d5e31fac9023) | `` update generated.nix to release 2025-02-23-031515 `` |
| [`fb4ee0d4`](https://github.com/nix-community/nix-index-database/commit/fb4ee0d4d8a501a7c8b84cfb87c222b05eac53f0) | `` flake.lock: Update ``                                |

chore(flake/nix-index-database): `ae15068e` -> `46579253`

---

flake.lock

| [`1398fc4d`](https://github.com/danth/stylix/commit/1398fc4dc8fd8e844ca23f275e87c988b0aa2c3f) | `` doc: use permalinks for option declarations ``                    |
| [`f4401071`](https://github.com/danth/stylix/commit/f4401071ea84ea6b4f90fb9b837760a0c9cceb63) | `` doc: add declaration entry ``                                     |
| [`4c04e0de`](https://github.com/danth/stylix/commit/4c04e0deceefb24ed4b8a0c788f3c673fd4ece06) | `` doc: redirect old …

chore(flake/stylix): `3a686a20` -> `f403ca10`

---

flake.lock

| [`b5ab2c7f`](https://github.com/nix-community/home-manager/commit/b5ab2c7fdaa807cf425066ab7cd34b073946b1ca) | `` waybar: support enable inspect from service (#5922) `` |

chore(flake/home-manager): `ed030a78` -> `b5ab2c7f`

---

flake.lock

| Commit                                                                                         | Message                                                                 |
| ---------------------------------------------------------------------------------------------- | ----------------------------------------------------------------------- |
| [`31aa4c5f`](https://github.com/NixOS/nixpkgs/commit/31aa4c5fefd7b53bbfb4ba52f25edb6da47bdf3f) | `` nixos/iso-image: fix build ``                                        |
| [`0c3729a9`](https://github.com/NixOS/nixpkgs/commit/0c3729a9d60c1442fff160b23cd67aa9b46776ab) | `` ocamlPackages.sexp: mark broken at versions 0.15 & 0.14 ``           |
| [`5e281f0f`](https://github.com/NixOS/nixpkgs/commit/5e281f0f6eba6fba658f2785973dd7c3ca9649fd) | `` …

chore(flake/nixpkgs): `73cf49b8` -> `32fb99ba`

---

flake.lock

| [`f121a142`](https://github.com/danth/stylix/commit/f121a142abde1b6aa9738e4c21a330c0ddd4eb70) | `` stylix: parametrize and change testbed field separator (#887) ``     |
| [`689fd55f`](https://github.com/danth/stylix/commit/689fd55ff286b01017c7d77acee6c904ce12f85c) | `` ci: make get-derivations job fail when input command fails (#888) `` |

chore(flake/stylix): `f403ca10` -> `f121a142`

---

flake.lock

| [`f1c95c76`](https://github.com/lovesegfault/vim-config/commit/f1c95c769b69dff55fddb89edea8040eb7777476) | `` chore(flake/nixpkgs): 73cf49b8 -> 32fb99ba `` |

chore(flake/lovesegfault-vim-config): `21b287c5` -> `f1c95c76`

---

flake.lock

| Commit                                                                                                  | Message                             |
| ------------------------------------------------------------------------------------------------------- | ----------------------------------- |
| [`a1bc2bd8`](https://github.com/tinted-theming/schemes/commit/a1bc2bd89e693e7e3f5764cfe8114e2ae150e184) | `` Base24 mbadolato iterm2 (#13) `` |

chore(flake/tinted-schemes): `59d9dc3b` -> `a1bc2bd8`

---

flake.lock

| [`12e26a74`](https://github.com/nix-community/home-manager/commit/12e26a74e5eb1a31e13daaa08858689e25ebd449) | `` tests/neovim: resolve deprecation (#6522) `` |
| [`6a2af4ff`](https://github.com/nix-community/home-manager/commit/6a2af4ffb26f812c353415c7316dff0a8b52b525) | `` tests/swayidle: bash -> bash-interactive ``  |
| [`3002f1ae`](https://github.com/nix-community/home-manager/commit/3002f1aedfde6d4d8112491ead088897a77ae661) | `` tests/mpd: bash -> bash-interactive …

chore(flake/home-manager): `b5ab2c7f` -> `12e26a74`

---

flake.lock

| Commit                                                                                                | Message                                                                                                        |
| ----------------------------------------------------------------------------------------------------- | -------------------------------------------------------------------------------------------------------------- |
| [`9b49e201`](https://github.com/NixOS/nixos-hardware/commit/9b49e201401825b581167c9467ff3791420644cc) | `` framework/13-inch/intel-core-ultra-series1: add check for hardware.enableRedistributableFirmware (#1367) `` |
| [`f75203cc`](https://github.com/NixOS/nixos-hardware/commit/f75203cc311b092a4c11f909bacd2534a7078c37) | `` common/gpu/nvidia: remove a …

chore(flake/nixos-hardware): `18e9f975` -> `9b49e201`

---

flake.lock

| [`d58f642d`](https://github.com/NixOS/nixos-hardware/commit/d58f642ddb23320965b27beb0beba7236e9117b5) | `` Rename dell/e7240 to dell/latitude/e7240 ``                      |
| [`55e9685e`](https://github.com/NixOS/nixos-hardware/commit/55e9685ec6291cb010d57198dafc2e60bf294b13) | `` Fix Gigabyte B650 suspend issue (#1385) ``                       |
| [`bbf25ca9`](https://github.com/NixOS/nixos-hardware/commit/bbf25ca940de16f74bf2264935bd748d67 …

chore(flake/nixos-hardware): `9b49e201` -> `d58f642d`

---

flake.lock

| [`9d433a6b`](https://github.com/danth/stylix/commit/9d433a6b1a44670ac1bf7e37e107a63ee04d32eb) | `` swaylock: attempt to avoid infinite recursion (#899) ``      |
| [`359084aa`](https://github.com/danth/stylix/commit/359084aae60e14d9223bd3fd67dba25854d88950) | `` doc: update GNOME testbed name in README (#909) ``           |
| [`ebdcc2a1`](https://github.com/danth/stylix/commit/ebdcc2a1902a602eaf7dcf6246c830ddb10a96a7) | `` doc: add module README for Firefox and …

chore(flake/stylix): `cbe42e21` -> `9d433a6b`

---

flake.lock

| Commit                                                                                                    | Message                                 |
| --------------------------------------------------------------------------------------------------------- | --------------------------------------- |
| [`e65210d7`](https://github.com/nix-community/lanzaboote/commit/e65210d77b44ef1b45505f4b22c1365c1371444b) | `` docs: fix small grammatical error `` |

chore(flake/lanzaboote): `3bdeebbc` -> `6321bc06`

---

flake.lock

| [`c12dcc9b`](https://github.com/nix-community/home-manager/commit/c12dcc9b61429b2ad437a7d4974399ad8f910319) | `` xdg: create '$XDG_STATE_HOME' (#6526) `` |

chore(flake/home-manager): `12e26a74` -> `c12dcc9b`

---

flake.lock

| [`c9195530`](https://github.com/danth/stylix/commit/c9195530b40e2589a70d3bf4154d2f92de1fafca) | `` stylix: apply testbed field separator check to each fields (#904) `` |

chore(flake/stylix): `9d433a6b` -> `c9195530`

---

flake.lock

| Commit                                                                                               | Message                                     |
| ---------------------------------------------------------------------------------------------------- | ------------------------------------------- |
| [`19c11404`](https://github.com/nix-community/disko/commit/19c1140419c4f1cdf88ad4c1cfb6605597628940) | `` fix schellcheck warning failing build `` |

chore(flake/disko): `15dbf8ce` -> `19c11404`

---

flake.lock

| [`74f0a854`](https://github.com/nix-community/home-manager/commit/74f0a8546e3f2458c870cf90fc4b38ac1f498b17) | `` clipse: add additional options (#6525) `` |

chore(flake/home-manager): `c12dcc9b` -> `74f0a854`

---

flake.lock
graphical/darwin.nix

| [`11ea44f3`](https://github.com/LnL7/nix-darwin/commit/11ea44f3e20737004f7c0f1d27354b9d7a79c2f5) | `` pam: add `pam_reattach` support ``                |
| [`47f26307`](https://github.com/LnL7/nix-darwin/commit/47f263077ee53de95a1c35eb6892665d77ce6165) | `` pam: switch to using `sudo_local` file ``         |
| [`bde9fa6f`](https://github.com/LnL7/nix-darwin/commit/bde9fa6f64211dc8bc9717fb37463e65de238b08) | `` add networking.hosts and .hostFiles from nixos `` |
| …

chore(flake/darwin): `6ab392f6` -> `42be12b5`

---

flake.lock

| [`7393047f`](https://github.com/lovesegfault/vim-config/commit/7393047f14b832bc1a4869601e01f1939dad7c58) | `` chore(flake/nixvim): 53f9d242 -> 6f8d8f7a `` |

chore(flake/lovesegfault-vim-config): `6b783278` -> `7393047f`

---

flake.lock

| [`a98c363a`](https://github.com/danth/stylix/commit/a98c363a58accad047a2580382d90433619a08e0) | `` stylix: use new package name for Noto Color Emoji (#917) `` |

chore(flake/stylix): `c9195530` -> `a98c363a`

---

flake.lock

| [`53c587d2`](https://github.com/nix-community/home-manager/commit/53c587d263f94aaf6a281745923c76bbec62bcf3) | `` tmux: fix shell example (#5361) ``                                     |
| [`87743e93`](https://github.com/nix-community/home-manager/commit/87743e9383d4cbf4138dc65dd644822fc38e7bbf) | `` firefox: deprecate vendorPath (#6519) ``                               |
| …

chore(flake/home-manager): `74f0a854` -> `53c587d2`

---

flake.lock

| Commit                                                                                           | Message                                                         |
| ------------------------------------------------------------------------------------------------ | --------------------------------------------------------------- |
| [`b1db30ce`](https://github.com/LnL7/nix-darwin/commit/b1db30ce36f25eb07a7d4832cc2d29b1697c00f1) | `` networking: Restore the original /etc/hosts on activation `` |
| [`1d9f6224`](https://github.com/LnL7/nix-darwin/commit/1d9f622484f00df0a8c00b13f427e4175760cf3c) | `` Revert "Add networking.hosts and .hostFiles from nixos " ``  |

chore(flake/darwin): `42be12b5` -> `31631ea6`

---

flake.lock

| [`6be185eb`](https://github.com/nix-community/home-manager/commit/6be185eb76295e7562f5bf2da42afe374b8beb15) | `` screen-locker: set Restart=always for all services (#6534) `` |
| [`44b86a72`](https://github.com/nix-community/home-manager/commit/44b86a72e73a7c3040ac54ed1c5eab5f156929bd) | `` xidlehook: set Restart=always (#6533) ``                      |

chore(flake/home-manager): `53c587d2` -> `6be185eb`

---

flake.lock

| [`b8869e4e`](https://github.com/nix-community/home-manager/commit/b8869e4ead721bbd4f0d6b927e8395705d4f16e6) | `` mpd: Add support for darwin (#6517) `` |

chore(flake/home-manager): `6be185eb` -> `b8869e4e`

---

flake.lock

| Commit                                                                                           | Message                              |
| ------------------------------------------------------------------------------------------------ | ------------------------------------ |
| [`727119f8`](https://github.com/LnL7/nix-darwin/commit/727119f8c7420879e83ffc310b8c1f4fa2800c11) | `` pam: add `pam_watchid` support `` |

chore(flake/darwin): `31631ea6` -> `665cc04a`

---

flake.lock

| [`009b764a`](https://github.com/NixOS/nixos-hardware/commit/009b764ac98a3602d41fc68072eeec5d24fc0e49) | `` apple/t2: update patches for the latest kernel `` |

chore(flake/nixos-hardware): `d58f642d` -> `009b764a`

---

flake.lock

| Commit                                                                                        | Message                                                            |
| --------------------------------------------------------------------------------------------- | ------------------------------------------------------------------ |
| [`21113945`](https://github.com/danth/stylix/commit/2111394586e922257168539142b2075e44c528b6) | `` Convert image path to string for Hyprlock fixing #918 (#925) `` |
| [`eab1ecf4`](https://github.com/danth/stylix/commit/eab1ecf41f2951e8655e7d66d19f21d5ab5fac4b) | `` docs: document configuring Standalone Nixvim ``                 |
| [`0a4755b6`](https://github.com/danth/stylix/commit/0a4755b656c28043c52063384fc68bbb30913903) | `` nixvim: expose config as …

chore(flake/stylix): `b273375e` -> `e7c09d20`

---

flake.lock

| Commit                                                                                                   | Message                                  |
| -------------------------------------------------------------------------------------------------------- | ---------------------------------------- |
| [`2a1b037f`](https://github.com/lovesegfault/vim-config/commit/2a1b037f394db76f6f5b348ab8cb23178563bee3) | `` chore: remove unused nixvim inputs `` |

chore(flake/lovesegfault-vim-config): `7393047f` -> `2a1b037f`

---

flake.lock

| [`7a4d97d4`](https://github.com/lovesegfault/vim-config/commit/7a4d97d450ec410c29981915ca28f27db0914332) | `` chore(flake/nixpkgs): 0196c017 -> 5135c594 `` |

chore(flake/lovesegfault-vim-config): `2a1b037f` -> `7a4d97d4`

---

flake.lock

| [`b71edac7`](https://github.com/nix-community/home-manager/commit/b71edac7a3167026aabea82a54d08b1794088c21) | `` launchd: sync up with changes from nix-darwin (#6508) `` |

chore(flake/home-manager): `343646e0` -> `b71edac7`

---

flake.lock

| [`c74352a1`](https://github.com/danth/stylix/commit/c74352a1459ac0d350b22a3a45bbaa18ab7b7e2d) | `` qt: adapt to style guide (#920) `` |

chore(flake/stylix): `e7c09d20` -> `c74352a1`

---

flake.lock

| Commit                                                                                           | Message                             |
| ------------------------------------------------------------------------------------------------ | ----------------------------------- |
| [`7386d887`](https://github.com/LnL7/nix-darwin/commit/7386d8878ec409f672f64df24e4d00da04bfc8ce) | `` services/dnscrypt-proxy: init `` |

chore(flake/darwin): `665cc04a` -> `5d6e0851`

---

flake.lock

| [`de4ee589`](https://github.com/danth/stylix/commit/de4ee5899042801b62f988687acd454d4d411075) | `` firefox: add gnome-theme testbed (#879) `` |

chore(flake/stylix): `c74352a1` -> `de4ee589`

---

flake.lock

| [`f0b5e7e8`](https://github.com/nix-community/home-manager/commit/f0b5e7e8a75abdea32bbff09ddd7b6eeb4b9b445) | `` xdg: add option 'xdg.cacheFile' (#6548) `` |

chore(flake/home-manager): `b71edac7` -> `f0b5e7e8`

---

flake.lock

| [`c9d05edf`](https://github.com/cachix/git-hooks.nix/commit/c9d05edf105495791fd154dd6f4ca626bfee0d3d) | `` dev: drop shellcheck from our dev checks ``             |
| [`3234ee65`](https://github.com/cachix/git-hooks.nix/commit/3234ee65344afdeada9c97408ee310647b801e44) | `` Update modules/hooks.nix ``                             |
| [`9a456ab1`](https://github.com/cachix/git-hooks.nix/commit/9a456ab1a5a25788915e8a0ecaec35970f163bfb) | `` feat: add mdformat …

chore(flake/git-hooks): `9364dc02` -> `a548245d`

---

flake.lock

| Commit                                                                                                      | Message                                                                          |
| ----------------------------------------------------------------------------------------------------------- | -------------------------------------------------------------------------------- |
| [`30da4310`](https://github.com/nix-community/home-manager/commit/30da4310935450ea38931abf775ffe1dfab15355) | `` librewolf: support darwin (#6561) ``                                          |
| [`4f05ef6a`](https://github.com/nix-community/home-manager/commit/4f05ef6a8adb5c2e9de83fee6d316ce168daf705) | `` firefox: fix wrong syntax grammar for search setting isAppProvided (#6556) `` |

chore(flake/home-manager): `f0b5e7e8` -> `30da4310`

---

flake.lock

| [`fcac3d6d`](https://github.com/nix-community/home-manager/commit/fcac3d6d88302a5e64f6cb8014ac785e08874c8d) | `` xdg: use mkOptionDefault ``                      |
| [`66505b85`](https://github.com/nix-community/home-manager/commit/66505b851b160a6937053a73b9b9808659df8c56) | `` xdg: add missing stateHome default for legacy `` |
| [`47c69496`](https://github.com/nix-community/home-manager/commit/47c694963e86b3e0f5d387506642a830871f331e) | `` tests: move xdg to …

chore(flake/home-manager): `30da4310` -> `fcac3d6d`

---

flake.lock

| [`b57a7012`](https://github.com/lovesegfault/vim-config/commit/b57a70124a018e04a3722ae4b6915b07d1fd921f) | `` chore(flake/git-hooks): 9364dc02 -> 25d4946d ``   |
| [`d6fc9fe7`](https://github.com/lovesegfault/vim-config/commit/d6fc9fe7db61175fb1f564e8aeddb04c901abb8f) | `` chore(flake/flake-parts): 32ea77a0 -> 3876f6b8 `` |

chore(flake/lovesegfault-vim-config): `7a4d97d4` -> `b57a7012`

---

flake.lock

| [`3adca9e8`](https://github.com/cachix/git-hooks.nix/commit/3adca9e8ed94feefb52765a0645e65a8ced04c2c) | `` Exposes configPath to the run wrapper `` |

chore(flake/git-hooks): `4a709a8c` -> `25d4946d`

---

flake.lock

| [`2dddb889`](https://github.com/lovesegfault/vim-config/commit/2dddb889b2f9a5b70b3ecd1720aa6863f6380fb6) | `` chore(flake/nixpkgs): 5135c594 -> 6313551c `` |

chore(flake/lovesegfault-vim-config): `b57a7012` -> `2dddb889`

---

flake.lock

| [`48ebf153`](https://github.com/cachix/git-hooks.nix/commit/48ebf1537f97ffb989c126530c58091e3b4b66d5) | `` fix(fourmolu): refer to its own settings `` |

chore(flake/git-hooks): `25d4946d` -> `42b1ba08`

---

flake.lock

| Commit                                                                                         | Message                                                                                   |
| ---------------------------------------------------------------------------------------------- | ----------------------------------------------------------------------------------------- |
| [`bb9abd73`](https://github.com/NixOS/nixpkgs/commit/bb9abd73464c9ec1bc79673e78a1b7e01b72f243) | `` spades: 4.0.0 -> 4.1.0 ``                                                              |
| [`e154a5da`](https://github.com/NixOS/nixpkgs/commit/e154a5da7dcb4911218c63974726bb041e776605) | `` vcmi: 1.6.6 -> 1.6.7 ``                                                                |
| …

chore(flake/nixpkgs): `0196c017` -> `303bd807`

---

flake.lock

| Commit                                                                                        | Message                                                            |
| --------------------------------------------------------------------------------------------- | ------------------------------------------------------------------ |
| [`489833b2`](https://github.com/danth/stylix/commit/489833b201a84488c6b4371a261fdbcafa6abcb6) | `` treewide: give mustache files correct file extensions (#946) `` |

chore(flake/stylix): `de4ee589` -> `489833b2`

---

flake.lock

| [`665bf10a`](https://github.com/lovesegfault/vim-config/commit/665bf10af77e0cede5aba65721c3cb831ad4d987) | `` chore(flake/nixpkgs): 6313551c -> ba487dbc `` |

chore(flake/lovesegfault-vim-config): `2dddb889` -> `665bf10a`

---

flake.lock

| Commit                                                                                           | Message                                             |
| ------------------------------------------------------------------------------------------------ | --------------------------------------------------- |
| [`fdc512d1`](https://github.com/LnL7/nix-darwin/commit/fdc512d107d2777e9af89f4dc0191c8878b57aa5) | `` services/dnscrypt-proxy: Fix use of pkg alias `` |

chore(flake/darwin): `5d6e0851` -> `4a0bddd4`

---

flake.lock

| Commit                                                                                                      | Message                                                                               |
| ----------------------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------- |
| [`70fbbf05`](https://github.com/nix-community/home-manager/commit/70fbbf05a5594b0a72124ab211bff1d502c89e3f) | `` Firefox: Apply global extension force setting to declarative extensions (#6567) `` |

chore(flake/home-manager): `fcac3d6d` -> `70fbbf05`

---

flake.lock

| Commit                                                                                        | Message                                                                   |
| --------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------- |
| [`65c42633`](https://github.com/danth/stylix/commit/65c42633d4d0ebc49e8f077c289786b13a145509) | `` ci: ignore Cachix errors (#952) ``                                     |
| [`2f47285f`](https://github.com/danth/stylix/commit/2f47285f9dbd63d33f8d56517afd70758d68aa11) | `` btop: memory and disk color gradient following logical color (#935) `` |

chore(flake/stylix): `489833b2` -> `65c42633`

---

flake.lock

| Commit                                                                                        | Message                                                                     |
| --------------------------------------------------------------------------------------------- | --------------------------------------------------------------------------- |
| [`11780517`](https://github.com/danth/stylix/commit/11780517948f214b9f93d1bf5a2d29bc181d3a33) | `` ncspot: match style guide better and add transparent bg (#938) ``        |
| [`afee64f3`](https://github.com/danth/stylix/commit/afee64f3c5090b4eadc30df46bad001015744858) | `` rio: add emoji font family and convert font size to pixel unit (#937) `` |

chore(flake/stylix): `65c42633` -> `11780517`

---

flake.lock

| Commit                                                                                           | Message                                 |
| ------------------------------------------------------------------------------------------------ | --------------------------------------- |
| [`d06cf700`](https://github.com/LnL7/nix-darwin/commit/d06cf700ee589527fde4bd9b91f899e7137c05a6) | `` homebrew: remove `--no-lock` flag `` |

chore(flake/darwin): `4a0bddd4` -> `991bb2f6`

---

flake.lock

| [`b1b964ea`](https://github.com/nix-community/home-manager/commit/b1b964ea9348aef08cab514fa88e9c99def6fd63) | `` mbsync: support maildir paths containing spaces ``      |
| [`6f71acf7`](https://github.com/nix-community/home-manager/commit/6f71acf71bd6a8a6f3152769737a53af6da6ae63) | `` git: apply sendmailCmd instead of smtpServer (#6399) `` |
| [`3f08cd8e`](https://github.com/nix-community/home-manager/commit/3f08cd8ef77dcd7586075a460a61c8432baf25a9 …

chore(flake/home-manager): `70fbbf05` -> `b1b964ea`

---

flake.lock

| [`def0dbbc`](https://github.com/nix-community/home-manager/commit/def0dbbcea715d4514ca343ab4d6d7f3a1742da0) | `` vscode: Support Cursor AI (#6417) `` |

chore(flake/home-manager): `b1b964ea` -> `def0dbbc`

---

flake.lock

| Commit                                                                                           | Message                                                                 |
| ------------------------------------------------------------------------------------------------ | ----------------------------------------------------------------------- |
| [`df599ea8`](https://github.com/LnL7/nix-darwin/commit/df599ea8f10e86985c1b09e3cd7a3a331dc702f3) | `` readme: update instructions as Determinate Nix is now the default `` |

chore(flake/darwin): `991bb2f6` -> `adf5c88b`

---

flake.lock

| Commit                                                                                                    | Message                         |
| --------------------------------------------------------------------------------------------------------- | ------------------------------- |
| [`cb77e064`](https://github.com/nix-community/lanzaboote/commit/cb77e064bb009ef749a9b24391320708cb25cb0a) | `` stub: update dependencies `` |
| [`55f599a5`](https://github.com/nix-community/lanzaboote/commit/55f599a56029a0b3bc59092bdad6e9484b215c29) | `` tool: update dependencies `` |
| [`98028683`](https://github.com/nix-community/lanzaboote/commit/98028683cd00c45d7659d7ef242ff126127d6077) | `` flake.lock: Update ``        |

chore(flake/lanzaboote): `cc9786aa` -> `3a3ed972`

---

flake.lock

| [`8a0d8090`](https://github.com/lovesegfault/vim-config/commit/8a0d80900c608786f42216261cd5e7b1bec3ab3d) | `` chore(flake/nixpkgs): ba487dbc -> d69ab0d7 `` |

chore(flake/lovesegfault-vim-config): `effd09a7` -> `8a0d8090`

---

flake.lock

| [`d23a3bc3`](https://github.com/NixOS/nixos-hardware/commit/d23a3bc3c600a064c72c7fb02862edfab11a46cf) | `` surface: linux 6.12.16 -> 6.12.17 `` |

chore(flake/nixos-hardware): `009b764a` -> `d23a3bc3`

---

flake.lock

| Commit                                                                                                | Message                                                                           |
| ----------------------------------------------------------------------------------------------------- | --------------------------------------------------------------------------------- |
| [`b48cc4da`](https://github.com/NixOS/nixos-hardware/commit/b48cc4dab0f9711af296fc367b6108cf7b8ccb16) | `` pine64/rockpro64: HDMI output and Network in initrd ``                         |
| [`ae546d01`](https://github.com/NixOS/nixos-hardware/commit/ae546d018a7f23e3ca35fdcaf31be4ff8d148d80) | `` Add support for TUXEDO InfinityBook Pro Intel Gen9 ``                          |
| …

chore(flake/nixos-hardware): `d23a3bc3` -> `b48cc4da`

---

flake.lock

| [`6fada03c`](https://github.com/danth/stylix/commit/6fada03cd5e223aa9c111e7073118692065a7ee1) | `` nvf: init (#939) ``                          |
| [`48538792`](https://github.com/danth/stylix/commit/4853879264376ae7d20dea2a7af58490f179bc7a) | `` vscode: support arbitrary profiles (#914) `` |

chore(flake/stylix): `11780517` -> `6fada03c`

---

flake.lock

| [`04c915bc`](https://github.com/nix-community/home-manager/commit/04c915bcf1a1eac3519372ff3185beef053fba7c) | `` firefox: Support paths for userChrome & userContent (#3856) `` |

chore(flake/home-manager): `486b0660` -> `04c915bc`

---

flake.lock

| [`fcea9160`](https://github.com/cachix/git-hooks.nix/commit/fcea91603f24a41113c1b9e4043510b1b96e10bb) | `` Revert "ci: use self-hosted runners" ``        |
| [`61fa9623`](https://github.com/cachix/git-hooks.nix/commit/61fa9623cba72d8bde0b84e264725584602e8cf2) | `` ci: use self-hosted runners ``                 |
| [`75796622`](https://github.com/cachix/git-hooks.nix/commit/75796622e2775e624944ff08e74777c383d2b65d) | `` docs: add supported but non-mentioned hooks `` |
| …

chore(flake/git-hooks): `42b1ba08` -> `fcea9160`

---

flake.lock

| Commit                                                                                                   | Message                                                                                                                    |
| -------------------------------------------------------------------------------------------------------- | -------------------------------------------------------------------------------------------------------------------------- |
| [`18bae3ab`](https://github.com/hercules-ci/flake-parts/commit/18bae3abd9e674e31e97ac8790eafb4f5b85647c) | `` Revert "flake-update: Get the nixpkgs/lib subtree only" ``                                                              |
| [`2a248bba`](https://github.com/hercules-ci/flake-parts/commit/2a248bba8ab12d669c7d712eaeea26a27 …

chore(flake/flake-parts): `3876f6b8` -> `f4330d22`

---

flake.lock

| [`83f46293`](https://github.com/nix-community/home-manager/commit/83f4629364b6e627ce25d7d246058e48ffa4b111) | `` granted: support fish shell (#6549) `` |

chore(flake/home-manager): `04c915bc` -> `83f46293`

---

flake.lock

| [`74f1ac55`](https://github.com/danth/stylix/commit/74f1ac55d3b09fb3be23563d398b430e756a6e83) | `` fnott: init (#948) ``              |
| [`7fc0a871`](https://github.com/danth/stylix/commit/7fc0a8716e753f0341300ebe34cda5f8a90527f8) | `` stylix: add editorconfig (#945) `` |

chore(flake/stylix): `6fada03c` -> `74f1ac55`

---

flake.lock

| [`95711f92`](https://github.com/nix-community/home-manager/commit/95711f926676018d279ba09fe7530d03b5d5b3e2) | `` treewide: remove with lib (#6512) `` |

chore(flake/home-manager): `83f46293` -> `95711f92`

---

flake.lock

| Commit                                                                                                    | Message                                         |
| --------------------------------------------------------------------------------------------------------- | ----------------------------------------------- |
| [`724022dd`](https://github.com/nix-community/lanzaboote/commit/724022dd400ed5c2afbd93c92dca87a262f7f407) | `` flake: remove unneeded uki module ``         |
| [`874ea2f5`](https://github.com/nix-community/lanzaboote/commit/874ea2f5fb1c8b8917c3c9465c777f73aa1d9585) | `` stub: remove fat stub ``                     |
| [`657ace37`](https://github.com/nix-community/lanzaboote/commit/657ace37a4150a653d2f3303b16dbdd7067ce5cb) | `` stub: remove nix expressions for fat stub `` |

chore(flake/lanzaboote): `3a3ed972` -> `21fc8d70`

---

flake.lock

| [`aa660a43`](https://github.com/lovesegfault/vim-config/commit/aa660a435f2bb3e3713ae9d5ec275ab66e3c75ac) | `` chore(flake/git-hooks): 42b1ba08 -> b5a62751 ``   |
| [`d0d6f418`](https://github.com/lovesegfault/vim-config/commit/d0d6f41808a61a71acd5a912dce216b5b614e03b) | `` chore(flake/flake-parts): 3876f6b8 -> f4330d22 `` |

chore(flake/lovesegfault-vim-config): `8a0d8090` -> `aa660a43`

---

flake.lock

| [`f4cdd2cc`](https://github.com/cachix/git-hooks.nix/commit/f4cdd2cc618f1ad3d8e4e43da36a120d55ee2b72) | `` Improve `configPath` docs ``                                  |
| [`e2fcecd7`](https://github.com/cachix/git-hooks.nix/commit/e2fcecd7db11ee277dc9fd8c285ddfd2ae7840af) | `` Improve the error message when an existing config is found `` |
| [`d952b5be`](https://github.com/cachix/git-hooks.nix/commit/d952b5be9c76833413cd8e4dab74a6e89b3e3719) | …

chore(flake/git-hooks): `1293270f` -> `b5a62751`

---

flake.lock

| [`6eea250b`](https://github.com/danth/stylix/commit/6eea250b10386be0fc23496d1039d76b3147680e) | `` dunst: fix opacity rounding (#965) ``   |
| [`4891f147`](https://github.com/danth/stylix/commit/4891f1471b682af073574dc51fa4810f1470ef8f) | `` stylix: simplify dummy values (#959) `` |

chore(flake/stylix): `74f1ac55` -> `6eea250b`

---

flake.lock

| [`c1d2a49e`](https://github.com/lovesegfault/vim-config/commit/c1d2a49efda411fdf5d58db5004923cdbb8c7593) | `` chore(flake/nixpkgs): d69ab0d7 -> 10069ef4 `` |

chore(flake/lovesegfault-vim-config): `aa660a43` -> `c1d2a49e`

---

flake.lock

| [`d2c014e1`](https://github.com/nix-community/home-manager/commit/d2c014e1c73195d1958abec0c5ca6112b07b79da) | `` treewide: null package support (#6582) ``                          |
| [`6c2b7940`](https://github.com/nix-community/home-manager/commit/6c2b79403e9ae852fbf1d55b29f2ea4d2aa43255) | `` treewide: use graphical-session.target for GUI services (#5785) `` |

chore(flake/home-manager): `95711f92` -> `d2c014e1`

---

flake.lock

| [`26f6b862`](https://github.com/nix-community/home-manager/commit/26f6b862645ff281f3bada5d406e8c20de8d837c) | `` tests/gh-dash: enable gh to test extension adding `` |
| [`5ab4305f`](https://github.com/nix-community/home-manager/commit/5ab4305f345ccf628fbcaa7a2dfd3696accd907b) | `` gh-dash: fix ``                                      |
| [`1347b0b4`](https://github.com/nix-community/home-manager/commit/1347b0b468ddf355657d58e50811238cfff517cb) | `` …

chore(flake/home-manager): `d2c014e1` -> `26f6b862`

---

flake.lock

| Commit                                                                                                            | Message                           |
| ----------------------------------------------------------------------------------------------------------------- | --------------------------------- |
| [`fdaa9d2f`](https://github.com/nix-community/nix-index-database/commit/fdaa9d2fb061b3c56e4db92df9d340ab268895dd) | `` More correct Darwin example `` |

chore(flake/nix-index-database): `26a0f969` -> `eeaf1084`

---

flake.lock

| Commit                                                                                                    | Message                                               |
| --------------------------------------------------------------------------------------------------------- | ----------------------------------------------------- |
| [`fd220317`](https://github.com/nix-community/lanzaboote/commit/fd220317eee2aa3273d6a62686fea42d51d10b1e) | `` readme: remove stale references to the fat stub `` |

chore(flake/lanzaboote): `21fc8d70` -> `d8099586`

---

flake.lock

| [`7f4c60a3`](https://github.com/nix-community/home-manager/commit/7f4c60a3d6e548dbc13666565c22cb3f8dcdad44) | `` podman: fix podman-user-wait-network-online (#6586) ``                |
| [`65d6043d`](https://github.com/nix-community/home-manager/commit/65d6043d32db2bf7fa22abd274443485cecef053) | `` flake.lock: Update (#6588) ``                                         |
| …

chore(flake/home-manager): `26f6b862` -> `7f4c60a3`

---

flake.lock

| [`4c95c60b`](https://github.com/lovesegfault/vim-config/commit/4c95c60bf531bbc551529d80b1d21e91a4a81852) | `` chore(flake/nixpkgs): 10069ef4 -> 36fd87ba `` |

chore(flake/lovesegfault-vim-config): `c1d2a49e` -> `4c95c60b`

---

flake.lock

| [`296a2c99`](https://github.com/nix-community/nix-index-database/commit/296a2c992a28b37427d062ade6e20d467e479e3f) | `` update generated.nix to release 2025-03-09-025742 `` |
| [`bb527ad1`](https://github.com/nix-community/nix-index-database/commit/bb527ad1e2ab6c59f3d2344fe043abaa7fd5a27d) | `` flake.lock: Update ``                                |

chore(flake/nix-index-database): `eeaf1084` -> `296a2c99`

---

flake.lock

| [`1fd39a10`](https://github.com/nix-community/home-manager/commit/1fd39a105575ea997b32a043a0dd2c49294add5b) | `` tests/vscode: fix darwin snippets test ``                             |
| [`8d2a0581`](https://github.com/nix-community/home-manager/commit/8d2a05810834119b96531745de7943cc8ba5bb79) | `` tests/thunderbird: fix darwin test ``                                 |
| …

chore(flake/home-manager): `7f4c60a3` -> `1fd39a10`

---

flake.lock

| Commit                                                                                        | Message                                                      |
| --------------------------------------------------------------------------------------------- | ------------------------------------------------------------ |
| [`a7606826`](https://github.com/danth/stylix/commit/a76068262cfc16c04f9c07a6458715548b067450) | `` palette: fix eval fail when image is null (#941) ``       |
| [`3fce9fb0`](https://github.com/danth/stylix/commit/3fce9fb038b7e24d5d6a2d5c10979d742364ef00) | `` treewide: propagate inputs and remove templates (#926) `` |

chore(flake/stylix): `6eea250b` -> `a7606826`

---

flake.lock

| Commit                                                                                                      | Message                                                                       |
| ----------------------------------------------------------------------------------------------------------- | ----------------------------------------------------------------------------- |
| [`db4386d6`](https://github.com/nix-community/home-manager/commit/db4386d686fb0b2788e7422e6a2299deace9c4b1) | `` home-environment: add line-break after sessionSearchVariables (#6596) ``   |
| [`2967de4d`](https://github.com/nix-community/home-manager/commit/2967de4d1146f1b6aa820eed85b823ea2ebfd0fa) | `` debug: make NIX_DEBUG_INFO_DIRS a list of strings (#6595) ``               |
| …

chore(flake/home-manager): `1fd39a10` -> `db4386d6`

---

flake.lock

| [`597f9c2f`](https://github.com/nix-community/home-manager/commit/597f9c2f06af8791b31c48ad05471ac5afbd0f0a) | `` thunderbird: set additional gmail server settings (#6579) `` |

chore(flake/home-manager): `db4386d6` -> `597f9c2f`

---

flake.lock

| Commit                                                                                                      | Message                                                                           |
| ----------------------------------------------------------------------------------------------------------- | --------------------------------------------------------------------------------- |
| [`ce9cb249`](https://github.com/nix-community/home-manager/commit/ce9cb2496c48ebb33e42ee0ab82267f67b82f71e) | `` podman: added volume, image, and build quadlets (#6137) ``                     |
| [`f8bb0ba6`](https://github.com/nix-community/home-manager/commit/f8bb0ba6de361c43c1c1e9756375f23ffadac1f9) | `` zoxide: update mkOrder to place bash configuration at end of bashrc (#6572) `` |

chore(flake/home-manager): `597f9c2f` -> `ce9cb249`

---

flake.lock

| [`744f749d`](https://github.com/nix-community/home-manager/commit/744f749dd6fbc1489591ea370b95156858629cb9) | `` mods: add a mods module (#6339) `` |

chore(flake/home-manager): `ce9cb249` -> `744f749d`

---

flake.lock

| [`3593ee59`](https://github.com/nix-community/home-manager/commit/3593ee59a44974b8518829a5239b2f77222e3c81) | `` xdg-mime: Fix cross compilation (#6500) `` |

chore(flake/home-manager): `744f749d` -> `3593ee59`

---

flake.lock

| Commit                                                                                                            | Message                           |
| ----------------------------------------------------------------------------------------------------------------- | --------------------------------- |
| [`5f83114e`](https://github.com/nix-community/nix-index-database/commit/5f83114eb638fba4f176cb81dd8795be1a632e1f) | `` README: fix links to flakes `` |

chore(flake/nix-index-database): `296a2c99` -> `66537fb1`

---

flake.lock

| [`7fb86787`](https://github.com/nix-community/home-manager/commit/7fb8678716c158642ac42f9ff7a18c0800fea551) | `` Fix missing styleName for kde6 (#6597) `` |

chore(flake/home-manager): `3593ee59` -> `7fb86787`

---

flake.lock

| [`5ea77556`](https://github.com/lovesegfault/vim-config/commit/5ea7755684cdb2f7ca56b3e41569c361b989e53e) | `` chore(flake/nixpkgs): 36fd87ba -> e3e32b64 `` |

chore(flake/lovesegfault-vim-config): `4c95c60b` -> `5ea77556`

---

flake.lock

| [`2db1d64f`](https://github.com/nix-community/disko/commit/2db1d64fc084b1d15e3871dffc02c62a94ed6ed7) | `` Added example for swap on `zfs_volume` `` |
| [`6c1b8344`](https://github.com/nix-community/disko/commit/6c1b8344569f8db95163276d275ecfad9b19cbff) | `` also deactivate swap partitions ``        |

chore(flake/disko): `8d6dd03a` -> `2db1d64f`

---

flake.lock

| Commit                                                                                                      | Message                                                                                 |
| ----------------------------------------------------------------------------------------------------------- | --------------------------------------------------------------------------------------- |
| [`c630dfa8`](https://github.com/nix-community/home-manager/commit/c630dfa8abcc65984cc1e47fb25d4552c81dd37e) | `` nix-darwin: respect username setting of home-manager in activation script (#5881) `` |
| [`7fd6dc2b`](https://github.com/nix-community/home-manager/commit/7fd6dc2b94f10b0229f5e6b8fd5ed49636f895e1) | `` granted: fix fish shell integration (#6602) `` …

chore(flake/home-manager): `7fb86787` -> `c630dfa8`

---

flake.lock

| Commit                                                                                                  | Message                                                                 |
| ------------------------------------------------------------------------------------------------------- | ----------------------------------------------------------------------- |
| [`d4a7c5b6`](https://github.com/tinted-theming/schemes/commit/d4a7c5b683fb4d4150162d163889a7882625022e) | `` fix(base24): rename ultra-violent.yaml to ultra-violet.yaml (#44) `` |

chore(flake/tinted-schemes): `47c8c772` -> `d4a7c5b6`

---

flake.lock
flake.nix

| Commit                                                                                         | Message                                                                                                     |
| ---------------------------------------------------------------------------------------------- | ----------------------------------------------------------------------------------------------------------- |
| [`21e4b751`](https://github.com/NixOS/nixpkgs/commit/21e4b751ae4b931710d0fdc1187f2832ab2f647e) | `` trenchbroom: 2024.1 -> 2025.2 ``                                                                         |
| [`4abfe287`](https://github.com/NixOS/nixpkgs/commit/4abfe287524105544245bfbab9f41a657e257f6b) | `` mgba: adopt `` …

chore(flake/nixpkgs): `ba487dbc` -> `e3e32b64`

---

flake.lock

| [`2bd9188b`](https://github.com/lovesegfault/vim-config/commit/2bd9188b4b7b3d128250e27e4e5b4ae10545ef0a) | `` chore(flake/nixvim): 03065fd4 -> 3a3abf11 `` |

chore(flake/lovesegfault-vim-config): `5ea77556` -> `2bd9188b`

---

flake.lock

| [`eea05760`](https://github.com/nix-community/disko/commit/eea057603d42c149eac9d51d035a4b8071da62aa) | `` fix syntax of disk-deactivate.jq ``       |
| [`9a7ab516`](https://github.com/nix-community/disko/commit/9a7ab516cf49c0df2f4d45c067d3b94d391701b8) | `` Set `buildPlatform` in make-disk-image `` |
| [`87d86e49`](https://github.com/nix-community/disko/commit/87d86e499c91f0bb175625a02072b00192f65711) | `` fix eval for make-disk-image test ``      |
| …

chore(flake/disko): `2db1d64f` -> `0d8c6ad4`

---

flake.lock

| [`e1f12151`](https://github.com/NixOS/nixos-hardware/commit/e1f12151258b12c567f456d8248e4694e9390613) | `` refactor: add model to outputs ``                   |
| [`09e97074`](https://github.com/NixOS/nixos-hardware/commit/09e97074ad78706156e8c8d380b8196a602ef719) | `` refactor: add generic laptop spec ``                |
| [`1b1acdc3`](https://github.com/NixOS/nixos-hardware/commit/1b1acdc3e7e4b2e4b5f07430392939e19a90fb8a) | `` init `` …

chore(flake/nixos-hardware): `b48cc4da` -> `e1f12151`

---

flake.lock

| [`9e3ab4d2`](https://github.com/danth/stylix/commit/9e3ab4d208e2cc2aef5ab0f8e18932ebf8064fc5) | `` stylix: system.darwin.release -> system.darwinRelease (#989) ``   |
| [`e28bd4de`](https://github.com/danth/stylix/commit/e28bd4de28a51216fd7c89158d82b688c3793e8e) | `` glance: fix RGB to HSL conversion (#932) ``                       |
| [`599d5a5e`](https://github.com/danth/stylix/commit/599d5a5ecaf8d3cc2d6e8a1fafcdda4c74852abb) | `` vscode: use base01 for …

chore(flake/stylix): `a7606826` -> `9e3ab4d2`

---

flake.lock

| Commit                                                                                                      | Message                                                                              |
| ----------------------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------ |
| [`1b0efe3d`](https://github.com/nix-community/home-manager/commit/1b0efe3d335f452595512c7b275e5dddfbfb28a5) | `` zsh: move option variables closer to usage ``                                     |
| [`ad487d38`](https://github.com/nix-community/home-manager/commit/ad487d3863e94ac839b2e1e451197ab5a4aafd1b) | `` zsh: move config variables closer to usage ``                                     |
| …

chore(flake/home-manager): `18780912` -> `1b0efe3d`

---

flake.lock

| [`0b0baed7`](https://github.com/nix-community/home-manager/commit/0b0baed7b2bf6a5e365d4cba042b580a2bc32e34) | `` tests/default: blacklist sapling ``               |
| [`0e46e842`](https://github.com/nix-community/home-manager/commit/0e46e84279d3d8eb7dcb044cb8aa9baa93298e66) | `` zsh: cleanup empty / wrong generated lines ``     |
| [`5d511628`](https://github.com/nix-community/home-manager/commit/5d5116286269c4e11976f6450afde1b30c3834c0) | `` syncthing: have …

chore(flake/home-manager): `1b0efe3d` -> `0b0baed7`

---

flake.lock

| [`db8307ee`](https://github.com/lovesegfault/vim-config/commit/db8307eebc944c191756942c13689728d4c152f0) | `` chore(flake/nixpkgs): e3e32b64 -> 6607cf78 `` |

chore(flake/lovesegfault-vim-config): `2bd9188b` -> `db8307ee`

---

flake.lock

| [`30cce684`](https://github.com/nix-community/home-manager/commit/30cce6848a5aa41ceb5fb33185b84868cc3e9bef) | `` synthing: fix synthing config being deleted on rebuild (#6621) `` |
| [`6914c15c`](https://github.com/nix-community/home-manager/commit/6914c15c09e3e635ce678eb72f5781e5a85a6b24) | `` tests/default: scrub zsh ``                                       |
| [`8f8f5432`](https://github.com/nix-community/home-manager/commit/ …

chore(flake/home-manager): `0b0baed7` -> `30cce684`

---

flake.lock

| Commit                                                                                        | Message                                           |
| --------------------------------------------------------------------------------------------- | ------------------------------------------------- |
| [`08e0c91d`](https://github.com/danth/stylix/commit/08e0c91d76e05a61ffe15bcd17ef7fa3160c5bd8) | `` ci: bump cachix/cachix-action from 15 to 16 `` |

chore(flake/stylix): `5053a63c` -> `08e0c91d`

---

flake.lock

| [`113cd391`](https://github.com/NixOS/nixos-hardware/commit/113cd3916682def185290145924fa30b30bda972) | `` build(deps): bump cachix/install-nix-action from 30 to 31 `` |

chore(flake/nixos-hardware): `e1f12151` -> `113cd391`

---

flake.lock

| [`eae06a96`](https://github.com/nix-community/home-manager/commit/eae06a96af1903655f06cb401907555ea4048357) | `` ci: bump cachix/install-nix-action from 30 to 31 (#6643) ``  |
| [`f55c5f65`](https://github.com/nix-community/home-manager/commit/f55c5f6569c98f36969def802f84bde44f254f41) | `` kubecolor: create oc alias conditionally ``                  |
| [`f9f766c6`](https://github.com/nix-community/home-manager/commit/f9f766c6009410f4523f …

chore(flake/home-manager): `4e12151c` -> `eae06a96`

---

flake.lock

| [`c657142e`](https://github.com/nix-community/home-manager/commit/c657142e24a43ea1035889f0b0a7c24598e0e18a) | `` thunderbird: add message filters option  (#6652) ``                         |
| [`b870fb2d`](https://github.com/nix-community/home-manager/commit/b870fb2d62ee0deb657951f83e8689143dce98c8) | `` zsh: update zsh initContent example to use lib.literalExpression (#6637) `` |
| …

chore(flake/home-manager): `eae06a96` -> `c657142e`

---

flake.lock

| [`e11302ee`](https://github.com/lovesegfault/vim-config/commit/e11302eebbfb0d915da3b02869704f3f2e017318) | `` chore(flake/nixvim): 33097dcf -> 78f6166c `` |

chore(flake/lovesegfault-vim-config): `9d919d11` -> `e11302ee`

---

flake.lock

| [`22a36aa7`](https://github.com/nix-community/home-manager/commit/22a36aa709de7dd42b562a433b9cefecf104a6ee) | `` swww: add swww service module for swww-daemon (#6543) `` |
| [`fb74bb76`](https://github.com/nix-community/home-manager/commit/fb74bb76d94a6c55632376c931fc108131260ee9) | `` vscode: fix creation of storage.json file (#6650) ``     |

chore(flake/home-manager): `c657142e` -> `22a36aa7`

---

flake.lock

| [`b3b938ab`](https://github.com/numtide/treefmt-nix/commit/b3b938ab8ba2e8a0ce9ee9b30ccfa5e903ae5753) | `` rustfmt: fix for Rust packages from rust-overlay (#311) ``     |
| [`60fce901`](https://github.com/numtide/treefmt-nix/commit/60fce90101ee4da830e056507721f38310a59e0d) | `` ruff-format: add `lineLength` option; add maintainer (#316) `` |
| [`7620ff43`](https://github.com/numtide/treefmt-nix/commit/7620ff43d88e46f4fd8b38205dcaa9b308d3c3b6) | `` …

chore(flake/treefmt-nix): `3d0579f5` -> `b3b938ab`

---

flake.lock

| [`3b74630f`](https://github.com/lovesegfault/vim-config/commit/3b74630f2c55bec9fabb97e2bc72442f3a4416c5) | `` chore(flake/git-hooks): 59f17850 -> ea26a82d `` |

chore(flake/lovesegfault-vim-config): `e11302ee` -> `3b74630f`

---

flake.lock

| [`e4a09d96`](https://github.com/lovesegfault/vim-config/commit/e4a09d96517fb42529e9395a8d4af0a41fa67efe) | `` chore(flake/nixvim): 78f6166c -> 1ca0ec3d ``      |
| [`3c51b27a`](https://github.com/lovesegfault/vim-config/commit/3c51b27a7a34bb222d11b56ba29ebc62edf191e3) | `` chore(flake/treefmt-nix): 3d0579f5 -> b3b938ab `` |

chore(flake/lovesegfault-vim-config): `3b74630f` -> `e4a09d96`

---

flake.lock

| [`3970af5d`](https://github.com/NixOS/nixos-hardware/commit/3970af5d5831be5c31eb6271a21bf5944cc0e791) | `` lenovo/thinkpad/x13-yoga: add thunderbolt support `` |

chore(flake/nixos-hardware): `4f4d97d7` -> `daaae13d`

---

flake.lock
hardware/sound.nix
nix/overlays/nix-latest.nix

| [`b6eaf97c`](https://github.com/NixOS/nixpkgs/commit/b6eaf97c6960d97350c584de1b6dcff03c9daf42) | `` liblouis: 3.32.0 -> 3.33.0 ``                                                    |
| [`b82dbaf3`](https://github.com/NixOS/nixpkgs/commit/b82dbaf3abfe30ba7625b0094c7ccf12ca6a02fc) | `` nixos-generate-config: Fix unspecified root ``                                   |
| …

chore(flake/nixpkgs): `e3e32b64` -> `b6eaf97c`

---

flake.lock

| [`b5976017`](https://github.com/nix-community/home-manager/commit/b5976017741653251258112f7e6ee5d8b9e3a832) | `` easyeffects: remove with lib ``                                         |
| [`e278f46a`](https://github.com/nix-community/home-manager/commit/e278f46a0990344b3186d09a35350fbcb6fa4dbd) | `` easyeffects: add hausken as maintainer ``                               |
| …

chore(flake/home-manager): `22a36aa7` -> `b5976017`

---

flake.lock

| [`eb0f617a`](https://github.com/nix-community/home-manager/commit/eb0f617aecbaf1eff5bacec789891e775af2f5a3) | `` tex-fmt: add null package support ``     |
| [`9556d3c2`](https://github.com/nix-community/home-manager/commit/9556d3c2b48c0ec9a5cf4aa444b368cfb85fa60e) | `` tex-fmt: add module ``                   |
| [`8b629b54`](https://github.com/nix-community/home-manager/commit/8b629b5424dd2b10ff5cbca7fa52fa66ef33a196) | `` firefox: migrate search config to v12 `` |
| …

chore(flake/home-manager): `b5976017` -> `eb0f617a`

---

flake.lock

| Commit                                                                                                   | Message                                                    |
| -------------------------------------------------------------------------------------------------------- | ---------------------------------------------------------- |
| [`6a823bc1`](https://github.com/lovesegfault/vim-config/commit/6a823bc14aed166243c00a3267c5af8daa062489) | `` chore(deps): bump cachix/cachix-action from 15 to 16 `` |
| [`428ae5d0`](https://github.com/lovesegfault/vim-config/commit/428ae5d024241133afe18f77b105a3119cf770c6) | `` chore(flake/nixpkgs): c80f6a7e -> b6eaf97c ``           |

chore(flake/lovesegfault-vim-config): `13b59ffd` -> `6a823bc1`

---

flake.lock

| [`97a00e06`](https://github.com/nix-community/home-manager/commit/97a00e0659b2807454507eb3a593bd09b099bd80) | `` librespot: init module (#6229) ``                     |
| [`8675edf7`](https://github.com/nix-community/home-manager/commit/8675edf7d36bfc972f66481a33f4f453d3b2d06e) | `` fish: add command option for abbreviations (#6666) `` |
| [`cfaa4426`](https://github.com/nix-community/home-manager/commit/cfaa4426a3eee6e71ab02a4d72410e69abf06a12) | `` …

chore(flake/home-manager): `eb0f617a` -> `97a00e06`

---

flake.lock

| [`94605dca`](https://github.com/nix-community/home-manager/commit/94605dcadefeaff6b35c8931c9f38e4f4dc7ad0a) | `` tests/firefox: add applicationName to mock (#6668) `` |

chore(flake/home-manager): `97a00e06` -> `94605dca`

---

flake.lock

| [`fc189507`](https://github.com/nix-community/home-manager/commit/fc189507bc0bc74b3794ee6912a5b80de8dfcc0c) | `` docs: nixos module declarative installation instructions (#6208) `` |
| [`c36cc49e`](https://github.com/nix-community/home-manager/commit/c36cc49e55aff5562b0ca924f34285de6d6273be) | `` onlyoffice: add module (#6667) ``                                   |

chore(flake/home-manager): `94605dca` -> `fc189507`

---

flake.lock

| [`bcad8054`](https://github.com/lovesegfault/vim-config/commit/bcad8054beae499fa16cac17dcfd70bbcba3c83e) | `` chore(flake/treefmt-nix): b3b938ab -> adc195ee `` |
| [`9c6f0ba7`](https://github.com/lovesegfault/vim-config/commit/9c6f0ba756b3dd8ec72bb4ce06aa824d30dea4e7) | `` chore(flake/nixvim): d79c291d -> d44b33a1 ``      |

chore(flake/lovesegfault-vim-config): `6a823bc1` -> `bcad8054`

---

flake.lock

| [`da018181`](https://github.com/nix-community/home-manager/commit/da0181819479ddc034a3db9a77ed21ea3bcc0668) | `` tests: scrub lazy{docker,git} on darwin ``                |
| [`2e9981ca`](https://github.com/nix-community/home-manager/commit/2e9981ca0d6cee56f54a5e265b5edcd4dfc1b554) | `` lazydocker: null package support ``                       |
| [`65413f29`](https://github.com/nix-community/home-manager/commit/65413f297f8c4c42a99270c15bce7bda …

chore(flake/home-manager): `fc189507` -> `da018181`

---

flake.lock

| [`d6171149`](https://github.com/nix-community/home-manager/commit/d61711497be9ad6a6633aaf203b038b5a970621f) | `` iamb: nullable package support ``              |
| [`e5ab1811`](https://github.com/nix-community/home-manager/commit/e5ab18116c4dae69be789aaf33d70e901b5a9ba6) | `` iamb: new module ``                            |
| [`71cbeb3a`](https://github.com/nix-community/home-manager/commit/71cbeb3afd1ea8fa95af9dd6c0567d763ba44bee) | `` hyprpolkitagent: add …

chore(flake/home-manager): `da018181` -> `d6171149`

---

flake.lock

| [`296ddc64`](https://github.com/nix-community/home-manager/commit/296ddc64627f4a6a4eb447852d7346b9dd16197d) | `` zsh: adjust initContent priorities (#6676) `` |

chore(flake/home-manager): `8a68f18e` -> `296ddc64`

---

flake.lock

| [`2e834e6b`](https://github.com/lovesegfault/vim-config/commit/2e834e6b2fab70cc04db99751a86d7698ac6fbe6) | `` chore(flake/nixvim): d44b33a1 -> c9802712 `` |

chore(flake/lovesegfault-vim-config): `bcad8054` -> `2e834e6b`

---

flake.lock

| [`cbbe5aa8`](https://github.com/lovesegfault/vim-config/commit/cbbe5aa83a1fc8cfd4e1fa2e5945fe637ebb5311) | `` chore(flake/nixpkgs): b6eaf97c -> a84ebe20 `` |

chore(flake/lovesegfault-vim-config): `2e834e6b` -> `cbbe5aa8`

---

flake.lock

| [`380ed15b`](https://github.com/NixOS/nixos-hardware/commit/380ed15bcd6440606c6856db44a99140d422b46f) | `` framework: fix TRRS headphones modprobe `` |

chore(flake/nixos-hardware): `daaae13d` -> `380ed15b`

---

flake.lock

| [`63e77d09`](https://github.com/nix-community/home-manager/commit/63e77d09a133ac641a0c204e7cfb0c97e133706d) | `` jankyborders: add module (#6677) ``                     |
| [`94ea2cb5`](https://github.com/nix-community/home-manager/commit/94ea2cb536fa083665e12d08515d97313e0900f1) | `` treewide: zsh initExtraBeforeCompInit -> initContent `` |
| [`10deb9d0`](https://github.com/nix-community/home-manager/commit/10deb9d043e625d8c6a629f5575718e0768dcfb4 …

chore(flake/home-manager): `296ddc64` -> `63e77d09`

---

flake.lock

| [`9172a6f9`](https://github.com/nix-community/home-manager/commit/9172a6f956f7e0f7810861b9b1146f1c43d9abcb) | `` skhd: add module (#6682) ``                       |
| [`7853236f`](https://github.com/nix-community/home-manager/commit/7853236fae80bb625c319df8d730cad2a5584f26) | `` rclone: ensure remotes have a type field ``       |
| [`7a08b8c8`](https://github.com/nix-community/home-manager/commit/7a08b8c898bb594f271bbabd3972af2c89d68b11) | `` rclone: …

chore(flake/home-manager): `63e77d09` -> `9172a6f9`

---

flake.lock

| [`5ff90f09`](https://github.com/nix-community/home-manager/commit/5ff90f09d1bd189b722e60798513724cdd3580b6) | `` wofi: merge multiple style definitions (#6673) `` |
| [`b61ae3b6`](https://github.com/nix-community/home-manager/commit/b61ae3b677a07c30cf6be5233e772b97a3a8b2fb) | `` flake.lock: Update (#6684) ``                     |
| [`57e9a8a2`](https://github.com/nix-community/home-manager/commit/57e9a8a290cbeeb173b12d6bec1681e177ce6570) | `` davmail: init …

chore(flake/home-manager): `9172a6f9` -> `5ff90f09`

---

flake.lock

| [`0e75a404`](https://github.com/nix-community/home-manager/commit/0e75a40458d065d1e5c6a10d0b74b9e35b550ae6) | `` firefox: fix assertion when missing force for extensions (#6688) `` |
| [`ecbcd792`](https://github.com/nix-community/home-manager/commit/ecbcd792e1f6cd018b0858b5b3d11733cd19c46f) | `` firefox: check if bookmarks attrset is of correct type ``           |
| …

chore(flake/home-manager): `5ff90f09` -> `0e75a404`

---

flake.lock

| [`ad582692`](https://github.com/lovesegfault/vim-config/commit/ad5826921d2f6adc4efd714331c51a9c426282ca) | `` chore(flake/nixpkgs): a84ebe20 -> 1e5b653d `` |
| [`d1f1076a`](https://github.com/lovesegfault/vim-config/commit/d1f1076ad1ac3d3800a3124a099c2af61d7410e7) | `` chore(flake/nixvim): 3d84c137 -> 7776e37b ``  |

chore(flake/lovesegfault-vim-config): `60b47d7e` -> `ad582692`

---

flake.lock

| [`ad0614a1`](https://github.com/nix-community/home-manager/commit/ad0614a1ec9cce3b13169e20ceb7e55dfaf2a818) | `` firefox: don't show migration warning when bookmarks isn't set (#6689) `` |
| [`4f453846`](https://github.com/nix-community/home-manager/commit/4f4538467fd29a8f5037c0939592cd89cd401155) | `` firefox: fix migrate search v7 test for all firefox forks (#6690) ``      |

chore(flake/home-manager): `0e75a404` -> `ad0614a1`

---

flake.lock

| [`97280e24`](https://github.com/NixOS/nixos-hardware/commit/97280e2440a75ffae340304817e62c3130055963) | `` Make comment less intimidating (Lenovo X1 Yoga Gen 7) `` |

chore(flake/nixos-hardware): `380ed15b` -> `ecaa2d91`

---

flake.lock

| [`908e055e`](https://github.com/nix-community/home-manager/commit/908e055e157a0b35466faf4125d7e7410ff56160) | `` git: option to use difftastic as difftool (#5335) `` |

chore(flake/home-manager): `ad0614a1` -> `908e055e`

---

flake.lock

| [`c4d5d728`](https://github.com/nix-community/home-manager/commit/c4d5d72805d14ea43c140eeb70401bf84c0f11b4) | `` neomutt: remove empty lines (#6523) `` |

chore(flake/home-manager): `2d057cd9` -> `c4d5d728`

---

flake.lock

| [`b5f66861`](https://github.com/lovesegfault/vim-config/commit/b5f668612476ea0dc6e7cd30b5cdbfe884e9dcc3) | `` chore(flake/nixvim): 7776e37b -> ff46e752 `` |

chore(flake/lovesegfault-vim-config): `ad582692` -> `b5f66861`

---

flake.lock

| [`b4feb69f`](https://github.com/danth/stylix/commit/b4feb69fd2c1b6ef02a6a81761a62af62ac7bf1b) | `` stylix: wrap code comment to 80 characters (#1057) `` |
| [`5321ab0c`](https://github.com/danth/stylix/commit/5321ab0c763caa786c9756a8e8e85d1c35a8e650) | `` doc: add GitHub PR template (#1038) ``                |
| [`20349ced`](https://github.com/danth/stylix/commit/20349ced5c2c23c152bbfee1665001378585eb31) | `` doc: add GitHub issue templates (#921) ``             |

chore(flake/stylix): `d9df91c5` -> `b4feb69f`

---

flake.lock

| [`869f2ec2`](https://github.com/nix-community/home-manager/commit/869f2ec2add75ce2a70a6dbbf585b8399abec625) | `` zsh: fix concatenation of aliases and global aliases (#6698) `` |

chore(flake/home-manager): `c4d5d728` -> `869f2ec2`

---

flake.lock

| Commit                                                                                           | Message                    |
| ------------------------------------------------------------------------------------------------ | -------------------------- |
| [`2c563bd0`](https://github.com/LnL7/nix-darwin/commit/2c563bd0494510934319916d921a8cf05ecc941e) | `` expose extendModules `` |

chore(flake/darwin): `ebb88c34` -> `bb81755a`

---

flake.lock

| [`61a5f77f`](https://github.com/danth/stylix/commit/61a5f77f2202f3a79797089752713e16b1ab5b10) | `` doc: add contact links to issue template chooser (#1060) `` |

chore(flake/stylix): `b4feb69f` -> `61a5f77f`

---

flake.lock

| [`4954d586`](https://github.com/lovesegfault/vim-config/commit/4954d586bbcffbf94c08464dc696f82cab8460df) | `` chore(flake/nixvim): ff46e752 -> 6b95b825 `` |

chore(flake/lovesegfault-vim-config): `b5f66861` -> `4954d586`

---

flake.lock

| Commit                                                                                                      | Message                                                                                          |
| ----------------------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------------------ |
| [`0ff53f6d`](https://github.com/nix-community/home-manager/commit/0ff53f6d336edb3ad81647dc931ad1c9c7f890ca) | `` helix: add extraConfig option (#6575) ``                                                      |
| [`2321c688`](https://github.com/nix-community/home-manager/commit/2321c6889bd473d384b687c7d536d88fec3b3256) | `` ripgrep-all: Add module (#5459) `` …

chore(flake/home-manager): `8bef8b7a` -> `0ff53f6d`

---

flake.lock

| [`ce287a5c`](https://github.com/nix-community/home-manager/commit/ce287a5cd3ef78203bc78021447f937a988d9f6f) | `` mpdscribble: add module (#6259) `` |

chore(flake/home-manager): `0ff53f6d` -> `ce287a5c`

---

flake.lock

| [`693840c0`](https://github.com/nix-community/home-manager/commit/693840c01b9bef9e54100239cef937e53d4661bf) | `` vscode: Fix version checks when using Cursor (#6680) `` |

chore(flake/home-manager): `ce287a5c` -> `693840c0`

---

flake.lock

| Commit                                                                                        | Message                                                                  |
| --------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------ |
| [`daef51e9`](https://github.com/danth/stylix/commit/daef51e92086a5b4d6a7756ad495dfd34353b7cb) | `` doc: format and polish Nix code according to our formatter (#1025) `` |

chore(flake/stylix): `61a5f77f` -> `daef51e9`

---

flake.lock

| [`99b16ae3`](https://github.com/lovesegfault/vim-config/commit/99b16ae3dd5d55d88ef980e4b23f651c4147f2ba) | `` chore(flake/treefmt-nix): adc195ee -> 61c88349 `` |
| [`c6865a3d`](https://github.com/lovesegfault/vim-config/commit/c6865a3daec961032382a4e77ca8037dee3de1be) | `` chore(flake/nixvim): 6b95b825 -> 1c0dd320 ``      |

chore(flake/lovesegfault-vim-config): `4954d586` -> `99b16ae3`

---

flake.lock

| [`b3932834`](https://github.com/lovesegfault/vim-config/commit/b39328347c67ae5f4270066c1ef041be2a2f3780) | `` chore(flake/nixpkgs): 1e5b653d -> 698214a3 `` |

chore(flake/lovesegfault-vim-config): `99b16ae3` -> `b3932834`

---

flake.lock

| [`b14a70c4`](https://github.com/nix-community/home-manager/commit/b14a70c40f4fd0b73d095ab04a7c6e31fbc18e52) | `` fzf: update zsh integration to be after plugins (#6716) `` |

chore(flake/home-manager): `171915bf` -> `b14a70c4`

---

flake.lock

| [`a3e81829`](https://github.com/lovesegfault/vim-config/commit/a3e81829d697a503cec74086ab64362d5e86ed2b) | `` chore(flake/treefmt-nix): 61c88349 -> 29a3d7b7 `` |

chore(flake/lovesegfault-vim-config): `b3932834` -> `a3e81829`

---

flake.lock

| Commit                                                                                                 | Message                                              |
| ------------------------------------------------------------------------------------------------------ | ---------------------------------------------------- |
| [`ce5a3b9d`](https://github.com/nix-darwin/nix-darwin/commit/ce5a3b9db91ee65f2e969442884baac64b4b41f3) | `` treewide: point to the new GitHub organization `` |
| [`000c40f4`](https://github.com/nix-darwin/nix-darwin/commit/000c40f4fe7009118aac5b02d432dcb9321c3042) | `` readme: update contact information ``             |

chore(flake/darwin): `bb81755a` -> `75f8e4db`

---

flake.lock

| [`48465efc`](https://github.com/lovesegfault/vim-config/commit/48465efc6fb2af30e8ee3f8d993b35a1a9152200) | `` chore(flake/nixvim): 1c0dd320 -> 95573411 `` |

chore(flake/lovesegfault-vim-config): `a3e81829` -> `48465efc`

---

flake.lock

| [`1f679ed2`](https://github.com/nix-community/home-manager/commit/1f679ed2a2ebe3894bad9f89fb0bd9f141c28a68) | `` zsh-abbr: Add global abbreviations (#6720) `` |
| [`3527c8c7`](https://github.com/nix-community/home-manager/commit/3527c8c7785d1855ccf9da0e8436a0e769190b18) | `` sesh: add module (#5789) ``                   |

chore(flake/home-manager): `1efd2503` -> `1f679ed2`

---

flake.lock

| [`b4314965`](https://github.com/nix-community/home-manager/commit/b431496538b0e294fbe44a1441b24ae8195c63f0) | `` launchd: refactor setupLaunchAgents ``   |
| [`86d2e3b0`](https://github.com/nix-community/home-manager/commit/86d2e3b00561a166f8c31ff9ec6a947ca0992ec5) | `` launchd: remove checkLaunchAgents ``     |
| [`ef8f8987`](https://github.com/nix-community/home-manager/commit/ef8f898727d174b16a154b29e8c0f82d39cbac21) | `` launchd: add khaneliman maintainer ``    |
| …

chore(flake/home-manager): `1f679ed2` -> `b4314965`

---

flake.lock

| [`2bd73f74`](https://github.com/lovesegfault/vim-config/commit/2bd73f7497915dacfbb41b60a14fd057f6e7616e) | `` chore(flake/nixvim): 95573411 -> 81fdde9f ``  |
| [`c4ab4971`](https://github.com/lovesegfault/vim-config/commit/c4ab49716ee82db43c5bc6545c7c7f5a59b33155) | `` chore(flake/nixpkgs): 698214a3 -> 5e5402ec `` |

chore(flake/lovesegfault-vim-config): `48465efc` -> `2bd73f74`

---

flake.lock

| Commit                                                                                                      | Message                                                                           |
| ----------------------------------------------------------------------------------------------------------- | --------------------------------------------------------------------------------- |
| [`1d2ed9c5`](https://github.com/nix-community/home-manager/commit/1d2ed9c503cf41ca7f3db091edc8519dcdcd8b41) | `` flake.lock: Update (#6730) ``                                                  |
| [`802653e5`](https://github.com/nix-community/home-manager/commit/802653e5d1f654ac67c045ca6eea8c8cfa8fc052) | `` auto-upgrade: unbreak on unattended, loginctl enable-linger systems (#6719) `` |
| …

chore(flake/home-manager): `b4314965` -> `1d2ed9c5`

---

flake.lock

| [`12c72156`](https://github.com/lovesegfault/vim-config/commit/12c721563d58740d821c5815708db7624b7a313a) | `` chore(flake/nixvim): 81fdde9f -> d81f3725 `` |

chore(flake/lovesegfault-vim-config): `2bd73f74` -> `12c72156`

---

flake.lock

| [`c546582b`](https://github.com/danth/stylix/commit/c546582bae1a2c8745295a167b8db779215d780b) | `` bat: add copyright notice (#1070) ``                         |
| [`eede7135`](https://github.com/danth/stylix/commit/eede71351571c60b87dbf9eefb7ddf2b11fb1354) | `` ci: prevent unintentional credential persistence (#1074) ``  |
| [`20117a58`](https://github.com/danth/stylix/commit/20117a58eb73c0ac36d1421ba9dd89392053da9a) | `` ci: run all builds in a single job (#1069) …

chore(flake/stylix): `2fb8321e` -> `c546582b`

---

flake.lock

| Commit                                                                                                 | Message                                          |
| ------------------------------------------------------------------------------------------------------ | ------------------------------------------------ |
| [`e7bd2f8f`](https://github.com/nix-darwin/nix-darwin/commit/e7bd2f8f2f0829149ce99142e2ad1cdce9dff155) | `` nix-tools: re‐add `nixPackage` ``             |
| [`75a7fb88`](https://github.com/nix-darwin/nix-darwin/commit/75a7fb885d0afcaa77e6c930be991aab6a6755ab) | `` website: try to fix redirect ``               |
| [`516590cf`](https://github.com/nix-darwin/nix-darwin/commit/516590cf1299aceb7f987d433e14f406f9089973) | `` website: fix manual path ``                   |
| …

chore(flake/darwin): `75f8e4db` -> `eaff8219`

---

flake.lock

| [`de6fc555`](https://github.com/NixOS/nixos-hardware/commit/de6fc5551121c59c01e2a3d45b277a6d05077bc4) | `` added intel whiskey lake ``                      |
| [`a3f63440`](https://github.com/NixOS/nixos-hardware/commit/a3f63440fcfb280d7c9c5dd83f6cc95051867b17) | `` added lenovo thinkpad p43s ``                    |
| [`be7794e5`](https://github.com/NixOS/nixos-hardware/commit/be7794e5a66c81be581ceccaf741a97189652f95) | `` Added Lenovo Thinkpad P14s Gen 5 Intel config `` |

chore(flake/nixos-hardware): `0ed819e7` -> `de6fc555`

---

flake.lock

| Commit                                                                                                      | Message                                                                                        |
| ----------------------------------------------------------------------------------------------------------- | ---------------------------------------------------------------------------------------------- |
| [`ccd7df83`](https://github.com/nix-community/home-manager/commit/ccd7df836e1f42ea84806760f25b77b586370259) | `` mcfly: Fix fzf overriding mcfly's Ctrl+R bind on fish(#6736) ``                             |
| [`21669077`](https://github.com/nix-community/home-manager/commit/216690777e47aa0fb1475e4dbe2510554ce0bc4b) | `` nixos-module: Fix potential recursion between users.users …

chore(flake/home-manager): `b6fd653e` -> `ccd7df83`

---

flake.lock

| [`1a2f1af9`](https://github.com/danth/stylix/commit/1a2f1af9f999b23c44a0b15a8841a7a297576a9c) | `` discord: add extraCss option (#1058) `` |
| [`eb19696b`](https://github.com/danth/stylix/commit/eb19696b18fd65ddcc6fbec5056b92b75b4f4343) | `` stylix: add overlay module (#1048) ``   |

chore(flake/stylix): `c546582b` -> `1a2f1af9`

---

flake.lock

| [`c21383b5`](https://github.com/nix-community/home-manager/commit/c21383b556609ce1ad901aa08b4c6fbd9e0c7af0) | `` streamlink: init module (#6031) ``     |
| [`5e193cdc`](https://github.com/nix-community/home-manager/commit/5e193cdcab61b5e7096ef3c132fdc0149e14f2d9) | `` msmtp: fix missing inherits (#6741) `` |
| [`0b491b46`](https://github.com/nix-community/home-manager/commit/0b491b460f52e87e23eb17bbf59c6ae64b7664c1) | `` treewide: remove with lib (#6735) ``   |

chore(flake/home-manager): `ccd7df83` -> `c21383b5`

---

flake.lock

| Commit                                                                                                      | Message                                                                                       |
| ----------------------------------------------------------------------------------------------------------- | --------------------------------------------------------------------------------------------- |
| [`f4d9d1e2`](https://github.com/nix-community/home-manager/commit/f4d9d1e2ad19d544a0a0cf3f8f371c6139c762e9) | `` broot: get rid of IFDs (#6723) ``                                                          |
| [`0afad8f0`](https://github.com/nix-community/home-manager/commit/0afad8f08014c992c832466c1d46a0aa96ca2563) | `` Revert "nixos-module: Fix potential recursion between …

chore(flake/home-manager): `c21383b5` -> `f4d9d1e2`

---

flake.lock

| [`baa21ff1`](https://github.com/lovesegfault/vim-config/commit/baa21ff13e8cc5ad19053bcb6cd5c8245f8c5468) | `` chore(flake/flake-parts): f4330d22 -> c621e842 `` |
| [`60785d7e`](https://github.com/lovesegfault/vim-config/commit/60785d7edb1eb1d19f8370913edb3eccba12c40d) | `` chore(flake/nixvim): d81f3725 -> 754b8df7 ``      |
| [`c8aaf011`](https://github.com/lovesegfault/vim-config/commit/c8aaf01179026303edfddd8abedc10e4fb71f2da) | `` chore(flake/nixpkgs): 5e5402ec …

chore(flake/lovesegfault-vim-config): `12c72156` -> `baa21ff1`

---

flake.lock

| [`5ee44bc7`](https://github.com/nix-community/home-manager/commit/5ee44bc7c2e853f144390a12ebe5174ad7e3b9e0) | `` news: add services.home-manager.autoExpire entry `` |
| [`28242a60`](https://github.com/nix-community/home-manager/commit/28242a60d3cdcb6675dfe68ebbb64bf43c7be4e0) | `` home-manager-auto-expire: init ``                   |
| [`938e802b`](https://github.com/nix-community/home-manager/commit/938e802b70ee7700141b18ef8dca05ad89917a37) | `` …

chore(flake/home-manager): `f4d9d1e2` -> `5ee44bc7`

---

flake.lock

| [`1d33ebcc`](https://github.com/lovesegfault/vim-config/commit/1d33ebcc7f00a6ddd2862c521af2ea5e9023cbd4) | `` chore(flake/treefmt-nix): 29a3d7b7 -> 18bed671 `` |
| [`61131268`](https://github.com/lovesegfault/vim-config/commit/61131268ac5e595201ac6a2e52abe384edc63579) | `` chore(flake/nixvim): 754b8df7 -> a183298b ``      |

chore(flake/lovesegfault-vim-config): `baa21ff1` -> `1d33ebcc`

---

flake.lock

| [`7e7e8c41`](https://github.com/lovesegfault/vim-config/commit/7e7e8c41328c2004c9b5e25b292fff391fb7dd95) | `` chore(flake/nixvim): a183298b -> 9f495dda ``      |
| [`c8ccf5e1`](https://github.com/lovesegfault/vim-config/commit/c8ccf5e1e1686aaf58ec48dea7af332ab2af3ef3) | `` chore(flake/treefmt-nix): 18bed671 -> 57dabe2a `` |
| [`d566b0e3`](https://github.com/lovesegfault/vim-config/commit/d566b0e3a2bb81be0cdda9a0727f1583c9caaac7) | `` chore(flake/nixpkgs): 52faf482 …

chore(flake/lovesegfault-vim-config): `1d33ebcc` -> `7e7e8c41`

---

flake.lock

| [`581fa67c`](https://github.com/danth/stylix/commit/581fa67c818aaf91a1533149fb737d3e8c0949b8) | `` stylix: guard entire overlay declarations (#1088) ``                 |
| [`a214b330`](https://github.com/danth/stylix/commit/a214b330e5d8940b05ccd951eb5c6ac0f13d125f) | `` mpv: unset subtitle font size (#1090) ``                             |
| [`9ef80628`](https://github.com/danth/stylix/commit/9ef806283b87f99dfa574b6642165cf052a1d49e) | `` discord: …

chore(flake/stylix): `1a2f1af9` -> `581fa67c`

---

flake.lock

| [`a802defb`](https://github.com/nix-community/home-manager/commit/a802defb16dcdcc7fd0ff5a2d7be913ce2fe79e7) | `` playerctld: add to `$PATH` (#6753) ``                                 |
| [`f3ac07f2`](https://github.com/nix-community/home-manager/commit/f3ac07f2f7c368952a9e7da64ec0991526f49020) | `` smug: init module (#6696) ``                                          |
| …

chore(flake/home-manager): `107352dd` -> `a802defb`

---

flake.lock

| [`bc76df0d`](https://github.com/lovesegfault/vim-config/commit/bc76df0dd799f2b53694cd0f523ba9cce1132fd1) | `` chore(flake/nixpkgs): 2c8d3f48 -> 42a1c966 ``     |
| [`022717a9`](https://github.com/lovesegfault/vim-config/commit/022717a9cd1299ab5e7ca413a25fa25f0c24aa55) | `` chore(flake/nixvim): 7b431133 -> 99a2f96c ``      |
| [`ee19b44f`](https://github.com/lovesegfault/vim-config/commit/ee19b44f44f7ebf69750101dd798837f52c9d2ed) | `` chore(flake/nixvim): 9f495dda …

chore(flake/lovesegfault-vim-config): `7e7e8c41` -> `bc76df0d`

---

flake.lock

| [`f98c2c42`](https://github.com/danth/stylix/commit/f98c2c42b210128f5a62099c12bc566b0050fea9) | `` mpv: unset OSD font size (#1097) `` |

chore(flake/stylix): `9a3fb931` -> `f98c2c42`

---

flake.lock

| [`f463902a`](https://github.com/nix-community/home-manager/commit/f463902a3f03e15af658e48bcc60b39188ddf734) | `` .git-blame-ignore-revs: init (#6767) ``                        |
| [`c15ab0ce`](https://github.com/nix-community/home-manager/commit/c15ab0ce0dbe64843358a3081b09ed35144dfd65) | `` swayr: systemd.target default to wayland.systemd target ``     |
| [`320e152d`](https://github.com/nix-community/home-manager/commit/320e152d0bad …

chore(flake/home-manager): `a802defb` -> `f463902a`

---

flake.lock

| [`02db4961`](https://github.com/Mic92/nix-fast-build/commit/02db4961dd394ed26a11defc25d2e73e93a4191e) | `` chore(deps): update nixpkgs digest to da98c5d ``            |
| [`662a0e96`](https://github.com/Mic92/nix-fast-build/commit/662a0e96626a80fcece298f755d680771f6c171e) | `` chore(deps): lock file maintenance (#116) ``                |
| [`e85548d5`](https://github.com/Mic92/nix-fast-build/commit/e85548d51e60ac6121e58d087856ee26f03df27d) | `` …

chore(flake/nix-fast-build): `0ef0c606` -> `ce8bd0c1`

---

flake.lock

| [`e943b4e4`](https://github.com/lovesegfault/vim-config/commit/e943b4e4262127f7e132299369ce03c65368b99f) | `` chore(flake/nixpkgs): 42a1c966 -> 063dece0 `` |
| [`7d8c4d94`](https://github.com/lovesegfault/vim-config/commit/7d8c4d94fe8db30f1333c14d71b63a2563240e01) | `` chore(flake/nixvim): 99a2f96c -> cc891866 ``  |

chore(flake/lovesegfault-vim-config): `bc76df0d` -> `e943b4e4`

---

flake.lock

| [`a4d80208`](https://github.com/nix-community/home-manager/commit/a4d8020820a85b47f842eae76ad083b0ec2a886a) | `` flake.nix: include more doc outputs ``           |
| [`1a186efb`](https://github.com/nix-community/home-manager/commit/1a186efb48030b06975677a6b8331fbe9e9a3e46) | `` default.nix: add htmlOpenTool output for docs `` |
| [`14269b06`](https://github.com/nix-community/home-manager/commit/14269b06a06601aecfd10c33f3f2a45b304b23d5) | `` docs/flake.nix: add …

chore(flake/home-manager): `f463902a` -> `a4d80208`

---

flake.lock

| Commit                                                                                        | Message                                                                     |
| --------------------------------------------------------------------------------------------- | --------------------------------------------------------------------------- |
| [`a2f8840b`](https://github.com/danth/stylix/commit/a2f8840bed6daade6b980426c9f72dd672e92329) | `` hyprland: disable default wallpaper when hyprpaper is enabled (#1120) `` |

chore(flake/stylix): `be86a9aa` -> `a2f8840b`

---

flake.lock

| Commit                                                                                               | Message                                |
| ---------------------------------------------------------------------------------------------------- | -------------------------------------- |
| [`8f806681`](https://github.com/nix-community/disko/commit/8f806681d781ca250ddaafd262d6b6c89d79d9ef) | `` tree-wise: quote path correctlys `` |

chore(flake/disko): `329d3d7e` -> `8f806681`

---

flake.lock

| [`760eed59`](https://github.com/nix-community/home-manager/commit/760eed59594f2f258db0d66b7ca4a5138681fd97) | `` flake.nix: remove treefmt-nix input (#6782) `` |

chore(flake/home-manager): `fefb6ae1` -> `760eed59`

---

flake.lock

| [`a8e75da0`](https://github.com/nix-community/disko/commit/a8e75da08f462a2a4cc9a637643bda4eb1ea2d6c) | `` disko-deactivate: fix jq syntax `` |

chore(flake/disko): `8f806681` -> `a8e75da0`

---

flake.lock

| [`241f9f66`](https://github.com/lovesegfault/vim-config/commit/241f9f664f2b375e541589929ee94f73bf350d5c) | `` chore(flake/nixvim): cc891866 -> 7114362f `` |

chore(flake/lovesegfault-vim-config): `e943b4e4` -> `241f9f66`

---

flake.lock

| [`4040c577`](https://github.com/nix-community/home-manager/commit/4040c5779ce56d36805bc7a83e072f0f894eae7d) | `` modules/programs/ssh: support identityAgent (#6783) `` |

chore(flake/home-manager): `760eed59` -> `4040c577`

---

flake.lock

| [`ce45f19e`](https://github.com/danth/stylix/commit/ce45f19e8acb43e5f02888d873d451e2f994546b) | `` kde: add run wrapper (#1117) ``                             |
| [`82f67a36`](https://github.com/danth/stylix/commit/82f67a36eba1b111f8d568bf5e5ceb30e4b623d6) | `` doc: align module capitalization (#1115) ``                 |
| [`31fdf606`](https://github.com/danth/stylix/commit/31fdf60634beaa0bb14fa57fc64cd5a67d1bf101) | `` stylix: disallow nixpkgs aliases in testbeds …

chore(flake/stylix): `a2f8840b` -> `ce45f19e`

---

flake.lock

| [`8d0724fc`](https://github.com/lovesegfault/vim-config/commit/8d0724fcc18145eb1790cd27543fd9f77057cef9) | `` chore(flake/nixvim): 7114362f -> 51203927 ``  |
| [`269b8ca0`](https://github.com/lovesegfault/vim-config/commit/269b8ca0e615b0c429775f1f8ee262aabb93058b) | `` chore(flake/nixpkgs): 063dece0 -> c8cd8142 `` |

chore(flake/lovesegfault-vim-config): `241f9f66` -> `8d0724fc`

---

flake.lock

| [`79461936`](https://github.com/nix-community/home-manager/commit/79461936709b12e17adb9c91dd02d1c66d577f09) | `` hyprland: load plugins using exec-once (#6789) `` |

chore(flake/home-manager): `542efdf2` -> `79461936`

---

flake.lock

| [`93b318c2`](https://github.com/Mic92/nix-fast-build/commit/93b318c24112dd435a265ecc6bf09401e63ade63) | `` chore(deps): update nixpkgs digest to 4838207 (#118) `` |

chore(flake/nix-fast-build): `ce8bd0c1` -> `93b318c2`

---

flake.lock

| Commit                                                                                               | Message                           |
| ---------------------------------------------------------------------------------------------------- | --------------------------------- |
| [`76c0a6db`](https://github.com/nix-community/disko/commit/76c0a6dba345490508f36c1aa3c7ba5b6b460989) | `` udevadm settle: use timeout `` |

chore(flake/disko): `a8e75da0` -> `76c0a6db`

---

flake.lock

| Commit                                                                                                 | Message                                     |
| ------------------------------------------------------------------------------------------------------ | ------------------------------------------- |
| [`5417dfd5`](https://github.com/nix-darwin/nix-darwin/commit/5417dfd58cbc1c475a0b3ffc5b016b29514d6fb8) | `` services/netdata: add cacheDir option `` |

chore(flake/darwin): `73d59580` -> `113883e3`

---

flake.lock

| [`8638a0b2`](https://github.com/nix-community/home-manager/commit/8638a0b28727a8cdbe851fefded3b8e96f4cf763) | `` sesh: add icons option (#6794) ``                  |
| [`140a7df9`](https://github.com/nix-community/home-manager/commit/140a7df916f6257c755b8663fb27ed79e81c8e89) | `` formatter: use a different treefmt root (#6792) `` |
| [`92266c9a`](https://github.com/nix-community/home-manager/commit/92266c9a6f03b7d86efc056580a1fddb89635a59) | `` btop: adjust …

chore(flake/home-manager): `79461936` -> `8638a0b2`

---

flake.lock

| [`f1ffd097`](https://github.com/nix-community/home-manager/commit/f1ffd097e717a8d1b441577b8d23f9d2c96e0657) | `` hyprsunset: support multiple commands to IPC ``                         |
| [`cf6314f8`](https://github.com/nix-community/home-manager/commit/cf6314f8e173e208882e32ed85158f78bf74d085) | `` hyprsunset: init ``                                                     |
| …

chore(flake/home-manager): `8638a0b2` -> `f1ffd097`

---

flake.lock

| Commit                                                                                                      | Message                                                                       |
| ----------------------------------------------------------------------------------------------------------- | ----------------------------------------------------------------------------- |
| [`e43c6bcb`](https://github.com/nix-community/home-manager/commit/e43c6bcb101ba3301522439c459288c4a248f624) | `` anyrun: init module (#6804) ``                                             |
| [`6bccb54a`](https://github.com/nix-community/home-manager/commit/6bccb54a4f98408f22d2e45921bb401f393f2174) | `` aerospace: revert flattening on-window-detected rules (#6803) ``           |
| …

chore(flake/home-manager): `f1ffd097` -> `e43c6bcb`

---

flake.lock

| [`4fc9ea78`](https://github.com/nix-community/nix-index-database/commit/4fc9ea78c962904f4ea11046f3db37c62e8a02fd) | `` update generated.nix to release 2025-04-13-041853 `` |
| [`9fba28cf`](https://github.com/nix-community/nix-index-database/commit/9fba28cf3d5dff9abd4e8fd7a942294294c01a6d) | `` flake.lock: Update ``                                |

chore(flake/nix-index-database): `a36f6a71` -> `4fc9ea78`

---

flake.lock

| [`042db377`](https://github.com/danth/stylix/commit/042db377bccc99b1a724b076c89ba803e411d889) | `` fcitx5: enable theme, refactor (#1131) ``                |
| [`379ba613`](https://github.com/danth/stylix/commit/379ba613a68fafdd756db370f0ef878a0d3a7308) | `` ci: explicit permissions for github app token (#1132) `` |
| [`2ce9f0ec`](https://github.com/danth/stylix/commit/2ce9f0ec13a12682856fac549de1ac86dc4aa51a) | `` emacs: add panchoh as maintainer (#1068) ``              | …

chore(flake/stylix): `ce45f19e` -> `042db377`

---

flake.lock

| [`cfa196c7`](https://github.com/nix-community/home-manager/commit/cfa196c705a896372319249d757085876ab62448) | `` flake.lock: Update (#6812) ``                               |
| [`4f898f37`](https://github.com/nix-community/home-manager/commit/4f898f373d8b0bfdac635b036396c90b0ad17be8) | `` helix: add support for path and string themes (#6814) ``    |
| [`db56335c`](https://github.com/nix-community/home-manager/commit/db56335ca8942d86f2200664 …

chore(flake/home-manager): `b74b22bb` -> `cfa196c7`

---

flake.lock

| [`ac3c1f4f`](https://github.com/nix-community/home-manager/commit/ac3c1f4fa40497b07f1f3ea3c4f644ce5dbcd2a4) | `` foot: enable duplicate key-bindings (#6815) `` |
| [`14229249`](https://github.com/nix-community/home-manager/commit/1422924908881faf59722810884addf109ebea07) | `` Translate using Weblate (Czech) (#6813) ``     |

chore(flake/home-manager): `cfa196c7` -> `ac3c1f4f`

---

flake.lock

| [`8a3584b7`](https://github.com/lovesegfault/vim-config/commit/8a3584b7a2d9a0c6a396169d871463c4554c60ee) | `` chore(flake/nixpkgs): c8cd8142 -> f675531b `` |

chore(flake/lovesegfault-vim-config): `8d0724fc` -> `8a3584b7`
