- flake.lock
| [`1556d8c5`](https://github.com/Mic92/nix-fast-build/commit/1556d8c533d8fee16ee7c46aa7092ef18d8b39ae) | `` chore(deps): update nixpkgs digest to d3dc44f (#123) `` |
| [`3df8aa89`](https://github.com/Mic92/nix-fast-build/commit/3df8aa89f7279746d790c014edc5208eb668c272) | `` chore(deps): update nixpkgs digest to 208645b (#122) `` |
| [`b01f2559`](https://github.com/Mic92/nix-fast-build/commit/b01f2559cdcef1f9c42ce3cac324256bd2b7955d) | `` chore(deps): update …
> chore(flake/nix-fast-build): `93b318c2` -> `1556d8c5`

- flake.lock
| Commit                                                                                                  | Message                                                                               |
| ------------------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------- |
| [`6db1e653`](https://github.com/tinted-theming/schemes/commit/6db1e6536a81339ff06bfe8aaaaf35f5a9032d5f) | `` Add and update github schemes to reflect the Tinted Theming styling spec (#52) ``  |
| [`0f18375c`](https://github.com/tinted-theming/schemes/commit/0f18375cac261b94e7fafa12ac1fd0d29c07349a) | `` Ensure relevant scheme-system exists in yaml file (#51) ``                         |
| …
> chore(flake/tinted-schemes): `c37771c4` -> `6db1e653`

- flake.lock
| [`33754144`](https://github.com/nix-community/home-manager/commit/337541447773985f825512afd0f9821a975186be) | `` helix: fix str + path theme (#6816) ``      |
| [`85dd758c`](https://github.com/nix-community/home-manager/commit/85dd758c703ffbf9d97f34adcef3a898b54b4014) | `` yazi: remove assertions (#6817) ``          |
| [`e980d0e0`](https://github.com/nix-community/home-manager/commit/e980d0e0e216f527ea73cfd12c7b019eceffa7f1) | `` nh: support 4.0 for flake option (#6818) …
> chore(flake/home-manager): `ac3c1f4f` -> `33754144`

- flake.lock
| [`db7738e6`](https://github.com/nix-community/home-manager/commit/db7738e67a101ad945abbcb447e1310147afaf1b) | `` nh: remove incorrect warning on gc conflicts (#6802) ``     |
| [`85c513aa`](https://github.com/nix-community/home-manager/commit/85c513aa862228d5b51295b20ccbdcc5fdf086bc) | `` home-manager: Feature test for flake support (#6824) ``     |
| [`d5cdf55b`](https://github.com/nix-community/home-manager/commit/d5cdf55bd9f19a3debd55b6c …
> chore(flake/home-manager): `5a096a88` -> `db7738e6`

- flake.lock
| [`c2d972be`](https://github.com/Mic92/nix-fast-build/commit/c2d972bed84323146535ac2e3e69e8a2d995eabd) | `` chore(deps): update treefmt-nix digest to 49d0555 (#126) `` |
> chore(flake/nix-fast-build): `1556d8c5` -> `c2d972be`

- flake.lock
| [`49d05555`](https://github.com/numtide/treefmt-nix/commit/49d05555ccdd2592300099d6a657cc33571f4fe0) | `` feat: Add buf as formatter (#337) `` |
> chore(flake/treefmt-nix): `815e4121` -> `49d05555`

- flake.lock
| [`6912b7d8`](https://github.com/lovesegfault/vim-config/commit/6912b7d8a7147f828fd49f8700dc43c33be44ba2) | `` chore(flake/treefmt-nix): 815e4121 -> 49d05555 `` |
> chore(flake/lovesegfault-vim-config): `8a3584b7` -> `6912b7d8`

- flake.lock
| [`5d48f3de`](https://github.com/nix-community/home-manager/commit/5d48f3ded3b55ef32d5853c9022fb4df29b3fc45) | `` mcfly: Fix mcfly-fzf initialization crash for fish and zsh (#6827) `` |
| [`401e7b54`](https://github.com/nix-community/home-manager/commit/401e7b544e7c8e8a59f4ec7f1745f7619bbfbde3) | `` Translate using Weblate (Dutch) (#6828) ``                            |
> chore(flake/home-manager): `db7738e6` -> `5d48f3de`

- flake.lock
| [`9342605c`](https://github.com/lovesegfault/vim-config/commit/9342605cfb46b84b401958f5a39c9b0b3ffb99cc) | `` fix: remove treesitter settings moved to dependencies `` |
| [`b5d68019`](https://github.com/lovesegfault/vim-config/commit/b5d68019478877188d2d1f10a4c41d21823b7c12) | `` chore(flake/nixvim): 51203927 -> d4dada28 ``             |
| [`2c481816`](https://github.com/lovesegfault/vim-config/commit/2c481816390af94428ce22cd8ad637a356f85796) | `` …
> chore(flake/lovesegfault-vim-config): `6912b7d8` -> `9342605c`

- flake.lock
| [`72526a5f`](https://github.com/nix-community/home-manager/commit/72526a5f7cde2ef9075637802a1e2a8d2d658f70) | `` tests/firefox: fix test commands (#6840) ``                     |
| [`e72178b8`](https://github.com/nix-community/home-manager/commit/e72178b84e440703e17ff5d393ba060784bed099) | `` tests/atuin: add theme test ``                                  |
| [`88e61873`](https://github.com/nix-community/home-manager/commit/88e61873 …
> chore(flake/home-manager): `5d48f3de` -> `72526a5f`

- flake.lock
| [`5e6a8203`](https://github.com/nix-community/home-manager/commit/5e6a8203cee7cc33b2e0d9a0adb7268f46447292) | `` khard: add option to set mutiple subdirs (#6823) `` |
> chore(flake/home-manager): `72526a5f` -> `5e6a8203`

- flake.lock
| [`fc09cb7a`](https://github.com/nix-community/home-manager/commit/fc09cb7aaadb70d6c4898654ffc872f0d2415df9) | `` tests/labwc: fix autostart ``          |
| [`4d6a8f59`](https://github.com/nix-community/home-manager/commit/4d6a8f590e46e62075e6787860f0ea030bab7651) | `` keepassxc: nullable package support `` |
| [`54b494a7`](https://github.com/nix-community/home-manager/commit/54b494a77fb9fa68b0ebd7f75a8179cca0b286cd) | `` keepassxc: add module ``               |
> chore(flake/home-manager): `5e6a8203` -> `fc09cb7a`

- flake.lock
| [`9676e8a5`](https://github.com/nix-community/home-manager/commit/9676e8a52a177d80c8a42f66566362a6d74ecf78) | `` inori: init module (#6289) ``                              |
| [`ae84885d`](https://github.com/nix-community/home-manager/commit/ae84885d9b6b62dc58ccd300e9ab321a3fd9f9c7) | `` workflows/conflicts: init (#6845) ``                       |
| [`307281bf`](https://github.com/nix-community/home-manager/commit/307281bfda7f3e3469234a03a7dd …
> chore(flake/home-manager): `fc09cb7a` -> `9676e8a5`

- flake.lock
| [`9af60cb4`](https://github.com/lovesegfault/vim-config/commit/9af60cb4283958c4188a29018f9e01222881e47e) | `` chore(flake/nixpkgs): 2631b0b7 -> b024ced1 ``     |
| [`99fc4664`](https://github.com/lovesegfault/vim-config/commit/99fc466416a16dc837621a2db4af7fe2e621a604) | `` chore(flake/nixvim): 500b56f0 -> 710f9cbd ``      |
| [`9f323319`](https://github.com/lovesegfault/vim-config/commit/9f3233191feb9a56f3e74e1049a2391c8df307f6) | `` chore(flake/treefmt-nix): …
> chore(flake/lovesegfault-vim-config): `90f6ebc2` -> `9af60cb4`

- flake.lock
| [`f98314bb`](https://github.com/nix-community/home-manager/commit/f98314bb064cf8f8446c44afbadaaad2505875a7) | `` restic: init module (#6729) ``                                               |
| [`bb8d2866`](https://github.com/nix-community/home-manager/commit/bb8d286649e97b89ad7dedae90418ff78f028c9d) | `` zed-editor: add themes option (#6832) ``                                     |
| …
> chore(flake/home-manager): `9676e8a5` -> `f98314bb`

- flake.lock
| Commit                                                                                        | Message                                        |
| --------------------------------------------------------------------------------------------- | ---------------------------------------------- |
| [`758fe634`](https://github.com/danth/stylix/commit/758fe63490093650075ec7587b7a6eb38614a4dd) | `` helix: use theme option ``                  |
| [`8b0d9317`](https://github.com/danth/stylix/commit/8b0d9317edd57c5374adcf6957ae4775875c2a9d) | `` btop: use theme option (#1126) ``           |
| [`8d5cd725`](https://github.com/danth/stylix/commit/8d5cd725ad591890c0cd804bf68cc842b8afca51) | `` qt: fix kvantum breaking plasma6 (#1128) `` |
> chore(flake/stylix): `38aff11a` -> `758fe634`

- flake.lock
| [`496fa9c0`](https://github.com/nix-community/home-manager/commit/496fa9c054d3a212c8bcb3ac80ab310841eed361) | `` PR_TEMPLATE: mention nix fmt (#6859) ``             |
| [`b71ca269`](https://github.com/nix-community/home-manager/commit/b71ca269615b0837724dac13358a2f0d6816d372) | `` uv: nullable package support ``                     |
| [`1d2d6b95`](https://github.com/nix-community/home-manager/commit/1d2d6b95688a6cb7555e2d50ba6ef1ebaa916546) | `` uv: init …
> chore(flake/home-manager): `f98314bb` -> `496fa9c0`

- flake.lock
| [`3fbe9a2b`](https://github.com/nix-community/home-manager/commit/3fbe9a2b76ff5c4dcb2a2a2027dac31cfc993c8c) | `` tests/ranger: null package ``       |
| [`63bfbf55`](https://github.com/nix-community/home-manager/commit/63bfbf55b6e561f5c517a29f9bf9157ff9dd8c87) | `` ranger: nullable package support `` |
| [`14eda3db`](https://github.com/nix-community/home-manager/commit/14eda3db4e0347bb03f0d2e32f28f4467744abe1) | `` clock-rs: add module ``             |
| …
> chore(flake/home-manager): `496fa9c0` -> `3fbe9a2b`

- flake.lock
| [`efa0a2b4`](https://github.com/nix-community/lanzaboote/commit/efa0a2b46761fd54d53dad0a9dade7c4851b0986) | `` chore(deps): lock file maintenance `` |
> chore(flake/lanzaboote): `d8099586` -> `e4cf2086`

- flake.lock
| [`039e938b`](https://github.com/danth/stylix/commit/039e938b29ce870ba326be1d60ae6d7c0a58f84e) | `` doc: promote lib.singleton in testbeds (#1148) `` |
| [`179220cf`](https://github.com/danth/stylix/commit/179220cfc24b77e206fe240fac76d7974c32c8d4) | `` gitui: switch from rgb to hex (#1144) ``          |
> chore(flake/stylix): `758fe634` -> `039e938b`

- flake.lock
| [`63179514`](https://github.com/lovesegfault/vim-config/commit/631795147bcf7da048d6ac094172319399cfe75e) | `` chore(flake/nixvim): 710f9cbd -> 6c4e2d92 `` |
> chore(flake/lovesegfault-vim-config): `9af60cb4` -> `63179514`

- flake.lock
| Commit                                                                                               | Message                                                                   |
| ---------------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------- |
| [`1770bf1a`](https://github.com/nix-community/disko/commit/1770bf1ae5da05564f86b969ef21c7228cc1a70b) | `` flake.lock: Update ``                                                  |
| [`51d33bbb`](https://github.com/nix-community/disko/commit/51d33bbb7f1e74ba5f9d9a77357735149da99081) | `` UI nit: remove unnecessary newline when prompting user for password `` |
> chore(flake/disko): `76c0a6db` -> `1770bf1a`

- flake.lock
| [`82ee14ff`](https://github.com/nix-community/home-manager/commit/82ee14ff60611b46588ea852f267aafcc117c8c8) | `` treewide: remove with lib (#6871) ``          |
| [`6695b1d4`](https://github.com/nix-community/home-manager/commit/6695b1d477246e30a3f14a7084c82775b30c09c1) | `` kconfig: escape arguments properly (#6867) `` |
> chore(flake/home-manager): `3fbe9a2b` -> `82ee14ff`

- flake.lock
| [`ddda2b1f`](https://github.com/nix-community/home-manager/commit/ddda2b1f20ffc92b803fc5c8c0d80bbfb54cd478) | `` direnv: only set sessionVariable for old version (#6842) `` |
> chore(flake/home-manager): `82ee14ff` -> `ddda2b1f`

- flake.lock
| [`22b326b4`](https://github.com/nix-community/home-manager/commit/22b326b42bf42973d5e4fe1044591fb459e6aeac) | `` television: add module (#6866) ``                    |
| [`be4e5ec6`](https://github.com/nix-community/home-manager/commit/be4e5ec62ce5703a00e40668f7a1a79d04c2195d) | `` nix-init: add module (#6864) ``                      |
| [`08b85bd0`](https://github.com/nix-community/home-manager/commit/08b85bd0002c7ac500b8d9ac0112467885712b1f) | `` …
> chore(flake/home-manager): `ddda2b1f` -> `22b326b4`

- flake.lock
| [`e6a29342`](https://github.com/lovesegfault/vim-config/commit/e6a293425b6a5750b7c93c22087483071d12acfe) | `` chore(flake/nixvim): 6c4e2d92 -> 7a581099 `` |
> chore(flake/lovesegfault-vim-config): `63179514` -> `e6a29342`

- flake.lock
| [`6899001a`](https://github.com/nix-community/home-manager/commit/6899001a762b0e089ad7b8ec7637d0a678640b8e) | `` fcitx5: add `themes` and `classicUiConfig` options (#6876) `` |
| [`c9433ae6`](https://github.com/nix-community/home-manager/commit/c9433ae62fbb4bd09609e242569edc3b551e21a9) | `` keepassxc: register as native messaging host (#6879) ``       |
| [`b925865c`](https://github.com/nix-community/home-manager/commit/b925865c74a783c2 …
> chore(flake/home-manager): `22b326b4` -> `6899001a`

- flake.lock
| [`4e7213fa`](https://github.com/lovesegfault/vim-config/commit/4e7213fadd1c268208853ea2e9ad3ca8cf9a0674) | `` chore(flake/nixpkgs): b024ced1 -> c11863f1 `` |
| [`16417a50`](https://github.com/lovesegfault/vim-config/commit/16417a50990ede10e35842b5d74c0a0fd7c51c14) | `` chore(flake/nixvim): 7a581099 -> 60638182 ``  |
> chore(flake/lovesegfault-vim-config): `e6a29342` -> `4e7213fa`

- flake.lock
| [`1d0e1390`](https://github.com/nix-community/home-manager/commit/1d0e13904bd8c444ab1595f686ede5eff377e881) | `` i18n.inputMethod: add awwpotato as maintainer ``                       |
| [`585bae4b`](https://github.com/nix-community/home-manager/commit/585bae4bbb48789ece06f4b18cb373651760c4ab) | `` i18n.inputMethod: align enable option with nixos ``                    |
| …
> chore(flake/home-manager): `6899001a` -> `1d0e1390`

- flake.lock
| [`6d1f834c`](https://github.com/nix-community/home-manager/commit/6d1f834ca63700604a96d8c38aa8ac272d95071a) | `` fcitx5: add upstream options (#6892) ``                                |
| [`59de2dfb`](https://github.com/nix-community/home-manager/commit/59de2dfb0a08ebcbc73e3bb8488d2c23057e6ad8) | `` workflows: only run conflicts and update flake on main repo (#6893) `` |
| …
> chore(flake/home-manager): `1d0e1390` -> `6d1f834c`

- flake.lock
| [`7ce50320`](https://github.com/lovesegfault/vim-config/commit/7ce503204b701ca0f9c7babd34e0e49998ce2867) | `` chore(flake/nixvim): 60638182 -> 78f6ff03 `` |
> chore(flake/lovesegfault-vim-config): `4e7213fa` -> `7ce50320`

- flake.lock
| [`abfad3d2`](https://github.com/nix-community/home-manager/commit/abfad3d2958c9e6300a883bd443512c55dfeb1be) | `` treewide: substituteAll -> replaceVars/substitute `` |
| [`d31710fb`](https://github.com/nix-community/home-manager/commit/d31710fb2cd536b1966fee2af74e99a0816a61a8) | `` fcitx5: fix iniFormat usage (#6899) ``               |
> chore(flake/home-manager): `6d1f834c` -> `abfad3d2`

- flake.lock
| Commit                                                                                                    | Message                        |
| --------------------------------------------------------------------------------------------------------- | ------------------------------ |
| [`c2246ebe`](https://github.com/nix-community/lanzaboote/commit/c2246ebed0462ece7829743240f968d5a12a79cd) | `` Remove rogue dollar sign `` |
> chore(flake/lanzaboote): `e4cf2086` -> `995637eb`

- flake.lock
| Commit                                                                                        | Message                                                                    |
| --------------------------------------------------------------------------------------------- | -------------------------------------------------------------------------- |
| [`1db9218e`](https://github.com/danth/stylix/commit/1db9218e9770c4fc2aaae64222820fabb213be7a) | `` stylix: update all flake inputs ``                                      |
| [`7ddc94f9`](https://github.com/danth/stylix/commit/7ddc94f9dc9b1fc39fb1b2eaf8d773a3132966c9) | `` treewide: add missing `.`s to extensions (#1165) ``                     |
| [`9738ceb9`](https://github.com/danth/stylix/commit/9738ceb9012fee460f3c545d0c1efe7246549912) | …
> chore(flake/stylix): `039e938b` -> `1db9218e`

- flake.lock
| [`04779973`](https://github.com/NixOS/nixos-hardware/commit/047799739c0c04c11075018a23b5ec55e4652b24) | `` lenovo-legion-16arh7h: add integrated GPU only and hybrid configurations `` |
| [`085c9ada`](https://github.com/NixOS/nixos-hardware/commit/085c9ada2dae5b7a67c8d7ab17754362f96ba8dd) | `` intel-comet-lake: use intel-media-driver ``                                 |
| …
> chore(flake/nixos-hardware): `9a049b4a` -> `8bf8a2a0`

- flake.lock
| [`c5140c60`](https://github.com/nix-community/disko/commit/c5140c6079ff690e85eac0b86e254de16a79a4b7) | `` Improve testing documentation `` |
> chore(flake/disko): `1770bf1a` -> `c5140c60`

- flake.lock
| Commit                                                                                                | Message                                                                                         |
| ----------------------------------------------------------------------------------------------------- | ----------------------------------------------------------------------------------------------- |
| [`3fd285f3`](https://github.com/NixOS/nixos-hardware/commit/3fd285f3860727e5af8d8859db914392cfdab5ef) | `` lenovo-thinkpad-x13s: Add support for aarch64 system ``                                      |
| [`306ff6c5`](https://github.com/NixOS/nixos-hardware/commit/306ff6c5f6b5554ef5e99af7cc336518d51538d3) | `` surface: revert longterm kernel to 6.12.19 `` …
> chore(flake/nixos-hardware): `8bf8a2a0` -> `f7bee55a`

- flake.lock
| Commit                                                                                               | Message                                                        |
| ---------------------------------------------------------------------------------------------------- | -------------------------------------------------------------- |
| [`ca27b88c`](https://github.com/nix-community/disko/commit/ca27b88c88948d96feeee9ed814cbd34f53d0d70) | `` Add bcachefs type with encryption and multi-disk support `` |
> chore(flake/disko): `c5140c60` -> `ca27b88c`

- flake.lock
| Commit                                                                                                 | Message                            |
| ------------------------------------------------------------------------------------------------------ | ---------------------------------- |
| [`985d704b`](https://github.com/SenchoPens/base16.nix/commit/985d704b4ff9f75627f279ef091b2899f8456690) | `` mk-theme: make $out the file `` |
> chore(flake/base16): `153d5237` -> `58bfe255`

- flake.lock
| [`32da4fba`](https://github.com/lovesegfault/vim-config/commit/32da4fba45d0c3e710af6d17d9f0bbb6430eba71) | `` chore(flake/nixpkgs): c11863f1 -> 8a2f738d `` |
| [`857e65c0`](https://github.com/lovesegfault/vim-config/commit/857e65c0b391bc912a5143005124eb33297fc5e1) | `` chore(flake/nixvim): 78f6ff03 -> d86fe3df ``  |
> chore(flake/lovesegfault-vim-config): `7ce50320` -> `32da4fba`

- flake.lock
| [`4846adbc`](https://github.com/danth/stylix/commit/4846adbc2a0334687c024aed0ca77ecd93ccdb0d) | `` vesktop: use upstream options (#1150) ``                          |
| [`21774695`](https://github.com/danth/stylix/commit/21774695205278373f67de5540bd08fea376895c) | `` ci: bump DeterminateSystems/nix-installer-action from 16 to 17 `` |
| [`3194470d`](https://github.com/danth/stylix/commit/3194470d07d2885da178a6baca10a91ea1068e1b) | `` gitui: fix two typos …
> chore(flake/stylix): `1db9218e` -> `4846adbc`

- flake.lock
| Commit                                                                                                      | Message                                                                                             |
| ----------------------------------------------------------------------------------------------------------- | --------------------------------------------------------------------------------------------------- |
| [`54207806`](https://github.com/nix-community/home-manager/commit/542078066b1a99cdc5d5fce1365f98b847ca0b5a) | `` wezterm: don't create config if extraConfig is empty, and don't create one by default (#6908) `` |
| [`98f4fef7`](https://github.com/nix-community/home-manager/commit/98f4fef7fd7b4a77245db12e33616023162bc6d9) | `` format: Fix failing due to no cache access …
> chore(flake/home-manager): `abfad3d2` -> `54207806`

- flake.lock
| [`fb6d2a5c`](https://github.com/lovesegfault/vim-config/commit/fb6d2a5c2718441b9034d6866abf45d294ab144a) | `` chore(flake/nixvim): d86fe3df -> b72ba2e4 `` |
> chore(flake/lovesegfault-vim-config): `32da4fba` -> `fb6d2a5c`

- flake.lock
| [`4d2d3223`](https://github.com/nix-community/home-manager/commit/4d2d32231797bfa7213ae5e8ac89d25f8caaae82) | `` thefuck: Add alias option (#6909) `` |
> chore(flake/home-manager): `54207806` -> `4d2d3223`

- flake.lock
| [`2f5819a9`](https://github.com/nix-community/home-manager/commit/2f5819a962489e037a57835f63ed6ff8dbc2d5fb) | `` onedrive: add module (#6907) `` |
> chore(flake/home-manager): `4d2d3223` -> `2f5819a9`

- flake.lock
| [`afcf1e0d`](https://github.com/lovesegfault/vim-config/commit/afcf1e0d6795cb570be0a45009fa2fc93d1c057b) | `` chore(flake/nixvim): b72ba2e4 -> 8d8a8568 `` |
> chore(flake/lovesegfault-vim-config): `fb6d2a5c` -> `afcf1e0d`

- flake.lock
| [`50bb714a`](https://github.com/nix-community/home-manager/commit/50bb714a8259b0c29b6c3429099a3b837771dab4) | `` rmpc: add module (#6910) ``   |
| [`ef47f364`](https://github.com/nix-community/home-manager/commit/ef47f36450b36d437f5c2f6953022648d76c0638) | `` flake.lock: Update (#6912) `` |
> chore(flake/home-manager): `2f5819a9` -> `50bb714a`

- flake.lock
| [`7b2aae3f`](https://github.com/nix-community/home-manager/commit/7b2aae3fb39928aecc5e41c10a9c87c4881614d5) | `` eza: add tests ``                                      |
| [`edaeeda2`](https://github.com/nix-community/home-manager/commit/edaeeda26429aa3d25b9119f358075813bd9d4ba) | `` eza: default disable nushell integration again ``      |
| [`2a264c17`](https://github.com/nix-community/home-manager/commit/2a264c17d5fb3673eeec891ea4a82027a41addc3) | …
> chore(flake/home-manager): `50bb714a` -> `7b2aae3f`

- flake.lock
| [`cb5e5aec`](https://github.com/lovesegfault/vim-config/commit/cb5e5aecc4ea2bd43ece434b8411751ae1a4c18f) | `` chore(flake/treefmt-nix): 8d404a69 -> b2b6c027 `` |
| [`87ee866e`](https://github.com/lovesegfault/vim-config/commit/87ee866e2b4693e3e5c8918d5b022421b42f5893) | `` chore(flake/nixvim): 8d8a8568 -> 89c94d9e ``      |
| [`9c73aa00`](https://github.com/lovesegfault/vim-config/commit/9c73aa00361f6380530939f7e7a063b0d6e4b541) | `` chore(flake/nixpkgs): 8a2f738d …
> chore(flake/lovesegfault-vim-config): `afcf1e0d` -> `cb5e5aec`

- flake.lock
| [`be7cf170`](https://github.com/nix-community/home-manager/commit/be7cf1709b469a2a2c62169172a167d1fed3509f) | `` lsd: add package option ``                                     |
| [`77f849c1`](https://github.com/nix-community/home-manager/commit/77f849c11458ee00dcf722ca267edefd3f51743e) | `` lsd: refactor module ``                                        |
| [`cf351071`](https://github.com/nix-community/home-manager/commit/cf351071fb4a …
> chore(flake/home-manager): `7b2aae3f` -> `be7cf170`

- flake.lock
| [`c54a8ab0`](https://github.com/nix-community/home-manager/commit/c54a8ab0d2ea7486eadb14f1dc498817ff164f59) | `` rofi: remove thiagokokada from maintainers (#6928) `` |
| [`6f974faa`](https://github.com/nix-community/home-manager/commit/6f974faa1962e2ee081635124ab96a1bfacb2f25) | `` gh: add `hosts` option (#6925) ``                     |
| [`69c60b03`](https://github.com/nix-community/home-manager/commit/69c60b035e6bb51a4c5607f184bf64312c294139) | `` …
> chore(flake/home-manager): `be7cf170` -> `c54a8ab0`

- flake.lock
| [`d0d9d0a1`](https://github.com/nix-community/home-manager/commit/d0d9d0a1454d5a0200693570618084d80a8b336c) | `` mpvpaper: add module (#6926) `` |
> chore(flake/home-manager): `c54a8ab0` -> `d0d9d0a1`

- flake.lock
| [`e968a070`](https://github.com/lovesegfault/vim-config/commit/e968a070b53ea106bcdaeaf83e8c4602031f3467) | `` chore(flake/nixvim): 89c94d9e -> 7a6c5b48 ``      |
| [`b9f280f4`](https://github.com/lovesegfault/vim-config/commit/b9f280f403b9a3154bcb15741f4b8bcf4d46fb18) | `` chore(flake/treefmt-nix): b2b6c027 -> 763f1ce0 `` |
> chore(flake/lovesegfault-vim-config): `cb5e5aec` -> `e968a070`

- flake.lock
| [`e135fccf`](https://github.com/lovesegfault/vim-config/commit/e135fccfb91a8267252cc38f48faa93c635a2151) | `` chore(flake/nixpkgs): f771eb40 -> 46e634be ``     |
| [`fc1c0d79`](https://github.com/lovesegfault/vim-config/commit/fc1c0d79403733ec6665eb484fa2f177efcb15fe) | `` chore(flake/nixvim): 7a6c5b48 -> cd3cbb1e ``      |
| [`ec239065`](https://github.com/lovesegfault/vim-config/commit/ec2390656a6024168337ddf6a04976e6a137df69) | `` chore(flake/treefmt-nix): …
> chore(flake/lovesegfault-vim-config): `e968a070` -> `e135fccf`

- flake.lock
| [`84d26211`](https://github.com/nix-community/home-manager/commit/84d262115e10ad321ef01cd85903d0f5c3ec113f) | `` nixos,darwin: add osClass (_class) as a specialArg (#6906) ``               |
| [`9389f373`](https://github.com/nix-community/home-manager/commit/9389f373bee64cc8459253e0ab00635b05c0bcb6) | `` pls: enableAliases -> enableShellIntegration (#6932) ``                     |
| …
> chore(flake/home-manager): `1ad12323` -> `84d26211`

- flake.lock
| [`98e9999d`](https://github.com/lovesegfault/vim-config/commit/98e9999d50098ac07a64977e36bc88180a290510) | `` chore(flake/nixvim): cd3cbb1e -> f2e96b67 `` |
> chore(flake/lovesegfault-vim-config): `e135fccf` -> `98e9999d`

- flake.lock
| Commit                                                                                        | Message                                                                     |
| --------------------------------------------------------------------------------------------- | --------------------------------------------------------------------------- |
| [`b4d3137c`](https://github.com/danth/stylix/commit/b4d3137c5ce960073a991bd99a333cad1b233101) | `` ci: use format for flake update title (#1197) ``                         |
| [`7476be8b`](https://github.com/danth/stylix/commit/7476be8b0bfdd4f6135e8a72678b2b9487069fe3) | `` ci: fix stable pr title for update flake (#1196) ``                      |
| [`51cc5640`](https://github.com/danth/stylix/commit/51cc5640d9532874274f754c64c2ef32ada1a703) …
> chore(flake/stylix): `4846adbc` -> `b4d3137c`

- flake.lock
| [`015f1913`](https://github.com/nix-community/home-manager/commit/015f1913109d44c36e683b55f0e47e283b383caa) | `` ci: remove GitLab rycee/nur-expression update ``           |
| [`4e7ee4d0`](https://github.com/nix-community/home-manager/commit/4e7ee4d02cc323fc338ff978ca4a2b72e08f5d8d) | `` home-manager: new formatting of generated configuration `` |
| [`81431b6d`](https://github.com/nix-community/home-manager/commit/81431b6d6fa756db641109461fc9 …
> chore(flake/home-manager): `84d26211` -> `015f1913`

- flake.lock
| [`ab0b2e7c`](https://github.com/lovesegfault/vim-config/commit/ab0b2e7caf9d1749266c022aa9ec52c7218d7e3d) | `` chore(flake/nixvim): f2e96b67 -> 0ec7ea3d `` |
> chore(flake/lovesegfault-vim-config): `98e9999d` -> `ab0b2e7c`

- flake.lock
| [`f045bd46`](https://github.com/nix-community/home-manager/commit/f045bd46b73c3b0ed4e46cdb6036b3d5823d7dee) | `` fish: keep all fish-completions packages around `` |
| [`361ab448`](https://github.com/nix-community/home-manager/commit/361ab4484e7b91a7b6bdedc6784e2a44d20a3dce) | `` home-environment: add `home.extraDependencies` ``  |
| [`1298a341`](https://github.com/nix-community/home-manager/commit/1298a3418be1a875e9ae6643770b0939814cd441) | `` ci: remove …
> chore(flake/home-manager): `015f1913` -> `f045bd46`

- flake.lock
| Commit                                                                                                      | Message                                                                              |
| ----------------------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------ |
| [`355a6b93`](https://github.com/nix-community/home-manager/commit/355a6b937d07a95cb0b753ef513bcaad09128dea) | `` nushell: throw instead of abort (#6870) ``                                        |
| [`2eabb26d`](https://github.com/nix-community/home-manager/commit/2eabb26d0859c7710a2aa76c3b0ff4149f41b04a) | `` restic: allow the convenience script to source environmentFile (#6947) ``         |
| …
> chore(flake/home-manager): `f045bd46` -> `355a6b93`

- flake.lock
| [`1e8c62c6`](https://github.com/nix-community/home-manager/commit/1e8c62c651242fc685b10efc4a48ab777635fb7f) | `` gpg-agent: avoid console output when using ssh `` |
| [`d6b0c054`](https://github.com/nix-community/home-manager/commit/d6b0c054571a444acd2755b038bb7df5eb7954a7) | `` visidata: add module (#6956) ``                   |
> chore(flake/home-manager): `355a6b93` -> `1e8c62c6`

- flake.lock
| [`a30c3bfb`](https://github.com/lovesegfault/vim-config/commit/a30c3bfba3fb601d5e66db8c3e6d342d6f613dc8) | `` chore(flake/nixvim): 0ec7ea3d -> 4b276785 ``      |
| [`cfb30532`](https://github.com/lovesegfault/vim-config/commit/cfb30532bb6692175221ffbb887f244e1b29d26f) | `` chore(flake/treefmt-nix): 82bf32e5 -> 29ec5026 `` |
> chore(flake/lovesegfault-vim-config): `ab0b2e7c` -> `a30c3bfb`

- flake.lock
| [`c0962eee`](https://github.com/nix-community/home-manager/commit/c0962eeeabfb8127713f859ec8a5f0e86dead0f2) | `` thunderbird: fix accounts being removed (#6959) `` |
| [`123297c5`](https://github.com/nix-community/home-manager/commit/123297c57e77c692fae7e860e701823367afbec4) | `` onagre: add module (#6958) ``                      |
> chore(flake/home-manager): `1e8c62c6` -> `c0962eee`

- flake.lock
| [`c1aa4902`](https://github.com/lovesegfault/vim-config/commit/c1aa4902a36c4a5ef5200cba70a5799e0fa8be5c) | `` chore(flake/nixpkgs): f02fddb8 -> 7a2622e2 `` |
| [`0b0f9d88`](https://github.com/lovesegfault/vim-config/commit/0b0f9d8896141239e47f22eab63e65f5af425e2b) | `` chore(flake/nixvim): 4b276785 -> c9781223 ``  |
| [`e7737ee6`](https://github.com/lovesegfault/vim-config/commit/e7737ee6642c1a43708d04aa23e0b5881238c440) | `` chore(flake/nixpkgs): 46e634be -> f02fddb8 `` |
> chore(flake/lovesegfault-vim-config): `a30c3bfb` -> `c1aa4902`

- flake.lock
| Commit                                                                                                            | Message                                                                      |
| ----------------------------------------------------------------------------------------------------------------- | ---------------------------------------------------------------------------- |
| [`137fd2bd`](https://github.com/nix-community/nix-index-database/commit/137fd2bd726fff343874f85601b51769b48685cc) | `` update generated.nix to release 2025-05-04-033656 ``                      |
| [`1a67f9bd`](https://github.com/nix-community/nix-index-database/commit/1a67f9bd3d2de450cbc81ffea8de0fe4a59bf189) | `` flake.lock: Update ``                                                     |
| …
> chore(flake/nix-index-database): `18752471` -> `137fd2bd`

- flake.lock
| [`d0c543d7`](https://github.com/nix-community/disko/commit/d0c543d740fad42fe2c035b43c9d41127e073c78) | `` [fix] added missing single quote in script `` |
> chore(flake/disko): `ca27b88c` -> `d0c543d7`

- flake.lock
| Commit                                                                                                 | Message                                        |
| ------------------------------------------------------------------------------------------------------ | ---------------------------------------------- |
| [`a6d73d09`](https://github.com/nix-darwin/nix-darwin/commit/a6d73d09045384a325eabe8827edd95ee3969a58) | `` nix-tools: use replaceVarsWith ``           |
| [`9603417d`](https://github.com/nix-darwin/nix-darwin/commit/9603417da1560d5d2286b1f7b810075f0f6b3067) | `` networking: allow users to override FQDN `` |
> chore(flake/darwin): `43975d78` -> `760a11c8`

- flake.lock
| Commit                                                                                         | Message                                             |
| ---------------------------------------------------------------------------------------------- | --------------------------------------------------- |
| [`58c55446`](https://github.com/ryantm/agenix/commit/58c554469cf7bbb27b02f7378c6058ea0ffa59b3) | `` fix: use replaceVars instead of substituteAll `` |
> chore(flake/agenix): `e600439e` -> `96e078c6`

- flake.lock
| [`29ec5026`](https://github.com/numtide/treefmt-nix/commit/29ec5026372e0dec56f890e50dbe4f45930320fd) | `` fix defaultText for `pkgs` option using `literalMD` (#350) `` |
| [`82bf32e5`](https://github.com/numtide/treefmt-nix/commit/82bf32e541b30080d94e46af13d46da0708609ea) | `` taplo: add option to pass settings (#348) ``                  |
| [`763f1ce0`](https://github.com/numtide/treefmt-nix/commit/763f1ce0dd12fe44ce6a5c6ea3f159d438571874) | `` …
> chore(flake/treefmt-nix): `8d404a69` -> `29ec5026`

- flake.lock
| [`3784e96d`](https://github.com/lovesegfault/vim-config/commit/3784e96dd746b3ec9b558a984be21167cd0b4358) | `` chore(flake/nixpkgs): 7a2622e2 -> 979daf34 `` |
| [`7c986a0a`](https://github.com/lovesegfault/vim-config/commit/7c986a0a75824fc1138e6eac131cd73a4eb3dca1) | `` chore(flake/nixvim): c9781223 -> 7d18194a ``  |
> chore(flake/lovesegfault-vim-config): `c1aa4902` -> `3784e96d`

- flake.lock
| Commit                                                                                               | Message                                                                |
| ---------------------------------------------------------------------------------------------------- | ---------------------------------------------------------------------- |
| [`7b636423`](https://github.com/nix-community/disko/commit/7b636423586635985f91bd2f0f0cb0511c340627) | `` Make bcachefs subvolumes boot-time mount tests pass + more tests `` |
> chore(flake/disko): `d0c543d7` -> `7b636423`

- flake.lock
| [`e9476294`](https://github.com/Mic92/nix-fast-build/commit/e947629455fa6f36701f5c39669d0e5a634324dd) | `` chore(deps): update nixpkgs digest to 0ab7cd9 (#137) `` |
> chore(flake/nix-fast-build): `22c2ade4` -> `e9476294`

- flake.lock
| [`b5d1320e`](https://github.com/nix-community/disko/commit/b5d1320ebc2f34dbea4655f95167f55e2130cdb3) | `` flake.lock: Update `` |
> chore(flake/disko): `7b636423` -> `b5d1320e`

- flake.lock
| [`a4bb30a9`](https://github.com/NixOS/nixos-hardware/commit/a4bb30a9000cf0444ecc8fdca8096d072f77f9e8) | `` add asus-zenbook-ux481 ``        |
| [`f5eedd65`](https://github.com/NixOS/nixos-hardware/commit/f5eedd65a342e155585e6d7a4ca7a4bbefecceee) | `` Lenovo ThinkPad X1 Yoga Gen 8 `` |
> chore(flake/nixos-hardware): `0833dc8b` -> `a4bb30a9`

- flake.lock
| [`3f859bb9`](https://github.com/Mic92/nix-fast-build/commit/3f859bb966fe65ac15412aaf39387d5e4d10e41b) | `` chore(deps): update nixpkgs digest to 8cf2a06 (#138) `` |
> chore(flake/nix-fast-build): `e9476294` -> `3f859bb9`

- flake.lock
- hosts/hilbert/default.nix
- hosts/popper/default.nix
- users/bemeurer/graphical/sway/mako.nix
| [`8a318641`](https://github.com/nix-community/home-manager/commit/8a318641ac13d3bc0a53651feaee9560f9b2d89a) | `` sway-easyfocus: add module (#6976) ``                                   |
| [`5f1f4725`](https://github.com/nix-community/home-manager/commit/5f1f472565ee59b5001ae5022bbb1a9a64239f91) | `` mako: use ini atom type (#6977) ``                                      |
| …
> chore(flake/home-manager): `c0962eee` -> `8a318641`

- flake.lock
| Commit                                                                                               | Message                                                                  |
| ---------------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------ |
| [`85555d27`](https://github.com/nix-community/disko/commit/85555d27ded84604ad6657ecca255a03fd878607) | `` remove broken flakestry github action ``                              |
| [`6ca7c94d`](https://github.com/nix-community/disko/commit/6ca7c94d6a50eae797ba8f73773d5b37b1bbb1ca) | `` create-release: indent version.nix according to nixfmt ``             |
| [`14afb101`](https://github.com/nix-community/disko/commit/14afb10129f010809fa …
> chore(flake/disko): `b5d1320e` -> `85555d27`

- flake.lock
| Commit                                                                                                      | Message                                                                             |
| ----------------------------------------------------------------------------------------------------------- | ----------------------------------------------------------------------------------- |
| [`a5159823`](https://github.com/nix-community/home-manager/commit/a51598236f23c89e59ee77eb8e0614358b0e896c) | `` lutris: add module (#6964) ``                                                    |
| [`3c59c513`](https://github.com/nix-community/home-manager/commit/3c59c5132b64e885faca381e713b579dcbddba75) | `` wayprompt: init module (#7002) ``                                                |
| …
> chore(flake/home-manager): `8a318641` -> `a5159823`

- flake.lock
| [`38eecfc4`](https://github.com/Mic92/nix-fast-build/commit/38eecfc45d91aa1e00a740ab39bbd9d33ba5835a) | `` chore(deps): update nixpkgs digest to 1676224 (#144) `` |
| [`88139228`](https://github.com/Mic92/nix-fast-build/commit/8813922864147f81f1b0d3644f8df6cf24d0d651) | `` chore(deps): update nixpkgs digest to c254c79 (#143) `` |
| [`011c7684`](https://github.com/Mic92/nix-fast-build/commit/011c7684932e9fc89b4251039ec2ed31ab57e518) | `` chore(deps): update …
> chore(flake/nix-fast-build): `3f859bb9` -> `38eecfc4`

- flake.lock
| [`1a5b789c`](https://github.com/nix-community/lanzaboote/commit/1a5b789ce4816e6e98cf706c681c7926b0724e40) | `` rust: placate clippy more ``                   |
| [`e634dc26`](https://github.com/nix-community/lanzaboote/commit/e634dc26d795073049798ec3d24f162a4294848b) | `` uefi: placate clippy ``                        |
| [`04176ea2`](https://github.com/nix-community/lanzaboote/commit/04176ea207059a50d6e7b582dbc91ce4ceff9610) | `` uefi: bump rust toolchain from 1.78 to …
> chore(flake/lanzaboote): `995637eb` -> `fa81496a`

- flake.lock
| [`aaa8e548`](https://github.com/NixOS/nixos-hardware/commit/aaa8e548c34cd261deb760f1641957d6926c7913) | `` E14-intel: add gen4 configuration ``                          |
| [`9b383cd3`](https://github.com/NixOS/nixos-hardware/commit/9b383cd3f4364ee37728978c8daa33e4f4b2f5f1) | `` Adding gen6 support for lenovo thinkpad e14 (#1470) ``        |
| [`7d9552ef`](https://github.com/NixOS/nixos-hardware/commit/7d9552ef6b02da7b8fafe426c0db5358ab8c4009) | …
> chore(flake/nixos-hardware): `a4bb30a9` -> `2ea3ad8a`

- flake.lock
| [`621f139b`](https://github.com/lovesegfault/vim-config/commit/621f139bfb9c8920fc2765a5cc7530261c8f1ecf) | `` chore(flake/nixvim): c26f5c2e -> 6597afe2 ``    |
| [`7280ac1b`](https://github.com/lovesegfault/vim-config/commit/7280ac1b65e03baad179109394dca662fd9933ea) | `` chore(flake/nixpkgs): 979daf34 -> 3730d8a3 ``   |
| [`e52c7e09`](https://github.com/lovesegfault/vim-config/commit/e52c7e092e02d9df7ead139e0d1d9d6ae9baee78) | `` chore(flake/git-hooks): dcf50727 -> …
> chore(flake/lovesegfault-vim-config): `3784e96d` -> `621f139b`

- flake.lock
| [`97af644c`](https://github.com/Mic92/nix-fast-build/commit/97af644c6941b8013fddddd719429beb8aac7c5e) | `` chore(deps): update nixpkgs digest to 2cd2dec (#145) `` |
> chore(flake/nix-fast-build): `38eecfc4` -> `97af644c`

- flake.lock
| [`a76ebd26`](https://github.com/lovesegfault/vim-config/commit/a76ebd26fdb621ebebc21c6d3719b8a3b7a636ca) | `` chore(flake/nixpkgs): 3730d8a3 -> 8fcc7145 `` |
| [`b75709f1`](https://github.com/lovesegfault/vim-config/commit/b75709f1c5f664288e3962ffe45e2a971b77e21d) | `` chore(flake/nixvim): 6597afe2 -> aa1ae69b ``  |
> chore(flake/lovesegfault-vim-config): `621f139b` -> `a76ebd26`

- flake.lock
| [`205cb960`](https://github.com/NixOS/nixpkgs/commit/205cb9602bee6697edf6402c1555b323a846613e) | `` odin: dev-2025-01 -> dev-2025-04 ``                                            |
| [`7cd4f789`](https://github.com/NixOS/nixpkgs/commit/7cd4f7897f44edb5686ab0820bf5cf8b666df360) | `` python312Packages.wandb: skip failing test on darwin ``                        |
| [`a386622c`](https://github.com/NixOS/nixpkgs/commit/a386622c94990 …
> chore(flake/nixpkgs): `979daf34` -> `dda3dcd3`

- flake.lock
| [`30b0e648`](https://github.com/Mic92/nix-fast-build/commit/30b0e64851dbb8e0d94ea1a93080a613dac8630b) | `` chore(deps): update nixpkgs digest to d06b53b (#146) `` |
> chore(flake/nix-fast-build): `97af644c` -> `30b0e648`

- flake.lock
| Commit                                                                                        | Message                                                                                |
| --------------------------------------------------------------------------------------------- | -------------------------------------------------------------------------------------- |
| [`b06c1cb6`](https://github.com/danth/stylix/commit/b06c1cb60ab83885fe62359257d9d982deea45ad) | `` stylix: simplify font options & use `literalExpression` default packages (#1225) `` |
> chore(flake/stylix): `685deb9b` -> `b06c1cb6`

- flake.lock
| Commit                                                                                        | Message                            |
| --------------------------------------------------------------------------------------------- | ---------------------------------- |
| [`8775d832`](https://github.com/danth/stylix/commit/8775d8322ad033c5f72d737aef3be146cbbe74a5) | `` fnott: set font size (#1243) `` |
> chore(flake/stylix): `b06c1cb6` -> `8775d832`

- flake.lock
| Commit                                                                                                      | Message                                                                           |
| ----------------------------------------------------------------------------------------------------------- | --------------------------------------------------------------------------------- |
| [`e95a7c5b`](https://github.com/nix-community/home-manager/commit/e95a7c5b6fa93304cd2fd78cf676c4f6d23c422c) | `` Revert "direnv: update nushell env conversion logic (#6999)" (#7014) ``        |
| [`b706037a`](https://github.com/nix-community/home-manager/commit/b706037a60acc727f1b5c037e84dc61a35ef1db1) | `` distrobox: make systemd unit optional (#7007) ``                               |
| …
> chore(flake/home-manager): `a5159823` -> `e95a7c5b`

- flake.lock
| Commit                                                                                        | Message                          |
| --------------------------------------------------------------------------------------------- | -------------------------------- |
| [`6690180c`](https://github.com/danth/stylix/commit/6690180c17153026c854584e8b7cb9df599127fe) | `` yazi: tweak colors (#1233) `` |
> chore(flake/stylix): `8775d832` -> `6690180c`

- flake.lock
| [`08d2d49e`](https://github.com/nix-community/lanzaboote/commit/08d2d49e940ed8197380ef5a4c375d53de2ecd35) | `` mark boot.lanzaboote.enrollKeys for testing `` |
> chore(flake/lanzaboote): `fa81496a` -> `8f27abb5`

- flake.lock
| [`3c5e1267`](https://github.com/NixOS/nixos-hardware/commit/3c5e12673265dfb0de3d9121420c0c2153bf21e0) | `` Add kvm-intel kernel module for XPS13 ``     |
| [`c4013507`](https://github.com/NixOS/nixos-hardware/commit/c40135076deb53668394a023c0220303c0126007) | `` Ensure WiFi works out-of-the-box on XPS13 `` |
> chore(flake/nixos-hardware): `2ea3ad8a` -> `3c5e1267`

- flake.lock
| [`1e462e81`](https://github.com/Mic92/nix-fast-build/commit/1e462e81133f0d9137079f89845485ada5b15f3e) | `` chore(deps): update nixpkgs digest to 0f1c18b (#147) `` |
> chore(flake/nix-fast-build): `30b0e648` -> `1e462e81`

- flake.lock
| [`e0a52f91`](https://github.com/lovesegfault/vim-config/commit/e0a52f91c28fce3c1ab7644dd41c92fe7ea09777) | `` chore(flake/nixpkgs): 8fcc7145 -> dda3dcd3 `` |
| [`794d202e`](https://github.com/lovesegfault/vim-config/commit/794d202e801c785303bc9a74f8ee9b50bdf662f1) | `` chore(flake/nixvim): aa1ae69b -> 1b1e43a3 ``  |
> chore(flake/lovesegfault-vim-config): `a76ebd26` -> `e0a52f91`

- flake.lock
| [`1c71f3bd`](https://github.com/danth/stylix/commit/1c71f3bde228f7b17c1aad75f2b97276daf8db42) | `` treewide: use lib.getExe (#1241) `` |
> chore(flake/stylix): `6690180c` -> `1c71f3bd`

- flake.lock
| [`12e67385`](https://github.com/nix-community/home-manager/commit/12e67385964d9c9304daa81d0ad5ba3b01fdd35e) | `` docs: remove recommendation to wait for maintainers for news `` |
| [`6fd639db`](https://github.com/nix-community/home-manager/commit/6fd639dbe5183850b6c4a7fb47ae04c4808cb891) | `` docs: update news.md to highlight create-news-entry command ``  |
| [`c4bd004d`](https://github.com/nix-community/home-manager/commit/c4bd004d …
> chore(flake/home-manager): `e95a7c5b` -> `12e67385`

- flake.lock
| [`a803b722`](https://github.com/Mic92/nix-fast-build/commit/a803b722190a857768b06b4a804aee53c26ee49b) | `` chore(deps): update nixpkgs digest to 5f833dd (#148) `` |
> chore(flake/nix-fast-build): `1e462e81` -> `a803b722`

- flake.lock
| Commit                                                                                        | Message                             |
| --------------------------------------------------------------------------------------------- | ----------------------------------- |
| [`df51c62e`](https://github.com/danth/stylix/commit/df51c62e43a841c01806d3db62dde7bf833879c5) | `` starship: fix testbed (#1248) `` |
> chore(flake/stylix): `1c71f3bd` -> `df51c62e`

- flake.lock
| [`c0e71d42`](https://github.com/lovesegfault/vim-config/commit/c0e71d422885e1ac583ddc2801b68240d07a9255) | `` chore(flake/nixvim): 1b1e43a3 -> e527939f `` |
> chore(flake/lovesegfault-vim-config): `e0a52f91` -> `c0e71d42`

- flake.lock
| [`9ef92f1c`](https://github.com/nix-community/home-manager/commit/9ef92f1c6b77944198fd368ec805ced842352a1d) | `` waveterm: fix markdown in description ``                |
| [`13289f06`](https://github.com/nix-community/home-manager/commit/13289f06429700f3ecf8f5109ed8831839f09145) | `` services.autorandr: improve systemd unit description `` |
| [`1875b5a1`](https://github.com/nix-community/home-manager/commit/1875b5a1606a897d9285d80600c7ab566911c7bc …
> chore(flake/home-manager): `12e67385` -> `9ef92f1c`

- flake.lock
| [`de496c9c`](https://github.com/nix-community/home-manager/commit/de496c9ccb705ed76c1f23c2cad13e8970c37f0b) | `` television: add support for channels (#7026) `` |
> chore(flake/home-manager): `9ef92f1c` -> `de496c9c`

- flake.lock
| [`c9c3cd5e`](https://github.com/Mic92/nix-fast-build/commit/c9c3cd5e340b53a6e4489297e4430ea5e1496e0b) | `` chore(deps): update nixpkgs digest to 7fb53a7 (#149) `` |
> chore(flake/nix-fast-build): `a803b722` -> `c9c3cd5e`

- flake.lock
| [`966db02d`](https://github.com/numtide/treefmt-nix/commit/966db02dee09fea0b1c81e035d0f632882b46aaf) | `` just: format justfile in subdirectories `` |
> chore(flake/treefmt-nix): `29ec5026` -> `48193321`

- flake.lock
| [`285f2b83`](https://github.com/Mic92/nix-fast-build/commit/285f2b83cceb85b163f185bf36394f3baef3f44e) | `` chore(deps): update treefmt-nix digest to 4819332 (#150) `` |
> chore(flake/nix-fast-build): `c9c3cd5e` -> `285f2b83`

- flake.lock
| [`6991569c`](https://github.com/nix-community/home-manager/commit/6991569cb7cdde9891f52b43abe9916779df45b0) | `` flake.lock: Update `` |
> chore(flake/home-manager): `de496c9c` -> `6991569c`

- flake.lock
| [`9d0b6546`](https://github.com/numtide/treefmt-nix/commit/9d0b6546c04f3b3addc6161470eaae7a7a700583) | `` feat(biome): add css support `` |
> chore(flake/treefmt-nix): `48193321` -> `708ec80c`

- flake.lock
| [`2b94af42`](https://github.com/Mic92/nix-fast-build/commit/2b94af42cb355865c8bfc4b7068681a4dbb171ef) | `` chore(deps): update treefmt-nix digest to 708ec80 (#151) `` |
> chore(flake/nix-fast-build): `285f2b83` -> `2b94af42`

- flake.lock
| [`ff915842`](https://github.com/nix-community/home-manager/commit/ff915842e4a2e63c4c8c5c08c6870b9d5b3c3ee9) | `` Translate using Weblate (Catalan) `` |
> chore(flake/home-manager): `6991569c` -> `ff915842`

- flake.lock
| [`5983fe6d`](https://github.com/lovesegfault/vim-config/commit/5983fe6d4e74618fd5f6713cfbfcc18144d0e72d) | `` chore(flake/nixpkgs): dda3dcd3 -> d89fc19e ``     |
| [`546c12db`](https://github.com/lovesegfault/vim-config/commit/546c12dbf07a17d32a5af4bcafebad1639059aa4) | `` chore(flake/nixvim): e527939f -> 02a85bd2 ``      |
| [`9f4da609`](https://github.com/lovesegfault/vim-config/commit/9f4da609953a33183a2de60df7f530f3787cedec) | `` chore(flake/treefmt-nix): …
> chore(flake/lovesegfault-vim-config): `c0e71d42` -> `5983fe6d`

- flake.lock
| [`7a3f3e55`](https://github.com/nix-community/home-manager/commit/7a3f3e550737c3ed43f6abf33a560cb58537d21f) | `` misc: fix mozilla native messaging hosts `` |
| [`a48fecda`](https://github.com/nix-community/home-manager/commit/a48fecda099e9324134f6dd88fe7e38f58d2d9d2) | `` files: add home.file.<name>.ignorelinks ``  |
| [`910292fe`](https://github.com/nix-community/home-manager/commit/910292fe342071f83d6906c7ca24864eba28676a) | `` halloy: add module (#7034) `` …
> chore(flake/home-manager): `ff915842` -> `7a3f3e55`

- flake.lock
| [`fb061f55`](https://github.com/nix-community/home-manager/commit/fb061f555f821fe4fb49f8f6f2a0cc3d5728bd52) | `` misc: add news entries for March modules ``                 |
| [`0083d901`](https://github.com/nix-community/home-manager/commit/0083d901a33696bf8d29966775bc420e302fb7ea) | `` misc: add news entries for April modules ``                 |
| [`4a7311c2`](https://github.com/nix-community/home-manager/commit/4a7311c2353a1ae1292500e2 …
> chore(flake/home-manager): `7a3f3e55` -> `fb061f55`

- flake.lock
| [`6f12fbf0`](https://github.com/Mic92/nix-fast-build/commit/6f12fbf083586fce01b8bfdc9df747eb3672b43f) | `` chore(deps): update nixpkgs digest to e4f52f3 (#152) `` |
> chore(flake/nix-fast-build): `2b94af42` -> `6f12fbf0`

- flake.lock
| [`e4eb7b41`](https://github.com/nix-community/lanzaboote/commit/e4eb7b41973e403eac626909582a68ba1e3fc1d0) | `` chore(deps): lock file maintenance `` |
> chore(flake/lanzaboote): `8f27abb5` -> `2e425f3d`

- flake.lock
| [`0c0df649`](https://github.com/danth/stylix/commit/0c0df649f7dcbc597fa1d47e8f9a5c2cedab6145) | `` wayprompt: add myself as maintainer ``                               |
| [`787a156f`](https://github.com/danth/stylix/commit/787a156f461b09388150dd2b82f977914968c05a) | `` wayprompt: capitalize name ``                                        |
| [`e020f1e8`](https://github.com/danth/stylix/commit/e020f1e8159cc8999eb3c0b81c8f0711394d2dc2) | `` wayprompt: …
> chore(flake/stylix): `df51c62e` -> `0c0df649`

- flake.lock
| Commit                                                                                        | Message                                  |
| --------------------------------------------------------------------------------------------- | ---------------------------------------- |
| [`f07a4d0b`](https://github.com/danth/stylix/commit/f07a4d0b85f60d5b5d6c4134afd322368a74b7f9) | `` zellij: use upstream themes option `` |
> chore(flake/stylix): `0c0df649` -> `f07a4d0b`

- flake.lock
| [`16023fe3`](https://github.com/NixOS/nixos-hardware/commit/16023fe3d4d48a79deaa3ebd9385716ef038a211) | `` lenovo/yoga/7/14ILL10: init `` |
| [`0d3ca753`](https://github.com/NixOS/nixos-hardware/commit/0d3ca7531030e2a405e6e7f885cc07681cac6aba) | `` add asus-rog-strix-g533zw ``   |
> chore(flake/nixos-hardware): `3c5e1267` -> `d1d68fe8`

- flake.lock
| Commit                                                                                                   | Message                                               |
| -------------------------------------------------------------------------------------------------------- | ----------------------------------------------------- |
| [`d9780df9`](https://github.com/lovesegfault/vim-config/commit/d9780df988974aff919de64d9780694033a089d4) | `` chore(flake/nixvim): 02a85bd2 -> ff0ccdf5 ``       |
| [`ca0192b9`](https://github.com/lovesegfault/vim-config/commit/ca0192b98349fb8c6a36d0d45d493cc5e867e77e) | `` chore(flake/flake-compat): ff81ac96 -> 9100a0f4 `` |
> chore(flake/lovesegfault-vim-config): `5983fe6d` -> `d9780df9`

- flake.lock
| [`f0a7db5e`](https://github.com/nix-community/home-manager/commit/f0a7db5ec1d369721e770a45e4d19f8e48186a69) | `` direnv: update nushell env conversion logic (#7015) `` |
| [`0b24658e`](https://github.com/nix-community/home-manager/commit/0b24658ec09908e5a6515cacc54f29d589c8423b) | `` halloy: add themes option (#7043) ``                   |
| [`58795314`](https://github.com/nix-community/home-manager/commit/587953146298b13e897b827181967ff2298fb63c) | …
> chore(flake/home-manager): `fb061f55` -> `f0a7db5e`

- flake.lock
| Commit                                                                                                 | Message                                             |
| ------------------------------------------------------------------------------------------------------ | --------------------------------------------------- |
| [`84644435`](https://github.com/nix-darwin/nix-darwin/commit/846444354b4ce9ea20db88c89a38fb7da7ecb087) | `` services/buildkite-agents: support multi-tags `` |
> chore(flake/darwin): `6cb36e83` -> `d642c985`

- flake.lock
| [`b63f6640`](https://github.com/danth/stylix/commit/b63f66408631fcc04d74e2ad61cab1b1cfd7d587) | `` kde: add and update testbeds (#1252) `` |
> chore(flake/stylix): `f07a4d0b` -> `b63f6640`

- flake.lock
| [`535a541b`](https://github.com/nix-community/home-manager/commit/535a541b429c1e89f0955c160df1d6d2bfeaf802) | `` halloy: fix themes example (#7046) ``                        |
| [`012cc9e1`](https://github.com/nix-community/home-manager/commit/012cc9e1666b8ce0d6f677b902651f6858dfbe45) | `` halloy: add note about server being required (#7047) ``      |
| [`665c49e0`](https://github.com/nix-community/home-manager/commit/665c49e0c2982d94f30a …
> chore(flake/home-manager): `f0a7db5e` -> `535a541b`

- flake.lock
| [`a132dbcf`](https://github.com/Mic92/nix-fast-build/commit/a132dbcf4d172216df12e971308a7e78b29f71f7) | `` chore(deps): update nixpkgs digest to fab95ba (#153) `` |
> chore(flake/nix-fast-build): `6f12fbf0` -> `a132dbcf`

- flake.lock
| [`ff949f78`](https://github.com/NixOS/nixos-hardware/commit/ff949f78d6b04a5294ff059cf7cdce9638ea8a86) | `` ideacentr-k330: include nvidia-fermi architecture ``     |
| [`5aa1b0f0`](https://github.com/NixOS/nixos-hardware/commit/5aa1b0f04942d01cb51b4e865d2ca161ce14a818) | `` dell-xps-15-9530-nvidia: include ada-lovelace profile `` |
| [`91dc75a8`](https://github.com/NixOS/nixos-hardware/commit/91dc75a805501815969342ad1672e9b553d1f95b) | `` fix …
> chore(flake/nixos-hardware): `d1d68fe8` -> `e81fd167`

- flake.lock
| [`df556f2a`](https://github.com/nix-community/home-manager/commit/df556f2a17b7b94148d0275c1a57fed20e62ad18) | `` tests/mako: add a original deprecation test ``              |
| [`78ad8e3c`](https://github.com/nix-community/home-manager/commit/78ad8e3c31cc5239674dfd7ca6159e5ca14da0e8) | `` tests/mako: add a deprecation test ``                       |
| [`0be2c246`](https://github.com/nix-community/home-manager/commit/0be2c246e37a5b6e851111bf …
> chore(flake/home-manager): `535a541b` -> `df556f2a`

- flake.lock
| [`8d832ddf`](https://github.com/nix-community/home-manager/commit/8d832ddfda9facf538f3dda9b6985fb0234f151c) | `` foliate: init (#7049) `` |
> chore(flake/home-manager): `df556f2a` -> `8d832ddf`

- flake.lock
| [`14667935`](https://github.com/danth/stylix/commit/1466793570f22c56fc9f606151bcb306fcaa3551) | `` stylix: use keep-sorted (#1263) ``  |
| [`2fbe00ae`](https://github.com/danth/stylix/commit/2fbe00aebe3653a84862395bc77c69038a1b4f0f) | `` doc: wrap to width of 80 (#1262) `` |
> chore(flake/stylix): `b63f6640` -> `14667935`

- flake.lock
| [`b44c39cf`](https://github.com/nix-community/home-manager/commit/b44c39cf4618ccf58df2b68827ca95a3fecf0655) | `` foliate: fix theme settings example (#7053) `` |
> chore(flake/home-manager): `8d832ddf` -> `b44c39cf`

- flake.lock
| [`c2c720a2`](https://github.com/lovesegfault/vim-config/commit/c2c720a28ce349e3ef2cfda1c6fe816fee80cf67) | `` chore(flake/nixvim): ff0ccdf5 -> 1c53ad9b `` |
> chore(flake/lovesegfault-vim-config): `d9780df9` -> `c2c720a2`

- flake.lock
| [`7c1cefb9`](https://github.com/nix-community/home-manager/commit/7c1cefb98369cc85440642fdccc1c1394ca6dd2c) | `` zsh: avoid IFD while sourcing prezto ``                        |
| [`5f36563a`](https://github.com/nix-community/home-manager/commit/5f36563a5cae05bcfbaa5e08a69d2e8d94242f61) | `` zsh: consider zsh.{profile,login,logout,env}Extra in prezto `` |
> chore(flake/home-manager): `b44c39cf` -> `7c1cefb9`

- flake.lock
| [`689861d6`](https://github.com/Mic92/nix-fast-build/commit/689861d60a91614c1010bb6b5b006c18f115a9dd) | `` chore(deps): update nixpkgs digest to 3a00b4e (#155) `` |
> chore(flake/nix-fast-build): `a132dbcf` -> `689861d6`

- flake.lock
| Commit                                                                                                  | Message                                               |
| ------------------------------------------------------------------------------------------------------- | ----------------------------------------------------- |
| [`8c00a361`](https://github.com/tinted-theming/schemes/commit/8c00a361a99b6d356db9572240053a3f8716ea68) | `` Change base06 to lowercase in base16-vice (#56) `` |
> chore(flake/tinted-schemes): `28c26a62` -> `8c00a361`

- flake.lock
| Commit                                                                                               | Message        |
| ---------------------------------------------------------------------------------------------------- | -------------- |
| [`490c0d6b`](https://github.com/nix-community/disko/commit/490c0d6bd151e33caa5b2cf0ae37758234e947f6) | `` Fix typo `` |
> chore(flake/disko): `85555d27` -> `490c0d6b`

- flake.lock
| Commit                                                                                        | Message                                          |
| --------------------------------------------------------------------------------------------- | ------------------------------------------------ |
| [`98444a94`](https://github.com/danth/stylix/commit/98444a942a85072baf12c4a1c4cd5ef9531c8ab0) | `` stylix: sort flake inputs (#1265) ``          |
| [`5d28886e`](https://github.com/danth/stylix/commit/5d28886e94835231e9b32d53ab2d76235960c8ab) | `` halloy: use upstream themes option (#1259) `` |
> chore(flake/stylix): `14667935` -> `98444a94`

- flake.lock
| [`f59908e2`](https://github.com/Mic92/nix-fast-build/commit/f59908e2b7a9e04579dace6b5728957f5dfbd058) | `` chore(deps): update nixpkgs digest to b112281 (#156) `` |
> chore(flake/nix-fast-build): `689861d6` -> `f59908e2`

- flake.lock
| [`477433c7`](https://github.com/lovesegfault/vim-config/commit/477433c75eafb9e9dd5e6431d286958fad785290) | `` chore(flake/nixvim): 1c53ad9b -> 95ca65c8 `` |
> chore(flake/lovesegfault-vim-config): `c2c720a2` -> `477433c7`

- flake.lock
| [`ec7c109a`](https://github.com/nix-community/disko/commit/ec7c109a4f794fce09aad87239eab7f66540b888) | `` flake.lock: Update `` |
> chore(flake/disko): `490c0d6b` -> `ec7c109a`

- flake.lock
| [`954615c5`](https://github.com/nix-community/home-manager/commit/954615c510c9faa3ee7fb6607ff72e55905e69f2) | `` flake.lock: Update (#7058) ``                       |
| [`02ea7985`](https://github.com/nix-community/home-manager/commit/02ea79853ce42853d019ce689f533dc93e462862) | `` emacs: respect `defaultEditor` on Darwin (#7063) `` |
> chore(flake/home-manager): `6bf057fc` -> `954615c5`

- flake.lock
| [`b460904a`](https://github.com/danth/stylix/commit/b460904a6fc6273345d5e2525dc89ec033d68be9) | `` doc: use hash instead of sha256 in example (#1270) ``   |
| [`71f8b116`](https://github.com/danth/stylix/commit/71f8b1166b88751e59648c94ff919cfb94966b3d) | `` nixcord: change theme location on nix-darwin (#1221) `` |
| [`cb42af55`](https://github.com/danth/stylix/commit/cb42af5571ed53c402dc956380a3f0511a9b0d4b) | `` foliate: use upstream option (#1260) ``                 |
| …
> chore(flake/stylix): `98444a94` -> `b460904a`

- flake.lock
| Commit                                                                                                 | Message                                               |
| ------------------------------------------------------------------------------------------------------ | ----------------------------------------------------- |
| [`f2753a4c`](https://github.com/nix-darwin/nix-darwin/commit/f2753a4ca62332923affe1182e1d4bbdef8a3837) | `` _1password{,-gui}: fix `package` not being used `` |
> chore(flake/darwin): `f88be002` -> `f0fbf2db`

- flake.lock
| [`c8177029`](https://github.com/Mic92/nix-fast-build/commit/c81770298382b911f7f14db37b0c3e82848ab330) | `` chore(deps): update treefmt-nix digest to e758f27 (#158) `` |
| [`a8da457b`](https://github.com/Mic92/nix-fast-build/commit/a8da457b09d902dcfd681c82c710b8259abdea0c) | `` chore(deps): update nixpkgs digest to 3ad376e (#157) ``     |
> chore(flake/nix-fast-build): `f59908e2` -> `c8177029`

- flake.lock
| Commit                                                                                                 | Message                                               |
| ------------------------------------------------------------------------------------------------------ | ----------------------------------------------------- |
| [`d693997a`](https://github.com/nix-darwin/nix-darwin/commit/d693997a324d92253772ebfc7fe5d48f3633861a) | `` defaults: update docs for `AppleInterfaceStyle` `` |
> chore(flake/darwin): `f0fbf2db` -> `b6fff20c`

- flake.lock
| [`7dce68d3`](https://github.com/Mic92/nix-fast-build/commit/7dce68d3adc8821db75018ff96acc876fd07c697) | `` chore(deps): update nixpkgs digest to e06158e (#159) `` |
> chore(flake/nix-fast-build): `c8177029` -> `7dce68d3`

- flake.lock
| Commit                                                                                                      | Message                                                                                 |
| ----------------------------------------------------------------------------------------------------------- | --------------------------------------------------------------------------------------- |
| [`dbc90cc3`](https://github.com/nix-community/home-manager/commit/dbc90cc3ae9c8f927200a6ceaf4aa247ea6bc443) | `` rclone: declarative mounts (#7060) ``                                                |
| [`b022c9e3`](https://github.com/nix-community/home-manager/commit/b022c9e3b805484e44aaad1973ed7572b0c1b5c4) | `` vscode: allow specifying paths for VSCode JSON settings (#7055) `` …
> chore(flake/home-manager): `954615c5` -> `dbc90cc3`

- flake.lock
| Commit                                                                                                      | Message                                                                            |
| ----------------------------------------------------------------------------------------------------------- | ---------------------------------------------------------------------------------- |
| [`098e365d`](https://github.com/nix-community/home-manager/commit/098e365dd83311cc8236f83ea6be42abb49a6c76) | `` borgmatic: add darwin-specific documentation to services.borgmatic.frequency `` |
| [`8ae36f8e`](https://github.com/nix-community/home-manager/commit/8ae36f8ea2e0621b6cdea862e938aaa018e0ef27) | `` nix-gc: fix documentation ``                                                    |
> chore(flake/home-manager): `dbc90cc3` -> `098e365d`

- flake.lock
| [`019385d2`](https://github.com/lovesegfault/vim-config/commit/019385d293717f3b7307247aef0fae424e86dbab) | `` chore(flake/nixpkgs): d89fc19e -> adaa24fb ``     |
| [`cb76a3cc`](https://github.com/lovesegfault/vim-config/commit/cb76a3cc29ae39683d0ed91190a92052d3a2cf30) | `` chore(flake/treefmt-nix): 708ec80c -> e758f274 `` |
> chore(flake/lovesegfault-vim-config): `477433c7` -> `019385d2`

- flake.lock
| [`7566bc01`](https://github.com/danth/stylix/commit/7566bc015064ed3eb50b436f2225ddab06132beb) | `` mako: don't use criteria option (#1264) ``                   |
| [`69303679`](https://github.com/danth/stylix/commit/69303679a4e33a407f3fa36fa9b9585d917f2bf8) | `` kubecolor: check `stylix.enable` ``                          |
| [`7051eb4d`](https://github.com/danth/stylix/commit/7051eb4db14d9aa827b6ba4070fe465e5d987879) | `` kitty: check `stylix.enable` `` …
> chore(flake/stylix): `b460904a` -> `7566bc01`

- flake.lock
| Commit                                                                                                 | Message                                                        |
| ------------------------------------------------------------------------------------------------------ | -------------------------------------------------------------- |
| [`14737a96`](https://github.com/nix-darwin/nix-darwin/commit/14737a967691173be76e0c1a77167210b8c2d266) | `` defaults: add `com.apple.iCal` for managing Calendar.app `` |
> chore(flake/darwin): `b6fff20c` -> `8817b00b`

- flake.lock
| [`a1a72d18`](https://github.com/nix-community/home-manager/commit/a1a72d18ee75ce4559b5f59296a7b2d37f608c1c) | `` pgcli: init (#7072) `` |
> chore(flake/home-manager): `098e365d` -> `a1a72d18`

- flake.lock
| [`0e5b1613`](https://github.com/danth/stylix/commit/0e5b1613bd9285700c99e5ecf0a4e31da8cb5e04) | `` stylix: rename homeManagerModules to homeModules (#1267) `` |
> chore(flake/stylix): `7566bc01` -> `0e5b1613`

- flake.lock
| Commit                                                                                               | Message                                |
| ---------------------------------------------------------------------------------------------------- | -------------------------------------- |
| [`42dd9289`](https://github.com/numtide/treefmt-nix/commit/42dd9289571ae3c6884af9885b1a7432e3278f92) | `` README: fix formatting ``           |
| [`8ceec8b1`](https://github.com/numtide/treefmt-nix/commit/8ceec8b1c06dfaf8a7a8f6335939d96fb69f57e4) | `` Add zizmor as an action linter ``   |
| [`2faace5c`](https://github.com/numtide/treefmt-nix/commit/2faace5cefca955da79be88df944b1c02ac6102d) | `` Add kdlfmt as a formatter (#355) `` |
> chore(flake/treefmt-nix): `e758f274` -> `42dd9289`

- flake.lock
| [`145221c7`](https://github.com/Mic92/nix-fast-build/commit/145221c7d655a46c0d772a5050d16021fe9d7576) | `` chore(deps): update nixpkgs digest to b965e4c (#163) ``     |
| [`529e4e49`](https://github.com/Mic92/nix-fast-build/commit/529e4e494621ef5efc440d615aa2145a58e51800) | `` chore(deps): update treefmt-nix digest to 42dd928 (#162) `` |
> chore(flake/nix-fast-build): `2aba5540` -> `145221c7`

- flake.lock
| [`4d68f1f7`](https://github.com/danth/stylix/commit/4d68f1f761285a6236e7d45efa227d6f4af09c80) | `` ci: bump DeterminateSystems/update-flake-lock from 24 to 25 ``    |
| [`ecfa5c40`](https://github.com/danth/stylix/commit/ecfa5c40b6a063a8d20272c123d05a3b91e14608) | `` flake: include packages in checks (#1285) ``                      |
| [`88e1c23d`](https://github.com/danth/stylix/commit/88e1c23df2d8c47e23f744389822e3c45f1bfc19) | `` flake: fix and …
> chore(flake/stylix): `0e5b1613` -> `4d68f1f7`

- flake.lock
| [`ae755329`](https://github.com/nix-community/home-manager/commit/ae755329092c87369b9e9a1510a8cf1ce2b1c708) | `` templates/nix-darwin: nixpkgs track nixpkgs-unstable `` |
| [`5d132608`](https://github.com/nix-community/home-manager/commit/5d13260881eae0e9894f2c1dffd2cb97d6b79a07) | `` treewide: lnl7 -> nix-darwin ``                         |
| [`74d31e11`](https://github.com/nix-community/home-manager/commit/74d31e1165341bf510ee2017841a599f5cfc1608 …
> chore(flake/home-manager): `d2263ce5` -> `ae755329`

- flake.lock
| [`101d23df`](https://github.com/danth/stylix/commit/101d23dfacbb2704c40639ae9b6ac1d41de7143a) | `` ci: fix dependabot backport label (#1288) `` |
> chore(flake/stylix): `4d68f1f7` -> `101d23df`

- flake.lock
| Commit                                                                                                            | Message                          |
| ----------------------------------------------------------------------------------------------------------------- | -------------------------------- |
| [`b1f78db9`](https://github.com/nix-community/nix-index-database/commit/b1f78db975af80aacba3b45fd6035a979fa54534) | `` README: fix ad-hoc example `` |
> chore(flake/nix-index-database): `e9b21b01` -> `c1f63a0c`

- flake.lock
| [`765c14ec`](https://github.com/Mic92/nix-fast-build/commit/765c14ec198730fd1b0648078da6d6dfe9e11d51) | `` chore(deps): update treefmt-nix digest to ab0378b (#165) `` |
| [`0abf70ed`](https://github.com/Mic92/nix-fast-build/commit/0abf70edf43d59b8388a34c1e9c89a74568c486d) | `` chore(deps): update nixpkgs digest to e067fb8 (#164) ``     |
> chore(flake/nix-fast-build): `145221c7` -> `765c14ec`

- flake.lock
| [`ab0378b6`](https://github.com/numtide/treefmt-nix/commit/ab0378b61b0d85e73a8ab05d5c6029b5bd58c9fb) | `` buf: doesn't support multiple file targets `` |
> chore(flake/treefmt-nix): `42dd9289` -> `ab0378b6`

- flake.lock
| [`51d2cb88`](https://github.com/Mic92/nix-fast-build/commit/51d2cb882dde63b270f37579479afb69b5e64391) | `` chore(deps): update nixpkgs digest to 6315e9c (#166) `` |
> chore(flake/nix-fast-build): `765c14ec` -> `51d2cb88`

- flake.lock
| Commit                                                                                         | Message                                             |
| ---------------------------------------------------------------------------------------------- | --------------------------------------------------- |
| [`af991e8d`](https://github.com/ryantm/agenix/commit/af991e8dc3899c91012f8c5621568ab7beee30fb) | `` Separate flags from positional args with `--` `` |
| [`cccd5afb`](https://github.com/ryantm/agenix/commit/cccd5afb1c02b71eb5e9facb074f342a44ec46c7) | `` docs: add home-manager module documentation ``   |
> chore(flake/agenix): `96e078c6` -> `8a4516ae`

- flake.lock
| Commit                                                                                         | Message                              |
| ---------------------------------------------------------------------------------------------- | ------------------------------------ |
| [`bd33a9b9`](https://github.com/ryantm/agenix/commit/bd33a9b9a5a370a7d1599c7c3af1d71df45f0201) | `` doc: strip trailing whitespace `` |
> chore(flake/agenix): `8a4516ae` -> `6697e8ba`

- flake.lock
| Commit                                                                                        | Message                                                          |
| --------------------------------------------------------------------------------------------- | ---------------------------------------------------------------- |
| [`91b23c7b`](https://github.com/danth/stylix/commit/91b23c7bc60b29e0140242db7cf9e46e2bb685be) | `` doc: explain how to build & check the docs locally (#1273) `` |
| [`3c172cbb`](https://github.com/danth/stylix/commit/3c172cbbc6a657039c6eb0c2eec83c27c69342e2) | `` gnome-text-editor: update style path (#1296) ``               |
> chore(flake/stylix): `101d23df` -> `91b23c7b`

- flake.lock
| [`8b3bf4dd`](https://github.com/lovesegfault/vim-config/commit/8b3bf4dd3503346352a0159bfa18f70374bae59f) | `` chore(flake/nixpkgs): adaa24fb -> e06158e5 ``     |
| [`9b6e6e24`](https://github.com/lovesegfault/vim-config/commit/9b6e6e24b079e6195811788e83c82fe355954de0) | `` chore(flake/nixvim): 2628efee -> 1deeb7f6 ``      |
| [`95b951b6`](https://github.com/lovesegfault/vim-config/commit/95b951b6b01d5f3847704b990d97916f2eda6a61) | `` chore(flake/treefmt-nix): …
> chore(flake/lovesegfault-vim-config): `d2c6d1e5` -> `8b3bf4dd`

- flake.lock
| [`5f6f08da`](https://github.com/nix-community/stylix/commit/5f6f08daad947b3116ccb878e4226e6bdf7a0c61) | `` treewide: change repository owner to nix-community (#1297) `` |
| [`7a0f30b5`](https://github.com/nix-community/stylix/commit/7a0f30b57eb940cd280e2001c73b09a63e6a5311) | `` stylix: update documentation URL in palette.html (#1298) ``   |
> chore(flake/stylix): `91b23c7b` -> `5f6f08da`

- flake.lock
| [`ec179dd1`](https://github.com/nix-community/nix-index-database/commit/ec179dd13fb7b4c6844f55be91436f7857226dce) | `` update generated.nix to release 2025-05-18-033800 `` |
| [`dbc173ab`](https://github.com/nix-community/nix-index-database/commit/dbc173abd9c1639597965fd17a95e8cdb86eadc2) | `` flake.lock: Update ``                                |
> chore(flake/nix-index-database): `c1f63a0c` -> `ec179dd1`

- flake.lock
| [`940de011`](https://github.com/nix-community/stylix/commit/940de011bb02a41e4b005beea42032e71abc5719) | `` gnome: update CSS to version 48.1 (#1295) `` |
| [`54628294`](https://github.com/nix-community/stylix/commit/54628294614355a4d6fb9c31c7c8684a3ed84385) | `` doc: update nix-darwin owner (#1301) ``      |
> chore(flake/stylix): `5f6f08da` -> `940de011`

- flake.lock
| [`4ade860f`](https://github.com/Mic92/nix-fast-build/commit/4ade860f015131c12ab0317289ad9336c5e882c7) | `` chore(deps): update nixpkgs digest to d0afebf (#167) `` |
> chore(flake/nix-fast-build): `51d2cb88` -> `4ade860f`

- flake.lock
| [`97118a31`](https://github.com/nix-community/home-manager/commit/97118a310eb8e13bc1b9b12d67267e55b7bee6c8) | `` flake-module: use toString primop `` |
| [`ee85cfc5`](https://github.com/nix-community/home-manager/commit/ee85cfc5c132e2cf956a7b5ab156ddaedaefcbbc) | `` home-manager: add missing file ``    |
| [`10d13a62`](https://github.com/nix-community/home-manager/commit/10d13a62e3ab95ba904cbc3d2a44ac177d85da65) | `` flake.lock: Update ``                |
| …
> chore(flake/home-manager): `ae755329` -> `97118a31`

- flake.lock
| Commit                                                                                         | Message                                                           |
| ---------------------------------------------------------------------------------------------- | ----------------------------------------------------------------- |
| [`34246aec`](https://github.com/ryantm/agenix/commit/34246aece3f4f63163389f22a7bde1b0f638157c) | `` doc: update link from unofficial nixos wiki to official one `` |
> chore(flake/agenix): `6697e8ba` -> `4835b1dc`

- flake.lock
| [`2eaa338e`](https://github.com/nix-community/stylix/commit/2eaa338eb879b8432f7e252d6ab8725ada98f52d) | `` gnome: install User Themes extension (#1306) ``      |
| [`8778cde5`](https://github.com/nix-community/stylix/commit/8778cde5fe6fc5a891558b2b0c7379f7741df9b9) | `` doc: set site-url (#1307) ``                         |
| [`3993363c`](https://github.com/nix-community/stylix/commit/3993363c0ca4e2872df00b57db51551267c76c9f) | `` doc: simplify 'Development Setup' …
> chore(flake/stylix): `940de011` -> `2eaa338e`

- flake.lock
| [`c8f09c16`](https://github.com/nix-community/stylix/commit/c8f09c164b6490613ccee5a083f22095385bef5c) | `` stylix: fix link to docs in README (#1311) `` |
> chore(flake/stylix): `2eaa338e` -> `c8f09c16`

- flake.lock
| [`26be029d`](https://github.com/lovesegfault/vim-config/commit/26be029d7db3531ad1519e95b23e13877f111475) | `` chore(flake/nixpkgs): e06158e5 -> 292fa7d4 `` |
| [`968acd3c`](https://github.com/lovesegfault/vim-config/commit/968acd3cfc9e6a486b5c31639b00c6eecc6d9dcb) | `` chore(flake/nixvim): 1deeb7f6 -> 563fdaee ``  |
> chore(flake/lovesegfault-vim-config): `8b3bf4dd` -> `26be029d`

- flake.lock
| [`cec44d77`](https://github.com/nix-community/disko/commit/cec44d77d9dacf0c91d3d51aff128fefabce06ee) | `` flake.lock: Update `` |
> chore(flake/disko): `ec7c109a` -> `cec44d77`

- flake.lock
| [`330397c7`](https://github.com/Mic92/nix-fast-build/commit/330397c7e005ef1fbd420d89877ed34e12d4988a) | `` chore(deps): update nixpkgs digest to b7d438b (#168) `` |
> chore(flake/nix-fast-build): `4ade860f` -> `330397c7`

- flake.lock
| [`214d9223`](https://github.com/Mic92/nix-fast-build/commit/214d92233e3b125efaaa2c2931448ab6f5bccd61) | `` chore(deps): update nixpkgs digest to 949fb7f (#169) `` |
> chore(flake/nix-fast-build): `330397c7` -> `214d9223`

- flake.lock
| [`54aa02e6`](https://github.com/nix-community/stylix/commit/54aa02e6272811233d099ad2493adb2d1b19415e) | `` doc: danth/stylix → nix-community/stylix (#1312) `` |
> chore(flake/stylix): `c8f09c16` -> `54aa02e6`

- flake.lock
| [`687c8fcf`](https://github.com/NixOS/nixos-hardware/commit/687c8fcf681371df084ad98b6211b928163b7394) | `` X1 Yoga: Enable fingerprint reader and FW update ``           |
| [`45da8c8a`](https://github.com/NixOS/nixos-hardware/commit/45da8c8ad8f77302ab3cbbcda7a113507f8ecebb) | `` lenovo/legion/15ich: Use Coffee Lake CPU ``                   |
| [`f139290a`](https://github.com/NixOS/nixos-hardware/commit/f139290af12744eca2a5b460ea6cfb1dceded227) | …
> chore(flake/nixos-hardware): `e81fd167` -> `e8f38b2c`

- flake.lock
| [`f8833c5e`](https://github.com/nix-community/stylix/commit/f8833c5e0c64287cd51a27e6061a88f4225b6b70) | `` treewide: update documentation links (#1314) ``        |
| [`2e58606c`](https://github.com/nix-community/stylix/commit/2e58606c9c14d943783b5c0a8097f6f9712db3ee) | `` flake: update and unlock tinted-kitty input (#1308) `` |
> chore(flake/stylix): `54aa02e6` -> `f8833c5e`

- flake.lock
| [`45c29856`](https://github.com/nix-community/home-manager/commit/45c2985644b60ab64de2a2d93a4d132ecb87cf66) | `` ci: bump DeterminateSystems/update-flake-lock from 24 to 25 (#7091) `` |
> chore(flake/home-manager): `97118a31` -> `45c29856`

- flake.lock
| [`f93affeb`](https://github.com/lovesegfault/vim-config/commit/f93affebd48a680481fecb7b7019272abb9a572e) | `` chore(flake/nixvim): 563fdaee -> 14c7f5f8 `` |
> chore(flake/lovesegfault-vim-config): `47747594` -> `f93affeb`

- flake.lock
| Commit                                                                                               | Message                                                                    |
| ---------------------------------------------------------------------------------------------------- | -------------------------------------------------------------------------- |
| [`58e72c6e`](https://github.com/nix-community/disko/commit/58e72c6ec29a9df611ed5cdef37db1081797a6e0) | `` build(deps): bump DeterminateSystems/update-flake-lock from 24 to 25 `` |
> chore(flake/disko): `cec44d77` -> `58e72c6e`

- flake.lock
| [`ee94f43c`](https://github.com/NixOS/nixos-hardware/commit/ee94f43c05e80c7a7e5d94ec78426f2bc92a63dd) | `` Add Lenovo Ideapad 5 Pro 14IMH9 / XiaoXin Pro 14IMH9 2024 `` |
| [`a9a7323a`](https://github.com/NixOS/nixos-hardware/commit/a9a7323a067284b5546beef7221ce49a1f3b8d24) | `` framework: Add framework12 ``                                |
> chore(flake/nixos-hardware): `e8f38b2c` -> `6ac6ec6f`

- flake.lock
| [`fb9c2205`](https://github.com/nix-community/stylix/commit/fb9c22056faa95f35749f116c49c5c202ceb159c) | `` doc: move to doc directory (#1272) `` |
> chore(flake/stylix): `f8833c5e` -> `fb9c2205`

- flake.lock
| [`df522e78`](https://github.com/nix-community/disko/commit/df522e787fdffc4f32ed3e1fca9ed0968a384d62) | `` only use nom if we write to a terminal `` |
> chore(flake/disko): `58e72c6e` -> `df522e78`

- flake.lock
| Commit                                                                                                      | Message                                                                                       |
| ----------------------------------------------------------------------------------------------------------- | --------------------------------------------------------------------------------------------- |
| [`559f6d36`](https://github.com/nix-community/home-manager/commit/559f6d36b32dd2180ebac40c522dd36290430fc5) | `` news: add some more missing news items (#7097) ``                                          |
| [`d3f5d870`](https://github.com/nix-community/home-manager/commit/d3f5d870e3f33f69fa6c0f9bcc44f8803a30e38e) | `` home-manager: add force option for gtk-2 config (#7073) `` …
> chore(flake/home-manager): `45c29856` -> `559f6d36`

- flake.lock
| Commit                                                                                                | Message                                                            |
| ----------------------------------------------------------------------------------------------------- | ------------------------------------------------------------------ |
| [`69b3dd05`](https://github.com/nix-community/stylix/commit/69b3dd05e6b64c71a10fb749b5ac4d7c8e40f720) | `` stylix: bump release to 25.11 (#1317) ``                        |
| [`c7feebc3`](https://github.com/nix-community/stylix/commit/c7feebc34ab7374cadea1a5da7ee3393ee692d68) | `` qutebrowser: remove lib.mkDefault option declaration (#1227) `` |
| [`43a652de`](https://github.com/nix-community/stylix/commit/43a652de771aabd206ad9ce137171d0da09661 …
> chore(flake/stylix): `fb9c2205` -> `69b3dd05`

- flake.lock
| [`29dda415`](https://github.com/nix-community/home-manager/commit/29dda415f5b2178278283856c6f9f7b48a2a4353) | `` qutebrowser: add support for per domain settings (#7078) ``         |
| [`3f591550`](https://github.com/nix-community/home-manager/commit/3f591550a99fe5a2a57927ccab15dedb4210e53e) | `` formatter: remove script, add treefmt.toml + keep-sorted (#7056) `` |
> chore(flake/home-manager): `559f6d36` -> `29dda415`

- flake.lock
| [`a0843a9c`](https://github.com/lovesegfault/vim-config/commit/a0843a9c563832c8da49d9e8211a5ff6a48b07de) | `` chore(flake/nixvim): 14c7f5f8 -> 47dba84e `` |
> chore(flake/lovesegfault-vim-config): `f93affeb` -> `a0843a9c`

- flake.lock
| Commit                                                                                                      | Message                                                                 |
| ----------------------------------------------------------------------------------------------------------- | ----------------------------------------------------------------------- |
| [`2468b2d3`](https://github.com/nix-community/home-manager/commit/2468b2d35512d093aeb04972a1d8c20a0735793f) | `` files: show colliding files at bottom in checkLinkTargets (#5495) `` |
> chore(flake/home-manager): `29dda415` -> `2468b2d3`

- flake.lock
| [`4830942f`](https://github.com/nix-community/stylix/commit/4830942fa2a475c2be5d45ca1267fa77036bf9a6) | `` treewide: remove unnecessary builtins prefix (#1322) `` |
> chore(flake/stylix): `69b3dd05` -> `4830942f`

- flake.lock
| [`2b176d49`](https://github.com/nix-community/stylix/commit/2b176d49defb6793eb475809de10097ea6d84b41) | `` discord: use new enable option for testbed ``                         |
| [`a2236aa2`](https://github.com/nix-community/stylix/commit/a2236aa2906a5c9a1029345adb4f14e099f5972a) | `` stylix: use a cheaper module eval for the `enable` option ``          |
| [`dfcab747`](https://github.com/nix-community/stylix/commit/dfcab7476d36cd …
> chore(flake/stylix): `4830942f` -> `42b15218`

- flake.lock
| [`6c2eb1e2`](https://github.com/nix-community/home-manager/commit/6c2eb1e24cd0e76d88bdd633ef4c50d6286586e0) | `` flake.lock: Update (#7101) `` |
> chore(flake/home-manager): `2468b2d3` -> `6c2eb1e2`

- flake.lock
| [`7c66eda8`](https://github.com/nix-community/stylix/commit/7c66eda89ec8eabcdd8f21790224e2971c6f9063) | `` treewide: partially apply mkTarget `` |
| [`c4fa6844`](https://github.com/nix-community/stylix/commit/c4fa684471d9230f4ca4d4543f02e8ac4c5f749b) | `` stylix: add mkTarget function ``      |
> chore(flake/stylix): `42b15218` -> `d3fadda7`

- flake.lock
| [`c32026ea`](https://github.com/nix-community/stylix/commit/c32026eab2b314c4599fe4a4f6070229d2d7a5f5) | `` mpv: use mkTarget (#1334) ``             |
| [`4ce349da`](https://github.com/nix-community/stylix/commit/4ce349da56e075f7e3456b48731cbbf5ae8b1eb8) | `` alacritty: fix mkTarget usage (#1332) `` |
> chore(flake/stylix): `d3fadda7` -> `c32026ea`

- flake.lock
| [`614c12c5`](https://github.com/nix-community/stylix/commit/614c12c5db0da406fd232cb9b0e82aec304a854e) | `` ci: fix tag for label merge conflicts (#1344) ``     |
| [`46caa412`](https://github.com/nix-community/stylix/commit/46caa4122c4eacafba8e38f4b9344dd149064a10) | `` ci: add workflow to label merge conflicts (#1269) `` |
> chore(flake/stylix): `c32026ea` -> `614c12c5`

- flake.lock
| [`f9186c64`](https://github.com/nix-community/home-manager/commit/f9186c64fcc6ee5f0114547acf9e814c806a640b) | `` Revert "fontconfig: Fix missing default fontconfig files (#7045)" (#7103) `` |
| [`a69ebd97`](https://github.com/nix-community/home-manager/commit/a69ebd97025969679de9f930958accbe39b4c705) | `` direnv: Fix `default` syntax for nushell integration (#7081) ``              |
> chore(flake/home-manager): `6c2eb1e2` -> `f9186c64`

- flake.lock
| [`4ce6bba2`](https://github.com/NixOS/nixos-hardware/commit/4ce6bba2f7c0d13b930685068e964dfd9f542fe1) | `` Update correct hash for imx mkimage utility `` |
> chore(flake/nixos-hardware): `2b911888` -> `11f2d9ea`

- flake.lock
| [`70391676`](https://github.com/Mic92/nix-fast-build/commit/7039167675dddba74e4ebbdfd430d1b42adaeb2c) | `` chore(deps): update treefmt-nix digest to 020cb42 (#172) `` |
> chore(flake/nix-fast-build): `225e65c9` -> `70391676`

- flake.lock
| [`f9a6a599`](https://github.com/nix-community/stylix/commit/f9a6a599d7212980c97e93701e50a7002d08802f) | `` hyprland: fix hyprpaper enable condition (#1355) `` |
| [`c1ef1efd`](https://github.com/nix-community/stylix/commit/c1ef1efd8fe5d263f3e9ebf34b64c377f27ebe06) | `` qutebrowser: simplify dark mode setting (#1352) ``  |
> chore(flake/stylix): `230705d5` -> `f9a6a599`

- flake.lock
| [`3e447578`](https://github.com/nix-community/stylix/commit/3e447578effb29574adf26f74d5a9466f977c5ca) | `` doc: give consistant input version and follows instructions (#1271) `` |
| [`e16d94d8`](https://github.com/nix-community/stylix/commit/e16d94d8685f5b1025def349f3dcb06b6cf5a6d5) | `` ci: prefix labels with type (#1256) ``                                 |
| [`6f67462b`](https://github.com/nix-community/stylix/commit/6f67462b01 …
> chore(flake/stylix): `f9a6a599` -> `3e447578`

- flake.lock
| [`a8685705`](https://github.com/nix-community/home-manager/commit/a868570581f0dbdef7e33c8c9bb34b735dfcbacf) | `` news: fix timestamp (#7109) `` |
> chore(flake/home-manager): `f9186c64` -> `a8685705`

- flake.lock
| [`f99fe598`](https://github.com/nix-community/stylix/commit/f99fe598a68831debbf096e289296c7c7178c21f) | `` foot: fix font size (#1360) `` |
> chore(flake/stylix): `3e447578` -> `f99fe598`

- flake.lock
| [`06f14b87`](https://github.com/lovesegfault/vim-config/commit/06f14b875dbbd856a68c432eec3b07678102b91c) | `` chore(flake/nixvim): 7e3a0f4e -> 46fd0b18 ``      |
| [`9b62fa85`](https://github.com/lovesegfault/vim-config/commit/9b62fa85e9b090482fe6d7bb2574f38d1669d962) | `` chore(flake/treefmt-nix): ab0378b6 -> 020cb423 `` |
> chore(flake/lovesegfault-vim-config): `0ba6605f` -> `06f14b87`

- flake.lock
| [`14b4478b`](https://github.com/Mic92/nix-fast-build/commit/14b4478bf841a53a8d57efa7b0cf849c91f2cddb) | `` chore(deps): update nixpkgs digest to ebcc1d6 (#171) `` |
> chore(flake/nix-fast-build): `70391676` -> `14b4478b`

- flake.lock
| Commit                                                                                                 | Message                                              |
| ------------------------------------------------------------------------------------------------------ | ---------------------------------------------------- |
| [`0e3b8554`](https://github.com/nix-darwin/nix-darwin/commit/0e3b855456ca38cc2c23cf24eade14b43b72032a) | `` add test ``                                       |
| [`e09c1aef`](https://github.com/nix-darwin/nix-darwin/commit/e09c1aefe489d1cb2f057ed443eb47e21ef3e3d6) | `` feat(services.openssh): add extraConfig option `` |
> chore(flake/darwin): `e2676937` -> `93562b65`

- flake.lock
| [`c4fa0a45`](https://github.com/Mic92/nix-fast-build/commit/c4fa0a456ff799b66bbd50993fe1259993a3c7aa) | `` chore(deps): update nixpkgs digest to 223d529 (#173) `` |
> chore(flake/nix-fast-build): `14b4478b` -> `c4fa0a45`

- flake.lock
| Commit                                                                                                | Message                                      |
| ----------------------------------------------------------------------------------------------------- | -------------------------------------------- |
| [`8dd18dd3`](https://github.com/nix-community/stylix/commit/8dd18dd3955548fe299d7ba337e464bc28dd1448) | `` hyprlock: fix setting background ``       |
| [`86cfc446`](https://github.com/nix-community/stylix/commit/86cfc446a5f4352c28ae81ae71303a1746cd2d85) | `` hyprlock: add MrSom3body as maintainer `` |
> chore(flake/stylix): `f99fe598` -> `8dd18dd3`

- flake.lock
| Commit                                                                                                 | Message                                           |
| ------------------------------------------------------------------------------------------------------ | ------------------------------------------------- |
| [`acf6b460`](https://github.com/nix-darwin/nix-darwin/commit/acf6b46011d044d1e99fedf111a8e7c4ef6c93cd) | `` system.build: Treat as variables, make lazy `` |
> chore(flake/darwin): `93562b65` -> `33220d47`

- flake.lock
| [`7589ff18`](https://github.com/lovesegfault/vim-config/commit/7589ff1861fa1e530c23d41dd6d9cd8c9faf8fde) | `` chore(flake/nixvim): 46fd0b18 -> 2f610f97 `` |
> chore(flake/lovesegfault-vim-config): `06f14b87` -> `7589ff18`

- flake.lock
| Commit                                                                                                 | Message                               |
| ------------------------------------------------------------------------------------------------------ | ------------------------------------- |
| [`7347f725`](https://github.com/nix-darwin/nix-darwin/commit/7347f7250726dba3557ae6d367f5773a0036ed3f) | `` programs/arqbackup: init module `` |
> chore(flake/darwin): `33220d47` -> `acd6aa5a`

- flake.lock
| Commit                                                                                                  | Message                               |
| ------------------------------------------------------------------------------------------------------- | ------------------------------------- |
| [`9aa38a41`](https://github.com/tinted-theming/schemes/commit/9aa38a41f02e46e37e60b42d0719efb8454a40b2) | `` Fix mountain base16 theme (#57) `` |
> chore(flake/tinted-schemes): `8c00a361` -> `9aa38a41`

- flake.lock
| [`c3d48a17`](https://github.com/nix-community/home-manager/commit/c3d48a17aad6778348abb1c4109add90cc42107c) | `` obsidian: add module (#6487) ``                                  |
| [`cf9ff6d9`](https://github.com/nix-community/home-manager/commit/cf9ff6d9930f74dd949ff2fde953470ecde37749) | `` wayvnc: init (#7123) ``                                          |
| [`8fc1e46a`](https://github.com/nix-community/home-manager/commit/8fc1 …
> chore(flake/home-manager): `74192507` -> `c3d48a17`

- flake.lock
| Commit                                                                                                 | Message                            |
| ------------------------------------------------------------------------------------------------------ | ---------------------------------- |
| [`5374405a`](https://github.com/nix-darwin/nix-darwin/commit/5374405a015f02e866bd4a9bbc551d07d7d3a0c2) | `` config/terminfo: init module `` |
> chore(flake/darwin): `acd6aa5a` -> `e0a7c377`

- flake.lock
| [`7196f365`](https://github.com/lovesegfault/vim-config/commit/7196f365c6555ed01a5082d3c9ea9ec482201058) | `` chore(flake/nixpkgs): 2795c506 -> 063f43f2 `` |
| [`4680f1e4`](https://github.com/lovesegfault/vim-config/commit/4680f1e4075e05fa6ec3c38ed8aec26fb01287c6) | `` chore(flake/nixvim): 2f610f97 -> 2c0a9ff1 ``  |
> chore(flake/lovesegfault-vim-config): `7589ff18` -> `7196f365`

- flake.lock
| [`a98adbf5`](https://github.com/nix-community/nix-index-database/commit/a98adbf54d663395df0b9929f6481d4d80fc8927) | `` update generated.nix to release 2025-05-25-034005 `` |
| [`44cc62e8`](https://github.com/nix-community/nix-index-database/commit/44cc62e814ad26cbe4d0ab0f03e710acac8b35c4) | `` flake.lock: Update ``                                |
> chore(flake/nix-index-database): `ec179dd1` -> `a98adbf5`

- flake.lock
| Commit                                                                                                 | Message                                               |
| ------------------------------------------------------------------------------------------------------ | ----------------------------------------------------- |
| [`0d3dcc55`](https://github.com/nix-darwin/nix-darwin/commit/0d3dcc55f3fef8ed1eb5afd976c6cc07f35071c3) | `` ci: enable merge queue ``                          |
| [`cd6a8a79`](https://github.com/nix-darwin/nix-darwin/commit/cd6a8a796d6d6479f425b56c601b189860e664fe) | `` config/system-path: restructure to mirror NixOS `` |
> chore(flake/darwin): `e0a7c377` -> `a9939228`

- flake.lock
| [`901f8fef`](https://github.com/nix-community/home-manager/commit/901f8fef7f349cf8a8e97b3230b22fd592df9160) | `` flake.lock: Update (#7125) `` |
> chore(flake/home-manager): `c1e67103` -> `901f8fef`

- flake.lock
| [`e22f96de`](https://github.com/nix-community/stylix/commit/e22f96de3f57b1ab1a393607bc08c003925f68fc) | ``  doc: update documentation to reflect #1083 (#1329) `` |
> chore(flake/stylix): `34b59308` -> `e22f96de`

- flake.lock
| [`33f16171`](https://github.com/Mic92/nix-fast-build/commit/33f161715e8a49bbae65a1a384b19b0a9fcf5317) | `` chore(deps): lock file maintenance (#176) `` |
> chore(flake/nix-fast-build): `5f5ff111` -> `33f16171`

- flake.lock
| [`a894f281`](https://github.com/nix-community/disko/commit/a894f2811e1ee8d10c50560551e50d6ab3c392ba) | `` flake.lock: Update `` |
> chore(flake/disko): `df522e78` -> `a894f281`

- flake.lock
| [`0f595c2d`](https://github.com/Mic92/nix-fast-build/commit/0f595c2db69ad8bf1caf2619a10684f1a5914136) | `` chore(deps): update treefmt-nix digest to 1f3f7b7 (#177) `` |
> chore(flake/nix-fast-build): `33f16171` -> `0f595c2d`

- flake.lock
| [`d66135de`](https://github.com/nix-community/stylix/commit/d66135deb39da600a4dcd7c686e9225eb531ec5a) | `` flake: add ruff formatter (#1389) `` |
| [`17398c4f`](https://github.com/nix-community/stylix/commit/17398c4fce431ddda8027b00634393e803576d05) | `` treewide: name default testbeds ``   |
| [`2b7ff59d`](https://github.com/nix-community/stylix/commit/2b7ff59d813d5b243eae5981ca3a598d65c1a352) | `` stylix: reduce testbed names ``      |
> chore(flake/stylix): `aa70426f` -> `1fdbf01e`

- flake.lock
| [`a4616c51`](https://github.com/lovesegfault/vim-config/commit/a4616c51eb47b152226d713139eae6707b116cbc) | `` chore(flake/nixvim): b37d4294 -> 91ee94cd ``      |
| [`f29d6f6e`](https://github.com/lovesegfault/vim-config/commit/f29d6f6e88d95a6acb4f968b38830409b9677349) | `` chore(flake/treefmt-nix): 020cb423 -> 1f3f7b78 `` |
> chore(flake/lovesegfault-vim-config): `5af5eeaa` -> `a4616c51`

- flake.lock
| [`1afe2466`](https://github.com/lovesegfault/vim-config/commit/1afe24668347a5f020c2ef4082ece94d7a96aad5) | `` chore(flake/nixpkgs): 063f43f2 -> 62b852f6 `` |
> chore(flake/lovesegfault-vim-config): `a4616c51` -> `1afe2466`

- flake.lock
| [`e38a646e`](https://github.com/nix-community/stylix/commit/e38a646e5cd3d000c8fffb14632f3bb8a45dd042) | `` bemenu: fix undefined variable error (#1390) `` |
> chore(flake/stylix): `dedf5de5` -> `e38a646e`

- flake.lock
| [`ad22169e`](https://github.com/nix-community/home-manager/commit/ad22169efa67448badd870076e441778f4cf7948) | `` jellyfin-mpv-shim: add module (#7129) ``            |
| [`8cb8a04c`](https://github.com/nix-community/home-manager/commit/8cb8a04cb1383fe08bb6cbf672f00ed60c92bbbd) | `` home-cursor: set hyprcursor size default (#7145) `` |
> chore(flake/home-manager): `d23d20f5` -> `ad22169e`

- flake.lock
| [`f996bf88`](https://github.com/nix-community/stylix/commit/f996bf88703547cb7a21173ba1674fec9b32afe0) | `` stylix: move testbed `isEnabled` to its own file `` |
| [`aaa0517d`](https://github.com/nix-community/stylix/commit/aaa0517d203b7f5f1a6b14d3126fd513de63197c) | `` stylix: move testbed themes to their own files ``   |
| [`7afee8f8`](https://github.com/nix-community/stylix/commit/7afee8f85b8737b28b3f2e96c21c5660c42e967d) | `` stylix: move testbed modules to their …
> chore(flake/stylix): `ba217a81` -> `25793957`

- flake.lock
| [`02077149`](https://github.com/nix-community/home-manager/commit/02077149e2921014511dac2729ae6dadb4ec50e2) | `` flake.lock: Update (#7148) ``                |
| [`9bf9b1ae`](https://github.com/nix-community/home-manager/commit/9bf9b1ae000a8484f718bef93a381fe7752e98b5) | `` Translate using Weblate (Persian) (#7150) `` |
> chore(flake/home-manager): `f5b12be8` -> `02077149`

- flake.lock
| [`e781d398`](https://github.com/lovesegfault/vim-config/commit/e781d3987c41d85d7365dccf819e8d654276a402) | `` chore(flake/nixpkgs): 62b852f6 -> 4faa5f53 `` |
| [`c2355f89`](https://github.com/lovesegfault/vim-config/commit/c2355f89cbe94545e3d9f6e28c96152da24babeb) | `` chore(flake/nixvim): 65b1bffd -> af5a0dea ``  |
> chore(flake/lovesegfault-vim-config): `846646e1` -> `e781d398`

- flake.lock
| Commit                                                                                                      | Message                                                                               |
| ----------------------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------- |
| [`95c988cf`](https://github.com/nix-community/home-manager/commit/95c988cf08e9a5a8fe7cc275d5e3f24e9e87bd51) | `` xsession: add xdg-desktop-autostart to requires of hm-graphical-session (#7108) `` |
| [`85a27991`](https://github.com/nix-community/home-manager/commit/85a27991d5d9c980e33179b2fc7f0eb4f7262db0) | `` fish: add binds option (#7121) ``                                                  | …
> chore(flake/home-manager): `02077149` -> `95c988cf`

- flake.lock
| [`01c44ecd`](https://github.com/lovesegfault/vim-config/commit/01c44ecd583747ed0c6938348e3a60c2c4cb3544) | `` chore(flake/nixvim): af5a0dea -> a9e45072 `` |
> chore(flake/lovesegfault-vim-config): `e781d398` -> `01c44ecd`

- flake.lock
| [`4e9efaa6`](https://github.com/nix-community/home-manager/commit/4e9efaa68b0be7e19127dad4f0506a9b89e28ef4) | `` misc: add librewolf native messaging hosts (#7127) ``    |
| [`8a4b3826`](https://github.com/nix-community/home-manager/commit/8a4b38262755fce39551e1182af1621a06ddde35) | `` kodi: make type for settings less restrictive (#5277) `` |
| [`2f4db1cd`](https://github.com/nix-community/home-manager/commit/2f4db1cd5be0afaa0a2ec8fa5da6460f0ebd …
> chore(flake/home-manager): `da282034` -> `4e9efaa6`

- flake.lock
| [`7c60ea02`](https://github.com/nix-community/home-manager/commit/7c60ea029602851cdeb2f3246e991fcc117195bc) | `` ci: add 'GitHub App' TODO to update workflow `` |
| [`9d2ae595`](https://github.com/nix-community/home-manager/commit/9d2ae59579b61a2137f12d87452733e3ab04d721) | `` ci: add backport workflow ``                    |
> chore(flake/home-manager): `379c9fb8` -> `7c60ea02`

- flake.lock
| [`f29f93fd`](https://github.com/lovesegfault/vim-config/commit/f29f93fd646ea9617456dd082a3cf50f72d55b56) | `` chore(flake/nixpkgs): 4faa5f53 -> 96ec055e `` |
| [`10735656`](https://github.com/lovesegfault/vim-config/commit/10735656e2c4bd42a0d3d368183d78e3d1821eeb) | `` chore(flake/nixvim): a9e45072 -> 8b3a69cf ``  |
> chore(flake/lovesegfault-vim-config): `01c44ecd` -> `f29f93fd`

- flake.lock
| [`6d09fd37`](https://github.com/nix-community/home-manager/commit/6d09fd37a7d4110251c1c03cb09fbf6321fbe10d) | `` ci: alternative fix for backport if condition (#7169) `` |
| [`b65126fa`](https://github.com/nix-community/home-manager/commit/b65126fa71e744c53fbae44d90139d3069711ac4) | `` ci: fix backport if condition (#7167) ``                 |
> chore(flake/home-manager): `7c60ea02` -> `6d09fd37`

- flake.lock
| [`99130f41`](https://github.com/nix-community/stylix/commit/99130f414dc51bb8fd3980efc9005ca6596e123b) | `` stylix: minor meta.nix cleanup ``                         |
| [`03748a36`](https://github.com/nix-community/stylix/commit/03748a36d5926bfd4bc084e8ba579d7a9c91922b) | `` stylix: drop unnecessary use of `self` in meta.nix ``     |
| [`23e3013b`](https://github.com/nix-community/stylix/commit/23e3013b6257c8fc9556f5e3a25047f30bcd8fdc) | `` stylix: drop …
> chore(flake/stylix): `b69e9b76` -> `8762da95`

- flake.lock
| [`64b9f2c2`](https://github.com/nix-community/stylix/commit/64b9f2c2df31bb87bdd2360a2feb58c817b4d16c) | `` stylix: yamlint ignore truthy for workflows (#1116) `` |
| [`093087e9`](https://github.com/nix-community/stylix/commit/093087e969e2ecfe1175dbf3cbc5c8624fde1c1e) | `` stylix: add imports to mkTarget (#1363) ``             |
> chore(flake/stylix): `8762da95` -> `64b9f2c2`

- flake.lock
| [`05328493`](https://github.com/lovesegfault/vim-config/commit/053284930d5e4a272552e1e042f258aa5569ebb3) | `` chore(flake/nixpkgs): 96ec055e -> 910796ca ``     |
| [`044adb79`](https://github.com/lovesegfault/vim-config/commit/044adb794d82a1ae64cdfac2c973d5f919207ec9) | `` chore(flake/flake-parts): c621e842 -> 49f0870d `` |
> chore(flake/lovesegfault-vim-config): `f29f93fd` -> `05328493`

- flake.lock
| [`855f86c2`](https://github.com/Mic92/nix-fast-build/commit/855f86c2993a093a1690832862ab0499ff9b5a83) | `` chore(deps): update flake-parts digest to 49f0870 (#179) `` |
> chore(flake/nix-fast-build): `0f595c2d` -> `855f86c2`

- flake.lock
| [`58d6e5a8`](https://github.com/nix-community/disko/commit/58d6e5a83fff9982d57e0a0a994d4e5c0af441e4) | `` flake.lock: Update `` |
> chore(flake/disko): `a894f281` -> `58d6e5a8`

- flake.lock
| [`3ca2c447`](https://github.com/nix-community/stylix/commit/3ca2c4478a1e984d2007c57467c6986bcdcb2629) | `` firefox: add naho as maintainer (#1442) `` |
| [`a231e38d`](https://github.com/nix-community/stylix/commit/a231e38dfc995be1a42e8af0079e3506fa895f14) | `` firefox: use mkTarget (#1339) ``           |
| [`599c7619`](https://github.com/nix-community/stylix/commit/599c76190ffa51a78b89bdd5b57d23d95935471d) | `` gnome-text-editor: use mkTarget (#1384) `` |
> chore(flake/stylix): `5f841056` -> `3ca2c447`

- flake.lock
| [`6c68e4f2`](https://github.com/lovesegfault/vim-config/commit/6c68e4f2b9560b3ceaa12398feec97f9a6b365bc) | `` chore(flake/nixvim): 8b3a69cf -> d063d0dd `` |
> chore(flake/lovesegfault-vim-config): `05328493` -> `6c68e4f2`

- flake.lock
| [`5adc1a51`](https://github.com/nix-community/home-manager/commit/5adc1a51a2fa8efec9d4eaa4f7df97908cded00d) | `` ci: use flake lock for tests ``                   |
| [`c3297d77`](https://github.com/nix-community/home-manager/commit/c3297d772174eaffe5601822010c18e2f127e2eb) | `` tests: create `no-big` and `ifd` test outputs. `` |
| [`2ef52bca`](https://github.com/nix-community/home-manager/commit/2ef52bcab55dfbf4b7c2b23add43f549c9351bb7) | `` tests: pass …
> chore(flake/home-manager): `c7fdb7e9` -> `5adc1a51`

- flake.lock
| [`aa5e3c03`](https://github.com/nix-community/stylix/commit/aa5e3c03330b8daec5c249d5d58ee970a1afed86) | `` treewide: use mkTarget (batch 3) (#1371) ``      |
| [`ced2af06`](https://github.com/nix-community/stylix/commit/ced2af06228bdc3de98a68cc7baec4ca0dc6f0ed) | `` ci: use ubuntu-24.04 for update-flake (#1444) `` |
> chore(flake/stylix): `3ca2c447` -> `aa5e3c03`

- flake.lock
| [`34a13086`](https://github.com/nix-community/home-manager/commit/34a13086148cbb3ae65a79f753eb451ce5cac3d3) | `` doc: add a missing subcommand (#7199) `` |
> chore(flake/home-manager): `bb846c03` -> `34a13086`

- flake.lock
| Commit                                                                                                 | Message                                       |
| ------------------------------------------------------------------------------------------------------ | --------------------------------------------- |
| [`b07a4c8b`](https://github.com/nix-darwin/nix-darwin/commit/b07a4c8be5aea8db66d4ee1754766d8b9c0aa06c) | `` Fix ShellCheck issue in `nixPath` check `` |
> chore(flake/darwin): `44a7d0e6` -> `d46a0721`

- flake.lock
| Commit                                                                                                 | Message                                                                    |
| ------------------------------------------------------------------------------------------------------ | -------------------------------------------------------------------------- |
| [`f6b29e4a`](https://github.com/nix-darwin/nix-darwin/commit/f6b29e4af88c74b2f19101a5693ea3f2983e326b) | `` defaults: support `AppleKeyboardUIMode = 2` for newer macOS versions `` |
> chore(flake/darwin): `d46a0721` -> `fa6120c3`

- flake.lock
| Commit                                                                                                  | Message                                           |
| ------------------------------------------------------------------------------------------------------- | ------------------------------------------------- |
| [`de3eeb6a`](https://github.com/tinted-theming/schemes/commit/de3eeb6add0a6051bfc717684e36c8c9a78a1812) | `` Add base16 and base24 for 0x96f theme (#61) `` |
> chore(flake/tinted-schemes): `ce495e39` -> `de3eeb6a`

- flake.lock
| [`ffab96a8`](https://github.com/nix-community/home-manager/commit/ffab96a8b4a523c4b5e2645ee09e95a75cbdbfab) | `` qutebrowser: null package support (#7203) ``                 |
| [`3830a21a`](https://github.com/nix-community/home-manager/commit/3830a21aa2313239b582e4e4ac97f0b25243cb7a) | `` xdg.desktopEntries: Update outdated links in docs (#7201) `` |
> chore(flake/home-manager): `34a13086` -> `ffab96a8`

- flake.lock
| [`c0398eba`](https://github.com/nix-community/stylix/commit/c0398ebaa4697adf6006931bf8d7896ae1ee6c69) | `` ci: add 'has: port to stable' label for backports (#1367) ``        |
| [`3945a2d3`](https://github.com/nix-community/stylix/commit/3945a2d3495728e00f545b5e6f60be38e7d0b8c8) | `` flake: include 'until' in rename warning ``                         |
| [`47553c06`](https://github.com/nix-community/stylix/commit/47553c06fb6c8524ca7d3a …
> chore(flake/stylix): `82d9424f` -> `0db3ec02`

- flake.lock
| [`86b95fc1`](https://github.com/nix-community/home-manager/commit/86b95fc1ed2b9b04a451a08ccf13d78fb421859c) | `` aichat: init (#7207) `` |
> chore(flake/home-manager): `ffab96a8` -> `86b95fc1`

- flake.lock
| [`13a45ede`](https://github.com/nix-community/home-manager/commit/13a45ede6c17b5e923dfc18a40a3f646436f4809) | `` aichat: fix config example (#7212) `` |
> chore(flake/home-manager): `86b95fc1` -> `13a45ede`

- flake.lock
| [`68cc9eeb`](https://github.com/nix-community/home-manager/commit/68cc9eeb3875ae9682c04629f20738e1e79d72aa) | `` jellyfin-mpv-shim: merge settings with existing config file ``   |
| [`7707ebb0`](https://github.com/nix-community/home-manager/commit/7707ebb05c6a021e730fdefdb41c2b7e8133251d) | `` jellyfin-mpv-shim: make sure the config file is read properly `` |
| [`09b0a4b0`](https://github.com/nix-community/home-manager/commit/09b0 …
> chore(flake/home-manager): `13a45ede` -> `68cc9eeb`

- flake.lock
| [`4690f1d2`](https://github.com/lovesegfault/vim-config/commit/4690f1d2d11360a7550605cdbd9b2a2709324615) | `` chore(flake/nixvim): 1d872414 -> 635a9e77 `` |
> chore(flake/lovesegfault-vim-config): `583be036` -> `4690f1d2`

- flake.lock
| [`91287a0e`](https://github.com/nix-community/home-manager/commit/91287a0e9d42570754487b7e38c6697e15a9aab2) | `` nixgl: remove alias (#7218) ``                                              |
| [`355c7d09`](https://github.com/nix-community/home-manager/commit/355c7d09ede3335b6642cf1736de3df0d4fdd136) | `` chawan: fix example for settings (#7210) ``                                 |
| …
> chore(flake/home-manager): `68cc9eeb` -> `91287a0e`

- flake.lock
| [`a7030373`](https://github.com/Mic92/nix-fast-build/commit/a7030373e2863e0f648188b7f46e2af67a79496c) | `` chore(deps): update treefmt-nix digest to a05be41 (#181) `` |
> chore(flake/nix-fast-build): `855f86c2` -> `a7030373`

- flake.lock
| Commit                                                                                                 | Message                                                   |
| ------------------------------------------------------------------------------------------------------ | --------------------------------------------------------- |
| [`daf8e228`](https://github.com/nix-darwin/nix-darwin/commit/daf8e22831c197ee52db43aac266d5a8c3d20e38) | `` programs/direnv: add finalPackage readonly option ``   |
| [`fb27326b`](https://github.com/nix-darwin/nix-darwin/commit/fb27326bbcc9ee5cce20f6ea85662a8e855d2278) | `` programs/direnv: fix silent option ``                  |
| [`0e83fc6e`](https://github.com/nix-darwin/nix-darwin/commit/0e83fc6e76e08931f8f87881c0f0ffd0809aa155) | `` feat: add option …
> chore(flake/darwin): `fa6120c3` -> `19346808`

- flake.lock
| [`96482a53`](https://github.com/nix-community/home-manager/commit/96482a538e6103579d254b139759d0536177370b) | `` keychain: warn about deprecated options (#7196) ``         |
| [`c18a7679`](https://github.com/nix-community/home-manager/commit/c18a767948ebe573502b564f88fadec448009b88) | `` zed-editor: userKeymaps default to empty array (#7222) ``  |
| [`812b43b4`](https://github.com/nix-community/home-manager/commit/812b43b45d4807e072b261cd00f3 …
> chore(flake/home-manager): `91287a0e` -> `96482a53`

- flake.lock
| [`2d7d65f6`](https://github.com/nix-community/home-manager/commit/2d7d65f65b61fdfce23278e59ca266ddd0ef0a36) | `` fish: fix the binds.*.erase option (#7186) ``     |
| [`1d595a5b`](https://github.com/nix-community/home-manager/commit/1d595a5b64fb887dd67dd98866af30b1a37b0f7a) | `` zed-editor: allow for nullable package (#7220) `` |
> chore(flake/home-manager): `96482a53` -> `2d7d65f6`

- flake.lock
| Commit                                                                                                      | Message                                                                                    |
| ----------------------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------------ |
| [`06451df4`](https://github.com/nix-community/home-manager/commit/06451df423dd5e555f39857438ffc16c5b765862) | `` ghostty: only source fish shell integration script when shell is interactive (#7228) `` |
| [`627157cc`](https://github.com/nix-community/home-manager/commit/627157ccebb4c82b6f60c2795e848e595d566dc7) | `` ludusavi: modernize and clean-up `` …
> chore(flake/home-manager): `2d7d65f6` -> `06451df4`

- flake.lock
| Commit                                                                                         | Message                                                                                  |
| ---------------------------------------------------------------------------------------------- | ---------------------------------------------------------------------------------------- |
| [`1d2afc0e`](https://github.com/NixOS/nixpkgs/commit/1d2afc0e998abe2a1bb2c6b803ae9154717c3e24) | `` ocamlPackages.wasm: 2.0.1 -> 2.0.2 ``                                                 |
| [`72caf3ac`](https://github.com/NixOS/nixpkgs/commit/72caf3acb7785b0ef5ec48152ccdd2288d44bf29) | `` uudeview: 0.5.20 -> 0.5.20-unstable-2025-03-20, update repo, fixes build (#411084) `` |
| …
> chore(flake/nixpkgs): `910796ca` -> `3e3afe51`

- flake.lock
| [`eb8c7bc1`](https://github.com/Mic92/nix-fast-build/commit/eb8c7bc1619c4e6b232173893e95cb5957e43e85) | `` chore(deps): update flake-parts digest to 9305fe4 (#183) `` |
> chore(flake/nix-fast-build): `dcf6612b` -> `eb8c7bc1`

- flake.lock
| [`b1dae483`](https://github.com/Mic92/nix-fast-build/commit/b1dae483ab7d4139a6297e02b6de9e5d30e43d48) | `` chore(deps): lock file maintenance (#184) `` |
> chore(flake/nix-fast-build): `eb8c7bc1` -> `b1dae483`

- flake.lock
| [`dfa4d1b9`](https://github.com/nix-community/disko/commit/dfa4d1b9c39c0342ef133795127a3af14598017a) | `` flake.lock: Update `` |
> chore(flake/disko): `17d08c65` -> `dfa4d1b9`

- flake.lock
| [`289356d0`](https://github.com/nix-community/stylix/commit/289356d03169542e5ef90f37fafa165e0fe8bae9) | `` treewide: use `mkEnableTargetWith` for dynamic conditions ``           |
| [`67b4644e`](https://github.com/nix-community/stylix/commit/67b4644e700747cb1b6e4748d9f04646c29f7295) | `` stylix: use `mkEnableTargetWith` in `mkTarget` ``                      |
| [`0449dae6`](https://github.com/nix-community/stylix/commit/0449dae6d4 …
> chore(flake/stylix): `5869510e` -> `d73d8f6a`

- flake.lock
| [`427c9604`](https://github.com/nix-community/home-manager/commit/427c96044f11a5da50faf6adaf38c9fa47e6d044) | `` codex: init ``                                     |
| [`7e3d76e7`](https://github.com/nix-community/home-manager/commit/7e3d76e7f71c05d4c2190d94ae1c438f60f1136e) | `` maintainers: add delafthi ``                       |
| [`e9763eb1`](https://github.com/nix-community/home-manager/commit/e9763eb195c1e3d508892993cf112bd75d6fd712) | `` …
> chore(flake/home-manager): `1df816c4` -> `427c9604`

- flake.lock
| [`6d72fc25`](https://github.com/nix-community/stylix/commit/6d72fc259b6f595f5bcf9634bf2f82b76f939a0d) | `` fontconfig: align Home Manager with NixOS and enhance docs (#1292) `` |
| [`54703a46`](https://github.com/nix-community/stylix/commit/54703a462187c83990cc9b671b14771ac63a59fb) | `` neovide: init (#1406) ``                                              |
> chore(flake/stylix): `d73d8f6a` -> `6d72fc25`

- flake.lock
| [`450f06ec`](https://github.com/nix-community/home-manager/commit/450f06ec3cd0d86f67db58a7245db8848773e895) | `` meli: support include statement (#7248) `` |
> chore(flake/home-manager): `427c9604` -> `450f06ec`

- flake.lock
| [`e7fa0e5c`](https://github.com/nix-community/stylix/commit/e7fa0e5cc2336b6b25310d5e49c149f14fdbc1bb) | `` ncspot: use mkTarget (#1333) `` |
> chore(flake/stylix): `6d72fc25` -> `e7fa0e5c`

- flake.lock
| Commit                                                                                                 | Message                                                               |
| ------------------------------------------------------------------------------------------------------ | --------------------------------------------------------------------- |
| [`63c31af3`](https://github.com/nix-darwin/nix-darwin/commit/63c31af37a79bd2847243e679fa5bff2537bffcd) | `` etc: add known hashes for zprofile and zshrc in macOS 26 beta 1 `` |
> chore(flake/darwin): `19346808` -> `e2da3338`

- flake.lock
| [`5b74d930`](https://github.com/nix-community/stylix/commit/5b74d930209bdafc186695a7c22da251f05ab790) | `` k9s: apply upstream breaking changes (#1382) ``                  |
| [`1a471ee9`](https://github.com/nix-community/stylix/commit/1a471ee95e1c7a69f15ce75b5f6b1fe9ede9a778) | `` neovim: combine Neovim, Neovide, NixVim, nvf, and Vim (#1377) `` |
| [`e9eb2308`](https://github.com/nix-community/stylix/commit/e9eb2308ff5b2cec8ff608edf707fef9c5 …
> chore(flake/stylix): `e7fa0e5c` -> `5b74d930`

- flake.lock
| Commit                                                                                                 | Message                                              |
| ------------------------------------------------------------------------------------------------------ | ---------------------------------------------------- |
| [`7c284a65`](https://github.com/nix-darwin/nix-darwin/commit/7c284a650484c90cf928779d77d9faa3f173522e) | `` Avoid confusing users with future deprecations `` |
> chore(flake/darwin): `e2da3338` -> `72c88d59`

- flake.lock
| [`74e9e500`](https://github.com/lovesegfault/vim-config/commit/74e9e500a17788d13c0b5a3b7bdda53bf61483f3) | `` chore(flake/nixvim): 1b08a4d9 -> 18d838e8 `` |
> chore(flake/lovesegfault-vim-config): `967c88d8` -> `74e9e500`

- flake.lock
| Commit                                                                                                | Message                                                                         |
| ----------------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------- |
| [`34393859`](https://github.com/nix-community/stylix/commit/343938594e57483635d6fb34d90c227e8dd46072) | `` doc: remove redundant documentation dummy values (#1318) ``                  |
| [`9724654e`](https://github.com/nix-community/stylix/commit/9724654e8d8ac2e48205efa33497ec1bc9540e62) | `` yazi: update tabs theming style (#1480) ``                                   |
| …
> chore(flake/stylix): `75411fe2` -> `34393859`

- flake.lock
| Commit                                                                                                      | Message                                                                             |
| ----------------------------------------------------------------------------------------------------------- | ----------------------------------------------------------------------------------- |
| [`18f3a0d2`](https://github.com/nix-community/home-manager/commit/18f3a0d21c3739a242aafa17c04c5238bbab5a41) | `` opensnitch-ui: add package option (#7260) ``                                     |
| [`0215073a`](https://github.com/nix-community/home-manager/commit/0215073a704e9b8992d8e59761344d83d8c72e8b) | `` ashell: add module ``                                                            |
| …
> chore(flake/home-manager): `faeab325` -> `18f3a0d2`

- flake.lock
| [`62acc1db`](https://github.com/NixOS/nixos-hardware/commit/62acc1db8ecebdda404eb86a0e3c947f4ec573ea) | `` xiaomi/redmibook/16-pro-2024: remove boot fix ``    |
| [`ddd49b38`](https://github.com/NixOS/nixos-hardware/commit/ddd49b38e4994c200e9d1f135a5d1c5e52ea8932) | `` Forgot README ``                                    |
| [`12b4b1a9`](https://github.com/NixOS/nixos-hardware/commit/12b4b1a92966020c748097e5feaf8a2ce585abe7) | `` Add support for TUXEDO InfinityBook …
> chore(flake/nixos-hardware): `4602f7e1` -> `b328aa78`

- flake.lock
| [`f1113939`](https://github.com/nix-community/home-manager/commit/f1113939873a62f185c18a51f4e45ae66686822b) | `` ashell: minor description improvements `` |
> chore(flake/home-manager): `18f3a0d2` -> `f1113939`

- flake.lock
| [`c79ad485`](https://github.com/nix-community/stylix/commit/c79ad485612a0277c1e25a0bcc562eea11b563d8) | `` doc: add link checking and fix broken links (#1478) `` |
> chore(flake/stylix): `34393859` -> `c79ad485`

- flake.lock
| [`88c842d2`](https://github.com/NixOS/nixos-hardware/commit/88c842d260a3c3bc88ca03b7f54d9e8a2b0c410e) | `` xiaomi/redmibook/15-pro-2021: init `` |
> chore(flake/nixos-hardware): `b328aa78` -> `db030f62`

- flake.lock
| [`77a8b265`](https://github.com/nix-community/stylix/commit/77a8b26520f48305f3b1bacffaa8740dde8afa2a) | `` doc: update docs on building docs (#1499) ``       |
| [`751d6c5d`](https://github.com/nix-community/stylix/commit/751d6c5df0841a0dc213c71f7d43b63abe9449db) | `` doc: Add VSCode color customization tip (#1461) `` |
> chore(flake/stylix): `c79ad485` -> `77a8b265`

- flake.lock
| [`9dd799b7`](https://github.com/lovesegfault/vim-config/commit/9dd799b71bf5a50060fd5926349232e3f0d8b5bc) | `` chore(flake/nixpkgs): 3e3afe51 -> ee930f97 `` |
| [`375067e8`](https://github.com/lovesegfault/vim-config/commit/375067e87784d59e542c7579c062078d32089830) | `` chore(flake/nixvim): 18d838e8 -> e114d442 ``  |
> chore(flake/lovesegfault-vim-config): `74e9e500` -> `9dd799b7`

- flake.lock
| [`c5f34515`](https://github.com/nix-community/home-manager/commit/c5f345153397f62170c18ded1ae1f0875201d49a) | `` atuin: fix docs url (#7252) ``    |
| [`8fabeb9c`](https://github.com/nix-community/home-manager/commit/8fabeb9c142a303e02270c3a3a0d8e00af9d0dfe) | `` fix meli eval warning  (#7267) `` |
> chore(flake/home-manager): `79dfd9aa` -> `c5f34515`

- flake.lock
| [`ad592a0e`](https://github.com/nix-community/stylix/commit/ad592a0e99386474a1826f3d90aeaff97848182c) | `` wezterm: use mkTarget (#1472) `` |
> chore(flake/stylix): `77a8b265` -> `ad592a0e`

- flake.lock
| [`a14e5257`](https://github.com/nix-community/stylix/commit/a14e525723c1c837b2ceacd8a37cba1f0b5e76c2) | `` neovide: guard neovim config (#1495) `` |
> chore(flake/stylix): `d9a4000d` -> `a14e5257`

- flake.lock
| [`cef3e0ad`](https://github.com/nix-community/home-manager/commit/cef3e0adc0b671062c2f911b46d9aacfd7235816) | `` maintainers: update aguirre-matteo email (#7279) ``  |
| [`83030f0e`](https://github.com/nix-community/home-manager/commit/83030f0e4a82a1f39f13fc057e3510938841c761) | `` ci: labeler issues permission (#7278) ``             |
| [`676e40a2`](https://github.com/nix-community/home-manager/commit/676e40a2464783e05146ab5cb196a68230dffc45) | `` …
> chore(flake/home-manager): `04672588` -> `cef3e0ad`

- flake.lock
| [`dfd3d3a3`](https://github.com/lovesegfault/vim-config/commit/dfd3d3a31962e584f914c605e943ae152d4bafba) | `` chore(flake/nixvim): e114d442 -> 7176d51a `` |
> chore(flake/lovesegfault-vim-config): `9dd799b7` -> `dfd3d3a3`

- flake.lock
| [`66523b0e`](https://github.com/nix-community/home-manager/commit/66523b0efe93ce5b0ba96dcddcda15d36673c1f0) | `` thunderbird: support declaration of calendars (#5484) `` |
> chore(flake/home-manager): `cef3e0ad` -> `66523b0e`

- flake.lock
| [`1db3cb41`](https://github.com/nix-community/home-manager/commit/1db3cb415da14c81d8e0fdd3a5edeba82ad13a1f) | `` lib/strings: add PascalCase support for toCaseWithSeperator (#7282) `` |
> chore(flake/home-manager): `66523b0e` -> `1db3cb41`

- flake.lock
| [`0edffd08`](https://github.com/nix-community/home-manager/commit/0edffd088e42fdc48598b37d88eb5345e2ca3937) | `` firefox: allow separators in bookmarks (#7284) `` |
> chore(flake/home-manager): `1db3cb41` -> `0edffd08`

- flake.lock
| [`28eef872`](https://github.com/nix-community/home-manager/commit/28eef8722d1af18ca13e687dbf485e1c653a0402) | `` vscode: fix version checks when using Windsurf (#7285) `` |
> chore(flake/home-manager): `0edffd08` -> `28eef872`

- flake.lock
| [`b1dfd0c0`](https://github.com/nix-community/lanzaboote/commit/b1dfd0c0b2ef63df29f167e13581a4096ef37c2a) | `` chore(deps): lock file maintenance `` |
> chore(flake/lanzaboote): `00292388` -> `38c2addd`

- flake.lock
| Commit                                                                                         | Message                                                    |
| ---------------------------------------------------------------------------------------------- | ---------------------------------------------------------- |
| [`531beac6`](https://github.com/ryantm/agenix/commit/531beac616433bac6f9e2a19feb8e99a22a66baf) | `` Improve `age.identityPaths must be set` error (#335) `` |
> chore(flake/agenix): `4835b1dc` -> `531beac6`

- flake.lock
| [`82323751`](https://github.com/nix-community/stylix/commit/82323751bcd45579c8d3a5dd05531c3c2a78e347) | `` bemenu: add defaultText to fontSize (#1513) `` |
> chore(flake/stylix): `a14e5257` -> `82323751`

- flake.lock
| [`f754e377`](https://github.com/nix-community/home-manager/commit/f754e377dc2da5d34dfea6a5215c21741eaf8930) | `` tests/yazi: manager -> mgr (#7289) `` |
> chore(flake/home-manager): `28eef872` -> `f754e377`

- flake.lock
| [`86384263`](https://github.com/nix-community/home-manager/commit/863842639722dd12ae9e37ca83bcb61a63b36f6c) | `` hyprland: update wiki domain name (#7293) `` |
> chore(flake/home-manager): `0f355844` -> `86384263`

- flake.lock
| Commit                                                                                                 | Message                                                        |
| ------------------------------------------------------------------------------------------------------ | -------------------------------------------------------------- |
| [`82566dd2`](https://github.com/nix-darwin/nix-darwin/commit/82566dd25414241193275f49a645680b23a4c107) | `` programs/ssh: remove `with lib;` ``                         |
| [`a991859d`](https://github.com/nix-darwin/nix-darwin/commit/a991859d1f404e89875e744517fc79bb79f8e0ff) | `` nixos/ssh: undeprecate knownHosts.«name».hostNames ``       |
| [`9d5b27bc`](https://github.com/nix-darwin/nix-darwin/commit/9d5b27bc93a3c845f4e834182c1112b34ead7ffe) | `` …
> chore(flake/darwin): `2f140d6a` -> `0d71cbf8`

- flake.lock
| [`2b231cdc`](https://github.com/nix-community/stylix/commit/2b231cdc9b0537f57be8260463d7e96fe22138ed) | `` treewide: use config in literalExpressions (#1517) `` |
> chore(flake/stylix): `82323751` -> `2b231cdc`

- flake.lock
| [`8c1421ae`](https://github.com/nix-community/stylix/commit/8c1421ae02475a874f2a09cc4a7ad6de63fbc9e8) | `` stylix: honour recent docs to doc renames (#1493) `` |
> chore(flake/stylix): `2b231cdc` -> `8c1421ae`

- flake.lock
| Commit                                                                                                | Message                                                                      |
| ----------------------------------------------------------------------------------------------------- | ---------------------------------------------------------------------------- |
| [`1552a9f4`](https://github.com/NixOS/nixos-hardware/commit/1552a9f4513f3f0ceedcf90320e48d3d47165712) | `` add community meetings to CONTRIBUTING.md ``                              |
| [`e9a0908c`](https://github.com/NixOS/nixos-hardware/commit/e9a0908c620cfd828f477ce815d691cbf4bf86cd) | `` flake.nix: add more distinct common modules import support ``             |
| …
> chore(flake/nixos-hardware): `61837d2a` -> `1552a9f4`

- flake.lock
| [`faa5a34c`](https://github.com/nix-community/stylix/commit/faa5a34c3fd533b289ed082ff2b0e579634e3e4f) | `` discord: use mkTarget (#1511) `` |
> chore(flake/stylix): `8c1421ae` -> `faa5a34c`

- flake.lock
| [`27721407`](https://github.com/nix-community/stylix/commit/27721407de0615e927c84f7c23277628e1d12b67) | `` discord: fix nixcord application condition (#1527) `` |
> chore(flake/stylix): `faa5a34c` -> `27721407`

- flake.lock
| Commit                                                                                                 | Message                                                 |
| ------------------------------------------------------------------------------------------------------ | ------------------------------------------------------- |
| [`f67a4856`](https://github.com/nix-darwin/nix-darwin/commit/f67a4856c36e64b1f3884f6f59dce0ba0ca9dddd) | `` Update homebrew module documentation and examples `` |
> chore(flake/darwin): `0d71cbf8` -> `ff139e81`

- flake.lock
| Commit                                                                                                 | Message                                                       |
| ------------------------------------------------------------------------------------------------------ | ------------------------------------------------------------- |
| [`e2361f44`](https://github.com/nix-darwin/nix-darwin/commit/e2361f44961f8a9cc7bf3c00e5c2d472b7a7b93c) | `` homebrew: allow setting greedy for all casks by default `` |
> chore(flake/darwin): `ff139e81` -> `04a34128`

- flake.lock
| [`39b7903e`](https://github.com/nix-community/home-manager/commit/39b7903eaba5579046f7069b9d85d3ef4f2f972c) | `` helix: don't ignore extraConfig when no other settings (#7302) `` |
> chore(flake/home-manager): `86384263` -> `39b7903e`

- flake.lock
| Commit                                                                                                 | Message                                                               |
| ------------------------------------------------------------------------------------------------------ | --------------------------------------------------------------------- |
| [`f2457a22`](https://github.com/nix-darwin/nix-darwin/commit/f2457a22c8cce48c2f8ede0935037c4d2cf8de39) | `` systems.defaults.alf: deprecate ``                                 |
| [`caa59bf5`](https://github.com/nix-darwin/nix-darwin/commit/caa59bf50a430d2ba18ff4d428c267561b686072) | `` networking.applicationFirewall: init ``                            |
| [`30845bee`](https://github.com/nix-darwin/nix-darwin/commit/30845beee0448bea77a7b …
> chore(flake/darwin): `04a34128` -> `1dd19f19`

- flake.lock
| [`873c5b2d`](https://github.com/nix-community/home-manager/commit/873c5b2dc5c9387bf67e59a12abc4de12a4b8697) | `` way-displays: use `mkOptionDefault` in `systemd.variables` (#7306) `` |
> chore(flake/home-manager): `05b8c950` -> `873c5b2d`

- flake.lock
| [`86402a17`](https://github.com/nix-community/home-manager/commit/86402a17b6c67b07c5536354da5d56c14196de46) | `` treewide: flatten single file modules `` |
| [`bda9deb7`](https://github.com/nix-community/home-manager/commit/bda9deb791b29454d49f8f5c35198e2b23f7751a) | `` modules: allow root level nix files ``   |
| [`f5098b07`](https://github.com/nix-community/home-manager/commit/f5098b074051d1ae0e919adf434a60fc3f23347b) | `` programs/hyprpanel: init (#7303) ``      |
> chore(flake/home-manager): `873c5b2d` -> `86402a17`

- flake.lock
| [`d07e9cce`](https://github.com/nix-community/home-manager/commit/d07e9cceb4994ed64a22b9b36f8b76923e87ac38) | `` docs: add note about importing modules (#7315) ``         |
| [`c9d8158b`](https://github.com/nix-community/home-manager/commit/c9d8158bc56923013fa9a4346ba3e273f3b956b3) | `` tests/aerospace: test launchd agent ``                    |
| [`d33444e6`](https://github.com/nix-community/home-manager/commit/d33444e63a88f70feccd99971c442dc9 …
> chore(flake/home-manager): `86402a17` -> `d07e9cce`

- flake.lock
| Commit                                                                                                | Message                  |
| ----------------------------------------------------------------------------------------------------- | ------------------------ |
| [`b8c7eb0c`](https://github.com/cachix/git-hooks.nix/commit/b8c7eb0c7e0817c78804947921b419ca50a509f0) | `` feat: add uv hooks `` |
> chore(flake/git-hooks): `fae816c5` -> `16ec914f`

- flake.lock
| [`ff31a467`](https://github.com/nix-community/home-manager/commit/ff31a4677c1a8ae506aa7e003a3dba08cb203f82) | `` fix(zed): support preexisting JSON5 settings (#7317) `` |
> chore(flake/home-manager): `951f0b30` -> `ff31a467`

- flake.lock
| [`57c6e6e5`](https://github.com/lovesegfault/vim-config/commit/57c6e6e52aee84b3398f43a3c5a268bac49c9267) | `` chore(flake/git-hooks): fae816c5 -> 16ec914f `` |
| [`a82b8f00`](https://github.com/lovesegfault/vim-config/commit/a82b8f001d600ee2eea61788ac64b209cb77aaf4) | `` chore(flake/nixvim): 1f3e5741 -> 6a15c2ff ``    |
> chore(flake/lovesegfault-vim-config): `aceb7d8d` -> `57c6e6e5`

- flake.lock
| [`37b8c5f6`](https://github.com/nix-community/stylix/commit/37b8c5f68086f36a109074c3fedebbbf8c20ecda) | `` waybar: fix attribute 'default' missing (#1541) ``           |
| [`1fc22894`](https://github.com/nix-community/stylix/commit/1fc22894545f5adf915e245b3c3e92639fd70f64) | `` stylix: extract testbed modules to `autoload.nix` (#1520) `` |
| [`edcecc02`](https://github.com/nix-community/stylix/commit/edcecc02e6f113758f401b2248d739f28c063478) | `` …
> chore(flake/stylix): `67a6479c` -> `37b8c5f6`

- flake.lock
| Commit                                                                                                | Message                                                                 |
| ----------------------------------------------------------------------------------------------------- | ----------------------------------------------------------------------- |
| [`a6eff346`](https://github.com/nix-community/stylix/commit/a6eff346d8e346b5a8e7eb3f8f7c4b36c9597a3c) | `` treewide: adjust notification colors to represent urgency (#1253) `` |
> chore(flake/stylix): `37b8c5f6` -> `a6eff346`

- flake.lock
| [`83c4da29`](https://github.com/nix-community/disko/commit/83c4da299c1d7d300f8c6fd3a72ac46cb0d59aae) | `` flake.lock: Update `` |
> chore(flake/disko): `8fd2d6c7` -> `83c4da29`

- flake.lock
| [`8f9623ef`](https://github.com/Mic92/nix-fast-build/commit/8f9623efceac21f432fdd83abbd3ab979ea8a39a) | `` chore(deps): lock file maintenance (#185) ``                |
| [`1bf771f2`](https://github.com/Mic92/nix-fast-build/commit/1bf771f28e27fa1ae3a8c9e11dd3173b48e45a0e) | `` chore(deps): update treefmt-nix digest to ac8e6f3 (#187) `` |
> chore(flake/nix-fast-build): `b1dae483` -> `8f9623ef`

- flake.lock
| [`36a66aa2`](https://github.com/lovesegfault/vim-config/commit/36a66aa268db51724db5531387645f0a7a98931c) | `` chore(flake/treefmt-nix): a05be418 -> ac8e6f32 `` |
> chore(flake/lovesegfault-vim-config): `f35b588a` -> `36a66aa2`

- flake.lock
| [`3a09d3f5`](https://github.com/nix-community/stylix/commit/3a09d3f5cb940fa4142a2f3415b508a8be92b721) | `` rofi: fix attribute 'size' missing (#1553) ``         |
| [`8c4b2ebf`](https://github.com/nix-community/stylix/commit/8c4b2ebfb83010e5b345cba4afcbe499603f6861) | `` ci: commit as stylix-automation in updates (#1547) `` |
> chore(flake/stylix): `713f8dae` -> `3a09d3f5`

- flake.lock
| [`76d0c31f`](https://github.com/nix-community/home-manager/commit/76d0c31fce2aa0c71409de953e2f9113acd5b656) | `` formatter: add deadnix (#7331) `` |
> chore(flake/home-manager): `da077f20` -> `76d0c31f`

- flake.lock
| [`f0f78780`](https://github.com/lovesegfault/vim-config/commit/f0f78780f6884160707c6a626ece9beb4f4e19a6) | `` chore(flake/nixpkgs): 4b1164c3 -> 30e2e285 `` |
| [`58cd07c1`](https://github.com/lovesegfault/vim-config/commit/58cd07c10729d1e1ed873f26c383d278a57f415b) | `` chore(flake/nixvim): c39f5f39 -> ceb52aec ``  |
> chore(flake/lovesegfault-vim-config): `a0a9a026` -> `f0f78780`

- flake.lock
| [`f6deff17`](https://github.com/nix-community/home-manager/commit/f6deff178cc4d6049d30785dbfc831e6c6e3a219) | `` quickshell: add module (#7316) ``                                            |
| [`cab8104e`](https://github.com/nix-community/home-manager/commit/cab8104e9236fab1eb9a702165454ffed353c20f) | `` home-manager: add repl subcommand (#5600) ``                                 |
| …
> chore(flake/home-manager): `76d0c31f` -> `f6deff17`

- flake.lock
| Commit                                                                                                | Message                                                                             |
| ----------------------------------------------------------------------------------------------------- | ----------------------------------------------------------------------------------- |
| [`4ead8043`](https://github.com/nix-community/stylix/commit/4ead8043f70cc3b951e704a1f6e40c8a10230e61) | `` zed: fix homepage URL (#1561) ``                                                 |
| [`a0082d08`](https://github.com/nix-community/stylix/commit/a0082d087eabaf710977f22b06984329145b526c) | `` nixos-icons: modify `nix-snowflake-colours.svg` to match color scheme (#1522) `` |
> chore(flake/stylix): `3a09d3f5` -> `4ead8043`

- flake.lock
| [`0f21ed51`](https://github.com/nix-community/home-manager/commit/0f21ed5182a158d2f84e9136f6bf8539fd9a6890) | `` bash: change sessionVariables to attrsOf ... (#7300) `` |
> chore(flake/home-manager): `f6deff17` -> `0f21ed51`

- flake.lock
| [`78fc50f1`](https://github.com/nix-community/home-manager/commit/78fc50f1cf8e57a974ff4bfe654563fce43d6289) | `` direnv: fix nushell cell-path handling (#7339) ``               |
| [`ee2189cb`](https://github.com/nix-community/home-manager/commit/ee2189cb2f6c9e2b9c734a839faa20ed2ba8b577) | `` gh: insert empty helper when using credential helper (#7347) `` |
> chore(flake/home-manager): `0f21ed51` -> `78fc50f1`

- flake.lock
| [`4bc15ef1`](https://github.com/nix-community/stylix/commit/4bc15ef13c970981e37506491e18d1158af9a70c) | `` blender: use mkTarget (#1509) ``                         |
| [`73b7d0f3`](https://github.com/nix-community/stylix/commit/73b7d0f30039b6e51a02a1cc29215565107ed6c7) | `` stylix: guard home-manager-integration config (#1494) `` |
> chore(flake/stylix): `4ead8043` -> `4bc15ef1`

- flake.lock
| [`479f8889`](https://github.com/nix-community/home-manager/commit/479f8889675770881033878a1c114fbfc6de7a4d) | `` bash: support path in sessionVariables again (#7354) `` |
> chore(flake/home-manager): `96354906` -> `479f8889`

- flake.lock
| [`e96a8a32`](https://github.com/nix-community/home-manager/commit/e96a8a325cf23538a7f58b9335b4c4c0b393bacf) | `` ci: conditional test step runs (#7358) ``                |
| [`5d2f3e3e`](https://github.com/nix-community/home-manager/commit/5d2f3e3e7fbb2cd8cab8b5f9e51526b1269645b9) | `` ci: fix update-maintainers reference location (#7357) `` |
| [`77bb9e03`](https://github.com/nix-community/home-manager/commit/77bb9e033b500a7111cee096555d510b715a …
> chore(flake/home-manager): `479f8889` -> `e96a8a32`

- flake.lock
| [`5b257989`](https://github.com/nix-community/stylix/commit/5b257989a8337dddc22aa04a70d3665d0384abef) | `` gnome: update to GNOME 48.2 (#1559) `` |
> chore(flake/stylix): `4bc15ef1` -> `5b257989`

- flake.lock
| [`2e9412e7`](https://github.com/lovesegfault/vim-config/commit/2e9412e7742c225689c5b428714badb611a4e749) | `` chore(flake/nixpkgs): 30e2e285 -> 3016b4b1 ``     |
| [`dbbf4657`](https://github.com/lovesegfault/vim-config/commit/dbbf46575e3838a675b2f229186b603f783141b8) | `` chore(flake/flake-parts): 9305fe4e -> 77826244 `` |
> chore(flake/lovesegfault-vim-config): `f0f78780` -> `2e9412e7`

- flake.lock
| [`29d717aa`](https://github.com/nix-community/home-manager/commit/29d717aab5189b3383d965928823ddac8a95e8f3) | `` ci: tests fetch nixpkgs from flake.lock rev ``              |
| [`212f4a4f`](https://github.com/nix-community/home-manager/commit/212f4a4fb20449d51bbc403e3d140778aab4d18a) | `` ci: update-maintainers fetch nixpkgs from flake.lock rev `` |
| [`121b430d`](https://github.com/nix-community/home-manager/commit/121b430df7b5c5eeb9d37dff …
> chore(flake/home-manager): `e96a8a32` -> `29d717aa`

- flake.lock
| [`3b622ae6`](https://github.com/NixOS/nixos-hardware/commit/3b622ae6e613bf0b59bd142394ee86ed62cd2a60) | `` Add System76 Thelio Mega module ``             |
| [`a724614b`](https://github.com/NixOS/nixos-hardware/commit/a724614b86a2a67f7dbb3873942dcd0561106102) | `` xiaomi/redmibook/15-pro-2021: fix flake.nix `` |
> chore(flake/nixos-hardware): `f49bb3b4` -> `497ae135`

- flake.lock
| [`df122690`](https://github.com/nix-community/home-manager/commit/df12269039dcf752600b1bcc176bacf2786ec384) | `` maintainers: update all-maintainers.nix (#7361) `` |
> chore(flake/home-manager): `29d717aa` -> `df122690`

- flake.lock
| [`7c455533`](https://github.com/nix-community/home-manager/commit/7c455533409411b4053bb6d7db71eb35e0544254) | `` mpvpaper: fix eval if no settings are defined (#7370) `` |
| [`3d243d4a`](https://github.com/nix-community/home-manager/commit/3d243d4a16cafe855df585b3030aa99261a27a86) | `` ci: fix which branch to show on pr (#7368) ``            |
| [`77027882`](https://github.com/nix-community/home-manager/commit/77027882a7f637f84f7c221406b75f1463f5 …
> chore(flake/home-manager): `df122690` -> `7c455533`

- flake.lock
| Commit                                                                                                | Message                     |
| ----------------------------------------------------------------------------------------------------- | --------------------------- |
| [`3f71d154`](https://github.com/nix-community/stylix/commit/3f71d154867b457adbef04b4982e78b5dc225e62) | `` ashell: init `(#1552) `` |
> chore(flake/stylix): `5b257989` -> `3f71d154`

- flake.lock
| [`43b16374`](https://github.com/lovesegfault/vim-config/commit/43b163742cf32a4349329b4bcb1f7595ec5dbfd2) | `` chore(flake/nixvim): ceb52aec -> 239d331b `` |
> chore(flake/lovesegfault-vim-config): `2e9412e7` -> `43b16374`

- flake.lock
| [`a5b56720`](https://github.com/nix-community/home-manager/commit/a5b56720841121d2189c011e445c4be4c943bab5) | `` kitty: add config change signal on darwin (#7375) `` |
| [`89af52d9`](https://github.com/nix-community/home-manager/commit/89af52d9a893af013f5f4c1d2d56912106827153) | `` tests/firefox: add extension user.js test ``         |
| [`1b25908d`](https://github.com/nix-community/home-manager/commit/1b25908d1dc6832c3cced1aba29b6ff932b6a0bd) | `` …
> chore(flake/home-manager): `25f003f8` -> `a5b56720`

- flake.lock
| [`d21cfb36`](https://github.com/nix-community/stylix/commit/d21cfb364a78ad72935625e79b8c5d497f0b7616) | `` ashell: fix use of opacity option (#1576) `` |
> chore(flake/stylix): `3f71d154` -> `d21cfb36`

- flake.lock
| [`426b405d`](https://github.com/nix-community/home-manager/commit/426b405d979d893832549b95f23c13537c65d244) | `` ci: add validation workflow for maintainers list `` |
| [`66de606f`](https://github.com/nix-community/home-manager/commit/66de606f48f789b0a407d842714de8dd01893dc5) | `` ci: update all-maintainers on merge ``              |
> chore(flake/home-manager): `a5b56720` -> `426b405d`

- flake.lock
| [`1fa73bb2`](https://github.com/nix-community/home-manager/commit/1fa73bb2cc39e250eb01e511ae6ac83bfbf9f38c) | `` fix(service/gpg-agent): allow SSH ForwardAgent compatibility (#7355) `` |
| [`b182e64c`](https://github.com/nix-community/home-manager/commit/b182e64c01aa4e61a007691525a3ea498a9aee63) | `` zed-editor: survive if previous files are not JSON5 (#7351) ``          |
> chore(flake/home-manager): `426b405d` -> `1fa73bb2`

- flake.lock
| [`402333d5`](https://github.com/nix-community/home-manager/commit/402333d5ec2f9eed0f2584555936361f39d2f93e) | `` ci: concurrency protect tag flow ``                     |
| [`03c3576f`](https://github.com/nix-community/home-manager/commit/03c3576f8b7e3d2154fba3f450e2bfd942024e1e) | `` ci: remove unneeded reviewers ``                        |
| [`7582cbfa`](https://github.com/nix-community/home-manager/commit/7582cbfabce2ff1626083f1c73a2e3c74ee4cf40 …
> chore(flake/home-manager): `28639e64` -> `402333d5`

- flake.lock
| [`83f97881`](https://github.com/nix-community/home-manager/commit/83f978812c37511ef2ffaf75ffa72160483f738a) | `` podman: support mounts configuration (#7377) `` |
> chore(flake/home-manager): `402333d5` -> `83f97881`

- flake.lock
| [`85d84607`](https://github.com/nix-community/stylix/commit/85d84607b2d4a28178f2ec0238ac5eed8e39cd71) | `` flake: sort pre-commit hooks and formatters (#1586) ``                 |
| [`732c666b`](https://github.com/nix-community/stylix/commit/732c666ba54a724bb90d76a1b6f1417bc4823235) | `` ci: fix dependabot backport label (#1585) ``                           |
| [`127fe6cc`](https://github.com/nix-community/stylix/commit/127fe6cc3d …
> chore(flake/stylix): `3c73dee2` -> `85d84607`

- flake.lock
| [`7d9e3c35`](https://github.com/nix-community/home-manager/commit/7d9e3c35f0d46f82bac791d76260f15f53d83529) | `` all-maintainers: regenerate with latest changes ``                |
| [`412c545b`](https://github.com/nix-community/home-manager/commit/412c545bb6df640c795177b02f79831087132267) | `` extract-maintainers-meta: simplify ``                             |
| [`f6d11046`](https://github.com/nix-community/home-manager/commit/ …
> chore(flake/home-manager): `83f97881` -> `7d9e3c35`

- flake.lock
| [`090176aa`](https://github.com/lovesegfault/vim-config/commit/090176aa03576f25f025389d908792d44ac185b0) | `` chore(deps): bump DeterminateSystems/nix-installer-action from 17 to 18 `` |
> chore(flake/lovesegfault-vim-config): `43b16374` -> `090176aa`

- flake.lock
| Commit                                                                                                | Message                                                              |
| ----------------------------------------------------------------------------------------------------- | -------------------------------------------------------------------- |
| [`606944b1`](https://github.com/nix-community/stylix/commit/606944b16862d43934fec3311f9cb9f478b7f99b) | `` rofi: fix mkTarget usage (#1593) ``                               |
| [`6b2898a6`](https://github.com/nix-community/stylix/commit/6b2898a6b7d6fc1956d808d285a1b4ceaf0ca56e) | `` mako: add testbed (#1192) ``                                      |
| [`dea0337e`](https://github.com/nix-community/stylix/commit/dea0337e0bffeeeb941ca6caffb44e …
> chore(flake/stylix): `85d84607` -> `606944b1`

- flake.lock
| [`57d1027e`](https://github.com/nix-community/home-manager/commit/57d1027e1eaf1220342248ff18d34f42b0beea7b) | `` aerc: allow config sections to be lines (#7280) `` |
> chore(flake/home-manager): `7d9e3c35` -> `57d1027e`

- flake.lock
| [`36c57c6a`](https://github.com/nix-community/home-manager/commit/36c57c6a1d03a5efbf5e23c04dbe21259d25f992) | `` lib/deprecations: add ignore parameter to remapAttrsRecursive `` |
| [`650a38eb`](https://github.com/nix-community/home-manager/commit/650a38ebe819d439ece41b5a1c510b3244896265) | `` ashell: support yaml and toml config ``                          |
| [`f62e9a81`](https://github.com/nix-community/home-manager/commit/f62e …
> chore(flake/home-manager): `57d1027e` -> `36c57c6a`

- flake.lock
| Commit                                                                                                      | Message                                                                             |
| ----------------------------------------------------------------------------------------------------------- | ----------------------------------------------------------------------------------- |
| [`f117b383`](https://github.com/nix-community/home-manager/commit/f117b383dd591fd579bce5ee7bac07a3fdc1d050) | `` numbat: Allow specifying a path for initFile ``                                  |
| [`26d405da`](https://github.com/nix-community/home-manager/commit/26d405da4179c7dafc0a84e611edfa2f5ddf7faa) | `` numbat: Add initFile option ``                                                   |
| …
> chore(flake/home-manager): `36c57c6a` -> `f117b383`

- flake.lock
| [`7c250bf6`](https://github.com/NixOS/nixpkgs/commit/7c250bf676fb448a2ff187ac8c69e1f088211762) | `` python3Packages.vector: skip failing tests ``                                  |
| [`521e3e5e`](https://github.com/NixOS/nixpkgs/commit/521e3e5eca0d2f076fb4472ef5a36011b1a15559) | `` kdePackages.qt3d: unvendor assimp ``                                           |
| [`2d3d9f49`](https://github.com/NixOS/nixpkgs/commit/2d3d9f497192a …
> chore(flake/nixpkgs): `3016b4b1` -> `5c724ed1`

- flake.lock
| [`e2e5f485`](https://github.com/lovesegfault/vim-config/commit/e2e5f48506d6ea5004d975a0f5dd06780505cbba) | `` chore(flake/nixpkgs): 3016b4b1 -> 5c724ed1 `` |
> chore(flake/lovesegfault-vim-config): `090176aa` -> `e2e5f485`

- flake.lock
| [`af8a8841`](https://github.com/nix-community/home-manager/commit/af8a884164bb50ad34c09719bdbdb2a1b01b917c) | `` kubeswitch: add module ``     |
| [`92db5be8`](https://github.com/nix-community/home-manager/commit/92db5be8e17c5150c46a2ca8f55a85d20df75643) | `` maintainers: add m0nsterrr `` |
| [`5a49fe44`](https://github.com/nix-community/home-manager/commit/5a49fe448e81ee05ab48ed3189109b322237ddbf) | `` opencode: init (#7320) ``     |
> chore(flake/home-manager): `f117b383` -> `af8a8841`

- flake.lock
| [`50ed5ddd`](https://github.com/nix-community/stylix/commit/50ed5ddd1072a6b10e6368cc338d759ffa02df9b) | `` {neovim, vim}: add testbeds (#1571) `` |
| [`1bd6d031`](https://github.com/nix-community/stylix/commit/1bd6d031acacf64cef2b45a570d114f16c4b9ae6) | `` rio: use mkTarget (#1599) ``           |
| [`aca5e11a`](https://github.com/nix-community/stylix/commit/aca5e11a1fc8cf5b9aa73ba64433c64e06f328ff) | `` rio: add testbed (#1600) ``            |
> chore(flake/stylix): `606944b1` -> `50ed5ddd`

- flake.lock
| [`85686025`](https://github.com/nix-community/nix-index-database/commit/85686025ba6d18df31cc651a91d5adef63378978) | `` update generated.nix to release 2025-07-06-034719 `` |
| [`d3de5a18`](https://github.com/nix-community/nix-index-database/commit/d3de5a18d3c1efa9ea05deeda071ff06c8fe39dc) | `` flake.lock: Update ``                                |
> chore(flake/nix-index-database): `9c932ae6` -> `85686025`

- flake.lock
| [`8b0180dd`](https://github.com/nix-community/home-manager/commit/8b0180dde1d6f4cf632e046309e8f963924dfbd0) | `` maintainers: update all-maintainers.nix (#7392) `` |
> chore(flake/home-manager): `af8a8841` -> `8b0180dd`

- flake.lock
| [`557e1623`](https://github.com/lovesegfault/vim-config/commit/557e16230fba31122c0ded286366f9cfc8ae04ca) | `` chore(flake/nixvim): 239d331b -> ef0fa015 `` |
> chore(flake/lovesegfault-vim-config): `e2e5f485` -> `557e1623`

- flake.lock
| [`b4486ff4`](https://github.com/nix-community/home-manager/commit/b4486ff44addd453a64fd8c176ab2fd7ad3f6eb3) | `` mkFirefoxModule: add extension settings example to policies (#7397) ``      |
| [`153e680c`](https://github.com/nix-community/home-manager/commit/153e680c4263fbd8fa416ef5b8ef13397e02fd2f) | `` firefox: add release option (#6784) ``                                      |
| …
> chore(flake/home-manager): `8b0180dd` -> `b4486ff4`

- flake.lock
| [`9aa58bf0`](https://github.com/lovesegfault/vim-config/commit/9aa58bf028333251bccf9efc4179c564819e3c74) | `` chore(flake/nixvim): ef0fa015 -> 28f818b5 `` |
> chore(flake/lovesegfault-vim-config): `557e1623` -> `9aa58bf0`

- flake.lock
| [`148c3836`](https://github.com/Mic92/nix-fast-build/commit/148c3836eab55ba69c10e5d7e85d643dabd88b5b) | `` chore(deps): lock file maintenance (#190) `` |
> chore(flake/nix-fast-build): `64b4f816` -> `148c3836`

- flake.lock
| Commit                                                                                                | Message                                                                     |
| ----------------------------------------------------------------------------------------------------- | --------------------------------------------------------------------------- |
| [`5259682c`](https://github.com/nix-community/stylix/commit/5259682ce58d935f248297bf1c9793a5cee0787e) | `` cava: add testbed (#1617) ``                                             |
| [`a5c1532a`](https://github.com/nix-community/stylix/commit/a5c1532ab8bf9566331f83be91517e02132f3d99) | `` flake: partition dev inputs (#1289) ``                                   |
| [`a294d8b2`](https://github.com/nix-community/stylix/commit/a2 …
> chore(flake/stylix): `50ed5ddd` -> `5259682c`

- flake.lock
| Commit                                                                                                      | Message                                                                                  |
| ----------------------------------------------------------------------------------------------------------- | ---------------------------------------------------------------------------------------- |
| [`fd9e55f5`](https://github.com/nix-community/home-manager/commit/fd9e55f5fac45a26f6169310afca64d56b681935) | `` tests/firefox: add bookmark policy to profile bookmarks test ``                       |
| [`753ea0b3`](https://github.com/nix-community/home-manager/commit/753ea0b3240ae3d64923dc77e33aa5c1be06b62f) | `` librewolf: allow bookmark configuration `` …
> chore(flake/home-manager): `b4486ff4` -> `fd9e55f5`

- flake.lock
| [`8f408a61`](https://github.com/NixOS/nixpkgs/commit/8f408a61f1eabd6195752574acc88c766c6600d0) | `` pineapple-pictures: 1.0.0 -> 1.1.0 ``                                          |
| [`9cdcdf17`](https://github.com/NixOS/nixpkgs/commit/9cdcdf177e969ac0e8e1ea91b960223812214451) | `` python313Packages.ciscoconfparse2: relax tomlkit ``                            |
| [`81f1a10d`](https://github.com/NixOS/nixpkgs/commit/81f1a10daee32 …
> chore(flake/nixpkgs): `5c724ed1` -> `1fd8bada`

- flake.lock
| [`bf0ef81c`](https://github.com/nix-community/stylix/commit/bf0ef81c8fcc30c32db9dab32d379f8d9db835e4) | `` ci: fix testbed labeling (#1606) ``         |
| [`c538d1a3`](https://github.com/nix-community/stylix/commit/c538d1a3571386eaaca31aef7bb5fd5c155327b0) | `` regreet: use mkTarget (#1598) ``            |
| [`ad13dd4e`](https://github.com/nix-community/stylix/commit/ad13dd4eb2747b0ba10bc0f1f23bbe2f52f9c60e) | `` spicetify: use mkTarget ``                  |
| …
> chore(flake/stylix): `5259682c` -> `bf0ef81c`

- flake.lock
| [`8f3259db`](https://github.com/nix-community/stylix/commit/8f3259dbc57c8ee871492fde80f77468826bbd63) | `` flake/dev: use treefmt flake parts module (#1551) `` |
> chore(flake/stylix): `2a1ad278` -> `8f3259db`

- flake.lock
| [`206ed3c7`](https://github.com/nix-community/home-manager/commit/206ed3c71418b52e176f16f58805c96e84555320) | `` neomutt: improve error when no way to send mail `` |
> chore(flake/home-manager): `bec8ff39` -> `206ed3c7`

- flake.lock
| [`480649bb`](https://github.com/nix-community/stylix/commit/480649bbdf8ef423c84a7152ceadf22839a5acbb) | `` mako: fix testbed name (#1653) ``                                   |
| [`9028a74f`](https://github.com/nix-community/stylix/commit/9028a74f88d5ed31f4cff3483f3c143346ce43ea) | `` stylix: use isFunction (#1652) ``                                   |
| [`4eadb250`](https://github.com/nix-community/stylix/commit/4eadb2503b80f0251ff2c4 …
> chore(flake/stylix): `7b9a528d` -> `480649bb`

- flake.lock
| [`d81cb050`](https://github.com/nix-community/home-manager/commit/d81cb050f5530fc84aa0ddb421d50722ee662600) | `` hyprshell: add module (#7409) `` |
| [`50330593`](https://github.com/nix-community/home-manager/commit/50330593f33d0b873e0b6b05294164d093c0992a) | `` flake.lock: Update (#7419) ``    |
> chore(flake/home-manager): `206ed3c7` -> `d81cb050`

- flake.lock
| [`19972366`](https://github.com/lovesegfault/vim-config/commit/199723666020b34361e9e01048d385972136f13b) | `` chore(flake/nixvim): 2e24f8e6 -> b728cf43 `` |
> chore(flake/lovesegfault-vim-config): `5b3e0af6` -> `19972366`

- flake.lock
| [`fab659b3`](https://github.com/nix-community/home-manager/commit/fab659b346c0d4252208434c3c4b3983a4b38fec) | `` trippy: add module (#7426) ``                           |
| [`3978bcd6`](https://github.com/nix-community/home-manager/commit/3978bcd6961847385121db30c58dbd444d4a73df) | `` thunderbird: configure SMTP and GPG for aliases ``      |
| [`d52abd5b`](https://github.com/nix-community/home-manager/commit/d52abd5b525e2f4ccc57b07db9759d1a147472fd …
> chore(flake/home-manager): `d81cb050` -> `fab659b3`

- flake.lock
| Commit                                                                                                | Message                                                            |
| ----------------------------------------------------------------------------------------------------- | ------------------------------------------------------------------ |
| [`0150050d`](https://github.com/nix-community/stylix/commit/0150050d6eed373b04fd85e08bd2ae7b5cc8d3b2) | `` wayfire: mixup between wayfire and wf-shell settings (#1670) `` |
| [`458d2835`](https://github.com/nix-community/stylix/commit/458d283547015183db68b82f17244ad9bbce0ddf) | `` spicetify: make background color different from text (#1626) `` |
> chore(flake/stylix): `d395780b` -> `0150050d`

- flake.lock
| Commit                                                                                                            | Message                               |
| ----------------------------------------------------------------------------------------------------------------- | ------------------------------------- |
| [`1dabe081`](https://github.com/nix-community/nix-index-database/commit/1dabe08190253287d1238059b46487911bf5e70a) | `` Use module-instantiated nixpkgs `` |
> chore(flake/nix-index-database): `85686025` -> `ad29e296`

- flake.lock
| [`392ddb64`](https://github.com/nix-community/home-manager/commit/392ddb642abec771d63688c49fa7bcbb9d2a5717) | `` home-manager: add flake support for repl command (#7439) ``                 |
| [`7c6f7377`](https://github.com/nix-community/home-manager/commit/7c6f7377ccca88c45a28875e7755c38b604c5ff3) | `` vscode: enable defining `mcp.json` separate from `settings.json` (#7441) `` |
> chore(flake/home-manager): `3976e050` -> `392ddb64`

- flake.lock
| [`f2795aa0`](https://github.com/nix-community/home-manager/commit/f2795aa053ef11f958fba49aef15a5c4d9734c02) | `` ci: tag-maintainers further refactoring (#7446) `` |
> chore(flake/home-manager): `ea24675e` -> `f2795aa0`

- flake.lock
| [`12201a43`](https://github.com/nix-community/nix-index-database/commit/12201a430ee613bc720cef21a130b416cb1b5108) | `` flake.lock: Update `` |
> chore(flake/nix-index-database): `deff7a9a` -> `12201a43`

- flake.lock
| [`05752c77`](https://github.com/nix-community/stylix/commit/05752c77acc9dc7ff7454c6fe6da829e3a40e548) | `` gtksourceview: init module (#958) `` |
> chore(flake/stylix): `0da583a3` -> `05752c77`

- flake.lock
| [`a950a3f5`](https://github.com/nix-community/stylix/commit/a950a3f529e1952a7ddf2af138b90a99edf41fe5) | `` wayfire: remove optional toString (#1658) `` |
> chore(flake/stylix): `05752c77` -> `a950a3f5`

- flake.lock
| [`bf893ad4`](https://github.com/nix-community/home-manager/commit/bf893ad4cbf46610dd1b620c974f824e266cd1df) | `` tests: re-add module argument `` |
> chore(flake/home-manager): `fc253984` -> `bf893ad4`

- flake.lock
| Commit                                                                                                | Message                                                                               |
| ----------------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------- |
| [`f6c5aaa4`](https://github.com/nix-community/stylix/commit/f6c5aaa4f8b70ec0bf995be43311c38be3131776) | `` stylix: add missing trailing period in mkEnableTargetWith's description (#1681) `` |
| [`2947a837`](https://github.com/nix-community/stylix/commit/2947a83755d206553fb88116058f5322f3bc2d0e) | `` gtksourceview: don't overlay all of gnome2 (#1680) ``                              |
> chore(flake/stylix): `a950a3f5` -> `f6c5aaa4`

- flake.lock
| [`1a4d8ffd`](https://github.com/nix-community/home-manager/commit/1a4d8ffd320c2393b72e7ebc5b647122d5703056) | `` gurk-rs: fix missing s in home.packages (#7467) `` |
| [`7969ed8b`](https://github.com/nix-community/home-manager/commit/7969ed8baac8363b32775c5f55e132668bab8123) | `` gurk-rs: add module (#7466) ``                     |
> chore(flake/home-manager): `bf893ad4` -> `1a4d8ffd`

- flake.lock
| [`d683e35f`](https://github.com/nix-community/stylix/commit/d683e35fa5ec8bbfd45d52e4b53c7b91f7b38d06) | `` stylix: use lib.warn instead of builtins.warn (#1676) ``            |
| [`218d4424`](https://github.com/nix-community/stylix/commit/218d4424b0634f8e9e3af92df7ca807bda529255) | `` treewide: remove redundant stylix.image Nix store copies (#1659) `` |
> chore(flake/stylix): `f6c5aaa4` -> `d683e35f`

- flake.lock
| [`06a33c6e`](https://github.com/lovesegfault/vim-config/commit/06a33c6eb8224361c5a0747783bf59ef956e95ac) | `` chore(flake/nixvim): 4b068551 -> eeec7f7c `` |
> chore(flake/lovesegfault-vim-config): `c9f4de01` -> `06a33c6e`

- flake.lock
| [`439ac4a3`](https://github.com/lovesegfault/vim-config/commit/439ac4a3744380b9d635daf3e0c169491540aa7d) | `` chore(flake/nixvim): eeec7f7c -> 03fa28a6 `` |
> chore(flake/lovesegfault-vim-config): `06a33c6e` -> `439ac4a3`

- flake.lock
| Commit                                                                                               | Message                                                                    |
| ---------------------------------------------------------------------------------------------------- | -------------------------------------------------------------------------- |
| [`2bf3421f`](https://github.com/nix-community/disko/commit/2bf3421f7fed5c84d9392b62dcb9d76ef09796a7) | `` build(deps): bump DeterminateSystems/update-flake-lock from 25 to 26 `` |
> chore(flake/disko): `79264292` -> `2bf3421f`

- flake.lock
| Commit                                                                                                | Message                                                              |
| ----------------------------------------------------------------------------------------------------- | -------------------------------------------------------------------- |
| [`a92b0ac9`](https://github.com/nix-community/stylix/commit/a92b0ac9da273fa484136283d4ef54ca19eacc4f) | `` ci: bump DeterminateSystems/nix-installer-action from 18 to 19 `` |
> chore(flake/stylix): `45749a79` -> `a92b0ac9`

- flake.lock
| [`32b25fa9`](https://github.com/lovesegfault/vim-config/commit/32b25fa9a20e34388b4f5a153555007e7f960c7f) | `` chore(flake/nixpkgs): 1fd8bada -> 62e0f05e `` |
| [`f8728ca4`](https://github.com/lovesegfault/vim-config/commit/f8728ca43658b54139bd6ce587b14d8204b5bf37) | `` chore(flake/nixvim): 03fa28a6 -> 1fb1bf8a ``  |
> chore(flake/lovesegfault-vim-config): `439ac4a3` -> `32b25fa9`

- flake.lock
| Commit                                                                                                | Message                                                                     |
| ----------------------------------------------------------------------------------------------------- | --------------------------------------------------------------------------- |
| [`8c854fe3`](https://github.com/nix-community/stylix/commit/8c854fe383fda20e8befefc31ecf248988a40bcc) | `` stylix: allow choosing testbed desktop (#1222) ``                        |
| [`436ad797`](https://github.com/nix-community/stylix/commit/436ad797df3fea6daab8b47a1ba10c7ae2505625) | `` zellij: update theme based on built-in Catppuccin Mocha theme (#1704) `` |
> chore(flake/stylix): `a92b0ac9` -> `8c854fe3`

- flake.lock
| Commit                                                                                                    | Message                                                        |
| --------------------------------------------------------------------------------------------------------- | -------------------------------------------------------------- |
| [`d32b8088`](https://github.com/nix-community/lanzaboote/commit/d32b80889700ec1479d19d08ebfdb9880a4e76d7) | `` Add note for Microsoft Surface devices to QUICK_START.md `` |
| [`1761822f`](https://github.com/nix-community/lanzaboote/commit/1761822fe0ade36dfedf5a33427ffc01269b5e23) | `` chore(deps): lock file maintenance ``                       |
> chore(flake/lanzaboote): `f4eb7554` -> `5a776450`

- flake.lock
| [`0ba0ffe9`](https://github.com/nix-community/stylix/commit/0ba0ffe94cbe20ae739c2aa8cae04cbf900bf56b) | `` wayprompt: add testbed (#1708) `` |
> chore(flake/stylix): `8c854fe3` -> `0ba0ffe9`

- flake.lock
| [`d5ad4485`](https://github.com/nix-community/disko/commit/d5ad4485e6f2edcc06751df65c5e16572877db88) | `` flake.lock: Update `` |
> chore(flake/disko): `2bf3421f` -> `d5ad4485`

- flake.lock
| [`03699ed2`](https://github.com/nix-community/stylix/commit/03699ed214f6e8195bc7199d6ae3aeccf9732b08) | `` stylix/testbed: respect xserver rename for gnome (#1714) `` |
| [`52804c7c`](https://github.com/nix-community/stylix/commit/52804c7c81fbe34e435113e253c002f788c096bf) | `` waybar: add testbed (#1712) ``                              |
> chore(flake/stylix): `0ba0ffe9` -> `03699ed2`

- flake.lock
| [`bc9f3c84`](https://github.com/nix-community/home-manager/commit/bc9f3c8413a3aaa01ed959c371c1f9e57515965b) | `` direnv: misc cleanup ``                           |
| [`8320333a`](https://github.com/nix-community/home-manager/commit/8320333a4547422afb68b6df7ac7edfa2733038b) | `` tests/direnv: refactor tests ``                   |
| [`63994b71`](https://github.com/nix-community/home-manager/commit/63994b71d223b48007dbec0089bbfd62d9cd4e1d) | `` direnv: fix …
> chore(flake/home-manager): `460f1e9a` -> `bc9f3c84`

- flake.lock
| [`016c55b8`](https://github.com/lovesegfault/vim-config/commit/016c55b8abadb2984726594f345b6daa6c6a5a19) | `` chore(flake/nixpkgs): 62e0f05e -> 6e987485 `` |
> chore(flake/lovesegfault-vim-config): `32b25fa9` -> `016c55b8`

- flake.lock
| [`d0300c88`](https://github.com/nix-community/home-manager/commit/d0300c8808e41da81d6edfc202f3d3833c157daf) | `` direnv: fix broken nushell integration (#7498) `` |
> chore(flake/home-manager): `dcfd70f8` -> `d0300c88`

- flake.lock
| [`663f68f1`](https://github.com/Mic92/nix-fast-build/commit/663f68f1f5a283e8a6d5b929104f7b4b084c47bd) | `` chore(deps): update treefmt-nix digest to 0043b95 (#194) `` |
> chore(flake/nix-fast-build): `36eb141b` -> `663f68f1`

- flake.lock
| Commit                                                                                                | Message                                                                               |
| ----------------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------- |
| [`24499b00`](https://github.com/nix-community/stylix/commit/24499b0049881959bd4e159b6fe4e96e4c03db25) | `` stylix: conditionally load external modules in testbeds (#1698) ``                 |
| [`2e2e96f6`](https://github.com/nix-community/stylix/commit/2e2e96f6b0720c9e974093b6521b8848ddd5706c) | `` treewide: remove blank lines around 'let', 'in', and function arguments (#1700) `` |
> chore(flake/stylix): `03699ed2` -> `24499b00`

- flake.lock
| [`f826d321`](https://github.com/nix-community/stylix/commit/f826d3214b8a9be3f158d5cc7514c4130674324b) | `` stylix: add generated all-maintainers file (#1654) `` |
| [`e4cc192b`](https://github.com/nix-community/stylix/commit/e4cc192b263f17fb58e616301e29b1498e72f390) | `` ci: use cachix/install-nix-action (#1725) ``          |
> chore(flake/stylix): `24499b00` -> `f826d321`

- flake.lock
| [`57d85475`](https://github.com/nix-community/nix-index-database/commit/57d8547540d3abb18922e8d1edbaac70dc486b7f) | `` flake.lock: Update `` |
> chore(flake/nix-index-database): `839e02de` -> `57d85475`

- flake.lock
| [`fafdcb50`](https://github.com/nix-community/nix-index-database/commit/fafdcb505ba605157ff7a7eeea452bc6d6cbc23c) | `` update generated.nix to release 2025-07-20-035855 `` |
> chore(flake/nix-index-database): `57d85475` -> `fafdcb50`

- flake.lock
| [`9242b3ec`](https://github.com/nix-community/stylix/commit/9242b3ec8e0d253f32614778ed4996af7aaf9438) | `` ci: fix generated all-maintainers path (#1728) `` |
> chore(flake/stylix): `f826d321` -> `9242b3ec`

- flake.lock
| [`421b5631`](https://github.com/numtide/treefmt-nix/commit/421b56313c65a0815a52b424777f55acf0b56ddf) | `` remove nufmt (#386) `` |
> chore(flake/treefmt-nix): `0043b95d` -> `421b5631`

- flake.lock
| [`c32c82e4`](https://github.com/nix-community/stylix/commit/c32c82e460b9022c4c20cf51014db1665e866ffb) | `` zen-browser: init (#1694) ``                                     |
| [`62bd6e52`](https://github.com/nix-community/stylix/commit/62bd6e52a541f5f717671812fd3556cb5bec40cf) | `` i3: use mkTarget (#1655) ``                                      |
| [`4af7cbde`](https://github.com/nix-community/stylix/commit/4af7cbde9cdae25e5ecc4a95693b9e0e30 …
> chore(flake/stylix): `9242b3ec` -> `c32c82e4`

- flake.lock
| [`9276a1ba`](https://github.com/lovesegfault/vim-config/commit/9276a1ba15d1ec017ca54f80d7e1824acdff7e66) | `` chore(flake/treefmt-nix): 0043b95d -> 421b5631 `` |
| [`a577bdc3`](https://github.com/lovesegfault/vim-config/commit/a577bdc3edb434561cd7427dd4dc3f6d021787ea) | `` chore(flake/nixvim): 1fb1bf8a -> 0c50ed93 ``      |
> chore(flake/lovesegfault-vim-config): `72d13609` -> `9276a1ba`

- flake.lock
| [`a8663953`](https://github.com/lovesegfault/vim-config/commit/a86639534edf25d7a080578f56615f18b92261b7) | `` chore(flake/nixpkgs): 6e987485 -> c87b95e2 `` |
> chore(flake/lovesegfault-vim-config): `9276a1ba` -> `a8663953`

- flake.lock
| [`1021b7d7`](https://github.com/nix-community/stylix/commit/1021b7d7322c4a3eada82bc6e60c6bedf08cfce1) | `` stylix: simplify API by renaming stylix.iconTheme option to stylix.icons `` |
| [`699262a0`](https://github.com/nix-community/stylix/commit/699262a0f8cd42ea1e786351cf91b1403fa7598e) | `` stylix: rename icon.nix to icon-theme.nix ``                                |
> chore(flake/stylix): `c32c82e4` -> `ea60526c`

- flake.lock
| [`6505841f`](https://github.com/lovesegfault/vim-config/commit/6505841f8045fd1b93cd1ad71f3557dcccbb1d1c) | `` chore(flake/flake-parts): 77826244 -> 644e0fc4 `` |
> chore(flake/lovesegfault-vim-config): `a8663953` -> `6505841f`

- flake.lock
| [`e4bf85da`](https://github.com/nix-community/home-manager/commit/e4bf85da687027cfc4a8853ca11b6b86ce41d732) | `` neomutt: allow default email sending behaviour (#7476) `` |
> chore(flake/home-manager): `13a83d1b` -> `e4bf85da`

- flake.lock
| [`847711c7`](https://github.com/nix-community/home-manager/commit/847711c7ffa9944b0c5c39a8342ac8eb6a9f9abc) | `` ci: bump DeterminateSystems/update-flake-lock from 26 to 27 `` |
| [`83674177`](https://github.com/nix-community/home-manager/commit/836741779f18dc111af1609f9749a5236e1e8f33) | `` ci: apply dependabot on release-25.05 ``                       |
| [`d1db9055`](https://github.com/nix-community/home-manager/commit/d1db9055ea39 …
> chore(flake/home-manager): `e4bf85da` -> `847711c7`

- flake.lock
| [`0cdfcdbb`](https://github.com/nix-community/home-manager/commit/0cdfcdbb525b77b951c889b6131047bc374f48fe) | `` Update translation files `` |
> chore(flake/home-manager): `847711c7` -> `0cdfcdbb`

- flake.lock
| [`1fde6fb1`](https://github.com/nix-community/home-manager/commit/1fde6fb1be6cd5dc513dc1c287d69e4eb2de973e) | `` yofi: add module (#7528) ``                                |
| [`fe38a5e0`](https://github.com/nix-community/home-manager/commit/fe38a5e02870debe6084203bca56d750e5d67ce8) | `` pueue: enable darwin configuration (#7519) ``              |
| [`3641df95`](https://github.com/nix-community/home-manager/commit/3641df95becab34d2d7a22121809 …
> chore(flake/home-manager): `0cdfcdbb` -> `1fde6fb1`

- flake.lock
| [`a8e57850`](https://github.com/nix-community/lanzaboote/commit/a8e57850ebbd745eb83361f1c53dbb9f5810411a) | `` chore(deps): lock file maintenance `` |
> chore(flake/lanzaboote): `5a776450` -> `4775927e`

- flake.lock
| [`c2328707`](https://github.com/lovesegfault/vim-config/commit/c2328707ac4978ed5fb299a79e9dc0a30bb10db7) | `` chore(flake/nixpkgs): c87b95e2 -> fc02ee70 `` |
> chore(flake/lovesegfault-vim-config): `6505841f` -> `c2328707`

- flake.lock
| [`4928fd7a`](https://github.com/lovesegfault/vim-config/commit/4928fd7a960641a6696ca4fc617d3a62d3a0c94f) | `` chore(flake/nixvim): 0c50ed93 -> 3d09c8ea ``      |
| [`3c76e27f`](https://github.com/lovesegfault/vim-config/commit/3c76e27f9db3385a8fe7ee2952f02ead891cdef9) | `` chore(flake/treefmt-nix): 421b5631 -> 2673921c `` |
> chore(flake/lovesegfault-vim-config): `c2328707` -> `4928fd7a`

- flake.lock
| [`744431e1`](https://github.com/nix-community/stylix/commit/744431e17676177c18c4c52e8781ba6e91db30d6) | `` flake: leverage lib.flip (#1754) `` |
> chore(flake/stylix): `ceda12a6` -> `744431e1`

- flake.lock
| [`37fec70b`](https://github.com/nix-community/home-manager/commit/37fec70bd5dace2fb025d3f7cbc0899a7fce6081) | `` ci: extract maintainers with single file eval (#7548) `` |
> chore(flake/home-manager): `a1817d1c` -> `37fec70b`

- flake.lock
| [`af85565a`](https://github.com/nix-community/stylix/commit/af85565aba0f4749cb18b118a7333a0745920950) | `` treewide: replace lib.listToAttrs with builtins.listToAttrs (#1760) `` |
| [`3a7b869c`](https://github.com/nix-community/stylix/commit/3a7b869cd61c0db5ca369d39632d64a6e45a41f2) | `` fuzzel: fix icons not being set correctly ``                           |
| [`07482556`](https://github.com/nix-community/stylix/commit/07482556dc …
> chore(flake/stylix): `744431e1` -> `af85565a`

- flake.lock
| [`f07da55d`](https://github.com/lovesegfault/vim-config/commit/f07da55df69b108df4c94283fd164fac70a1d2e3) | `` chore(flake/nixpkgs): fc02ee70 -> 7fd36ee8 `` |
| [`ecc05b29`](https://github.com/lovesegfault/vim-config/commit/ecc05b29351730ecc4792237e2eb3e03cdee932f) | `` chore(flake/nixvim): 3d09c8ea -> 29edaafd ``  |
> chore(flake/lovesegfault-vim-config): `4928fd7a` -> `f07da55d`

- flake.lock
| [`a4e1c3ba`](https://github.com/nix-community/nix-index-database/commit/a4e1c3bac560b098e71542ae5f262ceb68502a74) | `` flake.lock: Update `` |
> chore(flake/nix-index-database): `fafdcb50` -> `a4e1c3ba`

- flake.lock
| [`f0736b09`](https://github.com/nix-community/nix-index-database/commit/f0736b09c43028fd726fb70c3eb3d1f0795454cf) | `` update generated.nix to release 2025-07-27-040015 `` |
> chore(flake/nix-index-database): `a4e1c3ba` -> `f0736b09`

- flake.lock
| [`72cc1e31`](https://github.com/nix-community/home-manager/commit/72cc1e3134a35005006f06640724319caa424737) | `` tests/hyprlock: update tests with upstream changes ``  |
| [`0daef6fb`](https://github.com/nix-community/home-manager/commit/0daef6fbe0d71cd81967d9595a60c515a31ad034) | `` hyprlock: update example config ``                     |
| [`e8867156`](https://github.com/nix-community/home-manager/commit/e88671567b5020c41fa1880ef08428f91448548b) | …
> chore(flake/home-manager): `710771af` -> `72cc1e31`

- flake.lock
| [`a6cf7759`](https://github.com/nix-community/stylix/commit/a6cf77599790af5a21d7043a6b65767e410d633f) | `` yazi: allow to set boldness of directory (#1696) ``     |
| [`e6d25946`](https://github.com/nix-community/stylix/commit/e6d25946f370f50a1f7b48c9081845fae6804ae9) | `` zellij: add testbed (#1773) ``                          |
| [`4606c3e1`](https://github.com/nix-community/stylix/commit/4606c3e1b59d8c93b2368b4e5352fcee7992c0e0) | `` helix: add testbed …
> chore(flake/stylix): `af85565a` -> `a6cf7759`

- flake.lock
| [`3456e44b`](https://github.com/lovesegfault/vim-config/commit/3456e44b275d4c364d57392fe804c2784039a99d) | `` chore(flake/nixvim): 29edaafd -> 4f584b5b `` |
> chore(flake/lovesegfault-vim-config): `f07da55d` -> `3456e44b`

- flake.lock
| [`e4b032ba`](https://github.com/nix-community/home-manager/commit/e4b032ba5113664f0b8b23d956e59ce8e0bc349d) | `` ci: re-enable home manager install and uninstall tests on darwin `` |
| [`a07400a2`](https://github.com/nix-community/home-manager/commit/a07400a2e53a59e1b06ef5b76f0062bcaf3500fc) | `` ci: don't duplicate test runs on github ``                          |
| …
> chore(flake/home-manager): `72cc1e31` -> `e4b032ba`

- flake.lock
| [`a7b7c6f5`](https://github.com/nix-community/home-manager/commit/a7b7c6f520b51f3577bd6b7a7493d2cdbcb22ec6) | `` docs: add upgrade guide for NixOS version transitions `` |
| [`3156a1c4`](https://github.com/nix-community/home-manager/commit/3156a1c4196e03e66ce16220d4f2e58cb19718cb) | `` docs: minor manual style fix ``                          |
> chore(flake/home-manager): `e4b032ba` -> `a7b7c6f5`

- flake.lock
| Commit                                                                                                | Message                                                                     |
| ----------------------------------------------------------------------------------------------------- | --------------------------------------------------------------------------- |
| [`57d036d9`](https://github.com/nix-community/stylix/commit/57d036d92283fddc6ae080459e72e767144a1cda) | `` doc: commit_convention: overhaul and formalize unspoken rules (#1717) `` |
| [`683d6269`](https://github.com/nix-community/stylix/commit/683d626986cf87548c66bfe27c5588a071ad636f) | `` fuzzel: add testbed (#1784) ``                                           |
> chore(flake/stylix): `fc24382f` -> `57d036d9`

- flake.lock
| [`ba2f6e2e`](https://github.com/lovesegfault/vim-config/commit/ba2f6e2e4f405e76d599d0650945c304446ec0b7) | `` chore(flake/nixvim): 4f584b5b -> e1aa35fb `` |
> chore(flake/lovesegfault-vim-config): `3456e44b` -> `ba2f6e2e`

- flake.lock
| [`50adf8fc`](https://github.com/nix-community/home-manager/commit/50adf8fcaa97c9d64309f2d507ed8be54ea23110) | `` PR_TEMPLATE: remove maintainer cc section (#7569) `` |
> chore(flake/home-manager): `f49e872f` -> `50adf8fc`

- flake.lock
| [`b108e6b7`](https://github.com/nix-community/home-manager/commit/b108e6b7f75d2767a1a559345689e7bedfe7dd11) | `` editorconfig: fix insert_final_newline unset for json files `` |
| [`1a8b119e`](https://github.com/nix-community/home-manager/commit/1a8b119e60158711ac53962f7a6ad478796f449a) | `` tests/caffeine: add test coverage ``                           |
| [`cec4c1be`](https://github.com/nix-community/home-manager/commit/cec4c1be7eaa …
> chore(flake/home-manager): `cfe397c8` -> `b108e6b7`

- flake.lock
| [`ab148052`](https://github.com/nix-community/home-manager/commit/ab14805267c132c5e9ac66129ca5361abd592a3a) | `` darwinScrublist: add superfile ``                                         |
| [`fc55d9a4`](https://github.com/nix-community/home-manager/commit/fc55d9a42b178a62edb15a1d11b7085274a922a2) | `` flake.lock: Update ``                                                     |
| …
> chore(flake/home-manager): `b108e6b7` -> `ab148052`

- flake.lock
| [`e4fdedf7`](https://github.com/lovesegfault/vim-config/commit/e4fdedf7b0fd57494a7035e9862af7c9304e63d6) | `` chore(flake/treefmt-nix): 2673921c -> 6b9214ff `` |
| [`cab16e85`](https://github.com/lovesegfault/vim-config/commit/cab16e85fe3158faae2c74a531c410984b6cb18c) | `` chore(flake/nixvim): e1aa35fb -> fe0bcc92 ``      |
> chore(flake/lovesegfault-vim-config): `ba2f6e2e` -> `e4fdedf7`

- flake.lock
| [`cf71ad5a`](https://github.com/nix-community/stylix/commit/cf71ad5aae3555d9ccc3ae0b522a88e8973c500d) | `` ci: use nix-community cachix (#1797) `` |
> chore(flake/stylix): `57d036d9` -> `cf71ad5a`

- flake.lock
| [`b4e1daad`](https://github.com/nix-community/stylix/commit/b4e1daad3bcd434cf09a42fd0014c5d239c7ceed) | `` ci: request subsystem maintainers review (#1053) ``                    |
| [`4bfd32c8`](https://github.com/nix-community/stylix/commit/4bfd32c8f93ef95be2f41a00e438f0bb2de1c4ac) | `` ci: backport: fix "has: port to stable" condition (#1795) ``           |
| [`8017dec8`](https://github.com/nix-community/stylix/commit/8017dec82d …
> chore(flake/stylix): `cf71ad5a` -> `b4e1daad`

- flake.lock
| [`3b6731f6`](https://github.com/nix-community/stylix/commit/3b6731f6f065fa9936d94f188b0c8cf7a33cf04c) | `` stylix/testbed/modules/common: globally enable Bash (#1803) `` |
> chore(flake/stylix): `b4e1daad` -> `3b6731f6`

- flake.lock
| [`26bfb73f`](https://github.com/lovesegfault/vim-config/commit/26bfb73ff1473a31f2413b8aba9700925b3f997e) | `` fix: only enable wl-copy/xclip on linux ``                                 |
| [`a419f30a`](https://github.com/lovesegfault/vim-config/commit/a419f30a5c463d8bfe2ec5ce104f272c9a3bfd61) | `` chore(flake/nixpkgs): 7fd36ee8 -> dc963787 ``                              |
| …
> chore(flake/lovesegfault-vim-config): `e4fdedf7` -> `26bfb73f`

- flake.lock
| Commit                                                                                         | Message                                                                                             |
| ---------------------------------------------------------------------------------------------- | --------------------------------------------------------------------------------------------------- |
| [`6497d443`](https://github.com/NixOS/nixpkgs/commit/6497d443452cfba1405034e2f54cec5801f2bfdc) | `` release: don't block on bootstrap tools, temporarily ``                                          |
| [`2014a8b2`](https://github.com/NixOS/nixpkgs/commit/2014a8b27a90ef142462b5dfabc8e73bb95bec8b) | `` hyprprop: 0.1-unstable-2025-07-18 -> 0.1-unstable-2025-07-23 `` …
> chore(flake/nixpkgs): `7fd36ee8` -> `dc963787`

- flake.lock
| [`ded4f29a`](https://github.com/nix-community/stylix/commit/ded4f29a023e0f14506ec16b0e32d129e56341cc) | `` doc/src/modules: fix admonition formatting (#1814) `` |
> chore(flake/stylix): `e544f6ec` -> `ded4f29a`

- flake.lock
| [`7035020a`](https://github.com/nix-community/home-manager/commit/7035020a507ed616e2b20c61491ae3eaa8e5462c) | `` anki: set valid language default ``            |
| [`e2238e60`](https://github.com/nix-community/home-manager/commit/e2238e60736a2dd86f5bcf6fafee72429a9cd6ff) | `` anki: remove trailing whitespace ``            |
| [`4e97102b`](https://github.com/nix-community/home-manager/commit/4e97102bd44899c514411aa8e604ecc33a9da356) | `` nh: add options for specific …
> chore(flake/home-manager): `bd82507e` -> `7035020a`

- flake.lock
| [`3e37fbde`](https://github.com/lovesegfault/vim-config/commit/3e37fbde681effc0efacd01056be811e35756dca) | `` chore(flake/nixvim): 1729fe16 -> a16c89c1 `` |
> chore(flake/lovesegfault-vim-config): `2be60666` -> `3e37fbde`

- flake.lock
| Commit                                                                                         | Message                                                                                      |
| ---------------------------------------------------------------------------------------------- | -------------------------------------------------------------------------------------------- |
| [`caf5a7d2`](https://github.com/NixOS/nixpkgs/commit/caf5a7d2d10c4cc33d02cf16f540ba79d6ccd004) | `` gh: 2.76.1 -> 2.76.2 ``                                                                   |
| [`1905dad0`](https://github.com/NixOS/nixpkgs/commit/1905dad0b5d4f87cba3227b16a82fbce62f2cd8d) | `` go: add freebsd to binary bootstrap platforms ``                                          |
| …
> chore(flake/nixpkgs): `dc963787` -> `94def634`

- flake.lock
| [`19f94a3e`](https://github.com/nix-community/home-manager/commit/19f94a3e0e6c8573ea58dac685e96c36e2526cfa) | `` sesh: Add preview window ``                        |
| [`712c6dad`](https://github.com/nix-community/home-manager/commit/712c6dad6cc41abd77c103dc76cda7c443b6c4b3) | `` sesh: fix kill-session field seperator ``          |
| [`614956c9`](https://github.com/nix-community/home-manager/commit/614956c9932b607a758d7910a5c133af44110309) | `` sesh: switch …
> chore(flake/home-manager): `7035020a` -> `19f94a3e`

- flake.lock
| [`33d146a9`](https://github.com/lovesegfault/vim-config/commit/33d146a908869b9863b2af98aa458fecaa9e3aa7) | `` chore(flake/flake-parts): 644e0fc4 -> 67df8c62 `` |
| [`0f346757`](https://github.com/lovesegfault/vim-config/commit/0f34675733e0323f47142b56e17e36da2e89b1ca) | `` chore(flake/treefmt-nix): 6b9214ff -> 58bd4da4 `` |
> chore(flake/lovesegfault-vim-config): `3e37fbde` -> `33d146a9`

- flake.lock
| [`e102920c`](https://github.com/nix-community/home-manager/commit/e102920c1becb114645c6f92fe14edc0b05cc229) | `` zoxide: move zsh priority (#7593) `` |
> chore(flake/home-manager): `19f94a3e` -> `e102920c`

- flake.lock
| [`85a033e0`](https://github.com/lovesegfault/vim-config/commit/85a033e0146fcbaeccc1f1535276388a3d375bee) | `` chore(flake/nixpkgs): dc963787 -> 94def634 `` |
> chore(flake/lovesegfault-vim-config): `33d146a9` -> `85a033e0`

- flake.lock
| Commit                                                                                                  | Message                                                                         |
| ------------------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------- |
| [`ed9d7d6e`](https://github.com/tinted-theming/schemes/commit/ed9d7d6e024c358c68c17527022df3221f61c9f2) | `` Fix #65 Tomorrow light theme corrections for selection/current-line (#66) `` |
> chore(flake/tinted-schemes): `7ef9b314` -> `ed9d7d6e`

- flake.lock
| [`b9f618a0`](https://github.com/nix-community/nix-index-database/commit/b9f618a0b22d2c58a620afb7e2dec93582980057) | `` flake.lock: Update `` |
> chore(flake/nix-index-database): `f0736b09` -> `b9f618a0`

- flake.lock
| [`b7fcd4e2`](https://github.com/nix-community/nix-index-database/commit/b7fcd4e26d67fca48e77de9b0d0f954b18ae9562) | `` update generated.nix to release 2025-08-03-040401 `` |
> chore(flake/nix-index-database): `b9f618a0` -> `b7fcd4e2`

- flake.lock
| [`0de18bd5`](https://github.com/nix-community/home-manager/commit/0de18bd5c6681280d7ae017fa34ffd91bdcf0557) | `` flake.lock: Update ``                |
| [`2d3b2f33`](https://github.com/nix-community/home-manager/commit/2d3b2f33a70b5521f98e8ab8218f09cd1f29883b) | `` Translate using Weblate (Finnish) `` |
> chore(flake/home-manager): `e6e2f43a` -> `0de18bd5`

- flake.lock
| [`efef31b0`](https://github.com/lovesegfault/vim-config/commit/efef31b00f23acadfd4e57b8f9ac219613f196ce) | `` chore(flake/nixvim): a16c89c1 -> 0b87d944 `` |
> chore(flake/lovesegfault-vim-config): `85a033e0` -> `efef31b0`

- flake.lock
| Commit                                                                                                | Message                  |
| ----------------------------------------------------------------------------------------------------- | ------------------------ |
| [`1b5e1c56`](https://github.com/nix-community/stylix/commit/1b5e1c5642cf96e07daf14ae4c5ddd23d7ed5623) | `` anki: init (#1801) `` |
> chore(flake/stylix): `ded4f29a` -> `1b5e1c56`

- flake.lock
| [`39d0153e`](https://github.com/nix-community/lanzaboote/commit/39d0153e3f9406835232b8c0517ab5a4b7698e99) | `` chore(deps): lock file maintenance `` |
> chore(flake/lanzaboote): `785a5701` -> `892cbdca`

- flake.lock
| Commit                                                                                         | Message                                                                  |
| ---------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------ |
| [`da00e1cb`](https://github.com/ryantm/agenix/commit/da00e1cb898fc8f089e91a37b75a37a3398cc7e2) | `` Add more description on why armor may be useful ``                    |
| [`d1eefa4d`](https://github.com/ryantm/agenix/commit/d1eefa4de1e66cdf2f340cefd0781b375694f987) | `` Add wait for file write before assertion ``                           |
| [`783bf0da`](https://github.com/ryantm/agenix/commit/783bf0daf6c3b13e927849039247f213dcf401f8) | `` …
> chore(flake/agenix): `531beac6` -> `6d194f75`

- flake.lock
| [`665a4ede`](https://github.com/nix-community/stylix/commit/665a4ede4dbc2f52575a3eeaa457a89d97d3d28e) | `` anki/meta: fix name capitalization (#1820) `` |
> chore(flake/stylix): `1b5e1c56` -> `665a4ede`

- flake.lock
| [`e3c46306`](https://github.com/lovesegfault/vim-config/commit/e3c463067dbf57ad0cc04abe8e93dc6c6397b256) | `` chore(flake/nixpkgs): 94def634 -> 5b09dc45 `` |
> chore(flake/lovesegfault-vim-config): `efef31b0` -> `e3c46306`

- flake.lock
| [`845e13f7`](https://github.com/Mic92/nix-fast-build/commit/845e13f7fb9b73150ffd34e43c0d939e25eafdbd) | `` chore(deps): update flake-parts digest to 7f38f25 `` |
| [`f9a6ec46`](https://github.com/Mic92/nix-fast-build/commit/f9a6ec462f06c61a0b1e6fbe6ffb57ca29f7f631) | `` chore(deps): update flake-parts digest to 67df8c6 `` |
> chore(flake/nix-fast-build): `7f4fa3e6` -> `690b9c4f`

- flake.lock
| Commit                                                                                         | Message                         |
| ---------------------------------------------------------------------------------------------- | ------------------------------- |
| [`bc3b1316`](https://github.com/ryantm/agenix/commit/bc3b1316421a7edac0f515354a0ae52dbb94aebd) | `` hashed password file ``      |
| [`0814fdc0`](https://github.com/ryantm/agenix/commit/0814fdc0dea23e6c2656109e66d69e056f466358) | `` format nix with rfc style `` |
> chore(flake/agenix): `856df6f6` -> `9edb1787`

- flake.lock
| [`8410296a`](https://github.com/nix-community/stylix/commit/8410296a30e62e06305020cb74d3247cfa45d9cc) | `` anki/hm: remove unused config argument (#1821) `` |
> chore(flake/stylix): `665a4ede` -> `8410296a`

- flake.lock
| [`c1ac4b2c`](https://github.com/lovesegfault/vim-config/commit/c1ac4b2c454f57c25ac488d2e6c1ff123a3f86b4) | `` chore(flake/git-hooks): 16ec914f -> 9c523728 ``   |
| [`59dde398`](https://github.com/lovesegfault/vim-config/commit/59dde3989306ba1ef9331f273f134dbc465ddf7f) | `` chore(flake/flake-parts): 67df8c62 -> 7f38f25a `` |
> chore(flake/lovesegfault-vim-config): `e3c46306` -> `c1ac4b2c`

- flake.lock
| Commit                                                                                                      | Message                 |
| ----------------------------------------------------------------------------------------------------------- | ----------------------- |
| [`88913c98`](https://github.com/nix-community/home-manager/commit/88913c98fe674e10302bbdb71b4e173f527b69c2) | `` goto: init module `` |
> chore(flake/home-manager): `ad5d2b4a` -> `88913c98`

- flake.lock
| [`002c4dc7`](https://github.com/Mic92/nix-fast-build/commit/002c4dc74cb683de08a1f863e1831e19f86f3edd) | `` chore(deps): update treefmt-nix digest to 1298185 (#213) `` |
| [`e03be500`](https://github.com/Mic92/nix-fast-build/commit/e03be50046743a1861e7ac95741744f420a3ab98) | `` chore(deps): update treefmt-nix digest to bf87ce8 (#212) `` |
| [`85b95df9`](https://github.com/Mic92/nix-fast-build/commit/85b95df96be69378761ef8113501f1a5551ace79) | `` …
> chore(flake/nix-fast-build): `690b9c4f` -> `002c4dc7`

- flake.lock
| [`13461dec`](https://github.com/nix-community/home-manager/commit/13461dec40bf03d9196ff79d1abe48408268cc35) | `` git-credential-keepassxc: fix eval ``             |
| [`2a299689`](https://github.com/nix-community/home-manager/commit/2a29968912815e825a8cae73e2535a94424a9d1b) | `` git-credential-keepassxc: init module ``          |
| [`53bf4fab`](https://github.com/nix-community/home-manager/commit/53bf4fab3013c9c200593a45c95469dba12c5315) | `` docs: add tests …
> chore(flake/home-manager): `88913c98` -> `13461dec`

- flake.lock
| [`62fdc8d4`](https://github.com/nix-community/home-manager/commit/62fdc8d41097313e681446b46681a4f89544e51c) | `` keepassxc: add autostart option ``     |
| [`cb8cfa0e`](https://github.com/nix-community/home-manager/commit/cb8cfa0eb9a7f2ab2edaaf934f5e413b91800c31) | `` keepassxc: add maintainer bmrips ``    |
| [`13c5c2fb`](https://github.com/nix-community/home-manager/commit/13c5c2fb4cbed19ee40552a29a1b0fac8839a2dd) | `` Translate using Weblate (Ukrainian) `` |
> chore(flake/home-manager): `13461dec` -> `62fdc8d4`

- flake.lock
| [`9b0d0699`](https://github.com/lovesegfault/vim-config/commit/9b0d06996cee4f293fa82772812e080a46e0502d) | `` chore(flake/nixvim): 8d47a075 -> 085ef669 ``      |
| [`b2e0467b`](https://github.com/lovesegfault/vim-config/commit/b2e0467bbf7869ebe2738e1ef6b8c44455415b85) | `` chore(flake/treefmt-nix): 58bd4da4 -> 1298185c `` |
> chore(flake/lovesegfault-vim-config): `89fd9eb6` -> `9b0d0699`

- flake.lock
| [`8dac2fa4`](https://github.com/lovesegfault/vim-config/commit/8dac2fa45d68323905ddff08e6de18fafd3983be) | `` chore(flake/flake-parts): 7f38f25a -> af66ad14 `` |
> chore(flake/lovesegfault-vim-config): `9b0d0699` -> `8dac2fa4`

- flake.lock
| [`475d3579`](https://github.com/nix-community/home-manager/commit/475d35797d9537354d825260cf583114537affc2) | `` treefmt: handle deadnix excludes `` |
> chore(flake/home-manager): `62fdc8d4` -> `475d3579`

- flake.lock
| Commit                                                                                                  | Message                                           |
| ------------------------------------------------------------------------------------------------------- | ------------------------------------------------- |
| [`a4dc01bf`](https://github.com/tinted-theming/schemes/commit/a4dc01bf442ec87fdaec71a9546346df7dc423fd) | `` Fix base16 and base24 links and format text `` |
> chore(flake/tinted-schemes): `7fa77635` -> `a4dc01bf`

- flake.lock
| [`d8a475e1`](https://github.com/nix-community/home-manager/commit/d8a475e179888553b6863204a93295da6ee13eb4) | `` tests: add mullvad-vpn to darwin scrublist ``     |
| [`a5506862`](https://github.com/nix-community/home-manager/commit/a5506862dc265a20b6790ae48e017ac2b3da6454) | `` mullvad-vpn: fix home.package -> home.packages `` |
| [`c7acf2b1`](https://github.com/nix-community/home-manager/commit/c7acf2b1bf1ec6c3a17b0b598e62e4190a1f1844) | `` mullvad-vpn: add …
> chore(flake/home-manager): `475d3579` -> `d8a475e1`

- flake.lock
| [`928e61f4`](https://github.com/nix-community/stylix/commit/928e61f4ed08162de3569cb03acc314caf74e35d) | `` ci: request-reviewers: add missing members permission `` |
| [`5b265fac`](https://github.com/nix-community/stylix/commit/5b265fac06646d5af36004144e3f8094a6a80c1d) | `` ci: request-reviewers: fix modules path ``               |
> chore(flake/stylix): `8410296a` -> `63bb34a6`

- flake.lock
| [`a340e360`](https://github.com/lovesegfault/vim-config/commit/a340e360dca40d062a97daae566ff808105184ef) | `` chore(flake/nixvim): 085ef669 -> 1db17950 `` |
> chore(flake/lovesegfault-vim-config): `8dac2fa4` -> `a340e360`

- flake.lock
| [`3ec1cd9a`](https://github.com/nix-community/home-manager/commit/3ec1cd9a0703fbd55d865b7fd2b07d08374f0355) | `` launchd+targets/darwin: Escape XML in plists (#7356) `` |
> chore(flake/home-manager): `cc2fa233` -> `3ec1cd9a`

- flake.lock
| Commit                                                                                                  | Message                             |
| ------------------------------------------------------------------------------------------------------- | ----------------------------------- |
| [`097d751b`](https://github.com/tinted-theming/schemes/commit/097d751b9e3c8b97ce158e7d141e5a292545b502) | `` Add missing MIT license (#70) `` |
> chore(flake/tinted-schemes): `6486b6b0` -> `097d751b`

- flake.lock
| [`58320509`](https://github.com/nix-community/home-manager/commit/58320509c5b83c93012b328c9c9a943d8d90f932) | `` flake.lock: Update (#7651) `` |
> chore(flake/home-manager): `3ec1cd9a` -> `58320509`

- flake.lock
| Commit                                                                                                | Message                                                                           |
| ----------------------------------------------------------------------------------------------------- | --------------------------------------------------------------------------------- |
| [`afcfed6f`](https://github.com/nix-community/stylix/commit/afcfed6fd2a51615cd63aa7fa7608d670e7b61e5) | `` doc: update github:danth/stylix URLs to github:nix-community/stylix (#1835) `` |
> chore(flake/stylix): `63bb34a6` -> `afcfed6f`

- flake.lock
| [`91586008`](https://github.com/nix-community/home-manager/commit/91586008a23c01cc32894ee187dca8c0a7bd20a4) | `` firefoxpwa: fix ULID length typo (#7653) ``                |
| [`e7969e2f`](https://github.com/nix-community/home-manager/commit/e7969e2ffa261e6c0587183f67bc906f482ba115) | `` PULL_REQUEST_TEMPLATE: format ``                           |
| [`85ed337f`](https://github.com/nix-community/home-manager/commit/85ed337f360f5039a83f6dbda875 …
> chore(flake/home-manager): `58320509` -> `91586008`

- flake.lock
| [`32291f20`](https://github.com/lovesegfault/vim-config/commit/32291f2065d51ee5e2db105efdf92a7a56368bc8) | `` chore(flake/nixpkgs): c2ae88e0 -> 85dbfc7a ``     |
| [`39e835fb`](https://github.com/lovesegfault/vim-config/commit/39e835fba66b7b4a5f329d7f95ffffa0371d9311) | `` chore(flake/treefmt-nix): 1298185c -> 7d81f6fb `` |
> chore(flake/lovesegfault-vim-config): `793bb6d3` -> `32291f20`

- flake.lock
| [`0d492b89`](https://github.com/nix-community/home-manager/commit/0d492b89d1993579e63b9dbdaed17fd7824834da) | `` walker: add module (#7649) `` |
> chore(flake/home-manager): `91586008` -> `0d492b89`

- flake.lock
| [`ab11bbc3`](https://github.com/Mic92/nix-fast-build/commit/ab11bbc3eea5d114c9f352e6d065787a2d62a63f) | `` Bump actions/checkout from 4 to 5 `` |
> chore(flake/nix-fast-build): `002c4dc7` -> `4d204b0e`

- flake.lock
| [`8246829f`](https://github.com/nix-community/disko/commit/8246829f2e675a46919718f9a64b71afe3bfb22d) | `` build(deps): bump actions/checkout from 4 to 5 `` |
> chore(flake/disko): `545aba02` -> `8246829f`

- flake.lock
| [`56aa9aed`](https://github.com/Mic92/nix-fast-build/commit/56aa9aed59c207821dbb751a2aea0a1119012680) | `` Update flake input: treefmt-nix ``                |
| [`869355fe`](https://github.com/Mic92/nix-fast-build/commit/869355fe640213b90f1bdcdeef782fe1e458fc8c) | `` Update flake input: nixpkgs ``                    |
| [`ce5f48f3`](https://github.com/Mic92/nix-fast-build/commit/ce5f48f323b80bb1d864f54640ffdbcf9e7a5661) | `` add update-flake-inputs github action `` …
> chore(flake/nix-fast-build): `4d204b0e` -> `ca71de01`

- flake.lock
| [`4b6dd06c`](https://github.com/nix-community/home-manager/commit/4b6dd06c6a92308c06da5e0e55f2c505237725c9) | `` glance: restart service when settings file changes `` |
> chore(flake/home-manager): `27a26be5` -> `4b6dd06c`

- flake.lock
| Commit                                                                                                      | Message                                                                 |
| ----------------------------------------------------------------------------------------------------------- | ----------------------------------------------------------------------- |
| [`279ca5ad`](https://github.com/nix-community/home-manager/commit/279ca5addcdcfa31ac852b3ecb39fc372684f426) | `` PULL_REQUEST_TEMPLATE: fix commit message link formatting (#7673) `` |
| [`d9a57c59`](https://github.com/nix-community/home-manager/commit/d9a57c597c31f4c7523a395fe2a7ae4910e193e2) | `` davmail: enable access to the display server (#7671) ``              |
> chore(flake/home-manager): `4b6dd06c` -> `279ca5ad`

- flake.lock
| [`885a9693`](https://github.com/lovesegfault/vim-config/commit/885a9693a28289eee9151d40a8688a79935c4dc8) | `` chore(flake/nixvim): 7b53322d -> ecc7880e `` |
> chore(flake/lovesegfault-vim-config): `da72a844` -> `885a9693`

- flake.lock
| [`e797b565`](https://github.com/lovesegfault/vim-config/commit/e797b565af12a75be8966c9259574ed358eadfa7) | `` chore(flake/nixpkgs): 85dbfc7a -> 005433b9 `` |
> chore(flake/lovesegfault-vim-config): `885a9693` -> `e797b565`

- flake.lock
| [`928ca832`](https://github.com/nix-community/stylix/commit/928ca832d22ab3167b49dc5f4d52ff5d26b0b52a) | `` ci: bump korthout/backport-action from 3.2.1 to 3.3.0 (#1844) `` |
> chore(flake/stylix): `c592717e` -> `928ca832`

- flake.lock
| [`11626a43`](https://github.com/nix-community/home-manager/commit/11626a4383b458f8dc5ea3237eaa04e8ab1912f3) | `` keepassxc: note the manifest installation conflict (#7675) `` |
> chore(flake/home-manager): `279ca5ad` -> `11626a43`

- flake.lock
| [`a1d1e76f`](https://github.com/lovesegfault/vim-config/commit/a1d1e76f05165122ed1fe35f32dffbb0d0154e40) | `` chore(flake/nixpkgs): 005433b9 -> fbcf476f `` |
> chore(flake/lovesegfault-vim-config): `e797b565` -> `a1d1e76f`

- flake.lock
| [`82242e0f`](https://github.com/nix-community/stylix/commit/82242e0f9b1d91b6f170807a6ec622cfdb816eac) | `` zen-browser: replace mustache template with Nix multiline string (#1829) `` |
> chore(flake/stylix): `928ca832` -> `82242e0f`

- flake.lock
| [`77c07852`](https://github.com/Mic92/nix-fast-build/commit/77c078525d720647471b0a99ae9431d7bc71d353) | `` Update flake input: nixpkgs `` |
> chore(flake/nix-fast-build): `8adab2f6` -> `520987ca`

- flake.lock
| [`ebbc1c05`](https://github.com/nix-community/nix-index-database/commit/ebbc1c05f786ae39bb5e04e57bf2c10c44a649e3) | `` update generated.nix to release 2025-08-17-034715 `` |
> chore(flake/nix-index-database): `6991c112` -> `ebbc1c05`

- flake.lock
| [`d2ffdedf`](https://github.com/nix-community/home-manager/commit/d2ffdedfc39c591367b1ddf22b4ce107f029dcc3) | `` flake.lock: Update (#7686) ``     |
| [`bc014931`](https://github.com/nix-community/home-manager/commit/bc014931784c62b566cad39b8510e76dde588d94) | `` mypy: init module (#7656) ``      |
| [`3dcae8af`](https://github.com/nix-community/home-manager/commit/3dcae8af51acd6f5ecc039fa23d044439cd19ae0) | `` hyprshot: init module ``          |
| …
> chore(flake/home-manager): `8b4ac149` -> `d2ffdedf`

- flake.lock
| [`f19f1097`](https://github.com/lovesegfault/vim-config/commit/f19f10978028459baacb81e8b04832df15b81071) | `` chore(flake/nixvim): ecc7880e -> e1e4bb83 `` |
> chore(flake/lovesegfault-vim-config): `99acd0ca` -> `f19f1097`

- flake.lock
| [`c613ac14`](https://github.com/nix-community/home-manager/commit/c613ac14f5600033bf84ae75c315d5ce24a0229b) | `` nh: allow absolute flake paths ``                   |
| [`e293a1a1`](https://github.com/nix-community/home-manager/commit/e293a1a12f448a6d92309daebd7cbda03e0f75c4) | `` aerospace: add test ``                              |
| [`bbfbda4a`](https://github.com/nix-community/home-manager/commit/bbfbda4ad8ee3e94cfab012249493a8375382dd0) | `` …
> chore(flake/home-manager): `bf450a08` -> `c613ac14`

- flake.lock
| [`8af2e064`](https://github.com/nix-community/home-manager/commit/8af2e064f93234ee79df8b9858eeefbf84394488) | `` satty: add satty to program modules `` |
| [`589efcf9`](https://github.com/nix-community/home-manager/commit/589efcf9c039db9dbc9410d53cf722d9e483dfd3) | `` maintainers: add gauthsvenkat ``       |
> chore(flake/home-manager): `c613ac14` -> `8af2e064`

- flake.lock
| [`0e0a16b3`](https://github.com/nix-community/home-manager/commit/0e0a16b342bcd435ad83c62f4794ce1a4ccff0ea) | `` anyrun: minor description fix `` |
> chore(flake/home-manager): `8af2e064` -> `0e0a16b3`

- flake.lock
| [`3335202e`](https://github.com/nix-community/stylix/commit/3335202ed032912053e8132efc25b5cd4c8982b7) | `` ci: ISSUE_TEMPLATE: improve and match PR template `` |
| [`f6a351a4`](https://github.com/nix-community/stylix/commit/f6a351a444e9c3992c2573853f23e196899fb139) | `` treewide: add awwpotato to core maintainers list ``  |
> chore(flake/stylix): `9810b32b` -> `7bd8d9c5`

- flake.lock
| [`dd026d86`](https://github.com/nix-community/home-manager/commit/dd026d86420781e84d0732f2fa28e1c051117b59) | `` sherlock: add `74k1` as maintainer ``                       |
| [`a9c81dbc`](https://github.com/nix-community/home-manager/commit/a9c81dbcc4d6f4777f11a5eadc45c8cf5501c8e5) | `` sherlock: use `X-Restart-Triggers` instead of `onChange` `` |
> chore(flake/home-manager): `0e0a16b3` -> `dd026d86`

- flake.lock
| [`2355da45`](https://github.com/nix-community/stylix/commit/2355da455d7188228aaf20ac16ea9386e5aa6f0c) | `` ci: remove 'Notify Maintainers' section from PR template (#1856) `` |
> chore(flake/stylix): `2567b924` -> `2355da45`

- flake.lock
| [`da71acc4`](https://github.com/lovesegfault/vim-config/commit/da71acc44182528c9568465134a1232fd01455d1) | `` chore(flake/nixpkgs): fbcf476f -> 20075955 `` |
| [`673b49fe`](https://github.com/lovesegfault/vim-config/commit/673b49fe09a45d3a46de6326f31da68edbad4aae) | `` chore(flake/nixvim): e1e4bb83 -> 1bd91097 ``  |
> chore(flake/lovesegfault-vim-config): `f19f1097` -> `da71acc4`

- flake.lock
| [`6911d3e7`](https://github.com/nix-community/home-manager/commit/6911d3e7f475f7b3558b4f5a6aba90fa86099baa) | `` nix-gc: rename frequency to dates ``                 |
| [`3001400e`](https://github.com/nix-community/home-manager/commit/3001400e9ff29ec5e6d81d82dc3865d3df7254aa) | `` rclone: move activation script to systemd service `` |
| [`56b87499`](https://github.com/nix-community/home-manager/commit/56b87499874d16c43f4a732084650cb50b048f15) | `` …
> chore(flake/home-manager): `282b4c98` -> `6911d3e7`

- flake.lock
| [`94e20cc2`](https://github.com/lovesegfault/vim-config/commit/94e20cc26f1e3aa4290cbcfb1f25e627efa560f3) | `` chore(flake/nixvim): 1bd91097 -> d96069b1 `` |
> chore(flake/lovesegfault-vim-config): `da71acc4` -> `94e20cc2`

- flake.lock
| Commit                                                                                                 | Message                                                                |
| ------------------------------------------------------------------------------------------------------ | ---------------------------------------------------------------------- |
| [`be2d7d65`](https://github.com/nix-darwin/nix-darwin/commit/be2d7d653567f49223d4d675e4a7d268a6ce90ba) | `` applications: ensure sufficient permissions before updating apps `` |
| [`1f9cca77`](https://github.com/nix-darwin/nix-darwin/commit/1f9cca7781b18a073c45823a24e9bd74eb83d3fe) | `` Copy applications instead of linking them to make macOS happy ``    |
| [`21d733a5`](https://github.com/nix-darwin/nix-darwin/commit/21d733a51f0b4f4b6 …
> chore(flake/darwin): `3a0a38a1` -> `8df64f81`

- flake.lock
| [`19adc97d`](https://github.com/cachix/git-hooks.nix/commit/19adc97dac491c7aafaa6ad09767b2e1dbf0e6f6) | `` feat(gotest): Pass flags to gotest `` |
| [`c3628084`](https://github.com/cachix/git-hooks.nix/commit/c3628084b15de5f88f73e0968c24a07569284818) | `` feat: add zizmor ``                   |
> chore(flake/git-hooks): `4b04db83` -> `3ff45966`

- flake.lock
| [`f3874456`](https://github.com/lovesegfault/vim-config/commit/f38744564e83379ef84411dd1abe57fc5850a391) | `` chore(flake/nixvim): 18a1b512 -> 91f51aed ``      |
| [`acbed258`](https://github.com/lovesegfault/vim-config/commit/acbed258b7cc95d9ba96a8023ee372c0aa4f9721) | `` chore(flake/treefmt-nix): 7d81f6fb -> 74e1a52d `` |
> chore(flake/lovesegfault-vim-config): `11bc02bd` -> `f3874456`

- flake.lock
| [`efc44208`](https://github.com/nix-community/nix-index-database/commit/efc44208d443ff8952d0d53e908360cbfd1a99c1) | `` flake.lock: Update `` |
> chore(flake/nix-index-database): `ebbc1c05` -> `efc44208`

- flake.lock
| [`f47c0edc`](https://github.com/nix-community/stylix/commit/f47c0edcf71e802378b1b7725fa57bb44fe85ee8) | `` treewide: remove Plasma 5 support dropped upstream (#1860) `` |
> chore(flake/stylix): `2355da45` -> `f47c0edc`

- flake.lock
| [`9c46d530`](https://github.com/lovesegfault/vim-config/commit/9c46d5307eaeb28812e8b8b0993f46db9d69bc25) | `` chore(flake/git-hooks): 3ff45966 -> e891a93b `` |
> chore(flake/lovesegfault-vim-config): `f3874456` -> `9c46d530`

- flake.lock
| [`65347abd`](https://github.com/lovesegfault/vim-config/commit/65347abdcfa742f21ee8b70ac5b7f8a982faa6d5) | `` chore(flake/nixvim): 91f51aed -> dae0629a `` |
> chore(flake/lovesegfault-vim-config): `9c46d530` -> `65347abd`

- flake.lock
- nix/dev-shell.nix
| [`c78c366c`](https://github.com/NixOS/nixpkgs/commit/c78c366c0b08bbd5a99ef60fa037c1b5f5d3c760) | `` rtklib-ex: init at 2.5.0 ``                                                      |
| [`0c28d57e`](https://github.com/NixOS/nixpkgs/commit/0c28d57e029f66e07a130481aea6cea3a1ca63ff) | `` service/portable: Add meta placeholder ``                                        |
| …
> chore(flake/nixpkgs): `fbcf476f` -> `20075955`

- flake.lock
| [`e21fc798`](https://github.com/lovesegfault/vim-config/commit/e21fc7989a3e65a452b33b959fd57113a4b42ac2) | `` chore(flake/nixpkgs): 20075955 -> 3b9f00d7 `` |
> chore(flake/lovesegfault-vim-config): `4eb76fa0` -> `e21fc798`

- flake.lock
| [`2c4ef7d7`](https://github.com/nix-community/home-manager/commit/2c4ef7d7172708f6247d2ed9b56f0341b9ce63e1) | `` blueman-applet: fix typo in systemdTargets ``     |
| [`3882f886`](https://github.com/nix-community/home-manager/commit/3882f88691147dc325feb6bfece09ab6d058fb67) | `` ssh: remove top level options ``                  |
| [`59aabcd3`](https://github.com/nix-community/home-manager/commit/59aabcd3db975f9ff7a5df918ad17284361723c0) | `` swaylock: …
> chore(flake/home-manager): `9e3a33c0` -> `2c4ef7d7`

- flake.lock
| [`3ad47823`](https://github.com/lovesegfault/vim-config/commit/3ad478237ed9c06d0821e5aec241ca73d841c1d1) | `` chore(flake/nixpkgs): 8a6d5427 -> dfb2f12e `` |
> chore(flake/lovesegfault-vim-config): `44e86fa5` -> `3ad47823`

- flake.lock
| [`99a69bdf`](https://github.com/nix-community/home-manager/commit/99a69bdf8a3c6bf038c4121e9c4b6e99706a187a) | `` pizauth: reload on change and option type `` |
> chore(flake/home-manager): `77a71380` -> `99a69bdf`

- flake.lock
| [`7ec84f50`](https://github.com/lovesegfault/vim-config/commit/7ec84f50ca32da6f5077284062277cc34bfd179d) | `` chore(flake/nixpkgs): dfb2f12e -> d7600c77 `` |
| [`9c0b4f2e`](https://github.com/lovesegfault/vim-config/commit/9c0b4f2e5c3f42eeab9bb8bf4678634c0f17e08b) | `` chore(flake/nixvim): b7e96214 -> 8bad4d40 ``  |
> chore(flake/lovesegfault-vim-config): `3ad47823` -> `7ec84f50`

- flake.lock
| [`b4b5f008`](https://github.com/nix-community/home-manager/commit/b4b5f008d772c0e8e9c420cfa0d240a447747e0a) | `` hyprpanel: deprecate `theme.name` option ``     |
| [`1e759786`](https://github.com/nix-community/home-manager/commit/1e759786e526a87a3c05beeff5db41743d763569) | `` qt: deprecate kde6 ``                           |
| [`f671e772`](https://github.com/nix-community/home-manager/commit/f671e772d3c3b893e44399afedb84a0b3f27f922) | `` qt: Remove Plasma 5 and …
> chore(flake/home-manager): `e4454907` -> `b4b5f008`

- flake.lock
| [`0409b7d4`](https://github.com/lovesegfault/vim-config/commit/0409b7d4911096014c822dd88bc239b5f4e0808e) | `` chore(flake/treefmt-nix): 74e1a52d -> 1aabc6c0 `` |
> chore(flake/lovesegfault-vim-config): `7ec84f50` -> `0409b7d4`

- flake.lock
| Commit                                                                                            | Message                        |
| ------------------------------------------------------------------------------------------------- | ------------------------------ |
| [`3dc09d55`](https://github.com/nix-community/nh/commit/3dc09d55a4cda052843b7b6cf9962e431cfdd48b) | `` build: bump dependencies `` |
> chore(flake/nh): `99b47b91` -> `5d53f2b8`

- flake.lock
| Commit                                                                                              | Message                                                            |
| --------------------------------------------------------------------------------------------------- | ------------------------------------------------------------------ |
| [`125ae9e3`](https://github.com/serokell/deploy-rs/commit/125ae9e3ecf62fb2c0fd4f2d894eb971f1ecaed2) | `` remove no longer necessary apple_sdk from buildInputs (#339) `` |
> chore(flake/deploy-rs): `6bc76b87` -> `125ae9e3`

- flake.lock
| [`a5c4f2ab`](https://github.com/nix-community/disko/commit/a5c4f2ab72e3d1ab43e3e65aa421c6f2bd2e12a1) | `` make-disk-image: use modules  output of a kernel if present `` |
> chore(flake/disko): `bafad29f` -> `a5c4f2ab`

- flake.lock
| [`29ab63bb`](https://github.com/nix-community/home-manager/commit/29ab63bbb3d9eee4a491f7ce701b189becd34068) | `` maintainers: update all-maintainers.nix `` |
> chore(flake/home-manager): `fccb44df` -> `29ab63bb`

- flake.lock
| [`4d6dadde`](https://github.com/lovesegfault/vim-config/commit/4d6dadde98c36ecb8d6d70bb558245329ae5a694) | `` chore(flake/flake-parts): af66ad14 -> 45242719 `` |
> chore(flake/lovesegfault-vim-config): `0409b7d4` -> `4d6dadde`

- flake.lock
| [`4106e724`](https://github.com/lovesegfault/vim-config/commit/4106e72494cca39abd79f9cc935d2076bc6bca83) | `` chore(flake/nixvim): 8bad4d40 -> f5026663 `` |
> chore(flake/lovesegfault-vim-config): `4d6dadde` -> `4106e724`

- flake.lock
| [`f3d3b459`](https://github.com/nix-community/home-manager/commit/f3d3b4592a73fb64b5423234c01985ea73976596) | `` news: add hyprland submap entry ``                   |
| [`06179315`](https://github.com/nix-community/home-manager/commit/061793150a092e24315d14ff9e06510889849e75) | `` tests/hyprland: add submap test ``                   |
| [`5f64bccc`](https://github.com/nix-community/home-manager/commit/5f64bcccef6d54a8fda5f70b29a3a423596c90ea) | `` …
> chore(flake/home-manager): `e31db614` -> `f3d3b459`

- flake.lock
| Commit                                                                                            | Message                                                               |
| ------------------------------------------------------------------------------------------------- | --------------------------------------------------------------------- |
| [`f28f52e0`](https://github.com/nix-community/nh/commit/f28f52e05855e6313cf5d6505585dc2de45f0b56) | `` gitignore: fix `gen*` pattern wrongly excludes `generations.rs` `` |
> chore(flake/nh): `5d53f2b8` -> `f3095b9f`

- flake.lock
| [`30fc1b53`](https://github.com/nix-community/home-manager/commit/30fc1b532645a21e157b6e33e3f8b4c154f86382) | `` nix-init: ensure settings example produces a valid configuration `` |
| [`a1316b0a`](https://github.com/nix-community/home-manager/commit/a1316b0a77ef3e082a75bc5dc685c249b3c25f2c) | `` new: add swappy entry ``                                            |
| …
> chore(flake/home-manager): `f3d3b459` -> `30fc1b53`

- flake.lock
| [`6159629d`](https://github.com/nix-community/home-manager/commit/6159629d05a0e92bb7fb7211e74106ae1d552401) | `` swayosd: Remove non-existing `display` arg option (#7752) `` |
> chore(flake/home-manager): `30fc1b53` -> `6159629d`

- flake.lock
| Commit                                                                                                | Message                                                                                                      |
| ----------------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------------------------------ |
| [`4091b501`](https://github.com/NixOS/nixos-hardware/commit/4091b501aa0953259197f588bb89019a506936f3) | `` Add HP ProBook 460 G11 to hardware table in /README.md ``                                                 |
| [`4a395855`](https://github.com/NixOS/nixos-hardware/commit/4a395855464bd8740cff5d6b3be5b5a57d5a5013) | `` Add HP ProBook 460 G11 `` …
> chore(flake/nixos-hardware): `47eb4856` -> `ba6fab29`

- flake.lock
| [`b08f8737`](https://github.com/nix-community/home-manager/commit/b08f8737776f10920c330657bee8b95834b7a70f) | `` hyprpanel: fix dontAssertNotificationDaemons (#7745) `` |
> chore(flake/home-manager): `ed1a98c3` -> `b08f8737`

- flake.lock
| [`3a891996`](https://github.com/lovesegfault/vim-config/commit/3a891996e5b35d420e568cc1066ea53443506fb9) | `` chore(flake/nixvim): f5026663 -> 63496f00 `` |
> chore(flake/lovesegfault-vim-config): `4106e724` -> `3a891996`

- flake.lock
| [`7e40faf5`](https://github.com/NixOS/nixos-hardware/commit/7e40faf569db5ecb30aa50a0df88fdd50fa74e6f) | `` fydetab/duo: enable hid sensor hub kernel module `` |
| [`295e0f92`](https://github.com/NixOS/nixos-hardware/commit/295e0f92ff26b8260c78d141a4ee1210816c9ede) | `` fydetab/duo: clarify graphics support ``            |
| [`410a1773`](https://github.com/NixOS/nixos-hardware/commit/410a17733a70b9c103e60684aa30fc8f3249e285) | `` fydetab/duo: fix himax firmware source …
> chore(flake/nixos-hardware): `af3dd1cb` -> `11b2a10c`

- flake.lock
| [`d3694390`](https://github.com/lovesegfault/vim-config/commit/d3694390dd0d022736375d5d53f3e865ddb88616) | `` chore(flake/nixvim): 63496f00 -> 4f80458d `` |
> chore(flake/lovesegfault-vim-config): `3a891996` -> `d3694390`

- flake.lock
| Commit                                                                                                | Message                                                       |
| ----------------------------------------------------------------------------------------------------- | ------------------------------------------------------------- |
| [`f6e9a1b6`](https://github.com/nix-community/stylix/commit/f6e9a1b62457efcbf48a09aafbf7233f306fcdc9) | `` ci: request-reviewers: do not request PR author (#1885) `` |
> chore(flake/stylix): `b1a84f89` -> `f6e9a1b6`

- flake.lock
| [`9991299f`](https://github.com/nix-community/stylix/commit/9991299fe9aad330fb6b96bb58def37033271177) | `` ci: bump actions/labeler from 5.0.0 to 6.0.1 (#1883) ``       |
| [`f544772a`](https://github.com/nix-community/stylix/commit/f544772a6064cc5dea7ab93b6551db868531d6ce) | `` ci: bump actions/github-script from 7.0.1 to 8.0.0 (#1882) `` |
| [`c1ac8e9b`](https://github.com/nix-community/stylix/commit/c1ac8e9b3f96648e065fead56c63d8023b89a47d) | …
> chore(flake/stylix): `f6e9a1b6` -> `9991299f`

- flake.lock
| [`b33c3aad`](https://github.com/nix-community/nix-index-database/commit/b33c3aadca9343dbbcba8be71cb741d095aab8a9) | `` flake.lock: Update `` |
> chore(flake/nix-index-database): `3fe768e1` -> `b33c3aad`

- flake.lock
| Commit                                                                                         | Message                                                                                      |
| ---------------------------------------------------------------------------------------------- | -------------------------------------------------------------------------------------------- |
| [`bc5f7c59`](https://github.com/NixOS/nixpkgs/commit/bc5f7c59a7b165138ae4474b7c78bc9b14480c41) | `` postgresqlPackages.pgvector: 0.8.0 -> 0.8.1 ``                                            |
| [`19ca3419`](https://github.com/NixOS/nixpkgs/commit/19ca34196837487bb77f9ba9fe1c62dcdd26dc1d) | `` python3Packages.vulcan-api: drop ``                                                       |
| …
> chore(flake/nixpkgs): `d7600c77` -> `8eb28adf`

- flake.lock
| [`39ae2a91`](https://github.com/lovesegfault/vim-config/commit/39ae2a91b214d81ec166aa9b166869e0acb22f08) | `` chore(flake/nixpkgs): d7600c77 -> 8eb28adf `` |
| [`59104fbe`](https://github.com/lovesegfault/vim-config/commit/59104fbe2a6eaf41e22096df0673d55bb5264466) | `` chore(flake/nixvim): 7afdd40b -> 2365afc0 ``  |
> chore(flake/lovesegfault-vim-config): `a725ee16` -> `39ae2a91`

- flake.lock
| [`d28026f1`](https://github.com/lovesegfault/vim-config/commit/d28026f17944d5db13466d46851f8cf93b6f809c) | `` chore(flake/nixvim): 2365afc0 -> d38eb947 `` |
> chore(flake/lovesegfault-vim-config): `39ae2a91` -> `d28026f1`

- flake.lock
| [`8df7ffa9`](https://github.com/NixOS/nixpkgs/commit/8df7ffa95306f788f36e1923cae90c25e76d0541) | `` ktailctl: 0.21.0 -> 0.21.1 ``                                                            |
| [`b9b0a40e`](https://github.com/NixOS/nixpkgs/commit/b9b0a40ec483e825a51e5c54b717f711fc71d4d2) | `` limine: 9.6.5 -> 9.6.6 ``                                                                |
| …
> chore(flake/nixpkgs): `8eb28adf` -> `b599843b`

- flake.lock
| Commit                                                                                                 | Message                      |
| ------------------------------------------------------------------------------------------------------ | ---------------------------- |
| [`55106a88`](https://github.com/nix-darwin/nix-darwin/commit/55106a887ecb0157159ae65a28764da477e47da6) | `` Fix typo in Nix module `` |
> chore(flake/darwin): `15f06763` -> `830b3f0b`

- flake.lock
| [`41580833`](https://github.com/lovesegfault/vim-config/commit/415808332c098d57bb047cd45b71eb7734cc8cd8) | `` chore(flake/nixvim): d38eb947 -> 51edc33c `` |
> chore(flake/lovesegfault-vim-config): `d28026f1` -> `41580833`

- flake.lock
| [`ecc09d19`](https://github.com/lovesegfault/vim-config/commit/ecc09d19b89cb2213c78392f5195abfdfd768947) | `` chore(flake/nixpkgs): 8eb28adf -> b599843b `` |
> chore(flake/lovesegfault-vim-config): `41580833` -> `ecc09d19`

- flake.lock
| Commit                                                                                                      | Message                                                                 |
| ----------------------------------------------------------------------------------------------------------- | ----------------------------------------------------------------------- |
| [`a60021a8`](https://github.com/nix-community/home-manager/commit/a60021a8c99bf5a28919c0a9fbb6b04422a6a8da) | `` pianobar: add module to create config file (#7734) ``                |
| [`ede1f891`](https://github.com/nix-community/home-manager/commit/ede1f891c01b948bdbdde507cffa1fc3497f329b) | `` Translate using Weblate (Polish) (#7797) ``                          |
| …
> chore(flake/home-manager): `d587e11c` -> `a60021a8`

- flake.lock
| [`146f45be`](https://github.com/nix-community/disko/commit/146f45bee02b8bd88812cfce6ffc0f933788875a) | `` feat: add flake-parts module `` |
> chore(flake/disko): `c8a0e78d` -> `146f45be`

- flake.lock
| [`6e28513c`](https://github.com/nix-community/home-manager/commit/6e28513cf2ee9a985c339fcef24d44f43d23456b) | `` nix-darwin: redirect output to stderr `` |
> chore(flake/home-manager): `a3fcc921` -> `6e28513c`

- flake.lock
| [`e286f848`](https://github.com/nix-community/home-manager/commit/e286f848a032a94b875af703f7b9ad77faf58b32) | `` lutris: add defaultWinePackage option (#7778) `` |
> chore(flake/home-manager): `6e28513c` -> `e286f848`

- flake.lock
| [`6f5ccfbd`](https://github.com/NixOS/nixpkgs/commit/6f5ccfbd8ead432e33d146a2e92a9e5ae65a1c32) | `` pscale: 0.255.0 -> 0.256.0 ``                                                |
| [`d41ab9d1`](https://github.com/NixOS/nixpkgs/commit/d41ab9d14b8d9a524dbc3fbb57dec3415915c8e1) | `` super-productivity: 14.4.1 -> 15.0.0 ``                                      |
| [`26446738`](https://github.com/NixOS/nixpkgs/commit/2644673811934d93e97db …
> chore(flake/nixpkgs): `ab0f3607` -> `c23193b9`

- flake.lock
| Commit                                                                                                      | Message                                                                                |
| ----------------------------------------------------------------------------------------------------------- | -------------------------------------------------------------------------------------- |
| [`17a10049`](https://github.com/nix-community/home-manager/commit/17a10049486f6698fca32097d8f52c0c895542b0) | `` lsd: allow specifying a path type value for `icons` and `colors` options (#7733) `` |
| [`c3abf8ea`](https://github.com/nix-community/home-manager/commit/c3abf8ea1adf8f601e993de64921bcf4f52b6358) | `` khard: support discover entries (#7785) `` …
> chore(flake/home-manager): `e286f848` -> `17a10049`

- flake.lock
| [`050a5feb`](https://github.com/nix-community/nix-index-database/commit/050a5feb5d1bb5b6e5fc04a7d3d816923a87c9ea) | `` update generated.nix to release 2025-09-14-032502 `` |
> chore(flake/nix-index-database): `80b92602` -> `050a5feb`

- flake.lock
| Commit                                                                                            | Message                                   |
| ------------------------------------------------------------------------------------------------- | ----------------------------------------- |
| [`df9fdd6a`](https://github.com/nix-community/nh/commit/df9fdd6ac3f8bf5ea6f241ec5bb44d1a36e70272) | `` search: update nixos-search version `` |
> chore(flake/nh): `a8182189` -> `8bf32348`

- flake.lock
| Commit                                                                                                | Message                    |
| ----------------------------------------------------------------------------------------------------- | -------------------------- |
| [`82e5fcb5`](https://github.com/NixOS/nixos-hardware/commit/82e5fcb58cf7d2b3f3bd2264a5acdc8816c38bf4) | `` Fix fydetab duo eval `` |
> chore(flake/nixos-hardware): `f89c620d` -> `4c38a024`

- flake.lock
| [`0632a5e1`](https://github.com/NixOS/nixos-hardware/commit/0632a5e10fa0d4a81a59e9b084d4dc898f0e26ba) | `` MacBookAir6,x: fix wireless `` |
> chore(flake/nixos-hardware): `4c38a024` -> `67a709cf`

- flake.lock
| Commit                                                                                                | Message                                      |
| ----------------------------------------------------------------------------------------------------- | -------------------------------------------- |
| [`d9d4a28c`](https://github.com/cachix/git-hooks.nix/commit/d9d4a28c7c5f24a5c0997a7c05b02a55b8e980f4) | `` lint ``                                   |
| [`222d5504`](https://github.com/cachix/git-hooks.nix/commit/222d5504823a26d320a59356d5a4a55ddb7a0654) | `` feat(convco): add option configPath ``    |
| [`6bd8ba28`](https://github.com/cachix/git-hooks.nix/commit/6bd8ba28a461c6b4f4339703663238596b1ac52d) | `` feat(alejandra): add option configPath `` |
| …
> chore(flake/git-hooks): `ff879b26` -> `d1d8fe5c`

- flake.lock
| Commit                                                                                                | Message                                                                       |
| ----------------------------------------------------------------------------------------------------- | ----------------------------------------------------------------------------- |
| [`0ce0103b`](https://github.com/nix-community/stylix/commit/0ce0103b498bb22f899ed8862d8d7f9503ed9cdb) | `` qutebrowser: fix border settings and add missing color settings (#1897) `` |
> chore(flake/stylix): `834a743c` -> `0ce0103b`

- flake.lock
| [`f9c8c3fa`](https://github.com/cachix/git-hooks.nix/commit/f9c8c3fab7fef6e7677cfb8e9b586e92e5fe0ac8) | `` feat: Add comrak formatter ``                       |
| [`3200f1fc`](https://github.com/cachix/git-hooks.nix/commit/3200f1fccb682e28860be8f9eccf73828d654bcb) | `` Do not pass filenames to ansible-lint by default `` |
> chore(flake/git-hooks): `d1d8fe5c` -> `302af509`

- flake.lock
| [`5820376b`](https://github.com/nix-community/home-manager/commit/5820376beb804de9acf07debaaff1ac84728b708) | `` news: add cudatext entry ``           |
| [`10d30c91`](https://github.com/nix-community/home-manager/commit/10d30c9185697d86477e1e539ca755403d7a3216) | `` cudatext: add module ``               |
| [`a88781a3`](https://github.com/nix-community/home-manager/commit/a88781a35cf9de9042396c4b84d2fae127b316b5) | `` sway: drop oxalica from maintainer `` |
> chore(flake/home-manager): `11cc5449` -> `5820376b`

- flake.lock
| [`c003edf0`](https://github.com/lovesegfault/vim-config/commit/c003edf0583de013bf2330e2372122ee1569d965) | `` chore(flake/nixvim): db1a991f -> 7f45eae6 `` |
> chore(flake/lovesegfault-vim-config): `0f7d076c` -> `c003edf0`

- flake.lock
| [`d507f57d`](https://github.com/nix-community/home-manager/commit/d507f57df23d067165f3d1a1dd5fb169b4f6bc37) | `` maintainers: update all-maintainers.nix (#7815) ``                  |
| [`fad8e303`](https://github.com/nix-community/home-manager/commit/fad8e3033e95d0a4595080e1efc8927b16ac18ed) | `` fontconfig: add fonts.fontconfig.extraConfigFiles option (#7754) `` |
| …
> chore(flake/home-manager): `5820376b` -> `d507f57d`

- flake.lock
| [`fb928abb`](https://github.com/nix-community/home-manager/commit/fb928abb67bd4df99040721ed48c3b42e24b1d08) | `` tests/claude-code: add path tests for agents/commands `` |
| [`846f27fb`](https://github.com/nix-community/home-manager/commit/846f27fba84839a93015c3378449edd255071e42) | `` claude-code: support paths for agents/commands ``        |
| [`10f5a0cc`](https://github.com/nix-community/home-manager/commit/10f5a0cc4b98c61298a8d130185a25032e9f …
> chore(flake/home-manager): `d507f57d` -> `fb928abb`

- flake.lock
| [`9f408dc5`](https://github.com/nix-community/home-manager/commit/9f408dc51c8e8216a94379e6356bdadbe8b4fef9) | `` ssh-tpm-agent: fix test case ``                               |
| [`5c14260f`](https://github.com/nix-community/home-manager/commit/5c14260fad23f9fda91a0dd74b1c58cf3be95221) | `` systemd: make unit definitions freeform modules ``            |
| [`12dfb0cf`](https://github.com/nix-community/home-manager/commit/12dfb0cff99865ea …
> chore(flake/home-manager): `fb928abb` -> `9f408dc5`

- flake.lock
| [`a504aee7`](https://github.com/nix-community/home-manager/commit/a504aee7d452ecf8881b933b1eb573535a543a03) | `` news: add formiko entry `` |
| [`9093a3f2`](https://github.com/nix-community/home-manager/commit/9093a3f2002298239de7f10bd8bcdd9652d6904e) | `` formiko: add module ``     |
> chore(flake/home-manager): `9f408dc5` -> `a504aee7`

- flake.lock
| [`6fb2178f`](https://github.com/lovesegfault/vim-config/commit/6fb2178f4921d9351b48fc0904cfe6ee13208b69) | `` chore(flake/nixpkgs): c23193b9 -> 8d4ddb19 ``     |
| [`01c51dd9`](https://github.com/lovesegfault/vim-config/commit/01c51dd9d8e90449c8035dab799d7980ed3c3f7a) | `` chore(flake/treefmt-nix): 1aabc6c0 -> 128222dc `` |
> chore(flake/lovesegfault-vim-config): `cd26c6de` -> `6fb2178f`

- flake.lock
| [`363007f1`](https://github.com/nix-community/home-manager/commit/363007f12930caf8b0ea59c0bf5be109c52ad0ef) | `` nushell: expose config dir location as option ``        |
| [`b47ea12f`](https://github.com/nix-community/home-manager/commit/b47ea12ff4442029c7016c13d5c55f86e10cbad3) | `` mise: statically generate nushell config ``             |
| [`3f47f72c`](https://github.com/nix-community/home-manager/commit/3f47f72c97ec23d117d9ce6ad15a42552cfce66d …
> chore(flake/home-manager): `b5698ed5` -> `363007f1`

- flake.lock
| Commit                                                                                               | Message                                                                     |
| ---------------------------------------------------------------------------------------------------- | --------------------------------------------------------------------------- |
| [`67ff9807`](https://github.com/nix-community/disko/commit/67ff9807dd148e704baadbd4fd783b54282ca627) | `` lib: fix `mdadm` warning when using `config.system.build.installTest` `` |
| [`ddef55ae`](https://github.com/nix-community/disko/commit/ddef55ae5fa1710b5c30afad1daf95f70331ba89) | `` Revert "flake.lock: Update" ``                                           |
> chore(flake/disko): `4f554162` -> `67ff9807`

- flake.lock
| [`edc7468e`](https://github.com/nix-community/home-manager/commit/edc7468e12be92e926847cb02418e649b02b59dd) | `` yazi: add extraPackages option for wrapper PATH extension `` |
| [`d5fb6ebc`](https://github.com/nix-community/home-manager/commit/d5fb6ebc4f7304f4485a8adb7258b1b65547a3f9) | `` Translate using Weblate (Basque) ``                          |
> chore(flake/home-manager): `55b1f5b7` -> `edc7468e`

- flake.lock
| Commit                                                                                                 | Message                                                                    |
| ------------------------------------------------------------------------------------------------------ | -------------------------------------------------------------------------- |
| [`5eb53f60`](https://github.com/nix-darwin/nix-darwin/commit/5eb53f6003acd69b30d4d06997eea711540ed0b6) | `` Add test for system.defaults.NSGlobalDomain.AppleIconAppearanceTheme `` |
| [`3c7396a0`](https://github.com/nix-darwin/nix-darwin/commit/3c7396a09cf0248c586eb0a10cf5df657e86eab6) | `` Add system.defaults.NSGlobalDomain.AppleIconAppearanceTheme ``          |
> chore(flake/darwin): `ebd0bfc1` -> `7be9c1b1`

- flake.lock
| [`690af26b`](https://github.com/lovesegfault/vim-config/commit/690af26b1c62cfcb11069d1e34f7d1d59f4aa775) | `` chore(flake/nixpkgs): 0147c2f1 -> 8eaee110 `` |
| [`c23ee54c`](https://github.com/lovesegfault/vim-config/commit/c23ee54caff30d39c24099aeccdbf6bdac188b7e) | `` chore(flake/nixvim): 0c867f9e -> fd0c4235 ``  |
> chore(flake/lovesegfault-vim-config): `9d07cec5` -> `690af26b`

- flake.lock
| [`1eae6fe0`](https://github.com/Mic92/nix-fast-build/commit/1eae6fe065eea833bbf6b4697140ae0291edf7fe) | `` Update flake input: treefmt-nix `` |
> chore(flake/nix-fast-build): `dad0194a` -> `862aa595`

- flake.lock
| [`3bcb1214`](https://github.com/nix-community/nix-index-database/commit/3bcb1214ddc6cf50bb82811f26650f09dc354982) | `` flake.lock: Update `` |
> chore(flake/nix-index-database): `050a5feb` -> `3bcb1214`

- flake.lock
| Commit                                                                                                 | Message                                                                               |
| ------------------------------------------------------------------------------------------------------ | ------------------------------------------------------------------------------------- |
| [`5206a9fd`](https://github.com/nix-darwin/nix-darwin/commit/5206a9fd30951ff80e83c7a4b250b30735c055f3) | `` Correct enum values for system.defaults.NSGlobalDomain.AppleIconAppearanceTheme `` |
> chore(flake/darwin): `7be9c1b1` -> `25381509`

- flake.lock
| [`939e91e1`](https://github.com/nix-community/home-manager/commit/939e91e1cff1f99736c5b02529658218ed819a2a) | `` news: add fabric-ai entry `` |
| [`61c84a3b`](https://github.com/nix-community/home-manager/commit/61c84a3bbfcf75953f0eeb150a68f54ca1aad964) | `` fabric: add module ``        |
| [`f3ff73a5`](https://github.com/nix-community/home-manager/commit/f3ff73a5e13b62b4bebc69849eac58913aa2fc3a) | `` news: add animdl entry ``    |
| [`20d75ecd`](https://github.com/nix-community/home-manager/commit/20 …
> chore(flake/home-manager): `edc7468e` -> `939e91e1`

- flake.lock
| [`c82dc82b`](https://github.com/lovesegfault/vim-config/commit/c82dc82b06de573e7100da943fecc055d8fe8546) | `` chore(flake/nixvim): fd0c4235 -> 92ba37a3 `` |
> chore(flake/lovesegfault-vim-config): `690af26b` -> `c82dc82b`

- flake.lock
| [`de536983`](https://github.com/nix-community/home-manager/commit/de5369834ff1f75246c46be89ef993392e961c26) | `` maintainers: update all-maintainers.nix `` |
> chore(flake/home-manager): `9b6e609a` -> `de536983`

- flake.lock
| [`18b3dfc8`](https://github.com/lovesegfault/vim-config/commit/18b3dfc815f5776819a229e9ab522e6fe53b357b) | `` chore(flake/nixvim): f828dead -> 0c15f88f ``  |
| [`151a840a`](https://github.com/lovesegfault/vim-config/commit/151a840a4b42c83c68fef451e10722c66cb615bb) | `` chore(flake/nixpkgs): 8eaee110 -> 554be649 `` |
> chore(flake/lovesegfault-vim-config): `9c7980ed` -> `18b3dfc8`

- flake.lock
| [`6ce2e180`](https://github.com/nix-community/home-manager/commit/6ce2e18007ff022db41d9cc042f8838e8c51ed66) | `` nix-your-shell: Allow using `nom` for `nix` commands ``  |
| [`cb68b5cd`](https://github.com/nix-community/home-manager/commit/cb68b5cd6a90325c05a9aa0cb27d8c1c98bc14ae) | `` syncthing: handle per-folder `encryptionPasswordFile` `` |
| [`ef376249`](https://github.com/nix-community/home-manager/commit/ef3762499bb1ecd542e236b5b073c3c9399f …
> chore(flake/home-manager): `676c0159` -> `6ce2e180`

- flake.lock
| Commit                                                                                               | Message                                |
| ---------------------------------------------------------------------------------------------------- | -------------------------------------- |
| [`5eda4ee8`](https://github.com/numtide/treefmt-nix/commit/5eda4ee8121f97b218f7cc73f5172098d458f1d1) | `` yapf: init yapf formatter (#409) `` |
> chore(flake/treefmt-nix): `128222dc` -> `5eda4ee8`

- flake.lock
| [`2e260431`](https://github.com/nix-community/home-manager/commit/2e260431fca7a782e0d0591985f2040944b43541) | `` news: add aiac entry `` |
| [`68a92b03`](https://github.com/nix-community/home-manager/commit/68a92b0301ac0a2d5ac2c60aadce6bc8460591b5) | `` aiac: add module ``     |
> chore(flake/home-manager): `142acd7a` -> `2e260431`

- flake.lock
| [`484819a1`](https://github.com/nix-community/stylix/commit/484819a16fdc1c76cdd62d8e94018db44e5e1a8b) | `` stylix/testbed/default: simplify attribute set declaration (#1906) `` |
| [`1284c189`](https://github.com/nix-community/stylix/commit/1284c1891b72c8670164eefe602300fe2d87f0cb) | `` lazygit: use consistent border colors (#1907) ``                      |
> chore(flake/stylix): `526c8828` -> `484819a1`

- flake.lock
| [`0a69cab7`](https://github.com/lovesegfault/vim-config/commit/0a69cab78dae6c5f1ccfcd72377a02eccb51f41d) | `` chore(flake/nixvim): 0c15f88f -> fd835f3d ``      |
| [`722f4192`](https://github.com/lovesegfault/vim-config/commit/722f4192b891d5af61d47ce9a174b759c808c823) | `` chore(flake/treefmt-nix): 128222dc -> 5eda4ee8 `` |
> chore(flake/lovesegfault-vim-config): `18b3dfc8` -> `0a69cab7`

- flake.lock
| [`23245405`](https://github.com/nix-community/home-manager/commit/232454052008027c8e925979d13a951e92729781) | `` syncthing: assert tray service content in test `` |
| [`ade85015`](https://github.com/nix-community/home-manager/commit/ade850153b41793e785e730f812b09302e9fd3b4) | `` syncthing: remove deprecated code ``              |
| [`74a78aac`](https://github.com/nix-community/home-manager/commit/74a78aacb7fe6b5d8fac79f9314abddbdaf07f09) | `` maintainers: …
> chore(flake/home-manager): `2e260431` -> `23245405`

- flake.lock
| [`b050aa00`](https://github.com/lovesegfault/vim-config/commit/b050aa006aa3db17ff72c5e68ee4d0258248d6ba) | `` chore(flake/nixvim): fd835f3d -> da7b983a `` |
> chore(flake/lovesegfault-vim-config): `0a69cab7` -> `b050aa00`

- flake.lock
| [`c1a47eae`](https://github.com/nix-community/home-manager/commit/c1a47eae05fb93788d3e3a7f1e63d7fc34d60c63) | `` desktoppr: init module (#7878) `` |
> chore(flake/home-manager): `39d26c16` -> `c1a47eae`

- flake.lock
| [`ef5c1426`](https://github.com/nix-community/home-manager/commit/ef5c1426bfb558f13cf0e585e1b2830ded87a970) | `` maintainers: update all-maintainers.nix ``            |
| [`f3235d91`](https://github.com/nix-community/home-manager/commit/f3235d91abedc9bcfdcbf1d7807b5bce94258884) | `` mods: get ipsavitsky from Nixpkgs maintainers list `` |
> chore(flake/home-manager): `c1a47eae` -> `ef5c1426`

- flake.lock
| [`6238bbc0`](https://github.com/nix-community/home-manager/commit/6238bbc0ae04951b64a3ad1b69d3e03b8b329e51) | `` tailscale-systray: add module (#7821) `` |
> chore(flake/home-manager): `173a29f7` -> `6238bbc0`

- flake.lock
| [`497e2bfa`](https://github.com/nix-community/home-manager/commit/497e2bfa8a45bebe9788e2aa13e766e6a96677cd) | `` news: add aichat agents option entry `` |
| [`e3e15e76`](https://github.com/nix-community/home-manager/commit/e3e15e765d164454db72ca30290c2d3a4917daf9) | `` aichat: add agents option ``            |
| [`35329d44`](https://github.com/nix-community/home-manager/commit/35329d44f3e3578fb33fc7e410c5b26a05fb1e53) | `` news: add aider-chat entry ``           |
| …
> chore(flake/home-manager): `6238bbc0` -> `497e2bfa`

- flake.lock
| [`3f20455c`](https://github.com/lovesegfault/vim-config/commit/3f20455c804c5464088f09284768c3cdb6971c28) | `` chore(flake/nixvim): da7b983a -> f68f9d14 `` |
> chore(flake/lovesegfault-vim-config): `3267c9c6` -> `3f20455c`

- flake.lock
| [`11cc3d55`](https://github.com/nix-community/home-manager/commit/11cc3d55ded3346a8195000ddeadde782a611e56) | `` macos-remap-keys: add NonUSBackslash keycode `` |
> chore(flake/home-manager): `bc2afee5` -> `11cc3d55`

- flake.lock
| Commit                                                                                                      | Message                                                                                  |
| ----------------------------------------------------------------------------------------------------------- | ---------------------------------------------------------------------------------------- |
| [`26ace005`](https://github.com/nix-community/home-manager/commit/26ace005b720b7628fdf2d4923e7feecdd1631c4) | `` tests/zsh: add comprehensive smart formatting test ``                                 |
| [`3aaf3401`](https://github.com/nix-community/home-manager/commit/3aaf340173d3151dd131f679b3bf419da5cd456b) | `` zsh: optimize setOptions with array-based loops `` …
> chore(flake/home-manager): `11cc3d55` -> `26ace005`

- flake.lock
| [`369da01b`](https://github.com/lovesegfault/vim-config/commit/369da01b8f7cc6c0cb0f8c06fc0bf90c042ae1b8) | `` chore(flake/nixvim): f68f9d14 -> 4cec6765 `` |
> chore(flake/lovesegfault-vim-config): `3f20455c` -> `369da01b`

- flake.lock
| [`dba023c4`](https://github.com/nix-community/nix-index-database/commit/dba023c457b6a7c826cd63397f5c6d6ff4d8b828) | `` flake.lock: Update `` |
> chore(flake/nix-index-database): `fd2569ca` -> `dba023c4`

- flake.lock
| [`677fa746`](https://github.com/Mic92/nix-fast-build/commit/677fa746d5745d924af3363e5039c927af269d17) | `` Update flake input: treefmt-nix `` |
> chore(flake/nix-fast-build): `862aa595` -> `bee1a2dc`

- flake.lock
| [`c75fd8e3`](https://github.com/nix-community/home-manager/commit/c75fd8e300b79502b8eecdacd8a426b12fadb460) | `` gurk-rs: remove references to deprecated 'data_path' option `` |
| [`1dbb3fd2`](https://github.com/nix-community/home-manager/commit/1dbb3fd2f79c804859e6b65fd42f164f7527ff39) | `` radio-active: add module to create config files ``             |
> chore(flake/home-manager): `26ace005` -> `c75fd8e3`

- flake.lock
| [`6ee84731`](https://github.com/nix-community/home-manager/commit/6ee8473173af7a0181a788e8a3d4fa164f4cc72c) | `` tests: improve debugging for failed test runs `` |
| [`e9114f96`](https://github.com/nix-community/home-manager/commit/e9114f96efc6e40ecf60e3db130c0a0ca88d1800) | `` tests: rename test-all-* tests ``                |
> chore(flake/home-manager): `a97df40c` -> `6ee84731`

- flake.lock
| [`619ae569`](https://github.com/nix-community/home-manager/commit/619ae569293b6427d23cce4854eb4f3c33af3eec) | `` news: add intelli-shell entry ``          |
| [`580ff74a`](https://github.com/nix-community/home-manager/commit/580ff74a7132af3228f7dd778a07083b3c338aeb) | `` intelli-shell: add module ``              |
| [`50375df1`](https://github.com/nix-community/home-manager/commit/50375df1f734f955a6b532bcc900c2588cddd3ab) | `` git-worktree-switcher: use cfg.package `` |
> chore(flake/home-manager): `6ee84731` -> `619ae569`

- flake.lock
| [`12fa8548`](https://github.com/nix-community/home-manager/commit/12fa8548feefa9a10266ba65152fd1a787cdde8f) | `` maintainers: update all-maintainers.nix `` |
> chore(flake/home-manager): `619ae569` -> `12fa8548`

- flake.lock
| [`5a21f481`](https://github.com/nix-community/home-manager/commit/5a21f4819ee1be645f46d6b255d49f4271ef6723) | `` fish: support theme plugins `` |
| [`dcf52ade`](https://github.com/nix-community/home-manager/commit/dcf52ade95a79eb2a02aa9e80ae6763aa1ee610d) | `` news: add aliae entry ``       |
| [`10bcab77`](https://github.com/nix-community/home-manager/commit/10bcab77af34616244a2eca5dde5d15dcd37151c) | `` aliae: add module ``           |
| …
> chore(flake/home-manager): `9e0453a9` -> `5a21f481`

- flake.lock
- flake.nix
- nix/overlay.nix
- users/bemeurer/core/neovim.nix
- users/bemeurer/music/default.nix
| [`ee239adf`](https://github.com/NixOS/nixpkgs/commit/ee239adf013686e672a7d1f50b96e9a7fed59781) | `` python3Packages.guidance: 0.2.5 -> 0.3.0 ``                                |
| [`a4ebe2ee`](https://github.com/NixOS/nixpkgs/commit/a4ebe2ee6fc371e287b4a198b4a6bec011eb581d) | `` python313Packages.python-fx: disable failing tests ``                      |
| [`1f270079`](https://github.com/NixOS/nixpkgs/commit/1f270079cfcd4672c6e23ec4c1920 …
> chore(flake/nixpkgs): `0147c2f1` -> `e9f00bd8`

- flake.lock
| Commit                                                                                                      | Message                                                                 |
| ----------------------------------------------------------------------------------------------------------- | ----------------------------------------------------------------------- |
| [`004753ae`](https://github.com/nix-community/home-manager/commit/004753ae6b04c4b18aa07192c1106800aaacf6c3) | `` home-manager: add backup overwrite option ``                         |
| [`7500458e`](https://github.com/nix-community/home-manager/commit/7500458e853e17bb1a03f0142d24069ba02ad0f5) | `` files: improve collision error message formatting for readability `` |
| …
> chore(flake/home-manager): `5890176f` -> `004753ae`

- flake.lock
| [`3f8246db`](https://github.com/lovesegfault/vim-config/commit/3f8246db2f11cc7f4f330eee3b06b1e1e49dbe57) | `` chore(flake/nixpkgs): e9f00bd8 -> 7df7ff7d `` |
| [`e6e78e0a`](https://github.com/lovesegfault/vim-config/commit/e6e78e0ac2f9c1755a9bb41805df0e8dc4fb215b) | `` chore(flake/nixvim): fc779c6e -> eb54f65d ``  |
> chore(flake/lovesegfault-vim-config): `3a84d5da` -> `3f8246db`

- flake.lock
| [`bd92e8ee`](https://github.com/nix-community/home-manager/commit/bd92e8ee4a6031ca3dd836c91dc41c13fca1e533) | `` asciinema: Add module to configure package `` |
| [`dd2b0f74`](https://github.com/nix-community/home-manager/commit/dd2b0f74920541d5dc3a5f4e1a12a19e77f5eacc) | `` news: add alistral entry ``                   |
| [`6bbfe2d6`](https://github.com/nix-community/home-manager/commit/6bbfe2d6973fb16137d3ef5e322b4591c22948b1) | `` alistral: add module `` …
> chore(flake/home-manager): `004753ae` -> `bd92e8ee`

- flake.lock
| [`0257a0aa`](https://github.com/NixOS/nixos-hardware/commit/0257a0aa583f73e3d3abff60789a598b31ce9276) | `` Add missing README entries and re-align columns `` |
> chore(flake/nixos-hardware): `e087756c` -> `3441b524`

- flake.lock
| [`1fba70d3`](https://github.com/Mic92/nix-fast-build/commit/1fba70d3cb4085ce53cb2f83cd2b3102aeafa207) | `` Update flake input: flake-parts `` |
> chore(flake/nix-fast-build): `bee1a2dc` -> `c76c21dc`

- flake.lock
| [`b7d515fd`](https://github.com/nix-community/nix-index-database/commit/b7d515fdd507be90afe806cb8b3e7130e7c4104b) | `` flake.lock: Update `` |
> chore(flake/nix-index-database): `ec7a78cb` -> `b7d515fd`

- flake.lock
| Commit                                                                                                | Message                                                       |
| ----------------------------------------------------------------------------------------------------- | ------------------------------------------------------------- |
| [`09022804`](https://github.com/nix-community/stylix/commit/09022804b2bcd217f3a41a644d26b23d30375d12) | `` hyprpanel: more granularly split configElements (#1931) `` |
> chore(flake/stylix): `503d9896` -> `09022804`

- flake.lock
| [`6f4021da`](https://github.com/nix-community/home-manager/commit/6f4021da5d2bb5ea7cb782ff413ecb7062066820) | `` deprecations: move just module deprecation to new module `` |
| [`3f07ce05`](https://github.com/nix-community/home-manager/commit/3f07ce05c3b6d59602bc380e42320483081fa38f) | `` deprecations: add deprecations/removal module ``            |
> chore(flake/home-manager): `5b45dcf4` -> `6f4021da`

- flake.lock
| [`6c5025e2`](https://github.com/nix-community/home-manager/commit/6c5025e2bb117eb16c0aa55097ce69935f72e14c) | `` tests/dircolors: add nushell integration tests `` |
| [`38fbd890`](https://github.com/nix-community/home-manager/commit/38fbd8909e6d4a8a36fda318c5feb8704da178d1) | `` dircolors: add nushell integration ``             |
| [`462363e2`](https://github.com/nix-community/home-manager/commit/462363e248b0a2e8579a904a9991a86206ca98e8) | `` dircolors: …
> chore(flake/home-manager): `929535c3` -> `6c5025e2`
